### ISSUE TITLE
Preferred place for global DB connections e.t.c?

### ISSUE THREAD

**Issue by kokujin** [hapijs/hapi#1025]
Where is the preferred place to initialize a global DB connection? As an example, I would like to open a mongoDb connection that would be used in all my routes:

var Hapi = require('hapi');
var conf = require('./conf');
var routesGeneric = require('./routes/generic');
var mongoose = require('mongoose');
var db = mongoose.createConnection('localhost', 'test');
db.on('error', console.error.bind(console, 'connection error:'));

The routes in turn inport handlers:
var users = require('../handlers/users');

Thanks

**Comment by pierre-b** [comment]
Here is how to easily handle it using `server.decorate()`:

```javascript
Mongo.MongoClient.connect(config.mongo_url, function(error, db) {
  if(error) { 
    server.log('error', error);
    process.exit(0); 
    return; 
  }

  server.decorate('request', 'getMongo', function () {
    return db;
  });

  server.start(function () {
    server.log('info', 'Server running on port: ' + port);
  });
});
```
