### ISSUE TITLE
run on heroku error

### ISSUE THREAD

**Issue by jamalsoueidan** [hapijs/hapi#1043]
Hello,

I'm trying to run simple application on heroku, but it throws error, and I cannot figure out what the problem is.

``` javascript
var port = process.env.PORT || 80;
var Server = Hapi.createServer('localhost', port);
```

Error:
/restful_api/node_modules/hapi/node_modules/hoek/lib/index.js:382
throw new Error(msgs.join(' ') || 'Unknown error');

Error: Bad server constructor arguments: duplicated arg type: string (values: `localhost`, `5000`)

Here is a working express app from heroku.

``` javascript
var express = require("express");
var app = express();
app.use(express.logger());

app.get('/', function(request, response) {
  response.send('Hello World!');
});

var port = process.env.PORT || 5000;
app.listen(port, function() {
  console.log("Listening on " + port);
});
```

What do you think the problem is?

https://devcenter.heroku.com/articles/nodejs

**Comment by adrianblynch** [comment]
@jamalsoueidan - Did you solve the issue? I'm facing something similar at the moment.

**Comment by MrwanBaghdad** [comment]
I found this to be working `server.connection({port : process.env.PORT ||3000 }) `

**Comment by saru2020** [comment]
## Worked!
`app.listen(process.env.PORT || 5000);`
