### ISSUE TITLE
Plugins inter-communication

### ISSUE THREAD

**Issue by swayf** [hapijs/hapi#1052]
Let say, one plugin declares dependency on another plugin and needs to access to the API of this another plugin. As far as I understand it is not possible during registration? Right now, it is possible only on requests (through request.plugins or request.server.plugins).

Is it good idea, to make it somehow possible during register phase?

**Comment by sitamet** [comment]
This hapi-intercom plugin
https://www.npmjs.com/package/hapi-intercom
is a better solution based on events
