### ISSUE TITLE
get array variable with querystring 

### ISSUE THREAD

**Issue by idanwe** [hapijs/hapi#1062]
I would like to add this kind of route:

``` javascript
server.addRoute({
    method : 'GET',
    path : '/users',
    validate: {
        query: {
            roles: Hapi.types.Array().optional()
        }
    config : { 
        handler: getUsers
     }
});
```

It's optional to add roles to the query string.
Request without role works ok:
`http://localhost:8080/users`
Request with several roles works ok too:
`http://localhost:8080/users?roles=admin&roles=user`
But, when the request is only with 1 role the validation failed and I get badRequest error
`http://localhost:8080/users?roles=admin`

How can I create this kind of route with Hapi validation

**Comment by felipekm** [comment]
+1 But this kind of validation isn't documented

**Comment by Marsup** [comment]
It is documented in the validation module, see [this](https://github.com/hapijs/joi/blob/master/API.md#compileschema) part of the docs.
