### ISSUE TITLE
DefinitelyTyped hapi.d.ts

### ISSUE THREAD

**Issue by srlopez** [hapijs/hapi#1080]
Hapi is a must in https://github.com/borisyankov/DefinitelyTyped
The database for DefinitelyTyped libraries for TypeScript (Just a nice tool to make better JS)

This will make most popular this fabulous framework.

Please...

**Comment by AJamesPhillips** [comment]
@cjmarshall, @srlopez, @eglizzy I'm debating typing v16.1.  Any interest in reviewing / helping?

**Comment by vidur149** [comment]
@AJamesPhillips need add typings for `server.views`. Can i contribute in any way?

**Comment by AdriVanHoudt** [comment]
if there is a PR we would be hapi to review

**Comment by AJamesPhillips** [comment]
Thanks @AdriVanHoudt  :)   @vidur149 `server.views` is part of vision and [the typings are here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vision/index.d.ts)

**Comment by vidur149** [comment]
@AJamesPhillips thanks for the quick reply.
