### ISSUE TITLE
Validating a query parameter of "enum" type

### ISSUE THREAD

**Issue by carlandreaslarsson** [hapijs/hapi#1100]
Hello,

based on 'hapi/examples/validation' I try to set up validation of an optional query parameter that shall be allowed to take on one or more of a set of defined values, similar to an "enum" type. However, trying the following configuration and requests result in a an error saying {"code":400,"error":"Bad Request","message":"the value of state must be an Array". Same thing goes for using 'state: hapi.types.Array()' only. Any clue?

Configuration:
...
    validate: {
        path: {
            id: hapi.types.String().required()
        },
        query: {
            color: hapi.types.Array().includes(hapi.types.String().valid('red'
, 'blue', 'yellow'))
        }
    }
...

Test requests:
curl --request GET http://localhost:8080/test/5251c?color=red
curl --request GET http://localhost:8080/test/5251c?color=red&color=blue

**Comment by joscha** [comment]
For newer versions of hapi, the way to go is: `Joi.string().allow('red', 'blue', 'yellow')`.

**Comment by ConAntonakos** [comment]
Just to add to what you wrote, @joscha. Based on the docs: "Note that this whitelist of allowed values is _in addition_ to any other permitted values. To create an exclusive whitelist of values, see any.valid(value)."

For an _exclusive whitelist_, `Joi.string().valid('red', 'blue', 'yellow')` should still be the way.

**Comment by l2silver** [comment]
For anyone who needs to load an array, valid requires the this context to be set to the joi object.
