### ISSUE TITLE
How do I support CORS preflight check in HAPI?

### ISSUE THREAD

**Issue by shaunlimjin** [hapijs/hapi#1106]
Hi,

I've noticed that my client app is making a preflight CORS OPTIONS check before making an AJAX call. Is there a way to configure HAPI to support such a request?

Currently, my server options are as follows:

``` javascript
var options = {
    cors: {
        additionalHeaders: ['X-Requested-With']
    },
    tls: {
        key: fs.readFileSync('ssl/server.key'),
        cert: fs.readFileSync('ssl/server.crt')
    }
};
```

Thanks,
Shaun

**Comment by Miscellaneous** [comment]
link broken
