### ISSUE TITLE
Plugin for Role Base Access Control (RBAC)

### ISSUE THREAD

**Issue by abernardobr** [hapijs/hapi#1181]
Is there any plugin to implement RBAC with HAPI routes? If not, what would be the best practive to implement RBAC in the processing workfow of a HAPI route, just like authorization works.

Regards,

Augusto Pissarra

**Comment by franciscogouveia** [comment]
If somebody is still interested in RBAC plugin, this might be useful: https://www.npmjs.com/package/hapi-rbac

**Comment by VitoVan** [comment]
Caution:

hapi-rbac: A **Rule** Based Access Control module for hapi.

NOT: **Role** Base Access Control
