### ISSUE TITLE
Temporary routes or a way to remove a route

### ISSUE THREAD

**Issue by qzg** [hapijs/hapi#1184]
Is there a way that I could (at runtime) define and later delete a route?

My reasoning for wanting to do this is more about the handler and its scope than the route itself.  I have a socket connection to a client and need to have a server-to-server request-response conversation on the client's behalf (Twilio, driving a phone call).  I need some of the data which is in the client's session and I want to be able to update the client's UI synchronized with what is happening on their phone (without polling some shared data).  

My thought was that I could define the necessary routes and handlers at runtime within the context of the client's socket session and drive the request-response conversation there.  The problem is that the router would then have a pointer to a function and closure scope which needs to go away at some point.  I just need to clean it all up.  

I know that I can define a route with named parameters, one of which I could use to look up the client's data or session or whatever - and this is basically what I'm going to end up doing for now.  I'm still curious to know if there is a way to do it the other way.  

Thanks!

**Comment by KeKs0r** [comment]
I was coming across the same requirement, I am trying to build a modular plugin system, where some routes might extend others. Since I registering all my routes on plugin registration I might need to update my routes. Either by replacing existing ones with updated Versions or by removing and re-adding them.

This would be done before my server is started. So its not actually during runtime. Would there be an option to allow this kind of update?

I tried to hack around it, but I can't figure out a good way to do it.

**Comment by hueniverse** [comment]
You really should not mess with a route once added. Sounds like poor design choices to me.

**Comment by alexindigo** [comment]
My use case is to extend existing server (with routes), I couldn't modify original routes, so I'm trying to override existing one with my custom handlers, before server started. Any advice will be appreciated. Thank you.

**Comment by simon-p-r** [comment]
I wrote a start-up routine that loads core routes via server.route method and then all additional routes are loaded via plugins and the server.register method.

**Comment by alexindigo** [comment]
Thank you, I'll check out `server.register`.

**Comment by simon-p-r** [comment]
This module https://github.com/troygoode/node-require-directory/ builds a object of required modules which could be used to add to server.route.

**Comment by alexindigo** [comment]
It's not a problem to require the new handler, but overriding existing routes is the major PITA. :)

**Comment by jdarling** [comment]
So this has come up enough times for me that I wrote a plugin to do just this.  As the notes say, there are edge cases with this approach, but it does work.  It only supports basic routes for right now but it will support more in the near future.

https://github.com/scythrops/malkoha

**Comment by devinivy** [comment]
@jdarling cool, and nice to see call used in there!  For the sake of providing options, Eran has a similarish project that _could_ be used this way too: https://github.com/hueniverse/lobotomy

**Comment by jdarling** [comment]
Yeah I started to use lobotomy, but unfortunately it doesn't support "delete", manual expire, or updating once you have set.  So I basically had to write my own.

**Comment by devinivy** [comment]
You could set the response to `Boom.notFound()` for a route and get a similar effect.
