### ISSUE TITLE
Allow 'domain' option in cookie authentication scheme config

### ISSUE THREAD

**Issue by iotaweb** [hapijs/hapi#1294]
I would like to share session cookies between my API and web server running on different subdomains. But to do this, I need to set a common domain for the cookie, e.g. `.example.com`

This is not currently supported, but I can get around this by adding the following to `/hapi/lib/auth/cookie.js`

```
    if (this.settings.ttl) {
        cookieOptions.ttl = this.settings.ttl;
    }

    if (this.settings.domain) {
        cookieOptions.domain = this.settings.domain;
    }

    server.state(this.settings.cookie, cookieOptions);
```

This is working for me, but am not sure if this is a god thing so am curious to know your thoughts, e.g. was it excluded for security reasons? I note `server.state` supports a `domain` config option.

**Comment by kellyrmilligan** [comment]
I know this is old, but is it possible to set the cookie with the . in front with server.state?  it does not seem to be working for me.
