### ISSUE TITLE
Adding rate limiting

### ISSUE THREAD

**Issue by cl-aaron** [hapijs/hapi#1303]
Hi,
I'm trying to add rate limiting to Hapi via a plugin and there is something I could use help with. 

The issue is that the rate limiting needs to have access to the routing information. The most apparent way to get this is to use the servers _router.route function. The obvious problem with this that _router is probably intended to be private. If any plugin is to access route data I would think it should use the same routing function as the rest of the system.

What do you guys think?

**Comment by ilwebdifabio** [comment]
Hi,
sorry to bother you but I've also a problem.
Hi, there.
Please take a look at http://stackoverflow.com/questions/33450671/hapijs-ratelimiter-plugin-dont-trigger-get-method.
I don't understand why on earth the script doesn't enter in the limiter.get block.

Thanks in advance.

**Comment by ilwebdifabio** [comment]
I've worked it out setting up the redis connection
inside the plugin and not as option.
I don't really understand why on earth
it doesn't work with redis as option !
There is a simple first version.
