### ISSUE TITLE
Reverse Proxy clarification/example?

### ISSUE THREAD

**Issue by evengers** [hapijs/hapi#1307]
I can see that a proxy can be used to access an external url/REST api but how are user/passwords sent?  Is that though the headers somehow?

**Comment by johannesfasching** [comment]
Is it possible to use a standard handler, - a function, with does some stuff - and after it forward the request 1:1 like in the proxy-example like mentioned above? I'm using hapi 8.1.
Background is, that I move to another server, and for some time both are living parallel. So my clients have time for migration.
