### ISSUE TITLE
Validation - Allow other unused fields

### ISSUE THREAD

**Issue by mavdi** [hapijs/hapi#1308]
Here I set a few validation rules:

```
exports.post = {
  validate : {
    payload : {
      title : Hapi.types.String().required(),
      description : Hapi.types.String().required(),
      name : Hapi.types.String().required(),
      url : Hapi.types.String(),
      thumbnailUrl : Hapi.types.String()
    }
  },
  handler : function (request) {
    ...
  }
};

```

Currently I can either allow everything or just the fields in the validation. What if I don't mind what additional fields are passed in as long as the fields I want are supplied?

If anything other than these values gets passed by the client, the validation will fail. Is there a way to ask HAPI to ignore additional parameters in payload?

**Comment by jlouthan** [comment]
Know this is an old issue but I came across it when trying to solve the same thing. For future reference, I accomplished it by setting the route's validation.options.allowUnknown to true:
```
exports.post = {
  validate : {
    options: {
      allowUnknown: true
    },
    payload : {
      title : Hapi.types.String().required(),
      description : Hapi.types.String().required()
    }
  },
  handler : function (request) {
    ...
  }
};
```

**Comment by duro** [comment]
Is there any way to set this just for one particular validation type. For example, I want to allow unknown properties in my `headers`, but I want to **strip** them in my `payload`. Seems if I set the `validation.options.stripUnknown` property to `true` it starts to break things related to headers.

Here is the schema I tried, with no luck:

```
validate: {
  headers: Joi.object({
    'authorization': Joi.string().required()
  }).unknown(),
  payload: {
    folderName: Joi.string().required(),
    parent: Joi.number()
  },
  options: {
    stripUnknown: true
  }
}
```

**Comment by hueniverse** [comment]
Don't use the validation options at the `validate` level. Use the joi options to set it per source.
