### ISSUE TITLE
Cannot Parse form-encoded arrays

### ISSUE THREAD

**Issue by leore** [hapijs/hapi#1317]
I am sending this:

curl http://localhost:3000/test \
-d "test[foo]=Ukelele" \
-d "test[bar]=123"

Getting some crazy errors when I try to "request.payload". Looks like it is not getting parsed correctly.

{
    "------WebKitFormBoundaryhbKwt7XdcdFwx2vE\r\nContent-Disposition: form-data; name": "\"name\"\r\n\r\nhello\r\n------WebKitFormBoundaryhbKwt7XdcdFwx2vE--\r\n"
}

**Comment by red-0ne** [comment]
This feature got lost with commit c3aa9edd829648dbf6055ae1e11e30d2a002a568 any chance to get it back? Are PRs accepted?

**Comment by hueniverse** [comment]
@red-0ne what feature?

**Comment by red-0ne** [comment]
"Parsing field names with arrays on multipart content" which was covered in these two tests:
https://github.com/hapijs/hapi/commit/c3aa9edd829648dbf6055ae1e11e30d2a002a568#diff-f01e0f7ea59f37f9d2242c870abf7ff8L1556 and https://github.com/hapijs/hapi/commit/c3aa9edd829648dbf6055ae1e11e30d2a002a568#diff-f01e0f7ea59f37f9d2242c870abf7ff8L1584

**Comment by hueniverse** [comment]
This was removed when we got rid of qs. Look through the hapi release notes for info on how to add that back in your own deployment or open an issue in hapijs/discuss.

**Comment by red-0ne** [comment]
Ok, perfect
