### ISSUE TITLE
Documentation on deployment

### ISSUE THREAD

**Issue by mennopruijssers** [hapijs/hapi#1330]
Hi!

First of all: I recently started developing with hapi and I think it's great!
I'm wondering however if there's some kind of "optimal deployment" guide or something?
For example:
- is it possible with (for example) cluster to make use of a multicore setup?
- is it possible to do zero downtime deploys? (something Rails/unicorn suppors with the USR2+QUIT signals).

**Comment by joserochadocarmo** [comment]
Hi!!!! I think that's all you want:
http://www.sitepoint.com/how-to-create-a-node-js-cluster-for-speeding-up-your-apps/

**Comment by edimoldovan** [comment]
I like using pm2, worked worked well for me so far: https://github.com/Unitech/pm2
