### ISSUE TITLE
Calling hold() or header() on a reply(Hapi.error.badRequest()) is not working

### ISSUE THREAD

**Issue by thesillyhippo** [hapijs/hapi#1375]
``` javascript
var Hapi = require('hapi');
var server = Hapi.createServer('localhost', 8000, { cors: true });


var handler = function (request, reply) {
    var response = reply(Hapi.error.badRequest('Any message')).hold();
    header = response.header('Set-Cookie', request.state);

    response.send();
};

server.route({ method: '*', path: '/{p*}', handler: handler });

server.start();
```

---

The error I get when trying to access that page is TypeError: Object Error : Any Message has no method 'hold'

If I don't use hold and just chain the header method, I get the same error except method 'header'

**Comment by jokeyrhyme** [comment]
http://hapijs.com/api#reply-interface

> If the input is not an `Error` object, the method returns a `response` object which provides a set of methods to customize the response (e.g. HTTP status code, custom headers, etc.). If the input is an `Error` object, the method returns back the error wrapped in a `Boom` object.
