### ISSUE TITLE
Drop dtrace support

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#1473]
This feature is incomplete and unused. Will be replaced in the future with a new instrumentation API.

**Comment by jcollum-cambia** [comment]
I'm doing some evaluation of various API frameworks. Many include DTrace support out of the box. I'm curious what Hapi's preferred alternative is. All I see is epimetheus/prometheus.io is that the way to go?

**Comment by geek** [comment]
hapi has dtrace support through plugins. Here is one such plugin https://www.npmjs.com/package/hapi-dtrace
