### ISSUE TITLE
Native 405 support

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#1534]

**Comment by csrl** [comment]
It is really annoying to have to add routes for every method explicitly responding with a 405 just so we get proper status responses.

Are you against this feature, or just the proposed implementation?  Could we re-open this issue and look for a better implementation?

**Comment by hueniverse** [comment]
I generally find 405 to be a pointless status code. To implement it you have to check every 404 for potential 405 which means you have to go through the entire routing table. Even if you "precompile" this data, it is still an extra lookup on every 404.

It should be possible to implement this in a plugin. If you need built-in support in the router, I'm open to extra functionality in the call module.
