### ISSUE TITLE
View Partials Always Cached

### ISSUE THREAD

**Issue by uipoet** [hapijs/hapi#1564]
With the following views configuration...

``` javascript
views: {
  engines: {
    hb: 'handlebars'
  },
  path: path.resolve(__dirname, '../templates'),
  partialsPath: path.resolve(__dirname, '../templates/partials'),
  layout: 'index',
  isCached: false
}
```

... files in the templates directory are not cached. However, files in the templates/partials directory ignore isCached and always cache the file until server restart.

This problem exists with Hapi ^2.x.x. Won't be able to try later versions, until Travelogue works with latest Hapi.

**Comment by ugate** [comment]
:frowning: this would have been a nice feature

**Comment by smil2k** [comment]
Hi,

It would be good at least to mention this limitation in the docs. It would have saved me an hour of looking around...*

Tamas

ps. new to hapi/node etc...
