### ISSUE TITLE
trailing slash on routes

### ISSUE THREAD

**Issue by leore** [hapijs/hapi#1576]
I have a set of routes. When people goto /v1/addresses/ it does not direct to /v1/addresses. What is the best way to do this with hapi?

``` bash
module.exports = [
  {
    method: 'GET',
    path: '/v1/addresses',
    config: AddressesController.findAll
  }, {
    method: 'GET',
    path: '/v1/addresses/{id}',
    config: AddressesController.findById
  }, {
    method: 'POST',
    path: '/v1/addresses',
    config: AddressesController.create
  }
];
```

**Comment by hems** [comment]
i would say most people would want routes that finishes with / and routes that doesn't finish with / to behave the same?

as in, always remove it from the url and always declare the route without it?

**Comment by gergoerdosi** [comment]
@hems The router option has been added (`stripTrailingSlash`), see the documentation for more details: https://github.com/hapijs/hapi/blob/master/API.md#new-serveroptions

**Comment by hems** [comment]
@gergoerdosi works like a charm.

Thanks

:8ball:
