### ISSUE TITLE
multipart stream upload corrupting payload

### ISSUE THREAD

**Issue by michelle-becker** [hapijs/hapi#1580]
I noticed that if I stream a file from a multipart form, the resulting file upload is larger than the original, pretty much every time. The bigger the file, the bigger the discrepancy.

Here is what I am doing. As you can see I have set my payload config to parse:false, output:stream. 

https://gist.github.com/michelle-becker/11060563

**Comment by daslicht** [comment]
Does Parsing require the whole playload to be loaded in memory or does it parse on the fly  ?

**Comment by johnbrett** [comment]
Depends on the desired output @daslicht, info is in the route payload output options in the API docs: http://hapijs.com/api#route-options

In short:
 - data: buffered into memory
 - stream: payload available via Stream.Readable interface
 - file: the incoming payload is written to temporary file in the directory specified by the server's payload.uploads settings

**Comment by mtharrison** [comment]
With multipart and stream option it would have to buffer everything first though right. Otherwise how to expose the correct properties?

**Comment by johnbrett** [comment]
Right you are @mtharrison, apologies @daslicht!

**Comment by daslicht** [comment]
Anything fine, I just discovered Hapi and I am very pleased which was I see.
