### ISSUE TITLE
helpersPath doesnt work with jade templates

### ISSUE THREAD

**Issue by hochitom** [hapijs/hapi#1592]
when i define a a helpersPath i get undefined is not a function when requesting a page.

```
views: {
        path: __dirname + '/views',
        helpersPath: __dirname + '/helpers',
        partialsPath: __dirname + '/views/partials',
        engines: {
              jade: 'jade'
        },
        compileOptions: {
              pretty: true
        },
        isCached: false
}

```

i named my helper file test.js and exported a simple function

```
module.exports = function () {
      return 'hallo';
};
```

and in my template i called the function `test()`

i'm not quite sure if i made a mistake when implementing it, or if its an jade related issue.

**Comment by DmitryTsepelev** [comment]
@hochitom as far as I know hapi view helpers work with handlebars only

**Comment by bf** [comment]
Issue still persists with current Jade version :-(
