### ISSUE TITLE
Got hapi?

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#1613]
We are compiling a list of companies or products using hapi for a few reasons:
- **showcase logos** and user stories of successful hapi development for the new site
- create a private hapi **security notification list** for high risk alerts
- solicit **private feedback** about making hapi better
- potential hapi **developer event** in the coming months
- help companies to **hire** experienced hapi developers
- identify new hapi **core contributors** from other companies

What we need from you:
- Company name
- Product name or use case
- Is it in production or development?
- Contact information for further questions
- Contact information for security alerts
- Link to logo if we can showcase your company on the new site
- User quote (with attribution) about your hapi user experience (up to 300 characters)

Please reply to this thread if the information is public, or email eran@hammer.io.

**Comment by pandeysoni** [comment]
Company name: Cronj IT Technologies Pvt. Ltd.
Product name or use case: We use Hapi in Enterprise application
Is it in production or development?: Production.
Contact information for further questions: monu@cronj.com
Contact information for security alerts: monu@cronj.com
Link to logo if we can showcase your company on the new site:https://avatars2.githubusercontent.com/u/10220530?v=3&s=200
User quote (with attribution) about your hapi user experience (up to 300 characters): hapi gives you the right structure to give your code structure, it makes simple for any developer to understand and debug code, quickly develop even complex apis, with deep structural validation. The beauty of code comes from way routing and controllers are written.

**Comment by pandeysoni** [comment]
We created issue to add our company in hapi community. You can check link here: https://github.com/hapijs/hapijs.com/issues/157
Thanks in advance.

**Comment by maxprog** [comment]
**Company name:** JRB System (www.jrbsystem.com)
**Product name or use case**: Integrated Platform for Real Time Analysis Big Datas (AI = DeployR + Hapi.js + Big Data)
**Is it in production or development:** PRODUCTION, DEVELOPMENT
**Contact information for further questions:** info@jrbsystem.com
**Contact information for security alerts:** info@jrbsystem.com
**Link to logo if we can showcase your company on the new site:** http://jrbsystem.com/jrbsystem.png
**User quote (with attribution) about your hapi user experience:** 
Framework for Real-time (statistical) analytics Big Data 
**Details:**
Databases: NoSQL - MongoDB
Languages: R Language, JavaScript (V8 Engine)
Server: DeployR, (Hapi.js)
JavaScript Framework: Node.js(Hapi.js), Socket.IO, AngularJS
Node.js as a middlware running on http,https protocols with authorization process regardless to Operating System. Serving sending and storage huge parts of datas, real time analysis, 
Communication between Client<=>Node.js - Requests are submitted by the client application through the server application REST API. 
Communication between Node.js<=>DeployR - used DeployR javaScript libraries, CRUD operations of massive datas on MongoDB
Implemented Pagination of sending datas & RBroker functionality

**Comment by antony** [comment]
Company name: Vendigo Finance Ltd
Product name or use case: Offers a fast and easy way for merchants to offer their customers financing on home improvements, and allows customers a safe, affordable way to improve their home.
Is it in production or development? Production in Denmark and Finland
Contact information for further questions: antony.jones@vendigo.com
Contact information for security alerts: engineering@vendigo.com
Link to logo if we can showcase your company on the new site: ![logo](https://cloud.githubusercontent.com/assets/218949/21962188/9ebf92e8-db17-11e6-828d-c2c2e538336c.png)

User quote (with attribution) about your hapi user experience (up to 300 characters)

Hapi allows us to quickly build web-services using a complete, production tested framework, and enables us to do so with an easy to maintain, terse, logical syntax. Understandability of our codebase is significantly reduced in comparison to other frameworks, and the plugin system allows us to quickly break out parts of the system as we scale our development team. A broad community and availability of high-quality, tested plugins means that we don't find ourselves constantly re-inventing the wheel, and can get on with building out our business logic.

Details:

* Hapi for production apps, using MongoDB on MLab for document storage, Component based AngularJS for our client applications.
* Docker + Dockercloud for all environments, from development to production.
Full TDD / BDD / Agile approach for an ever changing business and high-quality software.
* Geb for functional / acceptance testing as no pure javascript solution can beat it for readability / maintenance of tests.
* Wordpress for our marketing site at vendigo.com

**Comment by hueniverse** [comment]
@antony open a PR in hapijs/hapijs.com

**Comment by antony** [comment]
Will do. Shall I also PR the link to this issue which I found on the
contributing page, maybe change it to talk about opening PRs?

**Comment by hueniverse** [comment]
@nlf ^^

**Comment by nlf** [comment]
@antony absolutely! pull requests to correct documentation are always welcome and appreciated

**Comment by ItsAsbreuk** [comment]
**Name**: Marco Asbreuk
**Product**: itsa-react-server: a React.js MVC framework for building server side renderable SPAs.
**Publication**: [medium.com](https://medium.com/@itsasbreuk/itsa-react-server-a-react-mvc-framework-d19efaa3077d)
**Url**: [https://itsaserver.io](https://itsaserver.io)

**Comment by AdriVanHoudt** [comment]
👋  hey @ItsAsbreuk you should do a PR like https://github.com/hapijs/hapijs.com/pull/501 to the hapijs website
Awesome that you are using hapi 🔥
