### ISSUE TITLE
Inject a server with plugin dependencies

### ISSUE THREAD

**Issue by fampinheiro** [hapijs/hapi#1647]
I have a plugin that depends on another, normal requirement I think. The problem that I face is present on the [docs](https://github.com/spumko/hapi/blob/master/docs/Reference.md#plugindependencydeps-after) for `plugin.dependency(deps, [after])`

>  after - an optional function called after all the specified dependencies have been registered and before the servers start. The function is only called if the pack servers are started

But I really need the dependencies to be resolved, any workaround for this?
Should I pass as options to the plugin to tell it to do it's job and assume the dependency is met?

**Comment by danieladams456** [comment]
I seem to be having the same issue.  I am running a hapi server on AWS Lambda/API Gateway and using `server.inject()` to invoke it.  Lout `/docs` route is not registered unless I call `server.start()`.

https://github.com/hapijs/lout/blob/master/lib/index.js#L63

https://hapijs.com/api#-serverdependencydependencies-after
> The `after` method is identical to setting a server extension point on `onPreStart`.

Is there a way to just trigger that extension point without `server.start()`, or was that what you were referring to earlier @hueniverse?  I don't need the HTTP listener, but I guess if I set it to localhost it's not going to hurt anything.

**Comment by devinivy** [comment]
Before "using" your server, whether for tests or some other reason, I would highly suggest calling `server.initialize()`, which will trigger `onPreStart`, enforce dependencies, start caches, but not cause your server to start listening.

**Comment by danieladams456** [comment]
After working on it for half a day, five minutes more Googling was all I needed. 😄 @devinivy mentioned `server.initialize()` over [here](https://github.com/hapijs/discuss/issues/154#issuecomment-137952386). Thanks!

**Comment by danieladams456** [comment]
...and I hadn't refreshed the Github issue to see your super-fast response @devinivy.  Thanks again!
