### ISSUE TITLE
Enable starting the server listener externally

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#1672]
Some environments expect the process to return a node HTTP server and call `listen()` on it outside the application. This provides a way to control the host and port of the application at the platform level.

The idea is to add new `server.init()` and `pack.init()` methods which will return the HTTP server reference and setup the `listening` event handler so that when it is started, the rest goes back to normal.

Questions:
1. What output should `pack.init()` return? An array of server references? A hash?
2. Should the `host` and `port` in the config be ignored? overwritten? Currently `server.info` is set with the actual state, but `server.host` and `server.port` are left unchanged.

/cc @reid

**Comment by 0x4139** [comment]
this means that passing a new listener should also work with a spdy server?

**Comment by hueniverse** [comment]
Should.
