### ISSUE TITLE
server.inject for multipart/form-data

### ISSUE THREAD

**Issue by yoitsro** [hapijs/hapi#1711]
`server.inject()` misinterprets payload objects containing both JSON data and buffer data. The buffer object is converted into a large array of integers, rather than kept as a buffer or binary data.

Background: I need to upload an image with some JSON data in the same request.

Here's the route's validation schema:

``` javascript
validate: {
  payload: {
      json: O({
        name: S().min(1).max(50).required(),
        filter: O().required()
    }).required(),
    image: Joi.binary()
}
```

This data can be retrieved in the handler function by referencing `request.payload.json` and `request.payload.image`. `request.payload.json` is a simple JSON object and `request.payload.image` is a buffer object.

The actual request from the browser has a content-type of `multipart/form-data` and looks like:

```
------WebKitFormBoundaryI8wGLTaJyPZAAnD5
Content-Disposition: form-data; name="json"; filename="blob"
Content-Type: application/json

{ "name": "Red stuff", "filter": { "colour": "red" }
------WebKitFormBoundaryI8wGLTaJyPZAAnD5
Content-Disposition: form-data; name="image"; filename="image.jpg"
Content-Type: image/jpeg

<BINARY IMAGE DATA>
------WebKitFormBoundaryI8wGLTaJyPZAAnD5--
```

This is interpreted correctly.

When using server.inject() as so:

``` javascript
var url = 'http://127.0.0.1/filters';
var method = 'POST';
var payload = {
    json: {
        name: 'Red stuff',
        filter: {
            colour: 'red'
        }
    },
    image: require('fs').readFileSync('image.jpg')
};

server.inject({url: url, method: method, payload: payload }, function(res) {
    console.log(res);
});
```

validation fails because the data is not binary data. When digging further, the received data is:

``` javascript
{
    json: {
        name: 'Red stuff',
        filter: {
            colour: 'red'
        }
    },
    image: [255,
        216,
        255,
        1,
        ...
    ]
}
```

**Comment by kirin-yuen** [comment]
@petermilan really need headers

**Comment by Pankaj-Sunal** [comment]
The following leaks were detected:@@any-promise/REGISTRATION
using above: 
streamToPromise(form).then(function(payload)

**Comment by kuryaki** [comment]
FYI you can use https://www.npmjs.com/package/get-stream snippet below to help any other soul with the same issue 

```javascript
const GetStream = require('get-stream');

const form = new FormData();
form.append('file', Fs.createReadStream(Path.join(__dirname, 'filename')));

const request = {
    method,
    url,
    headers: form.getHeaders()
};

request.payload = await GetStream(form);

const response = await internals.server.inject(request);
```
