### ISSUE TITLE
allow payload fields not in joi validate object on route

### ISSUE THREAD

**Issue by jerrybroughton** [hapijs/hapi#1737]
I have an endpoint in hapi that has a couple fields under validation.   It works great.

However, I have a need from the client to be able to send other fields which I don't care about, but NOT have them rejected with "Invalid request payload JSON format, just ignored and only validate the fields I have in validation object.

On route there is a config.validate.payload that accepts a boolean to not validate OR joi object, etc.. but it is one or the other

Is there some way I am missing to allow this behavior.

**Comment by cyberwombat** [comment]
How is this achieved in 8.x.x?  The validation field is throwing errors

**Comment by gergoerdosi** [comment]
You need to add it to the `routes` config:

```javascript
var server = new Hapi.Server();
server.connection({
    host: 'localhost',
    port: 8000,
    routes: {
        validate: {
            options: {
                stripUnknown: true
            }
        }
    }
});
```
