### ISSUE TITLE
Checking the "Accepts" Header

### ISSUE THREAD

**Issue by arb** [hapijs/hapi#1744]
Is there a configuration option or existing method to check an incoming requests's `Accepts` header before the handler is executed? If the `Accepts` header is asking for XML and the server only support, JSON, the server should send a 406 status code. 

There are a few different ways to solve this problem with the existing features and configurations (`pre`, `onPreHandler`, in the handler itself...). Is there a preferred way to check the `Accepts` header for these situations?

If not, would you be willing to entertain an `accepts` route config option?

**Comment by aredridel** [comment]
I so very need this :(
