### ISSUE TITLE
Route with specific pattern.

### ISSUE THREAD

**Issue by midnight-wonderer** [hapijs/hapi#1765]
Hello,
I want to add a route by specific pattern.
for example I want to route every request which path matching
/^\/range_[0-9]{4}_[0-9]{4}.js$/ (such as /range_0123_6789.js)
to a handler.
I can't use Joi to validate the input later because I want requests that doesn't match the regular expression to match other route.

Is there any way to do that with hapi?
Ideally, pass a boolean function as path parameter but something else that works with hapi. (regular expression is fine)

**Comment by torarnek** [comment]
We are writing a smart proxy in front of a Java-application, and the lack of regexp in paths is certainly an issue, as we get too broad matches and have to write "secondary" routing logic inside the services.

The Spring MVC framework has solved this by allowing a regexp as part of the parameter e.g. 
\company\{companyId:\\d+}

As for sorting and detecting conflicts in routes, I guess they have some kind of solution.

Please see URI Template Patterns with Regular Expressions:
http://docs.spring.io/spring/docs/current/spring-framework-reference/html/mvc.html#mvc-ann-requestmapping-uri-templates-regex

**Comment by hueniverse** [comment]
Still not going to add this feature.

**Comment by ChrisCinelli** [comment]
All other major frameworks have regex support. For example [Express](http://matthewgladney.com/blog/angular/using-regex-with-node-express-router/). There is usually no conflicts resolution and the routes matching is done going though all the defined ones in the order they are defined. 

Conflict resolution can be nice in development level but frankly I can remember only one time when I have a problem with it and it was an easy fix. Could you not just ignore the the regex routes for conflict resolution? You mention reordering. What is the purpose of that?

**Comment by hueniverse** [comment]
Regex routes are against the design principals of hapi. If you need regex routes I would suggest using another framework. In practice, a well designed system should not need it. Predictive routing is key in any large scale system. hapi ensures that the order in which you load routes will not matter as routes are matched in a predefined way. We can't do that with regex and I will not be making any special exceptions for it.
