### ISSUE TITLE
Reply view options

### ISSUE THREAD

**Issue by davidchase** [hapijs/hapi#1855]
Hi,
So I am trying to override or add the partialsPath from the `reply.view()` :

``` js
  reply.view('./basket/views/index', {
            basket: data
   }, {
           partialsPath: './client/src/basket/views/'
   });
```

But I get a handlebars error.

My config looks like this

``` js
 views: {
                engines: {
                    hbs: require('handlebars')
                },
                path: './client/src/',
                layoutPath: './client/src/common/',
                layout: true
            }
```

if i add `partialsPath: './client/src/basket/views/'` to the above `views` object it works
but I thought I could do it through the `reply.view` method

Any help is greatly appreciated

-David

**Comment by benkermode** [comment]
Hi @davidchase , I'm also trying to do this. Can you post your solution?
