### ISSUE TITLE
Throw error when trying to reply twice

### ISSUE THREAD

**Issue by jgallen23** [hapijs/hapi#1866]
I have a route where I'm returning an error early if some criteria isn't met.  All my tests were passing, but when I was manually testing, things were breaking.  It turned out that I had forgot to `return` my reply and after sending the error message, it continued through with the rest of my logic.  Since my tests were using server.inject, it just returned the error response, so my tests thought everything was working correctly.  It would be great if hapi threw an error when trying to call reply twice.  Here's some example code:

``` javascript
var Hapi = require('hapi');
var port = process.env.PORT || 8080;
var server = new Hapi.Server(port, '0.0.0.0', { debug: false });

server.route({
  path: '/',
  method: 'GET',
  handler: function(request, reply) {
    setTimeout(function() {
      reply('hi');
      setTimeout(function() {
        reply('there');
      }, 10);
    }, 20);
  }
});

server.start(function() {
  server.log(['server', 'info'], 'Hapi server started '+ server.info.uri);
});
```

**Comment by barbalex** [comment]
after updating to 8.0.0 this new error surfaced in my app
thanks for helping to eliminate dumb mistakes!
(and thanks for sharing this great tool)
