### ISSUE TITLE
Server method enhanced caching support

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#1948]
Server methods can be used as prerequisites and handlers. However, caching these methods is not possible if they return a stream or other non JSONifiable response.

The steps are to:
- enhance catbox to support caching of streams
- allow caching of delayed execution (e.g. method returns a stream, which is cached later after the stream is finished piping)
- link cache policy with the HTTP response (cache-control and warning headers)

This issue replaces #1237, #1243, #1250, #1263

**Comment by devinivy** [comment]
Any chance this will be added to the 9.0.0 milestone?

**Comment by hueniverse** [comment]
I am not actively working on this but I'm also not inclined to put a help wanted label on it because I am unlikely to like other people's implementation for this :-). But if someone wants to give it a go...

**Comment by mugli** [comment]
Any update on this?

**Comment by Autarc** [comment]
Second that, would also be interested for caching streams which are currently just piped through the `reply` interface. Its a while since the issue got created so it would be good to know from @hueniverse if there is is some progress or additional thoughts about an implementation.

**Comment by hueniverse** [comment]
It's a feature I want to add but have no time or need for at this point. If someone wants to give it a try, I'm open to it, but historically, I've been pretty hostile to other people's code when touching these areas of the framework. If you really want to do it, start with catbox.
