### ISSUE TITLE
Reciving JSON Data In a Post Request

### ISSUE THREAD

**Issue by fguler** [hapijs/hapi#1979]
Hello,
First of all I should say I'm a little bit new to Hapi and I'm playing around to learn its dynamics. My problem is that I'm simply trying to set a router that will receive json data from a SPA app. So in order to demonstrate that I'm using the router below. When I send data (simple name and age json object) via PostMan, reply(req.payload) returns me a string containing my values. However; if I want to read, for example, name property like this "req.payload.name" it is empty. In sum; I would like to receive json data from client and convert it to json object in my router. How can I do that?

``` js
server.route({
    method:"POST",
    path:"/test",
    config:{
        handler:function(req,reply){
            reply(req.payload);
        },
        payload:{
            output: 'data',
            parse:true
        }
    }
});
```

**Comment by varundbest** [comment]
@Anafartalar For anyone who comes after you, this should be a good start :- 
https://www.youtube.com/watch?v=2lprC0yYeFw
And you can have a read of this file :- 
https://github.com/paullang/hapi-post-example/blob/master/index.js

**Comment by Anafartalar** [comment]
Hey @varundbest thanks for sharing, good stuff. I also find the following series very useful.
[https://futurestud.io/tutorials/hapi-get-your-server-up-and-running](url)

**Comment by leotm** [comment]
Cheers for the links @Anafartalar .
@varundbest do you have up updated link? (I'm getting a 404)

**Comment by Anafartalar** [comment]
Hi @leotm, sorry my mistake I have updated the link.

**Comment by Sean-Bradley** [comment]
I had same problem, I fixed it by sending ajax post with contentType = application/json, and the data value stringified.

`$.ajax({

  type: "POST",
  url: serverUrl,
  dataType: "json",
  contentType: "application/json; charset=utf-8",
  data: JSON.stringify(data),
  success: function (response) {
    // success
  },
  error: function (e) {
    //error
  }
});`
