### ISSUE TITLE
Is it possible to dynamically change a path for a route at runtime

### ISSUE THREAD

**Issue by briandela** [hapijs/hapi#1983]
Prior to 6.9.0 we were using the private _parsePath method to dynamically modify a route based on some information in the database. 

Essentially, we have a route with a path like this: `/offers`. At application startup/runtime, a check of the database would determine if we need to have this path changed to something like `/{market}/offers`.

We were doing this in a plugin by determining which routes needed to have the path changes, then changing the `route.settings.path` value and calling `route._parsePath()`.

Is behaviour like this still possible in 6.9.0?

**Comment by jamesgibson14** [comment]
It is not a terrible idea, dynamic evaluation at runtime is a very powerful tool. Just as in every design, there are trade offs.
