### ISSUE TITLE
server.inject callback res.payload encoding issue

### ISSUE THREAD

**Issue by blakmatrix** [hapijs/hapi#1999]
Where is the encoding on `res.payload` set when using `server.inject`?
We use sequelize and return the data directly through our api, we have front end routes that use server.inject and then parse the `res.payload` (we did this to get around a sequilize issue on `res.result`)

Currently a character like `ó` ends up looking like `Ã³`, is there anyway to set it so res.payload returns the expected character?

Thanks

**Comment by icodeforlove** [comment]
@hueniverse I ran into the same issue and your suggestion worked wonderfully :)

```new Buffer(/*body*/, 'ascii').toString('utf8')```
