### ISSUE TITLE
Streaming response is not documented

### ISSUE THREAD

**Issue by antony** [hapijs/hapi#2013]
...and there is nothing about it on google.

The documentation points to a 'Stream' response variety, but that's where the documentation ends.

What I'd like to see is an example of, say, streaming the results of a large database query out to the browser. Piping from other streams seems to be there, but I can't seem to be able to build my own stream and pipe that.

**Comment by afiedler** [comment]
just a note on @srlm-io 's example:

I had to change `reply(outputStream)` to `reply(null, outputStream)` on my version of Hapi (10.0.1).

**Comment by mtharrison** [comment]
@afiedler that doesn't sound right, [it shouldn't make a difference](http://hapijs.com/api/10.0.1#reply-interface):

> Since an request can only have one response regardless if it is an error or success, the `reply()` method can only result in a single response value. This means that passing both an `err` and `result` will only use the `err`. There is no requirement for either `err` or `result` to be (or not) an `Error` object. The framework will simply use the first argument if present, otherwise the second. The method supports two arguments to be compatible with the common callback pattern of error first.

**Comment by afiedler** [comment]
Strange, it does for me. `reply(outputStream)` makes the handler return this response:
```
{"statusCode":400,"error":"Bad Request","message":"[object Object]"}
```

`reply('test')` returns this:
```
{"statusCode":400,"error":"Bad Request","message":"test"}
```

I've always just put a null in `reply` for the first argument of success responses to avoid this, but I am a relative hapi newbie, so I could be doing something else wrong.

I'm on node 5.1.0.

**Comment by gergoerdosi** [comment]
@afiedler: Can you show more of your code?

**Comment by fbandrey** [comment]
Guys what about v18?
