### ISSUE TITLE
Subsequent strategies aren't called when one fails and passes a message to Boom.unauthorized()

### ISSUE THREAD

**Issue by kamilwaheed** [hapijs/hapi#2081]
This is what I discovered:

– I have multiple authentication strategies on a route like this:

```
server.route({
  method: "GET",
  path: "/",
  handler: someHandlerFunc,
  config: {
    auth: {
      mode: "required",
      strategies: ["strategy1", strategy2"]
    }
  }
});
```

– When an authentication scheme calls `reply(Boom.unauthorized("Some error message", "Scheme"))`, the `isMissing` field is NOT set to true on the resulting error object returned by Boom.

– When an authentication scheme calls `reply(Boom.unauthorized(null, "Scheme"))`, the `isMissing` field IS set to true on the resulting error object returned by Boom.

– **hapi/lib/auth.js** checks the `isMissing` field of the Boom error object to decide whether to call subsequent strategies or not.

This is very confusing. Shouldn't **hapi/lib/auth.js** always call subsequent strategies when a strategy replies with a `Boom.unauthorized()` error object regardless of whether an error message was passed to Boom or not?

**Comment by SaintDako** [comment]
@hueniverse I'm not sure if this applies anymore, but can you clarify what a scheme not being present entails? I thought that Hapi threw an error for an auth scheme that isn't defined.

**Comment by hueniverse** [comment]
If credentials are present, they must be valid otherwise the request fails. If they are missing, the next type of credentials are tested.
