### ISSUE TITLE
Get parsed cookies in request

### ISSUE THREAD

**Issue by voronianski** [hapijs/hapi#2088]
Is there a way to get object cookie that was encoded?

Saving cookie:

``` javascript
var userData = {
    name: 'John',
    team: 'Arsenal'
};
reply.state('userData', userData, {encoding: 'base64json'});
```

Getting it:

``` javascript
{ userData: 'eyJ0SWQiOiJ0MyIsImxlYWd1ZUlkIjoiOCIsInRlYW0iOiJBcnNlbmFsIn0=' }
```

---

Also without passing `encoding` option I receive an error:

``` javascript
var userData = {
    name: 'John',
    team: 'Arsenal'
};
reply.state('userData', JSON.stringify(userData));
```

Error thrown:

``` bash
Debug: hapi, internal, implementation, error
    Error: Invalid cookie value: {"name":"John","team":"Arsenal"}
```

**Comment by ColorfulCow** [comment]
https://hapijs.com/api/15.2.0#serverstatename-options, this chapter said 'State defaults can be modified via the server connections.routes.state configuration option.',   is this document wrong? i can't set default state by using connections.routes.state, but `server.connections[0].states.settings.strictHeader = false` worked, my hapi version is 15.2.0
