### ISSUE TITLE
plugin.register.register

### ISSUE THREAD

**Issue by tcoopman** [hapijs/hapi#2259]
I'm currently testing 8.0.0rc8 and I get the following error:

```
if (plugin.register.register) {                             // Require
                           ^
TypeError: Cannot read property 'register' of undefined
    at internals.Plugin.register (c:\Workspace\www\viewer-login\node_modules\hapi\lib\plugin.js:201:28)
    at Object.<anonymous> (c:\Workspace\www\viewer-login\test.js:16:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

with this code:

``` js
'use strict';
var Hapi = require('hapi');

var server = new Hapi.Server();
server.connection({port: 3000});

var options = {
  opsInterval: 1000,
  reporters: [{
    reporter: require('good-console'),
    args:[{ log: '*', request: '*' }]
  }]
};


server.register({
  plugin: require('good'),
  options: options
}, function (err) {
  if (err) {
    console.log(err);
  } else {
    server.start(function () {
      server.log('info', 'Server running at: ' + server.info.uri);
    });
  }
});
```

And dependencies:

```
    "good": "^5.0.0-rc1",
    "good-console": "^3.0.0",
    "hapi": "^8.0.0-rc8",
```

Is some dependency not yet updated or am I missing something stupid?

**Comment by milkysingh** [comment]
I am having the same issue . Please help me out.
`const hapi=require('hapi');
const server=new hapi.Server();

//Add connection
server.connection({
    port:4500,
    host:'localhost'
});

//creating route

server.route({
    method:'GET',
    path:'/',
    handler:(req,reply)=>{
        reply('<h1>Sucessfully created first route</h1>');
    }
});

//dynamic route
server.route({
    method:'GET',
    path:'/user/{id}',
    handler:(req,reply)=>{
        reply(`<p>User : ${req.params.id}</p>`)
    }
})

//static route

server.register(require('inert'),(err)=>{
    if(err)throw err;
    server.route({
        method:'GET',
        path:'/about',
        handler:(req,reply)=>{
            reply.file('./public/index.html')
        }
    })
})

//Start connection
server.start().then(
    ()=>console.log(`Server is running at ${server.info.uri}`)
).catch(
    err=>{throw err} 
)
`

**Comment by alcfeoh** [comment]
The actual issue is that if you do exactly what is in the docs, then it does not work. You get this plugin.register.register issue.
The docs have to be fixed: https://hapijs.com/tutorials/serving-files?lang=en_US

**Comment by alcfeoh** [comment]
@tcoopman Could you provide your full snippet of code? What do you put in the register object?

**Comment by hueniverse** [comment]
Please move this discussion to hapijs/discuss. Also, you have to wait for register() to finish before you call start().
