### ISSUE TITLE
Support optional payload validation without parsing

### ISSUE THREAD

**Issue by chasdev** [hapijs/hapi#2260]
I would like your thoughts on the below before I submit a pull request for your consideration. 
#### My Problem

I need to proxy requests and wish to leverage 'hapi-swagger' to create an interactive documentation page. 

In order to support POST/PATCH/PUT through a Swagger UI, I need to "validate" the payload (in addition to the params) so the generated Swagger UI will expose an input box into which the payload can be populated. 

Currently, an assertion in hapi/lib/route.js requires the payload be parsed when validating the payload:

``` javascript
Hoek.assert(!this.settings.validate.payload || this.settings.payload.parse, 'Route payload must be set to \'parse\' when payload validation enabled:', options.method, options.path);
```

However, parsing the payload is not allowed when using the built-in proxy handler.  Specifically, h2o2/lib/index.js has the following assertion:

``` javascript
Hoek.assert(!route.payload || ((route.payload.output === 'data' || route.payload.output === 'stream') && !route.payload.parse), 'Cannot proxy if payload is parsed or if output is not stream or data');
```

I understand I can implement my own proxy handler versus using the built-in proxy handler, but the built-in proxy handler is very nice and otherwise satisfies my requirements.  
#### Proposed Resolution:

I am proposing (and can submit a pull request if acceptable) the following changes to allow payload validation without parsing, while not losing the benefit of having this assertion in place. 

In lib/schema.js:

```
218     payload: Joi.object({
219         output: Joi.string().valid('data', 'stream', 'file'),
220         parse: Joi.boolean().allow('gunzip'),
221         allowValidationWithoutParsing: Joi.boolean(), // <-- *** PROPOSED OPTION
222         allow: [
223             Joi.string(),
224             Joi.array()
225         ],
```

And in lib/route.js:

```
118     Hoek.assert(!this.settings.validate.payload || this.settings.payload.parse || this.settings.payload.allowValidationWithoutParsing, 'Route      payload must be set to \'parse\' when payload validation enabled:', options.method, options.path); // <-- *** PROPOSED MODIFIED ASSERTION
```

_(Note the above line numbers are based on my npm installed module and not a clone, so they are likely off a bit...)_

The above changes would then support the following configuration:

```
    {
      method: 'POST',
      path: '/api/{resourceName}',
      handler: handlers.post,
      config: {
        description: 'Creates a new instance of a resource.',
        notes: 'Creates a new instance of a resource within the authoritative source for that resource.',
        tags: ['api'],
        payload: { allowValidationWithoutParsing: true }, // <-- *** PROPOSED OPTION
        plugins: {
          'hapi-swagger': {
            responseMessages: httpErrors.modificationErrors
          }
        },
        validate: {
          params: urlWithoutIdValidation,
          payload: function (value, options, next) {
            if (value) {
              next(null, value);
            } else {
              next(Boom.badData('No content was posted'));
            }
          }
      }
    }

```

This configuration allows, albeit only with specific intent by specifying 'allowValidationWithoutParsing', the configuration of a payload validator function without having the payload parsed. With the above validator function in place, hapi-swagger is able to reflect the payload  within it's UI enabling interactive documentation for POST/PUT/PATCH. 

The above proposal is consistent with the design decision to not support parsing of the payload when using the built-in proxy handler.  _(The assertion referenced above that protects against this appears to have been introduced in commit https://github.com/hapijs/hapi/commit/8145ee9252e61b3fe330df0474d99ba167e0aa7b and this design decision has been validated in issues https://github.com/hapijs/hapi/issues/1561 and https://github.com/hapijs/hapi/issues/2062.)_   
#### Next Step

If my proposed solution (supporting the allowValidationWithoutParsing option) is acceptable, I can issue a pull request if helpful. (btw, I don't really like the overly long name but do think it may be warranted to make the configuration more self-documenting.)

I am certainly open to other alternatives.  Thoughts? 

Lastly, I have only been using Hapi for a few days and am really enjoying the experience. So, thank you for such an excellent framework.

Thanks for your consideration,
charlie

**Comment by fjsousa** [comment]
I have precisely the same issue as @chasdev. I need to create a swagger page for a API that acts basically as a proxy. I can't list the payload fields in swagger because I need validation and to enable validation I need to parse the payload, which I can't do when proxying. 

Do you have any suggestions?

**Comment by hueniverse** [comment]
@fjsousa so you want to specify validation for the sole purpose of documentations?

**Comment by fjsousa** [comment]
@hueniverse Not quite. I want to proxy an uri by specifying the proxy object in the handler property, and use payload validation. Currently you can't do that and the reason was explained by @chasdev. 

Now I'm just doing a request inside the handler as a workaround, but I would like to figure out a more elegant solution.

**Comment by Marsup** [comment]
@hueniverse FWIW it's been asked on lout (https://github.com/hapijs/lout/issues/40#issuecomment-97111778).
