### ISSUE TITLE
How to use caching

### ISSUE THREAD

**Issue by minustime** [hapijs/hapi#2296]
I can't seem to find an example of how to use the caching mechanisms in Hapi. I have a plugin that retrieves data from a remote API, what I'd like to do is add a caching layer to the plugin so it looks into its cache first before making the trip to the remote API for data.

I'm using: Hapi v8.0.0 with catbox-memcached v1.1.0. I'm passing in the `cache` options to the server and the app seems to be running correctly. I'm just not sure how to set/get data from within the plugin now.

Thanks for your help!

**Comment by hueniverse** [comment]
Which sample code?
