### ISSUE TITLE
Response validation with Joi. Rename doesn't work.

### ISSUE THREAD

**Issue by Gregy** [hapijs/hapi#2298]
I am trying to rename properties of response object with response validation but it doesn't work. Example:
```
var Hapi = require('hapi');
var Joi = require('joi');
var server = new Hapi.Server();
server.connection({ port: 3000 });

server.route({
    method: 'GET',
    path: '/test',
    handler: function (request, reply) {
        reply({test: 'this is test'});
    },
    config: {
      response: {
        schema: Joi.object().rename('test','test2').keys({test2: Joi.string()})
      }
    }
});

server.start(function () {
    console.log('Server running at:', server.info.uri);
});
```

Test route passes validation (no error). But the field in final response is called 'test' not 'test2' as I would expect.

P.S. Thank you for hapi, it makes me happy :+1:

**Comment by hueniverse** [comment]
You need to set the route `config.response.modify` setting to `true`.

**Comment by Gregy** [comment]
Thank you very much. I missed this :(

**Comment by bsiddiqui** [comment]
@hueniverse out of curiosity why does payload validation modify by default but response validation doesn't?

**Comment by hueniverse** [comment]
Because response validation is a really bad idea for anything other than testing.
