### ISSUE TITLE
can't reply with stream returned by node core http client methods

### ISSUE THREAD

**Issue by nlf** [hapijs/hapi#2301]
For example

```js
server.route({
  method: 'GET',
  path: '/',
  handler: function (request, reply) {
    reply(Http.get('http://google.com'));
  }
});
```

Will throw `TypeError: Cannot read property 'objectMode' of undefined` due to the fact that the http module has `_readableState` hidden behind a property. This also impacts `request` and `wreck`.

**Comment by jlit** [comment]
Still waiting on hapi 8.1.0

**Comment by kanongil** [comment]
@nlf You're using `Http.get` wrong. Actual fix can be found in #2382.

**Comment by hueniverse** [comment]
@kanongil Why is @nlf using it wrong?

**Comment by kanongil** [comment]
@hueniverse `Http.get` only creates a `Writable`stream for `POST`ing stuff, etc. You only read from the response.
