### ISSUE TITLE
Unable to set header in server.ext()

### ISSUE THREAD

**Issue by tomjnsn** [hapijs/hapi#2307]
I am trying to set a header in a server.ext() but it won't return.  Here's a short example:

``` javascript
server.ext('onPostHandler', function(request, reply) {
    reply().header('test-header', 'test value');
    reply.continue();
});
```

It never returns that header though.  I can get it to return in a route if I do something like:

``` javascript
reply({key: 'value'}).header('test-header', 'test value');
```

But I'm looking to have it set conditionally in the .ext() function.  From the docs it looks like I should be able to do this. Am I missing something or do I need to do this differently?

**Comment by kevinsimper** [comment]
@nif It does not seem to work anymore?

**Comment by tlhunter** [comment]
@kevinsimper Yeah, the information in this thread is no longer applicable.

**Comment by janl** [comment]
What is the solution now then? :)

**Comment by janl** [comment]
accessing `request.headers` directly seems to have done the trick.

**Comment by noose** [comment]
```js
if (request.response.header) {
    request.response.header('X-API-VERSION', 'v' + options.version);
}
```

it's good for me. Why that if? Because when I access swagger then it throw error.

**Comment by mtharrison** [comment]
The thread seems to have become several questions. @kevinsimper @tlhunter, what specifically isn't working for you anymore.

Some people are asking about setting a response header, @janl you seem to be asking about inspecting request headers.

This is still the way things work as of hapi 11.x.x:

```javascript
const Hapi = require('hapi');

const server = new Hapi.Server();
server.connection({ port: 4000 });

server.ext('onRequest', function (request, reply) {

    console.log(request.headers.accept);                     // accessing request header
    reply('My response').header('x-some-header', 'hello');   // setting a response with custom header
});

server.ext('onPreResponse', function (request, reply) {

    console.log(request.headers.accept);                    // accessing request header
    request.response.header('x-custom-header', 'value');    // setting another custom header
    reply.continue();
});

server.start(function () {
    console.log('Started server');
});
```
You can only call `request.response.header()` once an response has actually been set. Otherwise you set one and set a header `reply(value).header(key, value)`. Notice that they're actually the same thing though because `reply(value)` returns the response.

**Comment by janl** [comment]
Just for the record, my scenario was:

- `proxy` route
- `passThrough` option `true`
- `Authorization: header to authenticate at the proxy
- `proxy` + `passThrough` dutifully passed the `Authorization` header along
- proxy target didn’t like the `Authorisation` header

“works for me” solution:

```javascript
  server.ext({
    type: 'onPostAuth',
    method: function (request, reply) {
      delete request.headers['authorization']
      return reply.continue()
    }
  })
```
