### ISSUE TITLE
build-in directory handler cache header

### ISSUE THREAD

**Issue by salzhrani** [hapijs/hapi#2320]
When using the built-in directory handler how do you set the response headers? specifically the cache related ones.

**Comment by hueniverse** [comment]
You can either set the route cache config option or use a onPreResponse extension point to set the headers.

**Comment by salzhrani** [comment]
the route cache config adds the correct `max-age` but it also adds `must-revalidate` which I couldn't figure out how to opt-out of. is there a way to opt-out of it or should I just use `onPreResponse` ?

**Comment by hueniverse** [comment]
There is no way to opt out of it. If you have a use case, open a new issue.
