### ISSUE TITLE
Multiple handlers for the same route?

### ISSUE THREAD

**Issue by ide** [hapijs/hapi#2321]
I want to simulate the behavior of a normal PHP setup where .php and .html files can coexist, and the former are processed by the PHP interpreter (except in this case the extensions are .template and .html).

So with Hapi, I want to define two handlers for the same route: one that handles .template files and another that handles .html files. Additionally I'd like for the file extensions to be optional in the URLs. I've configured a view engine that can render .template files but am looking for the best way to proceed from here.

My first inclination was to write a custom handler for the route `/{path*}` that looks for `path` and `path.template` and renders the .template file, if found. If not, I wanted to fall back on the built-in directory handler. I wasn't able to do this by calling `server.route` with `/{path*}` twice ("Error: New route /{path*} conflicts with existing /{path*}").

Is this approach in the right direction or should I write one handler that combines all the logic (and is there a way to invoke the "directory" handler from within another handler?)?

**Comment by hueniverse** [comment]
First, this belongs in hapijs/discuss.

Second, there are many ways to implement this but the simplest would be to create two internal routes for each case, and then use the catch-all route you want to expose with `onRequest` and use `setPath()` to override the path to the internal routes based on the file extension.
