### ISSUE TITLE
How to test with crumb being allowed?

### ISSUE THREAD

**Issue by nagyv** [hapijs/hapi#2322]
Hi,

I've just started using hapi on a pet project, put together a boilerplate, then added hapi-auth-cookie, and tried to write my first test for it to see if I did right. Unfortunately, I didn't. Moreover, I can't figure out what I'm missing.

Here is my code http://github.com/nagyv/jalagati-admin-backend

I've already digged into the hapi docs and internals, and found the auth handling code, and as far as I could understand, my code should work as it uses the "try" auth mode. Still, my login handler is never called (at least, not in the test).

Could someone give a helping hand, please?

**Comment by smahi** [comment]
To test crumb being allowed set the headers in server.inject options like so
```js
let opts = {
        method: 'POST',
        url: '/api/some/path',
        payload: some_payload,
        headers: { cookie: `crumb=${crumb}`, 'x-csrf-token': crumb } // crumb is a variable that hold the string generate by crumb plugin
    }
    server.inject(opts, (res) => { // do something here });
```

**Comment by shorif2000** [comment]
what is the value of `${crumb}`
