### ISSUE TITLE
prePlugin for just a server without Glue

### ISSUE THREAD

**Issue by KeKs0r** [hapijs/hapi#2325]
Hi,

I am very new to Hapi and are currently playing around with a basic architecture. My main server is composed via Glue and all my logic is in plugins. I have also created a function that makes some default things that all my plugins need. I did implement this as a "prePlugin" hook:
```javascript
var manifest = require('./config/manifest.json');
var options = {
    relativeTo: process.cwd() + '/lib/modules',
    prePlugins: require('./lib/base')
};
Glue.compose(manifest, options, function (err, server) {
    server.start(function (err) {
});
```

The Problem is that I can't really call my "base" hook in my tests, since I only want to startup a dummy server within my just plugin tests:
```javascript
        var options = {
            // This is not working with the Server constructor
            // prePlugins: require('./../../../base')
        };
        this.server = new Hapi.Server(options);
        var pluginRegister = [
            { register: require('./../')},
        ];
        self.server.register(pluginRegister, function(err){
            done();
        });
```

I am not sure if a supporting the prePlugin hook would make sense on the server as well. 
Otherwise I might have to implement this "base" stuff as plugin as well, and just make all my plugins depend on it as well. I have seen that http://hapijs.com/api/#serverdependencydependencies-after would allow something like that.

**Comment by hueniverse** [comment]
I think this belongs outside of hapi.
