### ISSUE TITLE
request-error logged before `onPostHandler` or `onPreResponse`

### ISSUE THREAD

**Issue by phated** [hapijs/hapi#2326]
I am working on a plugin that transforms application-specific errors into boom errors, e.g. Record Not Found error into `boom.notFound()` but I am noticing that the Record Not Found error is being logged as a `request-error` before the `onPostHandler` or `onPreResponse` extensions are being called to do the transformation.  This causes Good to log the handler error as an `internalError`.  Is this expected/desired?  I feel like the `request-error`s should only happen if you don't recover from an expected error.

**Comment by hueniverse** [comment]
Hmm.

**Comment by hueniverse** [comment]
The key here is that it should only emit once per request which is not true currently.
