### ISSUE TITLE
Test for plugin registration

### ISSUE THREAD

**Issue by KeKs0r** [hapijs/hapi#2329]
Hi,

I have written a small Hapi App (Hapi 8.0.0.) and would like to test for successful plugin registration.

I know that my register function was called, because I am adding values to server.app but I don't see anything in server.plugins or server.connections.x.plugins.

And I saw that e.g. the frame boilerplate project accesses plugins like this:
```
expect(server.plugins['authentication']).to.exist();
```

How can I see on the server which plugins are already registered?
(I even fully started the sever, because some of my plugins use the server.after() method)

**Comment by hueniverse** [comment]
There is no public API to see which plugins are loaded but you can add a route and check for it's existence.
