### ISSUE TITLE
question : Is this a good tutorial to learn more about hapi  ? 

### ISSUE THREAD

**Issue by roelof1967** [hapijs/hapi#2330]
I m busy with learning node.js on nodeschool.io and one of the lessons are about hapi. 

I wonder if this (https://medium.com/@_expr/the-pursuit-of-hapi-ness-d82777afaa4b) is a good tutorial about hapi 

And is there a a tutorial where a complete site is build prefferly with one model needs another model. 
For example a tutorial with comments and users so I can learn how I can print all the comments of a user. 

Roelof

**Comment by AdriVanHoudt** [comment]
It is a fairly good tutorial only it is way outdated. It was fine with Hapi 7 but now with Hapi 8 the naming and structure of the api is so different it might be not worth it.

**Comment by hueniverse** [comment]
Please bring this topic up in hapijs/discuss. You can also ping the author and see if they want to update it.
