### ISSUE TITLE
Replacing plugin.dependency() with attributes key

### ISSUE THREAD

**Issue by expr** [hapijs/hapi#2332]
Would it be a cleaner idea to replace `plugin.dependency()` with an extension to `register.attributes`?

Rather than

```js
var resolved = function (server, next) {

    server.route({}) // etc
    next()
}

var register = function (server, options, next) {

    server.dependency("lout", resolved)
    next()
}

register.attributes = {
    name: "test",
    version: "1.0.0"
}
```

it'd be possible to do something like this

```js
var register = function (server, options, next) {

    server.route({})
    next()
}

register.attributes = {
    name: "test",
    version: "1.0.0",
    dependencies: "lout"
}
```

I can't see why this wouldn't work out at first look.

**Comment by bendrucker** [comment]
At very least it's a breaking change. What if I don't know that I need a particular dependency until something async happens? At that point you need to maintain two interfaces and I think the documentation cost is too high.

**Comment by hueniverse** [comment]
I don't mind it if others like the idea, but only as an additional option, not a replacement. There are plenty of use cases for dynamic dependencies, especially when dealing with test vs. production. I'll leave it open for a bit to see if others find it significantly cleaner to be worth the extra complexity.

**Comment by nlf** [comment]
I kind of like the idea, but I definitely agree this would need to be an "in addition to" and not a breaking change.

For some things this would be perfect, but like @hueniverse said there's some value in being able to dynamically declare your dependencies as well.

**Comment by kamilwaheed** [comment]
+1 for adding the ability to mention dependencies under `register.attributes`; as an enhancement, of course.

**Comment by devinivy** [comment]
I think this syntax for including dependencies, all so familiar to node developers, would be a nice feature addition.

**Comment by expr** [comment]
I can't imagine the complexity of implementing is too bad, can send a PR with this implemented since it seems to be getting positive feedback. Should it be `register.attributes.dependencies` or `register.dependencies`?

**Comment by nlf** [comment]
I think `register.attributes.dependencies` IMO

**Comment by devinivy** [comment]
I'd agree.

**Comment by hueniverse** [comment]
I'll consider a PR.

**Comment by hueniverse** [comment]
If anyone still cares about it, just open a pull request implementing the additional option.
