### ISSUE TITLE
Simplify table()

### ISSUE THREAD

**Issue by danielb2** [hapijs/hapi#2333]
Converting [blipp](https://www.npmjs.com/package/blipp) to hapi version 8 and looking into table() I can't help but think that `table()` has made routing information more obfuscated.

Accessing a given route directly from the `server` object using Hoek format looks something like this `_sources.0._router.routes.post.routes.0.route`.  Note that I have to refer to an internal variable ( prefixed with underscore ) to access it.

WIth `table()` the result isn't much better:  `0.table.0.connection._router.routes.post.routes.0.route`

Reading the [documentation](http://hapijs.com/api#servertablehost), it claims access to:

```javascript
 {
                method: 'get',
                path: '/example',
                settings: { ... }
            }
```

but as shown, it's very hard to access that information.

Perhaps this can be simplified? Or did I miss something?

**Comment by hueniverse** [comment]
The problem with `table()` is that it was added to support lout and nothing else so it doesn't have a solid foundation of use cases to consider. I am happy to take proposals for something better.

**Comment by Marsup** [comment]
I don't feel that pain in lout, did you check in it to make sure you were accessing information through the right properties ?

**Comment by danielb2** [comment]
I just started looking at the lout code after Eran mentioned it. Thanks

On Mon, Jan 5, 2015 at 1:34 PM, Nicolas Morel <notifications@github.com>
wrote:

> I don't feel that pain in lout, did you check in it to make sure you were
> accessing information through the right properties ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hapijs/hapi/issues/2333#issuecomment-68785866>.
>



-- 
"America was founded by men who understood that the threat of domestic
tyranny is as great as any threat from abroad. If we want to be worthy of
their legacy, we must resist the rush toward ever-increasing state control
of our society. Otherwise, our own government will become a greater threat
to our freedoms than any foreign terrorist."
 - Ron Paul, Texas Straight Talk, May 31, 2004

**Comment by danielb2** [comment]
OK, I've looked. It seems I had just missed an easier way to get to the data. Thanks
