### ISSUE TITLE
Configuring a plugin for multiple routes or connection label

### ISSUE THREAD

**Issue by kokujin** [hapijs/hapi#2338]
I would like to use an plugin for several routes at a time. An example from the docs

````
exports.register = function (server, options, next) {
    server.route({
        method: 'GET',
        path: '/test',
        handler: function (request, reply) {
            reply('test passed');
        }
    });

    next();
};

exports.register.attributes = {
    pkg: require('./package.json');
};
````

This shows how to configurethe plugin for one route, how can I configure the plugin to be used on a group of predefined routes by using a label for example? I have 3 groups(arrays) of routes and 2 server labels, "api" and "web". Thanks

**Comment by kokujin** [comment]
To be a little clearer, I have declared my routes elsewhere, is it possible to configure a plugin for certain routes using just a label? Thanks

**Comment by hueniverse** [comment]
I have no idea what you are asking. You can add as many routes as you want within the plugin. If you have multiple connections on your server, you can select the right labels to only add the routes you want to the selection connection.

**Comment by kokujin** [comment]
1. I have my routes configured and defined in a separate file called "routes.js"
2. In my server.js file, I import the routes and assign them to my server

````
server.route(baseRoutes);
server.route( profilesResource);
server.route((discussionsResource);
`````

3. My plugins are defined, configured and assigned to a server in a file called "plugins"

So stating my question again, how can I configure a plugin in my "plugins.js" file for only the "profilesResource" routes for example. I don't need or want to redefine the routes in the "plugins" file because I've done that already in the "routes.js" file.


Thanks

**Comment by Marsup** [comment]
Your plugins should be responsible for each routes groups, this is bad to define all your routes in a single file.

**Comment by kokujin** [comment]
@Marsup  I find your argument strange, actually, taking a look at what I posted above
````
server.route(baseRoutes);
server.route( profilesResource);
server.route((discussionsResource)
````

I meant to say that each REST resource and routes, "profiles", "discussions" are defined in separate files but all required and manged in one file called "routes", I think its much worse and strange if;

1. I need a plugin to configure another plugin for a group of routes
2. Declaring all the routes that need the plugin in one file where the plugin is declared.Isnt this bad too?

**Comment by hueniverse** [comment]
You are confusing a few things together. Plugins are nothing more than a way to organize server actions. They also create a realm which can be shared between the routes added by that particular plugin. What you want to do has nothing to do with all that. You want to protect a few routes with an auth scheme which is registered by a plugin. Once you register the auth scheme and add the strategy to your server, you can configure the routes you want to use it. There is no way to select a group of routes and apply an auth scheme to them (and not to the others). This is why we have the route `auth` config.

**Comment by kokujin** [comment]
Ok, got that. Thanks
