### ISSUE TITLE
Enexpected Extension Method Behavior

### ISSUE THREAD

**Issue by arb** [hapijs/hapi#2339]
In the following code, I would expect both 'onRequest' extension methods to be called. But if you make a request to "/" you'll get the redirect logic, but the second 'onRequest' event won't fire. If you remove the `return`, both extension events fire. The code doesn't work the same, but at least both extensions run.

I realize this isn't the best way to do HTTP -> HTTPS redirects, but this was the easiest way to demonstrate the unexpected behavior. And it relates to the issue that sort of uncovered it [here](https://github.com/hapijs/good/issues/285)

```js
var Hapi = require('hapi');
var server = new Hapi.Server();

server.connection({ host: 'localhost', port: 9001});

server.ext('onRequest', function (request, reply) {

    console.log('onRequest 1');

    if (request.connection.info.protocol === 'http') {
        return reply.redirect('https://' + request.headers.host + request.url.path).permanent();
    }

    reply.continue();
});

server.start(function () {

    server.ext('onRequest', function (request, reply) {

        console.log('onRequest 2');
        reply.continue();
    });
});
```

Is this expected? If so, is this in the docs somewhere and I missed it?

**Comment by hueniverse** [comment]
Once you call `reply()` or its derivatives in an ext you end the lifecycle including any other ext methods. It jumps straight to `onPreResponse` and even there will not execute all of them if one calls `reply()`. If this is not clear, please update the docs.
