### ISSUE TITLE
Access rendered HTML

### ISSUE THREAD

**Issue by asthanasid** [hapijs/hapi#2340]
I am trying to implement HTML caching for genereted HTML in case the data has not changed. I am using handlebars as my rendering engine.

Is there a way to access the html generated by the handlebar engine, before it is written to client, so that i can cache it and send it back again on next request?

**Comment by hueniverse** [comment]
It is not currently exposed when using the `reply.view()` method but if you use `server.render()` yourself, you can cache the response.
