### ISSUE TITLE
How to implement oauth

### ISSUE THREAD

**Issue by mstolin** [hapijs/hapi#2342]
I can't find a good example how to implement a oauth authentication with hapi 8. I could not find a good plugin as well for hapi.

There is a bridge for Auth2orize (https://github.com/blinkmobile/hapi-oauth2orize) but the documentation is just pain.

Are there any good example projects out there?

Thanks for the help!

**Comment by AdriVanHoudt** [comment]
Can't you use https://github.com/hapijs/bell?

**Comment by mstolin** [comment]
Isn't bell just a login plugin? 

I want to implement a oAuth Provider REST API with Hapi.

**Comment by AdriVanHoudt** [comment]
It's just the first thing that came to mind. I've never used and I don't know.

**Comment by hueniverse** [comment]
This would be better served posted at https://github.com/hapijs/discuss.
