### ISSUE TITLE
response event with null response

### ISSUE THREAD

**Issue by chulkilee** [hapijs/hapi#2344]
>  'response' - emitted after a response to a client request is sent back. Single event per request.

What if a request is terminated by client so that server cannot send back a response?

I actually encountered request.response is null for `response`event - see hapijs/good#285 

My use case is basically token auth with mysql backend. I used following components

- hapi@8.1.0
- hapi-auth-bearer-token@3.1.0
- good@5.1.1
- good-console@4.1.0
- mysql@2.5.4

At the end of wrk test (and it happens only at the last few requests), I got this error:

```
Debug: internal, implementation, error
    TypeError: Cannot read property 'statusCode' of null
    at internals.NetworkMonitor._onResponse (/somewhere/node_modules/good/lib/network.js:40:38)
    at emit (events.js:95:17)
    at handler (/somewhere/node_modules/hapi/node_modules/kilt/lib/index.js:54:44)
    at emit (events.js:95:17)
    at internals.Request._finalize (/somewhere/node_modules/hapi/lib/request.js:378:21)
    at internals.Request._reply (/somewhere/node_modules/hapi/lib/request.js:344:21)
    at /somewhere/node_modules/hapi/lib/request.js:325:18
    at done (/somewhere/node_modules/hapi/node_modules/items/lib/index.js:22:21)
    at /somewhere/node_modules/hapi/lib/request.js:314:24
    at iterate (/somewhere/node_modules/hapi/node_modules/items/lib/index.js:35:13)
```
I could reproduce request.response is null in test code - see #2345

From a close look (my first look on hapi internal so correct me if I'm wrong), currently `internals.Request.prototype._finalized` is called even `_isBailed`=true. `_isBailed` is set to true when the request (not response) is closed. So.. probably it happens when request is closed before response is actually created somehow.

One possible solution is just changing the doc `response` event can be emitted even response is not send back... which is misleading :(

Or emit `response`only when response is actually send back. This may break existing app which relies on this bug, but sounds better to me. Those app probably should use `tail` event.

**Comment by mynoheart** [comment]
hello, i'm also have similary problem.
I use hapi@8.1.0 and good@5.1.1

**Comment by AdriVanHoudt** [comment]
:+1: I also saw this passing by in my logs. Good debugging! I thought https://github.com/hapijs/good/issues/285 fixed it but apperently the response is still broken.

**Comment by AdriVanHoudt** [comment]
After testing myself I can confirm this error is thrown on a disconnect by client.

**Comment by hueniverse** [comment]
The right solution is to update the docs to reflect this. The event contract is well defined and changing it is a breaking change.
