### ISSUE TITLE
handler reply with server.inject response

### ISSUE THREAD

**Issue by Coobaha** [hapijs/hapi#2349]
I am testing CRUD routes,

and want to test handler logic in `POST /users` when `request.auth.isAuthenticated === false` to inject `payload` to auth-free route `/signup`.

when i reply with `server.inject` returned response object is for `POST /users` and i cant test this case.

should it overwrite `response.request.route` object to `/signup` route, so this case can be tested?

**Comment by hueniverse** [comment]
I have no idea what you are trying to do. Can you post some code?

**Comment by Coobaha** [comment]
@hueniverse i have two similar routes: `POST /signup` and `POST /users`

the idea was that `POST /users` is in admin scope, and `/signup` is in public scope.

at the end I moved all users creation logic to `POST /signup` handler.

signup handler code: 
```
function (request, reply) {

    var isAdmin = request.pre.scope.admin;
    if (request.auth.isAuthenticated && !isAdmin) {

      return reply(Boom.conflict('You are already authenticated'));

    }
    let _payload = request.payload;

    let payload = {
      email    : _payload.email,
      username : _payload.username,
      password : _payload.password
    };

    if (isAdmin) {

      if (_payload.scope) {
        payload.scope = _payload.scope;

      }

      if (_payload.createdAt) {
        payload.createdAt = _payload.createdAt;
      }

    }
    let User = request.server.plugins.mongoosePlugin.models.User;
    let user = new User(payload);

    user.saveAsync().spread(function (user) {
      if (!isAdmin) {

        let opts = User.getTransformOptions();
        opts.hide += ' scope isActive updatedAt';
        opts.transform = true;

        reply(user.toObject(opts));

      } else {

        reply(user.toObject());

      }

    }).catch(function (err) {

      reply(Boom.badImplementation((err)));

    });

  }
```

user create rest route is simple call to `signup` path with `server.inject`

```
function (request, reply) {

    let queryString = request.url.search ? request.url.search : '';

    request.server.inject({
      method  : 'POST',
      url     : '/signup' + queryString,
      headers : request.headers,
      payload : request.payload
    }, function (res) {

      reply(res.result);

    });

  }
```

I didnt find the way to test that the request to `POST /users` is internally redirected to `/signup` with server.inject to another route.

**Comment by hueniverse** [comment]
Why use inject for this? Why not just write a common method that's shared between the two routes?

**Comment by Coobaha** [comment]
I did so in the end, thanks
