### ISSUE TITLE
TypeError: Cannot read property 'onPostHandler' of undefined

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/hapi#2350]
Hi I'm trying to execute some code after the handler is done in my plugin.
I register it like this: 
```javascript
server.ext('onPostHandler', function (request, reply) {
	_endConnection(server, request.connection, function () {
		reply.continue();
	});
});
```

But then at runtime when calling an endpoint it throws the error in the title. 
My `onPreHandler` does work.

**Comment by AdriVanHoudt** [comment]
Apparently my prehandler is breaking it
```javascript
server.ext('onPreHandler', function (request, reply) {
		Hoek.assert(pool, 'No mysql pool found');
			pool.getConnection(function (err, connection) {
			if (err) return reply(err);

			if (useTransactions) {
				connection.beginTransaction(function (err) {
					if (err) _endConnection(server, connection, function () {
						return reply(err);
					});

					request.connection = connection;
					return reply.continue();
				});
			} else {
				request.connection = connection;
				return reply.continue();
			}
        });
});
```

**Comment by AdriVanHoudt** [comment]
Apparently overriding reserved keywords (`server.connection`) is not a good idea :smile:  
That was the problem.

**Comment by hueniverse** [comment]
Use `request.app` for anything you want to add so there are no conflicts.

**Comment by AdriVanHoudt** [comment]
So that would result in something like `request.app.dbConnection`?

**Comment by hueniverse** [comment]
It's an empty object. Do whatever you want there.

**Comment by AdriVanHoudt** [comment]
ok cool, thanks for the help!
