### ISSUE TITLE
Why are the emitted events frozen?

### ISSUE THREAD

**Issue by gagle** [hapijs/hapi#2353]
We cannot delete, modify or add new properties. Why this decision? I'm writing a good-reporter that writes to a MongoDB database and I need to create ISODate's from the timestamp:

```javascript
eventData.timestamp = new Date(event.timestamp);
```

However I cannot do this and what I have to do is to clone the object, what a waste of time. Why this overprotection?

```javascript
var data = hoek.clone(eventData);
data.timestamp = new Date(data.timestamp);
```

**Comment by hueniverse** [comment]
hapi doesn't call `freeze()` so I don't know what's your issue.

**Comment by gagle** [comment]
Then the good or good-reporter libraries freeze the object in some way because inside the `_reporter()` function I cannot modify the `eventData` argument, I get a TypeError.

**Comment by bendrucker** [comment]
https://github.com/hapijs/good/pull/280

**Comment by gagle** [comment]
Oh gotcha, now I see why are they frozen, to prevent things like I was trying to do without affecting other reporters.
