### ISSUE TITLE
Hapi.js versus asynchronous authentication schemes

### ISSUE THREAD

**Issue by jokeyrhyme** [hapijs/hapi#2356]
~~I'm having some issues with an asynchronous authentication scheme. I've tried to reduce this to a test case, but I've somehow succeeded in surfacing different error output:~~
~~https://gist.github.com/jokeyrhyme/dcf622385ded9cf232bc~~
~~So there's definitely something weird happening. I ran this reduction using Node.js 0.10.35 and Hapi.js 8.1.0.~~

~~My theory is that if the authentication scheme is too slow (multiple event loops / ticks or something), then Hapi.js can't find the result of the `authenticate()` method so it complains.~~

The real `authenticate()` method I'm developing first makes a request to [Auth0](https://auth0.com/) using [request](https://github.com/request/request), then if that goes well, it makes one or more requests to a PostgreSQL DB via [sequelize](https://github.com/sequelize/sequelize).

I have an automated test scenario that hits that HTTP endpoint. The client returns the following error:
>{ code: 'ECONNRESET' }
>      Error: socket hang up
>        at createHangUpError (http.js:1477:15)
>        at Socket.socketOnEnd [as onend] (http.js:1573:23)
>        at Socket.g (events.js:180:16)
>        at Socket.emit (events.js:117:20)
>        at _stream_readable.js:944:16
>        at process._tickCallback (node.js:442:13)

Further, whilst the client returns this error, the log statements in the server (via [good-file](https://github.com/hapijs/good-file)) don't show anything happening in the `request()` call's event handlers. A logging statement after the `request()` call at least shows that the call itself isn't causing any obvious errors, etc.

This project runs tests with Node.js on the host (OSX), against the service running in a Docker container, with the service connecting to PostgreSQL in another Docker container (using boot2docker).

I also don't get any unexpected errors if I make my MacBook completely offline. In fact, the error event handlers from `request()` suddenly jump to life and behave as expected. So maybe this is caused when `request()` opens a socket and `authenticate()` is unable to `reply.continue(...)` within the next few ticks?

**Comment by jokeyrhyme** [comment]
I should add that I've replaced `request()` with Node.js' built-in `http.get()` and this has not changed the results (still unexpected socket hang up).

**Comment by jokeyrhyme** [comment]
As far as I can tell, the code never gets to where PostgreSQL would be involved.

**Comment by johnbrett** [comment]
Hi @jokeyrhyme, as I read this, you would get 'denied' every time. You need an 'else' on line 26, as line 28 gets invoked before your setTimeout returns.

**Comment by jokeyrhyme** [comment]
@johnbrett good catch! So my reduced test case doesn't really capture anything weird after all.
I'm beginning to think doing this in Docker might be related to the issue, where making an outbound request during an inbound request causes the inbound request to be reset.

**Comment by johnbrett** [comment]
Possibly are you still having errors after fixing the issue I spotted? If
your using routes local to the server, I'd use server.inject

**Comment by jokeyrhyme** [comment]
No, the Gist is not demonstrating any of the issues my larger project is experiencing, after having fixed the logic error you pointed out. My larger project does not make requests to itself, and I just tested external hosts (e.g. http://www.microsoft.com/ ) in my Gist and everything is still good. So I need a new reduced test case.

**Comment by jokeyrhyme** [comment]
Okay, at this stage I am convinced this is nothing to do with authentication schemes. I've disabled my scheme to work on other functionality, and other tests are failing due to ECONNRESET and ECONNREFUSED errors.

Thanks for your suggestions and help. I'll close this now and only re-open if I narrow this down to Hapi-specific functionality.

**Comment by jokeyrhyme** [comment]
Solved it. My test runner was shutting down the server before the tests finished running. Feeling very stupid now. :)

**Comment by johnbrett** [comment]
Don't feel stupid, easy mistake to make, glad you got it sorted
