### ISSUE TITLE
Problem with "Getting started"

### ISSUE THREAD

**Issue by FFagundes** [hapijs/hapi#2357]
I tried to follow the "Getting started" guide of the main page on two different computers, with two different OS(windows 7  and windows 8) and with two different node versions (v0.10.35 and v0.10.29). On both cases when I type "node ." the server didn't start. The cursor just keeps flashing like there's something being processed but I see no response in the terminal.

I followed the guide step by step and after trying a few times I changed the port to 9090 thinking that maybe it was conflicting with another application.

Is it a known issue? Anything I can do to make it work?
Anyway, thx o/

**Comment by FFagundes** [comment]
I fell kinda dumb now, but it's working. I'm just not getting any log on the terminal. But the server is working.

**Comment by AdriVanHoudt** [comment]
You should always do something like 
```javascript
server.start(function () {
    console.log('Server running at:', server.info.uri);
});
```
:wink:

**Comment by hueniverse** [comment]
If the guide can be improved, do a PR on hapijs/hapijs.com
