### ISSUE TITLE
GET route with payload validation

### ISSUE THREAD

**Issue by gagle** [hapijs/hapi#2360]
If I configure a GET route with the `config.validate.payload` to false, a function or a joi object I get the error `TypeError: Cannot read property 'parse' of null`.

https://github.com/hapijs/hapi/blob/master/lib/route.js#L118

I want to validate that the client when performs a GET request doesn't send anything in the body (payload: false)

**Comment by kanongil** [comment]
See discussion in #2347 & #2343.

**Comment by hueniverse** [comment]
The error will be resolved by the other issues mentioned by @kanongil. There is no reason to do the validation you want because the payload should never be read.
