### ISSUE TITLE
How to properly set headers for static assets

### ISSUE THREAD

**Issue by micahlmartin** [hapijs/hapi#2364]
I'm trying to get Fastly pointed at my heroku instance that is running hapijs and serving static files from `/assets/`. I have a route setup that looks like this:

```
  // Assets
  {
    method: "GET",
    path: "/assets/{path*}",
    config: {
      cache: {
        privacy: 'public',
        expiresIn: 31536000000 // 1 year in milliseconds
      }
    },
    handler: {
      directory: { path: './public/assets'}
    }
  },
```

Here are the headers sent back on each request:

```
HTTP/1.1 200 OK
content-type: text/css; charset=utf-8
last-modified: Thu, 22 Jan 2015 07:08:07 GMT
etag: "9c7d48799e5230b7c97ef1978b81ad533c10b950"
set-cookie: csrf=8g-LrNZ8Hcil9mNKaOrDAxF4uXr1UAEWjH8Y2uqAwjX; Path=/
set-cookie: session=Fe26.2**aafe56233413c0736fc3801753af56b52e26f8d1b7414af8b1ac4123918d2522*TGiuBWMtXLLVdbHQ-AGO0g*kxVIgoNOYn6j-0pdplx1Kmf505Duwvboe4lFrx_yS6XDwDSW7Z3LPza8r95VhRpeHpasImHq8XNTHsQeDqmkLA**14c6fcff175626f21a88e981aface41bec3145c14cdeb5b501aa4f63d434dd31*4rCofZFeLlxkI4pB_IB72qs0nn-5BHXuV-IiQh1861s; Path=/
cache-control: max-age=31536000, must-revalidate, private
Date: Thu, 22 Jan 2015 07:21:15 GMT
Connection: keep-alive
```

How do I not set cookies on the responses from this enpoint and why does the cache-control header return `must-revalidate` and `private`. Shouldn't it just be public?

**Comment by hueniverse** [comment]
The cache-control will override your privacy settings if cookies are set or the response was the result of an authenticated request. As for cookies, where are those two coming from? You should disable those plugins for this endpoint.

**Comment by micahlmartin** [comment]
One cookie is coming from `crumb` which is defined like this:

```
server.register({
  register: require('crumb'),
  options: {
    key: "csrf",
    restful: true,
    cookieOptions: {
      isSecure: false
    }
  }
}, function (err) {
    if (err) throw err;
});
```
and the other is from `hapi-auth-cookie` which is defined like this:

```
server.register(require('hapi-auth-cookie'), function(err) {
  if(err) throw err;
});


server.auth.strategy('session', 'cookie', 'try', {
  password: 'test',
  isSecure: false,
  clearInvalid: true,
  ttl: 7 * 24 * 60 * 60 * 1000,
  keepAlive: true,
  redirectTo: /login,
  redirectOnTry: false,
  appendNext: true,
  validateFunc: function(session, callback) {
     ....
    });
  }
});
```

Both of these are configured globally and no specific path is set. How can I disable them specifically for my assets route?

**Comment by hueniverse** [comment]
For crumb I think you can set the route plugin config to false. For the cookie auth scheme, just set route auth to false.

**Comment by micahlmartin** [comment]
Thanks. This worked for me. It would be nice if there was a universal way of skipping plugins at the route level like you can for `auth`. Something simple even like: 

```
{
    plugins: {
        myPlugin: false
    }
}
```

**Comment by hueniverse** [comment]
That's per plugin to implement.
