### ISSUE TITLE
server.inject - how to mock the request?

### ISSUE THREAD

**Issue by PavelPolyakov** [hapijs/hapi#2365]
Hi there, 

I have a custom auth scheme, which is as simple as this:
~~~javascript
 server.auth.scheme('registration', function (server, options) {
        return {
            authenticate: function (request, reply) {
                var user_uuid = request.session.get('user_uuid'),
                    app_uuid = request.session.get('app_uuid');

                if (typeof user_uuid === 'undefined' ||
                    typeof app_uuid === 'undefined') {
                    reply(Boom.preconditionFailed('user_uuid, app_uuid should be present in the session'));
                } else {
                    reply.continue({'credentials':{}});
                }
            }
        }
    });
~~~

The sessions are provided by yar.

And I want to test it using server.inject (btw, if there are some better ways to test it - I would appreciate).
How could I mock the request object, and emulate the session storage during the test?

Something like this:
~~~javascript
/* inside the test */
 var options = {
     'method': 'POST',
     'url': '/registration/clientdata',
     /* pseudocode */
     request: {
         session: {
             get: function(key) {
                 return true;
             }
         }
     }
 };
 serverInstance.inject(options, function(res) {
     // if the validation is not passed, it gives us 412
     expect(res.statusCode).to.equal(200);
     done();
 });
~~~

Any thoughts how to overcome this? And how to have the session support ?

Regards,

**Comment by fampinheiro** [comment]
You can do something like what is done on [hapi-aut-cookie](https://github.com/hapijs/hapi-auth-cookie/blob/master/test/index.js#L24)

**Comment by hueniverse** [comment]
Why not just load yar in the test?

**Comment by PavelPolyakov** [comment]
The yar is loaded, and the server instance is the same we're using on production, however it's not clear which "request" is loaded during the server.inject operation.

22.01.2015, 23:54, "Eran Hammer" <notifications@github.com>:
> Why not just load yar in the test?
> 
> —
> Reply to this email directly or view it on GitHub.

-- 
Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by hueniverse** [comment]
There should be no difference.

**Comment by PavelPolyakov** [comment]
How can I then access the global "request" object (which, as you said would be available inside the auth, which is called when I try to access the route with the help of server.inject) ?

I mean - when I want to set the session values before I call the inject, how to do that, where to take the request ?

23.01.2015, 00:11, "Eran Hammer" <notifications@github.com>:
> There should be no difference.
> 
> —
> Reply to this email directly or view it on GitHub.

-- 
Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by hueniverse** [comment]
Inject works like any incoming request from the outside. There is no request object before you call it. Look at the test/auth.js file to see how we test auth schemes in the core module.

**Comment by PavelPolyakov** [comment]
@hueniverse 
Excuse me one more time, if I don't understand something basic. But - when we register yar, it starts to be available under request.session . You suggested me to use yar directly, and 2nd point - you told that request is not accessible before the server.inject .

So the question - how can I reach yar, to put the data there?

**Comment by hueniverse** [comment]
You setup your code the way you want it, and then to test it, you make requests that try our different scenarios. If you need yar to contain certain data first, you should find a way to make an initial request that will do that, and then make the request you want after.

There are so many examples in hapi and every auth plugin showing how you can test it using inject. I don't know why you are making it so complicated.

**Comment by PavelPolyakov** [comment]
I don't :) Just asked the community.
Thanks for your feedback.

**Comment by hueniverse** [comment]
The best way to do it is using lab's coverage report. You start with some basic scenarios for the success paths and then see what else you need to add to hit all the other lines of code. If you need more help, I recommend opening an issue in hapijs/discuss.
