### ISSUE TITLE
Question: Gracefully Restarting a Longpoll Proxy Hapi App

### ISSUE THREAD

**Issue by dahjelle** [hapijs/hapi#2371]
Hi!

I have a Hapi server with one route proxying a longpoll'd feed (in this case, a CouchDB `_changes` feed). I'd like to be able to gracefully restart my Hapi server such new connections (to any route) connect to the new instance, while existing connections to the `_changes` feed wait for the longpoll to complete.

(I realize this may be a bit outside the `hapi` issue list, so feel free to close without comment—but if anyone has some pointers, it would be greatly appreciated!)

Things I've tried:

- Searching through the `hapi` issues, I see there has been some support for graceful restarts in the `hapi` command line tool, now `rejoice`.
    - Looking at its code, it is looking for a `SIGUSR2` signal, and then stopping the server, followed by a restart. Implementing this logic into my `hapi` app directly, I find that it keeps the old server around until the timeout is hit, at which point it is killed directly. The new server isn't started until the old one stops.
- The `pm2` module says it supports graceful restarts, but not before node v0.11. I'm not completely opposed to using unstable node for my project…but I do wonder if there are better options.
- A [StackOverflow question](https://stackoverflow.com/questions/8933982/how-to-gracefully-restart-a-nodejs-server) about graceful restarts mentions the `cluster` module and has some example code, but I haven't gotten that to work yet. (I've not used node's clustering before.)

Anyone have some example code that they could share, or pointers to articles/resources that I could learn from?

Thanks

**Comment by hueniverse** [comment]
This would be better served in hapijs/discuss.

**Comment by dahjelle** [comment]
Awesome—thanks!
