### ISSUE TITLE
Thrown errors which are not Error objects

### ISSUE THREAD

**Issue by gagle** [hapijs/hapi#2375]
If you throw an error like `throw 123` inside a route handler, the `event.data` Error object which you receive listening to the `request-internal` event does not contain the thrown error in its message, the `event.data.message` is just `Uncaught error`. If you throw an Error object, `throw new Error(123)`, the `event.data.message` is `Uncaught error: 123`.

Can you handle this use case?

```javascript
server.on('request-internal', function (request, event, tags) {
  if (tags.error && event.data instanceof Error) {
    if (event.data.data){
      // Thrown errors which are not Error objects
      event.data.message += ': ' + event.data.data;
    }
    print(event.data.stack);
  }
});
```

**Comment by hueniverse** [comment]
Why are you throwing something other than Error objects?!

**Comment by gagle** [comment]
I'm just asking to treat this use case, third party libraries could throw things that you don't have control over them.

**Comment by Marsup** [comment]
They could, but they shouldn't, ever. I don't think it's a good idea supporting one of the bad parts of javascript.

**Comment by gagle** [comment]
But you are already using domains for the same thing, for catching uncaught errors. Modules could throw errors that are not handled properly. So, I think it's a good idea to handle errors not encapsulated in an Error object. If I want to log the errors somewhere (like I'm doing now, I'd like to have a descriptive message for all the errors emitted by hapi, I'd like to have some consistency.

**Comment by Marsup** [comment]
If something's thrown that's not an error, it can only come from userland, ie. a bad module author, or yourself.

**Comment by gagle** [comment]
Yes, but I'd still like to see the message of the error, it helps me to throubleshoot errors.
