### ISSUE TITLE
Better error output for HTML pages

### ISSUE THREAD

**Issue by swaj** [hapijs/hapi#2379]
Suppose I have the following route:

```javascript
server.route({
    path: "/settings",
    method: "POST",
    handler: function(req, reply) {
        // do stuff to modify settings
        return reply.view("user/settings", { title: "Settings" });
    },
    config: {
        validate: {
            payload: {
                alias: Joi.string().max(60),
                status: Joi.string().max(120)
            }
        }
    }
});
```

The view in this case is a simple HTML form with two text fields, `alias`, and `status`.  Now suppose the user submits data to this form which violates the Joi schema.  Hapi will respond, by default, with a HTTP 400 "Bad Request" object.

In my case, I actually want to display the exact same form again, only with errors inline.  To do this, I have to do use the `onPreResponse` extension point:

```javascript
server.ext("onPreResponse", function(req, reply) {
    if (req.response.isBoom &&
        req.response.output.statusCode === 400 &&
        req.route.path === "/settings") {

        return reply.view("user/settings", { title: "Settings", error: req.response });
    }

    return reply.continue();
});
```

My problem with this approach is that if I want to make this more generic, then I have to maintain some internal map of views to routes, which is kind of ugly.  Or I need to write a bunch of these `onPreResponse` handlers for each form in my application, which results in a lot of unnecessary code being executed on each request since each one of this extensions would be executed.  This drastically increases my surface area for introducing new bugs.  So here's what I'm proposing:

  * Add a new `failAction` type of `handler`
  * When the `failAction` is `handler`, pass the error object to the actual request handler function.

An example of what this would look like is:

```javascript
server.route({
    path: "/settings",
    method: "POST",
    handler: function(err, req, reply) {
        if (!err) {
            // do stuff to modify settings and maybe redirect when done
        }

        // now my view can show errors...
        return reply.view("user/settings", { title: "Settings", err: err });
    },
    config: {
        validate: {
            failAction: "handler",
            payload: {
                alias: Joi.string().max(60),
                status: Joi.string().max(120)
            }
        }
    }
});
```

I hope this makes sense.  Let me know if you think I'm crazy.  Cheers!

**Comment by kanongil** [comment]
So essentially you want to forward errors through the regular flow all the way to the handler?

This does sound kinda neat for certain use cases. The "crazy" part is how you want to extend the handler signature. I'd say a much cleaner approach would be to add an `validationErrors` property or similar to the `request` object, and let the app decide what to do about it. Then your handler would look something like this:
```javascript
handler: function (request, reply) {
  var err = request.validationErrors.payload;
  if (!err) {
  }

  return reply.view("user/settings", { title: "Settings", err: err });
}
```
A nice feature of this approach, is that it will be functionally identical to `"ignore"` if you never use the `validationErrors` object, and it allows `pre` handlers to reason about the errors as well.

**Comment by swaj** [comment]
Sounds good to me.  To further simplify my "ask": I would really love the ability to use the built-in request validation system, but have my handler decide how to react given the validation errors that were encountered.

**Comment by hueniverse** [comment]
You mean the `validate.failAction` option with a function?
https://github.com/hapijs/hapi/blob/master/test/validation.js#L481-L500
