### ISSUE TITLE
Small error in routing tutorial

### ISSUE THREAD

**Issue by KevinBatdorf** [hapijs/hapi#2380]
I think the last line should be `user` instead of `request.params.user`

![screen shot 2015-01-29 at 11 15 31 am](https://cloud.githubusercontent.com/assets/1478421/5952424/1ede3afa-a7a9-11e4-8349-1917aa13c253.png)

**Comment by AdriVanHoudt** [comment]
I think you're right. You can do a PR on this file: https://github.com/hapijs/hapijs.com/blob/beta/lib/tutorials/routing.md :wink:

**Comment by hueniverse** [comment]
This issue belongs in hapijs/hapijs.com. Thanks.

**Comment by AdriVanHoudt** [comment]
This is fixed by https://github.com/hapijs/hapijs.com/pull/139
