### ISSUE TITLE
Make onPreHandler a real extension point previous to the route handler

### ISSUE THREAD

**Issue by gagle** [hapijs/hapi#2381]
With Hapi 8.1.0 onPreHandler is called before the route prerequisites. I propose to rename the current onPreHandler to onPrePrerequisites and create a new onPreHandler which is called just before the route handler.

**Comment by AdriVanHoudt** [comment]
Well it is in the docs and the pre function can be seen as part of the handler since they also handle the request. Also that would be super breaking :stuck_out_tongue_winking_eye:

**Comment by hueniverse** [comment]
Nah.
