### ISSUE TITLE
Encoding problems using views with special chars

### ISSUE THREAD

**Issue by karlas** [hapijs/hapi#2385]
When using views to render content using special characters, I experience this:

    reply.view('www/index.jade', {name : 'Pagès'}); //outputs "PagÃ¨s"

Template is just : 

    p #{name}

But, if i just send the plain text, it works ok:

    reply('<p>Pagès</p>');  //outputs "<p>Pagès</p>"

I tried with Jade and EJS, and both render it wrong, so I think problem is related to Hapi.

Using

    p !{name}

does not work :(

Any suggestion? Thanks in advance

**Comment by karlas** [comment]
Following code discards Jade issues:

    var jade = require('jade');
    var fn = jade.compile('p #{name}');
    var html = fn({name : 'Pagès'});
    console.log(html);   // outputs -> <p>Pagès</p>

**Comment by karlas** [comment]
OK, sorry... Problem was...

  <meta http-equiv="Content-Type" content="text/html;charset=utf-8">

My apologies

**Comment by Marsup** [comment]
What was your solution for that ? Same problem on handlebars, I don't understand your fix.

**Comment by karlas** [comment]
You must put this meta inside your html <head> tag

**Comment by Marsup** [comment]
Then that didn't fix it for me.

**Comment by Marsup** [comment]
FWIW I ended up escaping accentuated characters manually or through Hoek.escapeHtml when possible. Isn't that an escaping bug @hueniverse ?

**Comment by hueniverse** [comment]
No idea.

**Comment by Marsup** [comment]
@hueniverse FTR I'm following up in hapijs/shot#7.
