### ISSUE TITLE
Better error reporting in case of payload errors. 

### ISSUE THREAD

**Issue by bhanuc** [hapijs/hapi#2387]
I am not sure of other errors but errors regarding payload are not being passed on to console and hence makes it extremely hard to debug things for beginner like me. I was trying to get submit files using ajax and I had been getting 400 error. Finally I did a console log in the internals.payload route.js to see that it was 'Invalid content-type header: multipart missing boundary' .
Is there a way currently to enable this ?

**Comment by AdriVanHoudt** [comment]
Does the response not include this? Also you can use https://github.com/hapijs/good-console to log Hapi events to console.

**Comment by bhanuc** [comment]
No the response did not have  have it . I was just getting 400 . Also I am using good-console but I did not get any error in the console, just the status code

**Comment by hueniverse** [comment]
hapi doesn't log 4xx error to the console, only 5xx. I don't know what good logs but its probably worth asking for that feature there. The tv module might be a better way to understand what is going on with your server than console logging.

To log things yourself you can use the `server.on('response')` event and log the result to the console.

**Comment by rainabba** [comment]
@bhanuc I'm hitting "" also. Any chance you could share why you were getting it and/or how you resolved? I'm trying to test with ARC (Chrome Advanced Rest Client) so it may be the client, but I've not done uploads with Hapi before so the more I can eliminate, the less time I hope to spend fighting this (already lost the day).

**Comment by rainabba** [comment]
Think I just stumbled on the issue or I'm at least close. It looks like the request (coming from ARC) needs to include a "boundary" param with the content-type header such as `content-type: multipart/form-data; boundary=----WebKitFormBoundaryS4AeNzAzUP7OArMi`

When I do this, I don't get the "multipart missing boundary" error, but I do get "Invalid multipart payload format" so I think I've just got the boundary wrong and need to figure out what it is.

**Comment by rainabba** [comment]
I've got the request working with POSTMAN and from what I can tell, the boundary is changing for each request so I don't think it's appropriate for me to include and ARC is supposed to be doing it automatically (it even says ""), but I think it's not and so I get the "missing boundary" error.

If I'm right, I had such a hard time with this because I couldn't inspect my request object in the handler because something at a lower-level is handling the error and not logging to the console so I think ultimately I'm dealing with the same issue that the OP here is and so now I have the same request; to have useful information (in my case, the request.headers) logged to the console.

**Comment by hussainb** [comment]
@rainabba, thankyou for your analysis, saved me lot of trouble since I too got the same error by using ARC.

**Comment by bhanuc** [comment]
@rainabba Apologies.. somehow missed your message. I don't recall if I did solve it or not but I moved on to a diff. framework namely koa.js which is more simpler in design.

**Comment by rainabba** [comment]
@hussainb Glad to have helped. I got things working and as I recall, it DID end up being the sames I'd seen, but there was something on the edge of these operations that I'd had configured differently or something along those lines. Now that I think about it, I'll distill my implementation and provide a gist and link back here when it's ready.
