### ISSUE TITLE
[question] Is "Debug: request, closed, error" really an error?

### ISSUE THREAD

**Issue by davidchase** [hapijs/hapi#2388]
Using Hapi v8.1.0 
So with the following setup config for the server
```js
 debug: {
        request: ['error']
    },
```
for every request after a little bit of time i get `Debug: request, closed, error` printed out via 
`good-console`

Is that an error that i should look into or is it just letting me know that the request was closed?

-David

**Comment by kanongil** [comment]
This error should only be output when the connection is closed prematurely (eg. the client aborts the request), which shouldn't happen for normal requests.

**Comment by davidchase** [comment]
@kanongil thanks for the reply... below is an example of what happens, i.e. refreshed the page 3 times
```
150210/013702.163, [response], http://0.0.0.0:9000: get /shop/123456789/ {} 200 (528ms)
150210/013702.794, [response], http://0.0.0.0:9000: get /client/dist/css/global.css {} 304 (4ms)
150210/013702.795, [response], http://0.0.0.0:9000: get /client/dist/css/product.css {} 304 (5ms)
150210/013702.795, [response], http://0.0.0.0:9000: get /client/dist/js/common.js {} 304 (6ms)
150210/013702.796, [response], http://0.0.0.0:9000: get /client/dist/js/main.js {} 304 (7ms)
150210/013702.797, [response], http://0.0.0.0:9000: get /client/dist/js/product.js {} 304 (7ms)
150210/013703.483, [response], http://0.0.0.0:9000: get /shop/123456789/ {} 200 (529ms)
150210/013704.084, [response], http://0.0.0.0:9000: get /client/dist/css/global.css {} 304 (5ms)
150210/013704.085, [response], http://0.0.0.0:9000: get /client/dist/css/product.css {} 304 (8ms)
150210/013704.085, [response], http://0.0.0.0:9000: get /client/dist/js/common.js {} 304 (10ms)
150210/013704.087, [response], http://0.0.0.0:9000: get /client/dist/js/main.js {} 304 (9ms)
150210/013704.088, [response], http://0.0.0.0:9000: get /client/dist/js/product.js {} 304 (9ms)
150210/013704.684, [response], http://0.0.0.0:9000: get /shop/123456789/ {} 200 (529ms)
150210/013705.265, [response], http://0.0.0.0:9000: get /client/dist/css/global.css {} 304 (4ms)
150210/013705.266, [response], http://0.0.0.0:9000: get /client/dist/css/product.css {} 304 (4ms)
150210/013705.267, [response], http://0.0.0.0:9000: get /client/dist/js/common.js {} 304 (4ms)
150210/013705.267, [response], http://0.0.0.0:9000: get /client/dist/js/main.js {} 304 (5ms)
150210/013705.267, [response], http://0.0.0.0:9000: get /client/dist/js/product.js {} 304 (6ms)
Debug: request, closed, error
Debug: request, closed, error
Debug: request, closed, error
Debug: request, closed, error
Debug: request, closed, error
Debug: request, closed, error
Debug: request, closed, error
Debug: request, closed, error
Debug: request, closed, error
```

It shows up when i setup debug in the server config

**Comment by kanongil** [comment]
Ok, so the client is a browser in this case? In that case I suspect that either your handler, or an extension handler, is leaving the connection dangling, causing the browser to eventually timeout the request and close the connection.

**Comment by kanongil** [comment]
Further discussion should probably be moved to the [discuss repo](https://github.com/hapijs/discuss), unless you think this is a Hapi issue.

**Comment by davidchase** [comment]
@kanongil you are correct the ` /shop/123456789/` and the `/client` is the current static files be served to the browser, however the browser doesn't seem to hang. Maybe once in a while takes a bit longer to respond. So let me know if it should be moved to the other repo

**Comment by davidchase** [comment]
are you typically not suppose to see those messages? or is it suppose to one per request?

**Comment by davidchase** [comment]
so the culprit was the `favicon` i found that out by setting
```js
routes: {
   timeout: {
      server: 10 * 1000
    }
}
```

it which it should that `favicon` was a `503` so fixing the favicon path fixed the error :+1:
