### ISSUE TITLE
Moving from 7.5.3 to 8.1.0: can't find the clearInvalid option equivalent

### ISSUE THREAD

**Issue by briandela** [hapijs/hapi#2391]
Trying to update from hapi 7.5.3 to 8.1.0. In 7.5.3 we were able to specify default options on how to deal with cookies. For example, we could set the following options for  state: `{ cookies: { clearInvalid: true } }`.

 I can't see how to do this in Hapi 8.1.0 - it looks like the only options under connections - routes - state are `parse`, and `failAction`. Any ideas how to globally set clearInvalid for cookies?

**Comment by AdriVanHoudt** [comment]
Look here http://hapijs.com/api#serverstatename-options

**Comment by kanongil** [comment]
Check the "Server configuration" and "Connection configuration" chapters in the [migration guide](https://github.com/hapijs/hapi/issues/2186).

**Comment by ubaltaci** [comment]
I also trying to find `clearInvalid` option in connection settings.

@AdriVanHoudt isnt it cookie based ?

@kanongil I've checked but could not find that in migration guide.

**Comment by AdriVanHoudt** [comment]
@ubaltaci I don't know I have never used it. But it is the only `clearInvalid` I could find so you can give it a try.

**Comment by ubaltaci** [comment]
@AdriVanHoudt thank you,

@briandela I think i figure it out but I could not understand the logic of separation of these state options.

```js
new Hapi.Server({connections: {
        state: {
            clearInvalid: true
        },
        routes: {
            state: {
                failAction: "log"
            },
        }
    }});

// or

server.connection({
   ... 
   state: {
        clearInvalid: true
    },
    routes: {
        state: {
            failAction: "log"
        }
    }
})

**Comment by hueniverse** [comment]
@ubaltaci there are two sets of options:
- settings for how to handle individual cookies in `connection.state` or when setting `server.state()`
- settings for what to do with cookies in general when processing a route.
