### ISSUE TITLE
No Payload Validation

### ISSUE THREAD

**Issue by arb** [hapijs/hapi#2392]
Unless I'm misreading the docs, the code below should validate that 204 status code responses should not have a payload.

```js
server.route({
    method: 'GET',
    path: '/',
    config: {
        response: {
            status: {
                204: false
            }
        },
        handler: function (request, reply) { reply().code(204); }
    }
});
```

However, if you make a request to "/" you get an error

```bash
Debug: internal, implementation, error 
    Error: value must be an object
```

Is this intentional or a bug? Tracing the code, it looks like a Joi validation schema is created https://github.com/hapijs/hapi/blob/master/lib/route.js#L101-L106 with the value of `false` which turns into an empty object and then that makes 204 responses required to be an object, instead of nothing.

**Comment by Marsup** [comment]
Probably because of https://github.com/hapijs/hapi/blob/5543663cc87752cf48204b8bb6b92fe968d5cc9c/lib/route.js#L240.
