### ISSUE TITLE
give some hooks to decode multipart payload

### ISSUE THREAD

**Issue by mohan43u** [hapijs/hapi#2393]
here is one multipart,

--------------------------7c92f9e67b266bbe
Content-Disposition: form-data; name="media[]"; filename="TransferDetails.png"
Content-Type: image/png
..some..binary..content..
--------------------------7c92f9e67b266bbe--

If I have a way to parse the payload, I'll construct request.payload like this,
```
{ 'media[]' : {value: <Buffer ..>, options: { "filename": "TransferDetails.png", "content-type": "image/png"}}}
```
this makes easier for me to re-transfer the same payload to other servers.

But, currently what I'm getting in request.payload is,
```
{ 'media': [ <Buffer..> ] }
```
lot of original information is gone.

do something about this. or tellme some way to achieve what I'm expecting with the current multipart parser (I think its pez and it sucks)

**Comment by hueniverse** [comment]
A piece of advice - telling someone their code "sucks" and then expecting them to help you isn't the most effective.

The way multipart payload is parsed is based on how every other module does it including multiparty and formidable. If you don't like it, don't use it. Just set your payload option `parse` to `false` and `output` to `'stream'` and handle it yourself. `request.payload` will be the incoming stream and you can do whatever you want.
