### ISSUE TITLE
Cached server method results are not promises

### ISSUE THREAD

**Issue by bmcmahen** [hapijs/hapi#2394]
I have a (pretend) sever method as follows:

```javascript
var Promise = require('bluebird');

var sayHi = function(name, next){
  setTimeout(function(){
    next(null, 'hi '+ name);
  }, 500);
}

server.method({
  name: 'users.sayhi',
  method: Promise.promisify(sayHi),
  options: {
    callback: false,
    cache: { expiresIn: 6000 }
  }
});
```

```
server.methods.users.sayhi('ben')
  .then(function(message){
      console.log(message);
    })
    .catch(function(err){
      console.log('err', err);
    })
```

When I don't set a cache to the method, this works fine. However, when I set the cache, I get the following error:

```
TypeError: Cannot read property 'then' of undefined
```

**Comment by hueniverse** [comment]
Can't help you here. hapi does not return a promise object (notice no dependency on any promises module). It can only support using a promise object you provided and once it is used, it is discarded. If you are going to cache the results, the output is never a promise.

**Comment by bendrucker** [comment]
> Note that using a synchronous function with caching will convert the method interface to require a callback as an additional argument with the signature `function(err, result, cached, report)` since the cache interface cannot return values synchronously.

If you want to use caching + promises, use the callback interface and use Bluebird's [`nodeify`](https://github.com/petkaantonov/bluebird/blob/master/API.md#nodeifyfunction-callback--object-options---promise) method instead. As Eran mentioned, Hapi would have to be able to return a promise wrapper around the catbox call in order to allow caching of server methods that return promises.

**Comment by bmcmahen** [comment]
Thanks for the responses. It makes sense that you wouldn't want to add a promise dependency to your stack. I messed around with wrapping the functions with promisify... using nodeify, etc., but I actually ended up rolling my own server methods plugin that uses promises.

**Comment by calmdev** [comment]
@bmcmahen would you mind sharing your solution? I'm attempting to do the same thing; running into the same issue(s). Trying to solve it with nodeify as suggested, but not having any luck yet.

**Comment by bendrucker** [comment]
```js
server.method('getData', function getData (arg, next) {
  return lib.getAsync(arg).nodeify(next);
});
```

**Comment by calmdev** [comment]
@bendrucker thanks, I managed to get it working :+1:
