### ISSUE TITLE
Question: Ensure plugins are loaded before a server.inject test is run.

### ISSUE THREAD

**Issue by duro** [hapijs/hapi#2399]
Is there a good best practice for ensuring that plugins have loaded before a server.inject test is run with Lab. Here is my server file:

https://gist.github.com/duro/51402326705a883f43ca#file-index-js

And here is my test:

https://gist.github.com/duro/51402326705a883f43ca#file-test_auth-js

If I console.log the connection status in the test callback, I can tell the DB is not connected.

**Comment by hueniverse** [comment]
Start the server and run your tests after the callback. Otherwise you have to know exactly how each plugin behaves so you can keep track of its callbacks.
