### ISSUE TITLE
Method name RegExp

### ISSUE THREAD

**Issue by gagle** [hapijs/hapi#2401]
Currently, the method name is validated with [this regexp](https://github.com/hapijs/hapi/blob/2a9ce7196e9db45a99a271ba36da4df5384066ae/lib/methods.js#L38):

```javascript
/^[a-zA-Z]\w*(?:\.[a-zA-Z]\w*)*$/
```

You could allow any [identifier name](http://www.ecma-international.org/ecma-262/5.1/#sec-7.6), that is, any string starting with `$` or `_`. For instance, I need to create a method with a name starting with underscore and I can't.

```
Error: Invalid name: _common.injectQueryClientAndAncestors
```

**Comment by hueniverse** [comment]
I'll take a PR.
