### ISSUE TITLE
Please maintain the changelog

### ISSUE THREAD

**Issue by 6a68** [hapijs/hapi#2406]
I just dropped by to see what the diff looked like between 8.1.0 and 8.2.0, but the changelog hasn't been updated since the 8.0 release.

I don't mind looking through the commit log myself, but it would be great to see the changelog kept up to date as part of the minor release process.

Thanks!

**Comment by AdriVanHoudt** [comment]
I use the milestones to see what has changed https://github.com/hapijs/hapi/issues?q=milestone%3A8.2.0 but idd valid point to maybe add more to the changelog

**Comment by Marsup** [comment]
This could probably be done by travis on a new release tag.

**Comment by AdriVanHoudt** [comment]
Can you do that with travis?

**Comment by 6a68** [comment]
Thanks for looking into it, guys. I noticed that the changelog prior to 8.0 contains changes for major, minor, and patch releases. Was there a handoff after 8.0? Maybe part of the release checklist wasn't documented and got overlooked.

**Comment by brianjmiller** [comment]
I did the same so :+1:.

**Comment by hueniverse** [comment]
The script that generates the changelog doesn't always work because of github API quota limits. Then it gets forgotten. You can generate it with `make changelog` and do a PR to update it to the latest.

**Comment by AdriVanHoudt** [comment]
I keep getting this error 
```bash
[//github.com/AdriVanHoudt/hapi] fetching 1311/1311 issues [====================] 100% 0.0s
Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
{ [Error: ENOENT, mkdir 'c:\tmp\mdchangelog-CLTDWIM']
  errno: -4058,
  code: 'ENOENT',
  path: 'c:\\tmp\\mdchangelog-CLTDWIM' }
Makefile:8: recipe for target 'changelog' failed
make: *** [changelog] Error 1
```
Even when setting the `--cwd`

**Comment by hueniverse** [comment]
Maybe open an issue in the mdchangelog repo?

**Comment by AdriVanHoudt** [comment]
@hueniverse will do

**Comment by AdriVanHoudt** [comment]
@diffsky generated a new changelog https://gist.github.com/diffsky/73f62e1430d84c16d51b it does include 8.2.1 which i'm not sure should be there already.

**Comment by hueniverse** [comment]
Nope. But if you remove it and submit a PR I'll merge.

**Comment by AdriVanHoudt** [comment]
Notified @diffsky of it and he's looking into an option to only add closed milestones and will do!

**Comment by diffsky** [comment]
`mdchangelog@0.5.0` now supports a `--only-closed-milestones` option
