### ISSUE TITLE
Errors in tutorial?

### ISSUE THREAD

**Issue by edthedev** [hapijs/hapi#2408]
The example using good and good-console does not work as it shows on the tutorial page.
<pre>
server.register({
    register: Good,
    options: {
        reporters: [{
            reporter: require('good-console'),
            args:[{ log: '*', response: '*' }]
        }]
    }
}, function (err) {
    if (err) {
        throw err; // something bad happened loading the plugin
    }

    server.start(function () {
        server.log('info', 'Server running at: ' + server.info.uri);
    });
});
</pre>

The <pre>register:Good,</pre> line throws an error.

After reading the server.register method on the [Hapi API](http://hapijs.com/api) page, I was able to make it work:
<pre>
server.register({
    register: require('good'),
    options: {
        reporters: [{
            reporter: require('good-console'),
            args:[{ log: '*', response: '*' }]            }]
    }
 }, function (err) {
     if (err) {                                            
        throw err; // something bad happened loading the plugin
     }
 });

// Start the server                               
server.start(function () {                                
console.log('Server running at:', server. info.uri);
});
</pre>

The important difference is replacing <pre>register:Good,</pre> with <pre>register: require('good'),</pre>

I dropped moving the server start into the callback for my own test. I'm not sure why the example switches to using a callback to start the server. I'm including my exact source just in case it makes some difference - I'm pretty new to Node.

I suppose it might be worth adding an explanation for switching to starting the server in the register callback, if it is important.  Or it might be worth changing it so the step does not make that change, just to simplify the tutorial. But now I'm way off topic.

**Comment by edthedev** [comment]
I would be glad to submit a pull request with just the minimum necessary change, but I wasn't able to find the Git repo for the tutorial.

**Comment by bendrucker** [comment]
You can edit this:

https://github.com/hapijs/hapijs.com/blob/master/lib/tutorials/getting-started.md

**Comment by kanongil** [comment]
@edthedev The tutorial is correct. I guess you missed line 2 with `Good = require('good');`

The server is started from the callback to allow the plugin to finish any async processing before the start.
