### ISSUE TITLE
server.types and server.pack occasionally undefined

### ISSUE THREAD

**Issue by kimballjohnson** [hapijs/hapi#2409]
I collected a number of Hapi server examples because I liked the way Hapi was organized better than I like Express. 

But I found that I had issues with some of the Hapi server properties. At first it was server.types that was undefined. After a few hours I noticed some bugs in your history about that, so I discovered version 8.2.0 and that was solved.

Now, with 8.2.0 I'm having the same thing with server.pack (actually server.pack.register on an object array and a callback function (this is from the hapi-dashboard example based on the hapi-ninja). example.

the server (passed as a parameter to a require statement && in the required file just after successful new'ing) has an undefined 'pack' property, so I get an error at the 'r' in server.pack.register.

And I've found server.pack = undefined in the Webstorm debugger, as in the attached image.
Since the server.types was soved by a version, is the server.pack thing I'm experiencing a version issue or a bug, or can I solve it with syntax?

Thanks,

Kimball Johnson 

![hapi-server-pack-undefined](https://cloud.githubusercontent.com/assets/2092723/6202367/261d5a9a-b49b-11e4-87b4-5b69f7c28611.png)

**Comment by kanongil** [comment]
`server.pack` is no longer available in Hapi@8.x. If you want to migrate the code to 8.x, you can find a guide here: https://github.com/hapijs/hapi/issues/2186

For further questions about Hapi, please post them in the [hapijs/discuss](https://github.com/hapijs/discuss) repository.
