### ISSUE TITLE
Custom validation that combines route and payload info

### ISSUE THREAD

**Issue by futurechan** [hapijs/hapi#2410]
I have a scenario where I need to dynamically build a joi object to validate a payload based upon a route param. Is this possible?

**Comment by hueniverse** [comment]
You can implement this in a pre, or in the handler. You can also pass a custom validation function that then creates a joi schema and uses it directly, passing the validation function callback to complete the action. Note that constructing joi schemas is expensive so you want to avoid doing it per request.

**Comment by futurechan** [comment]
Do you have an example where my custom validation function has access to both the route and the payload? I tried settings ```config.validate.payload``` to ```function (value, options, next)```, but I couldn't find the path info.

**Comment by hueniverse** [comment]
The path parameters and payload are part of the validation context. Not the full path.

**Comment by futurechan** [comment]
I checked ```this``` inside of my custom validation method, but I didn't see a ```request``` object. I'll keep looking.

**Comment by futurechan** [comment]
Can I set my custom validation function on ```config.validate``` directly?

**Comment by futurechan** [comment]
Ah, ```options.context```. Thanks.
