### ISSUE TITLE
View helpers not rendering in Jade Templates

### ISSUE THREAD

**Issue by chyld** [hapijs/hapi#2412]
I'm on Hapi 8.2.0, Mac OSX 10.10, Node 0.12 x64.

My jade templates render perfectly, however, if I want to use a helper it tells me that the helper is undefined.

My view config:

```js
module.exports = {
  engines: {jade: require('jade')},
  path: __dirname + '/../views',
  helpersPath: __dirname + '/../views/helpers',
  compileOptions: {pretty: true, doctype: 'html'}
};
```

My sample helper. It's called fortune.js. And it's in views/helpers directory. This example was taken from the tutorial on views.

```js
module.exports = function() {
  var fortunes = [
    "Heisenberg may have slept here...",
    "Wanna buy a duck?",
    "Say no, then negotiate.",
    "Time and tide wait for no man."
  ];
  var x = Math.floor(Math.random() * fortunes.length);
  return fortunes[x];
};
```

My jade template that is attempting to use the helper. It shows this variable as undefined.

```jade
ul
  li= fortune
```

**Comment by hueniverse** [comment]
Been a few years since I looked at jade but according to this, partials and helpers are not supported via hapi: https://github.com/hapijs/vision/blob/master/test/manager.js#L1259-L1273

Maybe things have changed.

**Comment by chyld** [comment]
If true, that's too bad.

**Comment by hueniverse** [comment]
The [jade API](http://jade-lang.com/api/) does not seem to support loading partials or helpers.

**Comment by grabbou** [comment]
you can always decorate `view` method, to create your own and always merge helpers object with context you pass. That's how we solved it in our project.
