### ISSUE TITLE
Question: Route not accepting '?'

### ISSUE THREAD

**Issue by 0x4139** [hapijs/hapi#2430]
i have the following route 
```
server.route({
    method: 'GET',
    path:'/{string}',
    handler: function (request, reply) {
        reply(request.params.id);
    }
});
```
but when i  access `/?randomstring` i get 
```
{
statusCode: 404,
error: "Not Found"
``` 
i read the documentation on how to do the routing but i really need to send it in this form

**Comment by lloydbenson** [comment]
I think you are confusing params with query but I think this should move to
the discuss repo which is more appropriate.

**Comment by 0x4139** [comment]
i am not confusing params with query, i want to send a string parameter that begins with ?

**Comment by gergoerdosi** [comment]
`?` indicates the beginning of the query:

> The generic syntax uses the slash ("/"), question mark ("?"), and
   number sign ("#") characters to delimit components that are
   significant to the generic parser's hierarchical interpretation of an
   identifier.

If you want to send `?` in the URL, you need to escape it.
