### ISSUE TITLE
Lost key after validation

### ISSUE THREAD

**Issue by sarhugo** [hapijs/hapi#2431]
Hi, not sure if this is a problem of Joi itself or the integration with Hapi.
I'm doing the following validation in a route:

```javascript
server.route({
    method: 'POST',
    path: '/register',
    config: {
      validate: {
        payload: Joi.object({
          username: Joi.string().regex(/^[a-z0-9_\.]+$/i).required(),
          email: Joi.string().email().required(),
          password: Joi.string().min(6).required(),
          confirm: Joi.object().keys({
            email: Joi.string().required(),
            password: Joi.string().required()
          }).required()
        }).assert('confirm.email', Joi.ref('email'))
          .assert('confirm.password', Joi.ref('password'))
          .required()
        , options: {abortEarly: false}
      },
     handler: function() {}
   });
```
The problem is with the assert validation. If I send different emails and passwords I get the following response:
```javascript
{ statusCode: 400,
  error: 'Bad Request',
  message: 'value validation failed because confirm.email failed to pass the assertion test. value validation failed because confirm.password failed to pass the assertion test',
  validation: { source: 'payload', keys: [ 'value', 'value' ] } }
```
Shouldn't the keys be 'confirm.email' and 'confirm.password' instead of 'value'? Am I doing something wrong?

Thanks

**Comment by hueniverse** [comment]
Looks like a problem in joi: https://github.com/hapijs/hapi/blob/master/lib/validation.js#L76 /@marsup

**Comment by Marsup** [comment]
Sorry but I can't reproduce, which version of Joi ? Can you provide a minimal gist that I can run to see the issue ?

**Comment by DJMcK** [comment]
https://gist.github.com/DJMcK/103d0a692dc7d048253a

@Marsup above gist seems to reproduce

**Comment by sarhugo** [comment]
Here: https://gist.github.com/sarhugo/6ec6929a98697cfd8a1a

**Comment by Marsup** [comment]
Oh yeah right. Well `assert` is a rule on the object, when there's no path to something, Joi reports that as "value", so what you're seeing is expected since it's the root object. I'll agree it probably doesn't make a lot of sense. Can you create an issue on joi ?

**Comment by sarhugo** [comment]
Moving there, thanks!

**Comment by hueniverse** [comment]
I'll keep this open to track.

**Comment by Marsup** [comment]
This can be closed now. I don't think I'll backport that to 5.x though, it involves too much cherry picking.

**Comment by hueniverse** [comment]
Can you reference the fix in joi?

**Comment by Marsup** [comment]
It's the commit referenced in hapijs/joi#569.
