### ISSUE TITLE
TLS certificate errors are not surfaced in logs

### ISSUE THREAD

**Issue by benbarclay** [hapijs/hapi#2432]
I was attempting to debug an error around TLS connections not working and noticed that errors produced by the underlying server are not captured by Hapi.

In the end I used the snippet in #559 to capture the issue directly to the console.

Inside hapi/lib/server.js internals.Server.prototype.start
```
this.listener.once('clientError', function(e) {
    console.error(e);
});
```

It would be nice if this was captured by Hapi, so that the errors are found when you run Hapi with the debug option turned on.

**Comment by hueniverse** [comment]
First, you can do this without changing hapi internals since the `connection.listener` is exposed. Second, I'll consider a pull request for this.
