### ISSUE TITLE
Consider exposing _setSource or a public method to set the payload

### ISSUE THREAD

**Issue by devinus** [hapijs/hapi#2434]
I'd like to set the payload of a response **after** it's been created. Is there currently any way to do this using a public interface?

E.g.,

```javascript
function(request, reply) {
  var response = reply().hold();

  async.waterfall([
    // ...
  ], function(err, result) {
    if (err) {
      response._setSource(Boom.wrap(err));
    } else {
      response._setSource('success');
    }
    response.send();
  });

  return response;
}

**Comment by devinus** [comment]
The same goes for the `view` function. I currently have no way to do async operations and still return a reference to the reply.

**Comment by AdriVanHoudt** [comment]
Can't you just wait until you have the payload you want and then reply?

**Comment by devinus** [comment]
@AdriVanHoudt How would I return the response object in an async scenario?

**Comment by AdriVanHoudt** [comment]
To take your example
```javascript
function(request, reply) {

  async.waterfall([
    // do all your async stuff here
  ], function(err, result) {
    if (err) {
      return reply(Boom.wrap(err));
    }

     return reply('success');
  });
}
```

Maybe a quick read on the docs will also help and in particular http://hapijs.com/api#reply-interface ;)

**Comment by devinus** [comment]
@AdriVanHoudt That wont allow returning the `Response` object from the handler itself.

**Comment by AdriVanHoudt** [comment]
@devinus whatever you pass into ´reply()´ will be the response payload
Or am I misreading your intent?

**Comment by devinus** [comment]
@AdriVanHoudt Correct, in am async scenario I'm not sure what my payload is going to be into later. But I still want to return the reference to the `reply()` for e.g. testability.

**Comment by AdriVanHoudt** [comment]
@devinus If you reply in your final callback you can be sure.
And what do you mean with `return the reference`?
I think you can do `var response = reply()` or `var response  = reply.reponse` not sure

**Comment by devinus** [comment]
If I manually call handler() the return value will be undefined.

```javascript
hanlder(request, reply); //=> undefined
```

**Comment by AdriVanHoudt** [comment]
You can try `var response = Hoek.clone(reply('success'))? 
I'm still note sure what you want. You want to reply, but still be able to access the response from that reply afterwards?

**Comment by Marsup** [comment]
Why would you want to call your handlers directly ? Isn't hapi's testability enough ?

**Comment by devinus** [comment]
@AdriVanHoudt Correct.

@Marsup It's not just about testability but compostability as well. For example, I could write a single handler that when composed with simple function could give me several different handlers.

**Comment by Marsup** [comment]
Shouldn't you abstract yourself from the concept of request/reply if you want composability then ?

**Comment by AdriVanHoudt** [comment]
@devinus is there a specific use case you want to use this is in?

**Comment by hueniverse** [comment]
`reply()` is how you set the payload. You can change the payload by directly manipulating `request.response` but to completely replace it, call `reply()`. That is the public interface.

**Comment by devinus** [comment]
@hueniverse I was not arguing to replace `reply()` but to allow a method to modify the payload after `reply()` has been called. You can for instance modify the `status()`, so why not the payload itself?

**Comment by devinus** [comment]
Also, you cannot call `reply()` twice within the same handler, so asynchronously setting the payload after a `Response` has been created is currently not possible.

**Comment by hueniverse** [comment]
This is why we have lifecycle extensions so you can make those changes after the handler.
