### ISSUE TITLE
Consider data in request.log/server.log to give same format

### ISSUE THREAD

**Issue by Torsph** [hapijs/hapi#2435]
Have you guys considered to let the request.log or server.log give the same format/type regardless of the data type?

Today one can use whatever type in the data parameter and that could be a problem for elasticsearch when aggregating the logs. (That is of course if one do not filter the logs.)

Would it be better to always print the data as an object or maybe a string like the error stack?

Or maybe you have a better solution to handle this problem?

Just some examples:
```
request.log(['tag'], 'Log message');

/* Gives
{
    'data':  'Invites result'
}
*/

request.log(['tag'], ['Log message', 'Some other info]);

/* Gives
{
    'data':  ['Log message', 'Some other info']
}
*/

request.log(['tag'], {'some_key' : 'Some message'});

/* Gives
{
    'data':  {'some_key' : 'Some message'}
}
*/
```

**Comment by hueniverse** [comment]
I am not sure what you are asking for.

**Comment by Torsph** [comment]
Hmm, shall we see if I can say this in a better way.

When calling: ``` request.log(['tag1', 'tag2'], <any data>) ``` the < any data > block can be of any type. 
And since developers can send what ever type, they will. 

Then we cannot expect it to be of one type. Therefore we need to have:
```
var data = getDataFromLog();
if(data is array) {}
else if(data is string) {}
else if(data is object) {}
```
we aggregating the logs.

**Comment by hueniverse** [comment]
It's not the job of the framework to enforce such logging rules. You can put whatever you want there. It is up to you to enforce a policy.

**Comment by Torsph** [comment]
I agree with you! Thanks!
