### ISSUE TITLE
Is there a way to route a route

### ISSUE THREAD

**Issue by ssylvia** [hapijs/hapi#2436]
I'm coming from express and I want to modularize my routes. In express I could do something like:

`app.use('/my-route',require('route-module');`

Then in this route-module I could do: 

`router.route('/path1').get(...`
and
`router.route('/path2').get(...`

Where the full route of both would become:
/my-route/path1
/my-route/path2
without having to include '/my-route' in every route. 

Does Hapi have something similar? If it does have something similar, is is possible to also include a check before it redirects to a module? Let's say I want to version an api and include a version url parameter:
`/{api-version}/my-route/` --> `/v1/my-route/path1`

I was thinking I could nest modules within modules to better organize an api:
```
/
|_ index.js
|_ api
  |_ v1
    |_ users
       |_ index.js
 |_ v2
   |_ users
      |_ index.js
```
Is this the best way to do this? Thanks in advance for any advice you might have.

**Comment by Marsup** [comment]
You're looking for the prefix option to register.

**Comment by codetrash** [comment]
Im having the same structured folder as @ssylvia , 

with the routes inside each module

**api/v1/auth/index.js**

```
exports.register = function(server, options, next) {

    server.route([
        {
            method: 'POST',
            path: '/v1/auth/verify',
            handler: verify
        }
    ]);

    next();
};

```

api/v1/users/index.js

exports.register = function(server, options, next) {

    server.route([
        {
            method: 'GET',
            path: '/v1/users',
            handler: getUser,
            config: { auth: 'jwt' }
        }
    ]);

    next();
};

I want to Apply Auth Strategy for those routes

I tried to Put it inside server.js
server.register(plugins, (error) => {

    if(error) {       
        throw error;
    }

     //Configire JWT Auth Strategy
    server.auth.strategy('jwt', 'jwt', {
        key: Config.jwt_key,
        validateFunc: Helper.JWTauthCheck,
        verifyOption: {algorithms:[Config.jwt_algo]}
    });

});

It failed, I know its because I defined routes in different (in each module) folder and not inside Server.js

how can I achieve this  ?

**Comment by devinivy** [comment]
Try declaring that `jwt` auth strategy prior to registering the plugins that contain the routes that use the strategy.
