### ISSUE TITLE
Will HAPI Support application/xml,text/xml Content-type?

### ISSUE THREAD

**Issue by bboysathish** [hapijs/hapi#2437]
XML Request Support, like parse the xml and convert it to JSON?

**Comment by devinivy** [comment]
Sounds like a nice plugin!

**Comment by AdriVanHoudt** [comment]
https://github.com/hapijs/faketoe

**Comment by hueniverse** [comment]
No built-in support for XML parsing. It's pretty easy to add it yourself with one of many available XML parsers.
