### ISSUE TITLE
issue using server.auth.default()

### ISSUE THREAD

**Issue by withdust** [hapijs/hapi#2441]
the docs say
Calling server.auth.default() after adding a route will have no impact on routes added prior.

But with ...

```
server.route( {path: '/one', method: 'GET', handler: function(request, reply){...} )
server.auth.default('token')
server.route( {path: '/two', method: 'POST', handler: function(request, reply){...} )
```

hitting path 'one' returns a missing authentication error

Am I misundertsanding how .default() works, or should path one not be using any auth strategy ?

**Comment by hueniverse** [comment]
I need to see how you are setting up the strategy. Most likely you are setting it as a default already.

**Comment by withdust** [comment]
Here's a fleshed out server that returns a Missing authentication error on route `/one`  ... even with the strategy's mode set to false and auth.default() called after the route is added ...

```
var Hapi = require('hapi')

var server = new Hapi.Server()
server.connection({ port: 3000 })

server.register(require('hapi-auth-bearer-token'), function (err) {
	server.auth.strategy('token', 'bearer-access-token', false, {
		validateFunc: function (token, callback) {
			callback(null, true, {})
		}
	})
})

server.route({path: '/one', method: 'GET', handler: function (request, reply) { reply() } })
server.auth.default('token')
server.route({path: '/two', method: 'GET', handler: function (request, reply) { reply() } })

server.start(function () {
	console.log('Server running at ' + server.info.uri)
})
```

**Comment by hueniverse** [comment]
The docs are not accurate.
