### ISSUE TITLE
Is it possible in a plugin to get the routes?

### ISSUE THREAD

**Issue by mdumouchel** [hapijs/hapi#2443]
I'm creating a plugin and I would like to get all the routes that have a configuration for this plugin, I looking to validate these options are setup correctly.  is there a setting or an event I can tie into?

**Comment by jonhester** [comment]
This should work:
https://gist.github.com/tobi-or-not/c7ff5282ef60f81ce7af

**Comment by mdumouchel** [comment]
When I get server.table() it returns an array of info objects that don't appear to have settings.
````
{ info:
   { created: 1425490984301,
     started: 0,
     host: 'YAMOL1150.local',
     port: 0,
     protocol: 'http',
     id: 'xxxxxxxx',
     uri: 'xxxxxxx' },
  labels: undefined,
  table: [] }
````

This is kind of what I'm doing.  I was hoping to be able to throw an error at this level.

````
exports.register = function (server, options, next) {
 var table = server.table();
    table.forEach(function(route) {
      console.log(route);
    });
    next();
}
````

**Comment by mdumouchel** [comment]
I was able to get the routes with the following.
````
server.on('start', function(){
var table = server.table()[0].table;
console.log(route.settings.plugins);
});
````
