### ISSUE TITLE
how to define custom attributes for routes in plugins?

### ISSUE THREAD

**Issue by zaggino** [hapijs/hapi#2444]
I can't find a sample anywhere in the docs. I need to write a plugin which would require additional attributes in route configuration. How to do that? Currently the route configuration doesn't allow any custom fields I think.

https://github.com/hapijs/hapi/blob/master/lib/schema.js#L237-L254

**Comment by nlf** [comment]
Scroll down to `plugins` here http://hapijs.com/api#route-options


tl;dr

```javascript
server.route({
  config: {
    plugins: {
      myplugin: { some: 'settings' }
    }
  }
});
```

Accessible from within your plugin as `request.route.settings.myplugin` (assuming you have a reference to the `request` object).

**Comment by zaggino** [comment]
thanks @nlf 
is there a possibility for plugin to validate these settings before the route is executed?
I could't find any `onRouteAdded` event and I'd like to do checks on server startup.
Was looking here: http://hapijs.com/api#server-events

**Comment by nlf** [comment]
before the route is added? no. you could validate at runtime (i.e. when your plugin needs the data), or you could listen for the server's `start` event and then iterate over the output of `server.table()` to check routes, but that's about the best you could do.

I tend to just validate it when I want to use it and make the handler return a 500 error if it's invalid.

**Comment by zaggino** [comment]
Got it all working, thanks again for the help, much appreciated.
