### ISSUE TITLE
npm install hapi  fails

### ISSUE THREAD

**Issue by erikhemrick** [hapijs/hapi#2445]
383 silly addNameRange     '0.4.27',
383 silly addNameRange     '0.4.28',
383 silly addNameRange     '0.4.29',
383 silly addNameRange     '0.4.30',
383 silly addNameRange     '0.4.31',
383 silly addNameRange     '0.4.32',
383 silly addNameRange     '0.5.0' ] ]
384 verbose addNamed [ 'ws', '0.4.32' ]
385 verbose addNamed [ '0.4.32', '0.4.32' ]
386 silly lockFile d580c141-ws-0-4-32 ws@0.4.32
387 verbose lock ws@0.4.32 /home/eh/.npm/d580c141-ws-0-4-32.lock
388 verbose registry.get http://npm-registry.prv-openclass.com/mongodb not expired, no request
389 silly addNameRange number 2 { name: 'mongodb', range: '>=1.1.0-0 <1.2.0-0', hasData: true }
390 silly addNameRange versions [ 'mongodb',
390 silly addNameRange   [ '0.9.4',
390 silly addNameRange     '0.9.4-4',
390 silly addNameRange     '0.9.3',
390 silly addNameRange     '0.9.1',
390 silly addNameRange     '0.9.2',
390 silly addNameRange     '0.9.6-7',
390 silly addNameRange     '0.9.6-8',
390 silly addNameRange     '0.9.6-9',
390 silly addNameRange     '0.9.6-10',
390 silly addNameRange     '0.9.6-11',
390 silly addNameRange     '0.9.6-12',
390 silly addNameRange     '0.9.6-13',
390 silly addNameRange     '0.9.6-14',
390 silly addNameRange     '0.9.6-15',
390 silly addNameRange     '0.9.6-16',
390 silly addNameRange     '0.9.6-17',
390 silly addNameRange     '0.9.6-18',
390 silly addNameRange     '0.9.6-19',
390 silly addNameRange     '0.9.6-20',
390 silly addNameRange     '0.9.6-21',
390 silly addNameRange     '0.9.6-22',
390 silly addNameRange     '0.9.6-23',
390 silly addNameRange     '0.9.7',
390 silly addNameRange     '0.9.7-0',
390 silly addNameRange     '0.9.7-1',
390 silly addNameRange     '0.9.7-1.1',
390 silly addNameRange     '0.9.7-1.2',
390 silly addNameRange     '0.9.7-1.3',
390 silly addNameRange     '0.9.7-1.4',
390 silly addNameRange     '0.9.7-2',
390 silly addNameRange     '0.9.7-2-1',
390 silly addNameRange     '0.9.7-2-2',
390 silly addNameRange     '0.9.7-2-3',
390 silly addNameRange     '0.9.7-2-4',
390 silly addNameRange     '0.9.7-2-5',
390 silly addNameRange     '0.9.7-3',
390 silly addNameRange     '0.9.7-3-1',
390 silly addNameRange     '0.9.7-3-2',
390 silly addNameRange     '0.9.7-3-3',
390 silly addNameRange     '0.9.7-3-4',
390 silly addNameRange     '0.9.7-3-5',
390 silly addNameRange     '0.9.8',
390 silly addNameRange     '0.9.8-1',
390 silly addNameRange     '0.9.8-2',
390 silly addNameRange     '0.9.8-3',
390 silly addNameRange     '0.9.8-4',
390 silly addNameRange     '0.9.8-5',
390 silly addNameRange     '0.9.8-6',
390 silly addNameRange     '0.9.8-7',
390 silly addNameRange     '0.9.9',
390 silly addNameRange     '0.9.9-1',
390 silly addNameRange     '0.9.9-2',
390 silly addNameRange     '0.9.9-3',
390 silly addNameRange     '0.9.9-4',
390 silly addNameRange     '0.9.9-5',
390 silly addNameRange     '0.9.9-6',
390 silly addNameRange     '0.9.9-7',
390 silly addNameRange     '0.9.9-8',
390 silly addNameRange     '1.0.0',
390 silly addNameRange     '1.0.1',
390 silly addNameRange     '1.0.2',
390 silly addNameRange     '1.1.0-beta',
390 silly addNameRange     '1.1.0',
390 silly addNameRange     '1.1.1',
390 silly addNameRange     '1.1.2',
390 silly addNameRange     '1.1.3',
390 silly addNameRange     '1.1.4',
390 silly addNameRange     '1.1.5',
390 silly addNameRange     '1.1.6',
390 silly addNameRange     '1.1.7',
390 silly addNameRange     '1.1.8',
390 silly addNameRange     '1.1.9',
390 silly addNameRange     '1.1.10',
390 silly addNameRange     '1.1.11',
390 silly addNameRange     '1.2.0',
390 silly addNameRange     '1.2.1',
390 silly addNameRange     '1.2.2',
390 silly addNameRange     '1.2.3',
390 silly addNameRange     '1.2.4',
390 silly addNameRange     '1.2.5',
390 silly addNameRange     '1.2.6',
390 silly addNameRange     '1.2.7',
390 silly addNameRange     '1.2.8',
390 silly addNameRange     '1.2.9',
390 silly addNameRange     '1.2.10',
390 silly addNameRange     '1.2.11',
390 silly addNameRange     '1.2.12',
390 silly addNameRange     '1.2.13',
390 silly addNameRange     '1.2.14',
390 silly addNameRange     '1.3.0',
390 silly addNameRange     '1.3.1',
390 silly addNameRange     '1.3.2',
390 silly addNameRange     '1.3.3',
390 silly addNameRange     '1.3.4',
390 silly addNameRange     '1.3.5',
390 silly addNameRange     '1.3.6',
390 silly addNameRange     '1.3.7',
390 silly addNameRange     '1.3.8',
390 silly addNameRange     '1.3.9',
390 silly addNameRange     '1.3.10',
390 silly addNameRange     '1.3.11',
390 silly addNameRange     '1.3.12',
390 silly addNameRange     '1.3.14',
390 silly addNameRange     '1.3.15',
390 silly addNameRange     '1.3.17',
390 silly addNameRange     '1.3.18',
390 silly addNameRange     '1.3.19',
390 silly addNameRange     '1.4.0-rc2',
390 silly addNameRange     '1.3.20',
390 silly addNameRange     '1.4.0-rc3',
390 silly addNameRange     '1.3.21',
390 silly addNameRange     '1.3.22',
390 silly addNameRange     '1.3.23',
390 silly addNameRange     '1.4.0-rc4',
390 silly addNameRange     '1.4.0-rc5',
390 silly addNameRange     '1.4.0-rc6',
390 silly addNameRange     '1.4.0-rc7',
390 silly addNameRange     '1.4.0-rc8',
390 silly addNameRange     '1.4.0-rc9',
390 silly addNameRange     '1.4.0-rc10',
390 silly addNameRange     '1.4.0',
390 silly addNameRange     '1.4.1',
390 silly addNameRange     '1.4.2',
390 silly addNameRange     '1.4.3',
390 silly addNameRange     '1.4.4',
390 silly addNameRange     '1.4.5',
390 silly addNameRange     '1.4.6',
390 silly addNameRange     '1.4.7',
390 silly addNameRange     '1.4.8',
390 silly addNameRange     '1.4.9',
390 silly addNameRange     '1.4.10',
390 silly addNameRange     '2.0.0-alpha1',
390 silly addNameRange     '1.4.11',
390 silly addNameRange     '1.4.12',
390 silly addNameRange     '1.4.14',
390 silly addNameRange     '1.4.15',
390 silly addNameRange     '1.4.16',
390 silly addNameRange     '1.4.17',
390 silly addNameRange     '2.0.0-alpha2',
390 silly addNameRange     '1.4.18',
390 silly addNameRange     '2.0.0',
390 silly addNameRange     '2.0.1',
390 silly addNameRange     '2.0.2',
390 silly addNameRange     '1.4.19',
390 silly addNameRange     '2.0.3',
390 silly addNameRange     '2.0.4',
390 silly addNameRange     '2.0.5',
390 silly addNameRange     '2.0.6',
390 silly addNameRange     '1.4.20',
390 silly addNameRange     '1.4.22',
390 silly addNameRange     '2.0.7' ] ]
391 verbose addNamed [ 'mongodb', '1.1.11' ]
392 verbose addNamed [ '1.1.11', '1.1.11' ]
393 silly lockFile 15a441d5-mongodb-1-1-11 mongodb@1.1.11
394 verbose lock mongodb@1.1.11 /home/eh/.npm/15a441d5-mongodb-1-1-11.lock
395 verbose registry.get http://npm-registry.prv-openclass.com/multipart-parser not expired, no request
396 silly addNameRange number 2 { name: 'multipart-parser',
396 silly addNameRange   range: '>=0.0.0-0 <1.0.0-0',
396 silly addNameRange   hasData: true }
397 silly addNameRange versions [ 'multipart-parser', [ '0.0.1', '0.0.2' ] ]
398 verbose addNamed [ 'multipart-parser', '0.0.2' ]
399 verbose addNamed [ '0.0.2', '0.0.2' ]
400 silly lockFile d230debe-multipart-parser-0-0-2 multipart-parser@0.0.2
401 verbose lock multipart-parser@0.0.2 /home/eh/.npm/d230debe-multipart-parser-0-0-2.lock
402 silly lockFile 5268d29e-hoek-0-0-21 hoek@0.0.21
403 silly lockFile 5268d29e-hoek-0-0-21 hoek@0.0.21
404 silly lockFile 09d21715-async-0-1-22 async@0.1.22
405 silly lockFile 09d21715-async-0-1-22 async@0.1.22
406 silly lockFile 228b00c3-request-2-11-4 request@2.11.4
407 silly lockFile 228b00c3-request-2-11-4 request@2.11.4
408 silly lockFile 3681bf0a-joi-0-0-10 joi@0.0.10
409 silly lockFile 3681bf0a-joi-0-0-10 joi@0.0.10
410 silly lockFile 23a4a0c7-hoek-0-0-x hoek@0.0.x
411 silly lockFile 23a4a0c7-hoek-0-0-x hoek@0.0.x
412 silly lockFile 463e1c03-async-0-1-x async@0.1.x
413 silly lockFile 463e1c03-async-0-1-x async@0.1.x
414 silly lockFile d7d9fa7e-request-2-11-x request@2.11.x
415 silly lockFile d7d9fa7e-request-2-11-x request@2.11.x
416 silly lockFile 63d0c94f-redis-0-8-6 redis@0.8.6
417 silly lockFile 63d0c94f-redis-0-8-6 redis@0.8.6
418 silly lockFile 77962a16-joi-0-0-x joi@0.0.x
419 silly lockFile 77962a16-joi-0-0-x joi@0.0.x
420 silly lockFile c2053527-shot-0-0-13 shot@0.0.13
421 silly lockFile c2053527-shot-0-0-13 shot@0.0.13
422 silly lockFile 75f4e88f-handlebars-1-0-12 handlebars@1.0.12
423 silly lockFile 75f4e88f-handlebars-1-0-12 handlebars@1.0.12
424 silly lockFile d580c141-ws-0-4-32 ws@0.4.32
425 silly lockFile d580c141-ws-0-4-32 ws@0.4.32
426 silly lockFile 7e89a0e1-redis-0-8-x redis@0.8.x
427 silly lockFile 7e89a0e1-redis-0-8-x redis@0.8.x
428 silly lockFile 904cc89a-shot-0-0-x shot@0.0.x
429 silly lockFile 904cc89a-shot-0-0-x shot@0.0.x
430 silly lockFile e3c6acff-handlebars-1-0-x handlebars@1.0.x
431 silly lockFile e3c6acff-handlebars-1-0-x handlebars@1.0.x
432 silly lockFile d230debe-multipart-parser-0-0-2 multipart-parser@0.0.2
433 silly lockFile d230debe-multipart-parser-0-0-2 multipart-parser@0.0.2
434 silly lockFile 5d9e9ce0-ws-0-4-x ws@0.4.x
435 silly lockFile 5d9e9ce0-ws-0-4-x ws@0.4.x
436 silly lockFile 15a441d5-mongodb-1-1-11 mongodb@1.1.11
437 silly lockFile 15a441d5-mongodb-1-1-11 mongodb@1.1.11
438 silly lockFile cef3c41c-multipart-parser-0-x-x multipart-parser@0.x.x
439 silly lockFile cef3c41c-multipart-parser-0-x-x multipart-parser@0.x.x
440 silly lockFile 713f61ad-mongodb-1-1-x mongodb@1.1.x
441 silly lockFile 713f61ad-mongodb-1-1-x mongodb@1.1.x
442 silly addNameRange { name: 'mac', range: '>=0.0.0-0 <1.0.0-0', hasData: false }
443 verbose request where is /mac
444 verbose request registry http://npm-registry.prv-openclass.com/
445 verbose request id ef97a8ff2501f455
446 verbose url raw /mac
447 verbose url resolving [ 'http://npm-registry.prv-openclass.com/', './mac' ]
448 verbose url resolved http://npm-registry.prv-openclass.com/mac
449 verbose request where is http://npm-registry.prv-openclass.com/mac
450 info trying registry request attempt 1 at 10:01:09
451 verbose etag "35X04J8O4MT2L2AEOXBW601N6"
452 http GET http://npm-registry.prv-openclass.com/mac
453 http 304 http://npm-registry.prv-openclass.com/mac
454 silly registry.get cb [ 304,
454 silly registry.get   { server: 'nginx/1.1.19',
454 silly registry.get     date: 'Thu, 05 Mar 2015 17:01:09 GMT',
454 silly registry.get     'content-length': '0',
454 silly registry.get     connection: 'keep-alive',
454 silly registry.get     etag: '"35X04J8O4MT2L2AEOXBW601N6"' } ]
455 verbose etag http://npm-registry.prv-openclass.com/mac from cache
456 silly addNameRange number 2 { name: 'mac', range: '>=0.0.0-0 <1.0.0-0', hasData: true }
457 silly addNameRange versions [ 'mac', [] ]
458 error TypeError: Cannot read property 'latest' of undefined
458 error     at next (/home/eh/.nvm/v0.10.36/lib/node_modules/npm/lib/cache/add-named.js:219:35)
458 error     at /home/eh/.nvm/v0.10.36/lib/node_modules/npm/lib/cache/add-named.js:207:5
458 error     at saved (/home/eh/.nvm/v0.10.36/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:167:7)
458 error     at Object.oncomplete (fs.js:108:15)
459 error If you need help, you may report this *entire* log,
459 error including the npm and node versions, at:
459 error     <http://github.com/npm/npm/issues>
460 error System Linux 3.13.0-45-generic
461 error command "/home/eh/.nvm/v0.10.36/bin/node" "/home/eh/.nvm/v0.10.36/bin/npm" "install" "hapi"
462 error cwd /home/eh/dev/src/hapiTutorial/ProductsAPI
463 error node -v v0.10.36
464 error npm -v 1.4.28
465 error type non_object_property_load
466 verbose exit [ 1, true ]

**Comment by Marsup** [comment]
The private npm registry you're using is faulty, nothing we can do about that.

**Comment by arthurvr** [comment]
> The private npm registry you're using is faulty, nothing we can do about that.

Issue closed then?

**Comment by Marsup** [comment]
I'd say so.

**Comment by erikhemrick** [comment]
Close it. Thanks for the help
eh
