### ISSUE TITLE
Isn't there any api document to disable compression? (gzip)

### ISSUE THREAD

**Issue by buraktamturk** [hapijs/hapi#2449]
Hello,

I couldn't find any api or key to disable compression? Is it implemented? How can i disable it?

**Comment by gergoerdosi** [comment]
Have you tried to override the mime settings? https://github.com/hapijs/hapi/blob/master/API.md#servermime

**Comment by buraktamturk** [comment]
Sorry didn't mentioned earlier, I am using 7.5. I couldn't find the mime config in 7.5. Can you show me the config or path?

**Comment by hueniverse** [comment]
You want to disable it for all mime types?

**Comment by buraktamturk** [comment]
Yes.

**Comment by kanongil** [comment]
A simple workaround, that works for some use cases, is to unset the `accept-encoding` header in one of the request handlers. If you want to disable it completely, you can do it in an `onRequest` extension handler.

**Comment by wy193777** [comment]
I can I disable compression Hapi 16? Couldn't find how on document or anywhere on the internet.
