### ISSUE TITLE
Passing strategy name to request and server.auth.scheme()

### ISSUE THREAD

**Issue by patbaker82** [hapijs/hapi#2456]
This might be a stupid idea, but I wanted to develop a plugin that can plugin.expose() functions based upon a registered authentication strategy.  Given that plugin.expose() can only be called within a plugin and not a scheme I tried to do something like (trivial example):

```javascript
exports.register = function(plugin, options, next) {

  plugin.auth.scheme('jwt', internals.implementation);

  plugin.expose('sign', function (strategy, data) {
    return internals.jwt[strategy].signAsync(data);
  });

  plugin.expose('verify', function (strategy, data) {
    return internals.jwt[strategy].verifyAsync(data);
  });

  return next();
};
```

Then when a strategy is registered:

```javascript
internals.implementation = function (server, options, name) {

  internals.jwt[name] = new JWT(options);

  return {
    authenticate: function (request, reply) {
......
```

The use case being is that I might want to register multiple different jwt strategies that implement different keys, certifications, claims, etc.  Exposing appropriate verify and sign functions specific to the registered strategy would be a nice to have.  Passing the name of the strategy in the request and to server.auth.scheme(name, function()) would allow the plugin to be more flexible to implement what I'm attempting to describe here.

Before I dive into the code and create a pull request I wanted to run it by everyone.

**Comment by hueniverse** [comment]
A better way of doing it is the way the yar plugin works. You decorate the request object when it uses the scheme.

**Comment by patbaker82** [comment]
@hueniverse Thanks Eric, I appreciate the great advice.
