### ISSUE TITLE
internals.Request.prototype._setUrl()'s this.url.query parses string param into an array for CORS

### ISSUE THREAD

**Issue by freshmatrix** [hapijs/hapi#2460]
Though this might be a bug related to [Qs](https://github.com/hapijs/qs) module that's being used in this parsing, _setUrl()'s resulted url.query contains an invalid value -- when 

For example, below url that's generated by hapi when CORS option is turned on returns *bar* param as an array.
```
'use strict';

var Qs = require('qs')
  , urlWithCors = '/api/v1/test/me?&foo=xyz&bar=123&Access-Control-Allow-Origin=http://localhost:3000/?foo=xyz&bar=123'
;

console.log(Qs.parse(urlWithCors));
```

returns
```
{ '/api/v1/test/me?': '',
  foo: 'xyz',
  bar: [ '123', '123' ],
  'Access-Control-Allow-Origin': 'http://localhost:3000/?foo=xyz' }
```

**Comment by devinivy** [comment]
I think you ought to URL-encode the `Access-Control-Allow-Origin` value: 

```
'use strict';

var Qs = require('qs')
  , urlWithCors = '/api/v1/test/me?&foo=xyz&bar=123&Access-Control-Allow-Origin=http%3A%2F%2Flocalhost%3A3000%2F%3Ffoo%3Dxyz%26bar%3D123'
;

console.log(Qs.parse(urlWithCors));
```

**Comment by hueniverse** [comment]
Generated by hapi where? What is the header doing in the uri?

**Comment by freshmatrix** [comment]
Thanks @devinivy and @hueniverse for the reply.

Looks like only happening in IE 7 and as far as I can see it sends the URL without the "Access-Control-Allow-Origin" header in the param. I am about to look into this now and see if IE7 does something odd on its own or hapi turns header into param.

**Comment by freshmatrix** [comment]
Seems like it is one of the polyfill for IE7 that's causing this issue. Will need to explore more and will re-open this issue if more clarify on root cause.
