### ISSUE TITLE
Missing dependency in 8.3

### ISSUE THREAD

**Issue by phated** [hapijs/hapi#2461]
When using 8.3, the process is crashing because it is unable to find `wreck` as a dependency of `subtext`.  I believe it is due to https://github.com/hapijs/hapi/commit/e7bdeaab7cbeabcec76fbddeb7d6bc5b7d62b8de#commitcomment-10132900

I think this is all caused by `wreck` being a devDependency of `hapi` which satisfies `subtext` so the shrinkwrap doesn't include it.  I believe this can be solved by generating the shrinkwrap file after `npm install --production` so there are no devDependencies in the tree.

**Comment by cmfatih** [comment]
+1

**Comment by itsgg** [comment]
+1
