### ISSUE TITLE
Can't use multiple 'onPreResponse'

### ISSUE THREAD

**Issue by dawnerd** [hapijs/hapi#2467]
Using 8.3.1

If I have this:

```js
server.ext('onPreResponse', function (request, reply) {
  console.log('test');
  return reply.continue();
});
```

And in another bit of code (not a plugin) that does:

```js
server.ext('onPreResponse', function (request, reply) {
  console.log('test2');
  return reply.continue();
});
```

Only the first attached 'onPreResponse' gets called.

Is this expected behavior or am I missing something obvious?

**Comment by devinivy** [comment]
Is it possible that your connection is closing prematurely?  See #2096 from 8.0.0.  I would otherwise expect using multiple onPreResponse extensions to work as you intend.

**Comment by AdriVanHoudt** [comment]
If you are **only** doing those things it should work

**Comment by arb** [comment]
My guess is in one of your 'onPreResponse' functions, you are calling `reply` which will short-circuit the request lifecycle.

**Comment by hueniverse** [comment]
Seems to work just fine.

**Comment by dawnerd** [comment]
Thanks! There was indeed a lone reply() in there.
