### ISSUE TITLE
Accessing 'request.auth.isAuthenticated' from global view context

### ISSUE THREAD

**Issue by cdroms** [hapijs/hapi#2471]
Currently I'm accessing 'request.auth.isAuthenticated' from my views by passing it in as a context property each time I call 'reply.view()'.

To cut down on repetition in my code, I was hoping I'd be able to somehow set this inside the global context object in the 'server.views()' config, but of course the 'request' object isn't accessible from my index.js (which is where I'm configuring 'server.views()').

Is there any way I achieve this?

**Comment by mtharrison** [comment]
This is related to https://github.com/hapijs/hapi/issues/2419. You can use a `onPreHandler` extension point to set it yourself.

**Comment by cdroms** [comment]
@mtharrison - I've just tried firing up your 'hapi-context-credentials' plugin but I maybe be installing it wrong :/ 

I've done:
```js
server.register([{register: hapiContextCredentials}], function (err) {
  if (err) throw err
})
```

and in my template, something similar to:
```jade
if credentials
  div logout | settings
else
  div login | about
```

but it seems to be printing out 'logout | settings' all the time now.

**Comment by mtharrison** [comment]
@cdroms Added a couple of examples: https://github.com/mtharrison/hapi-context-credentials/tree/master/examples/basic

**Comment by cdroms** [comment]
@mtharrison - thanks for building the example! :)

I still must be doing something wrong though. I've followed your JavaScript file, and I'm having no luck. Can you or anyone else spot what I'm doing wrong?

```js
var Hapi = require('hapi')
var server = new Hapi.Server()
server.connection({ port: 3000 })

var Boom = require('boom')
var db = require('./lib/db')

var routes = require('./routes')

server.views({
  engines: {
    jade: require('jade'),
  },
  path: __dirname + '/views',
  isCached: false,
  compileOptions: {
    pretty: true
  }
})

server.register([
  { register: require('hapi-context-credentials') },
  { register: require('hapi-auth-cookie') }
  ], function (err) {
  server.auth.strategy('session', 'cookie', {
    password: process.env.COOKIE_PW,
    cookie: 'beepboop',
    redirectTo: '/login',
    redirectOnTry: false,
    isSecure: false
  })

  server.route(routes)

  server.start(function () {
    console.log('Server running @ ' + server.info.uri)
  })
})
```
Excerpt from route file:
```js
{
  method: 'GET',
  path: '/',
  config: {
    auth: {
      strategy: 'session',
      mode: 'try'
    }
  },
  handler: function (request, reply) {
    reply.view('home')
  }
}
```

The jade file:
```jade
if credentials
  div(id='menu') logout | settings | about
else
  div(id='menu') login | about
```

**Comment by gergoerdosi** [comment]
@cdroms As I can see `hapi-context-credentials` sets the value of `credentials` to an empty object if the user is not authenticated. https://github.com/mtharrison/hapi-context-credentials/blob/master/index.js#L7

```
response.source.context.credentials = request.auth.isAuthenticated ? request.auth.credentials : {};
```

And `{}` evaluates to true. That's why you see the logout link all the time.

**Comment by cdroms** [comment]
@gergoerdosi ah! spot on. :+1: thanks so much for pointing that out.
I've temporarily modified `hapi-context-credentials` to do:

```js
response.source.context.credentials = request.auth.isAuthenticated ? request.auth.credentials : false;
```
I shouldn't do that though. @mtharrison 's plugin is surely doing the correct thing and maybe I just need to modify the behaviour of my jade template instead? Is there a better way to reference `credentials` from the jade file?

**Comment by mtharrison** [comment]
@cdroms No, my bad. I think it should be `null` if they're not authenticated. I intended for it to be used the way that you've been trying to. Published an update.

**Comment by cdroms** [comment]
right on! that works a treat now :) :+1:
thanks to @mtharrison @gergoerdosi - closing issue.
