### ISSUE TITLE
404 error on a exercise of makemehapi

### ISSUE THREAD

**Issue by roelof1967** [hapijs/hapi#2473]
Hello, 

I have this : 

~~~
var Hapi = require('hapi');
var Path = require('path')

var server = new Hapi.Server();

server.connection({
    host: '0.0.0.0',
    port: Number(process.argv[2] || 8080)
});

server.route({
    method: 'GET',
    path: '/',
    handler: { 
        file : Path.join(__dirname, 'index.html')
    }
});

server.start();

~~~

index.html is in the same directory then the js file.
But still I see a 404 error. 

Roelof

**Comment by jonhester** [comment]
I am unable to duplicate this on my system. I just pasted your code into a .js file, created an index.html file right next to it, and it worked for me. Are you sure that an index.html file exists in the same folder as your javascript file?

**Comment by roelof1967** [comment]
yes, see this output : 

roelof1967: ~/Web/handling $ ls

index.html  solution.js

**Comment by hueniverse** [comment]
Did you console.log the full path to make sure it is being resolved correctly?
