### ISSUE TITLE
Wreck removed when pruning with npm with the production flag

### ISSUE THREAD

**Issue by JawjLindo** [hapijs/hapi#2474]
```npm prune --production``` removes the **wreck** dependency under the following flow:

1. ```npm init``` to create the **package.json**.
2. Create the **server.js** using the code at [Using plugins](http://hapijs.com/tutorials#using-plugins).
3. Verify that the application works.
4. Run ```npm prune --production```. This will unbuild wreck, which will break the following step.
5. Attempt to run the application again.

I'm not sure where the breakdown is but the error stems from **h2o2**'s call to wreck. The only place I can see wreck listed as a dependency is in **h2o2** but it's listed in the **dependencies** object and not the **devDependencies**. I hope this is just a fluke but it seems to be consistent over multiple systems and OSes.

I am using the following as my dependencies in this sample code:
```
"dependencies": {
    "good": "^5.1.2",
    "good-console": "^4.1.0",
    "hapi": "^8.4.0"
}
```

**Comment by m-allanson** [comment]
I'm noticing the same problem with an upgrade from hapi `8.0.0` to `8.4.0`.

**Comment by jedrichards** [comment]
I think this is causing production deployments on Heroku to fail. `wreck` is unbuilt when the Heroku Node buildpack does an `npm prune --production` and the app will crash immediately on start with the error `Error: Cannot find module 'wreck'`.

Setting the `NPM_CONFIG_PRODUCTION` to `false` is a temporarily work around.

**Comment by AdriVanHoudt** [comment]
I think this is because of npm, you install all deps including wreck for hapi so h2o2 doesn't need to because it is already in hapi's node_modules. Then when pruning npm sees that wreck is devDep and unbuilds it but forget's to install it for h2o2. This is pure speculation btw I have not tested this. Could you see if wreck gets installed under h2o2's node_modules when installing Hapi?

**Comment by Marsup** [comment]
That's an npm bug, it doesn't happen with any of the npm 2.*. If you're on heroku the correct solution would be to use the correct buildpack settings to fix that : https://github.com/heroku/heroku-buildpack-nodejs#specify-an-npm-version.

**Comment by jedrichards** [comment]
Thanks for the info, yes we were on some old Node/npm versions in package.json. Will update them, which should fix it for us. Cheers!
