### ISSUE TITLE
Grouping routes

### ISSUE THREAD

**Issue by thetutlage** [hapijs/hapi#2475]
Is there any way to group routes 

```javascript
server.group({prefix: 'users'},function(route){
  route({
     method: 'GET'
  });
});
```

**Comment by bendrucker** [comment]
Yes, by registering them from a plugin and passing the `prefix` to `register` when registering the plugin

**Comment by thetutlage** [comment]
But that way i need to have a plugin registered everytime i need to prefix something.

Example i have several logical routes like

1. users
2. accounts
3. apiv1
4. apiv2

and so on

**Comment by bendrucker** [comment]
If you want the API you're asking for here, implement it by calling `server.decorate` to add a group method and use it to register plugins under the hood or manually prefix the route paths yourself.

**Comment by thetutlage** [comment]
Okay thanks for adding some light
