### ISSUE TITLE
server.register with select still executes plugin

### ISSUE THREAD

**Issue by ericclemmons** [hapijs/hapi#2476]
I've so-far successfully switched from Express & Koa to Hapi, so _thank you_ for all of the hard-work in making a great library!

**I expected a registered plugin to only execute on matching, `select`ed servers with the specified `labels`**.

## Example

```javascript
// server.js
const server = new Hapi.server();

server.connection({
  labels: ["app"],
  port: 3000,
});

server.register(
  require('./plugins/should-not-execute'),
  { select: ["label-does-not-exist"] },
  function(err) { ... }
);
```

Interestingly enough, **the plugin's `register` function still executes**, despite the specified label not existing.

I apologize if I'm misunderstanding the documentation:
> http://hapijs.com/api/#serverregisterplugins-options-callback
> `labels` – a single string or array of strings of labels used as a logical OR statement to select all the connections with matching labels in their configuration.

Is this a bug?  Am I using this incorrectly?  **Or am I confusing the single `server` instance from sub-connection configurations?**

Thanks again for Hapi!

**Comment by AdriVanHoudt** [comment]
Did some quick testing and I think that when the label is not found it will return all the connections. This because the `server.select()` works as an OR operator http://hapijs.com/api/#serverselectlabels
I don't know if this is by design or not

**Comment by hueniverse** [comment]
The function isn't executed "on" the selected connections but the selected connections are passed to the register function. This means the function is always executed and always once. If this isn't clear I'm happy to take a PR making the doc better.

**Comment by AdriVanHoudt** [comment]
To be clear a server object with the selected connections is passed right? and if the select doesn't match anything a server object will still be passed but just with no connections?

**Comment by ericclemmons** [comment]
@hueniverse I think this is more my confusion than anything.  (I opened the issue since I didn't see anything else on the internets mentioning it)

Besides, the docs state:
> `server.connects` – An array containing the server's connections. When the server object is returned from `server.select()`, the `connections` array only includes the connections matching the selection criteria.

Of _course_ the plugin would still run!

Thanks for clearing this up!
