### ISSUE TITLE
Consider allowing per-plugin options when loading multiple plugins with `server.register()`

### ISSUE THREAD

**Issue by mtharrison** [hapijs/hapi#2478]
The optional second argument to `server.register()` (plugin options) is pretty powerful and can allow you to create plugins that are fairly agnostic about how they are "mounted", which has lots of benefits. If you want to change the prefix/connection a plugin uses, you can do so without modifying the actual plugin.

Currently you can only specify these options once per call to `server.register()` and the options apply to all the plugins:

    server.register([
        {
            register: require('./sales')
        },{
            register: require('./analytics')
        }
    ], {
        routes: {
            prefix: '/api/v1/sales'    // applies to both plugins
        }
    }, 
    function (err) {

        if (err) {
            throw err;
        }
        
        server.start(function () {
            console.log('Started server');
        });
    });

If you want to specify a separate prefix for each plugin, to my knowledge you need to:

1. Update the actual plugin itself
2. Use Glue
3. Call `server.register` multiple times (using Items.serial for instance)

I think it would be useful if you could specify the plugin options for each plugin in a single `server.register` call, with perhaps an additional property like so:

    server.register([
        {
            register: require('./sales'),
            pluginOptions: { routes: { prefix: '/api/v1/sales' } }
        },{
            register: require('./analytics'),
            pluginOptions: { routes: { prefix: '/api/v1/analytics' } }
        }
    ], function (err) {

        if (err) {
            throw err;
        }
        
        server.start(function () {
            console.log('Started server');
        });
    });

**Comment by puchesjr** [comment]
@mtharrison I believe Hapi does provide the functionality you are seeking.  From http://hapijs.com/tutorials/plugins 

```
// load multiple plugins
server.register([
    {
        register: require('myplugin'),
        options: {} // options for 'myplugin'
    },{
        register: require('yourplugin'),
        options: {} // options for 'yourplugin'
    }
], function (err) {
    if (err) {
        console.error('Failed to load a plugin:', err);
    }
});
```

**Comment by hueniverse** [comment]
This was discussed in the past and I decided it better belongs in glue or another utility like it. The issue this is trying to solve is to avoid nesting `register()` calls, but that's easy to abstract in another module instead of adding complexity here.

**Comment by saidimu** [comment]
@hueniverse Requiring a separate utility for what appears to be a basic utility limits the out-of-the-box power of the plugin system, don't you think?

**Comment by hueniverse** [comment]
@saidimu sure, but that assumes we can agree on what a "simple straightforward API" means and so far we don't. Also, at this point you are going to be using more than just hapi core no matter what. Glue was part of core and used by many people. So the argument of where things belong is a pretty weak one when trying to convince me it belongs here because you just don't want more dependencies. You are going to have lots.

**Comment by indieforger** [comment]
Quick note for everyone who encounters this problem and google himself into this issue.

What worked for me was, nesting registrations of individual plugins with custom route `prefix` parameter. **That is very bad solution**.

As pointed out by @hueniverse, I totally agree, there is no point of adding more functionality to registration functionality if problem can be easily solved with glue. Take a look at this test (marked lines) [has registrations having the same plugin loaded multiple times](https://github.com/hapijs/glue/blob/v3.2.0/test/index.js#L325-L348), before rolling out your hacks.
