### ISSUE TITLE
Best Practice Project Structure

### ISSUE THREAD

**Issue by puchesjr** [hapijs/hapi#2479]
When building an ReST API project, what would be the best project structure to keep things HAPI? 

I currently have the following structure 
```
project
  -node_modules
  -server
     -server.js
      -routes.js
      -config
          -config.js
          -db.js
      -controllers
          -example.js
      -models
          -example.js
      -server.js
  -package.json
```

**Comment by lvegerano** [comment]
@puchesjr +1 I'm interested in what others have to say. I personally take advantage of hapi's ability to separate logic into modules. Here is the structure try to follow
```
project
    node_modules
    lib
        middleware
            db.js
        routes
            user
                user-routes.js
                user-controllers.js
        models
        server.js
        index.js
    index.js
```
I treat everything I can as a plugin.

**Comment by AdriVanHoudt** [comment]
I try to use the plugin system as well and make every entity a plugin e.g. user plugin, contact plugin and then my handlers/controllers orchestrates what needs to happen

**Comment by simon-p-r** [comment]
I have built a core base to handle schema loading, database connections, logging, configuration and loading core routes.  I can then load different logic into the core via plugins which encapsulate specific logic.  My current structure looks like this

````
project
    node_modules
    lib
       logger.js
       schema.js
       config.js
       dataStore.js
       methods.js
       routes.js
       core.js
       plugins.js
   routes
       endpoints
           admin.js
           api.js
           dataStore.js
       handlers
           admin.js
           api.js
           dataStore.js
   plugins
       plugin1
       plugin2
    schemata
       schema1
       schema2
       schema3
````

**Comment by AdriVanHoudt** [comment]
the problem with that is if you get a lot of endpoints the endpoints and handlers folder will quickly be unhandlable

**Comment by simon-p-r** [comment]
The project is quite large and haven't encountered that problem

**Comment by nvcexploder** [comment]
@simon-p-r what do you use to distinguish 'endpoints' from 'handlers'? Are the endpoints the main configurations and the handlers the functions handling each of the routes?

**Comment by simon-p-r** [comment]
Yes the endpoints are the config object and the handler is the request and reply function?  I use a module to require directories of exposed endpoints and concat the arrays to load into hapi.  It works well so far.

**Comment by nvcexploder** [comment]
Cool. That would jive with the way I like to order the addition of my routes. I like to have one big table where you can see all the exposed endpoints within an application or plugin with clear code-paths to where the functionality supporting the Endpoints resides.

**Comment by simon-p-r** [comment]
Yeah it gives some clarity over what you have loaded, I also expose an endpoint that is a viewer into the route table which also helps when developing.

**Comment by AdriVanHoudt** [comment]
@simon-p-r i get annoyed quicker than you I guess :D

**Comment by simon-p-r** [comment]
Still fresh to it all at the moment, time could change that though!?

**Comment by AdriVanHoudt** [comment]
let me know ;)

**Comment by devinivy** [comment]
It's worth checking out a project called [stimpy-medium](https://github.com/semateos/stimpy-medium), which built upon work done in [hapi-ninja](https://github.com/poeticninja/hapi-ninja).  Like many hapi projects, it's a plugin that can be optionally run standalone as a server.  It splits configuration, controllers, and route definitions up across several folders, organized by creating files of the same name in those folders.  For example, `controllers/api.js` would hold controllers for any routes defined in `routes/api.js`.

**Comment by przemoli** [comment]
There are limited number of technical functions code can be classified as, while in successful project, there are potentially unlimited number of business features this code can implement.

When organizing code one can make false assumption that time to search for any particular file is most important, when in fact its access pattern that matter (and obviousness of it, after all we send more then 50% of our time maintaining code!).

So keeping similar code by access pattern wins the day. Much more probable that after accessing e.g user_routes.js we will wont to access user_models.js and user_helpers.js. So lets keep those together.

It also make much easier to extract parts of API as either reusable component and/or micro-service on its own right.

Also. Node/JS is not PHP, and thankfully so! We do not have auto load based on namespace/directory correlation. We can have nice project structure AND auto loading that just works.

**Comment by SistemasLTP** [comment]
project/
	-	app.js
	-	node_modules/
	-	bussines/
		--		reports.js
	-	dam/
		--		reports.js
	-	dtm/
		--		report.js
	-	utils/
	-	public/
		--		assets/
			---			jQuery/
			---			css/
			---			font/
			---			images/
			---			etc/
	-	routes/
		--		index.js
	-	utils/
		--		dateTimeUtil.js
	-	view/
		--		js/
		--		css/
		--		index.html

**Comment by Stradivario** [comment]
One of the best applications that i used and its quite handy and configurable.

```
-node_modules(1)
-private (1)
--modules (2)
---exampleModule (3)
---exampleAPI.js (3)
---exampleRouteController.js (3)
---exampleRoutes.js (3)

```
With this approach everything is clear and the only thing that you need to do is to load the modules that way:

```
const gitRoutes = require('./private/modules/exampleModule/exampleRoutes.js');

for (var route in gitRoutes){
	server.route(gitRoutes[route]);
}
```

- In this structure you have multiple modules which you can combine if you need.For example another api that uses the same feature just copy and paste it where you need :).
- You can spawn child processes for every single module(if you wish to) 
for example if over time you found out that most of your users are using 3 modules and your api power is overwhelmed with only these 3 modules in this case you can spawn 3 independent api which serve only for these modules and you can pass via socket for availability of the current api and switch the client to preferred api if you wish to for load balancing.Most of the times you just spawn new docker container and you don't give a shit about that :D.
Anyway there are some people which prefer to create a self sustained system and others choose just to use available resources and enjoy its your choise. :))

Please share your opinion with this approach i will be really happy  :))) 

Have a hapi..... happy coding :D

**Comment by sfabriece** [comment]
I have a lot of custom sql in my handlers that I would like to abstract out as it is becoming hard to manage. What would the right way to handle that? Also I saw a lot of people referencing controllers, what do they do?

**Comment by hueniverse** [comment]
@sfabriece Post your questions to hapijs/discuss.
