### ISSUE TITLE
Ability to pass options to qs for payload parsing

### ISSUE THREAD

**Issue by kpjf** [hapijs/hapi#2480]
I'm working away on my project and noticed that when I hit a certain amount of objects in my post data that it the data in the payload was changing from a normal array ( i.e. zero indexed ) to an associative array.

As an example (I've only included the necessary details, I can add a working code snippet if needed), if you have the following form:

```html
<form action="/dummy" method="POST">
	<input type="hidden" name="dummy[0]" value="testing">
	<input type="hidden" name="dummy[1]" value="testing">
	<input type="hidden" name="dummy[2]" value="testing">
	<input type="hidden" name="dummy[3]" value="testing">
	<input type="hidden" name="dummy[4]" value="testing">
	<input type="hidden" name="dummy[5]" value="testing">
	<input type="hidden" name="dummy[6]" value="testing">
	<input type="hidden" name="dummy[7]" value="testing">
	<input type="hidden" name="dummy[8]" value="testing">
	<input type="hidden" name="dummy[9]" value="testing">
	<input type="hidden" name="dummy[10]" value="testing">
	<input type="hidden" name="dummy[11]" value="testing">
	<input type="hidden" name="dummy[12]" value="testing">
	<input type="hidden" name="dummy[13]" value="testing">
	<input type="hidden" name="dummy[14]" value="testing">
	<input type="hidden" name="dummy[15]" value="testing">
	<input type="hidden" name="dummy[16]" value="testing">
	<input type="hidden" name="dummy[17]" value="testing">
	<input type="hidden" name="dummy[18]" value="testing">
	<input type="hidden" name="dummy[19]" value="testing">
	<input type="hidden" name="dummy[20]" value="testing">
	<input type="submit" value="submit" />
</form>
```

I'll get the data in my payload object as:

```javascript
{ dummy: [ 'testing', 'testing', 'testing', 'testing', 'testing', 'testing', 'testing', 'testing', 'testing', 'testing', 'testing', 'testing', 'testing', 'testing', 'testing', 'testing', 'testing', 'testing', 'testing', 'testing', 'testing' ] }
```

But when my form has an additional input: `<input type="hidden" name="dummy[21]" value="testing">` then the data is coming back as an associative array. A la, 

```javascript
{ dummy: { '0': 'testing', '1': 'testing', '2': 'testing', '3': 'testing', '4': 'testing', '5': 'testing', '6': 'testing', '7': 'testing', '8': 'testing', '9': 'testing', '10': 'testing', '11': 'testing', '12': 'testing', '13': 'testing', '14': 'testing', '15': 'testing', '16': 'testing', '17': 'testing', '18': 'testing', '19': 'testing', '20': 'testing', '21': 'testing' } }
```

Given I'm explicitly setting the key values in the form input name attributes, the latter is the expected result. That said, the former is a nice feature.

Is this something that the hapi core is doing? Or am I doing something unexpected (explicitly adding the 0 indexed keys aside)?

**Comment by hueniverse** [comment]
@nlf ?

**Comment by nlf** [comment]
currently that's intentionally done within qs for security reasons, the default is 20 items in an array before it will be coerced into an object with numerical keys.

qs allows overriding that limit, i'd have to look to see if hapi lets you pass options to qs for payload parsing. or i'm sure @hueniverse knows.

**Comment by Marsup** [comment]
Just curious, what's the security reason ?

**Comment by nlf** [comment]
So the limit actually only applies when manually indexing keys. The reason for the limit is because without it, you can easily create sparse arrays of an arbitrary length which can cause a crash.

**Comment by kpjf** [comment]
Okay I think I understand the reasoning now. So this prevents a user creating dummy[0] with some data, then dummy[100000], as such creating a large nothing array which would create memory issues, etc...

Thanks for the clarity.

**Comment by hueniverse** [comment]
We don't currently have a way to pass options to qs but I'm open to a clear PR adding it.

**Comment by kpjf** [comment]
I don't much knowledge of hapi's core, but I do want to get to know it more if I'm going to using it on public projects. So I can have a look at this to get more exposure to the code and get a better idea of how it does what it does.

**Comment by kpjf** [comment]
FYI I created a PR in hapi/subtext that allows for passing of qs options. If / when that gets merged I can create a PR here to have new payload parsing options added here.

**Comment by DavidTPate** [comment]
Linking the two together. hapijs/subtext#7
