### ISSUE TITLE
Feature: server.decorate('request' ... )

### ISSUE THREAD

**Issue by danielb2** [hapijs/hapi#2481]
There's a lot of data on the request object. It would be useful to be able to decorate the request object with functions in addition to reply and server

**Comment by AdriVanHoudt** [comment]
you can add anything to `request.app` on any server event like `preHandler`, would that solve your case or do you want to add a function to every request object?

**Comment by danielb2** [comment]
every request object

**Comment by AdriVanHoudt** [comment]
you can do what I proposed but I'm also in favor of the decorate to work on request

**Comment by simon-p-r** [comment]
:+1:  could server.decorate also decorate server.app?.  Currently you are restricted to change value, for example if you want to pre-load the object before run-time this would be extremely useful.  I looked at glue however you can only manipulate server.settings.app.

**Comment by AdriVanHoudt** [comment]
Why decorate? You can just do `server.app.yourNewFunction = function () {}`

**Comment by simon-p-r** [comment]
Thanks @AdriVanHoudt let me see if that will work!  Just trying things out due to the experience gained from hueniversity

**Comment by AdriVanHoudt** [comment]
:+1:

**Comment by AdriVanHoudt** [comment]
I'll add updating the docs to reflect this to my to do list

**Comment by hueniverse** [comment]
@AdriVanHoudt missed that. Fixed.

**Comment by AdriVanHoudt** [comment]
Thanks!

**Comment by danielb2** [comment]
Thanks!  Looks like it got used  in https://github.com/hapijs/chairo/blob/master/lib/index.js#L27

already ;)

**Comment by ozum** [comment]
How can I access request object from the function?

        server.decorate('request', 'setLocale', function(locale) {
            this.i18n.locale = locale;  // <-- this = undefined, I assumed this = request
        });

I assumed `this` is a reference to request object like `decorate('reply', ...)` example in API docs.

**Comment by kanongil** [comment]
@ozum It is bad form to revive old issues like this.

If you think you have found a bug, create a new issue. Otherwise I advice you to use the [hapijs/discuss](https://github.com/hapijs/discuss) repo.

**Comment by ozum** [comment]
@kanongil, oh, sorry, I thought this issue is a pinpoint to ask. I'm not sure it is a bug or by design. I will create a new issue.
