### ISSUE TITLE
Trailing Parameter and Query Params not working well together

### ISSUE THREAD

**Issue by KeKs0r** [hapijs/hapi#2482]
I am building an EndPoint that is returning the Messages within a group with query parameters for Pagination:

My Route looks like this:
```javascript
path: '/messages/{groupId}',
   method: 'GET',
   config: {
       id: 'chat_get_messages',
       validate: {
           params: {
               groupId: Joi.number().required().description('ID for the group to be returned')
           },
           query: {
               page: Joi.number().integer().min(0).default(0).description('Page number')
           }
       }
   },
```
When testing this Endpoint, I am injecting a request via server.inject:
```javascript
server.inject({
           method: 'GET',
           url: '/messages/1?page=5',
       }, function(res){
           // Test Stuff
       });
```
When debugging my Route handler I see that the `groupId` is 5, but my `page` is 0, due to the default value.

When changing the path to: `/messages/{groupId}/`and injecting `/messages/1/?page=5` it works fine. Somehow I have the feeling that the whole part after `/messages/` in the first example is parsed into the groupId.

**Comment by hueniverse** [comment]
I cannot reproduce this. See new test. Also, if you can see that `groupId` is `5`, you are running the wrong test as the right value you are passing is `1`.
