### ISSUE TITLE
cannot create resource on GET error on a PATCH request

### ISSUE THREAD

**Issue by picsoung** [hapijs/hapi#2484]
Hi,

I have just started a new project in hapi and I found a weird behavior.

I have a route for a PATCH method on `/products/{productId}`
In the handler I do something like this

```javascript
    handler: function(req, reply) {
        Product.findById(req.params.productId,function(err,cell){
            if(!err){
                console.log(Object.keys(req.payload));
                Object.keys(req.payload).forEach(function(e){
                    product[e]=req.payload[e]
                })
                product.save(function(err,user){
                    if(!err){
                        console.log("updated")
                        reply(product).created('/product/' + product._id); // HTTP 201
                    }else{
                        console.log(err)
                    }
                })
            }else{
                reply(Boom.badImplementation(err));
            }
        })
    }
```

I want to use a `PATCH` http request as I am only updating part of the object.
The object is updated as expected by issue is on the reply, I want to return the path to the updated object.
i have seen examples with a `.updated` method that does not seem to exist anymore. so I used `.created` instead.
but then I got a `Cannot create resource on GET` error.

When I change my route to a `POST` or a `PUT` it works great.
Any idea why?

Thanks :)

**Comment by Marsup** [comment]
I'd say this is semantically correct. Returning a 201 for an object that already exists seems wrong. You should return a 200 or 204.

**Comment by picsoung** [comment]
Thanks @Marsup for your prompt answer
True... did not thing on a upper level.

PUT can also create resource. so 201 makes sense.

and as `updated()` does not exist anymore I would got with a `reply(object).code(200).location(uri)`

Should be better.
