### ISSUE TITLE
Forward route to another route?

### ISSUE THREAD

**Issue by hems** [hapijs/hapi#2487]
At the moment i have a "catch all" route like ````path  : '/{page*}'```` then on this route i must check if this is a page template or a user page.

At the moment this route has an "if" conditional, which directs it to the right render function.

But in an ideal world, i believe would be cleaner to have 1 route for template and 1 route for user page, and then on my "catch all" route, i can just check which kind of page it is and then "forward" it to the correct route.

something like this pseudo code:
````
handler: function ( request, reply ) {
  url = request.url.href

  if url is user_route then return request.forward( "/user_route" )

  if url is template_route then return request.forward( "/template_route" )

  return reply( "Page not found" ).code( 404 )
}
````

Would that be possible ?

**Comment by danielb2** [comment]
Can you give an example of what constitutes a user_route and a template_route? It's difficult to tell if it's possible without knowing. The routes would have to begin with something to distinguish them as such.

For example  `/user/{path*}`  and `/template/{path*}` would work, but I suspect it's not like that.   Because of how hapi routes are designed, there can't be any overlap of routes. Iow, you can't do something like

`/users/{path*}` and `/{blah*}/template`. However, what you can do is `{blah*3}/template`  if you know the number of segments.

**Comment by hems** [comment]
Actually i just realised i have a solution, but i still wonder what would be the " hapi js way"

see this pseudo code:
````
// my "catch_all"route"
user_route = require( "./user_route" )
template_route = require( "./template_route" )

handler: function ( request, reply ) {
  url = request.url.href

  if url is 'some_url_i_know_its_a_user' then return user_route.handler( request, reply );

  if url is 'some_url_i_know_its_a_template' then return template_route.handler( "/template_route" )

  return reply( "Page not found" ).code( 404 )
}
````

**Comment by hems** [comment]
answering you questions, "user_route" and "template_route" is something that i discover using an assyncronous method.

if the template exists on disk, it's a template route.

if doesn't exist, i try to fetch a user from the database.

if the user doesn't exist, then it's 404.

i know theoretically i would need to use a route for each, but for the sake of pretty urls i'm doing this rountrips on all requests ( which the result will be cached later on the process )

**Comment by devinivy** [comment]
This may be what you're looking for: [Request#setUrl](http://hapijs.com/api#requestseturlurl).

**Comment by hems** [comment]
@devinivy perfect, so onRequest i should parse the URL myself and re-route it?

there is no way of doing that from inside a route?

**Comment by devinivy** [comment]
Correct!

**Comment by hems** [comment]
@devinivy last question: is there an easy way to use hapi.js url parser on onRequest ?

ps: thanks for the clarification

**Comment by devinivy** [comment]
Sure!  The router has it's own project here: https://github.com/hapijs/call.
This will get you a start:
```javascript
var Call = require('call');

var Router = new Call.Router({});
var pathInfo = Router.analyze('/some/{path*}');
```

**Comment by arb** [comment]
@hems I would suggest creating the routes dynamically before the server starts like you said in an earlier comment. Either that or change your logic to use route parameters so you know ahead of time if it's a template or not. The path you are going down is inefficient. If you are the one creating the server, how do you not know if a user/template exists or not? Also, do you have the same route set up to serve two purposes? If so, that is bad design. 1 route => 1 predictable resource.

**Comment by hems** [comment]
@arb i'm aware of that and was asking about the router for learning purposes.

indeed the best solution is to create the routes dynamically.

i know it's bad design to have 1 route handling 2 kind of resources, but in the end of the way what maters for the end user is the experience and on this project specifically is very important to don't prefix the endpoints, for instance:

http://mysite.com/hems <~ hems user profile
http://mysite.com/about <~ about page

thanks for your insights guys!

have a nice week! 

:8ball:
