### ISSUE TITLE
content

### ISSUE THREAD

**Issue by bowerst** [hapijs/hapi#2488]
Hello!
I'm working with Matt Harrison, who is in the process of writing on book on hapi.js. I understand that your site is primarily about community. I wondered if you would consider an excerpt from Matt's unreleased book to be something that might help the members of your community understand Hapi.js better? Or maybe just offer a link on your site to the Manning Publications site where some of his chapters are offered for free before the scheduled pub date? We have an affiliate program in which you would be compensated for every book or chapter that is sold by way of your link.

We're looking for ways to get the word out on this niche book. Do you think that would be something you'd be interested in? Thanks for your time!
Toni Bowers
tobo@manning.com

**Comment by AdriVanHoudt** [comment]
I would be very interested in the book. Just fyi for as far as I know, Hapi is community owned so unless there is some way affiliate program could benefit the community there is no need for it. Maybe a section on hapijs.com to books and articles etc. would be nice

**Comment by simon-p-r** [comment]
:+1: for any hapi :book:

**Comment by bowerst** [comment]
Not sure who makes the ultimate decision on doing this, so if anyone knows, could you let me know? And thanks!

**Comment by hueniverse** [comment]
This issue should be posted in https://github.com/hapijs/hapijs.com
