### ISSUE TITLE
Listing currently registered strategies

### ISSUE THREAD

**Issue by jclaybaugh** [hapijs/hapi#2490]
Is there a way to list the current auth strategies that are loaded within a Hapi server? 

For example, I register a plugin which sets a scheme and strategy, then I want to verify that the server contains that strategy before I assign it to a route's config.

**Comment by AdriVanHoudt** [comment]
your tests should verify that

**Comment by jclaybaugh** [comment]
To be even more specific then, I am building an endpoint to utilize an array of potential auth strategies. I check through the list of available strategies *pulling the list from hapi's strategies somewhere*, then assign the endpoint to use the first found in its list.

So - again, is there a way to list the current available auth strategies registered to hapi?

**Comment by AdriVanHoudt** [comment]
look at http://hapijs.com/api#route-options under `auth.strategies` you can define an array of strategies to be tried

**Comment by hueniverse** [comment]
There is no current API to get the list of registered strategies. But it would be an odd design to pick a strategy in runtime based on what happens to be available. How would you even pick one?
