### ISSUE TITLE
How to fetch some statistics out of server ?

### ISSUE THREAD

**Issue by guptakvgaurav** [hapijs/hapi#2492]
Hi,

I need to get some basic statistics from the server. Some are "Information related to every hit. Information should be: time when request arrived, url of request, parameter of request(if any), response sent for each request, time when response was sent back."

I understand, this can be implemented with not much effort, but it would be better if server object store some of this information (may be not all), so i will re-user data from server and won't be re-eventing the wheel.

**Comment by arb** [comment]
You should check out [good](https://github.com/hapijs/good)
