### ISSUE TITLE
Prerequisite error cannot kill request lifecycle

### ISSUE THREAD

**Issue by devinivy** [hapijs/hapi#2494]
Although the [tests](https://github.com/hapijs/hapi/blob/ce924d268a0cc2446c89c4332aaf39ee8a25684a/test/handler.js#L376) verify that replying an error in a route prerequisite takes precedence over the handler, there is still no way to skip the rest of the request lifecycle.  My prerequisite is returning an error, but my post-handler extension (`onPostHandler`) is still running.

In my particular case, my post-handler assumed that it would not run if the prerequisite replied with an error.  That assumption caused an uncaught error in my post-handler, and I received a 500 error _from the post-handler_ rather than the error from the prerequisite.  Of course, error replies are not decorated with `takeover`, so there is effectively no way to end the request lifecycle upon an error in a route prerequisite.

**Comment by MathieuLoutre** [comment]
Can you post some code? I'm currently using prerequisites and they do stop the lifecycle for me.

**Comment by devinivy** [comment]
Sorry, I may have spoken imprecisely: it's (correctly) not hitting the handler, but it is hitting the posthandler.  And in my case, I get an error from the posthandler that overrides the error from the prerequisite.  Also, are you using `next` as the name of the `reply` interface?  I'll post some code here when I get a chance!

**Comment by MathieuLoutre** [comment]
Oh, I see, you mean the `onPostHandler` extension? You're saying that it's still called although a prerequisite is returning an error? That is strange...

Yes, I use `next` as a habit from previous version of `hapi` where the reply interface wasn't (yet) consistent between handler/pre.

**Comment by hueniverse** [comment]
Pre are just part of the handler and whatever they return is treated the same way. They are not extensions. If you have pre that can return an error your post handler ext must accommodate it, the same way it must accommodate handler errors.

**Comment by devinivy** [comment]
Thanks– that makes sense.  I still do find it odd that a non-error response has _some_ way to takeover, but an error response does not have any way at all.  Is there a good reason for that that I'm missing?

**Comment by hueniverse** [comment]
Errors in pre automatically do a takeover (default setting). Takeover means use that as the handler return value, not skip the lifecycle.
