### ISSUE TITLE
CORS issue with Cross Domain Font

### ISSUE THREAD

**Issue by jeffwhelpley** [hapijs/hapi#2495]
I have a font that I am hosting on a CDN which is accessed by many different subdomains. I am using the CORS settings in my hapi route like this:

```
var cors = {
        origin:            ['*.dev.gethuman.com'],
        headers:        ['Accept', 'Accept-Version', 'Content-Type', 'Api-Version', 'X-Requested-With'],
        methods:        ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
        credentials:    true,
        matchOrigin:    true
}
server.route({
            method:     'GET',
            path:       '/dist/{path*}',
            config:     { cors: cors },
            handler:    { directory: { path: './dist', listing: false, index: false } }
})
```

In prod I have my static assets on a CDN, but here I am exposing them from my local directory. To mimic the prod environment, though, I have my hosts file set so assets.dev.gethuman.com points to localhost. So, a request to assets.dev.gethuman.com/dist/somefont.woff would pull from my local directory. If I go to my.dev.gethuman.com (also pointing to localhost), the font loads fine because of the CORS settings above. If, however, I then click on a link which goes from my.dev.gethuman.com to reviews.dev.gethuman.com, the font on reviews.dev.gethuman.com is blocked with the following error:

```
Font from origin 'http://assets.dev.gethuman.com' has been blocked from loading by Cross-Origin Resource Sharing policy: The 'Access-Control-Allow-Origin' header has a value 'http://my.dev.gethuman.com' that is not equal to the supplied origin. Origin 'http://reviews.dev.gethuman.com' is therefore not allowed access.
```

The reason for this error is that the server returns a 304 not modified when reviews.dev.gethuman.com attempts to access the font file. So, the browser cache version of the font file is used. HOWEVER, that is a problem because the browser cache version has a response header of:

```
access-control-allow-origin:http://my.dev.gethuman.com
```

I thought I could fix this by changing my Hapi CORS settings to `matchOrigin: false`, however, when I do this I get the error:

```
Cannot include wildcard origin values with matchOrigin disabled
```

I can see [this is where this error is coming from](https://github.com/hapijs/hapi/blob/22b87a307d1cddb9ea1451abfc7ddf9351851263/lib/route.js#L186) but it appears that there is no way to get around it without modifying the Hapi source.

So, I can totally understand why you have this security measure in Hapi for CORS API access, but I think it does make sense to allow access-control-allow-origin to actually be a wildcard for fonts. So, I am looking for feedback on the following:

1. Is there an alternative workaround you can think of for me to do cross domain fonts with apps on different subdomains?
2. If not, then do you agree it makes sense to allow this for fonts?
3. If yes, then are you OK with me submitting a pull request to fix this?

**Comment by hueniverse** [comment]
I don't think you can return a wildcard value in the access-control-allow-origin header. The reason why you have to use `matchOrigin` with wildcards is because that's the only way you can set the header. I don't understand what you expect the end result to be here. This is not a security feature, it is just how we generate any value for the response header.

**Comment by jeffwhelpley** [comment]
OK, you are right that a wildcard with a domain is not allowed (i.e. *.gethuman.com), but according to this:

http://www.w3.org/TR/cors/#access-control-allow-origin-response-header

it does allow for a straight *. So, how can I configure Hapi to allow for:

```
Access-Control-Allow-Origin: *
```

**Comment by hueniverse** [comment]
Full wildcard is a special case. You should be able to just set it.
