### ISSUE TITLE
How set description readable text for validation error?

### ISSUE THREAD

**Issue by MikeBazhenov** [hapijs/hapi#2496]
```JavaScript
route = {
  auth: { strategies: ['token'], scope: ['admin', 'superadmin', 'concierge'] },
  payload: {
    output: 'stream',
    maxBytes: 1024 * 1024 * 5 // 5 MB
  },
 handler: function (request, reply) {}
};
```

If payload size greater than 5 mb, i want show text 'Max file size 5mb'.
How i can set up this error description?

**Comment by devinivy** [comment]
See this section of the documentation on error transformation: http://hapijs.com/api#error-transformation
