### ISSUE TITLE
Got hapi

### ISSUE THREAD

**Issue by pandeysoni** [hapijs/hapi#2497]
We would like you to know that we are using Hapi in almost all services of our platform.

Company name: Cronj IT Technologies Pvt. Ltd.
Product name or use case: We use Hapi in Enterprise application
Is it in production or development?: Production.
Contact information for further questions: monu@cronj.com
Contact information for security alerts: monu@cronj.com
Link to logo if we can showcase your company on the new site:https://avatars2.githubusercontent.com/u/10220530?v=3&s=200
User quote (with attribution) about your hapi user experience (up to 300 characters): hapi gives you the right structure to give your code structure, it makes simple for any developer to understand and debug code, quickly develop even complex apis, with deep structural validation. The beauty of code comes from way routing and controllers are written.

**Comment by hueniverse** [comment]
Moved to hapijs/hapijs.com.

**Comment by pandeysoni** [comment]
Sorry, I didn't get you. Please clarify... Thanks in advance
