### ISSUE TITLE
Hapi allows me to set headers to undefined values

### ISSUE THREAD

**Issue by wspringer** [hapijs/hapi#2500]
While testing a setup using `reply.proxy` with Nock, I ran into an issue where my nock response wasn't setting the Content-Type header. Since Nock doesn't implement the `Readable` stream implementation Hapi expects, so I needed to wrap Nocks response into the `Readable` it expects using `Readable.wrap`, and therefore had to copy the Content-Type header manually. Since it was undefined, it sets the header to undefined in transmit.js, line 251, which silently blows up. As a consequence, Nock is never able to handle the request getting made by `reply.proxy`. 

It's a complicated setup, and perhaps not many people would run into it, but it would be nice if Hapi would make a little bit more noise if its asked to set a header to undefined. 

Perhaps something like this would help:

```javascript
    var headers = Object.keys(response.headers);
    for (var h = 0, hl = headers.length; h < hl; ++h) {
        var header = headers[h];
        assert(!_.isUndefined(response.headers[header]), 'Expected ' + headers[h] + ' to be defined');
        request.raw.res.setHeader(header, response.headers[header]);
    }
```

**Comment by hueniverse** [comment]
This was changed in io.js. I don't think it's the framework's job to ensure headers are not undefined. What error do you get now and how would this change make it easier?

**Comment by wspringer** [comment]
I didn't get any error. It only shows up in debug logging.

**Comment by hueniverse** [comment]
So what's the problem?
