### ISSUE TITLE
Authentication scheme: Set custom header on authenticate

### ISSUE THREAD

**Issue by ro-ka** [hapijs/hapi#2504]
I’m implementing an authentication scheme in Hapi.js.

In my `authenticate` function I verify the request and want to set a custom header. But as I have to finish the `authenticate` function with a `reply.continue()`, I cannot pass any headers to the response.

I found #2307 and a promising solution, but `req.response` is `null`.

How can I pass my custom header to the client?

```js
var request = require('request');

exports.register = function(plugin, config, next) {
  plugin.auth.scheme('myScheme', function(server, options) {
    return {
      authenticate: function(req, reply) {
        request('http://localhost/somewhere', function(error, response, body) {
          options.validateFunc(body, function(validateError, isValid, credentials) {
            // I want to add a custom header here                
            // req.response.header('my-header', 'my-header-content')

            return reply.continue({credentials: credentials});
          });
        });
      }
    };
  });

  next();
};

exports.register.attributes = {
  pkg: require('../package.json')
};
```

**Comment by hueniverse** [comment]
You should use the `response()` auth function. In your `authenticate()` function figure out the header content (if it is dynamic) and store it in something like `req.plugins[__name__].header` or `req.app.header`, and then set the actual header after the response is set and ready.

**Comment by ro-ka** [comment]
Thanks! That’s what I needed!
