### ISSUE TITLE
EMFILE 'Failed to open file' error when hapi serves static files. hapi 8.4.0

### ISSUE THREAD

**Issue by Kyii** [hapijs/hapi#2507]
Suddenly after weeks working on an application without any problems this error (below) - trying to serve my front-end main.js - comes up irregular but continuous. After restarting the server it's gone for a while, but comes up again.
 
I saw an old issue so maybe this is related to https://github.com/hapijs/hapi/issues/1387 ? 

But i don't fully understand. Is this error related to hapi, node or maybe my build process (gulp) ?

Thank you very much for your help. Or any hint how i can further investigate this error.

hapi: 8.4.0
node: 0.10.33
gulp: 3.8.11
OSX: 10.9.5 
Chrome: 42.0.2311.90
    
    Debug: handler, error
    {
    "msec":0.32216699980199337,
    "error":"Failed to open file: EMFILE, open 'static/main.js'",
    "data": {
        "errno":20,
        "code":"EMFILE",
        "path":"static/main.js",
        "isBoom":true,"data":null,
        "output": {
            "statusCode":500,
            "payload":{
                "statusCode":500,
                "error":"Internal Server Error",
                "message":"An internal server error occurred"},
                "headers":{}
    }}}
    
    150418/083817.200, [error], message: Failed to open file: EMFILE, open 'static/main.js' 
    stack: Error: Failed to open file: EMFILE, open 'static/main.js'

**Comment by kanongil** [comment]
Static file serving is handled in the [inert](/hapijs/inert) module now. If you submit your issue there, I will have a look at it.

**Comment by Kyii** [comment]
thank you for your response. i am not using inert at all right now. is this mandatory? i am still using this:
        
    server.route({
            path: '/static/{file*}',
            method: 'GET',
            config: {
                auth: false
            },
            handler: {
                directory: {
                    path: './static',
                    listing: false,
                    index: false
                }
            }
        });

i will switch to use inert and see if errors with serving the static files will disappear. but it is kind of confusing that the errors are only sometimes present. my impression is that they are present after rebuilding static files with gulp and then reloading the server.

**Comment by Kyii** [comment]
sorry. of course i am using inert as part of hapi default. so is the above code still ok? i am using it since hapi 8.0. 
thanks.

**Comment by Kyii** [comment]
reopened it here: https://github.com/hapijs/inert/issues/24
