### ISSUE TITLE
Behaviour of server.stop and server.stop

### ISSUE THREAD

**Issue by k-sheth** [hapijs/hapi#2511]
In my testing, I need to stop the server after a certain test to test out a certain branch. But I can't call server.start again after that. Is that the expected behaviour ? Can i call server.start again after server.stop ?

**Comment by apipkin** [comment]
I've tried this out locally running a loop to start, stop, then start again. This seems to work as expected. Do you have anything you can share to reproduce locally?

**Comment by k-sheth** [comment]
apologies, i dug through my code and realised that the test setup was registering plugins but not really  doing server.start, server.stop clearly didnt have the intended effect because of that.
