### ISSUE TITLE
Tags for request-internal and auth.strategy

### ISSUE THREAD

**Issue by gansbrest** [hapijs/hapi#2512]
While playing with https://github.com/silas/hapi-bunyan logging module I noticed too many noise messages. Turns out it's related to the way my internal requests are tagged.

So let say I have this strategy defined:

    server.auth.strategy('session', 'cookie', 'optional', {
        password: 'secret',
        isSecure: false,
        ttl: 15552000000
    });

Note that my mode is optional in this case. Now internal requests generated for every route gets following tags:

tags: [
      "auth",
      "unauthenticated",
      "error",
      "session"
    ]

And because of that error tag it's captured by logging module.. Ofcourse I could patch logging module, but I'm wondering why my request is tagged with error tag, even though my mode is "optional" ? I assume it's in the route handler logic somewhere in the hapi core?

**Comment by hueniverse** [comment]
You should only see this error logged when using optional auth if the request included invalid credentials. Otherwise it will be logged as missing.
