### ISSUE TITLE
Invalid cookie value

### ISSUE THREAD

**Issue by seemsindie** [hapijs/hapi#2513]
I have a blank server running with just , and it's working fine. But when i forward the port trough NAT because i have server listening inside VM and when i try to access the API on the host machine i get this:
{"statusCode":400,"error":"Bad Request","message":"Invalid cookie value"}

Any idea why is this happening, and how to fix it?

**Comment by edimoldovan** [comment]
Looks like a validation error, at least I get similar responses when validation fails. Do you have any kind of request validation in there?

**Comment by seemsindie** [comment]
nope, just this:
    server.route({
        method: 'GET',
        path: '/wer',
        handler: function(req, res) {
          res('Hello World!');
        }
      });

**Comment by edimoldovan** [comment]
Just tried your code, works perfectly here. Can you post the rest of your app.js?

**Comment by MathieuLoutre** [comment]
I've seen that before and I'm not sure what's exactly happening (although nothing as complex as port forwarding was needed, just a simple server). The server wasn't even using any cookie related thing explicitly (no cookie auth etc.). Can you try in an incognito window?
I suspect a malformed cookie has been set somehow and hapi can't deal with it.

**Comment by seemsindie** [comment]
@edimoldovan 
var Hapi = require('hapi');

var server = new Hapi.Server();
server.connection({ port: 3000 });
server.route({
method: 'GET',
path: '/',
handler: function(req, res) {
res('Hello World!');
}
});

server.start(function () {
    console.log('Server running at:', server.info.uri);
});

But there is no issue on the host machine, but where the port is forwarded.

@MathieuLoutre Yes, it works in incognito, do you know witch cookie is the issue?

**Comment by MathieuLoutre** [comment]
@seemsindie no clue. But if you find out, I'm interested!

**Comment by seemsindie** [comment]
@MathieuLoutre i have another project on same domain 'localhost', and that project have two cookies, tr and tr_tkn. Can i somehow turn off cookie parsing, or if i can parse what i just want?

**Comment by MathieuLoutre** [comment]
Hum, I'm not 100% sure as I haven't done it myself, but I'd look here: https://github.com/hapijs/hapi/blob/master/API.md#route.config.state

**Comment by seemsindie** [comment]
@MathieuLoutre Yep, i just added 
config: {
      state: {
        parse: false, // parse and store in request.state
        failAction: 'ignore' // may also be 'ignore' or 'log'
      }
    }
to the route and it's working. 
Thanks man!

**Comment by MathieuLoutre** [comment]
Nice! Happy that we found a solution :)

**Comment by danielb2** [comment]
This happens at least when there's a space in the cookie. When dealing with legacy code and migration, this can be an issue. Should hapi really fail completely here?

**Comment by stefanwille** [comment]
I just got the same error on a freshly installed Hapi with the "hello" example from the homepage. After adding the config to the route by Mathieu it worked. Not a good experience. 

It still worked after deleting all my cookies for the domain (which was localhost).

**Comment by vv13** [comment]
thank u very much.

**Comment by khromov** [comment]
Same issue after following the "Getting started" guide at https://hapijs.com/

**Comment by george-norris-salesforce** [comment]
Wait, you have to ignore a "failAction" to make cookies work? 🙄

**Comment by blex41** [comment]
@george-norris-salesforce you can also disable the [`server.options.state.strictHeader`](https://github.com/hapijs/hapi/blob/master/API.md#-serveroptionsstate) option to allow malformed cookies:
```
const server = new Hapi.Server({
    host: '0.0.0.0',
    port: 3000,
    state: {
      strictHeader: false
    }
});
```
I had the same problem with a cookie value from a thrid party which included spaces. This fixed it.

**Comment by lucaswxp** [comment]
I solved like this

```

server.connection({
  host: '0.0.0.0',
  port: port,
  state: {
    ignoreErrors: true
  },
  }
});
```

**Comment by svallory** [comment]
This just happened to me. It happens due to a malformed cookie. The boom error data contains the name of the cookie which is breaking the request parsing. If you delete it, the problem is fixed

**Comment by lucaswxp** [comment]
@svallory In case the cookie is generated in a third-party service which you have no control, I recommend the configuration above.

**Comment by BigBlueHat** [comment]
For posterity, Microsoft's MSAL authentication libraries use un-escaped spaces in their cookie values. Consequently, `strictHeader: false` (per above) is required to use those client-side libraries with a hapi-based server.
