### ISSUE TITLE
Can I pass a route handler to another route handler?

### ISSUE THREAD

**Issue by namlet** [hapijs/hapi#2515]
I'd like to pass a request to a generic route handler and have that function determine which route handler to pass the request onto. Is this possible?

For instance, a user POSTs to the /message resource. In that message there is a type parameter. If the type is sms, I want to send it to the twilio route handlers contained in a different route file. If the type is email, I'd send it to a different route handler.

Is there any way to simple pass the request along to another handler, like middleware works?

**Comment by edimoldovan** [comment]
I wouldn’t do that with passing the request to another route, but instead perhaps handling it with different controller methods

**Comment by namlet** [comment]
So are you suggesting that I just define functions outside of the route handlers themselves, like in a /lib directory and call those functions directly? I'd prefer to allow direct access to the POST sms route and still support the more generic /message endpoint that can use the same code. I suppose both the direct /sms and indirect /message could call the same function, but I'm not sure the best way to structure that. This is my first Hapi app (I generally use Express) and I'm trying to make this as simple as possible.

Is there a pattern on how Hapi is designed to handle this scenario? In my view, the route handlers *are* the controllers, and I don't want to create different handlers that do the same thing. That's not very DRY.

Am I understanding you accurately?

**Comment by edimoldovan** [comment]
No, I am suggesting to catch the route with a path like this `*` and then based on the url decide what to do.
The fact that you want to reuse code is another reason to do something like this, because having handlers defined separately, you may use them in more than one route if you want.

**Comment by namlet** [comment]
Unfortunately I can't route based entirely on the path. Maybe I didn't explain well. /message is a generic route to send any type of message. This is a requirement, and is outside of my control. The type of message could be sms, email, blah, blah, and it's an array, so it can be multiple messages of various types. Based on introspection of the type of message being sent, I need to call an appropriate handler for that message.

**Comment by namlet** [comment]
So then, can I do pre-processing on the request to dynamically determine the appropriate handler to call?

**Comment by arb** [comment]
Why do you want to call a different handler? One route, one handler. I would add some `pre` functions to this route and do the majority of the processing there.

You could also use the "onRequest" [extension point](https://github.com/hapijs/hapi/blob/master/API.md#request-lifecycle), check the payload and then use `request.setUrl()` to reroute the request.

**Comment by edimoldovan** [comment]
@namlet This means that you get routes which look like this path: `"/message/{type}”`? If this is the case, then just use this as your path and then in the handler call any function you want based on `request.params.type`.

**Comment by namlet** [comment]
@edimoldovan No, I get a POSTed /message with a json payload that includes type in each message item. i.e. {[ {message: 'hi', type: 'sms'}, {message: 'bye', type: 'email'} ]}

**Comment by namlet** [comment]
@arb so request.setUrl() routes the request internally? Meaning, it doesn't send a redirect HTTP response to the client?

**Comment by edimoldovan** [comment]
@namlet Than the only difference is that you will reach data under `request.payload`. Log it in the console in that handler and you’ll see all your posted data there.

**Comment by namlet** [comment]
@edimoldovan Sorry, I don't understand how that allows me to call a handler based on the type of the message. I know how to see the payload in the handler, but I need to choose a handler *based on* the payload, not the parameters. My apologies if I'm being dense.

**Comment by edimoldovan** [comment]
So if you have the type in the payload, in any way, I would do this:
```
funtion handleSMS() {
  return “SMS habdled”;
}

...

handler: function(request, reply) {
  // lets assume type = “SMS”;

  if (type === “SMS”) {
    handleSMS();
  }
}
```
Very roughly, this is what I mean. Not sure though if this is what you need.

**Comment by namlet** [comment]
@edimoldovan That's basically what I was asking in my first response. Define some function that gets called based on the type of the message. I don't want to define that function in the same context as the routes though, as my Twilio routes load libraries that are unneeded for other routes. So I'd need to create a library of functions that operate in the appropriate contexts. That seems complex. Still not clear on why I can't just pass the request along to another handler to finish off the request. Isn't that the spirit of middleware? Or should I just be using Express to accomplish these things?

**Comment by arb** [comment]
@namlet have you tried any of the suggestions given so far? You'll learn a lot more getting in there and writing some code.

Try the extension point/setUrl method, or experiment using `pre` methods and see how far you can get. Then you can ask specific questions when you have problems.

**Comment by namlet** [comment]
@arb I have tried the suggestions. But the reason I was asking on this board was to hopefully get some experience from the developers of this software, specifically on how something like this was intended to be done. I know I can hack around and see what happens. But that often results in doing things poorly because of a lack of understanding of the underlying principles that this project was built on. Its something I caution my junior developers against -- simply hacking until it works.

To answer your question more specifically, the onRequest method hasn't processed the payload yet as described clearly in the documentation you pointed me to, making it impossible for me to determine what route to forward to as you suggested. The onPreHandler method has processed the payload so I can determine where to forward the request, but no longer has access to the setUrl method the onRequest method is decorated with. So I can either decide where to go, or know where to go, but not both. Very Heisenberg of Hapi, no? (http://en.wikipedia.org/wiki/Uncertainty_principle)

So I remain at my previous location, and again inquire if there is a way to accomplish what I have perhaps inadequately described above. Can Hapi accomplish this or not?

Thank you for your continued patience and support.

**Comment by arb** [comment]
The short answer is "no". You can't do it like you would in Express as hapi purposely does not have a concept of middleware. You'll have to solve the problem differently.

I would suggest extracting the common logic from your /messages route handler and your other twilio route handlers into `pre` functions and just reusing the common logic that way. Assuming that reusing logic from two different routes is your primary goal. You could also just create a common module and require it as needed.

**Comment by danielb2** [comment]
@namlet 

This is what you want.

Did you have a different syntax in mind perhaps?

``` javascript
module.exports.messages = {
   description: 'Generic message handler',
   handler: function (request, reply) {

    if (request.payload.type === 'SMS') {
         return module.exports.SMSmessages.handler(request, reply)
    }
    // Handle other types
   return reply(Boom.internal('unknown message type'));
}

module.exports.SMSmessages = {
    description: 'Handles SMS messages',
    handler: function (request, reply) {
        // do your SMS stuff here
        return reply('done and done');
    }
}

server.route({ method: 'POST', path: '/messages', config: Controllers.messages });
server.route({ method: 'POST', path: '/sms', config: Controllers.SMSmessages });
```

**Comment by namlet** [comment]
@danielb2 Exactly what I was looking for, THANK YOU!!!

**Comment by danielb2** [comment]
Glad to help :)
