### ISSUE TITLE
Means to force plugin registration to complete prior to server.inject

### ISSUE THREAD

**Issue by garthk** [hapijs/hapi#2517]
As far as I can tell, we need to `start` the server to ensure all plugins' `register` methods and their `server.dependency` calls' `after` arguments have called `next`. Also noticed by @hulbert, who reminded me of the problem.

**Comment by hueniverse** [comment]
Not sure what you are asking for. I can expose the dependency validation logic and allow you to run it directly, or I can move some of the `server.start()` logic out into an `init()` method that does some of the work but does not start the server. The hard part is figuring out which actions to take in `init()` and which to defer to `start()` (e.g. start the cache? start the heavy measurements?).

**Comment by garthk** [comment]
The main problem for me was having to `server.start` so I could `server.inject` in tests of my plugins with dependencies. Cache yes; heavy measurements no?

**Comment by MandarinConLaBarba** [comment]
I'm also running into this problem, I think. Basically I'd like to have the cache policies initialized without starting the server, so that integration tests that touch the cache layer can be performed w/ `server.inject` without having to first call `server.start()`.
