### ISSUE TITLE
More than  5s for generate reponse !

### ISSUE THREAD

**Issue by andrelec1** [hapijs/hapi#2519]
Hello i have simple route with a request SQL ...

    {
        method: 'GET',
        path: '/getAllContents',
        handler: function (request, reply) {

            bdd.getConnection(function(err, connection){
                if(!err) {
                    connection.query(
                       " // sql request"
                        function(err, rows){
                            if(err != null){
                                console.log(err);
                                reply("error sql.").code(901);
                                return;
                            }
                            reply(rows);
                        });
                }else{
                    reply("error sql.").code(901);
                }
                connection.release();
            });
        },
        config:{
            plugins: {
                policies : ['WsseVerif']
            },
            validate: {
                query: {
                    id: t.number()
                }
            }
        }
    }

when i excute the sql requeste in phpmyadmin, the resulte come in 0.0008 sec for 43174 lines ...
But good-console say the reponse is general in more than 5 secondes ...
How improuve performance ?

**Comment by Marsup** [comment]
Unlikely to be hapi's fault, try to narrow down the timings by measuring time spent in your handler's operations.

**Comment by andrelec1** [comment]
with this code : 

     handler: function (request, reply) {
            
            var startTime = new Date().getTime();
            var elapsedTime = 0;


            bdd.getConnection(function(err, connection){
                if(!err) {
                    connection.query(
                        'SELECT ctn.*, ctn_br.id as cb_id, ctn_br.contenu_id as cb_contenu_id, ctn_br.branche_id as cb_branche_id  FROM `client_branche` as cb ' +
                        'INNER JOIN branche b ON b.id = cb.branche_id ' +
                        'INNER JOIN categorie c ON b.id = c.branche_id ' +
                        'INNER JOIN contenu_branche ctn_br ON b.id = ctn_br.branche_id ' +
                        'INNER JOIN contenu ctn ON ctn.id = ctn_br.contenu_id ' +
                        'INNER JOIN utilisateur u ON if(u.client_id, u.client_id = cb.client_id, 1) AND u.u_pseudo ="' +
                        Entities.encode(request.headers.user) + '"',
                        function(err, rows){
                            if(err != null){
                                console.log(err);
                                reply("error sql.").code(901);
                                return;
                            }
                            
                            elapsedTime = new Date().getTime() - startTime;
                            console.log(elapsedTime);
                            
                            reply(rows);
                        });
                }else{
                    reply("error sql.").code(901);
                }
                connection.release();
            });

![capture4](https://cloud.githubusercontent.com/assets/3273204/7366402/3df4b998-ed98-11e4-9c75-29ee87df1b75.PNG)

well sql take 2 secondes ( and only 0.0008 in phpmyadmin ) why ?
and hapi take 3 secondes for generating reponse ?

**Comment by Marsup** [comment]
Is it localhost ? The time you see is the time it took to transmit the whole response, if the response is big, the time will be.

**Comment by andrelec1** [comment]
no, its on vps ...
"rows" have 43174 lines ... yes its big but not very big !
the application take more than 30seconde for download all json , this part its not a probleme ...

The problème is for generating response by hapijs ...

well well , i seed a error on my requeste but for the moment its on testing base ...
i juste missing "DISTINCT" in my request ...

Now my requeste return 11254 result, and hapi take 500 ms for generating response 
( result lines is like : 
{"id":21770,"r_libelle":"1","question_id":6228,"type_reponse_id":1,"r_valeur":1,"r_ordre":1,"r_chemin_icone":null}
)

but when the release project can handle 50k results

**Comment by edimoldovan** [comment]
I generally would say it is not a good idea to return that many rows in one call. Why can’t you use some sort of pagination?

**Comment by Marsup** [comment]
This doesn't seem to be an issue with hapi itself, re-open an issue on the hapijs/discuss repo when you know more.

**Comment by andrelec1** [comment]
@edimoldovan this for the first synchronisation ... i juste need send lot of information one time without crash/slow down my api for other user !

@marsup the probleme is when you have more than 1000 result in reply the time increases exponentialy
