### ISSUE TITLE
API wart: server.dependency after method lacks options

### ISSUE THREAD

**Issue by garthk** [hapijs/hapi#2520]
I find myself having to do this a fair bit:

```
function register(server, options, next) {
    server.dependency(['auth-plugin'], function (_server, _next) {
        after(_server, options, _next));
    }
}

function after(server, options, next) {
    // ... register routes, etc
}
```

Sure, I could use closures… but if the `after` API is designed around closures, why are we passing it `server`? If there's a reason to pass `server`, there's a reason to pass `options`. 

Do we have a bug category for "API changes waiting for enough friends to justify a major version bump"?

**Comment by hueniverse** [comment]
What's the issue against using a closure here? I understand the question but I'm trying to think if passing `server` is that big of a deal to bother with.

**Comment by garthk** [comment]
We fixed the 1-ary callback style for server methods because it stood out. This stands out in the same way, for me. We force use of closures to get `options`, but not to get `server`. Most of the API, if I ask "why?", I learn something useful from the answer. This, not so much. I think it's a wart.

To fix it, we could get away with calling `after` with just `next` and force use of closures for both `server` and `options`. I think it's tidier to echo the registration API and call with `server, options, next`, but I could argue for either way.

That said, I wouldn't bump the major for just this wart. I'd batch up a bunch of wart fixes.

**Comment by hueniverse** [comment]
I decided to keep the API as is but to expose the options via the realm object so you no longer need a closure.
