### ISSUE TITLE
Header based routing

### ISSUE THREAD

**Issue by KeKs0r** [hapijs/hapi#2521]
Hi,

I am looking into a way to version my API. And I don't really like the idea of using the API version in the URL. So I am trying to work with Accept headers. 

As far as I could see there is currently no way to route based on headers, correct? Is that maybe something to consider? Restify is providing something similar:
```
var PATH = '/hello/:name';
server.get({path: PATH, version: '1.1.3'}, sendV1);
server.get({path: PATH, version: '2.0.0'}, sendV2);
```

In restify it works with a `Accept-Version` header. It could also be something. Just wanted to hear what you think about it or if it is too "api" specific.

**Comment by DavidTPate** [comment]
Hi there! What you're talking about is normally referred to as `Content Negotiation` and I'd definitely suggest continuing on your current route for versioning.

Check out [hapi-negotiator](https://github.com/felipeleusin/hapi-negotiator) I think it will get you what you need.

**Comment by franciscogouveia** [comment]
I was also looking for something like this. I tried the hapi-negotiator plugin for versioning. It does the job of having different handlers depending on Accept header.

Although, it has a limitation. There is no way to define validation and response schemas per version, as far as I could discover.

Does anyone know if this is possible or if there is any alternative to the module?

**Comment by kanongil** [comment]
I would probably create separate paths for each version (`/v1/…`, `v2/…`, etc) and reroute incoming requests using `setUrl()` in a custom `onRequest` handler based on the value of whatever header you want.

**Comment by hueniverse** [comment]
For now, I would use @kanongil's suggestion. Versions is a tricky topic and I would not want to pick one solution over another. I think writing a generic plugin that maps headers to path structure is the best approach. If it proves to be too slow, we can look for ways to optimize.
