### ISSUE TITLE
Invalid Path Error, when using '//' instead of '/'. Running ProxyPass to route requests to Node.

### ISSUE THREAD

**Issue by ykiran** [hapijs/hapi#2523]
Hi,
I'm running both Apache and Node on the same machine. I'm using **ProxyPass** to route requests matching a pattern to Node running on another port. When using Hapi to configure routes, I can't use '/'; as such I'm using '//'; for ex: **'//show/{user}'**.
This is where I'm getting the following error.

> Error: Invalid path: //show
    at Object.exports.assert (/root/apisrc/node_modules/hapi/node_modules/hoek/lib/index.js:678:11)
    at internals.Router.analyze (/root/apisrc/node_modules/hapi/node_modules/call/lib/index.js:190:10)
    at new module.exports.internals.Route (/root/apisrc/node_modules/hapi/lib/route.js:79:46)
    at internals.Connection._addRoute (/root/apisrc/node_modules/hapi/lib/connection.js:352:17)
    at internals.Connection._route (/root/apisrc/node_modules/hapi/lib/connection.js:344:18)
    at internals.Plugin._apply (/root/apisrc/node_modules/hapi/lib/plugin.js:440:14)
    at internals.Plugin.route (/root/apisrc/node_modules/hapi/lib/plugin.js:415:10)
    at Object.<anonymous> (/root/apisrc/test.js:13:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

And, here is the route function:
```
server.route({
   method: 'GET',
   path: '//show',
   handler: function(request, reply){
   reply("Hello there");
   }
});
```
This route works when I'm using express. 
Am I doing something wrong here? Is there another way to achieve this?
Thanks in advance for your help.

**Comment by dciccale** [comment]
the route should start with only 1 slash

**Comment by ykiran** [comment]
@dciccale True, but as I mentioned, I'm using **ProxyPass** to route requests to node. As such single slash is not working. I've to mention two slashes. For example: I'm **routing** all **URLs** ending with **/api to node**.
So, for the endpoint **/api/vendor**, I need to mention as **//vendor**, else I get an error **Cannot GET //vendor**
I can create that route in **expressjs**, but when I do the same in **Hapi**, I'm getting the **invalid path** error.
Is there any workaround in Hapi or for my setup, I've to be content with using expressjs?

Thanks,
Kiran.

**Comment by dciccale** [comment]
i know this is a bit hacky but you could try something like this working example

```javascript
var Hapi = require('hapi');

var server = new Hapi.Server();
server.connection({port: 3000});

server.route({
  method: 'GET',
  path: '/vendor',
  handler: function (request, reply) {
    reply('hello world');
  }
});

server.ext('onRequest', function (request, reply) {
  // remove double slash
  var path = request.url.path.replace(/\/\//, '/');
  // set the url to an existing path in hapi
  request.setUrl(path);
  return reply.continue();
});

server.start();
```

```bash
$ node server
$ curl http://localhost:3000//hello
hello world
```

**Comment by dciccale** [comment]
i thinks is enough with the example, but in any case.. every request you proxy to hapi, will trigger the "onRequest" event so then you remove the double slash to an existing and valid rout path.

**Comment by Marsup** [comment]
This looks like a misconfiguration of nginx to me.

**Comment by Marsup** [comment]
Anyway this belongs to the discuss repo, not here.

**Comment by ykiran** [comment]
Hi @dciccale Thanks a lot for that **hack**. Works for me now.
 I'm not sure if this is the way forward, but this is a starter.

Hi @Marsup I'm not using Nginx, just Apache. 

Thanks,
Kiran.

**Comment by Marsup** [comment]
Sorry, same applies to Apache, this should not be forwarded with that extra slash, this doesn't look like a hapi problem.
