### ISSUE TITLE
several auth strategies for the route

### ISSUE THREAD

**Issue by PavelPolyakov** [hapijs/hapi#2526]
Hi,

I use the next syntax for the route config:

~~~javascript
"config" : {
      "auth": {
        "strategies": [
          "logged-in",
          "user-with-app"
        ]
      }
    }
~~~

In the documentation it's stated, that:
> The strategies will then be attempted in order until one succeeds, or they have all failed.

And that's the way it works.

How can I try several strategies for the route, not with OR condition, but with AND condition. Meaning I want all of them to be valid, in order to access the route.

**Comment by PavelPolyakov** [comment]
The question is still open.

Any advice is appreciated.

**Comment by AdriVanHoudt** [comment]
does setting `mode` to `required` work?

**Comment by PavelPolyakov** [comment]
@AdriVanHoudt 

No,

if I do this:
~~~
    "config" : {
      "auth": {
        "mode" : "required",
        "strategies": [
          "logged-in",
          "user-with-app"
        ]
      }
    }
~~~

**Comment by Marsup** [comment]
This looks weird, usually a user authenticate with a (single) service, then gets a token (cookie, jwt, whatever). It would be cumbersome to ask your users to login on ALL services to access your api, I don't see the use-case here.

**Comment by PavelPolyakov** [comment]
Well,

I think there could be different cases for the auth strategies, they should not correspond the idea that the customer was authenticated through some service.

For example, we can use the auth strategies to understand if the customer is allowed to access the certain edit article action. So we should apply two strategies - 1. the user is authenticated, 2. the user is author of the article .

Does it make sense?

**Comment by Marsup** [comment]
Well they do so you're using them the wrong way. You can use the built-in `scope`s to achieve that considering you set roles and not permissions. Otherwise there's `mrhorse` or `hapi-authorization` that may help you.

**Comment by MathieuLoutre** [comment]
@PavelPolyakov I like the sound of it, but it poses a few problems I think:
- You'll need to create auth strategies for each of your "permissions"
- Passing the authenticated scope from one strategy to the other seems a little dirty (checking that the auth user is the author requires the user, which you probably have from checking that the user is authenticated correctly in the first place)

I like the final syntax it would produce, but I worry it might end up just bending the rules/config instead of having something really nice.

**Comment by Marsup** [comment]
He's mistaking authorization for authentication, this is definitely not the way to go guys.
Anyway if you want to discuss further I'll let you open an issue in the discuss repo, this is not the place.

**Comment by PavelPolyakov** [comment]
@Marsup 

Thanks, I would go with mr-horse, becase, if I understood correctly - scopes are working the same as auth way. If one passes, then the customer would go further.

Regards,

**Comment by Marsup** [comment]
Roles are usually a better way to represent permissions long-term, but whatever suits you.
