### ISSUE TITLE
help with server.injection

### ISSUE THREAD

**Issue by polizinha** [hapijs/hapi#2529]
Hello everybody!
I'm doing tests using lab and mocking a request with `server.injection`, but when my request hit function, I have `{}` at `console.log(request.query)`. Can you help me?

    lab.test('GET /get', function (done) {
        var injectOptions = {
            method: 'GET',
            url: '/a121212/reckon/get',
            payload: querystring.stringify({registry: "12", start: "2015-02-01", end: "2015-02-02"})
        };
        server.inject(injectOptions, function (response) {
            console.log(response);
            Code.expect(response.statusCode).to.equal(200);
            done();
        });
    });

**Comment by AdriVanHoudt** [comment]
you don't have a query. I think you are putting your query inside the payload and not in the url like `a12121212/reckon/get?registry=12`

**Comment by polizinha** [comment]
oh jesus...

    var injectOptions = {
        method: 'GET',
        url: '/a121212/reckon/get?'+querystring.stringify({matricula: "12", inicio: "2015-02-01", fim: "2015-02-02"}),
    };

TY!

**Comment by AdriVanHoudt** [comment]
np ^^
