### ISSUE TITLE
root path and `route: {prefix: '...'}`

### ISSUE THREAD

**Issue by gr2m** [hapijs/hapi#2531]
When running the following code, my expectation would be that http://localhost:1337/debug/ would return `ok`, instead it returns a 404. When I remove the trailing slash, I get `ok`. But that's not what I expect, as I set the path to `/` in the `server.route` call.

```js
var Hapi = require('hapi')

var server = new Hapi.Server()
server.connection({
  port: 1337
})

var myPlugin = {
    register: function (server, options, next) {
      server.route({
        method: ['GET'],
        path: '/',
        handler: function (request, reply) {
          reply('ok')
        }
      })
      next()
    }
}

myPlugin.register.attributes = {
    name: 'myPlugin',
    version: '1.0.0'
}

server.register(myPlugin, {
  routes: {
    prefix: '/debug'
  }
}, function (error) {
  if (error) {
    console.log(error)
  }
})

server.start(function () {
  console.log('Server running at:', server.info.uri);
});
```

This issue might be related: https://github.com/hapijs/hapi/issues/1720

**Comment by AdriVanHoudt** [comment]
I think this is due to https://github.com/hapijs/hapi/blob/master/lib/route.js#L28 If you have a prefix and the route is just `/` it gets turned into nothing

**Comment by gr2m** [comment]
Yeah, it seems to be by design as per this commit: https://github.com/hapijs/hapi/commit/d9c5243e54ba41e22ebf037fc4ac6b1ff7eeda9c. But it's not what I'd expect. Ideally, it would return `ok` for both http://localhost:1337/debug & http://localhost:1337/debug/, or it would redirect http://localhost:1337/debug -> http://localhost:1337/debug/ as other servers do

**Comment by AdriVanHoudt** [comment]
hmm as per this issue (https://github.com/hapijs/hapi/issues/1720) this behaviour does look normal to me

**Comment by gergoerdosi** [comment]
@gr2m You can set `stripTrailingSlash` to `true` in router configuration.

**Comment by gr2m** [comment]
@gergoerdosi true dat, thanks for the pointer, I didn't know about the option. Feel free to close the issue if nobody agrees with my expectations :)

**Comment by hueniverse** [comment]
The current behavior is more consistent with the intention of the prefix feature. This is a special case and we ended up going the other way with it. If this wasn't clear to you, we should fix the docs.

I'll take a PR making this more obvious.

**Comment by FalloutX** [comment]
I Thought I'll be able to contribute on this one, But I guess this has already been updated in Documentation. I also think It was very clear to someone like me, who has been doing hapi only since 2-3 weeks.
