### ISSUE TITLE
Documented method for serving static files may be incorrect

### ISSUE THREAD

**Issue by geuis** [hapijs/hapi#2535]
Relevant docs: http://hapijs.com/tutorials/serving-files

I was attempting to use the documented method to serve static files but was unsuccessful. Sample code looks like the following, and I use a directory structure like /static/css, /static/js, /static/img.

```javascript
// 1st attempt (verbatim code from documentation except "path: 'public'" is "path: 'static'"
server.route({
  path: '/{param*}',
  method: 'GET',
  handler: {
    directory: {
      path: 'static'
    }
  }
});
```
```javascript
// Successful. Note I have added "static/" to precede "{param*}" in the path property.
server.route({
  path: 'static/{param*}',
  method: 'GET',
  handler: {
    directory: {
      path: 'static'
    }
  }
});
```

Directly following the example code in the docs under "Directory handler options", it says "The above route will respond to any request by looking for a matching filename in the public directory."

From my testing, this is not true unless that path property defined in the handler.directory precedes the {param*} string.

I don't know if the documentation is wrong, or if the code implementation is. So I'm filing this issue to make others aware.

**Comment by kanongil** [comment]
I am unable to replicate this issue. If you still believe this is a hapi issue, can you please submit a failing test case as a pull request to https://github.com/hapijs/inert?
