### ISSUE TITLE
Objects passed to views by default?

### ISSUE THREAD

**Issue by geuis** [hapijs/hapi#2537]
I'm trying to see if the request and response objects are exposed to views by default, or if its necessary to pass it through to each view call.

On a broader topic, are there any objects accessible in the view other than 'global' by default?

**Comment by arb** [comment]
Per [this](https://github.com/hapijs/vision/blob/master/lib/index.js#L89-L102) you get the context you pass in as well as `params`, `payload`, `query` and `pre`.

**Comment by geuis** [comment]
@arb @hueniverse I'm looking into this again and I do not see the internals.handler method being called at all. The context object is not being passed to reply.view.

**Comment by hueniverse** [comment]
They are only passed when you use the reply handler, not when you call `reply.view()` yourself. Either way, this issue belong in the hapijs/vision.

**Comment by geuis** [comment]
@hueniverse Yes, I'm working through an issue over there and referenced here in case others in the future need to track it.
