### ISSUE TITLE
can not set content-length in head request

### ISSUE THREAD

**Issue by gitawego** [hapijs/hapi#2540]
for a HEAD request, I can't set content-length by using reply, I have to use internal method to set it:
```js
server.route({
        method: 'GET',
        path: '/release/{param*}',
        handler: function (request, reply) {
            var filepath = __dirname + '/data/release/' + request.params.param;
            if (!fs.existsSync(filepath)) {
                return reply(Boom.notFound());
            }
            var fileStat = fs.statSync(filepath);
            if (request.method === 'head') {
                //doesn't work
                //reply().header('accept-ranges','bytes').bytes(fileStat.size);
                request.raw.res.setHeader('content-length', fileStat.size);
                return  reply()
                    .header('accept-ranges', 'bytes');
            }
            reply(fs.createReadStream(filepath))
                .header('accept-ranges', 'bytes')
                .bytes(fileStat.size);
        }
    });
```

**Comment by arb** [comment]
`request.method` will never be equal to "head" in this `handler`. You've specified the method for this handler to be "GET" and that is the only method that will be routed to this handler. 

You should also take a look at the [built-in-handlers](https://github.com/hapijs/hapi/blob/master/API.md#built-in-handlers), specifically the "file" one.

**Comment by kanongil** [comment]
@arb Actually, all `GET` methods respond to `HEAD` request through some internal magic. I have had to use it to override the `HEAD` response once.

@gitawego Hapi removes the content-length from any `HEAD` response. It is possible that this not the best way about it, as the spec indicates that it should be present when known (see http://stackoverflow.com/a/18925736).

**Comment by hueniverse** [comment]
Sounds like a bug then.
