### ISSUE TITLE
timezone issue

### ISSUE THREAD

**Issue by PavelPolyakov** [hapijs/hapi#2542]
Hi,

My local machine timezone is UTC+2.

When I do the next:
```javascript
                   console.log(new Date());
                   reply(new Date());
```

Which leads to:
1. in the console I see ```Wed May 20 2015 15:12:29 GMT+0200 (CEST)```
2. in the browser I see ```2015-05-20T13:12:29.104Z```

how to make them equal? haven't find any documentation reference.

**Comment by jzorn** [comment]
It appears that reply serializes a Date object using the toISOString function.

```
console.log(new Date().toISOString());
// 2015-05-20T13:45:56.463Z
```

**Comment by PavelPolyakov** [comment]
I found only one line in hapijs, which looks like the one who does that convertion:
```
hapi/node_modules/qs/lib/stringify.js:29
```

But it seems that hapi doesn't reach that point while processing the reply.

Any other thoughts?

**Comment by AdriVanHoudt** [comment]
they are the same dates.
First one is gmt +2, so distract the 2 hours and the date is the same since date 2 is gmt +0

**Comment by PavelPolyakov** [comment]
Well, they are the same.

But we do not expect that one string would be shaped to the other string, in the reply method.

Are there any ways to avoid it?

**Comment by AdriVanHoudt** [comment]
Since you pass the Date as a string to the browser I suggest to wrap incoming dates with `new Date()` so it's a date object again, same other way around, if the browser sends dates to the server, although that might be solvable with Joi

**Comment by jzorn** [comment]
I am sorry, I might have misunderstood you. What are you trying to archive? If you want to reply the Date object in the same format as console.log does, convert it to a string or call the `toString` method:

```
reply(String(new Date()));
// ... or ...
reply(new Date().toString());
```

**Comment by PavelPolyakov** [comment]
The full story is this:
0. The timezone on the server is +2
1. In the database we have the next value ```2015-04-18 00:00:00``` , TIMESTAMP.
2. When we read the value from the database, using sequelize, we receive ```Sat Apr 18 2015 00:00:00 GMT+0200 (CEST)``` . It converts it to the date object.
3. When we reply, with hapi, we receive ```2015-04-17T22:00:00.000Z```, string. Which doesn't correspond the value in the database.

What we want to get - receive the same data in the front-end as it is stored in the database.
And, if possible - avoid the duplicate conversion in the controller/model on the back-end side. E.g. - convert the Date to simple string, so hapi would not adjust it.

**Comment by AdriVanHoudt** [comment]
Isn't that sequalize adding the GMT +2 there? And then when turning that
into Zulu that's correct so if the db stores as Zulu sequalize is doing
something wrong

**Comment by PavelPolyakov** [comment]
yep,

It turned out that this is the sequelize issue. Which is nor bug nor feature.
Here is the solution:
https://github.com/sequelize/sequelize/issues/3768#issuecomment-104028310

I suppose it would help, would try tomorrow morning.

**Comment by hueniverse** [comment]
hapi just called `JSON.stringify()` on the provided object. I don't know what `console.log()` does. If you want more control over the format you need to do it yourself and pass a string to `reply()`.
