### ISSUE TITLE
no simple way to use bundled h2o2 plugin if minimal=true

### ISSUE THREAD

**Issue by hulbert** [hapijs/hapi#2543]
We're setting minimal=true in server config but want to use *one* of the disabled plugins. We can add h2o2 to our `package.json` file but it would be nice to be able to use the module that comes with the version of Hapi that we're using (instead of having to upgrade Hapi & h2o2 separately).

Some libraries will work with something like `var h2o2 = require('hapi/lib/h2o2')` but I don't see an obvious way to do something like this.

**Comment by hueniverse** [comment]
It really shouldn't be a big deal. h2o2 is a stable module and like all hapi modules uses semver. Just get the latest of the current major version and you should be just fine.

When I added the minimal flag I considered allowing you to specify what you wanted but it doesn't really add value and it does add complexity.
