### ISSUE TITLE
reply.continue() propagates errors thrown in route handlers

### ISSUE THREAD

**Issue by mgmorcos** [hapijs/hapi#2556]
So if a route handler throws an error sync'ly, and a pre-handler plugin does `reply.continue()` async'ly, then there's no live reply interface to give the error to.

e.g., https://gist.github.com/mgmorcos/5cbcd665c4380fab38fd

Tested in 8.1.0, 8.5.0 and 8.5.1. Is this a bug, or what's the Hapi way of dealing with this scenario?

**Comment by hueniverse** [comment]
What exactly is the scenario? What is the purpose of the try..catch in the ext function? What do you get if you just remove the try..catch?

**Comment by mgmorcos** [comment]
Aha, that's good to know!--replies as expected without the try..catch.
