### ISSUE TITLE
Bug handler reply

### ISSUE THREAD

**Issue by furyscript** [hapijs/hapi#2562]
Hi all,

This is a big bug in my opinion. When I create an IF Statement and I would like to reply I got error
```
Error: Uncaught error: reply interface called twice
```
But it's logical that I've another reply if the control is passed.

**Comment by arb** [comment]
That is a basic Node developer error; trying to send two responses for the same request. This error is a nicer error message that you would get otherwise. You need to do something like 
```js
if (foo) {
 return reply('error');
}
reply('ok');
```

**Comment by furyscript** [comment]
Thank's, so it would be better return anyway at the end??
```
if (foo) {
  return reply('error');
}
return reply('ok');
```

**Comment by arb** [comment]
You can do that too, in that case it's just a style preference. We try to enforce that style in the hapi organization.
