### ISSUE TITLE
Global variable

### ISSUE THREAD

**Issue by furyscript** [hapijs/hapi#2568]
Hi,

I'm start with hapi-ninja boilerplate.
I need to make accessible some variable.
For example I create a service and I start ("construct", "load") it in the server.js (main file).
I would that this variable so `var user_service = require(__dirname + '/service/user.js');` is accessible from other service.
For example:
### server.js
```javascript
var user_service = require(__dirname + '/service/user.js');
var test_service = require(__dirname + '/service/test.js');
``` 
### user.js
```javascript
module.exports.someFunction = function() {
   return 'Hello';
};
``` 
### test.js
```javascript
module.exports.useUserFunction = function() {
   return user_service.someFunction();
   // I got error because user_service is undefined
};
``` 
I solution that I'd found is load inside the test_service again user_service but it's bad because I'd load too much times `user_service`.
What is the best solution for shared variables??

**Comment by Marsup** [comment]
This is not a hapi issue, use the discuss repo for that.
