### ISSUE TITLE
Unable to validate empty text body

### ISSUE THREAD

**Issue by matthieusieben** [hapijs/hapi#2572]
I have a route that has:
```
config: {
	validate: {
		payload: Joi.string().allow(''),
	},
},
```
And when I send requests with an empty body and a content-type = 'text/plain' I get the following error:
```
{
  "statusCode": 415,
  "error": "Unsupported Media Type",
  "message": "payload must represent an object"
}
```
Why isn't plain/text supported by validation?

**Comment by hueniverse** [comment]
You can't have it both ways. If the route has validation is must have a payload type that allows parsing. You can send an empty payload without the content-type header and it should work as expected.
