### ISSUE TITLE
Parsing requests with no payload

### ISSUE THREAD

**Issue by matthieusieben** [hapijs/hapi#2576]
When an HTTP request that has "Content-type: plain/text" and no payload is received by hapi, `request.payload` is an empty object `{}`. It should be an empty string.

When an HTTP request w/o content-type an no payload is parsed by hapi, `request.payload` is an empty object `{}`. It would make more sense if it was `null`.

**Comment by devinivy** [comment]
The first case certainly makes sense to me.  The second case seems a little more open-ended, but intuitively it does seem like it should be falsey.

**Comment by matthieusieben** [comment]
```
Content-type: plain/text
Content-Length: 1

 
```
(space in body) results in `request.payload = " "`
```
Content-type: plain/text
Content-Length: 0


```
(empty body) results in `request.payload = {}`

How does this makes sence ? Detecting an empty string would require to do `if (typeof request.payload === 'object' && Object.keys(request.payload) === 0 && (request.headers['content-type'] || '').split(';')[0] === 'text/plain')`

**Comment by devinivy** [comment]
I'm sorry for the poor communication– I meant that your gripe makes sense.  I agree that a `plain/text` request without a body should yield an empty string in hapi's request payload.

In the case of an empty content-type header and an empty body, I am less sure.  Here's what the [spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec7.html#sec7.2.1) says:
>Any HTTP/1.1 message containing an entity-body SHOULD include a Content-Type header field defining the media type of that body. If and only if the media type is not given by a Content-Type field, the recipient MAY attempt to guess the media type via inspection of its content and/or the name extension(s) of the URI used to identify the resource. If the media type remains unknown, the recipient SHOULD treat it as type "application/octet-stream".

**Comment by matthieusieben** [comment]
All right. Damn those "SHOULD" in specs...

**Comment by arb** [comment]
I believe if you set the status code to 204, you'll get the desired behavior.

**Comment by matthieusieben** [comment]
@arb, I'm not sure I understand. How would you set a status code in an HTTP **request** ?

**Comment by hueniverse** [comment]
Covered by subtext 2.0.0
