### ISSUE TITLE
how to detect request timeouts? (doc example does not seem to work)

### ISSUE THREAD

**Issue by jasonswearingen** [hapijs/hapi#2577]
trying to capture client disconnects and the request events do not seem to be working.   here is my hapi-specific code:

```
public start() {
var server = new hapi.Server();
		this.server = server;
		server.connection({ port: 80 });

		server.route({
			method: "GET",
			path: "/api/v2/{userApiKey}/",
			handler: (request, reply) => this._processRequest(request, reply),

		});

		
		server.ext("onRequest", (request: hapi.Request, reply: hapi.IReply) => {

			request.once("finish", () => {
				log.info("finish", request.id);
			});

			request.once("disconnect", () => {
				log.info("disconnect", request.id);
			});

			return (<any>reply).continue();
		});

		server.start();
}
```

Please note that both the "finish" and "disconnect" events are not firing.  the routes (and request/reply roundtrip are otherwise working normally.

I am following the pattern described here: http://hapijs.com/api#request-events

**Comment by jasonswearingen** [comment]
I modified my events code a bit to test:
```
		server.ext("onRequest", (request: hapi.Request, reply: hapi.IReply) => {
			console.log("onRequest");
			request.on("peek", () => {
				console.log("peek");
			});
			request.on("finish", () => {
				console.log("finish");
			});

			request.on("disconnect", () => {
				console.log("disconnect");
			});

			return (<any>reply).continue();
		});
```

When running and triggering the route, I see "onRequest" in the console, but none of the other console.log calls.

**Comment by kanongil** [comment]
The `peek` and `finish` events require a payload to trigger, which you usually don't see in `GET` requests. They also don't timeout, since they are complete by the time the request is passed to the routing layer. Before that it's just an open socket, where timeouts needs to be handled at the socket layer.

**Comment by jasonswearingen** [comment]
ok thank you, it seems strange that this (hooking the socket layer) isn't done by hapi!
