### ISSUE TITLE
Multi-segment parameters should return array of parameter values instead of a single string

### ISSUE THREAD

**Issue by SuperAmin** [hapijs/hapi#2579]
Using the example from the "Multi-segment parameters" section in (http://hapijs.com/tutorials/routing), these two requests will return the same output:
/hello/john/doe
/hello/john%2fdoe/hahaha

Since request.params.user contained a string joined on  '/' after each path segment is decoded, requests.params.user contains the strings "john/doe" and "john/doe/hahahaha" respectively.

An easy (but breaking) fix would be to eliminate the '/' joining and just return the decoded path segments to the user as an array (e.g. ['john', 'doe'] instead of "john/doe").

**Comment by hueniverse** [comment]
Why is this an issue? Why do you need to get the raw parts?

**Comment by SuperAmin** [comment]
I need to know whether the '/' is separating the segments or the '/' is encoded within a segment (encoded as %2f). There is no way to distinguish between the two using the "/hello/{user*2}" spec and splitting request.params.user on '/'.

I realized I can just parse the raw url using request.path instead of relying on the request.params parsing logic, so I'm happy to close this issue.
