### ISSUE TITLE
preversion hook for changelog

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/hapi#2585]
Since there is now a `preversion` hook maybe plug the changelog generation into it so we always have the latest changelog? 
`"preversion": "npm run changelog"` 
and maybe some git command to auto commit or something?
see https://github.com/npm/npm/blob/master/CHANGELOG.md#featurelets

**Comment by Marsup** [comment]
IIRC Eran doesn't use it.

**Comment by hueniverse** [comment]
I want to get rid of generating the changelog here. I am only going to support automating this as part of the hapijs.com site.

**Comment by AdriVanHoudt** [comment]
so the website should do this? any implementation in mind?

**Comment by hueniverse** [comment]
I think it should be part of the existing hook when I publish a new version for the API docs

**Comment by AdriVanHoudt** [comment]
where is the hook located? would it be hard to add this?

**Comment by hueniverse** [comment]
@nlf ^^

**Comment by nlf** [comment]
no hook there, just a cached server method. i'll put details as to what we need to be done in hapijs/hapijs.com#171
