### ISSUE TITLE
Server.connection undefined in hapi

### ISSUE THREAD

**Issue by piyushvyas901** [hapijs/hapi#2592]
var server = new Hapi.Server();
server.connection({port:3000});
//version 8.6.x .connection is an undefined function can someone help me with this

**Comment by jzorn** [comment]
I cannot reproduce this error. The following code works just fine for me.

```js
var Hapi = require('hapi');

var server = new Hapi.Server();
server.connection({port: 3000});

server.start(function () {
      console.log('Server running at:', server.info.uri);
});
```

**Comment by hueniverse** [comment]
This is not enough information.
