### ISSUE TITLE
Memory increasing on every request

### ISSUE THREAD

**Issue by funerr** [hapijs/hapi#2594]
So every request is adding about ~ 0.1 m"b

Here is the code I'm testing: 
``` 
var Hapi = require('hapi');
var server = new Hapi.Server();
server.connection({ port: 5001 });

server.route({
	method: '*',
	path: '/hello',
	handler: function(request, reply) { 
		reply('world');
	}
});


server.start(function () {
    console.log('API instance running at:', server.info.uri);
});
```

The test: Holding the f5 key and looking at `pm2 monit test.js`

Testing on:
* Windows 10
* Node: v0.12.3
* npm: 2.9.1
* hapi: 8.6.1

**Comment by Marsup** [comment]
Known issue with node 0.12, go back to 0.10.

**Comment by hueniverse** [comment]
@funerr let me know if you can reproduce this on node 0.10

**Comment by funerr** [comment]
Well, I'm sure I am doing something wrong, but this also happened to me on v0.10.38 :/

**Comment by Marsup** [comment]
Maybe that's specific to the windows platform. For how long did you test ? Can you get a graph of that increase ?

**Comment by funerr** [comment]
How should I setup the testing enviorment (package? app?) @Marsup ?

**Comment by Marsup** [comment]
Since you're using PM2 maybe you can try their monitoring solution (keymetrics).

**Comment by funerr** [comment]
![mem](https://cloud.githubusercontent.com/assets/1269911/8126185/daf20528-10f4-11e5-953a-7dd156497126.png)
Well it started at about 20mb and doubled it's memory usage to 40mb where is was kept stable. This still looks quite bad, although it doesn't increase to be >100mb which is nice.

**Comment by Marsup** [comment]
It doesn't look like a leak though.

**Comment by funerr** [comment]
Well, I didn't write leak specifically, but this increase looks bad, but I don't know what will happen on a larger scale. To sum up, what are the best versions to put in production?

**Comment by Marsup** [comment]
I don't know anything about the Windows platform, for Linux 0.10 is still best.

**Comment by funerr** [comment]
Ok, thanks. I think we can close it now, If I find more abnormalities I'll post them here.

**Comment by Marsup** [comment]
BTW, don't expect V8 to free your memory as soon as you release it, or ever, this is not C++. The VM doesn't need to waste time micro managing memory, it will eventually be re-used anyway.

**Comment by mooncakelmn** [comment]
>Known issue with node 0.12, go back to 0.10.

@Marsup Is this a node issue or hapijs?

**Comment by Marsup** [comment]
I didn't investigate but I'd say it's node.

**Comment by hueniverse** [comment]
0.12 is not supported (and will never be).

**Comment by cjihrig** [comment]
Just out of curiosity, what is the next version of Node to be officially supported after 0.10? Or is that still TBD?

**Comment by hueniverse** [comment]
v4.0 if that proves not to be shit.

**Comment by OpakAlex** [comment]
v6.2.1 still same shit. +30MB each request. What i need to do? Upgrade to 0.10.0 node?

**Comment by OpakAlex** [comment]
@hueniverse what you think? 0.10.0 really good? without leaks?

**Comment by Marsup** [comment]
Really unmaintained. Better find the source of the leak than work around it.

**Comment by OpakAlex** [comment]
Better never use nodejs man :)
