### ISSUE TITLE
Timeout values not working?

### ISSUE THREAD

**Issue by vkumara** [hapijs/hapi#2595]
Hi there,

I just need to know how the socket timeout works with hapi.js here. Apparently server level timeout are not taken in server.connection(options). Or does it work? 

Seems it takes 1-2 minutes (default) to timeout an external service call made by hapi.js (wreck). This gets accumulated and seems affecting the server TPS. Is there a way set the socket and client timeout to smaller values so that they will be closed quickly?

Regards,
VK.

**Comment by hueniverse** [comment]
You need to be more specific about which timeout value you are trying to set and what you expect to happen.

**Comment by vkumara** [comment]
Hi,

Usually when we call a REST API via wreck (hapi.js) GET/POST etc... the connection is kept around 1 minute (in latest hapi.js 8.6.1) in TIME_WAIT state. Setting is similar to below...

server.connection(...,{timeout:{server:true}},{payload:{timeout:4000}},{socket:{timeout:5000}})

As seen above socket timeout is set to 5 seconds but the connections stay there around 1 minute. Is this the correct way to set this. Or is there any other option for this?

Thanks
VK.

**Comment by hueniverse** [comment]
Server timeouts has nothing to do with wreck request timeouts. You need to provide a full example of what you are doing.

**Comment by kanongil** [comment]
Concerns about sockets in `TIME_WAIT` state are usually an OS level issue. Whenever a socket is closed, the OS needs some time before the port used can be safely recycled.

**Comment by vkumara** [comment]
@kanongil Yes. But my concern is whether there's any option to made the closing of socket faster via hapi.js OR wreck.

For example when you make a call in wreck after the response is received the connection should be closed. I don't think a specific method exists for this? 

What role this socket timeout (mentioned above) plays here in hapi.js?
