### ISSUE TITLE
Set header

### ISSUE THREAD

**Issue by furyscript** [hapijs/hapi#2596]
I need to set my personal header from frontend to pass auth-token.
But in backend (Hapi) there isn't option..
The default allow header is : `access-control-allow-headers:Authorization, Content-Type, If-None-Match`

How can I set it?

**Comment by edimoldovan** [comment]
You should have a look here for a plugin that does server side auth for you: http://hapijs.com/plugins#Authentication

**Comment by furyscript** [comment]
Uhm, I need to write my auth plugin so I need my personal header..

**Comment by gergoerdosi** [comment]
You can override that list in `routes` configuration:

```js
routes: {
    cors: {
        headers: ['Authorization', 'Content-Type', 'If-None-Match', 'Your-Custom-Header']
    }
}
```

**Comment by furyscript** [comment]
Ok it work! @gergoerdosi

**Comment by dariospadoni** [comment]
Uhm
I'm trying to pass extra params to cors section of my configuration, but it breaks: "invalid connection options". 


Here's my config:
```
serverConfig = {
  port: 3000
  router: {
       stripTrailingSlash: true
  }
  routes: {
     cors: {
          additionalHeaders: ['language','Language']
     }
  }
}

server = new Hapi.Server()
server.connection(serverConfig)

```

I'm using Hapijs (8.8.0)

**Comment by Marsup** [comment]
Works for me.
