### ISSUE TITLE
errors not being thrown and app just stalling

### ISSUE THREAD

**Issue by aschmid** [hapijs/hapi#2597]
hi guys,

i have a weird situation i would like to know how to solve.
in my app errors that happen after functions with promises do net get thrown and the app just stalls.

here an example:

```
getTenant = (req) ->
  deferred = Q.defer()

  deferred.resolve('foo') if req.info.referrer
  deferred.resolve('bar') if !req.info.referrer

  deferred.promise

Routes =[
  {
    method: 'GET'
    path:   '/'
    handler: (request, reply) ->
      getTenant(request).then (tenant) ->
        console.log 'tenant', tenant

        # here `User` is not defined and doesn't even exist
        # why is there no error here?

        if !User.isAuthorized(request, tenant)
          reply 'not authorized'
        else
          reply 'authorized' 
    
  }
]
``` 

after ```getTenant``` i call a function on ```User```. User doesnt exist or is imported but the app gives me no error. 
why is that? 

here the full sample app: https://github.com/aschmid/hapierrortest

thank you,
andreas

**Comment by Marsup** [comment]
A js error is thrown, caught by the promise, but you're not listening to it. You're missing the catch, see promise api.

**Comment by aschmid** [comment]
but the error should be thrown after the promise got resolved. how is this still an issue with the promise?

**Comment by Marsup** [comment]
> but the error should be thrown

Why ? No it won't. It's in the spec.

**Comment by aschmid** [comment]
could you please point me to the correct docs/specs? i cant find anything regarding listening to promise errors rather than the 'reject' event

**Comment by Marsup** [comment]
https://promisesaplus.com/ <- everywhere the word exception appears.

**Comment by aschmid** [comment]
ill check it out. thx
