### ISSUE TITLE
Helpers not loading/being registered

### ISSUE THREAD

**Issue by geuis** [hapijs/hapi#2600]
Having some trouble getting helpers setup.

Here's the server config:

    web.views({
      engines: {
        html: Swig
      },
      path: 'views',
      helpersPath: 'views/helpers',
      isCached: false,
    });

Here's my sample helper under /views/helpers/sample.js

    module.exports = function (context) {
      console.log(context);
      return '###';
    };

Sample.js isn't being loaded at all (tried with a console.log in outside of module.exports). I know that Jade doesn't support Hapi helpers natively. Is this the same case for Swig?

**Comment by hueniverse** [comment]
From a quick glance it doesn't look like swig supports the `registerHelper()` API.

**Comment by geuis** [comment]
Thanks @hueniverse.
