### ISSUE TITLE
Reply interface called twice is not caught by 'request-error' event

### ISSUE THREAD

**Issue by guptakvgaurav** [hapijs/hapi#2604]
Hi 

In one of my api i am calling reply() twice which leads to following exception (as excepted), but this exception should have been surfaced to 'request-error' but it didn't.
```
Debug: internal, implementation, error 
    Error: reply interface called twice
    at Object.exports.assert
(/home/gaurav/Gaurav-Drive/Devlopment/node-dev-space/ragchews/node_modules/hapi/node_modules/hoek/lib/index.js:678:11)
    at Function.internals.response
(/home/gaurav/Gaurav-Drive/Devlopment/node-dev-space/ragchews/node_modules/hapi/lib/reply.js:129:10)
    at reply
(/home/gaurav/Gaurav-Drive/Devlopment/node-dev-space/ragchews/node_modules/hapi/lib/reply.js:67:22)
    at
/home/gaurav/Gaurav-Drive/Devlopment/node-dev-space/ragchews/src/controllers/userController.js:178:5
    at
/home/gaurav/Gaurav-Drive/Devlopment/node-dev-space/ragchews/src/libs/user/main.js:749:9
    at
/home/gaurav/Gaurav-Drive/Devlopment/node-dev-space/ragchews/src/libs/user/profile.js:830:17
    at
/home/gaurav/Gaurav-Drive/Devlopment/node-dev-space/ragchews/src/dao/cs_discoverydao.js:416:3
    at b (domain.js:183:18)
    at
/home/gaurav/Gaurav-Drive/Devlopment/node-dev-space/ragchews/node_modules/cassandra-driver/lib/request-handler.js:173:5
    at Connection.handleResult
(/home/gaurav/Gaurav-Drive/Devlopment/node-dev-space/ragchews/node_modules/cassandra-driver/lib/connection.js:489:3)
```

``` javascript
server.on('request-error', onInternalError); // captured event.
```

Hapi version: 8.4.0

**Comment by Marsup** [comment]
I don't see why.
`'request-error' - emitted whenever an Internal Server Error (500) error response is sent. Single event per request.`
Calling reply twice doesn't necessarily cause a 500.

**Comment by guptakvgaurav** [comment]
`Calling reply twice doesn't necessarily cause a 500.`
Yes, calling reply() twice doesn't cause Internal Server Error(500) to be sent, this is probably because the first call to reply() completes the request lifecycle.
But, still second call to reply() generates an exception which can be seen on console with the stack-trace, So since it's a valid exception in system, shouldn't it be captured by event handler.

**Comment by Marsup** [comment]
As mentioned in the tags `internal, implementation, error`, it's not a request error, it didn't generate any error for the requester, I tend to agree with the current implementation.

**Comment by AdriVanHoudt** [comment]
Keeping the server running after that is dangerous since then your server is probably in a bad state. On production you would have it logged and then reboot the server with forever or npm2 or something, on dev you'd want to crash because errors like that should not go unnoticed

**Comment by Marsup** [comment]
This should be spotted at test time anyway, but it's not necessarily dangerous.

**Comment by guptakvgaurav** [comment]
Thanks for suggestion @AdriVanHoudt  . Can i have any link to article where i can read more about "What happens to the server when crash occurs"? What bad state you are actually reffering to.

**Comment by AdriVanHoudt** [comment]
http://www.nearform.com/nodecrunch/10-tips-coding-node-js-3-know-throw-2/
