### ISSUE TITLE
stripTrailingSlash allows both slash and non-slash endings to resolve but not redirect

### ISSUE THREAD

**Issue by geuis** [hapijs/hapi#2605]
I enabled stripTrailingSlash on paths to allow /an/example/path and /an/example/path/ to both resolve. I was initially expecting that /an/example/path/ would redirect to not having the trailing slash, but it doesn't.

I understand that from prior similar issues filed over the last few years there might be some issues with the router that have prevented this from being a default behavior. Is there a particular way to get the behavior I'm describing to work?

**Comment by hueniverse** [comment]
You can't have both. You need to pick one (redirect or ignore).

**Comment by geuis** [comment]
What are the specific reasons we can't have both? It seems technically feasible at least.

**Comment by hueniverse** [comment]
How can you both ignore it and redirect at the same time?

**Comment by geuis** [comment]
I think I see why what I'm asking is confusing. "Ignore" isn't quite the right word. Let me try an example of what I think the desired behavior is.

We want this:
 
    http://example.com/prefer/no/slashes

We get this from the browser:

    http://example.com/prefer/no/slashes/

We've configured our routes to redirect trailing slashes, so:

    302: http://example.com/prefer/no/slashes

I also looked at a few other sites to see how they handle it.
* Google does the reverse, i.e. no trailing slash redirects to /: https://www.google.com/intl/en/about
* Google also doesn't do it for some paths like https://www.google.com/webhp, so adding a / returns a 404.
* Stackoverflow does it like stripTrailingSlash. It doesn't redirect, but treats trailing slashes and none as the same, http://stackoverflow.com/questions and http://stackoverflow.com/questions/
* Reddit does it like stripTrailingSlash, http://www.reddit.com/new and http://www.reddit.com/new/
* Snapguide does it like the first Google example, https://snapguide.com/guides redirects to https://snapguide.com/guides/

So I don't see a definitive right/wrong way to handle it. The behavior seems to just be the preference of the dev team.

Also, there is already "redirectToSlash" on the directory handler.

    "optional boolean, determines if requests for a directory without a trailing slash are redirected to the same path with the missing slash"

What I'm proposing is a feature that is similar to redirectToSlash that works on all routes. It will allow redirects both ways. 

    http://example.com/prefer/slashes -> http://example.com/prefer/slashes/
    http://example.com/prefer/no/slashes/ -> http://example.com/prefer/no/slashes

The syntax might look like:

    var server = new Hapi.Server({
      connections: {
        router: {
          redirectTrailingSlash: ('none', 'slash', false)
        }
      }
    });

* 'none': Redirect trailing slash to no slash
* 'slash': Redirect no slash to slash
* false: Default state. Feature is disabled. Current functionality would exist. 

redirectTrailingSlash would supersede stripTrailingSlash if both are defined.

Also as an extra note, I've thought about this a bit and I believe the description for stripTrailingSlash isn't as full as it should be. 

    "stripTrailingSlash - removes trailing slashes on incoming paths. Defaults to false."

This indicates that a trailing slash will be removed on the path. This only happens internally in the router and isn't reflected in the browser. 

An alternate proposal to 'redirectTrailingSlash' might be to update stripTrailingSlash to send a redirect header in response to the request.

**Comment by gergoerdosi** [comment]
We could also solve this issue with just one parameter `trailingSlash` with the values:

- `ignore`: It would ignore the trailing slash. It would either strip the trailing slash internally, or it would check for both `/foo` and `/foo/` in routes.
- `append`: It would make a redirect to `/foo/` if URL is `/foo`.
- `remove`: It would make a redirect to `/foo` if URL is `/foo/`.
- Falsy value would not do anything.

**Comment by hueniverse** [comment]
What you are asking makes sense but could be easily implemented in a plugin using an `onRequest` extension. I would suggest you start with something like that and see if people are using it and interested in this. I think most people just don't really care and go with the options already available. If there is much interest, I'll reconsider moving it into core.
