### ISSUE TITLE
Handlebars Helper problem

### ISSUE THREAD

**Issue by dhershman1** [hapijs/hapi#2606]
I built a small helper to setup some data for my main index slider html.

The helper is functioning perfectly and returning exactly what was needed. However, the html is not being added to the page? Maybe I am missing something but here's my setup:

#### Helper "slider.js"
```javascript
var slider = function(options) {
    var filesystem = require("fs");
    var tmpObj = {
        title: {
            "slide1": "Welcome to NoradGaming!",
            "slide2": "A New Start",
            "slide3": "Want to help out?",
            "slide4": "PlaceHolder"
        },
        subtitle: {
            "slide1": "A Rust PvP, and build server",
            "slide2": "Welcome to the new website!",
            "slide3": "Check below and vote for the server!",
            "slide4": "SubPlaceHolder"
        }
    };
    filesystem.readdirSync('./public/images/homepage-slider/').forEach(function(file) {

        var ext = file.substr(file.lastIndexOf('.'));
        var tmp = file.replace(ext, "");

        if (tmp !== "background") {
            var context = {
                bg: "bg" + Math.floor(Math.random() * 14 + 1),
                title: tmpObj.title[tmp],
                subtitle: tmpObj.subtitle[tmp],
                slide: file,
                slidenum: tmp,
            }
            var html = options.fn(context);
            return html;
        }

    });
}

module.exports = slider;
```
after this helper runs it returns a proper html block with all the proper variables filled in. The html block looks like so: 
#### Html Block
```handlebars
{{#slider}}
                <li class="{{bg}}">
                    <!-- 1-14 BGs -->
                    <!-- Slide Title-->
                    <h2 class="title">{{title}}</h2>
                    <!-- Slide Text-->
                    <h3 class="subtitle">{{subtitle}}</h3>
                    <!-- Slide Image--><img src="./images/homepage-slider/{{slide}}" alt="{{slidenum}}" class="slide-img">
                </li>
                {{/slider}}
```
when I log the return inside the helper it returns this block filled out properly. when I use `{{debug}}` in my handlebars html I get the object back but if I debug the variables they return properly. 

#### Edit:
This is what the helper `html` variable returns: 
```html
<li class="bg9">
                    <!-- 1-14 BGs -->
                    <!-- Slide Title-->
                    <h2 class="title">Want to help out?</h2>
                    <!-- Slide Text-->
                    <h3 class="subtitle">Check below and vote for the server!</h3>
                    <!-- Slide Image--><img src="./images/homepage-slider/slide3.png" alt="slide3" class="slide-img">
                </li>
```

And this is what `{{debug}}` returns inside the block:
```
Current Context
====================
{ bg: 'bg1',
  title: 'PlaceHolder',
  subtitle: 'SubPlaceHolder',
  slide: 'slide4.jpg',
  slidenum: 'slide4' }
```

The issue now is the slider html list items are not returning on the page itself, it's blank like it never happened but I know the helper is running thanks to `debug`, am I going about this incorrectly?

**Comment by Marsup** [comment]
I'll point out the obvious but you're not returning anything.

**Comment by hueniverse** [comment]
To be more specific, your helper function does not return any value. Your return statement is inside a child function.

**Comment by dhershman1** [comment]
Thank you so much @Marsup I think I was just looking at it so line the level of my scope just merged together and I missed the fact it was indeed the child.  I feel dumb, but I am oh so relieved to have the answer
