### ISSUE TITLE
Is there a way to modify request payload before next handler is triggered ?

### ISSUE THREAD

**Issue by szydan** [hapijs/hapi#2608]
Let say I have a proxy, but before proxying to another server I would like to modify the request payload
Is this possible ? 
I've cloned the proxy handler module and tried to modify the 
```
   payload._readableState.buffer = new Buffer(MY MODIFIED BODY STRING)
```
before the requests is proxied but once I touch the buffer 
the request gets stuck.
Any hint appreciated.

**Comment by hueniverse** [comment]
Write your own handler using wreck. Read the payload, process it, and then make a new upstream request and pipe the response back.

**Comment by tamilsweet** [comment]
@szydan Were you able to figure out way to modify request payload before proxying? I'm facing the same issue.

**Comment by szydan** [comment]
Hi @tamilsweet i took the advice from @hueniverse and implemented my own handler.
Which is basically a fork of h2o2 proxy handler.
In my fork I've introduced 2 new handlerConfiguration options:
**modifyPayload** and **modifyResponse**

The code of modified proxy now called "kibi_proxy" is available [here](https://github.com/sirensolutions/h2o2), it requires the node 4.x to work properly

To use it in your project declare it as dependency in your package.json

```
"kibi_proxy": "sirensolutions/h2o2#645c6795eb29b79b6c65543a17ea338e1c7cdbfb"
```

and then something like this 

```
var kibi_proxy = require('kibi_proxy');
...

server.register(kibi_proxy);
...

var options = {
  method: method,
  path: route,
  handler: {
    kibi_proxy: {
    mapUri: uri,
    passThrough: true,
    agent: agent,

    modifyPayload: function (request) {

      var req = request.raw.req;
      return new Promise(function (fulfill, reject) {
        var chunks = [];
        req.on('data', function (chunk) {
          chunks.push(chunk);
        });
        req.on('end', function () {
            
            // do something with chunks 
            // and create your new modified payload

            //fulfill({
            //  payload: YOUR_NEW_PAYLOAD_AS_BUFFER,
            //  data: dataToPass
            //})
            //OR
            //reject(err);
        });
      });

    },
    modifyResponse: function (response, dataPassed) {

      return new Promise(function (fulfill, reject) {
        var chunks = [];

        response.on('data', function (data) {
          chunks.push(data);
        });

        response.on('end', function () {
            
            // do something with chunks 
            // create your new responce body as Buffer

            // fulfill({
            //  response:response,
            //  data: dataPassed
            // });
            // OR
            // reject(err)
        });
      });

    }
    
  }
}

server.route(options);    
``` 

There are currently no test for the **modifyPayload**,  **modifyResponse** options I'm planning to add them in the coming days. Hope this will help you 
Cheers
