### ISSUE TITLE
reply.file() with a 1GB file

### ISSUE THREAD

**Issue by msurdi** [hapijs/hapi#2611]
I'm trying to stream a file from a hapi (8.6.1) handler with: 

curl http://localhost/file -o file

And I get the following error:

curl: (18) transfer closed with 517803168 bytes remaining to read

In the handler, I simply do:

reply.file('/path/to/file');

Am I doing something wrong?

**Comment by doron2402** [comment]
@msurdi you might want to try do it from the client side and store the file on an s3 bucket or some other similar service let the browser handle that

**Comment by kanongil** [comment]
Just tested `reply.file()` with a 10GB file & curl without issue. I suspect you are encountering some file-level issue unrelated to hapi itself.

**Comment by msurdi** [comment]
Seems like the problem is that I'm hitting the default node socket timeout as the connection always breaks at about 1:58m. The route configuration seems to be right:

     {
            method: 'GET',
            path: '/{hash}',
            handler: uploadHandler.download,
            config: {
                bind: uploadHandler,
                timeout: {
                    socket: 3600001,
                    server: 3600000
                },
            }
        }


@kanongil did your test take more than 2 minutes to download?

@doron2402 I'm not using nor want to use S3 and there is no browser involved here.

**Comment by msurdi** [comment]
Ok, forget about it, this seems to be a problem in a load balancer we use in from of our servers (hipache) which I didn't know was also built in node and thus had this default timeout which I assumed was mine. Sorry for wasting your time and thanks a lot for your help.
