### ISSUE TITLE
working with the nodejs Benchmarking WG

### ISSUE THREAD

**Issue by trevnorris** [hapijs/hapi#2614]
An official Benchmarking WG has been created for the nodejs foundation (information on https://github.com/nodejs/benchmarking). We are investigating ways to more thoroughly detect performance regression over different versions. Part of this has been discussion around using larger scale benchmarks, instead of relying so heavily on the micro benchmarks commonly used.

I'm reaching out to larger and heavily used projects to hopefully get participation in creating mock realistic use cases that can be used to test node throughout the development process. Would anyone like to participate by either helping us write the benchmarks or pointing to existing suitable cases?

**Comment by corbinu** [comment]
@trevnorris What is the best place to respond? Here there or is there a gitter for this WG?

Anyway I have something that might be of interest. I am currently building set of examples for running a set of Docker containers glued together with Consul. The first one is an adaptation of a Node.js Demo Couchbase developed. It's main goal is to demonstrate containerizing a Node application for development on local machines. Then deploying to various infrastructures including Triton. 

I was thinking a next good goal would be to also adapt the  https://github.com/acmeair/acmeair-nodejs and possibly merge both demos to run on hapi.js as it is the framework my company uses. I was thinking this would allow me and others to benchmark various container platforms and databases easily. 

If your interested I think either just the demo project or the entire cluster example could be used in your benchmarks.

**Comment by trevnorris** [comment]
@corbinu Here is fine. I'm tracking all these issues.

Both of your examples sound excellent. Getting acmeair running on hapi would be an excellent cross comparison example, but the stand alone running in a docker container would be much easier to scale out.

**Comment by corbinu** [comment]
The primary objective of what I am doing is to develop an example that scales out. The idea would be acme running on it and write a new demo app on api based on both acme and the Couchbase demo.

It could definitely be written in multiple node frameworks to do the same task and so each could be benchmarked simply by changing the application docker container. I am documenting the first simple version today and writing out a roadmap so will post here when is done so you can comment on ideas what would make it fit the working groups needs also.

**Comment by corbinu** [comment]
@trevnorris The current version is here: https://github.com/corbinu/docker-demos I will be trying to add more to the documentation, examples and roadmap over the next few days.

**Comment by trevnorris** [comment]
@corbinu Looks great. Thanks for sharing.

**Comment by hueniverse** [comment]
This would be better posted in hapijs/discuss.
