### ISSUE TITLE
Returning Boom 504 error as 500

### ISSUE THREAD

**Issue by tanepiper** [hapijs/hapi#2615]
In our app we have a error handler to help us pass out errors easier: https://gist.github.com/tanepiper/d00f2039160a31ada5d4

In this example, we check to see if the `statusCode` returned from a [Request](https://github.com/request/request) query is an error.  In the specific case I saw this, we got a 504 error back indicating a gateway timeout from the service we're querying.

As you can see from the file https://gist.github.com/tanepiper/d00f2039160a31ada5d4#file-should-be-js the Boom error generated has a 504 payload as seen in the `console.log`.  However when returning via the Hapi reply method, we get a 500 error returned to the client.

**Comment by hueniverse** [comment]
I'm missing the complete flow to figure out where the error response is changed. Can you add an `onPreResponse` extension and log the `request.response` object you see there?

**Comment by tanepiper** [comment]
@hueniverse Right, thanks for the tip! Turns out a further method call that is made was failing, but wasn't being reported in the stack for some reason.  `onPreResponse` has helped track that down.
