### ISSUE TITLE
registering plugins can throw; API suggests callback(error) will be triggered instead

### ISSUE THREAD

**Issue by jmonster** [hapijs/hapi#2620]
## sample code
```js
var Hapi = require('hapi');

var server = new Hapi.Server();
server.connection({ port: 3000 });

const Foo = {
  register: function (server, options, next) {

    next();
  }
};

Foo.register.attributes = {
  name: 'foo',
  version: '1.0.0'
}

server.register([Foo, Foo], function(error) {

  console.log('register callback: ', error);
});
```

## Expectation:
Console will log:
```
register callback: Error: Plugin foo already registered ...
```

## Actuality:
```
........./node_modules/hapi/node_modules/hoek/lib/index.js:723
    throw new Error(msgs.join(' ') || 'Unknown error');
          ^
Error: Plugin foo already registered...
```

## Use case:
I'm building apps composed of plugins via Glue. Those plugins may (do) aregister other plugins. If/when the nested registration fails, for example due to already being registered [or any other error], an Error is thrown -- but it is not propagated back to my root Hapi application. The process dies without any output whatsoever and is quite difficult to debug. I confirmed the root cause of this by drilling down into the Hapi codebase and wrapping the registration code in the `plugins` file with a try/catch and confirming the error stems from there (again, specifically because a plugin has already been registered).

## Sugested solution:
Wrap the registration code in a `try/catch`, call `next(error)` rather than simply throwing the exception. This would enable me to 1) more easily debug my app by actually seeing the error, 2) potentially ignore some errors that aren't deemed dangerous -- for example, I may be ok with a second attempt to register a plugin failing as I only require that it was registered at least once.

## What on earth am I trying to do?
I'm attempting to combine what could be multiple isolated Hapi applications into one server that needs to be deployed/maintained. I could write a single Hapi server, require/register my one key plugin, and start the server. Repeat for each plugin/component. Instead, I'm attempting to load multiple such plugins and serve them all from one place. As mentioned, this can hurt at the point where each of your primary plugins may depend on another plugin -- for example, something that is parsing out the Authorization header and setting it to `request.app.foo`. And that is what led me to to create this issue :+1:

**Comment by hueniverse** [comment]
So... no.

Wrapping stuff in try..catch when you cannot know for sure you are calling a purely synchronous code is code theater. If you want to solve it, you will need to do it within glue or something like glue that provides such higher level contract.

If you think the docs should be updated, I'll take a PR.
