### ISSUE TITLE
Update hapijs/qs to 4.0.0 from 2.4.2

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#2623]
Planning on including this in 8.8.0 and not in a major version as the changes in qs while breaking for some qs use cases, should not be breaking here. I will tag the issue as breaking changes just in case someone does have an issue with this to make finding the cause easier.

**Comment by hueniverse** [comment]
@nlf so this breaks some of the tests because the deep comparison fails. I am not sure what's the right way to fix this. I can force the object back into prototype but that means basically overriding members (same bug 3.x was trying to fix) or I we need to change the tests or assertion module to ignore prototype somehow.

Thoughts?

**Comment by nlf** [comment]
Code.expect has the ability to pass options to Hoek.deepEqual, which allows you to pass `{ prototype: false }` and not compare prototypes, but this still feels hackish. I'm trying to think of a better solution to the overall problem in qs.

**Comment by arb** [comment]
I added that feature to address this very problem.

**Comment by nlf** [comment]
should update to 4.0.0 instead of 3.1.0 now, should resolve any issues you had.
