### ISSUE TITLE
Question: Custom validation function, how to exit nicely with correct error message?

### ISSUE THREAD

**Issue by jvduf** [hapijs/hapi#2630]
I want to use validation which is build into my data models so I do not want to use Joi for validation of requests. Instead I opted for a custom validation function as provided below.

``` javascript
server.route({
  'method': 'POST',
  'path': '/foo',
  'config': {
    'validate': {
      'payload': function validation(payload, context, exit) {
        if ('valid' === true) {
          exit();
        } else {
          exit(Boom.badData('error message...'));
        }
      }
    }
  },
  'handler': function handler(request, reply) {
    reply('{"foo":"ready"}');
});
```
The following error message get's returned by Hapi. However it doesn't seem to return the correct `statusCode` and `keys` is empty. I have no idea where or how to provide the `keys` data. I checked the documentation and explored the code base. But no luck so far. Anybody here who can point me into the right direction?
``` json
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "error message...",
    "validation": {
        "source": "payload",
        "keys": []
    }
}
```

**Comment by hueniverse** [comment]
It's not documented because it's more of an integration point with joi than a fully baked interface. The code is here: https://github.com/hapijs/hapi/blob/master/lib/validation.js#L74-L78 and you should be able to figure out the full format between the hapi and joi code.

**Comment by jvduf** [comment]
Awesome! Thanks, I didn't see that one before!


*Jeroen van Duffelen*
+31 6 2854 1275
@jvduf
