### ISSUE TITLE
Wazzup with the Hapi docs?

### ISSUE THREAD

**Issue by williamle8300** [hapijs/hapi#2632]
I mean wazzup? Why is it a long-running document. CAMON!

It'd be nice if it were collapsible, and fancy-like.

**Comment by arb** [comment]
If you feel that you need a fancy view of an API document, please check out http://hapijs.com/api

**Comment by williamle8300** [comment]
What. No man! That's what I'm talking about!

Accordion everything! Most especially the body content.

I dunno. It's A little crazy scrolling an semi-infinite page like that.

**Comment by martineboh** [comment]
Tired of scrolling. Make it collapsible and reader friendly.

**Comment by AdriVanHoudt** [comment]
Feel free to do a PR on https://github.com/hapijs/hapijs.com
