### ISSUE TITLE
Relative redirect

### ISSUE THREAD

**Issue by matthieusieben** [hapijs/hapi#2633]
Is it possible to perform a ```reply.redirect()``` that is relative to the entire prefix currently applied to the route (including module prefixes)?

Currently, i'm performing:
```js
// -1 because the current route is only one level (e.g. "/test" )
var prefix = request.path.split('/').slice(0, -1).join('/');
return reply.redirect(prefix+'/some/other/route');
```

**Comment by hueniverse** [comment]
There is no shortcut to do this. You can however use the `server.decorate('reply', ...)` to add this functionality.

**Comment by matthieusieben** [comment]
I ended up doing:
```js
var prefix = request.route.realm.modifiers.route.prefix;
```
