### ISSUE TITLE
Best method for session checks

### ISSUE THREAD

**Issue by geuis** [hapijs/hapi#2634]
This is more of a "which way is best" question than a specific issue.

We have Hapi and an old php site both pulling their session data from an api. Login is being handled by Hapi and updates the state via the api.

Hapi has routes that it handles, then proxies other routes to the existing php app. On each request, regardless of where the request routes to, the session needs to be checked from the api. 

My initial implementation sets up an auth strategy that does the check, but requires all routes to add it in config.auth in the route. It works, but doesn't support the idea of generic sessions regardless of authentication.

What would be the best way to check for session state via the api endpoint in Hapi?

**Comment by kanongil** [comment]
Such questions are better suited for the [hapijs/discuss](https://github.com/hapijs/discuss) repo. I suggest you post it there.

**Comment by geuis** [comment]
Thanks, wasn't aware of /discuss.
