### ISSUE TITLE
Global parameter in route

### ISSUE THREAD

**Issue by furyscript** [hapijs/hapi#2635]
Hi, 

I need to set "global" parameter in my route because I want to write a strategy that based on auth-token received it check if auth-token is compatible with "global" parameter

For example
```javascript
server.route({
    method: 'GET',
    path: '/example',
    config: {
        auth: {
            strategy: 'check-if-token-is-allowed',
            global_parameter: 'view_dashboard'
        },
        handler: function(request, reply) {

            return reply('Success, you can access a route!');

        }
    }
});
```
So it is a basically filter to user's permission. But I want to make a strategy that check if "view_dashboard" exist on user token table! In this way I can set what permission is allowed to access on the route... Alternative I can check on each route handler, but moreover it is boring work with callbacks...

If you have suggestion tell me everything!!!

**Comment by hueniverse** [comment]
I assume your problem is that the key is not allowed in `auth`. This is what the route `config.app` is for.

**Comment by furyscript** [comment]
Can you explain more clearly?? Or with example? @hueniverse

**Comment by furyscript** [comment]
I can access it in strategy with `request.route.settings.app.my_key`

**Comment by hueniverse** [comment]
You can't do this. Only one strategy will execute per request. The second will be executed only if the first one returns an error with `isMissing` set to true. You need to either create a meta strategy that does both things or move one of them to `onPostAuth`
