### ISSUE TITLE
Cookies tutorial needs more information

### ISSUE THREAD

**Issue by Downchuck** [hapijs/hapi#2638]
The documentation for cookies is incomplete:
http://hapijs.com/tutorials/cookies

It should recommend how to delete a cookie (is it  reply.state('cookiename', null) ? ), and it should recommend how to read cookies (request.state['cookiename']).

**Comment by hueniverse** [comment]
First, this issue belongs under hapijs/hapijs.com. Second, why not just go and submit a PR fixing it instead.
