### ISSUE TITLE
Events (e.g. received, request) don't work as documented.

### ISSUE THREAD

**Issue by mik01aj** [hapijs/hapi#2639]
I tried to listen to the `received` and `request` events, according to what's [in the docs](http://hapijs.com/api#server-events), but it seems that these events aren't triggered at all. Some of the other events, like `response` and `request-internal` work. I have no idea what it all means.

I also find the documentation about logging very, very unclear. I had to write [my own logging function](http://stackoverflow.com/a/29819184/115493), because I lost several hours trying to hake HAPI builtin logging work.

Possibly it's related to https://github.com/hapijs/hapi/issues/2578 (?)

**Comment by AdriVanHoudt** [comment]
look at https://github.com/hapijs/good for logging ;)

Also if the docs are not clear feel free to do a PR on them! Always welcome!

**Comment by mik01aj** [comment]
I don't understand this behaviour well enough to do a PR. For me these events seem pretty unpredictable and somehow entangled with the logging logic. There is some connection between `debug` object passed on server init and the events, but I never figured out which options are available and which events do they trigger.

**Comment by hueniverse** [comment]
If something is not working as expected, an example would be useful. If you need help using the APIs, you are better off asking it on hapijs/discuss.

**Comment by mik01aj** [comment]
So here's an example:

```
var Hapi = require('hapi');
var hapiServer = new Hapi.Server();
hapiServer.connection({port: 8888});
hapiServer.on('received', function () { console.log('received'); });
hapiServer.on('request', function () { console.log('request'); });
hapiServer.on('request-internal', function () { console.log('request-internal', arguments[2]); });
hapiServer.on('response', function () { console.log('response'); });
hapiServer.on('log', function () { console.log('log'); });
hapiServer.on('tail', function () { console.log('tail'); });
hapiServer.route({method: 'GET', path: '/', handler: function(req, reply) { reply('Hello!'); }});
hapiServer.start(function() { console.log('started!'); });
```

When I send a request, it produces:

```
started!
request-internal { received: true }
request-internal { handler: true }
request-internal { response: true }
response
tail
```

There is no `request` event. There are no `log` events.

I'm using Hapi 8.8.0, and the [documentation for events in Hapi 8.8.0](http://hapijs.com/api/8.8.0#server-events) says these events should be emitted.

**Comment by AdriVanHoudt** [comment]
take a look at http://hapijs.com/api#server-events

**Comment by hueniverse** [comment]
`request` event is emitted only when you call `request.log()`. `log` event is emitted only when you call `server.log()`.

**Comment by mik01aj** [comment]
> 'request' - events generated by request.log(). Does not include any internally generated events.

It says that these events are *generated*, so I understood that they are somehow triggered by the hapi engine. If I have to trigger it manually, then these are just "events resulting from my calls to `request.log()`". No "generating" here.

> 'log' - events logged with server.log() and server events generated internally by the framework.

I expected something to be "generated internally by the framework".

Now I understand that the current behaviour is valid, just the docs are not clear about it.
