### ISSUE TITLE
Server method strings and prerequisites

### ISSUE THREAD

**Issue by MathieuLoutre** [hapijs/hapi#2644]
I have a bunch of server methods, look like these:

```coffee
	name: 'groupWithUsers'
	fn: (groupId, userId, next) -> Models.Group.findOne(_id: groupId, user: userId).populate('users').execute(next)
```

and I seem to be encountering problems when I call them inside `pre` using a string like this:

```
groupWithUsers(params.groupId, pre.user._id)
```

The result is that the second argument evaluates to `undefined` in the method although it _definitely_ exists (the first one is ok).

Does the syntax not allow two levels of dots (and is this something that should be the object of a PR or maybe a doc update)? Or does the problem lie somewhere else?

EDIT:

I'm using Hapi `7.5.3` on node 0.10.x, in case that changes anything.

**Comment by hueniverse** [comment]
The depth of keys should not be a problem as it's using `Hoek.reach()`. Can you create a failing test?

**Comment by MathieuLoutre** [comment]
Interesting. I wrote a test which reproduces the situation I'm in and it's working fine.

```js

    it('registers methods with nested path in prerequisites', function (done) {

        var server = new Hapi.Server();
        server.connection();

        server.method('group', function (groupId, userId, next) {

            return next(null, { group: groupId, user: userId });
        });

        server.method('user', function (request, next) {

            return next(null, { id: 10 });
        });

        server.route({
            method: 'GET',
            path: '/group/{groupId}',
            config: {
                pre: [
                    'user',
                    'group(params.groupId, pre.user.id)'
                ],
                handler: function (request, reply) {

                    return reply(request.pre.group);
                }
            }
        });

        server.inject('/group/5', function (res) {

            expect(res.result).to.deep.equal({ group: '5', user: 10 });
            done();
        });
    });
```

Could it be linked to the fact that the object returned by the query is a Mongoose object and not a plain old JS object?

**Comment by MathieuLoutre** [comment]
After some fiddling in the code, it turns out that it's very probably linked to the Mongoose object. `Hoek.reach()` doesn't seem to react too well if it's not a standard JS object. 

After some digging and trial/error, I found that the Mongoose object doesn't seem to return anything on `ref.hasOwnProperty(path[i])` and therefore fails. However, `ref[path[i]]` does exist and returns something.
Should I move this to the `hoek` repo? Checking for `ref[path[i]]` `instead of ref.hasOwnProperty(path[i])` does not fix the problem, but maybe there's a solution.

**Comment by hueniverse** [comment]
I am not sure if this is actually an issue... but you can bring it up in hoek and maybe there is a way to work around it.
