### ISSUE TITLE
request.app not set correctly?

### ISSUE THREAD

**Issue by lemonizer** [hapijs/hapi#2648]
Running on 8.8.0 -The `app` config obj in the route option is not being exposed through `request.app` in the handler. 

I may have missed it going through the breaking changes list. Was this feature removed? I'm referencing an older example here: https://github.com/hapijs/hapi/issues/1500

```javascript
var Hapi = require('hapi');

var server = new Hapi.Server();
server.connection({ port: 3000 });

server.route({
    method: 'GET',
    path: '/',
    config: {
        app: {
            foo: 'bar'
        }
    },
    handler: function (request, reply) {
        reply('Hello ' + request.app.foo); //Returns Hello undefined - request.app = {}
    }
});

server.start(function () {
    console.log('Server running at:', server.info.uri);
});

```

**Comment by devinivy** [comment]
You should be able to find it exposed in the route settings: `request.route.settings.app`.  `request.app` also exists, but would generally be used/set in server extensions.

**Comment by lemonizer** [comment]
@devinivy thanks for the clarification!

**Comment by devinivy** [comment]
:+1: sure thing!

**Comment by rubennorte** [comment]
I think many people has this confusion and I find myself doing this a lot:

```javascript
var something = request.route.settings.app.something || request.app.something;
```

Have you considered initializing `request.app` with the values in `request.route.settings.app`?

**Comment by devinivy** [comment]
One complication there is that during `onRequest`, `request.app` should exist, but the request _isn't routed yet_, so there's no way to know which route settings to dip into.

**Comment by rubennorte** [comment]
That's the way I'm already doing it, but I thought it'd be a nice thing to have in the framework. Same with a plugin I have to use `request.app` as default values for the templates. I understand though this complication may prevent it from being implemented in the framework.

Thanks!
