### ISSUE TITLE
Are there more debug log / request tags?

### ISSUE THREAD

**Issue by janl** [hapijs/hapi#2649]
The docs only explain `['error']` and `false` as options for the log and request tags in the `debug` server option, but the text makes it sound that there are more tags. Are there?

**Comment by briandela** [comment]
The calls take an array of strings so you can actually tag them with anything. For example:

```js
request.log(['error', 'purchase', 'retryable'], { message: 'something went wrong. see error', error: new Error() })
```

You are not limited to the tags. It's a really powerful labeling system for errors - my suggestion is that you come up with a strategy as to how you use them.

**Comment by briandela** [comment]
These docs should also help:
- `request.log` http://hapijs.com/api#requestlogtags-data-timestamp
- `server.log` http://hapijs.com/api#serverlogtags-data-timestamp

**Comment by briandela** [comment]
The debug call essentially controls which tags end up on the console so can take the same tags you use with `request.log` and `server.log`.

**Comment by hueniverse** [comment]
I'll take a PR to make it more clear. You can use any tags you want.

**Comment by janl** [comment]
Sorry if I was unclear, I was looking to debug things that happen in hapi-land, so I was wondering which tags are used inside hapi.

I was specifically referring to this section on http://hapijs.com/api (sorry, screenshot instead of a link because I couldn’t find the source on first try and I can’t seem to link to specific sections):

![screen shot 2015-07-20 at 12 46 10](https://cloud.githubusercontent.com/assets/11321/8774354/621b2cb8-2edd-11e5-9a63-be4a1ca59f51.png)

Thanks for explaining that this is also relevant for my out-of-hapi code :)

**Comment by hueniverse** [comment]
This is the list of internally generated tags: http://hapijs.com/api#internal-events

**Comment by hueniverse** [comment]
@janl how can we make the docs better?

**Comment by janl** [comment]
I was hoping for a link to http://hapijs.com/api#internal-events from the location I posted the screenshot of. If you link me to the docs repo, I can send a PR.

**Comment by AdriVanHoudt** [comment]
https://github.com/hapijs/hapi/blob/master/API.md

**Comment by hueniverse** [comment]
I'm confused. While the section itself is not linked, the two subsections are linked under log and request.

**Comment by tiagocpontesp** [comment]
@hueniverse > how can we make the docs better?
Please reduce the line-spacing from 1.75 to 1.4, max 1.45. 
I find them hard to read through mostly because of it.
