### ISSUE TITLE
Thought: `server.route` plugin hooks.

### ISSUE THREAD

**Issue by devinivy** [hapijs/hapi#2650]
I want to put forward an idea that could turn into a more spec'ed-out feature request if this generates any conversation.  The main idea: it would be nice for plugins to be able to hook into `server.route` calls that occur on overlapping connections (between the `server` and plugin).

This would allow for route-level plugin settings to be taken into account by a plugin _before_ a request is made to a particular route, which is really all I'm trying to achieve.  Most likely the route public interface would be reported to the appropriate plugins (either, those on relevant connections or those also mentioned in a particular route's plugin settings).

**Comment by hueniverse** [comment]
I need an example.

**Comment by devinivy** [comment]
One example would be a plugin that enables server extensions (or even other routes) based upon existing route tags, scopes, or other route settings.  It's crude, but that might look something like,
```node
exports.register = function (server, options, next) {

    var enhancedLogging = false;

    server.addedRoute(function(route) {

        var tags = route.settings.tags || [];
        if (!enhancedLogging && tags.indexOf('logs') >= 0) {

            enhancedLogging = true;
            server.ext('onRequest', function(request, reply) {

                // Enable some enhanced logging

                return reply.continue();
            });
        }
    });

    next();
};

exports.register.attributes = {
    // Plugin info
};

```

**Comment by hueniverse** [comment]
Are you asking for the plugin to be notified whenever a route is added anywhere so it can act on it? As in a "new route" event?

**Comment by devinivy** [comment]
Yes, precisely.

**Comment by hueniverse** [comment]
That's seems too complicated. Why not setup a server `start` event listener and just go over the routing table at that point?

**Comment by devinivy** [comment]
I can see how it could be considered complicated, and that's an okay solution for me.  It might be nice to not have to rely on the server being started, but I'll drop this– it doesn't seem like anyone jumped on this as a life-changing feature for them.  Thanks for entertaining the thought.
