### ISSUE TITLE
Setting headers and auth middleware

### ISSUE THREAD

**Issue by kevinsimper** [hapijs/hapi#2651]
I am using hapi.js because I heard that it was good for making a proxy in, but I found it really difficult to use, if you want to set custom headers, that is nearly impossible.

And if you use a middleware like `hapi-auth-basic` and want to expose a header to the client, like `X-api-version`, I did not find a solution. I ended up taking the whole code into my project.

I propose:
- That it should be possible to set headers in `onRequest`.
- Or that it would be possible to set headers in onPostHandler, but then that function should run as well if you are doing authentication.

**Comment by mtharrison** [comment]
Setting custom headers pretty straightforward. Why do you say it's nearly impossible?

    server.route({
        method: 'GET',
        path: '/{p*}',
        handler: {
            proxy: {
                mapUri: function (request, callback) {

                    var headers = {
                        'X-Req-Header': 'I\'m a custom request header'
                    };
                    
                    var uri = 'http://hapijs.com' + request.url.path;
                    callback(null, uri, headers);
                },
                onResponse: function (err, res, request, reply) {

                    reply(res).header('X-Res-Header', 'I\'m a custom response header');
                }
            }
        }
    });

**Comment by kevinsimper** [comment]
@mtharrison Thank you for your response. Yes, that is correct that you can set a header inside a `route.handler`, but if you are using a library like `hapijs-basic-auth` the request never reaches `route.handler`, because the middleware replies.

**Comment by mtharrison** [comment]
@kevinsimper So you want to add a custom header to the 401 response? You can do:

    server.ext('onPreResponse', function (request, reply) {

        var response = request.response;

        if (response.isBoom && response.output.statusCode === 401) {
            response.output.headers['X-Other-Custom'] = 'Blah';
        }

        return reply(response);
    });
