### ISSUE TITLE
Is it possible to send any parameter value to route handler pre?

### ISSUE THREAD

**Issue by anilapu** [hapijs/hapi#2652]
Hi, I am new to hapi. I want to use pre as a middleware function for authorization. For that I have to pass permission to pre function which will check whether logged in user have the permission or not?
When I try to pass a parameter it throws Error: Invalid route config.So is it possible to pass parameter into a pre function?

**Comment by mtharrison** [comment]
Related: http://stackoverflow.com/questions/31517335/how-to-pass-params-into-route-handler-pre-hapi-js

**Comment by anilapu** [comment]
@mtharrison Is that question has correct answer?

**Comment by mtharrison** [comment]
The reason you're getting an invalid route config in that example is that what you're assigning to `config.pre.method` isn't a valid pre method. You're assigning the return value of:

`Activity.checkVal(1)`

Which isn't a function. It's `undefined`.

It needs to be a function, like so:

    server.route({ 
        method: 'GET', 
        path: '/getUser', 
        config: {
            handler: User.getUser, 
            pre: [
                { 
                    method: function (request, response) {

                        ... // logic goes in here
                    } 
                }
            ]
        }
    });

**Comment by anilapu** [comment]
yes the way I call pre is incorrect but It is a common functionality to check user authorization. Every time I have to write almost same piece of pre function code in every route

**Comment by mtharrison** [comment]
I'm not sure what your point is. What's preventing you from doing what you need, if you assign a valid pre function?

**Comment by anilapu** [comment]
My aim is to check whether logged in user has permission for api to access it. For that I choose pre method. In that function I am getting set of permissions user has. Now I need to pass particular persmissionId to check whether it exists in his set of permissions.

**Comment by mtharrison** [comment]
Ok, and given the solution I posted above, what's now preventing that from happening?

FYI What you're describing sounds awfully similar to scopes, which there's an example of here: http://stackoverflow.com/questions/29052940/role-based-authentication-in-hapijs

Yet another possible way to do it if you don't want to return a function is to put your route's "permission level" on the config object and check it that way:

    var checkVal = function (request, reply) {

        var permissionLevel = request.route.settings.app.permissionLevel;

        ... // decide whether to allow
    };

    server.route({
        config: {
            app: {
                permissionLevel: 1  // "permission level" for this route
            },
        },
        pre: [
            checkVal   
        ]
        method: 'GET',
        path: '/',
        handler: function (request, reply) {

            ... // do whatever
        }
    });

**Comment by anilapu** [comment]
Thanks @mtharrison this is what I want.My problem is solved.

**Comment by golb** [comment]
Hello,

so, in manual "app - application-specific configuration. Should not be used by plugins which should use plugins[name] instead." When i use in plugin like:
pluginName: {...}  or plugins[myPluginName]: {...} or any other variants not worked. When i use 'app' works well. What is correct syntax for plugins?

**Comment by ferrao** [comment]
Same question here, what is the correct syntax for plugins?
