### ISSUE TITLE
Question: How-To Use Multiple Auth Strategies

### ISSUE THREAD

**Issue by Icehunter** [hapijs/hapi#2654]
I use:

hapi-auth-jwt2
hapi-auth-signature
hapi-auth-basic

My config is like so:
```
auth: {
    strategies: [
        'rsa',
        'hmac',
        'token'
    ]
},
```

The following lines are only ever called once:
https://github.com/hapijs/hapi/blob/master/lib/auth.js#L218
https://github.com/hapijs/hapi/blob/master/lib/auth.js#L231

This is never called:
https://github.com/hapijs/hapi/blob/master/lib/auth.js#L199

I'm doing this wrong I assume? Is there anything I can do to make it work without "try"?

**Comment by hueniverse** [comment]
It will try them in the order provided and will stop when a strategy is found (even if it is invalid). A request can only be authenticated with a single strategy, but if the first one is not present, it will try the second, and so on.

**Comment by Icehunter** [comment]
@hueniverse Thanks! I incorrectly assumed it would work until one is found or all are invalid :)
