### ISSUE TITLE
Possible race condition for reply with specific type?

### ISSUE THREAD

**Issue by KrisSiegel** [hapijs/hapi#2655]
This is boggling my mind but essentially there is a configuration that gets included into some front end code as a simple JavaScript object so client code can access it. Simple enough, right? I'm trying to force it to return as ```"application/javascript"``` but running my unit tests it sometimes returns as ```"application/javascript"``` and other times it returns as ```"application/json; charset=utf-8"```. I can't figure out what's wrong here.

```javascript
// Setup route for dynamic client-side configuration serving
var clientConfig;
server.route({
    method: "GET",
    path: "/lib/configuration.js",
    handler: function (request, reply) {
		if (clientConfig === undefined) {
			clientConfig = "var configuration = " + JSON.stringify(configuration.client) + ";";
		}
		
		return reply(clientConfig).type("application/javascript").encoding("utf8");
	}
});
```

Is there some sort of race condition here?

(moved from https://github.com/hapijs/discuss/issues/132)

Edit: I should probably mention here that this is in a project currently without any security setup (so essentially a vanilla hapijs server). I can try to create a smaller, reproducible project later today if it's needed (I still don't necessarily know this is a hapijs issue but I'm also not sure what I would be doing wrong here).

**Comment by kanongil** [comment]
I'd guess that this is caused by `JSON.stringify()` throwing, aborting the handler, and returning a JSON object response.

Is it always the same input?

**Comment by KrisSiegel** [comment]
Yeah always the same and when it fails to output the correct type it still contains the same data. I'll see if I can create a simplified test case in a new project.

**Comment by KrisSiegel** [comment]
I think I figured out the issue here; I had a part of my unit tests a step where it starts the server then does some testing against the endpoints and I think what was happening was it simply hadn't registered the endpoint yet so the test was getting the 404 json but the web browser just always seemed to have the cached JavaScript (or maybe it only happened in unit tests because of the speed; I'm not seeing it in the web browser anymore).

Though I am curious as the code is structured to setup all the routes first (runs in ```server.after()```); does this mean even though there isn't a callback that route setups happen asynchronously?

**Comment by hueniverse** [comment]
I am not following how the 404 could be related. Adding routes is blocking so no issue there.

Is this still an issue? Can you help me reproduce?

**Comment by KrisSiegel** [comment]
Sorry I can't seem to reproduce this in the original project anymore or in the a small project I created just for this issue. It must have been a side effect to something else I'm just not sure what it was right now.
