### ISSUE TITLE
Customise output from Inert's directory listing handler?

### ISSUE THREAD

**Issue by Trippnology** [hapijs/hapi#2656]
The main thing I'd like to do is add `<meta name="viewport" content="width=device-width, initial-scale=1">` so mobile users get a more sensible first view. Perhaps add a stylesheet too. Is this possible?

**Comment by arb** [comment]
Did you mean to open this on the hapijs.com repo instead? hapi doesn't know anything about meta tags?

**Comment by mtharrison** [comment]
Think he means the directory handler listing that comes from https://github.com/hapijs/inert

**Comment by Trippnology** [comment]
I am indeed talking about the built in `directory` handler.

**Comment by Trippnology** [comment]
I see the html is [hard coded into inert](https://github.com/hapijs/inert/blob/master/lib/directory.js#L211). :(

**Comment by kanongil** [comment]
Indeed. The current listing mode is very barebones and probably only suitable for testing.

I could just add the extra html you suggest but I don't think that is the right way to go with this. I created https://github.com/hapijs/inert/issues/31 which I believe can be used to solve your issue.

**Comment by hueniverse** [comment]
Moved to inert.
