### ISSUE TITLE
payload validation for routes that have multiple method arguments

### ISSUE THREAD

**Issue by ugate** [hapijs/hapi#2659]
Is there a way to handle ```payload``` validation for routes that have multiple ```method``` arguments?
```js
server.route({
    method: [ 'GET', 'POST' ],
    config: {
        validate: {
            payload: {
                value: Joi.string().required()
            } 
        }
    }
});
```
I get the following error:
```Cannot validate HEAD or GET requests```

v8.8.0

**Comment by mtharrison** [comment]
I would advise making those routes separately. Payload validation doesn't make sense for GET requests.

**Comment by hueniverse** [comment]
The right solution as @mtharrison said is to split it.

**Comment by ugate** [comment]
@mtharrison @hueniverse  just wanted to reduce the amount of boilerplate... seems redundant to have duplicate route properties just because of one separate property, no?

What about allowing ```validate``` take an ```Array``` like the following?
```js
server.route({
    method: [ 'GET', 'POST' ],
    config: {
        validate: [
            {
                query: {
                        value: Joi.string().required()
                }
            },
            {
                payload: {
                        value: Joi.string().required()
                }
            }
        ]
    }
});
```

**Comment by hueniverse** [comment]
Method array makes sense when the routes are really identical. It is really just a shortcut and internally it is the same as adding two completely separate routes. In this case verbosity is better.

**Comment by ugate** [comment]
@hueniverse The routes are near-identical with the exception of the method and validation. the handler, path, etc. are all the same. So, verbosity in the 2nd proposed solution makes sense?

**Comment by hueniverse** [comment]
I am not going to add this. Multiple methods is a simple shortcut. If you need more, either write your own helper or just repeat the route.
