### ISSUE TITLE
internals.Server does not allow proto inheritance

### ISSUE THREAD

**Issue by harrytruong** [hapijs/hapi#2663]
> https://github.com/hapijs/hapi/blob/master/lib/server.js#L27
> ```js
> exports = module.exports = internals.Server = function (options) {
>
>     Hoek.assert(this.constructor === internals.Server, 'Server must be instantiated using new');
> ```

Is there a reason why `this.constructor === internals.Server` is used? This breaks prototypical inheritance, preventing the `internals.Server` class from being extended. 

Here's a simplified setup for the issue:
```js
var Server = function(options) {
  if (this.constructor !== Server) throw 'Must use new.'; 
}

// this inheritance helper comes from babel (6to5)
function inherits(subClass, superClass) {
    subClass.prototype = Object.create(
        superClass.prototype,
        { constructor: {
            value: subClass,
            enumerable: false,
            writable: true,
            configurable: true
        } }
    );

    Object.setPrototypeOf(subClass, superClass);
}

// extended child of Server (inheritance style comes from babel/6to5)
var BlueServer = (function (_Server) {
    inherits(BlueServer, _Server);
    function BlueServer(options) {
        Object.getPrototypeOf(BlueServer.prototype).constructor.call(this, options);
    }
    return BlueServer;
})(Server);
```

The following works properly:
```js
var server = new Server(); // no error, good.
var server = Server(); // throws "use new" error, good.
```

But this throws an error, when it shouldn't:
```js
var blueServer = new BlueServer(); // throws "use new" error, BAD
```

Changing `(this.constructor !== Server)` to `!(this instanceof Server)` fixes the issue:
```js
var server = new Server(); // no error, good.
var server = Server(); // throws "use new" error, good.

var blueServer = new BlueServer(); // no error, good.
var blueServer = BlueServer(); // throws "use new" error, good.

blueServer instanceof Server; // true, respects prototypical inheritance
```

----

This issue is directly related to https://github.com/hapijs/contrib/issues/43. I wasn't sure if I needed to file the issue in both places.

**Comment by hueniverse** [comment]
Why would you want to inherit from Server?

**Comment by harrytruong** [comment]
I have no real reason. I was playing around with reusing Hapi's components in a side project. When I extended from Server to test something, I saw the implementation, and was just curious about the rationale behind it.

**Comment by harrytruong** [comment]
I traced the `this.constructor === Constructor` choice back to @thegoleffect, [way back in 2012](https://github.com/hapijs/hapi/blob/eb29245f2d4935d8b3aa503a2cbc5a64a07c7aaf/lib/server.js#L45). Maybe he can explain why it was used instead of `this instanceof Constructor`?

**Comment by hueniverse** [comment]
I'm ok changing the style of the implementation. If you want, you can open a PR on this and on the style guide.

**Comment by harrytruong** [comment]
PR submitted. Thanks for the consideration/approval. I really appreciate the responsiveness!
