### ISSUE TITLE
Support for plugin alias option

### ISSUE THREAD

**Issue by dylancwood** [hapijs/hapi#2666]
# Background

For discoverability, plugins are often named quite verbosely, with the word *hapi* in them. Further, they are often hyphenated (e.g. `hapi-redis`). See https://github.com/sandfox/node-hapi-redis/issues/9 for a specific example.

# Problem

1. The hyphens used by most authors prevent developers from referencing the plugin with dot notation. They have to use bracket notation to reference the plugin (e.g. `server.plugins['hapi-redis']). IMO this adds up to wasted time, and ugly code. 
1. While it makes sense to prefix a plugin name with the the word *hapi* when interacting with it outside of hapi (e.g. `npm i hapi-redis`), it is redundant inside of hapi (e.g. `server.plugins['hapi-redis']`).

# Solution

Packages need to be discoverable, so prefixing them with *hapi-* is important. Further, it is important that the plugin name match the package name so that it is easy to understand where the plugin comes from. In order to maintain both of these requirements, and solve the above problem, I suggest that we support a user-defined `alias` option when registering a plugin. This idea was actually originally suggested by @Marsup on gitter when I asked for ideas about this problem. 

Here is how I envision the `alias` option being used:

```js
server.register([
    {
      register: require('hapi-redis'),
      options: {},
      alias: 'redis'
    },
    require('boom')
  ],
  { /*hapi-options*/ },
callbackFn
);
```

At first glance, I think that this could be accomplished in [lib/plugin.js](https://github.com/hapijs/hapi/blob/master/lib/plugin.js#L340) just after line 340:

```js
internals.Plugin.prototype.expose = function (key, value) {

    Hoek.assert(this.realm.plugin, 'Cannot call expose() outside of a plugin');

    var plugin = this.realm.plugin;
    this.root.plugins[plugin] = this.root.plugins[plugin] || {};
    // need to figure out how to grab alias :-(
    this.root.plugins[alias] = this.root.plugins[plugin];
    this.root.plugins[
    if (typeof key === 'string') {
        this.root.plugins[plugin][key] = value;
    }
    else {
        Hoek.merge(this.root.plugins[plugin], key);
    }
};
```

# Discussion

**What do you all think about adding a plugin alias for easier namespacing of plugins?**

**Comment by hueniverse** [comment]
I have no objection. This needs to go in the `option` passed to `server.register()` as the second argument. It can only be passed when there is a single plugin. I plan to make some changes to this API that will allow setting it for multiple plugins but for now these are the specs.

I'll take a PR.

**Comment by dylancwood** [comment]
Awesome. I'll get started on the PR right away.

**Comment by hueniverse** [comment]
On second thought, this is not going to work. There is no way to resolve the namespace conflicts that this can create. I am going to come up with a different solution for this. Mostly, I just need to find a different place to put this other than `server.plugins`.

**Comment by hueniverse** [comment]
Instead of putting the aliased content under `server.plugins` which is going to be a mess if there are conflicts (and simply preventing override isn't a valid solution), I put the aliases under `server.aka`. I am not super happy about this name. I might just drop this feature but for now it's in under this new spot.

I'm open to other ideas and feedback.

**Comment by Marsup** [comment]
Which namespace conflicts ? The aliases should be under the sole responsibility of the one doing the registers, plugins themselves shouldn't have control over it. We might be able to prevent duplicate aliases (or conflicts with existing plugin names) but I'd put that on developer's stupidity.

**Comment by dylancwood** [comment]
I tend to agree with @Marsup on this: If the user wishes to override the `server.plugins.x` namespace with an alias, then they should be free to do so. We could add a warning that is sent to `server.log` if such a namespace collision is detected to help with debugging unintentional overloading.

The trickiest part with detecting the namespace collisions IMO is that it is possible for `multi` plugins to `expose`. This means that each exposure could be interpreted as an overloading event. 

I'm happy to continue to work with you both to continue refining this feature, so let's keep the discussion going :+1:

**Comment by devinivy** [comment]
What if multiple plugins have a dependency on the same plugin that is being aliased?  Do they both have to know the aliased name?  I'd be less worried about a collision in aliased names, and more worried about breaking the nice property of the hapi ecosystem that a plugin knows how to use/reference other plugins by the package `name` attribute.  I don't think hapi itself can really account for that.

One option would be to use something like `server.aka` to separate aliased names, and another would be for `server.plugins` to include both aliases and names specified by package attributes (e.g. `server.plugins['hapi-redis']` and alias `server.plugins.redis` both exist and have the same object reference).

**Comment by Marsup** [comment]
It's an alias, not a rename, you'll have both names (real & alias) available in the end, plugins dependencies must still be declared with their real name. That's already what @dylancwood's PR does.

**Comment by hueniverse** [comment]
@dylancwood letting people shoot themselves in the foot is absolutely not the hapi way. The framework goes out of its way to protect people from making mistakes and an alias stepping over another plugin namespace fits this pattern.

What this boils down to is the problem that exposed plugin apis are pretty messy to use right now. This gets even worse if we are looking for these apis from a request (e.g. `request.server.plugins['some-plugin-name'].some_method()`). I need to sit on this for a bit but I think I am going to replace `aka` with something like `s` (for shortcut) and map the same thing to the request object. Once you shortcut a plugin when you register it, you will have its methods under `server.s.alias_name` and `request.s.alias_name`. Another option I am considering is introducing a new third argument for passing an application environment variable. More on that later.

**Comment by hueniverse** [comment]
I've removed this for now. I need to think about this some more.

**Comment by dylancwood** [comment]
@hueniverse I am glad that hapi helps developers avoid shooting themselves in the foot, and would be happy to help come up with a scheme that avoids the accidental overloading issue.  I'll post possible solutions here as they come to me. 

I think that it might be good to take a step back and mention the problem that the alias feature aims to solve: **Discoverable plugin names are inherently redundant and awkward to work with inside of hapi (e.g. `hapi-redis`).** 

Another solution to this problem would be to encourage plugin authors to specify a more concise plugin name in `register.attributes` that does not match the package name in `package.json`.For instance, simply dropping the `hapi-` portion of a package name may make a lot of sense. I believe that the current docs on plugin development encourage authors to match the package and plugin names, but it looks like the hapi plugin registration code is built to allow overriding the package name.

@devinivy I understand your comment. In fact, you have accurately described how my PR works in the second paragraph of your comment.
> ...and another would be for server.plugins to include both aliases and names specified by package attributes

To explain further: As @Marsup said, the alias is an *additional* name for a plugin, not a replacement name. As such, plugin dependencies shouldn't be affected by an alias, since the original plugin name remains registered and in-tact.

**Comment by Marsup** [comment]
Careful with letting authors define their alias, npm guarantees you there will be no collision on package name, not on that alias, if you let authors define their own, everyone will be named redis and you'll be back to square one. (that's why I suggested user-defined aliases in the 1st place)

**Comment by dylancwood** [comment]
Good point @Marsup! I agree with you, and take back my previous suggestion. 

Hapi guarantees that plugins will not overload each other (it throws an error unless the plugin is a `multi` plugin). However, tracking down which plugins are conflicting might be difficult if the plugin names do not match the package name (e.g. if some author decides to name their plugin `boom`, but the package name is `node-hapi-basic-object-oriented-methods-plugin`.). **Further, if both plugins are `multi` plugins, then I think that they the will both be registered to the same namespace.**

A unique `pluginId` could help to prevent this as well. Perhaps a checksum of the plugin's attributes?

**Comment by spiralni** [comment]
By default, why not to alias the plugin just removing the hypen , e.g hapi-redis alias hapiredis. Al least it let us use the dot notation.

**Comment by dylancwood** [comment]
I thought of that as well, in fact it was my first solution to the problem. Unfortunately,it might still cause namespace issues in some edge cases. For instance, imagine that someone creates a hapi plugin called `hapiredis`, which offers some different functionality compared with `hapi-redis`. I want to use both `hapi-redis` and `hapiredis` in my application (each one for a different redis connection). I will have a namespace collision in the aliases because both plugins will have the same alias. If hapi detects this collision, it may throw an error and refuse to start, and I would not be able to do anything to avoid the error, because I have no power over the alias used for the plugins. 

That is why a user-defined alias is ideal.

**Comment by hueniverse** [comment]
The only solution I am open to is to define a new namespace and put it there alongside `plugins` but that's kinda ugly. So I am going to close this without taking any action. I think people should use better names for their modules.
