### ISSUE TITLE
Set plugin prefix in the plugin itself

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/hapi#2667]
Atm you can pass a plugin prefix with the `options` on `server.register`. I would like to define a 'global' (at plugin level) prefix as well so the plugin also has control over the prefix.
I would still allow the prefix to be passed by the `options`.
This would result into `route = options.prefix + plugin.attributes.prefix + route.path`

Would you accept a PR for this?

**Comment by mtharrison** [comment]
You can modify the prefix inside the register function?

**index.js**

    var Hapi = require('hapi');

    var server = new Hapi.Server();
    server.connection({ port: 8080 });

    server.register(require('./plugin'),
        {
            routes: {
                prefix: '/outside'
            }
        }, 
    function () {

        server.start();
    });

**plugin.js**

    exports.register = function (server, options, next) {

        server.realm.modifiers.route.prefix += '/inside';

        server.route({
            path: '/path',
            method: 'GET',
            handler: function (request, reply) {

                reply('ok');
            }
        });

        next();
    };

    exports.register.attributes = {
        name: 'plugin'
    }

The route is then `GET /outside/inside/path`

**Comment by AdriVanHoudt** [comment]
Yeah that is want to avoid. I want to give the plugin the responsibility of setting its own prefix like I have a `user` plugin and it prefixes all it routes with `/user/`. I want it to be some option in `register.attributes` or something rather than setting it in the server registration logic

**Comment by mtharrison** [comment]
The plugin does have the responsibility in my example though. It's modifying the prefix internally. Are you just looking for a way to do the same in config instead?

**Comment by AdriVanHoudt** [comment]
oh wow totally missed that line :open_mouth: and yeah that works but config would look cleaner and it will be 1 line of code from the looks of it then

**Comment by hueniverse** [comment]
I am not a fan of messing with the realm config this way. Config should be treated as read-only (and will probably become const at some point).

The right way to accomplish this is with a utility that simply adds a prefix before calls to `route()` are called. Basically this sounds like a shortcut, not a core feature.

**Comment by AdriVanHoudt** [comment]
Is there a way to come between the route calls? Because then I could make an easy plugin

**Comment by hueniverse** [comment]
You can decorate the server with your own version of adding a route function.

**Comment by devinivy** [comment]
That's a good solution to a problem closely related to a question/proposition I posed over at #2566.

**Comment by AdriVanHoudt** [comment]
@hueniverse like overriding the function or decorating with server.decorate/method(don't know the right one from the top of my head)
@devinivy this is about startup not about during lifecycle stuff

**Comment by devinivy** [comment]
Ugh, sorry @AdriVanHoudt – I linked to the wrong issue.  Try #2650.

**Comment by AdriVanHoudt** [comment]
I am not fully following your explanation in the issue and yeah something like
```js
Var oldRoute = server. Route()
Server.route = function () {
    My stuff
}
```

(Programming on phone :P)

**Comment by devinivy** [comment]
See docs for `server.decorate`: http://hapijs.com/api/8.8.0#serverdecoratetype-property-method.  

Ex.
```node
var specialRoute = function (definition) {

    // Transform or glean info from definition then...
    server.route(definition);
}

server.decorate('server', 'specialRoute', specialRoute);

server.specialRoute({/* Route definition */});
```

**Comment by mtharrison** [comment]
@AdriVanHoudt You could have a plugin that does this:

    server.decorate('server', 'routePrefix', function (prefix) {

        var originalRoute = this.route;
        
        return function (options) {

            options = [].concat(options);

            for (var i = 0; i < options.length; i++) {
                options[i].path = prefix + options[i].path;
            }

            return originalRoute.call(server, options);
        };
    });

And then use it like this:

    var route = server.routePrefix('/adri');

    route({
        method: 'GET',
        path: '/path',
        handler: function (request, reply) {

            reply('hello');
        }
    });

    route([{
        method: 'GET',
        path: '/path2',
        handler: function (request, reply) {

            reply('hello');
        }
    }, {
        method: 'GET',
        path: '/path3',
        handler: function (request, reply) {

            reply('hello');
        }
    }]);

Each route is then prefixed with `/adri`

**Comment by AdriVanHoudt** [comment]
can I do `server.decorate('server', 'route', myRoute);` so that I don't have to change the calls but the implementation is just different?

**Comment by mtharrison** [comment]
No, you'll get an error:

`Error: Cannot override the built-in server interface method: route`

**Comment by AdriVanHoudt** [comment]
:disappointed: 
Could I force it by not using `decorate` but just doing:
```js
var old = server.route;
server.route = function() {
    // my own stuff...
    old();
};
```
