### ISSUE TITLE
Multiple Plugins List Register using server.register()?

### ISSUE THREAD

**Issue by bboysathish** [hapijs/hapi#2669]
So, i have two plugin list as shown below,

```
var plugins1 = [{'register':"something",options:{'hi':"key"}},{'register':"something",options:{'hi1':"key1"}}]
var plugins2 = [{'register':"something1",options:{'hi2':"key2"}},{'register':"something",options:{'hi3':"key3"}}]

And, i have two separate options for each plugins list,

i have two sepate options for this,

var plugin1Options = {routes:{prefix: '/api'}}
var plugin2Options = {routes:{prefix: '/webapi'}}

Normally, to register this we use following,

server.register(plugins1,plugin1Options,function(err){
   if(err){
     throw err;
   }
   
   server.register(plugins2,plugin2Options,function(err){
      if(err){
        throw err;
      }
     server.start();
   })   
})

```

What i am actually doing now to overcome this,

```

var routes = {
  'version02': {
    register: require('./version02'),
    options: {
      routes: {
        prefix: '/v2'
      }
    }
  }
};

module.exports = function registerRoutes(server, done) {
  Object.keys(routes).forEach(function(aRoute) {
    server.register(routes[aRoute].register, routes[aRoute].options, function(err) {
      if (err) {
        throw err;
      }
      done(server);
    })
  })
};
```

1. Is this a feasible way?
2. Can i achieve this without duplicating the server.register(),because in future i may have 5+ Plugin lists.
3. Above method which i am following to register , throws an errors (the plugin already registered), when running with forever(whenever forever restarts the process).

**Comment by hueniverse** [comment]
You should look at using glue (or discuss this use case there). The goal is for hapi to provide a minimal register function and for other modules to provide better utilities to manage it.

**Comment by bboysathish** [comment]
Awesome! Thanks for adding that feature.. This should reduce the overload of the plugin register with additional options.. Great!!! :)
