### ISSUE TITLE
304 response sends: no-cache regardless of routes.cache settings

### ISSUE THREAD

**Issue by atomantic** [hapijs/hapi#2673]
configuring 
```
routes.cache = {
       expiresIn: 900000,
       privacy: "public"
}
```
is working great for 200 responses, but when the if-non-match or if-modified-since matches and converts the response to a 304, the cache-control header becomes "no-cache". Normally, this is OK, as a browser will use the existing cached asset instead of updating the cache-control with the 304 cache-control header, but this makes a reverse proxy like Akamai unhapi.

This RFC suggests a 304 should always return the same cache-control that a 200 would return: https://tools.ietf.org/html/rfc7232#section-4.1
```
The server generating a 304 response MUST generate any of the following 
header fields that would have been sent in a 200 (OK) response 
to the same request: 
Cache-Control, Content-Location, Date, ETag, Expires, and Vary.
```

**Comment by kanongil** [comment]
@atomantic See https://github.com/hapijs/hapi/issues/2676#issuecomment-128298036 for a work-around.

@hueniverse I am looking into fixing this. I have created a failing test case but I am not sure about the right way to implement the actual fix.

I am leaning towards amending the default `cache.statuses` option with the 304 header. However, this does not fix the issue for anyone who is already using the option (with 200 and no 304).

The other option is to implicitly add the 304 response as cacheable whenever 200 is included in the `cache.statuses` list. This is simple to do while converting the list to an object for the lookup.

**Comment by hueniverse** [comment]
It needs to be explicit in the logic, not the config.
