### ISSUE TITLE
Cors not working for me

### ISSUE THREAD

**Issue by ballerabdude** [hapijs/hapi#2674]
I dont know what i'm doing but with this configuration shouldn't cors be enabled?

app.js
```javascript
'use strict';

let Hapi = require('hapi'),
    fs = require('fs'),
    config = require('./config/application');


let serverConfig = { };
let server = new Hapi.Server(serverConfig);

server.app.name = config.app.name;

server.connection({port: config.app.port, routes: {cors: true}});

// Iterates through all ./routes files to init the routes for use in the api
fs.readdirSync('./routes').forEach(function(curFile) {
  if (curFile.substr(-3) === '.js') {
    let route = require('./routes/' + curFile);
    route.routes(server);
  }
});

server.start(function (err) {
  let dashChars = '+' + Array(32 + server.info.uri.length + server.app.name.length).join('-') + '+';
  console.log(dashChars);
  console.log('| Application `%s` is running at %s |', server.app.name, server.info.uri);
  console.log(dashChars);
});
```
route1.js
```javascript
'use strict';
let CrowdController = require('../controllers/crowdController');

let crowdController = new CrowdController();

function CrowdRoutes(server) {
  server.route({
    method: 'POST',
    path: '/api/login',
    handler: crowdController.authenticateUser
  });
}

module.exports.routes = CrowdRoutes;

**Comment by hueniverse** [comment]
I have no idea what the problem is without a lot more information like curl examples with verbose response turned on, client side logs from the browser, etc. Just because CORS isn't working doesn't mean the problem is with the server's header.

**Comment by ballerabdude** [comment]
@hueniverse Thanks for the reply. I figured out the problem. When I started my server for some reason it was being hosted on http://abduls-macbook-pro.local:8080 instead of http://localhost:8080. Thanks for thanks for asking for curl examples because I did not even think about it.

![image](https://cloud.githubusercontent.com/assets/7660642/9050968/746dbdcc-3a22-11e5-9aef-6e301d5df42e.png)
