### ISSUE TITLE
Handling failed authentication

### ISSUE THREAD

**Issue by gilly3** [hapijs/hapi#2679]
My goal is simple - if authentication fails, redirect to a login page.  This is not fancy or new, and yet I'm struggling to see how to do it.  I must be missing something obvious.

In trying to figure this out I tried creating an auth scheme that simply redirects to a login scheme:

```js
server.auth.scheme("login", function (server, options) {
	return {
		authenticate: function (request, reply) {
			reply.redirect("/login");
		}
	};
});
server.auth.strategy("login", "login");
server.auth.default({ strategies: ["jwt", "login"] });
```

But, this fails because `jwt` returns a message, `"Token expired"`.  The rules for using multiple auth strategies are unintuitive:

> When the scheme `authenticate()` method implementation calls `reply()` with an error condition, the specifics of the error affect whether additional authentication strategies will be attempted if configured for the route. If the `err` returned by the `reply()` method includes a message, no additional strategies will be attempted. If the `err` does not include a message but does include a scheme name (e.g. `Boom.unauthorized(null, 'Custom')`), additional strategies will be attempted in order of preference.

Huh?! Not just unintuitive, but inflexible.  Since whether or not failed authentication includes a message depends on the scheme, using a plugin for my auth scheme leaves me at the mercy of the plugin author whether or not to include a message for auth failure reason.

So, then is this the correct way to redirect to login when auth fails?

```js
server.auth.scheme("login", function (server, options) {
	return {
		authenticate: function (request, reply) {
			server.auth.test("jwt", request, function (err, credentials) {
				if (err) {
					reply.redirect("/login");
				}
				else {
					reply.continue({ credentials: credentials });
				}
			});
		}
	};
});
server.auth.strategy("login", "login", true);
```

The above seems to work.  Is it right?  Is there a better way to redirect to a login page when authentication fails?

**Comment by devinivy** [comment]
Perhaps you could set your route authentication mode to `try` then add an onPostAuth hook that orchestrates the redirect.  Or manage this during onPreResponse.

**Comment by hueniverse** [comment]
First, you can't have multiple authentication strategies attempted per route. You can provide a list and the first to return anything other than a not-present status will end the chain. This is how HTTP works. If you want to have multiple authentication layers, you can only use one with the built-in infrastructure and the rest must go elsewhere (`onPostAuth`, the handler, pre, etc.).

Second, the scheme author decides what constitutes a bad authentication vs. missing authentication. This is an important distinction and again is based on HTTP.

Your solution to manually run the JWT scheme within your custom scheme is perfectly valid. I don't know anything about JWT but hapi-auto-cookie does provide this redirection feature as part of the scheme.
