### ISSUE TITLE
Documentation error: 'cache' in server.connection, not routes object

### ISSUE THREAD

**Issue by mindbits** [hapijs/hapi#2680]
I tried the proposed fix in #2676 (server.connection({ …, cache: { statuses: [200, 304] } })) but it's not working as 'cache' is not allowed for the connection method, though http://hapijs.com/api states the cache : {statuses: [..]} object as an option for it.

So I guess it's a documentation error and should be moved from server.connection to the cache part of the routes object where the statuses array is missing?

**Comment by devinivy** [comment]
Indeed!  That seems to be the case.  `statuses` should be a route `cache` option next to `expiredIn`, `expiresAt`, and `privacy`.  Here's an example usage from the tests: https://github.com/hapijs/hapi/blob/c29d2e1cf6d4b95445683b9ef2b7da49fc3547d6/test/transmit.js#L2434 .

**Comment by kanongil** [comment]
Ah, nice catch. I had not actually tried it, and assumed that the api docs were correct.
