### ISSUE TITLE
Override an existing decoration

### ISSUE THREAD

**Issue by aymericbeaumet** [hapijs/hapi#2702]
It is currently not possible to override an existing decoration. For example the following code will fail (by design):

```javascript
var Hapi = require('hapi');
var server = new Hapi.Server();
server.decorate('request', 'foobar', function DBConnection() {});
server.decorate('request', 'foobar', function DBConnectionMock() {}); // expected override
```

```
/private/tmp/hapidecoration/node_modules/hapi/node_modules/hoek/lib/index.js:723
    throw new Error(msgs.join(' ') || 'Unknown error');
          ^
Error: Request interface decoration already defined: foobar
    at Object.exports.assert (/private/tmp/hapidecoration/node_modules/hapi/node_modules/hoek/lib/index.js:723:11)
    at internals.Generator.decorate (/private/tmp/hapidecoration/node_modules/hapi/lib/request.js:50:10)
    at internals.Plugin.decorate (/private/tmp/hapidecoration/node_modules/hapi/lib/plugin.js:300:37)
    at Object.<anonymous> (/private/tmp/hapidecoration/index.js:4:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

I would like to be able to redefine an existing decoration, mainly for testing purpose so as to mock DB connections, etc.

Maybe adding an option would make sense:

```javascript
server.decorate('request', 'foobar', function DBConnectionMock() {}, { force: true });
```

**Comment by hueniverse** [comment]
This is asking for trouble. We don't allow overriding anything (routes, ext, methods, decorations, etc.). You can always monkey patch for testing.

**Comment by aymericbeaumet** [comment]
Got it, makes sense.

For Googlers reaching this issue, the equivalent of [the `server.decorate` example](http://hapijs.com/api#serverdecoratetype-property-method) in the documentation can be monkey-patched as:

```javascript
var server = new Hapi.Server();

var property = 'response';
var method = function () {
    return this.response({ status: 'ok' });
};

server._requestor._decorations[property] = method;
```

Same principle goes for `server._decorations` and `server.requestor._decorations`.

**Comment by danielo515** [comment]
> It is currently not possible to override an existing decoration. For example the following code will fail (by design):
> 
> var Hapi = require('hapi');
> var server = new Hapi.Server();
> server.decorate('request', 'foobar', function DBConnection() {});
> server.decorate('request', 'foobar', function DBConnectionMock() {}); // expected override

Sorry, if this is just for testing purposes I don't understand why do you need to decorate the server twice. Why don't just decorate it with the mocked version?

**Comment by aymericbeaumet** [comment]
Because I wanted to require the server code as a whole, and just override the decoration I wanted to mock.
