### ISSUE TITLE
undefined is not a function when trying to use a view engine

### ISSUE THREAD

**Issue by 0x4139** [hapijs/hapi#2706]
```
'use strict';
var Path = require('path');
var Hapi = require('hapi');

var server = new Hapi.Server();
server.views({
    engines: {
        html: require('handlebars')
    },
    path: Path.join(__dirname, 'templates')
});

server.route({
    method: 'GET',
    path: '/',
    handler: function (request, reply) {
        reply('Hello, world!');
    }
});

server.connection({ port: process.env.PORT ||3000 });

server.start(function () {
    console.log('Server running at:', server.info.uri);
});
```
error:
```
server.views({
       ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/vali/dev/jeeves-cm/index.js:6:8)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Function.Module.runMain (module.js:469:10)
    at startup (node.js:124:18)
    at node.js:882:3
```

**Comment by mtharrison** [comment]
Hi! It looks like you're using hapi 9 where view rendering is now enabled by an optional plugin (vision). To use `server.views`, `reply.view` and friends you need to register it: https://github.com/hapijs/vision

See release notes for hapi 9 for other changes here: https://github.com/hapijs/hapi/issues/2682

**Comment by 0x4139** [comment]
shouldn't that reflect on the docs?

**Comment by mtharrison** [comment]
Yes they're being worked on now. This example from the docs has been updated but looks incorrect:

```javascript
var Hapi = require('hapi');
var Inert = require('inert');
var server = new Hapi.Server();
server.register(Inert);
server.connection({ port: 80 });
server.views({
    engines: {
        html: require('handlebars')
    }
});

server.ext('onPreResponse', function (request, reply) {

    var response = request.response;
    if (!response.isBoom) {
        return reply.continue();
    }

    // Replace error with friendly HTML

      var error = response;
      var ctx = {
          message: (error.output.statusCode === 404 ? 'page not found' : 'something went wrong')
      };

      return reply.view('error', ctx);
});
```

It's loading Inert rather than vision. @0x4139 would you like to make a PR?

**Comment by 0x4139** [comment]
sure thing will do

**Comment by hueniverse** [comment]
It's not a documentation issue here...

**Comment by jayrore** [comment]
i just started to use this framework and following the documentation i found this problem to so this is my code and how i did untill now i hope it help you guys and comment to a better approach.

// Require dependencies
var Hapi = require('hapi');
var Good = require('good');
var Path = require('path');
var inert = require('inert');

/*
	Setup server
 */
var server = new Hapi.Server();
server.connection({port: 3000});

/*
	Setup routes
 */
server.route({
	method: 'GET',
	path:'/',
	handler: function(request, reply){
		reply.view('index');
	},
    config: {
    	description: 'index page',
    	notes: 'This is all the afluence is going to come',
        tags: ['hello', 'greeting']
    }
});

server.route({
	method: 'GET',
	path: '/hello/{user?}',
	handler: function(request, reply){
		var user =  request.params.user ? 
			encodeURIComponent(request.params.user) : 'stranger'; 
		reply('Hello, ' + user+ '!');
	}
});

server.route({
	method: 'GET',
	path: '/hello/{user*2}',
	handler: function(request, reply){
		var user =  request.params.user ? 
			encodeURIComponent(request.params.user) : 'stranger'; 
		reply('Hello,!');
	}
});

server.route({
	method:['PUT', 'POST'],
	path: '/',
	handler: function(request, reply){
		reply('i did something!');
	}
});

//	handler method 
server.route({
	method: 'POST',
	path: '/create',
	handler: function(request, reply){
		reply('i created!!').code(201);
	}
});

//	Config

server.route({
	method: 'GET',
	path: '/config/{user?}',
	handler: function (request, reply) {
        var user = request.params.user ? encodeURIComponent(request.params.user) : 'stranger';
        reply('Hello ' + user + '!');
    },
    config: {
    	description: 'Say hello!',
    	notes: 'The user parameter defaults to \'stranger\' if unspecified',
        tags: ['api', 'greeting']
    }
});



/*
	Register plug ins
 */ 
server.register([
	{
		register: Good,
		options: {
			reporters: [{
				reporter: require('good-console'),
				events:{
					response: '*',
					log: '*'
				}
			}]
		} 
	},
	{
		register: require('vision')
	},
	{
		register: inert
	}
], function (err) {
    if (err) {
        throw err; // something bad happened loading the plugin
    }

    server.start(function () {
        server.log('info', 'Server running at: ' + server.info.uri);
    });
});

server.views({
    engines: { jade: require('jade') },
    path: __dirname + '/templates',
    compileOptions: {
        pretty: true
    }
});

//	Static file
server.route({
    method: 'GET',
    path: '/static',
    handler: function(req, res){

    	res.file(__dirname+'/media/picture.jpeg');
    }
});

**Comment by Marsup** [comment]
That was just luck, if one of the plugins decides it needs to do something async, that solution won't work anymore, it should be in the callback. Or better yet, in a plugin that depends on vision/inert.

**Comment by jayrore** [comment]
I create a new module(plugin) and register to server after the dependencies inert and vision, 
i tried to register them on the same plugin but an error ocurred
```javascript
// Require dependencies
var Hapi = require('hapi');
var Good = require('good');
var Path = require('path');
/*
 Setup server
 */
var server = new Hapi.Server();
server.connection({port: 3000});
/*
 Register plug ins
 */
server.register([
    {
        register: Good,
        options: {
            reporters: [{
                reporter: require('good-console'),
                events:{
                    response: '*',
                    log: '*'
                }
            }]
        }
    },
    require('inert'),
    require('vision'),
    require('./myRoutes')
], function (err) {
    if (err) {
        throw err; // something bad happened loading the plugin
    }
    server.start(function () {
        server.log('info', 'Server running at: ' + server.info.uri);
    });
});
```

```javascript
exports.register = function(server, options, next) {

    /*
        Setup template engine
     */
    server.views({
        engines: {
            jade: require('jade')
        },
        path: __dirname + '/templates',
        compileOptions: {
            pretty: true
        }
    });

    /*
     Setup routes
    */
    server.route({
        method: 'GET',
        path: '/',
        handler: function(request, reply) {
            reply.view('index');
        },
        config: {
            description: 'index page',
            notes: 'This is index',
            tags: ['index', 'greeting']
        }
    });

    server.route({
        method: 'POST',
        path: '/create',
        handler: function(request, reply) {
            reply('its created!!').code(201);
        }
    });
    //    Static file
    server.route({
        method: 'GET',
        path: '/static',
        handler: function(req, res) {
            res.file(__dirname + '/media/picture.jpeg');
        },
        config: {
            cache: {
                expiresIn: 30 * 1000,
                privacy: 'private'
            }
        }
    });
    next();
};

exports.register.attributes = {
    name: 'myPlugin',
    version: '1.0.0'
};

```
