### ISSUE TITLE
serving static content

### ISSUE THREAD

**Issue by 0x4139** [hapijs/hapi#2707]
```
{
    method: 'GET',
    path: '/public/{param*}',
    handler: {
        directory: {
            path: Path.normalize(__dirname + '/public')
        }
    }
  }
```
I am not able to find a proper example to serve static content

**Comment by jzorn** [comment]
What about http://hapijs.com/tutorials/serving-files?

**Comment by 0x4139** [comment]
reply.file does not exist anymore it seems

**Comment by kanongil** [comment]
Those examples have not been updated to hapi 9.x.

You can find a working example here: https://github.com/hapijs/inert#static-file-server
