### ISSUE TITLE
Add ability to inject bind object to route handlers

### ISSUE THREAD

**Issue by grabbou** [hapijs/hapi#2708]
Hey,
In my case, my route handler has `this.db.User.findOne` as I wrapped Mongoose in a local plugin to bind and ideally mock it easily. Unfortunately, it seems impossible at this point to write something like this:
```
server.inject({
   method: 'GET',
   url: '/users/me',
   bind: {
     db: {User: {findOne: fakeUserHandler}}}
   }
});
```
If this is a no-go for you, do you have any other alternative ways of testing route handlers when an app relays on some plugins? I am using them quite extensively as I thought that it's going to be easier to mock `server.bind` than mess around with `import User from '../db'`

PS. In my test suite, when I create a test server (my `app` is a plugin as well and everything is Glue driven), I am already mocking plugins with a simple `mockPlugin(server, pluginName)` function that just registers empty plugin with {} interface and given pluginName). It's possible to pass fake interface there, but I'd like to manipulate the behaviour of e.g. `findOne` on per test case basis in order to test different behaviour (e.g user does not exist)

**Comment by grabbou** [comment]
The only solution that comes to my mind which is not that ideal is to define in-memory database with e.g. one user and then, manipulate payload with inject to test different behaviours instead of manipulating the findOne method by itself.

**Comment by mtharrison** [comment]
I think you're trying to solve this in the wrong place. `server.inject` is just for pushing a fake HTTP request through node, it doesn't care about what happens inside your application to get the response.

**Comment by grabbou** [comment]
Hm, you are right. But then - it feels like there should be a way to do exactly equivalent of `inject` for a handler (which might be too complex). For a time being, I think I'm going to go with something like this:
```js
const users = {
    "grabbou@gmail.com": {
        ...
    }
}
export default {
   findOne: (query, cb) {
     cb(null, users[query.emai]);
   }
}
```

**Comment by mtharrison** [comment]
Could you not just change what you bind with server.bind depending on test environment or not?

**Comment by grabbou** [comment]
Hm, if I bind an object from external file, then it might be possible to mock it.

**Comment by grabbou** [comment]
Ok, thank you @mtharrison for your help, I think I have the solution now! The issue can be closed :)

**Comment by mtharrison** [comment]
No worries.
