### ISSUE TITLE
update peer dependencies to hapi 9 on hapi-dependent projects

### ISSUE THREAD

**Issue by k-sheth** [hapijs/hapi#2710]
There are a number of projects under the hapijs organisation that have peerDependencies 
"peerDependencies": {
    "hapi": ">=8.x.x"
  },
When I upgrade to hapi 9, and reinstall all my dependencies I get the following error
npm ERR! peerinvalid The package hapi does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer hapi-auth-basic@3.0.0 wants hapi@>=8.x.x

I know hapi-auth-basic has this error, presumably others do too. Pls update and publish the dependent projects.

I am using 
node v0.12.7
npm  v2.11.3

Thanks

**Comment by devinivy** [comment]
`>=8.x.x` is satisfying the peer dependency.  Most likely there's another peer dependency that conflicts with hapi-auth-basic.  Do you have more `npm ERR` lines?

**Comment by k-sheth** [comment]
npm WARN prefer global jshint@2.8.0 should be installed with -g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\dev\\nodejs\\0.12\\\\node.exe" "C:\\dev\\nodejs\\0.12\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package hapi does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer hapi-auth-basic@3.0.0 wants hapi@>=8.x.x
npm ERR! peerinvalid Peer hapi-require-https@2.0.0 wants hapi@8
npm ERR! peerinvalid Peer inject-then@2.0.0 wants hapi@^8.0.0

**Comment by hueniverse** [comment]
It's the last two plugins. You need to contact their authors.
