### ISSUE TITLE
Ability to add callback to `failAction` not reflected in docs

### ISSUE THREAD

**Issue by camerow** [hapijs/hapi#2711]
This may be on purpose - I'm really just learning about Hapi and am a new developer in general. However I noticed that the API does not mention that `failAction` can take a callback on an invalid Joi object. Here's a quick snippet of what I'm talking about:

```
let routes = [{
  path: "/setup/{token}",
  method: "GET",
  config: {
    validate: {
      params: {
        token: Joi.string().guid()
      },
      failAction: (request, reply, source, error) => {
        let context = {};
        context.error = "Token invalid.";
        let element = React.createElement(ErrorPage, context);
        let markup = React.renderToString(element);
        reply.view("index", { markup: markup, context: JSON.stringify(context) });
      }
    }
  },
handler: ...
```

The docs only mention that `failAction` takes `"error"`, `"log"`, and `"ignore"`. 

Sorry if this is a lack of knowledge on my part. If so I would love to be informed on where my understanding is lacking.

Thanks! 

-Will

**Comment by hueniverse** [comment]
You are correct. I'll take a PR fixing the docs.

**Comment by camerow** [comment]
Cool. I'll create that asap.
