### ISSUE TITLE
Server closes immediately using Hapi 9.0.1

### ISSUE THREAD

**Issue by nelsonic** [hapijs/hapi#2715]
Hi! The following simple (hello world) hapi server code *used* to work in Hapi 8.x but *not* in **9.0.1**

```js
var Hapi   = require('hapi');
var server = new Hapi.Server();

server.connection({
    host: '0.0.0.0',
    port: 3000
});

server.route({
	method: 'GET',
	path: '/{p*}',
	handler: function(req, reply){
		return reply('Hello ' + req.params.p)
	}
})

server.start(function(){
  console.log('Now Visit: http://localhost:3000/YOURNAME')
});
```
But now sadly, runs but closes *immediately*. 
We have read the release notes for **9.0.0** but not found what we need to do to get this working.
Can someone point me in the right direction? *thanks*

**Comment by gergoerdosi** [comment]
Use 9.0.1. 9.0.0 had an issue with the wreck module which causes your code to fail:

module.js:338
    throw err;
          ^
Error: Cannot find module 'wreck'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/node_modules/subtext/lib/index.js:14:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by nelsonic** [comment]
@gergoerdosi we *are* using **Hapi v9.0.1** and the code above does not invoke `wreck`.

**Comment by lloydbenson** [comment]
Works for me just fine.  Maybe you can provide more details about what OS you are on, what node version, etc?

**Comment by nelsonic** [comment]
@lloydbenson just updated node to V0.12.7 and re-tried. works. 
thanks for taking the time to help investigate. closing. :+1:
