### ISSUE TITLE
Local sources cannot be found with static page setup 9.x

### ISSUE THREAD

**Issue by LukeDowell** [hapijs/hapi#2716]
I've been trying to convert an old express project to work with Hapi. A friend and I have looked through a lot of the available documentation and it seems like everything is broken/outdated. I want to serve a static  html page that links to local resources.

Here is my route: 
```
//Catch-all route
server.route({
    method: 'GET',
    path: '/{param*}',
    handler: {
        directory: {
            path: "assets/views",
            index: true
        }
    }
});
```

My server is set up to use public/ as a relativeTo option:
```
//Creates a hapi server
var server = new hapi.Server({
    connections: {
        routes: {
            files: {
                //All future pathing will be relative to this url
                relativeTo: path.join(__dirname, "public")
            }
        }
    }
});
```

And my assets/libaries are under assets/ and vendors/ respectively, which are direct children of the public/ folder. 

Here is a picture of my folder structure and how I'm sourcing my files inside of Index.html. 
<img src="http://puu.sh/jCSW9/e593f150d9.png">
I'm only posting this issue because we have cruised through a LOT of Hapi documentation today, and it seems odd that successfully serving a static resource is so difficult. Is there an issue with the new release, or are we just completely missing something?

**Comment by LukeDowell** [comment]
I fixed my problem. I didn't realize that you had to manually write your own source handler stuff. Here is the code I used to fix my problem: 

```
//Assets
server.route({
    method: 'GET',
    path: '/assets/{param*}',
    handler: function(request, reply) {
        console.log(request.params.param);
        reply.file('assets/' + request.params.param);
    }
});

//Vendor
server.route({
    method: 'GET',
    path: '/vendors/{param*}',
    handler: function(request, reply) {
        console.log(request.params.param);
        reply.file("vendors/" + request.params.param);
    }
});
```

**Comment by hueniverse** [comment]
The problem is probably with your `relativeTo` settings. Did you try to console log it to make sure you are pointing at the right place? `__dirname` is relative to the current source file. Is it at the same place `./public` is?
