### ISSUE TITLE
After upgrading to newer version throwing error for every handler - Unknown handler

### ISSUE THREAD

**Issue by nagendertank** [hapijs/hapi#2719]
<img width="869" alt="screen shot 2015-08-16 at 15 29 54" src="https://cloud.githubusercontent.com/assets/12261617/9292850/db3e2c40-442b-11e5-8288-36f244bfbea5.png">

**Comment by gergoerdosi** [comment]
See the release notes: https://github.com/hapijs/hapi/issues/2682. The inert plugin has been removed from hapi, you need to register it manually.

**Comment by nagendertank** [comment]
Thanks, Now its working.
