### ISSUE TITLE
Decorations not propagated to sibling plugins

### ISSUE THREAD

**Issue by Marsup** [hapijs/hapi#2727]
Credits go to @jedireza for finding this one.

Registration order has an impact on decorations access, regardless of the use of `server.dependency`.
For exemple calling `server.views` with `[Vision, Lout]` will work, `[Lout, Vision]` won't : `TypeError: Object [object Object] has no method 'views'`.

Decorations are only copied on the initialization of the plugins, so while the server.root is always aware of those decorations, [this line](https://github.com/hapijs/hapi/blob/1a541472da4b00bb72f528916b6b339b3ffc402d/lib/plugin.js#L321) will not be propagate the decorators to others.

It seems I have 2 choices here :
- always use `server.root.*`
- fix it in hapi, by copying again (maybe [here](https://github.com/hapijs/hapi/blob/1a541472da4b00bb72f528916b6b339b3ffc402d/lib/server.js#L313)) all the decorations from the root

Willing to make a PR if that's the 2nd case.

**Comment by hueniverse** [comment]
Why is this not an issue of lout needing to wait for vision to load? You are seeing it now because vision is not built in anymore but this isn't new. Before it was still the same problem. You need to wait for after event when vision is loaded.

I am not saying that's the only issue here but that it's not just a matter of supporting random order.

**Comment by Marsup** [comment]
[I am](https://github.com/hapijs/lout/blob/7a0597dd53f7ba2f4bc7269538faf2166f12bdfb/lib/index.js#L61). New Plugin instances are provided to each register, they don't share the same `this` (though they do share the same `root`).

**Comment by Marsup** [comment]
To be even more explicit, I think we should have a similar loop as [this one](https://github.com/hapijs/hapi/blob/1a541472da4b00bb72f528916b6b339b3ffc402d/lib/plugin.js#L84-L88) before calling the dependency callback.

**Comment by Marsup** [comment]
@hueniverse do you want a PR doing what I suggested in OP ?

**Comment by hueniverse** [comment]
Nah. I need to do a deeper fix.

**Comment by Marsup** [comment]
Wow, that was simpler than I expected :)

**Comment by devinivy** [comment]
That commit is sort of delightful.

**Comment by hueniverse** [comment]
There are some dark corner of this code base :-)
