### ISSUE TITLE
Access-Control-Request-Headers gone?

### ISSUE THREAD

**Issue by Icehunter** [hapijs/hapi#2728]
Just out of curiosity; I swear 2 days ago I was able to do:

```javascript
var headers = request.headers['access-control-request-headers'];
```

In that I got the headers that came from the request it self but flattened out into a string with the correct original capitalization.

The reason I ask was I had an all-purpose route setup to respond with accepts on all headers like so:

```javascript
    server.route({
        method: 'OPTIONS',
        path: '/{param*}',
        handler: function (request, reply) {
            // echo request headers back to caller (allow any requested)
            var additionalHeaders = [];
            if (request.headers['access-control-request-headers']) {
                additionalHeaders = request.headers['access-control-request-headers'].split(', ');
            }
            var headers = _.union('Authorization, Content-Type, If-None-Match'.split(', '), additionalHeaders);
            reply().type('text/plain')
                .header('Access-Control-Allow-Origin', '*')
                .header('Access-Control-Allow-Headers', headers.join(', '));
        }
    });
```

I was using 9.x.x but for some reason I can't get this in the values anymore. Is there a server setting which adds it that I might have removed?

Thanks!

**Comment by Icehunter** [comment]
As a added note I did just find them in request.raw.req.rawHeaders with the proper caps and in an array. Should I just be reading them from there instead?

The following NPM module though assumes they will be in request.headers:

https://github.com/gr2m/hapi-cors-headers/blob/master/index.js#L21

**Comment by hueniverse** [comment]
Did you change node version? hapi is only supported on 0.10.x. There has not been any change to headers. In fact, hapi doesn't touch the headers at all (it's a direct reference to the raw request headers). Capitalization usually means something in node.

**Comment by Icehunter** [comment]
I'm using 12.7 because we use private npm modules on npmjs.com. Is there planned support for it? I haven't noticed any issues around hapi, bell and all the other plugins yet. Is there a planned support path for it?

Thanks for all the hard work!

**Comment by arb** [comment]
You can update `npm` globally independent of the Node version as well. I know 2.x.x of npm still works with Node 0.10.x. The 2.x.x version is where private npm module compatibility was introduced.

**Comment by hueniverse** [comment]
0.12 will never be supported.

**Comment by Icehunter** [comment]
I assume version 4 then would be when the merge happens or will it only ever support 0.10.x? @arb I'll try that however all our stuff was written around 12.x now (pending the merge from io.js) that is.

**Comment by hueniverse** [comment]
Yes, v4 or whatever version is the next stable one. 0.12 is really a bad idea.

**Comment by Icehunter** [comment]
Fair enough; I'll work through that then. As a note to this though, I downgraded to 0.10.4 but that header key isn't present. I'll work around that (maybe even in 12) and just read it from the raw headers instead. Back to me working on porting over oauth2orize into hapi.

**Comment by hueniverse** [comment]
If this is still an issue with 0.10, we need to understand what is going on here. Node is supposed to force all incoming headers to lowercase in `req.headers`. Is this not what you expect?

**Comment by Icehunter** [comment]
Oh! Sorry for the miscommunication. They are all lowercase, however the header "access-control-request-headers" is not present anymore. Previously according to that NPM I linked I was using that to echo back the headers with the original capitalization that came from the raw headers.

So when I would console.log(request.headers); I would have them all there, include that extra one with the original casing, separated by commas.

**Comment by Icehunter** [comment]
Maybe it was just the client sending them instead; not quite sure.

**Comment by hueniverse** [comment]
If you can reproduce this, let me know. Otherwise, hapi doesn't touch the headers. They are exactly what was received from node `req.headers`. You might have something that is deleting that header somewhere...
