### ISSUE TITLE
reply.file - TypeError: Uncaught error: undefined is not a function

### ISSUE THREAD

**Issue by jonathanKingston** [hapijs/hapi#2729]
When using:
```
  handler: function (request, reply) {
    reply.file('index.html');
  }
```

As suggested here: http://hapijs.com/tutorials/serving-files

I get:
```
    TypeError: Uncaught error: undefined is not a function
    at server.route.handler ...
```

Seems related to other changes of code like: https://github.com/hapijs/hapi/issues/2706

**Comment by jonathanKingston** [comment]
Adding in https://github.com/hapijs/inert fixed this. Is this now a requirement?

If so the issue here is just documentation.

**Comment by hueniverse** [comment]
The tutorials are not up to date for version 9.x. This change is clearly documented in the 9.x release notes.

**Comment by jonathanKingston** [comment]
@hueniverse can I suggest the docs have a warning pointing that out then? It seems pretty bad user experience to come to a new library and expect them to read the release notes before the tutorials.

**Comment by hueniverse** [comment]
It's a large community project with different parts maintained by different people. Some are on vacation. Tutorials should have the version number on them (open issue) but it's a new release and it takes time. It's all open source by volunteers.

**Comment by MattiSG** [comment]
+1

**Comment by ohabash** [comment]
How can I learn hapi if the docs wont even work for me.

**Comment by WesTyler** [comment]
The docs on the repo are kept up to date. It is extra tutorials that take time for volunteers to update in their free time.
