### ISSUE TITLE
Version >= 9.0 documentation missing proxy route handler

### ISSUE THREAD

**Issue by dj** [hapijs/hapi#2734]
It seems like in newer versions of Hapi, the references to the proxy options to route handlers have been removed (in almost all places, other parts of the documentation make reference to proxy route handlers but the proxy option under route handlers is missing).

Is the proxy option being deprecated? I wouldn't expect it to be since it seems to be a pretty essential feature of hapi. Sorry if this is the wrong place to raise the issue.

**Comment by nlf** [comment]
the proxy support was always provided by a plugin, that plugin has been removed from core however. see https://github.com/hapijs/h2o2 for the plugin and its documentation.

**Comment by mtharrison** [comment]
h202 is no longer part of core as per 9.0.0 release notes: https://github.com/hapijs/hapi/issues/2682
