### ISSUE TITLE
Stopping the server while starting it

### ISSUE THREAD

**Issue by kanongil** [hapijs/hapi#2736]
I would like to be able to call `server.stop()` even while it is starting. Currently, it will throw when I try to do this, with no practical way of telling before making the actual call.

The use case is simple: I want to install a `SIGINT` handler that gracefully stops the server. If it triggers while starting the server, I would like it to abort the start process, and apply the stop process as usual, before calling the `server.start()` callback with an error.

Note that it should also work if stopped while in the implicit `initializing` state.

**Comment by hueniverse** [comment]
Can't abort the start process fully. Can try in between callbacks.

**Comment by kanongil** [comment]
@hueniverse That was the idea. I guess it would also work if the stop is deferred until the start is completely finished.

**Comment by kanongil** [comment]
Ok, I decided to create an addon to handle my use case, making this request somewhat redundant. See https://github.com/kanongil/exiting if you are interested.

**Comment by hueniverse** [comment]
Changed the assertion to a callback error. While this is a breaking change, it should not cause issues as existing code should already be handling errors on the callback.
