### ISSUE TITLE
Can I tell what the route-specific CORS settings were in a plugin?

### ISSUE THREAD

**Issue by brabster** [hapijs/hapi#2737]
Hi, great lib!

I'm looking into an issue with the Lout plugin https://github.com/hapijs/lout/issues/108 where the global CORS settings appear in the documentation for every route.

I've had a look around the Hapi source, and I think the route-specific settings for CORS are overwritten after being combined with the defaults (route.js around line 154), so there's nowhere a plugin could see what the original route-specific settings were.

If someone who knows this project better than me could confirm my findings I'd appreciate it!

Also, if that is the case, would it be reasonable to ask the project to provide a way of getting the original route-specific settings for CORS for plugins when the setup?

Thanks!

**Comment by hueniverse** [comment]
You are correct and the raw route config are not retained. We could keep a reference to that object, but it would be wrong if anyone was reusing route config and changing the option object between calls to `server.route()`. So not sure it is worth adding. You should be able to get the global config and subtract it from the route specific information.

**Comment by Marsup** [comment]
That's not very complicated to add though, just need to store the old version of the cors somewhere before merging on [this line](https://github.com/hapijs/hapi/blob/5b2212d08eafa85e9c44caccc80bc3630a11a69f/lib/route.js#L155), and it might avoid lout a much more complicated diffing algorithm.

**Comment by hueniverse** [comment]
The question is, is that enough or should we clone the entire options object. I don't want to do this for each little piece.
