### ISSUE TITLE
route handler called multiple times if reply takes too long

### ISSUE THREAD

**Issue by PranavRam** [hapijs/hapi#2738]
Hello,

Here is my workflow:

1) User uploads a zip file
2) The server processes the file and goes about performing more actions (database communication and some Machine Learning tasks) that could take upwards of 3-4 mins
3) the reply function in called when everything is completed

The issue I'm facing is that the handler is called again (no input from the client) if I don't reply right away. Is there a way to prevent this from happening?

Thanks!

**Comment by hueniverse** [comment]
This doesn't make sense. If you take minutes to respond, the request will time out unless you changed the defaults for both hapi and node (socket and server timeouts). Is it possible the client is sending another request because it gets disconnected?

**Comment by PranavRam** [comment]
That must be it. I don't see another request in the debugger console coming in from the Angular web app. I haven't messed with the Hapi defaults and I believe the timeout is disabled by default for the server. Is that correct? Would you have any pointers to configuration options I might need to look into?

Thanks for the help!

**Comment by hueniverse** [comment]
You need to override the node default 2m timeout.

**Comment by PranavRam** [comment]
Awesome, thank you! That worked beautifully.

On the route object:
<code>
config: {
  timeout: {
    socket: false
  }
}
</code>

**Comment by Marsup** [comment]
This is not the correct solution anyway, browsers (and firewalls) have timeouts that the server can't control. You either need websockets, server-sent events or long polling.
