### ISSUE TITLE
Reply.continue is not a function in promise chain

### ISSUE THREAD

**Issue by bsiddiqui** [hapijs/hapi#2740]
I'm trying to add some additional authentication on a particular route using the `onPreHandler` extension.

I'm trying to understand why this doesn't work since `continue` is a function: 
```js
return doSomething()
.then(reply.continue) // undefined is not a function
.catch(reply) 
```
but this works:
```js
return doSomething()
.then(function () {
   reply.continue()
})
.catch(reply)

**Comment by bsiddiqui** [comment]
I was actually able to figure it out. Returning promise changes the context of `this`, which the `continue` function references. 

This, for example, would work:
```js
return doSomething
.bind(reply)
.then(reply.continue)
.catch(reply)
```

**Comment by hueniverse** [comment]
It not that the promise changes the context but that when you pass `reply.continue` as a function reference, you lose the `reply` context.

**Comment by bsiddiqui** [comment]
@hueniverse that's helpful, thanks!
