### ISSUE TITLE
HTTP/2 and hapi

### ISSUE THREAD

**Issue by pkaske** [hapijs/hapi#2742]
If I wanted to used HTTP/2 to serve my web app, could that somehow be accomplished with hapi as of right now?

**Comment by mtharrison** [comment]
These kind of questions are probably better over at https://github.com/hapijs/discuss. I'll try to help though. 

hapi doesn't deal with the protocol, that all happens in node's http module. Provided you can find a drop-in replacement for `http` (can't comment on this as I've never looked), you can set your own listener when creating a hapi server connection:

```javascript
var Hapi = require('hapi');
var Http2 = require('...');

var server = new Hapi.Server();

server.connection({ listener: Http2.createServer() }); 
```

**Comment by pkaske** [comment]
Thank you! Sorry, I didn't know about https://github.com/hapijs/discuss
