### ISSUE TITLE
[Feature Request] Proxy Protocol

### ISSUE THREAD

**Issue by felipegs** [hapijs/hapi#2743]
Sometimes we are behind a loadbalancer, and we need to know de real ip of the client, and the only way to do that is use proxy protocol.

It will be nice if hapijs supports proxy protocol, like this module does https://github.com/findhit/proxywrap

**Comment by hueniverse** [comment]
The right way to do this is in the load balancer, not the server. Either way, you can implement something like this in the onRequest extension point. I have no plans to add support in hapi itself.
