### ISSUE TITLE
request.log(err) show an empty object

### ISSUE THREAD

**Issue by kevinsimper** [hapijs/hapi#2744]
That is because you can't stringify an Error, but Hapi.js does try anyways because `typeof error === 'object'`.

I propose that
- stringifying a console.error is wrong, since it can't show linebreaks, so an `error.stack` looks bad, it should just console.error without JSON.stringify
- it should use `data instanceof Error`

**Comment by kevinsimper** [comment]
Does somebody has a opinion? :)

**Comment by AdriVanHoudt** [comment]
Well console.error would not show up in logging if you use Good for instance, I do `server.log(err.message)`  in some cases, it depends

**Comment by kevinsimper** [comment]
@AdriVanHoudt Thanks for you reply :+1: 

Yes, but the stacktrace would be good to have as well, but the request log purposely stringified it here
https://github.com/hapijs/hapi/blob/master/lib/request.js#L257

**Comment by gergoerdosi** [comment]
> stringifying a console.error is wrong, since it can't show linebreaks

It can, we just need to change `Hoek.stringify(data)` to `Hoek.stringify(data, null, 4)`.

**Comment by kevinsimper** [comment]
@gergoerdosi It is not that json can't be prettified, it is that the Error.stack contains breaks and they will be converted to \n in JSON.stringify

**Comment by gergoerdosi** [comment]
Can you please add a sample code? I'm trying to reproduce the problem, but the stack is displayed correctly for me:

```js
var Hapi = require('hapi');

// Create a server with a host and port
var server = new Hapi.Server({ debug: { request: ['error'] } });
server.connection({
    host: 'localhost',
    port: 8080
});

// Add the route
server.route({
    method: 'GET',
    path:'/hello',
    handler: function (request, reply) {
        request.log(['error'], new Error('test'));
        reply('hello');
    }
});

// Start the server
server.start(function () {
    console.log('Server running at:', server.info.uri);
});
```

This outputs:

```sh
$ node index.js 
Server running at: http://localhost:8080
Debug: error 
    Error: test
    at server.route.handler (/index.js:15:32)
    at Object.internals.handler (/node_modules/hapi/lib/handler.js:93:36)
    at /node_modules/hapi/lib/handler.js:28:23
    at internals.Protect.run (/node_modules/hapi/lib/protect.js:56:5)
    at exports.execute (/node_modules/hapi/lib/handler.js:22:22)
    at /node_modules/hapi/lib/request.js:377:13
    at iterate (/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at done (/node_modules/hapi/node_modules/items/lib/index.js:27:25)
    at /node_modules/hapi/node_modules/hoek/lib/index.js:841:22
    at process._tickDomainCallback (node.js:381:11)
```

**Comment by kevinsimper** [comment]
I did not understand the code properly and how hapi.js works together with good and good-console. I should have mentioned that I used good. There is actually no error.

To help on my shame for creating this issue, I donated 50 danish kroners to red cross to help children in syria.

Thanks for your answers!
![image](https://cloud.githubusercontent.com/assets/1126497/9833738/781fae76-59a3-11e5-815d-bda563b96cd0.png)

**Comment by AdriVanHoudt** [comment]
@gergoerdosi try using Good console and then you will see what he means and yeah true it will convert to \n but there is no other way to log it to let's say a log file otherwise, you can parse it back into multiline on read.

Also no shame! Cool to donate though

**Comment by kevinsimper** [comment]
I dug into it some more, now that i knew it was handle more by `good` and it is actually fairly complicated because each reporter decide themselves how they show the output. That means that the if you fix so that `good-console` [shows an error with `error.stack`](https://github.com/hapijs/good-console/blob/master/lib/index.js#L80-L84), and you are also using `good-file` and `good-loggly`, you also have to fix it in those.

I thought it was the same output, but it is not. I wanted to just log my javascript errors, but it seems not that easy.

**Comment by AdriVanHoudt** [comment]
Good-console will do that for you, but as @gergoerdosi showed just doing the log, hapi will print it out for you nicely, or you can make your fork of good-console that does as you described in your original post with the console.error thing

**Comment by gergoerdosi** [comment]
Changing `SafeStringify(data.data)` to `SafeStringify(data.data, Object.getOwnPropertyNames(data.data))` should do the trick in good-console. However json-stringify-safe raises an error with this code. I created an issue:

https://github.com/isaacs/json-stringify-safe/issues/14

If this gets fixed in json-stringify-safe, we can look into changing the code in good-console to support Error.

**Comment by AdriVanHoudt** [comment]
@gergoerdosi what does passing the property names do? (not familiar with safestringify)

**Comment by gergoerdosi** [comment]
@AdriVanHoudt Properties in Error objects are non-emurable, that's why Error objects can't be stringified. Whitelisting the property names is a little trick that makes `JSON.stringify()` to select those properties.

```
> var error = new Error('test')
undefined
> JSON.stringify(error)
'{}'
> JSON.stringify(error, Object.getOwnPropertyNames(error))
'{"stack":"Error: test\\n    at repl:1:13\\n    at REPLServer.defaultEval (repl.js:132:27)\\n    at bound (domain.js:254:14)\\n    at REPLServer.runBound [as eval] (domain.js:267:12)\\n    at REPLServer.<anonymous> (repl.js:279:12)\\n    at REPLServer.emit (events.js:107:17)\\n    at REPLServer.Interface._onLine (readline.js:214:10)\\n    at REPLServer.Interface._line (readline.js:553:8)\\n    at REPLServer.Interface._ttyWrite (readline.js:830:14)\\n    at ReadStream.onkeypress (readline.js:109:10)","message":"test"}'
```

Not sure this is the best way to solve this problem, but it's one.

**Comment by AdriVanHoudt** [comment]
I see, is it perf?

**Comment by gergoerdosi** [comment]
Not really. I just did a test now, `JSON.stringify()` with `Object.getOwnPropertyNames(error)` is 93% slower than without it. Well, we could then move stringification to an internal function and check for `data.data instanceof Error` as suggested by @kevinsimper.

Anyway, this is not a hapi issue. @kevinsimper: Open an issue in good-console if you want and we can continue the discussion there.

**Comment by kevinsimper** [comment]
The problem is not only with `good-console`, it applies to every `good-` reporter, so `good-file`, `good-loggly` etc.

But the problem is not either in `good`, because all that library does is being an enabler for all the reporters.

I solved it anyways in a hacky way, where i change the Error prototype to be enumerable.
```
Object.defineProperty(Error.prototype, 'stack', {
  configurable: true,
  enumerable: true
})
```
and then not using good-console for the request.log, but using the built in
```
if(process.env.NODE_ENV === 'development') {
  serverOptions.debug = {
    request: ['error', 'mongo']
  }
}
var server = new Hapi.Server(serverOptions)
```

**Comment by DamodarSojka** [comment]
So is changing Error object the way to solve that problem? Is there a better way?
I had an intuition that good was meant to help with logging. 
Please correct me if I am missing something.
