### ISSUE TITLE
"failAction" does not accept custom error function as stated in the documentation

### ISSUE THREAD

**Issue by maddin77** [hapijs/hapi#2746]
According to [Route options](http://hapijs.com/api#route-options) in the documentation, `payload.failAction`, `response.failAction`, `state.failAction`, `validate.failAction` and `pre.failAction` all accept a custom error handler function besides predefined string values.

However, as defined in [schema.js](https://github.com/hapijs/hapi/blob/master/lib/schema.js), `validate.failAction` is the only one that actually accepts a function as a valid value. Therefore trying to use a custom function as `failAction` for any of the others will throw
```
[1] "failAction" must be a string
```
on startup.

There's #2741 to remove the part of the documentation for the request prerequisites, so i'm wondering if it's supposed to be like in the documentation, or as defined in the schema.

**Comment by hueniverse** [comment]
As you can tell from #2741 being merged, it's not supported.
