### ISSUE TITLE
Is there a limit for concurrent requests

### ISSUE THREAD

**Issue by KeKs0r** [hapijs/hapi#2747]
Hi,

I am currently load testing my Hapi backend and I have an endpoint, that only authenticates user (via Redis) and then executes a query against the Database.

My new relic trace indicates that half of the time is spent in Hapi:
![image](https://cloud.githubusercontent.com/assets/2970814/9579118/46876532-4ff0-11e5-9a6f-fa4c07e0b3da.png)

The thing is that no real logic is executed except for the database query. And it appears that Hapi only consumes time on higher loads.

Is there a limit to concurrent requests in Hapi that might queue the request and would explain the delay?
I know that node had a limit in connections in older versions, but I am running node 12.7 and there it is set to Infinity by default.

Any ideas what else could take some time in Hapi?

**Comment by hueniverse** [comment]
First, node 0.12 is not supported. Second, it would be really hard to figure this out with the information provided. I don't know anything about what new relic does and how it is measuring thing. I suggest you put some timers throughout the request lifecycle and get a better idea of where time is spent.

**Comment by bboysathish** [comment]
@hueniverse  may i know what do you mean by node 0.12 is not supported. Does that mean Hapi.js is recommended only for 0.10 ?

**Comment by KeKs0r** [comment]
Okay thanks.

I thought there might be an internal configuration in Hapi or something. If
that is not the case I am pretty sure, Hapi itself is not causing the
delay, the bottleneck will probably be somewhere else.
Thanks for the feedback.

**Comment by hueniverse** [comment]
@bboysathish we only test hapi on 0.10. People reported issues with 0.12 in the past and I don't know what's the status of it right now. I recommend using 0.10 in production until the next version of node (4.0?) will be stable enough. You are free to try it with any version but just know that the project is not being tested on those platforms.
