### ISSUE TITLE
Error: reply interface called twice when called from onPostHandler extension point

### ISSUE THREAD

**Issue by Wenzil** [hapijs/hapi#2749]
Hello,

I'm having an issue with modifying a response from an 'onPostHandler' extension point. According to the documentation,
> **'onPostHandler' extension point**
> - The response object contained in request.response may be modified (but not assigned a new value). To return a different response type (for example, replace an error with an HTML response), return a new response via reply(response).

I gather that it is supported to call `reply(response)` again, from an `onPostHandler` extension point to alter the response being sent. However when I do this, i get the following error:

```
Error: reply interface called twice
```

Is this a known bug?

**Comment by hueniverse** [comment]
I need to see your actual code. This error means you are calling `reply()` twice which happens when your logic is broken. For example:

```js
function (request, reply) {
    if (a === 1) {
        reply('ok');
    }

    reply('bad');
}
```

This will throw the error you got.

**Comment by Wenzil** [comment]
I think you're right, after some restructuring I don't get the error anymore. I should have tried with a more trivial example first.

Thanks!
