### ISSUE TITLE
Add connections inside a plugin

### ISSUE THREAD

**Issue by duro** [hapijs/hapi#2754]
I have a plugin that gets registered via a manifest (Glue). I am wondering if it can define it's own connection via the server object it is passed? Or can connections only be created by the main Server instance, and accessed via a label in the plugin?

**Comment by hueniverse** [comment]
It's a bit delicate. It can using `server.root.connection()` but that connection is not going to show up within the plugin own `server.connections`. Handle with care.

**Comment by duro** [comment]
@hueniverse: so then the recommended approach is to setup connections at the highest level of the Server. These does seem to fly in the face of Hapi's modular approach where everything is a plugin. Because now I have a parent that is defining things that the plug-ins have to assume will be present. Makes moving a plugin from one server to another require that the new server implement the plug-ins connection.

No big deal for my app, but seems like a chink in the foundation that Hapi establishes.

**Comment by hueniverse** [comment]
The contract is that `server.connections` doesn't change once you enter the `register()` plugin method. This creates the limitation that when a plugin calls `server.root.connection()`, that connection is not directly available to it. You could make it available to a sub-plugin of that by calling `server.root.select()` to get the connection you just added and then `server.register()` on the returned selection.

The current API protects you from unexpected changes in the environment such as a new connection showing up during the registration process. By forcing you to use `server.root`, it is making it clear that you are basically stepping outside of the current plugin realm.

**Comment by hueniverse** [comment]
Now with the introduction of connectionless plugins, you have a new pattern that is safer to use. You create a plugin with `attributes.connections` set to `false` and inside called `server.root.connection()`. The `connection()` method will return a new `server` object you can use from that point on instead of the `server` object passed to the `register()` method.
