### ISSUE TITLE
Missing server decoration in after callback

### ISSUE THREAD

**Issue by thebinarypenguin** [hapijs/hapi#2759]
First I'm not sure if this is a vision issue or a core issue. I started with hapijs/vision#52 which led me to hapijs/hapi#2727 and even though the latter is closed I'm still experiencing this problem.

My code

server.js
```js
var Hapi  = require('hapi');
var Views = require('./views.js');

var server = new Hapi.Server();

server.connection({ port: 3000 });

server.register([Views], function(err) {
  if (err) { throw err; }

  server.route({
    method: 'GET',
    path: '/',
    handler: function(request, reply) {
      reply.view('test', { message: 'Hello' });
    }
  });

  server.start(function() {
    console.log('Server running at:', server.info.uri);
  });
});
```

views.js
```js
var Handlebars = require('handlebars');
var Vision     = require('vision');

exports.register = function(server, options, next) {

  server.register([Vision], function(err) {
    if (err) { throw err; }

    server.views({
      engines: {
        html: Handlebars
      },
      path: __dirname + '/templates'
    });

    next();
  });
};

exports.register.attributes = {
  name: 'views',
  version: '0.0.0'
};
```

My Error

```
/home/ethan/incubator/hapi-vision-bug/views.js:9
    server.views({
           ^
TypeError: Object [object Object] has no method 'views'
```

**Comment by Marsup** [comment]
Which version of hapi are you using ?

**Comment by thebinarypenguin** [comment]
Hapi: 9.3.0
Vision: 3.0.0

**Comment by Marsup** [comment]
It's a bit unusual that plugins register others, they usually depend upon each other.

**Comment by thebinarypenguin** [comment]
Yeah, I wasn't sure about that. It seems strange to me that a plugin wouldn't  "load" its specific dependencies. Isn't that one of the ideas behind plugins/modules, to hide complexity by encapsulating the implementation details?

**Comment by Marsup** [comment]
I'll let @hueniverse decide on whether it should be a supported use case but in the mean time if you really want to do it this way you'll have to write it like that :
```js
server.register([Vision]);
server.dependency(['vision'], function(server, next) {
 if (err) {
   throw err;
 }

 server.views({
   engines: {
     html: Handlebars
   },
   path: __dirname + '/templates'
 });

 next();
});

next();
```

**Comment by devinivy** [comment]
@thebinarypenguin most plugins are designed to be loaded once.  So if there are multiple plugins with the same dependency, you'd quickly run into issues with that pattern.  Registering vision above your views.js plugin will allow other plugins, such as hapi-swagger, to safely use vision no matter where the plugin is registered.

That said, I do personally agree that the decorators should be able to be used in `after` callbacks.

**Comment by thebinarypenguin** [comment]
Well I switched to using dependency() but I still have a problem. Now the process return and I have no output (I probably did something dumb).

server.js
```js
var Hapi  = require('hapi');
var Vision = require('vision');
var Views = require('./views.js');

var server = new Hapi.Server();

server.connection({ port: 3000 });

server.register([Vision, Views], function(err) {
  if (err) { throw err; }

  server.route({
    method: 'GET',
    path: '/',
    handler: function(request, reply) {
      reply.view('test', { message: 'Hello' });
    }
  });

  server.start(function() {
    console.log('Server running at:', server.info.uri);
  });
});
```

views.js
```js
var Handlebars = require('handlebars');

exports.register = function(server, options, next) {

  server.dependency(['vision'], function(server, next) {

    server.views({
      engines: {
        html: Handlebars
      },
      path: __dirname + '/templates'
    });

    next();
  });
};

exports.register.attributes = {
  name: 'views',
  version: '0.0.0'
};
```

**Comment by Marsup** [comment]
Forgot to call the 1st next in the views register.

**Comment by thebinarypenguin** [comment]
Ah of course. Well my issue is solved. Shall I leave this open in case anyone wants to comment on the "register within a plugin" use case?

**Comment by Marsup** [comment]
Nah, no doubt Eran will see it an re-open if need be :)

**Comment by devinivy** [comment]
@hueniverse does https://github.com/hapijs/hapi/commit/a4247390ae2291cc8f1a26ffd784133774353654 have any effect on this issue?

**Comment by hueniverse** [comment]
Yes. Should resolve it. Also, this really needs conditional registration which I already planning on adding so that any plugin that needs vision can register it if not available.
