### ISSUE TITLE
get cache stats for a server method?

### ISSUE THREAD

**Issue by jgallen23** [hapijs/hapi#2763]
It looks like catbox stores [stats](https://github.com/hapijs/catbox#api-1) for gets/sets/hits/stales/etc.  Is there any way to access this for a server method?  From the looks of it, drop is the only thing exposed to the server method.

**Comment by hueniverse** [comment]
I'll take a PR

**Comment by toboid** [comment]
I'd be really pleased to take a look at implementing this if it's up for grabs?

**Comment by jgallen23** [comment]
@toboid go ahead. I wouldn't have time for a few weeks anyways.

**Comment by toboid** [comment]
Thanks @jgallen23. I've submitted a PR
