### ISSUE TITLE
hapi-tedious

### ISSUE THREAD

**Issue by yosiasz** [hapijs/hapi#2767]
Greetings all,

I am a newbie, I have done my due diligence (I think) reading documentation, trial and error, tears and sweat.

Creating my own little plugin to tie hapi with tedious. After having created hapi-tedious I make the call as follows

server.register({
    register: require('hapi-tedious'),
    options: dbOpts
}, function (err) {
    if (err) {
        console.error(err);
        throw err;
    }
}); 

But when making call to the plugin as 
var tediousRequest = request.server.plugins['hapi-tedious'].tediousRequest;

I get error
Cannot read property 'tediousRequest' of undefine

Calling console.log(request.server.plugins); for test purposes shows me {}

I thought I had registered my plugin successfully but it seems not. What am I missing here?

Thanks!

**Comment by gergoerdosi** [comment]
Your plugin needs to expose something to be available under `server.plugins`. For example:

```js
register: function (server, options, next) {
    server.expose('key', 'value');
    next();
}
```

Then `console.log(server.plugins['plugin-name'].key)` will print `value`.

**Comment by yosiasz** [comment]
Thanks I have it exposed in the index.js of hapi-tedious as
var tedious = require('tedious'), 
	Request = tedious.Request,
	Connection = tedious.Connection,
    joi = require('joi'),
    config = require('./config/config'),
	connection = new Connection(config);;

/* var result = joi.validate(config, configSchema); */

var singleOption = joi.object({
    server: joi.string().required(),
    userName: joi.string().required(),
    password: joi.string().required(),
    options: joi.object({
        rowCollectionOnDone: joi.boolean().required(),	
        rowCollectionOnRequestCompletion: joi.boolean().required(),	
        useColumnNames: joi.boolean().required(),		
        useFieldNames: joi.boolean().required()
    })
});
var optionsSchema = joi.array().items(singleOption).min(1).single();

exports.register = function (plugin, options, next) {
  optionsSchema.validate(options, function (err, options) {
    if (err) {
      return next(err);
    }

    var connect = function (options, done) {
	  connection.on('connect', function(err, db) {
        if (err) {
          return done(err);
        }

		var tediousRequest = function(query, callback){			
				// If no error, then good to go...
				var request = new Request(query, function(err, rowCount, rows, columns) {
				  if (err) {
					console.log(err);
				  } else {
					//3.
					callback(null, columns);
				  }
				});

				//2.

				request.on('row', function(columns) {
			 			data.push( {PreferredTermID: columns.PreferredTermID.value,
								PreferredTerm: columns.PreferredTerm.value,
								LanguageCode: columns.LanguageCode.value
								}); 
					});

				//1.
				connection.execSql(request);			
			
		}		
		plugin.expose('tediousRequest', tediousRequest)	;

		});
    };

  });

   next();	

};

exports.register.attributes = {
  pkg: require('./package.json')
};

**Comment by yosiasz** [comment]
Thanks. I have it exposed as follows

plugin.expose('tediousRequest', tediousRequest)	; 

Cant reach server.plugins['hapi-tedious'] with error undefined so cant do console.log(server.plugins['hapi-tedious'].key) 

Thanks!

**Comment by gergoerdosi** [comment]
Well, you define `connect`, but you never call it. So `plugin.expose` is not executed. Anyway, this is not a hapi issue. I suggest to move this to https://github.com/hapijs/discuss.
