### ISSUE TITLE
Release notes for v10 ?

### ISSUE THREAD

**Issue by rstormsf** [hapijs/hapi#2768]
Home page points to wrong link.

**Update:
found it
https://github.com/hapijs/hapi/issues/2764

Homepage points to #2767

**Comment by gergoerdosi** [comment]
If you mean the link in "Latest update", then it points to the latest issue or the latest comment, not to the latest release note. Also, this issue belongs on https://github.com/hapijs/hapijs.com.

**Comment by nlf** [comment]
as @gergoerdosi mentioned, this issue would belong on the hapijs.com repo not here. we actually have an issue there tracking the request to add links to release notes next to entries in the changelog.

**Comment by rstormsf** [comment]
Sorry about that. Lesson learned!
