### ISSUE TITLE
Additive scopes?

### ISSUE THREAD

**Issue by jamesdixon** [hapijs/hapi#2769]
I was curious as to whether or not it's possible for scopes to be additive when setting a default scope? For example, using `server.auth.default({'strategy: 'basic', scope: ['admin']})`, the admin scope is applied to all routes as expected. However, I'd like this to be in addition to any existing scope applied to a particular route. Currently, when a scope is defined on a route, the default scope is discarded. 

Thanks!
James

**Comment by hueniverse** [comment]
Nope. Route config always overrides defaults.

**Comment by jamesdixon** [comment]
Thanks, @hueniverse. Btw, love your module naming.
