### ISSUE TITLE
multipart/form-data issue

### ISSUE THREAD

**Issue by bricss** [hapijs/hapi#2774]
Hi there,

I found some weird issue with file upload. For example if I have form with file input and sending it by AJAX request with FormData(window.chabon) payload but do not pick up any file on that form, I'm always getting request with zero bytes length file in payload. That empty file is also drop-in into temp directory.

Form:
```html
  <form action="/api/1.0/upload" enctype="multipart/form-data" id="chabon" method="post">
    <label for="title">Title:</label><input name="title" type="text">
    <br>
    <label for="upload">File (Binary):</label><input name="upload" type="file">
    <br>
    <button type="submit" value="puff!">Puff!</button>
  </form>
```
Node:
```javascript
  {
    method : 'POST',
    path : '/api/1.0/upload',
    config : {
      app : {
        name : 'upload'
      },
      payload : {
        maxBytes : 1048576 * 100,
        output : 'file',
        parse : true,
        uploads : config.server.uploads.to
      },
      handler : function(request, reply) {
         console.log(request.payload);
         reply(204);
      }
    }
  }
```
Payload:
```javascript
  { title: 'chacha',
    upload:
     { filename: '',
       path: 'd:\\Documents\\Aptana Studio 3 Workspace\\puff\\assy\\assets\\uploads\\1442763574658-924-e0a68701e1d8f184',
       headers: {
         'content-disposition': 'form-data; name="upload"; filename=""', 'content-type': 'application/octet-stream'
         },
         bytes: 0
       }
  }
```

**Comment by mtharrison** [comment]
Few suggestions/questions:

1. Can we see the code where you're sending the form request (AJAX)?
2. What's `window.chabon`? Do you mean `new FormData(document.getElementById('chabon'))`?
3. If you're not constructing a payload with `Blob` or `File` API, are you sure you're actually picking a file with the filepicker?

**Comment by bricss** [comment]
1. For example (Fetch API):
    ```javascript
      fetch(window.chabon.action, {
        body: new FormData(window.chabon),
        method : 'POST'
      }).then(function(res) {
        console.log(res);
      }, function(err) {
        console.error(err);
      });
    ```

2. Every DOM element that have an ID always available globally in window object.
Form has id="chabon", then -> document.getElementById('chabon') === window.chabon;

3. I do not select any files, just fill in title input and press submit button. Then I have 0 byte file in payload without filename and also have it stored in temp directory.

**Comment by mtharrison** [comment]
Ok. What's the issue then? What were you expecting to happen?

**Comment by bricss** [comment]
I'm expecting that if I don't sending any files within request they don't persist in payload and much more important do not have stored on filesystem at all.

**Comment by mtharrison** [comment]
Then you need to delete the file key-value pair from the form data object (https://developer.mozilla.org/en-US/docs/Web/API/FormData/delete). This isn't an issue with hapi. hapi just sees a blank file in the multipart request.

**Comment by bricss** [comment]
Yep, browsers sends multipart with empty file fields, but in previous versions I don't have seen that issue, in version 8 for example.
And it is not a good idea to handle FormData before send it to server. I'm doing this by AJAX request but in another case I'm can just make good known page post request and there is not possible to remove something from it.

**Comment by bricss** [comment]
FormData.delete() work not in all browsers, only in very modern. And request with FormData is also old good know page post request with page refresh after it.

**Comment by gergoerdosi** [comment]
This may be the relevant change: https://github.com/hapijs/subtext/commit/8ffb4cf15fa7fcfb830791b9729aee6358912a34

The new code returns `{}` on an empty payload, previously it returned `null`.

**Comment by bricss** [comment]
Imagine how many empty files may be created on filesystem after simple 1000 page post requests.

**Comment by mtharrison** [comment]
I'm not sure about a change here so I'll let others with more knowledge comment on this. 

You can use a different payload output setting like "data" or "stream" and manage the payloads yourself if you don't want hapi creating files for you.

**Comment by hueniverse** [comment]
Nothing changes about processing file uploads in hapi 9.x or 10.x. Not sure why you are seeing different outcome. Either way, an empty file is still a file. If you want to have special handling of empty files you can handle the payload yourself or delete the empty files.

**Comment by bricss** [comment]
Sorry my bad, today I looked in git history and found that zero byte files absent in hapi version 6, then I updated code to hapi 9 next to 10 and found that issue.
