### ISSUE TITLE
Flaky test? "Request does not return an error when server is responding when the timeout occurs"

### ISSUE THREAD

**Issue by rvagg** [hapijs/hapi#2779]
Test @ line 1422 on current master uses a timeout value of 50 but has a `expect(timer.elapsed()).to.be.at.least(60);` which I'm noticing failing occasionally when running against 4.1.0 and the build of 4.1.1 I'm about to promote. As far as I can tell this does not appear to be a core issue but if you believe it is then please let me know so we can take this back up to core.

I'm getting failures such as:

```
      Expected 56.29089307785034 to be at least 60
```

```
      Expected 50.512534856796265 to be at least 60
```

**Comment by hueniverse** [comment]
Looking...
