### ISSUE TITLE
Get request object from logger

### ISSUE THREAD

**Issue by netei** [hapijs/hapi#2792]
We would like to add information about the current request so that for all loggers that we use, we get that information in our logs (for example the request-id). 

Is they already some sort of way to do it or is it best to use a wrapper function that will add the interesting parts for us and call request.log itself ?

EDIT: In case we write a wrapper function, is it possible to add a new method to the request object so that we could do request.customLog(), so that we don't have to pass the `request` object to the function manually ?

**Comment by AdriVanHoudt** [comment]
do you know about https://github.com/hapijs/good ?

**Comment by netei** [comment]
Yes, I know about good, how could I do that with good ? From my custom-reporter, I don't have access to the request

**Comment by AdriVanHoudt** [comment]
hmm true maybe @arb will accept a PR to add it?

**Comment by Marsup** [comment]
Anyway that's not the place to discuss it, continue that in the discuss or good repo.
