### ISSUE TITLE
Define custom id generator

### ISSUE THREAD

**Issue by netei** [hapijs/hapi#2793]
I see that [this pull request](https://github.com/hapijs/hapi/pull/2059) has not been merged, is it possible to generate an id ourselves (we have to be able to set the requestId from a header in the `onRequest` event of our server).

Is that possible somehow ?

**Comment by hueniverse** [comment]
Just override it. The only place it will be logged is the initial received event. I rather not add another option for this for one use case. If others will ask for this feature I'll reconsider.
