### ISSUE TITLE
Route handler being called multiple times

### ISSUE THREAD

**Issue by PaddyMann** [hapijs/hapi#2794]
My route takes a URL string and returns a PDF using `phantom-html-to-pdf`:

```
server.register(require('inert'), function (err) {
  // Add the route
  server.route([
    {
      method: 'GET',
      path: '/pdf',
      handler: function (request, reply) {
        generatePdf(request.url.query.url, reply);
      }
    }
  ]);

  // Start the server
  server.start(function () {
    console.log('Server running at:', server.info.uri);
  });
});

function generatePdf (url, reply) {
  console.log('Rendering', url);

  htmlToPdf({
    url: url,
  }, function(err, pdf) {
    reply(pdf.stream).type('application/pdf');
  });
}
```

Unfortunately, the route is called twice each time the page is opened - like #2738. The response is sent back within seconds, so I can't see a good reason for this happening.

As with #2738, it can be fixed by adding this to the route:

```
      config: {
        timeout: {
          socket: false
        }
      }
```

... but it was suggested that this shouldn't be needed (and isn't a good idea?) in #2738. #2738 was also closed as a non-issue, when I suspect there may be one... thoughts?

**Comment by hueniverse** [comment]
How do you know the handler is called more than once for a single request?

**Comment by PaddyMann** [comment]
I refresh the page and watch the terminal...

**Comment by devinivy** [comment]
Sometimes browsers will make requests on their own, especially Chrome.  Try `curl`ing to get a better idea.

**Comment by PaddyMann** [comment]
OK - but I'm generating and returning a PDF, and that process hasn't necessarily stopped by the time the second request comes in.

What is the best way to handle this?

**Comment by devinivy** [comment]
Compute-heavy processes are sometimes best delegated to a child process, since they can stall your server.  This might be a good place to start looking: https://github.com/polotek/procstreams

**Comment by hueniverse** [comment]
You can't have an endpoint take this long without changing the timeouts. Making it take this long isn't a great design. Usually to notify the client via some other means that the response is ready, not making it wait. This isn't a hapi issue but a design issue with your application.

**Comment by PaddyMann** [comment]
@hueniverse: But it's not taking that long - around 5 seconds perhaps?

The documentation suggests that the socket timeout should be 2 minutes by default (http://hapijs.com/api):

```
socket - by default, node sockets automatically timeout after 2 minutes. Use this option to override this behavior. Defaults to undefined which leaves the node default unchanged. Set to false to disable socket timeouts.
```

**Comment by hueniverse** [comment]
You need to reproduce the issue with curl to make sure nothing is making a second request. If you can show the problem like that, we can take another look.
