### ISSUE TITLE
Url encoded question mark in URL path

### ISSUE THREAD

**Issue by matthieusieben** [hapijs/hapi#2801]
I'm not sure this is a valid request wrt http standarts but URL params do not seem to support URLencoded question marks (%3F).

I would like that the following URL matches the route: `/example/{someParam}`

`/example/test%40domain%3Ffoo%3Dbar?queryName=queryValue`

which would result in:

```js
request.param.someParam = "test@domain?foo=bar"
request.query.queryName = "queryValue"
```

Currently, I feel like both `?` and its url encoded version `%3F` are used by hapi as query string separator. Is this desired?

**Comment by hueniverse** [comment]
Can you add a test that fails?

**Comment by matthieusieben** [comment]
Nevermind, my proxy is responsible for this behavior.
