### ISSUE TITLE
How to match all files with a specific extension?

### ISSUE THREAD

**Issue by santo74** [hapijs/hapi#2830]
Hi,
I'm new to hapi and I'm trying to find a way to set up a route that matches all files of a given extension, including subfolders.

This is what I tried already:
```javascript
path: '/{filename}.ext'
```
Works, but only matches files in the root folder
```javascript
path: '/{filename*}.ext'
```
Doesn't appear to be a valid path (wildcard parameter can only be used as last parameter)

So I have no clue how to do this in hapi.

**Comment by mtharrison** [comment]
I'm not positive here but I think this is a case where you'd have to handle it yourself within a catch-all route. Something like:

```javascript
server.route({
    method: 'GET',
    path: '/{path*}',
    handler: function (request, reply) {

        var path = request.params.path;
        var match = path.match(/(.+\/)?(.+\.ext)$/);
        if (match) {
            var filename = match[2];
            return reply('Processing file: ' + filename);
        }

        reply('Something else');
    }
});
```

**Comment by santo74** [comment]
yeah, I thought about that too, but that seems more like a hack than a real solution because then what's the point of having a router in the first place?

I would think this is a common use case, isn't it?
E.g. serving all images from a gallery folder (which obviously can have subfolders), parsing all html files (might be in subfolders, e.g. addons) via handlebars or another template engine, etc

**Comment by danielb2** [comment]
Because of how hapi is handling routing, you cannot specify a wildcard before the end of the segment, but you can do one at the end.

http://hapijs.com/api/10.2.1#path-parameters

>  A parameter can cover the entire segment ('/{param}') or part of the segment ('/file.{ext}').

The reason hapi doesn't do this is so that the routing table is always deterministic. When you introduce regular expressions in the route, it means the order of the routes cannot be certain, and hapi also can't check if there are overlapping routes.

**Comment by danielb2** [comment]
Here's more: https://github.com/hapijs/hapi/issues/1765

**Comment by mtharrison** [comment]
It is a common use case to serve all files under a folder. But not to restrict to particular extensions via the router. In such a case I would just use a wildcard path with Inert:

`/gallery/{path*} `

I wouldn't care about extensions because if there's not a file that matches the user gets a 404 as expected.

**Comment by santo74** [comment]
Thanks Daniel, I think I understand the way wildcards work in hapi.

The reference to the other issue makes it clear that hapi is trying to avoid relying on the route order, which can be a good thing, but having to define most of the router logic inside a catch-all route because of this approach seems like a major drawback as well to me.
So actually you seem to solve a common problem by introducing another one.

I'm not sure yet, but I think I prefer relying on routing order rather than having to implement the routing logic in a catch-all route because of the lack of regex support.

**Comment by santo74** [comment]
@mtharrison The gallery example might not be the best indeed, but what if you need to do some processing before serving files, e.g. template files?
What if you have to serve files from external libraries/frameworks where all resources are located in the libraries/frameworks' subfolders?
Just putting everything under /assets and serving everything inside it via /assets/{filename*} is not a good solution in my opinion.

I understand there are pros and cons for both approaches, and depending on the type of project one approach might be better than the other, but a trivial thing such as filtering on file type should be possible in all cases in my opinion.

Another issue is the combination with SPA's, where all requests to html files should be served as is, while all requests to non-existing paths should result in the index.html file being served in order to let the client handle the routing.
As far as I understand this is also something that's apparently not obvious with hapi.

**Comment by bricss** [comment]
FYI -> https://nodejs.org/api/path.html#path_path_extname_p

```javascript
var fs = require('fs');
var path = require('path');

module.exports = function(path) {
  return fs.readdirSync(path).filter(function(val, idx, ret) {
    return fs.lstatSync(path + '/' + val).isFile() && path.extname(path + '/' + val) === 'ext';
  }).map(function(val, idx, ret) {
  return {
    method : 'GET',
    path : '/' + val,
    handler : {
      file : path + '/' + val
    }
  };
});
```
