### ISSUE TITLE
Server.inject response.result is different to server output when using sequelize

### ISSUE THREAD

**Issue by clarkie** [hapijs/hapi#2832]
I have the following route handler:
```JS
handler: function (request, reply) {
    var query = request.db.userToken.findOne({
        include: [request.db.user]
    });
    return reply(query);
}
```
If I instantiate a server and hit the route it returns the correct userToken JSON structure but if I do a `console.log` from within a `server.inject` callback I get the sequelize object:

```JS
{ dataValues:
    { id: 35,
    ...
```

A solution is to add the following to get sequelize to return the raw object
```JS
.then(function (userToken) {
    return userToken.get();
}) 
```
... but if Hapi is doing it anyway when a server is instantiated then I'm having to add this purely for the tests which doesn't seem right.

My problem is that the following assertion will fail:
```
expect(response.result).to.include(['user', 'token']);
```

**Comment by hueniverse** [comment]
I am not familiar with sequelize (or promises) to understand what you are doing. Maybe someone else can help.

**Comment by nlf** [comment]
I think I've heard this mentioned elsewhere before. Basically the gist of the matter is that the result from inject is an object that hasn't been serialized by hapi, but rather the raw object is passed through.

Sequelize (and others) return a model object with a bunch of stuff hanging off of it, but have a `.toJSON` method that hapi seems to call (whether explicitly or not) that returns a plain object. When using inject that call never happens.

**Comment by nlf** [comment]
As a workaround, you can manually `JSON.parse` the `response.payload` property

**Comment by nlf** [comment]
Which I see now is actually the intended, and documented, behavior:

```
result - the raw handler response (e.g. when not a stream or a view) before it is serialized for transmission. If not available, the value is set to payload. Useful for inspection and reuse of the internal objects returned (instead of parsing the response string).
```

**Comment by hueniverse** [comment]
Oh. Just use `result.payload` then.

**Comment by Marsup** [comment]
@nlf toJSON is used by JSON.stringify, I doubt we call it explicitly.
