### ISSUE TITLE
hapi-lts requiring node 4 and no updates to hapi 9?

### ISSUE THREAD

**Issue by ldesplat** [hapijs/hapi#2835]
Installing hapi-lts returns the following:
```
npm install hapi-lts@9
npm WARN engine hapi-lts@9.4.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.40","npm":"2.14.5"})
```

Also, why is the normal npm install hapi@9 not updated? I don't see this documented anywhere?

**Comment by nlf** [comment]
fixed the engine problem in 9.4.1.

there will be no more 9.x releases under the `hapi` package name

**Comment by hueniverse** [comment]
Note that you will need npm 3.x in order for peer deps not to block you due to the name change.

**Comment by phated** [comment]
@hueniverse can you elaborate why you decided to not use npm tags to publish LTS as "hapi" still?

**Comment by hueniverse** [comment]
My last experience with npm tags are awful. I don't know why it was so bad but even when we set the latest tag on the right version, people still ended up with the wrong release. I just don't trust the tag feature. If someone wants to play with it and prove that it works correctly now, we can move these to the hapi@9.x name.

**Comment by phated** [comment]
Going to cc @othiym23 here because he uses tags for the npm release cycle.

We are stuck on node 0.10 and npm@^2 for the time being and the peer dep problem is killer

**Comment by ldesplat** [comment]
My big problem with the naming change is that existing people on `Hapi@9` might think they are getting updates but they not told anywhere to move to `hapi-lts`. I think that's biggest issue. It is so much more intuitive to continue publishing on `hapi@9`.

I have minor gripes for plugin's tests then we need to support require('hapi-lts') and require('hapi') depending on which version of Hapi we are testing with. It can be worked around but it's annoying nonetheless.

**Comment by hueniverse** [comment]
Regarding plugins, you will soon need to stop supporting 9.x or older except for critical bugs and security issues. Basically, there are not going to be more 9.x releases except for critical issues. No new features are going to be ported down.

If we can work out the npm tags issues and the proper way to do this, I am happy to publish 9.x on hapi from the lts branch.

**Comment by phated** [comment]
Just wanted to follow up here.  The npm release process (including tagging 2.x as LTS) is documented at https://github.com/npm/npm/wiki/Release-Process

Does hapi have a release script or is it just published with `npm publish` directly?

**Comment by hueniverse** [comment]
I think we'll just publish under hapi the 9.x lts branch since we are not likely to have many releases. With 11.x we are no longer going to backport anything except for patching critical security issues.
