### ISSUE TITLE
Update hapijs/heavy to 3.0.1 from 3.0.0

### ISSUE THREAD

**Issue by kanongil** [hapijs/hapi#2836]
After I run `npm install hapi` on an empty project, an `npm ls` reports: `missing: joi@5.x.x, required by heavy@3.0.0`.

Fortunately, this does not seem to break hapi itself, but npm is confused.

npm@2 does not produce this issue.

Full output:
```sh
$ npm -v
3.3.6
$ npm ls
/Users/gil/test
└─┬ hapi@10.4.0
  ├── accept@1.1.0
  ├── ammo@1.0.1
  ├── boom@2.9.0
  ├── call@2.0.2
  ├── catbox@6.0.0
  ├── catbox-memory@1.1.2
  ├── cryptiles@2.0.5
  ├─┬ heavy@3.0.0
  │ └── UNMET DEPENDENCY joi@5.x.x
  ├── hoek@2.16.3
  ├── iron@2.1.3
  ├── items@1.1.0
  ├─┬ joi@6.8.1
  │ ├── isemail@1.2.0
  │ └── moment@2.10.6
  ├── kilt@1.1.1
  ├─┬ mimos@2.0.2
  │ └── mime-db@1.19.0
  ├── peekaboo@1.0.0
  ├── qs@4.0.0
  ├── shot@1.7.0
  ├── statehood@2.1.1
  ├─┬ subtext@2.0.0
  │ ├── content@1.0.2
  │ ├─┬ pez@1.0.0
  │ │ ├── b64@2.0.1
  │ │ └─┬ nigel@1.0.1
  │ │   └── vise@1.0.0
  │ └── wreck@6.2.0
  └── topo@1.1.0

npm ERR! missing: joi@5.x.x, required by heavy@3.0.0
```

**Comment by Marsup** [comment]
From what I can see in heavy, it's just a matter of bumping the version.

**Comment by kanongil** [comment]
Yeah, should be a simple fix.

**Comment by lloydbenson** [comment]
I updated this against master a bit ago (https://github.com/hapijs/heavy/commit/93380061b867d521576600967fcfc0af3f2d5ecc) but it would need to be published.  @kpdecker or @hueniverse?
