### ISSUE TITLE
hapi 9.3.2 and up not published to npm

### ISSUE THREAD

**Issue by KrisSiegel** [hapijs/hapi#2837]
Taking a look at ```npm view hapi versions``` the 9.x series is only up to 9.3.1. Perhaps I missed an announcement but I assume 9.3.2 and the 9.4.x series should be published to npm, no?

For anyone who stumbles by this issue because they need the latest 9.x just include the latest commit from the 9.4.2 like this in ```package.json```:

```javascript
"dependencies": {
    "hapi": "git@github.com:hapijs/hapi.git#85a93087740f630d48c60ef9b4163c63c58e7506",
},
```

You'll just need to reference hapi as ```require("hapi-lts");```.

**Comment by nlf** [comment]
They are currently published as `hapi-lts` as announced here https://github.com/hapijs/hapi/issues/2765

**Comment by KrisSiegel** [comment]
Oh that's what I was missing; didn't even notice that. Was there a reason for the package rename? Most of the packages I used simply created a branch for whatever major version they were last supporting for node x.12. Just curious.

**Comment by KrisSiegel** [comment]
Found this thread which helped me understand a bit better. Thanks for the clarification! https://github.com/hapijs/hapi/issues/2835
