### ISSUE TITLE
Support for request forwarding

### ISSUE THREAD

**Issue by bleupen** [hapijs/hapi#2838]
Hapi makes so many things so easy that I am surprised that internal request forwarding is not built-in. I would love to do something like:

```javascript
...
handler: function(req, reply) {
   req.forward('/some/other/route/on/this/server', reply);
}
```

I realize that I can do server.inject() but I don't want to buffer (or otherwise process) the response. I also would like to preserve the original request, rather than recreate it. 

Is this possible? Or is there an obvious approach that I am missing? Thanks!

**Comment by hueniverse** [comment]
The right way to do this is to change the request uri in `onRequest` using an extension.

**Comment by bleupen** [comment]
I hoped I could put this in a route-based extension in Hapi 10 but onRequest is not allowed there. This means the forwarding logic would have to reside outside of my route configuration, which is less than ideal.

**Comment by hueniverse** [comment]
You can't have it both ways. Either you forward before you even start processing a request or you have to finish processing all the way. I know you think this is simple but it really isn't especially once you have other plugins involved.

**Comment by devinivy** [comment]
@bleupen if your primary goal is to organize your code in a particular way, you could add it to your route configuration, then consume it out of your route configuration before passing the proper config to `server.route()`.
