### ISSUE TITLE
server.decorate('request', ... ) access to request object. 

### ISSUE THREAD

**Issue by ozum** [hapijs/hapi#2842]
I mistakenly created this question in an old issue (#2481), and recreated it here.

I'm not sure it is a bug or it is by design:

When using `server.decorate('request', ...), I can not access request object from the function.

    server.decorate('request', 'setLocale', function(locale) {
        this.i18n.locale = locale;  // <-- this = undefined, I assumed this = request
    });

I assumed this is a reference to request object like decorate('reply', ...) example in API docs.

How can I access request object?

**Comment by AdriVanHoudt** [comment]
it should work see https://github.com/hapijs/hapi/blob/master/test/plugin.js#L2323

**Comment by Marsup** [comment]
Indeed, are you sure that's not i18n that's undefined ?

**Comment by AdriVanHoudt** [comment]
uhu if the error is `cannot access i18n of undefined` then `request.i18n` is undefined

**Comment by ozum** [comment]
@AdriVanHoudt, the error is `Cannot read property 'i18n' of undefined`. So it seems `this` is undefined. However the test you mentioned works well. I created a minimal test on a barebone hapi server, it also works. Most probably my tests in the first place have some error. I'm investigating it.

I'm closing this issue. Sorry for inconvenience.

**Comment by AdriVanHoudt** [comment]
Oh my thing should have been `cannot read locale of undefined` but you got the point ^^ 
And that is weird then...
