### ISSUE TITLE
reply.continue throws error

### ISSUE THREAD

**Issue by nelsonic** [hapijs/hapi#2843]
Hi!
We are trying to write an auth plugin which supports the `try` and `optional` modes.
My *understanding* (per the [*API*](http://hapijs.com/api#reply-interface) ) is that the plugin's implementation needs to `return reply.continue()` 
to return control back to the framework without setting a response if auth *does not succeed*.

But when we attempt to do this, we see:

```sh
Debug: internal, implementation, error
    Error: Authentication response missing both error and credentials
```

We see the same error if we attempt to: `return reply.continue({ credentials : null });`

Can anyone clarify what we are doing wrong here? thanks!
(*tried googling, found nothing...* :disappointed: )

**Comment by AdriVanHoudt** [comment]
As the error tells you it expects an error or credentials, setting credentials to null is the same as not passing credentials. You can take a look at any other auth implementation to see what is expected (shameless self plug https://github.com/Salesflare/hapi-auth-bearer-simple/blob/master/lib/index.js ;), we return an error as first param always unless successfull, then we pass credentials, which is an actual object or value not null )

**Comment by nelsonic** [comment]
@AdriVanHoudt thanks for your reply, however you are not *explicitly* ***testing*** for `try` or `optional` mode in [hapi-auth-bearer-simple](https://github.com/Salesflare/hapi-auth-bearer-simple/blob/8af7e33c2828b70a52d5e4216c029e399b65efc3/test/index.js) ...
We are trying to make our authentication scheme ***optional*** so that people can:
```js
      config: {
        auth: {
          strategy: 'auth-plugin-name',
          mode: 'try'
        }
      }
```

**Comment by devinivy** [comment]
@nelsonic hapi will take care of making the strategy optional or tried on its own, based upon the scheme's implementation.

**Comment by nelsonic** [comment]
@devinivy thanks, but *how* do we *explicitly* declare that a type of auth is `optional` for a given route?

**Comment by AdriVanHoudt** [comment]
won't hapi just do that for you when you return 'isValid: false' ?

**Comment by hueniverse** [comment]
In the docs: "If the err does not include a message but does include a scheme name (e.g. Boom.unauthorized(null, 'Custom')), additional strategies will be attempted in order of preference."

**Comment by nelsonic** [comment]
Thanks @hueniverse :+1:

**Comment by devinivy** [comment]
@nelsonic a good example of this is https://github.com/dwyl/hapi-auth-jwt2/issues/104.  Might be a good idea for us to add this to http://hapijs.com/tutorials/auth#authenticate.

**Comment by nelsonic** [comment]
@devinivy I think I'm just not very *good* at reading the documentation and end up asking a lot of questions... :wink:

**Comment by devinivy** [comment]
All well :+1: :)
