### ISSUE TITLE
Can't add templating engine in plugin

### ISSUE THREAD

**Issue by luismatute** [hapijs/hapi#2846]
I want to implement routes per plugin, but I can't add the views engine inside the plugin. I've seen examples where this is possible, E.G.: https://github.com/hapijs-edge/hapi-plugins.com/blob/master/lib/routes.js, but I'm getting an error saying `server.views is not a function`

Here is a quick example that will get the error:

    var Hapi = require('hapi');

    var server = new Hapi.Server();
    server.connection();

    var myPlugin = {
        register: function (server, options, next) {

            // Error happens here, should be able to see server.views()
            console.log(server.views()); 
            next();
        }
    };

    myPlugin.register.attributes = {
        name: 'myPlugin',
        version: '1.0.0'
    };

    server.register( myPlugin, function(err) {

        if (err) {
            console.error('Failed to load a plugin:', err);
        }
    } );

    server.start(function () {

    	console.log('Server running at:', server.info.uri);
    });

**Comment by Marsup** [comment]
You need to register and depend on vision since hapi 9.

**Comment by luismatute** [comment]
wow, i feel dumb... Thanks @Marsup!
