### ISSUE TITLE
Server hangs on GET /stuff/123 after DELETE /stuff/123

### ISSUE THREAD

**Issue by maxhedouin** [hapijs/hapi#2851]
This is reproducible on the latest version of hapi (11.0.0) as well as previous version (at least 8.4.0)

Here is the reproduction scenario: 
- create a server with 2 routes: GET /stuff/123 and DELETE /stuff/123
- start the server
- call DELETE /stuff/123
- call GET /stuff/123 > the GET call hangs. 
- call GET /stuff/123 > returns as expected

Let me know if there is anything else I can provide. Note that it seems that calling any GET hangs after a DELETE. 

Here is the code I used the reproduce the scenario above: 

```javascript
'use strict';

var Hapi = require('hapi');

// Create a server with a host and port
var server = new Hapi.Server();

server.connection({
    port: 3000
});

// Add the route
server.route(
    [
        {
            method: 'GET',
            path:'/stuff/{id}',
            handler: function (request, reply) {
                reply('get');
            }
        },
        {
            method: 'DELETE',
            path:'/stuff/{id}',
            handler: function (request, reply) {
                reply('delete');
            }
        }
    ]
);

// Start the server
server.start(function () {
    console.log('Server running at:', server.info.uri);
});
```

**Comment by maxhedouin** [comment]
Please note that this seems to be OS specific. I can't reproduce on a mac book pro but I can reproduce on an ubuntu server: 
```shell
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
```

**Comment by mtharrison** [comment]
Don't have an Ubuntu installation around to test this but version 0.12 of node was never supported by hapi. Does it happen on node versions supported by hapi (4.x.x, 0.10)?

**Comment by maxhedouin** [comment]
Thanks @mtharrison, as weird as this sounds, it seems to be a Postman issue... I wasn't able to reproduce the above steps using curl... 

So, feel free to close this ticket and thanks for the prompt answer.
