### ISSUE TITLE
Ext invoke inconsistent with sync vs. async callback

### ISSUE THREAD

**Issue by kpdecker** [hapijs/hapi#2854]
Prior to [this change](https://github.com/hapijs/hapi/commit/ae2c280f48aa5ccd8ba60537521f5f4e98af11d2#diff-c945a46d13b34fcaff544d966cffcabaL342), server extensions were always async. After the above change, this is causing a test failure in nes (See below) due to cleanup not completing prior to the `server.stop` callback method being called.

In some ways this test was passing as a coincidence of the async behavior, so arguably the fix should be made in there, but filing a bug here to address the potential Zalgo concerns in the API itself.

```
  86) Listener _subscribe() subscribes to two paths on same subscription:

      actual expected

      {}

      Expected { Object (1445213006672:hayes:32242:ifx6icss:10000) } to equal specified value

      at nes/test/listener.js:356:74
```

**Comment by hueniverse** [comment]
I don't think this is a bug. If you notice, the next tick call was only added when no extension was found. If one was found, unless it called `reply()` (and not just `reply.continue()`, no next tick is inserted.

**Comment by kpdecker** [comment]
If other portions of this function could be sync vs. async, I suppose it doesn't matter.
