### ISSUE TITLE
OPTIONS not working with new cors

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/hapi#2855]
Previously I had the methods option set for cors but v11 removed this. Now my options calls are failing. The regular GET/... calls still work though.

I noticed that https://github.com/hapijs/hapi/blob/master/lib/cors.js#L147 was set to false.

Server settings:
```js
{
	"host": "127.0.0.1",
	"port": 4430,
	"routes": {
		"cors": true
	},
	"labels": ["default"]
}
```

Request headers:
```json
OPTIONS /me HTTP/1.1
Host: 127.0.0.1:4430
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Access-Control-Request-Method: GET
Origin: http://127.0.0.1:3500
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36
Access-Control-Request-Headers: accept, authorization
Accept: */*
DNT: 1
Referer: http://127.0.0.1:3500/src/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: nl,en-US;q=0.8,en;q=0.6
```

Response headers:
```js
HTTP/1.1 404 Not Found
content-type: application/json; charset=utf-8
cache-control: no-cache
vary: accept-encoding
content-encoding: gzip
Date: Mon, 19 Oct 2015 08:36:20 GMT
Connection: keep-alive
Transfer-Encoding: chunked
```

Route config:
```js
{
		method: 'GET',
		path: '/me',
		handler: handler,
		config: {
			auth: 'bearerAuth'
		}
	}
```

**Comment by Marsup** [comment]
Shouldn't the routes part be inside a connections property ?

**Comment by AdriVanHoudt** [comment]
Might have typed it ambiguous, the server settings are for a connection so they are inside a connections property

**Comment by hueniverse** [comment]
I need code I can reproduce. As you can see from the test, it works.

**Comment by AdriVanHoudt** [comment]
Yeah I looked at the tests, why I opened an issue because I don't know what I am doing wrong. I have meetings all day but it is the first thing I'll do afterwards.

**Comment by nlf** [comment]
I had a similar issue myself, it turned out to be because 'Accept' isn't in the list of allowed headers by default. I added it in the additionalHeaders and it resolved the issue for me.

**Comment by vdeturckheim** [comment]
I had the same issue yesterday. I'll try @nlf's fix tonight.
Cheers.

**Comment by AdriVanHoudt** [comment]
Ok so it looks like I had to match `additionalHeaders` with the request `Access-Control-Request-Headers` header https://github.com/hapijs/hapi/blob/master/lib/cors.js#L118-L124

Although not sure why I need to do this (don't know everything about cors :P)

Thanks @nlf for the hint!

**Comment by hueniverse** [comment]
If there are more headers we should include by default, that's a possible solution.

**Comment by nlf** [comment]
It's likely that 'Accept' should be added to the default headers

**Comment by hueniverse** [comment]
I'll take a PR

**Comment by AdriVanHoudt** [comment]
For me it was accept and authorization, is there a spec for this or are these just sane defaults?
