### ISSUE TITLE
Mixed CORS responses since update...

### ISSUE THREAD

**Issue by varmint09** [hapijs/hapi#2860]
Hi,

The changes to Hapi have caused issues with the handling of CORS, what is the solution?

**Comment by varmint09** [comment]
I also now get a failed OPTIONS request which I am sure I wasn't before;

Remote Address:xx.xxx.xx.xxx:443
Request URL:https://api.mydomain.com/user/login
Request Method:OPTIONS
Status Code:404 Not Found

**Comment by vdeturckheim** [comment]
Are you referring to #2855 ?

**Comment by varmint09** [comment]
Perhaps, but I couldn't quite work out what the exact fix was, and if it was worth adding the header etc in the interim?

**Comment by hueniverse** [comment]
Try 11.0.1 and see if the error payload helps you figure out the issue.

**Comment by varmint09** [comment]
I have tried with 11.0.1

XMLHttpRequest cannot load https://api.mydomain.com/user/login. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I am using angular to make the request to the API.

Has something changed with how I should enable CORS on the api? I have included the config I used at the start of this thread.

Ever so sorry to be a nuisance, but like I said, this was working just fine before...

**Comment by AdriVanHoudt** [comment]
that is not the payload, can you also copy the headers of the request?

**Comment by varmint09** [comment]
Ok, looks like one issue was that I wasn't sending a response to an OPTIONS call on the same endpoint;

```javascript
XMLHttpRequest cannot load https://api.justhowcute.com/user/login. Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.
```

The full details of what happens in that OPTIONS is here;

```javascript
Remote Address:xx
Request URL:https://api.mydomain.com/user/login
Request Method:OPTIONS
Status Code:200 OK
Response Headers
view source
access-control-allow-credentials:true
access-control-allow-origin:http://www.mydomain.com
access-control-expose-headers:x-total-count
cache-control:no-cache
Connection:keep-alive
Content-Length:0
Date:Tue, 20 Oct 2015 13:22:25 GMT
Server:nginx/1.6.2
vary:origin,accept-encoding
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Access-Control-Request-Headers:accept, content-type
Access-Control-Request-Method:POST
Cache-Control:no-cache
Connection:keep-alive
DNT:1
Host:api.mydomain.com
Origin:http://www.mydomain.com
Pragma:no-cache
Referer:http://www.mydomain.com/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36
```

The POST doesnt seem to happen because of the first error... sorry to ask again, but the way I enabled CORS for all routes; is that still the correct approach (post 1).

Like I say the other requests work fine... I handle the OPTIONS like so;

```javascript
  {
    method: 'OPTIONS',
    path: '/user/login',
    handler: function (request, reply) {
        reply();
    }
  }
```

**Comment by varmint09** [comment]
Looks like this is now the same issue as #2853

**Comment by hueniverse** [comment]
You can't set your own OPTIONS handler with the new setup. Either you let hapi handle all OPTIONS requests or come up with your own CORS solution. Things should work just fine if you remove your OPTIONS handler.

**Comment by AdriVanHoudt** [comment]
It is possible you will need to set 
```js
"cors": {
    "additionalHeaders": ["accept", "authorization", "content-type"]
}
```
and like Eran said remove your own options handler, hapi will register these for you

**Comment by gitawego** [comment]
just updated to 11.0.1, it still doesn't work even with ``"additionalHeaders": ["accept", "authorization", "content-type"]``

OPTION request just simply returns 404

**Comment by varmint09** [comment]
I can confirm that for me, the above setting did work; although I feel due to the number of other users with this issue, it should have been better communicated in the changelog, or caught sooner.

Perhaps we can have a alpha version in npm and using an odd version number for development releases that need more extensive (public) testing.  Keeping it all in npm, and allowing us to easily switch would hopefully result in more testers (certainly I would be willing to test and provide feedback on those).

Otherwise, thanks for your help and continued good work on this, its still my favourite npm package.

**Comment by AdriVanHoudt** [comment]
It seems there was an issue with comparing lowercase headers, I was able to replace the above with just cors: true

**Comment by AdriVanHoudt** [comment]
With the latest patch
