### ISSUE TITLE
`request.server` has multiple connections

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/hapi#2863]
Why is not just the connection the request happened on?

**Comment by mtharrison** [comment]
Perhaps I misunderstood the question but I think you answered it yourself. A server can have multiple connections:

    server.connection({ port: 5000 });
    server.connection({ port: 5001 });

If you just want the connection a request was picked up by, you can use `request.connection`.

**Comment by AdriVanHoudt** [comment]
Hmm can I do inject on that?

**Comment by mtharrison** [comment]
Yep. From the Docs (http://hapijs.com/api#serverinjectoptions-callback):

> When the server contains more than one connection, each server.connections array member provides its own connection.inject().

**Comment by AdriVanHoudt** [comment]
so I can do `request.connection.inject`? cool

**Comment by mtharrison** [comment]
I've never done it but it should work. you should try it out!

**Comment by AdriVanHoudt** [comment]
seems to work thanks!
