### ISSUE TITLE
certificate for TLS configuration

### ISSUE THREAD

**Issue by kynwu** [hapijs/hapi#2864]
**I used below cmd to generate private key and cert. for hapi, however when browsing the website, Chrome always shows ``ERR_SSL_VERSION_OR_CIPHER_MISMATCH``
But if I use TLS example code under test folder...it just work...**

**Where can I possibly make mistake?**

```
openssl genrsa -out key.pem
openssl req -new -key key.pem -out csr.pem
openssl x509 -req -days 9999 -in csr.pem -signkey key.pem -out cert.pem
```

**Comment by mtharrison** [comment]
Try setting your private key size higher than the default of 512:

openssl genrsa -out key.pem 1024

**Comment by kynwu** [comment]
@mtharrison 
Hi, thanks for reply.
I use https://www.sslshopper.com/certificate-key-matcher.html for checking the cert.
and I found out that the cert under ``test`` folder doesn't contain Common Name (CN),
Could this make the difference?

**Comment by mtharrison** [comment]
Not sure. Not really a TLS expert. I just know the above from testing with self-signed certificates.

**Comment by kynwu** [comment]
@mtharrison 
Thank you so much!!! I tried your suggestion and it worked!
***raise private key size from 512 to 1024***
What's the magic behind? Is it requirement from Chrome?

**Comment by AdriVanHoudt** [comment]
Also no expert but I believe a higher key size is indeed required see https://developers.google.com/web/fundamentals/security/encrypt-in-transit/generating-keys-and-csr?hl=en
