### ISSUE TITLE
Gzip compression is skipped when content-length is unknown

### ISSUE THREAD

**Issue by nlindley** [hapijs/hapi#2869]
I ran across an issue that when replying with a stream of unknown length, gzip compression is skipped. It looks like the issue stems from assuming the content-length is 0 if the header has not been set.

https://github.com/hapijs/hapi/blob/master/lib/transmit.js#L183

As far as I can tell, the check for length first appeared in this commit.

https://github.com/hapijs/hapi/commit/96083e3abf231c77d6192ed8f9716803a22e5880#diff-1b255634e333bd5cd92f5b48c61e72cbR224

**Comment by kanongil** [comment]
Thanks. This definitely seems like a bug. I have submitted a PR to fix this in #2870, which also includes a fix to a more serious bug when `response.emptyStatusCode === 204`.
