### ISSUE TITLE
How do I specify a route prefix when registering multiple plugins?

### ISSUE THREAD

**Issue by Dindaleon** [hapijs/hapi#2878]
Hello,

I know how to set a route prefix when registering a single plugin; however, I need to do this when registering multiple plugins. 

How am I suppose to accomplish this? I cannot find the answer anywhere.

**Comment by nlf** [comment]
As per the documentation [here](http://hapijs.com/api#serverregisterplugins-options-callback)


```js
server.register({
  register: YourPlugin,
  routes: {
    prefix: '/prefix'
  }
}, function (err) {});
```

**Comment by nlf** [comment]
For future reference, questions like this belong in the [discuss](https://github.com/hapijs/discuss) repo. I'm going to close this, but feel free to reopen it there if you still have trouble.

**Comment by Dindaleon** [comment]
Great, thanks. I missed it. Sorry for posting in the wrong section.
