### ISSUE TITLE
`server.decorate` method signature update

### ISSUE THREAD

**Issue by arb** [hapijs/hapi#2880]
With the move to using `=>` functions, functions passed as the `method` value of `server.decorate` rely on the the `this` pointer being the server, reply, or request object. If you want to use the `server.decorate` method, you have to know this fact and know that you can't use an arrow function in this context because your `this` pointer won't be to the object you are trying to decorate. 

I think for consistency and to reduce confusion, the `method` function should be passed the object you are trying to decorate as well as any other arguments the function would normally be passed.

```
server.decorate('reply', 'success', (obj) => {

    return obj.response({ status: 'ok' });
});
```

**Comment by AdriVanHoudt** [comment]
This would in general make the api more readable instead of having to use an 'invisible' this

**Comment by hueniverse** [comment]
That's a lot of arguments manipulation in what is likely to be hot code.

**Comment by hueniverse** [comment]
For now I opted to simply document this.

**Comment by duivvv** [comment]
any chance on reopening this (pun intended); makes a lot more sense when using ES2015

**Comment by devinivy** [comment]
Unless the whole framework is going to pass contexts (i.e. in handlers), I would personally opt to hold off on this.  I do like that the current implementation gives the experience of adding a method to an object similar to monkey-patching– I think this keeps it all conceptually simple.  Sometimes you need full functions!

**Comment by hueniverse** [comment]
I still don't want to change this.

**Comment by duivvv** [comment]
Ok.
Your call. 

I try to avoid the magical "this" as much as possible in my code.

**Comment by hueniverse** [comment]
Nothing magical about it. It's part of the language and worth learning how to use.

**Comment by duivvv** [comment]
oh well, this is a debate I can't win ;)
