### ISSUE TITLE
Replace bluebird with native promises

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#2881]

**Comment by mmc41** [comment]
Are native promises still used (which would be great)? The typescript definitions on DefinitelyTyped indicate that non-native promises are used which gives some compilation errors in typescript with mixing native promises with the promises returned by server.inject etc. So if you can confirm native promises are the only ones in play, I will open an issue on the DefinitelyTyped typings.

**Comment by devinivy** [comment]
@mmc41 I can confirm we use native promises!
