### ISSUE TITLE
Extension Point prevents close callback to be fired

### ISSUE THREAD

**Issue by KeKs0r** [hapijs/hapi#2882]
Hi,

I just upgraded to Hapi 11.0.1 and experience some weird behaviour within one of my test cases:

I have an onPostStop extension Point:
```javascript
    s.ext('onPostStop', function (server, next) {
        var timerObj = new Hoek.Timer();
        console.log('onPostStop');
        Async.parallel([
            function(cb){
                console.log('Starting shutdown');
                q.shutdown(500,function(){
                    console.log('Done Shutdown');
                    cb();
                });
            },
            function(cb){
                console.log('starting server close');
                kueServer.close(function(){
                    console.log('done server close');
                    cb();
                });
            }
        ], function(){
            console.log('onPostStop done');
            console.log("Elapsed time from initialization: " + timerObj.elapsed() + 'milliseconds');
            next();
        });
    });
```

And I also have a testcase 
```javascript
    after(function (done) {
        console.log('Start Stop');
        server.stop({timeout: 3000}, function(){
            console.log('stopping done');
            done();
        });
    });
```

Problem is that my server.stop callback is never called and my testcases time out.
I know that the last console.log("Elapsed time from initialization: ....") is triggered. Also when I change the next() call to return an error, the callback within my testcase is triggered:

```javascript
            // .....
            console.log("Elapsed time from initialization: " + timerObj.elapsed() + 'milliseconds');
            next(new Error('My Error'));
        });
```

**Comment by Marsup** [comment]
Mind giving more details than that ?

**Comment by KeKs0r** [comment]
@Marsup: Sorry I hit enter and it created the issue before I could write any details for it

**Comment by Marsup** [comment]
Maybe something else is blocking the stop, do you have any plugin dealing with that ?

**Comment by KeKs0r** [comment]
I do, but when commenting out my whole extension point and instead just call next, it works fine as well:

```javascript
    s.ext('onPostStop', function (server, next) {
        next();
    });
```

**Comment by Marsup** [comment]
I don't see anything wrong in the code dealing with that nor in your code, I'll let other people dig that :)

**Comment by Marsup** [comment]
Is your onPostStop log appearing multiple times ?

**Comment by KeKs0r** [comment]
These are my logs: 
```
Start Stop
onPostStop
Starting shutdown
Done Shutdown
starting server close
done server close
onPostStop done
Elapsed time from initialization: 3milliseconds


Test script errors:

Timed out (20000ms) - After Admin matchday input
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

**Comment by hueniverse** [comment]
Try putting the `server.stop()` in a `setTimeout()` and see if that helps. If it does, I'll look more into it.

**Comment by KeKs0r** [comment]
I figured out that one of the callbacks in another ext Handler is occasionally not triggered. That is what caused it. Don't know why directly calling next(), solved the problem. 
Still thinking that the extensions should timeout or throw an exception to point towards the issue.
