### ISSUE TITLE
subtext requires qs@'4.x.x' but will load 5.2.0

### ISSUE THREAD

**Issue by jcollum** [hapijs/hapi#2883]
```
 $ npm list hapi 
npm WARN unmet dependency /Users/collumj/work/alpha/node_modules/hapi/node_modules/subtext requires qs@'4.x.x' but will load
npm WARN unmet dependency /Users/collumj/work/alpha/node_modules/hapi/node_modules/qs,
npm WARN unmet dependency which is version 5.2.0
ser-widget-api@0.9.0 /Users/collumj/work/alpha
└── hapi@11.0.2 
```

I'm looking around now, trying to sort out why. Thought y'all might be able to answer it more definitively though. It seems like maybe the qs module bumped a major version of a dependency in a minor version of that repo. That seems odd.

**Comment by jcollum** [comment]
Related: https://github.com/hapijs/subtext/commit/57c547bdb3ba345ea1a794dcbafb14a946349b17

**Comment by johnbrett** [comment]
This is resolved through https://github.com/hapijs/hapi/issues/2862

**Comment by jcollum** [comment]
OK so it looks like the issue is that the new version of Hapi etc. hasn't made it to NPM yet.
