### ISSUE TITLE
PUT/POST paylaods not parsed

### ISSUE THREAD

**Issue by craigbeck** [hapijs/hapi#2889]
I have two routes, a `POST` and a `PUT` that are exhibiting strange behavior with respect to payload parsing resulting in validation failures.

In both cases a response with status 400 is returned:

```json
{
  "statusCode":400,
  "error":"Bad Request",
  "message":"\"value\" must be an object",
  "validation": {
    "source":"payload",
    "keys":["value"]
  }
}
```

It's the same response for both endpoints that use different validation schema (via Joi)

I added a couple of handlers for the extension points `onRequest`, `onPreAuth`, `onPostAuth`, and `onPreHandler` just to log the request and see what was happening and I found that the payload at `onPostAuth` was still `null`. According to [Request Lifecycle docs](http://hapijs.com/api#request-lifecycle) the payload should have been parsed at this point.

1. `onRequest`
1. `onPreAuth`
1. (authenticate)
1. (payload parsed)   <== doesn't appear to be happening
1. `onPostAuth`       <== payload is still `null`
1. (validate payload) <== legitimately fails as payload is `null`
1. `onPreHandler`

I've tried debugging the issue, and couldn't reproduce it (i.e. the payload was there and passed validation as expected when debugging). We also have the same app running elsewhere (other dev machines, test environment) where it also fails... or works okay. 

There also is a `POST` /login route that takes a payload and validates okay even when the other routes are being problematic. Login doesn't require auth, so I tried setting `auth: false` on the problem routes and the problem goes away (i.e. payload is parsed)

Any suggestions?

**Comment by mtharrison** [comment]
It will be much easier to help if you can share some code? Ideally a minimal sample showing the unexpected behaviour.

**Comment by craigbeck** [comment]
I'll try and craft a minimal app to reproduce. As it is currently, I don't know what to share that would shed light on the situation. I have working auth using [hapi-auth-jwt2](https://github.com/dwyl/hapi-auth-jwt2) that has a bit of code for verifying the token, but otherwise the request doesn't even hit the handler and is response is coming from within the framework.

onPreAuth:

```
[log,debug,onPreAuth], data: {"method":"put","path":"/invites/774e7d67-c051-4eb8-83b4-bca658b3a83f","payload":null,"auth":{"isAuthenticated":false}}
```

onPostAuth:

```
[log,debug,onPostAuth], data: {"method":"put","path":"/invites/774e7d67-c051-4eb8-83b4-bca658b3a83f","payload":null,"auth":{"isAuthenticated":true}}
```

**Comment by devinivy** [comment]
To be clear– are you actually posting a payload when this fails?  What's the content-type sent?  Depending on your version of hapi, if you want to be able to receive an empty payload and you're using Joi, you need to `.allow(null)` at the end of your schema.

This was a breaking change in hapi v9: https://github.com/hapijs/hapi/issues/2689

**Comment by craigbeck** [comment]
Yes, I am sending a JSON payload with content-type of "application/json". The client is using [axios](https://github.com/mzabriskie/axios) for the request and does this by default, and the same result happens using swagger UI provided by [hapi-swaggered-ui](https://github.com/z0mt3c/hapi-swaggered-ui)

This is a request against the misbehaving instance (backed by fake auth data etc):

```sh
curl -X PUT --header "Content-Type: application/json" --header "Accept: application/json" --header "Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZvb0BiYXIuY28iLCJvcGVyYXRvcklkIjoxMTQ5LCJzY29wZSI6WyJhZ3JlZW1lbnQ6dmZvbmsiXSwidmVyc2lvbiI6MSwiaWQiOiJhNWM3OTZiNi0yM2RkLTQ0OTgtYjlkMy1kMzM5ZGY3ZGE0YjQiLCJleHAiOjE0NDg5MDkxNjM2MDgsImlhdCI6MTQ0NjMxNzE2M30.xlMX9euf6hQjiLWnDHyi7c_233Ju6qfvRgHMvF4vdXY" -d "{ \"alias\": \"string 123\"}" "http://multiline-admin-api.zipwhip.com/invites/82a970a9-33c0-4d5b-89e4-8b0e9c382929"
```

and this is the output of the request lifecycle hooks logging:

```
[log,debug,onRequest], data: {"method":"put","path":"/invites/82a970a9-33c0-4d5b-89e4-8b0e9c382929","payload":null,"headers":{"content-type":"application/json","accept":"application/json"},"auth":{"isAuthenticated":false}}
[log,debug,onPreAuth], data: {"method":"put","path":"/invites/82a970a9-33c0-4d5b-89e4-8b0e9c382929","payload":null,"headers":{"content-type":"application/json","accept":"application/json"},"auth":{"isAuthenticated":false}}
[log,debug,onPostAuth], data: {"method":"put","path":"/invites/82a970a9-33c0-4d5b-89e4-8b0e9c382929","payload":null,"headers":{"content-type":"application/json","accept":"application/json"},"auth":{"isAuthenticated":true}}
[response], http://6a0ef3f58239:8081: put /invites/82a970a9-33c0-4d5b-89e4-8b0e9c382929 {} 400 (86ms) 
```

The request has appropriate headers, authenticates okay, but there isn't any payload and therefore fails validation after the `onPostAuth` event where the payload _should_ be available.

I also added another route on a different path that uses same handler/validation/config _execpt_ for `auth: false` which works as expected

```
[log,debug,onRequest], data: {"method":"put","path":"/invites/no-auth/82a970a9-33c0-4d5b-89e4-8b0e9c382929","payload":null,"headers":{"content-type":"application/json","accept":"application/json"},"auth":{"isAuthenticated":false}}
[log,debug,onPreAuth], data: {"method":"put","path":"/invites/no-auth/82a970a9-33c0-4d5b-89e4-8b0e9c382929","payload":null,"headers":{"content-type":"application/json","accept":"application/json"},"auth":{"isAuthenticated":false}}
[log,debug,onPostAuth], data: {"method":"put","path":"/invites/no-auth/82a970a9-33c0-4d5b-89e4-8b0e9c382929","payload":{"alias":"string 89078"},"headers":{"content-type":"application/json","accept":"application/json"},"auth":{"isAuthenticated":false}}
[log,debug,onPreHandler], data: {"method":"put","path":"/invites/no-auth/82a970a9-33c0-4d5b-89e4-8b0e9c382929","payload":{"alias":"string 89078"},"headers":{"content-type":"application/json","accept":"application/json"},"auth":{"isAuthenticated":false}}
[response], http://7496f40fa8c4:8081: put /invites/no-auth/82a970a9-33c0-4d5b-89e4-8b0e9c382929 {} 200 (34ms) 
```

logging `onPostAuth` shows the payload has been parsed.

config for above handler:

```js
{
    tags: ["api"],
    validate: {
      params: {
        id: Joi.string().required()
      },
      payload: Joi.object({
        alias: Joi.string().required()
      })
    },
    handler: (request, reply) => {
       // updates and returns data
    }
  }
```

So, I'm still perplexed as to why the payload isn't parsed form the request. Stil trying to come up with minimal repro-case.

**Comment by devinivy** [comment]
The fact that this happens when auth is `false` points towards a possible blip during payload authentication.  Does the auth scheme you're using support payload authentication?  On your route configuration, are you setting `auth.payload` to anything other than `false`?  In route settings, do you have `payload.failAction` set to anything other than it's default (`error`)?  Also, mind sharing your version of hapi?

**Comment by hueniverse** [comment]
What version are you on?

**Comment by craigbeck** [comment]
The auth scheme is using JSON web tokens, and isn't doing any payload authentication. `auth.payload`  and `payload.failAction` are not set.

Hapi version is 11.0.2

**Comment by craigbeck** [comment]
So far I haven't been able to get a repro with a minimal project. This is what I put together: https://github.com/craigbeck/hapi-issue-2889 but I've not had the same issue — authenticated and non-authenticated routes have parsed payloads available as expected. I've tried this locally on OSX and Ubuntu as well as on the same host in our test environment as is running the problematic instance.

**Comment by devinivy** [comment]
With the given info, if this were my project, at this point I would start poking around the application to see if anything is tampering with `request.payload`.  Starting place would be any `onPostAuth` extension.

If you feel comfortable digging, adding some logging around here where the payload is set might be worthwhile to verify hapi is setting the payload correctly: https://github.com/hapijs/hapi/blob/99c1c4cfccafc36b596313b89e73e44ddeb115be/lib/route.js#L399

**Comment by craigbeck** [comment]
Thaks @devinivy I missed the hint at Subtext doing the parsing before so I just started looking at this area of the code. The only extensions I have are the ones that are logging the request lifecycle, and I spent some time this weekend reviewing plugin code for anything related to `payload` and don't see anything else even reading the payload.

**Comment by craigbeck** [comment]
I've spent a bunch of time on this but have been unable to get a repro case to provide outside of the single instance that was failing. FWIW the problem app was running in a Docker container with nginx proxy in front of that. I tried taking that docker image and running locally, as well as starting new instances from the same image that was failing on the same host, with, and without, nginx proxying to the node app without being able to reproduce. Subsequent builds of the image are not exhibiting the issue.

Closing issue. Thanks for giving it attention.

**Comment by craigbeck** [comment]
I've had this issue pop up again. Thanks to @devinivy pointers to Subtext parsing in route.js I've been able to determine that that buffer is empty at this point. Digging into the auth code for `hapi-auth-jwt2` I could use Wreck to parse the payload OK in the `authenticate` step, so that verifies that hapi is recieving it. My guess now is some step is reading the stream, so that the "second" read that happens in the `parse payload` step is passed a stream that has already been read. Now just to track down where this could be happening...
