### ISSUE TITLE
request.auth not set in custom failAction handler

### ISSUE THREAD

**Issue by Uptown76** [hapijs/hapi#2890]
Using Hapi js version 8.8.1.

*request.auth* is not set to the current session but to a non-authenticated session object in the custom *failAction* handler for when a validation error occurs. This in turn means that the *request.auth* is not also set in the *onPreResponse* handler. I am passing the session object to all views in the *onPreResponse* handler. I am new to node and hapi js, I could be missing something fundamental.

**Comment by mtharrison** [comment]
Is there definitely an auth strategy configured on your route? Seeing come code would be good in order to give more specific advice.

**Comment by Uptown76** [comment]
My bad, apologies, you are correct the auth was turned off for the route. I used another route that didn't use sessions as a template. Copy-paste fail. Thanks.
