### ISSUE TITLE
No CORS options response when vhost is configured

### ISSUE THREAD

**Issue by robinvdvleuten** [hapijs/hapi#2892]
If I configure a vhost for any route, the CORS options requests results in a 404 response. 

Can be reproduced with the following example;
```
var Hapi = require('hapi');

var server = new Hapi.Server();
server.connection({ port: 3000 });

server.route({
    method: 'GET',
    path: '/',
    vhost: 'example.com',
    handler: function (request, reply) {
        reply('Hello, world!');
    },
    config: {
        cors: true
    }
});

server.inject({ method: 'OPTIONS', url: '/', headers: { origin: 'http://github.com/', 'access-control-request-method': 'GET' } }, (res) => {

    // Results in a 404...
    console.log(res.statusCode);
});
```

If you remove the vhost, the response returns 200 as normal.

**Comment by devinivy** [comment]
Is it possible that you need to hint at the host (in the `url` or with a header) when doing an injection to any route on a vhost?

**Comment by robinvdvleuten** [comment]
In the testcase it's correct but it still doesn't work for a "real" request.

**Comment by robinvdvleuten** [comment]
Maybe it has something to do with that my app uses a glue manifest

**Comment by robinvdvleuten** [comment]
Ok I cannot reproduce it with Hapi itself, it occurs when I run my app through glue. I open an issue in that repo.
