### ISSUE TITLE
Missing 'Access-Control-Allow-Headers' in CORS for 'OPTIONS' method

### ISSUE THREAD

**Issue by njl07** [hapijs/hapi#2893]
Hello,

We think some code are missing in `lib/cors.js` for the method `exports.headers` at line 141.

If we add this code inside:

```javascript
if (settings._headersString) {
    response._header('access-control-allow-headers', settings._headersString, { append: true });
}
```

header `Access-Control-Allow-Headers` is set correctly but without it, no header is in the response.

Can you check it and validate the issue?

Thanks in advance,

Best regards.

**Comment by mtharrison** [comment]
That header is set [here](https://github.com/hapijs/hapi/blob/master/lib/cors.js#L128), only in response to a [preflight request](http://www.w3.org/TR/cors/#access-control-allow-headers-response-header).

**Comment by njl07** [comment]
Sorry but your link expose a code that is not in `npm` because my issue is for this [code](https://github.com/hapijs/hapi/blob/master/lib/cors.js#L141) and all your code is not inside.

I don't understand why code is different but it's a problem.

Thanks.

**Comment by hueniverse** [comment]
Access-Control-Allow-Headers should not be set when sending a non-OPTIONS response.

**Comment by njl07** [comment]
I'm agree with you but in `OPTIONS` method, header is not set, code doesn't enter in method and goes out [here](https://github.com/hapijs/hapi/blob/master/lib/cors.js#L61)

I think error is here:

```javascript
if (route.method === 'options' || !route.settings.cors) {
    return;
}
```

And If this is this method which must set header, so you must change test to:
```javascript
if (route.method !== 'options' || !route.settings.cors) {
    return;
}
```

Sorry for my mistake but I think this update is OK.

Check please I'm sure that I'm saying or explain me how to do.

Thanks

**Comment by njl07** [comment]
My problem is solved I had `cors` config in server connection and not in each route.
