### ISSUE TITLE
CORS  headers to include 'Origin'

### ISSUE THREAD

**Issue by nettaru** [hapijs/hapi#2894]
Safari is sending 'Origin' in its headers, and therefor is denied by hapi, which makes the OPTIONS request to fail and return 404:
![screen shot 2015-11-02 at 15 46 10](https://cloud.githubusercontent.com/assets/1736657/10884706/c6a2a7a8-8179-11e5-9fe7-def0d38f6ad4.png)

need to add 'Origin' to the allowed headers to fix the issue:
https://github.com/hapijs/hapi/blob/master/lib/defaults.js#L86

**Comment by mtharrison** [comment]
You're making a cross origin request there. Have you enabled CORS on your /token route?

**Comment by nettaru** [comment]
yes. it's set to true on all the routes in the server configuration like so
```
server: {
    port: 3000
    router: {
      stripTrailingSlash: true
    }
    routes: {
      cors: true
    }
  }
```

**Comment by mtharrison** [comment]
Is that a Glue manifest? Are you using the latest versions of everything? The `routes` option is supposed to sit under a `connections` object:

```javascript
var manifest = {
    server: {
        connections: {
            routes: {
                cors: true
            }
        }
    },
    connections: [
        ...
    ],
    plugins: [
        ...   
    ]
};
```

**Comment by nettaru** [comment]
not using Glue. The object above is my serverConfig object, and i'm using it like so in my app.js: `server.connection(serverConfig)`.

I'm using hapi 11.0.2 because I'm getting the following error for 11.0.3:
![screen shot 2015-11-02 at 16 37 48](https://cloud.githubusercontent.com/assets/1736657/10885818/79e254f8-817f-11e5-8997-541b8f9bbe24.png)

**Comment by devinivy** [comment]
hapi v10 and v11 are meant to be used with node v4, which is probably the issue you've run into above!  Up until 11.0.3 hapi worked on node v0.10 essentially by coincidence.

I'm curious if you're able to verify your cors issue using curl or a similar client, by checking to see that the origin header is the only difference for you between a working cors request and a failing cors request.  Does adding `'origin'` to `cors.additionalHeaders` fix your issue?

**Comment by darsee** [comment]
> Does adding 'origin' to cors.additionalHeaders fix your issue?

It seems to fix the issue for me.

**Comment by nettaru** [comment]
@devinivy thanks, updating node did help the terminal issue.
As for the second question - it does fix the issue. when i do the same request from chrome there is no problem since the header is different (includes only access and content-type):
![screen shot 2015-11-02 at 17 12 50](https://cloud.githubusercontent.com/assets/1736657/10886849/5c8017d8-8184-11e5-9277-f91c1088674e.png)

**Comment by mtharrison** [comment]
This looks like a bug indeed then. Here's a [minmal example](https://gist.github.com/mtharrison/e6ba31bdfbbb4a90d5df) to confirm the issue. Look like `settings._headers` needs to include `origin` to keep safari happy.

**Comment by primitive-type** [comment]
I can confirm that the `origin` workaround works for me as well.

**Comment by nettaru** [comment]
ill create a PR

**Comment by nettaru** [comment]
@mtharrison @devinivy I've created the fixing PR here: https://github.com/hapijs/hapi/pull/2895

**Comment by hueniverse** [comment]
I am not sure if this is enough but can you please test master? It will implicitly allow Origin but will not include it in the response. I don't have Safari to test it out. If you can confirm master works, I'll publish.

**Comment by mtharrison** [comment]
My example above works with master now.

**Comment by nettaru** [comment]
@hueniverse the requests works now with the hapi upgrade. thanks!

**Comment by pabx06** [comment]
hello helps needed.
i have this strange behaviours: request WORKS but preflight requestion the ones with OPTIONS method does not

this a screen-cap of the problem.
since chrome is sending pre-flight request before the actual request.

![hapi-options](https://cloud.githubusercontent.com/assets/4013370/23618506/cdded750-0290-11e7-82ad-52f5630f25ff.png)

**Comment by Marsup** [comment]
Which hapi version ?

**Comment by pabx06** [comment]
problem solved the insomnia was stripping out the Origin flag sometimes. what a pain . then tweked out the hapi conf then worked. thanks Marsup.

i added a route with option that print the headers received. wireshark unable to listen to loopback :(

by the way i am using hapi@16.1.0
