### ISSUE TITLE
backport CORS issues to 9.x branch?

### ISSUE THREAD

**Issue by pdehaan** [hapijs/hapi#2896]
We're still using Hapi@9, but I recently noticed that we're getting the following warning/error from **nsp** due to a CORS issue apparently in versions <11:

| &nbsp; | Incorrect handling of CORS preflight request headers
|----|----|
| Name | hapi
| Installed | 9.3.1
| Vulnerable | <11.0.0
| Patched | >=11.0.0
| Path | able > hapi
| More Info | https://nodesecurity.io/advisories/45

Are there any plans to backport the CORS fixes to hapi@9 or hapi-lts branch? /cc @nlf

**Comment by hueniverse** [comment]
No. The 9.x implementation is reasonable and as long as you don't use per-route settings should be fine. If you have a specific issue, open a new one.
