### ISSUE TITLE
Update hapijs/heavy to 4.0.0 from 3.0.1

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#2911]

**Comment by ljtang2009** [comment]
来自 魅族 MX4

-------- 原始邮件 --------
发件人：Eran Hammer <notifications@github.com>
时间：周二 11月3日 15:08
收件人：hapijs/hapi <hapi@noreply.github.com>
主题：[hapi] Update hapijs/heavy to 4.0.0 from 3.0.1 (#2911)

>null
