### ISSUE TITLE
Use greenkeeper.io to manage versions of the dependencies

### ISSUE THREAD

**Issue by stojanovic** [hapijs/hapi#2924]
Use [greenkeeper.io](http://greenkeeper.io) to manage versions of the dependencies  and update them automatically, so you don't need to think about this again:
<img width="491" alt="dependencies" src="https://cloud.githubusercontent.com/assets/613478/10903597/be720564-820b-11e5-97cf-9f4dabd689a3.png">

**Comment by hueniverse** [comment]
This is done manually on purpose.
