### ISSUE TITLE
How do I use mysql on hapi?

### ISSUE THREAD

**Issue by jonahzheng** [hapijs/hapi#2932]
I want to use mysql on hapi, because In my system, other applications use the mysql.
very thankful

**Comment by jonahzheng** [comment]
o,i know, use waterline,
https://github.com/balderdashy/waterline

**Comment by devinivy** [comment]
I wrote a waterline plugin for hapi that might be useful to you: https://github.com/devinivy/dogwater

You'll want to use the sails-mysql adapter: https://github.com/balderdashy/sails-mysql

**Comment by AdriVanHoudt** [comment]
shameless self plug https://github.com/Salesflare/hapi-plugin-mysql if you do not need/want a full orm ;)

**Comment by Marsup** [comment]
This is the kind of discussion that should really go in [hapijs/discuss](https://github.com/hapijs/discuss/).

**Comment by jonahzheng** [comment]
@AdriVanHoudt @devinivy  thank you very much,I try it
@Marsup ok
