### ISSUE TITLE
Default cors configuration for routes does not seem to be respected.

### ISSUE THREAD

**Issue by zacharyclaysmith** [hapijs/hapi#2933]
__Using hapi v11.1.0 (though this was also occurring in earlier versions of hapi 11.*)__

I'm setting up my server as such:

```
server.connection({
    host: process.env.PORT ? undefined : '127.0.0.1',
    port: process.env.PORT || 8081,
    routes: {
        cors: true
    }
});
```
After much trial and error (hours and hours), it seems that only the cors configurations on individual route definitions are respected, and that the default cors configuration set here is completely ignored.

OR there's some small issue with how I've defined the default cors configuration, though I've scoured the internet for pretty much every iteration.

**Comment by hueniverse** [comment]
See: https://github.com/hapijs/hapi/blob/master/test/cors.js#L44-L60

Unless you can provide an example I can use to reproduce this, I don't see an issue.

**Comment by devinivy** [comment]
Does your setup look comparable to this test? https://github.com/hapijs/hapi/blob/5671a5796b4992c7cadb4ac6d2fa504a690db46b/test/cors.js#L44-L60

**Comment by zacharyclaysmith** [comment]
I think it was user error. I had `cors:true` set on the individual routes (part of me debugging it earlier). I had mindlessly assumed that the cors routes defaults would still be applied, but `cors:true` apparently resets it to the hapi cors defaults.

Thanks for the quick replies :).
