### ISSUE TITLE
Request Method Change Based on Hidden Form Field

### ISSUE THREAD

**Issue by 58bits** [hapijs/hapi#2934]
Is it possible in Hapi to create a plugin that would change the request method, based on a hidden form field?

i.e. `<input name="_method" type="hidden" value="patch" />`

The only point in the request lifecycle where the request method can be changed, is in the 'onRequest' extension point, although if I'm not mistake, since no route has been matched yet, the request stream has yet to be processed - meaning there's no payload information.

The raw Node.js request object is available, but Hapi docs strongly advise against accessing this - and I'm not exactly sure what would happen here if the entire pipeline was changed to process the stream at this point.

Thoughts? Can this be done another way? And tips or suggestions much appreciated. Would be glad to take a stab at this.

**Comment by bboysathish** [comment]
There is an api in Hapi.. Check is this what you are looking forhttps://github.com/hapijs/hapi/blob/master/API.md#requestsetmethodmethod

**Comment by hueniverse** [comment]
You are correct. The only place you can change the method is in onRequest and at that point you cannot access the payload. This sounds like poor system design, overriding the method in the payload. It violates multiple HTTP principals.

**Comment by 58bits** [comment]
Hi @hueniverse - thanks for the reply, and understood. The idea, which is implemented elsewhere (Rails for example) allows a unified set of endpoints for the API. And since browsers can only POST, it solves this by correctly setting the method, (PUT, PATCH, DELETE), before resolving the route and handler. 

It's not an issue of course with XHR requests, which can set any verb/method, but for 'regular' form submissions, it's a nice way to send the request to the correct endpoint.

**Comment by Marsup** [comment]
You could probably use server.inject once the request is fully parsed but that's still poor design.

**Comment by 58bits** [comment]
This is how it's done in [Express/Sails](https://github.com/expressjs/method-override) etc.

This is how it's done in [Rails](http://guides.rubyonrails.org/form_helpers.html#how-do-forms-with-patch-put-or-delete-methods-work-questionmark)

**Comment by Marsup** [comment]
Just because they do it doesn't it should be done. The world kind of moved on from auto submitted forms, maybe you should too, unless you have a constraint that requires that.

**Comment by hueniverse** [comment]
Also it's more commonly done using a query parameter than payload. And no, it's no longer a valid use case. Its a bad hack that people should stop using.

**Comment by 58bits** [comment]
I wouldn't use that logic either. However, there's no law that says a Web form submission must be XHR in order to support all http verbs. And so I thought the hidden field option was an eloquent solution to the problem of browsers only supporting POST natively. It's really not that big a deal, and just means that routes have to be decorated to include both ['POST', 'DELETE'], to support a regular browser form submission, and an XHR/API request. I would have liked to have had very clean route definitions, that match our api spec exactly. I only mentioned that it was being done elsewhere, to give pause for though - and to wonder if there might in fact be a valid use case here.

**Comment by 58bits** [comment]
@hueniverse I hear what you're saying about the use case, and your view on the matter as a whole, and I'd like to know more. But before that, I'd also like to ask if this is something that _could_ in theory be made to work? Or would it have a big impact on the current request pipeline? Also out of curiosity, where is the request stream processed in hapi - when does payload get populated? I'm only asking because the more I read Hapi code, the more I learn, which makes working with the framework all the more fun.

**Comment by 58bits** [comment]
@hueniverse I may have read that a bit too quickly. Are you saying that it _can_ be done via querystring at onRequest?

**Comment by 58bits** [comment]
Setting the method at `onRequest` via query string `method=put` - works fine.  Although non-restful  requests in [Crumb](https://github.com/hapijs/crumb) would need to be patched as follows: https://github.com/58bits/crumb/blob/master/lib/index.js#L95

Thought experiment complete. @hueniverse @Marsup @bboysathish  - very grateful for the replies.

@hueniverse if you have the time, I'd still be very interested to know why this is a bad idea ;-)

**Comment by hueniverse** [comment]
It's a bad idea for many reason. When you do this you are basically bypassing many protections and semantics provides by HTTP. It's a hack put in when you could not properly send HTTP requests. That's not the case anymore.

**Comment by 58bits** [comment]
So I have a stubborn streak, a use case for non-XHR forms, and now a unified set of routes - https://github.com/58bits/hapi-method-change (when I have time I'll write some proper tests).
