### ISSUE TITLE
docs: Reply.view() is undocumented

### ISSUE THREAD

**Issue by bboysathish** [hapijs/hapi#2935]
I don't see the `reply.view` behaviour in API.md.

**Comment by gergoerdosi** [comment]
It's part of the vision module:

https://github.com/hapijs/vision/blob/master/API.md#replyviewtemplate-context-options

**Comment by bboysathish** [comment]
@gergoerdosi  Oops! My Bad.. Forgot Vision is not part of Hapi Core. Thanks.
