### ISSUE TITLE
server.views is not a function although vision is registered

### ISSUE THREAD

**Issue by KeKs0r** [hapijs/hapi#2938]
I have a plugin that registers a route with a view:

```javascript
    server.register({
            register: require('vision'),
            once: true
        },
        function (err) {
            if (err) {
                server.log(['user-basic', 'vision', 'error'], err);
            } else {

                // Normal HTML non API Views
                server.views({
                    engines: {
                        html: require('handlebars')
                    },
                    path: Path.join(__dirname, 'templates')
                });

                // Non Api Routes
                server.route(require('./routes/resetPassword'));
            }
            next(err);
        });
```

But event though it is wrapped into the vision registration, I still get sometimes the error message that `server.views is not a function`

**Comment by devinivy** [comment]
What version of hapi are you on?  Possibly related to https://github.com/hapijs/hapi/issues/2727, which was a bug fixed in v9.0.4.

**Comment by KeKs0r** [comment]
I am using Hapi 11.0.2, which does not necessary mean that it is nor a similar bug that you described. I also see it only ocassionally, so somehow plugin loading order has an impact on it.

**Comment by hueniverse** [comment]
What version of vision? Can you provide an example that demonstrates it (even if inconsistently)?

**Comment by KeKs0r** [comment]
The problem is, that it is my whole app. So I am not sure If I could reproduce it in a small app. And it barely happens in production, but quite often during tests (since I restart the server for a all my test runs around 80 times...)

Its the Vision 3.0.0 .

**Comment by hueniverse** [comment]
I really can't help without a way to reproduce this.

**Comment by hueniverse** [comment]
If you can help reproduce this, I'll reopen.

**Comment by beiping** [comment]
I get the same error. 

package.json as below:

{
  "name": "hapijs.com",
  "version": "1.0.0",
  "description": "hapijs.com",
  "main": "server.js",
  "dependencies": {
    "async": "1.x.x",
    "boom": "^3.x.x",
    "catbox-memory": "1.x.x",
    "catbox-redis": "1.x.x",
    "getconfig": "2.x.x",
    "good": "6.x.x",
    "good-console": "5.x.x",
    "hapi": "^13.x.x",
    "hoek": "3.x.x",
    "jade": "^1.11.x",
    "npm": "^3.8.9",
    "semver": "5.x.x",
    "wreck": "6.x.x",
    "npm":"^3.8.9"
  },
  "scripts": {
    "build": "make",
    "start": "node server.js",
    "lint:tutorials": "./node_modules/.bin/eslint --ext .md lib/tutorials"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/hapijs/hapijs.com.git"
  },
  "author": "&yet <team@andyet.net>",
  "license": "BSD-3-Clause",
  "bugs": {
    "url": "https://github.com/hapijs/hapijs.com/issues"
  },
  "homepage": "https://github.com/hapijs/hapijs.com",
  "devDependencies": {
    "building-static-server": "3.x.x",
    "eslint": "1.0.x",
    "eslint-config-hapi": "1.x.x",
    "eslint-plugin-markdown": ">=1.0.0-beta.1 <2.0.0",
    "glob-cli": "1.x.x",
    "stylus": "0.52.x",
    "uglify-js": "2.x.x"
  },
  "peerDependencies": {
    "hapi": ">= 8"
  }
}

console log:

Super-Home:hapijs.com-master leolee$ npm start

> hapijs.com@1.0.0 start /Users/leolee/Downloads/hapijs.com-master
> node server.js

/Users/leolee/Downloads/hapijs.com-master/server.js:21
server.views({
       ^

TypeError: server.views is not a function
    at Object.<anonymous> (/Users/leolee/Downloads/hapijs.com-master/server.js:21:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! hapijs.com@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hapijs.com@1.0.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the hapijs.com package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hapijs.com
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls hapijs.com
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/leolee/Downloads/hapijs.com-master/npm-debug.log

**Comment by gergoerdosi** [comment]
@beiping: You need to add `vision` to `dependencies` and you need to register it with `server.register()`.

**Comment by eosimosu** [comment]
`vision` plugin must be registered first, before accessing the `server.views` method.

**Comment by anuraggupta816** [comment]
i am facing same issues in hapi like view is not function 
node version v10.13.1
hapi version 18.1.0
