### ISSUE TITLE
cors allow-headers issue

### ISSUE THREAD

**Issue by agdolla** [hapijs/hapi#2939]
upgraded to latest hapi: 11.1.0

cors enabled:
server.connection({ port: process.env.PORT || 3000, routes: { cors: true } });

curl -X OPTIONS -v -H 'Origin: http://localhost:8080' -H 'Access-Control-Request-Method: POST' http://localhost:3000/v1/comments?pageid=4
and
curl -X OPTIONS -v -H 'Origin: http://localhost:8080' -H 'Access-Control-Request-Method: POST' -H 'Access-Control-Request-Headers: accept, content-type' http://localhost:3000/v1/comments?pageid=4

gives:
access-control-allow-headers: Accept,Authorization,Content-Type,If-None-Match

curl -X OPTIONS -v -H 'Origin: http://localhost:8080' -H 'Access-Control-Request-Method: POST' -H 'Access-Control-Request-Headers: accept, accept-language, content-type' http://localhost:3000/v1/comments?pageid=4

access-control-allow-headers is missing from the answer

is this intentional ?

**Comment by antony** [comment]
I am noticing the same issue since 11.1.0 from 10.0.0.

The header only appears to be missing from an OPTIONS request.

Since this seems to break CORS, I can't imagine this is intentional.

**Comment by hueniverse** [comment]
'accept-language' is not in the default list.

**Comment by agdolla** [comment]
I know that accept-language is not in the list
I'd expect to get back the allowed headers, so accept and content-type
and not get back accept-language

**Comment by hueniverse** [comment]
Nope. That's not how CORS works. If there is a mismatch, you get nothing.

**Comment by agdolla** [comment]
ok, thanks, sorry for the noise

**Comment by hueniverse** [comment]
No worries. This is what issues are for.
