### ISSUE TITLE
Route option route.config.ext not allowed

### ISSUE THREAD

**Issue by owenscott** [hapijs/hapi#2941]
In the [documentation](http://hapijs.com/api#route-options) for 11.0.1 the route config option `ext` is allowed. However, including the `ext` option with a route throws an error ("ext" is not allowed). Looking at the route config documentation and `lib/schema.js`, most other route options from the documentation appear in `internals.routeBase` but `ext` is not present.

I am just wondering if this is a documentation issue or if I am misinterpreting the documentation?

For reference, below is the route which caused the error:

    {
      path: endpointOptions.documentPath,
      method: 'PUT',
      handler: handlers.updateDocument,
      config: extendDefaultConfig({
        description: `Updates a document in the ${endpointOptions.collectionName} collection.`,
        payload: {
          allow: 'application/json'
        },
        validate: {
          payload: Joi.object().required().keys(putSchema),
          params: Joi.object().required().keys(idParamSchema)
        },
        ext: {
          onPreHandler: function(request, reply) {
            console.log(request.payload);
            reply.continue();
          }
        }
      })
    },

**Comment by hueniverse** [comment]
This has been allowed since 10.4.0. Specifically in 11.0.1:
https://github.com/hapijs/hapi/blob/v11.0.1/lib/schema.js#L91
https://github.com/hapijs/hapi/blob/v11.0.1/test/route.js#L591

What does `extendDefaultConfig()` do?

**Comment by owenscott** [comment]
Ok, i'm officially "that person". Older project and we're on Hapi v10, not v11. Thanks for taking the time to look into this and really sorry for not triple-checking things on my end before posting an issue.

**Comment by nlf** [comment]
No need to apologize :) glad you found the problem!
