### ISSUE TITLE
Response schema across all routes

### ISSUE THREAD

**Issue by toboid** [hapijs/hapi#2947]
I would like to be able to define a schema for error responses across all routes in my application so that I can ensure consistent responses for things like http 400 or 500 errors. Is there a way to specify this once at the server level so that I don't have to repeat it in every route?

**Comment by devinivy** [comment]
Yes– when you create a new server and pass it options, `options.connections.routes` can be used to specify default route options across all connections on the server.  You can also do this at the connection-level when calling `server.connection(options)` with `options.routes`.

**Comment by toboid** [comment]
Excellent, thanks that's exactly what I was looking for just couldn't find it in the docs.
