### ISSUE TITLE
How to customize joi validation for multiple version sent through accept header

### ISSUE THREAD

**Issue by brahamshakti** [hapijs/hapi#2948]
Hi I want to version my api. The nice way to send version in accept header like

    accept: application/vnd.myapp.version.v1+json

and I need to customize my joi validation on basis of version 
 
    validate: {
         payload: {
              name: Joi.string().regex(/^[a-zA-Z ]+$/).trim().min(2).required()
         }
    }
     
Now in my v2 version I would like to validate email as well but v1 version should remain affected

    validate: {
         payload: {
              name: Joi.string().regex(/^[a-zA-Z ]+$/).trim().min(2).required(),
              email: Joi.string().email().required(),
         }
     }

Is there any way to do this like checking version header before applying joi validation.

**Comment by bboysathish** [comment]
IMO, i dunno this can be done in `validate` maybe @Marsup can share his thought , but you can validate it in the handler. 
There is `when` in `joi` (may be if you found a way to combine header and body validation somehow).

**Comment by Marsup** [comment]
Relevant abstract from the api docs :
> validate - request input validation rules for various request components. When using a Joi validation object, the values of the other inputs (i.e. headers, query, params, payload, and auth) are made available under the validation context (accessible in rules as Joi.ref('$query.key')). Note that validation is performed in order (i.e. headers, params, query, payload) and if type casting is used (converting a string to number), the value of inputs not yet validated will reflect the raw, unvalidated and unmodified values.

Use that with joi alternatives.
