### ISSUE TITLE
Access-Control-Expose-Headers response header duplicate values 

### ISSUE THREAD

**Issue by craigbeck** [hapijs/hapi#2950]
- Hapi v11.1.1
- making CORS request failing in Chrom, Safari, succeeds in Firefox
- notice duplicate values in `Access-Control-Expose-Headers` response header

```
access-control-expose-headers: WWW-Authenticate,Server-Authorization,WWW-Authenticate,Server-Authorization
```

Header gets set in [cors.js line 140](https://github.com/hapijs/hapi/blob/3bf38746f7185e008aaf8e3950d6023ae2a16b3c/lib/cors.js#L139-L141) and get appended to in [cors.js line 168](https://github.com/hapijs/hapi/blob/3bf38746f7185e008aaf8e3950d6023ae2a16b3c/lib/cors.js#L167-L169)

**Comment by craigbeck** [comment]
I have a failing test.

It looks like with option of `cors: true` line 140 doesn't get hit, so line 168 sets the correct values. When using non-default CORS configuratoin, line 140 and line 160 get executed and the header values get duplicated.

**Comment by craigbeck** [comment]
I'm unclear as to a fix or what exactly are the conditions for _both_  lines 140 and 168 to get executed. The first couple of tests in #2953 fail but don't double-append (nothing is appended). I added an assertion to 'matches allowed headers (Origin explicit)' test that executes both lines that shows the issue.

**Comment by hueniverse** [comment]
The three new tests you added are not necessary. The two that fail are because your config and origin do not match (missing tailing `/` in the config). The last change is the actual problem and I'll fix it shortly.
