### ISSUE TITLE
The syle guide is somewhat different to the eslint config

### ISSUE THREAD

**Issue by SteveALee** [hapijs/hapi#2954]
In particular you are now requiring ES6 features like let/const not mentioned in the [style guide](https://github.com/hapijs/contrib/blob/master/Style.md).

Very minor

**Comment by cjihrig** [comment]
There is a PR to update the style guide (https://github.com/hapijs/contrib/pull/59), it just hasn't been merged yet.

**Comment by SteveALee** [comment]
Great. One of the best styleguides as far as I'm concerned.
