### ISSUE TITLE
Trailing Slash changes path?

### ISSUE THREAD

**Issue by House3272** [hapijs/hapi#2955]
a route of `/one/` is apparently different than `/one`?
I came across [this](http://stackoverflow.com/a/16445016/1543640) but I'm not really sure I understand it right.

The index.html that is being served at `/one/` depends on css and js files in the same folder. So I have them as just `href="main.css"` in the html header.
`path: '/one/'` works while `stripTrailingSlash` is set to false.
`path: '/one'` however, sends the css and js file requests to just `/` instead of `/one/`
With `stripTrailingSlash` turned on, it says I can't have a trailing slashes in my path definitions, but the same issue still arises from `path: '/one'`.

I'm not sure what the proper etiquette for trailing slashes are, but both seem to be used by popular websites so I want to know how to do both.
Thanks!

**Comment by vdeturckheim** [comment]
Hi,

You can take a look at #2605, #1904 and #1576.
Also it seems feasible through https://github.com/hapijs/hapi/blob/master/API.md#new-serveroptions with `stripTrailingSlash` option.

**Comment by hueniverse** [comment]
Use hapijs/discuss
