### ISSUE TITLE
Official TypeScript d.ts support

### ISSUE THREAD

**Issue by Think7** [hapijs/hapi#2958]
Are there any plans to provide an OFFICIAL TypeScript d.ts file for the most recent version of the Hapi framework?

TypeScript:
http://www.typescriptlang.org/

DefinitelyTyped
https://github.com/DefinitelyTyped/DefinitelyTyped

Someone aslready asked this question here but there was no official response: https://github.com/hapijs/hapi/issues/1080

Would absolutely pay to fund this effort.

**Comment by AJamesPhillips** [comment]
@Think7 you still interested in funding this?  I'm debating typing v16.1

**Comment by atrauzzi** [comment]
Better to do 17 now :)

**Comment by Think7** [comment]
@AJamesPhillips Unfortunately not. :/ I've given up on TypeScript for now and ended up writing the authentication server in C++. Thats all i was using Hapi for anyway.

**Comment by AJamesPhillips** [comment]
No worries.  I ended up submitting some PRs including this monster for v16 typings https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16065  I hope the C++ auth server progressed smoothly and quickly.
