### ISSUE TITLE
I want to set object in cookies without encoding format ??

### ISSUE THREAD

**Issue by AP25** [hapijs/hapi#2959]
Hi,

I want to set object in cookies without encoding format is it possible to do so ??
and i want to redirect to another page e.g login.html but i unable to do it.

For that i am using 
reply.file('login.html').state('MyInfo','{userName : aap , pwd : aap}',{
    ttl: null,
    isSecure: false,
    isHttpOnly: false,
    encoding: 'base64json',
    clearInvalid: false, // remove invalid cookies
    strictHeader: true // don't allow violations of RFC 6265
});

Its setting cookies in encoding format.After making encoding value as none i got error as invalid cookie.So how to do it??

Thanks in advance

**Comment by hueniverse** [comment]
Cookies are strings. You can't set it to an object without encoding it to a string somehow.

**Comment by AP25** [comment]
Thanks hueniverse!!
But i am storing object in stringy format.Can i store it without encoding?? Means without base64 format i want to store the cookies is it possible to do so ??

**Comment by hueniverse** [comment]
If you pass a string value you can set encoding to none.
