### ISSUE TITLE
request.connection.server.methods["methodName"] is not caching with catbox-redis

### ISSUE THREAD

**Issue by J0NNYZER0** [hapijs/hapi#2960]
Hi All,
I am trying to use cacheing with catbox and redis. My routes and handlers are both seperated into modules. I don't have access to a server object so I further broke out my methods into a module which I register and pass in the server options and next. See the following:

```js
"use strict";

const Db = require("./../../db/mongodb")
    , Promisify = require("./../../promises");

var getCommentById = (id, next) => {
    console.log("hit method")
    var result = Db.Comments.FindById(id);
    return next(null, result);
};

exports.register = (server, options, next) => {
    
    server.method("getCommentById", getCommentById, {
        cache: {
            cache: "redisCache"
            , expiresIn: 20 * 1000
            , generateTimeout: 100            
        }
    });
    
    console.log("Set caches");
    
    next();
};

exports.register.attributes = {
    name: "CacheKeys"
    , version: "1.0.0"
};
```
In my handler I am able to call the method but it is not getting cached and always executes the full request. See the following:
```js
module.exports = {
GetById: (request, reply) => {
            console.log(request.connection.server.methods["getCommentById"].stats)
            request.connection.server.methods.getCommentById(request.params.id
            , (err, result) => {
                if (err) throw err;
                
                reply(result);
            });
        }
}
```
How can I cache this method?

**Comment by J0NNYZER0** [comment]
I figured it out and I am successfully caching with cat box and redis

**Comment by J0NNYZER0** [comment]
Btw, if anyone needs help setting the cat box cache with services plz let me know and I will gladly help. It is not exactly straight forward if you go the route of breaking up your API into tiny modules and keep to dry principle. 😺

**Comment by prashaantt** [comment]
@J0NNYZER0 I don't need this immediately, but I will be using catbox in the near future. If you could spare some time, you could perhaps leave the link to a gist here for anybody who's looking. Thanks.
