### ISSUE TITLE
Plugin Creation: decorate vs handler

### ISSUE THREAD

**Issue by AdrieanKhisbe** [hapijs/hapi#2963]
I'm currently building an hapi plugin, taking [chairo](https://github.com/hapijs/chairo) has an example.

I was wondering what was the difference between decorating a `server` with a function,
and calling the `handler` with a function.

```js
server.decorate('server', 'mykey', myFun);
// vs //
server.handler('mykey', myFun);
```

cf: https://github.com/hapijs/chairo/blob/master/lib/index.js#L33-L42

**Comment by johnbrett** [comment]
Best look at the API docs for description of each:

Server decorate: http://hapijs.com/api#serverdecoratetype-property-method-options
Server.handler: http://hapijs.com/api#serverhandlername-method

**Comment by AdrieanKhisbe** [comment]
Thanks for the pointers :)
Was looking in the wrong place

**Comment by Marsup** [comment]
Also discussions like that go to the [hapijs/discuss](https://github.com/hapijs/discuss/) repo.
