### ISSUE TITLE
Bad CORS handling

### ISSUE THREAD

**Issue by diegossilveira** [hapijs/hapi#2964]
Consider the following code that uses Hapi and creates 2 routes:

* a specific GET /foo that enables Hapi CORS handling
* a catch-all methods on / that does not enable Hapi CORS handling 

```javascript
const Hapi = require('hapi')
const server = new Hapi.Server();
server.connection({ port: 8000 });

// Listening GET method with CORS enabled
server.route({
  method: 'GET',
  path: '/foo',
  handler: function (request, reply) {
    return reply({ message: 'With CORS' });
  },
  config: {
    cors: true
  }
});

// Listening all methods
server.route({
  method: '*',
  path: '/',
  handler: function (request, reply) {
    return reply({ message: 'OK' });
  },
  config: {
    cors: false
  }
});

server.start(function () {
  console.log('Server running at:', server.info.uri);
});
```
When I request `http://localhost:8000/` with **OPTIONS** method, it was expected that the result was `{message: "OK"}`, what indeed happens if Hapi CORS handling is disabled on the first GET /foo specific route. But with Hapi CORS handling enabled for the first route, even when Hapi CORS handling disabled for the second one, I get `{"statusCode":404,"error":"Not Found","message":"CORS error: Missing Origin header"}`.

Looks like Hapi inherits CORS config when a single route enables it.

**Comment by mtharrison** [comment]
Once you have a single route that requires CORS, [hapi adds a catch-all OPTIONS route](https://github.com/hapijs/hapi/blob/master/lib/cors.js#L72-L82). That's what you're seeing.

You didn't say why you think this is a problem though.

**Comment by diegossilveira** [comment]
@mtharrison,

I think it's a problem because this should be a per-route config. Sometimes I need a route supports CORS and other routes uses OPTIONS method for something else than CORS.

**Comment by mtharrison** [comment]
What you're saying is possible now. You can still add more specific OPTIONS routes if you need to do something else. They will take precedence over the catch-all route.

**Comment by diegossilveira** [comment]
This really works @mtharrison! I think it's enough for my needs, although a little bit confusing. Don't you think it would be nice if Hapi supported CORS on truly per-route basis?

Thank you for the quick reply!

**Comment by hueniverse** [comment]
@diegossilveira it would be too complicated and not worth the effort. The main issue is that CORS doesn't map to a route (path + method), but just to the path. If you have both GET and POST of a route, there is only going to be one OPTIONS route for both. Things get more complex with wildcards and parameters.
