### ISSUE TITLE
Server.state()

### ISSUE THREAD

**Issue by nikhilkamath08** [hapijs/hapi#2965]
I'm trying to set a configuration and then set the cookie in the handler,but the cookie isn't getting set.

```js
 a.state('demoo', {
    ttl:  null,
    isSecure: true,
    isHttpOnly: true,
    encoding: 'base64json',
    //clearInvalid: false, // remove invalid cookies
    //strictHeader: true // don't allow violations of RFC 6265
});



a.route(
  {
    method: 'GET',
    path: '/',
    config:{
    handler:function(request,reply){
      var session={user : "nik"};
      session.last = Date.now();
      //reply('Hello').state('demoo', { firstVisit: false });
      reply.state('demoo', session);
      return reply({
        message : 'success'
      }).state('demoo', session)
```

**Comment by hueniverse** [comment]
Are you using HTTPS?

**Comment by nikhilkamath08** [comment]
No I'm not using HTTPS.

**Comment by mtharrison** [comment]
Then you need to set `isSecure` to `false`. When it's `true` cookies won't be sent over an insecure connection.

**Comment by nikhilkamath08** [comment]
Hi ,
I tried doing that. But it still isn't setting the cookie . Is there
anything wrong in the code which I wrote. I set is secure to false.

**Comment by hueniverse** [comment]
How do you know it is not getting set? Where are you looking for it? Did you test with curl?
