### ISSUE TITLE
Non Joi object in 'config.validate' of routes

### ISSUE THREAD

**Issue by ozum** [hapijs/hapi#2967]
Hi,

Sorry for long post. As documented, route's `config.validate.xxx` expects a function, `true`, `false` or a Joi validation object. Other validation plugins such as JSON schema validators etc. need to provide a function and options key, or plugin details in route config.

Reading #1039 I would like to write JSON schema validator plugin and let users provide schema in validate section as below:

```js
server.route([{
    method: 'GET',
    path: '/accounts',
    handler: getAccount,
    config: {
        validate: {
            params: { '$schema': '...', properties: { id: { type: 'integer' } } }
        }
    }
}])
```

However it is not possible to write a plugin which would use `config.validate` with an object.

**hapi/lib/route.js line: 260**
```js
internals.compileRule = function (rule) {

    // null, undefined, true - anything allowed
    // false - nothing allowed
    // {...} - ... allowed

    return (rule === false ? Joi.object({}).allow(null)
                           : typeof rule === 'function' ? rule
                                                        : !rule || rule === true ? null                     // false tested earlier
                                                                                 : Joi.compile(rule));
};
```

Providing JSON schema as an object to `config.validate.param`, hapi converts it to Joi object (even it is not a Joi object) which is expected as seen hapi's API docs. As a result you cannot access bare JSON schema even in `onPostAuth`, since it is already converted as below:

```
{ options: {},
  params: 
   { isJoi: true,
     _type: 'object',
     _settings: null,
     _valids: { _set: [] },
     _invalids: { _set: [] },
     _tests: [],
     _refs: [],
     _flags: {},
     _description: null,
     _unit: null,
     _notes: [],
     _tags: [],
     _examples: [],
     _meta: [],
     _inner: 
      { children: [Object],
        renames: [],
        dependencies: [],
        patterns: [] } },
  payload: null,
  headers: null,
  query: null }
```

My question is: How to not to touch `config.validate` object if it is not a valid Joi object?

If this isn't possible yet, I would gladly make a pull request to hapi. However IMHO this also touches Joi.

My backwards compatible suggestion for hapi would be using an imaginative method from Joi.

**hapi/lib/route.js line: 260**
```js
internals.compileRule = function (rule) {

    // null, undefined, true - anything allowed
    // false - nothing allowed
    // {...} - ... allowed

    return (rule === false ? Joi.object({}).allow(null)
//                           : typeof rule === 'function' ? rule
                           : !rule || rule === true ? null                                               // false tested earlier
                                                    : !Joi.isValidJoiObject(rule) ? rule
                                                                                  : Joi.compile(rule));
};
```

**hapi/lib/validation.js line: 130**
```js
//    if (typeof schema !== 'function') {
    if (Joi.isValidJoiObject(schema)) {
        return Joi.validate(request[source], schema, localOptions, postValidate);
    }
```

I can't think of an efficient way for this imaginative `Joi.isValidJoiObject` method. Perhaps @Marsup would suggest.

**Comment by Marsup** [comment]
Unlikely to happen, anything in javascript is a valid joi object. Your best bet is to put your stuff in the plugins part of the route and have your plugin process that.

**Comment by ozum** [comment]
Thank you for fast response @Marsup. I will put my effort to that direction then.

Regards,

**Comment by hueniverse** [comment]
If you want to store some other validation config, just use the `app` config key and put your own validation logic there, then handle it with a plugin.

**Comment by ozum** [comment]
Thanks.
