### ISSUE TITLE
CORS and headers in custom OPTIONS route

### ISSUE THREAD

**Issue by vbardales** [hapijs/hapi#2968]
Hello,

I was wondering if it was possible to define a custom OPTIONS route when using CORS since in the default CORS special route some headers are set (which is normal) but not in cors.headers method (vary: origin in the other side).

Special route headers:
```
access-control-allow-origin
**access-control-allow-methods**
**access-control-allow-headers**
**access-control-max-age**
[access-control-allow-credentials]
[access-control-expose-headers]
```

cors.headers:
```
**vary: origin**
access-control-allow-origin
[access-control-allow-credentials]
[access-control-expose-headers]
```

Thanks!

**Comment by hueniverse** [comment]
That's how CORS suppose to work. The extra headers are only returned in a pre-flight response. What is your issue? What problem are you trying to solve?

**Comment by vbardales** [comment]
I'd like to define my own OPTIONS routes (especially documentation on OPTIONS routes, to determine the options and/or requirements associated with a resource) but I would like that my own OPTIONS routes use Hapi CORS implementation and let the framework set the right CORS headers. I'd also like to use "Range" header, which is a custom header on CORS point of view (so `access-control-allow-headers` is required in the preflight response).

I've created OPTIONS routes on my CORS enabled-server. There was no error messages about route collision (that is normal since OPTIONS is a "_special" route, but this is quite weird to debug). Then, I've requested my API (the GET route associated to my OPTIONS route) and analyzed my preflight request and response to find out that some fields were missing, which made my next request invalid because `access-control-allow-methods` and `access-control-allow-header`, but `access-control-allow-origin` and `access-control-allow-origin` were defined.

I had those missing headers by hand in my route (which is a valid workaround), but it this really what you meant to do? Or can it be taken as a enhancement or bug of HAPI CORS lib ?

(By the way, I love what you did of HAPI, I'm following since 1.0 version and that's my favorite API server. So thanks :))

**Comment by hueniverse** [comment]
I see. I am not going to support this use case for the time being. The CORS support is a packaged deal. You turn it on and hand over control of the OPTIONS method to the framework. If you need to do something else, you need to also take over CORS handling.
