### ISSUE TITLE
Hapi behind an HTTPS offloading loadbalancer: rewrite links?

### ISSUE THREAD

**Issue by tnolet** [hapijs/hapi#2974]
Hi,

I'm running Hapi behind an AWS ELB that takes care of offloading SSL/TLS. This means Hapi only ever sees HTTP traffic. However, when generating links in API responses (think pagination) or pages I get 'http://' prepended. This makes sense, but how can I override this?

**Comment by mtharrison** [comment]
How are you generating links?

**Comment by tnolet** [comment]
@mtharrison I'm using this pagination plugin https://github.com/fknop/hapi-pagination. AFAIK it just takes the request protocol and uses that to create new links. The plugin works great. Here is an example result. It adds a `meta` object and populates it with links to all pages in the API endpoint.
I notice now it also uses the port in the link.  My question should actually be rephrased into "how do I set the canonical name or FQDN for responses"
```json
{
	"meta": {
		"count": 1,
		"totalCount": 43,
		"pageCount": 2,
		"self": "http://api.site.com:3000/customers?page=1&limit=25",
		"previous": null,
		"next": "http://api.site.com:3000/customers?page=2&limit=25",
		"first": "http://api.site.com:3000/customers?page=1&limit=25",
		"last": "http://api.site.com:3000/customers?page=2&limit=25"
	},
	"results": []
}
```

**Comment by devinivy** [comment]
When you generate those links, you'll want to take advantage of the X-Forwarded-Proto header that ELB sets on requests.  Please move this over to the hapijs/discuss repo if you'd like to continue discussion, as this does not seem to be directly related functionality within hapi core.

**Comment by devinivy** [comment]
You might want to move this to hapi-pagination instead, then!  They build the URI from `server.info.uri`, which is probably not exactly what you want (see [here](https://github.com/fknop/hapi-pagination/blob/master/lib/index.js#L20)).

**Comment by tnolet** [comment]
@devinivy Ah thanks. That makes sense yeah. That part should be configurable depending on NODE_ENV. That's when you can check for X-forwarded-for headers and stuff.

**Comment by tnolet** [comment]
For posterity: anyone finding this. I created a pull and it was fixed in the plugin: https://github.com/fknop/hapi-pagination/pull/
