### ISSUE TITLE
Potential issue with gzip compression and  use of h2o2 with streaming api

### ISSUE THREAD

**Issue by skeary-immt** [hapijs/hapi#2975]
Hi,

We've noticed an issue in our environment that was introduced in v11.0.3 by dcd65d6. To be honest we're not 100% sure if this is a a bug in hapi or in our our use of it so have raised this issue for your consideration.

We are using the h2o2 library on a particular route to proxy incoming requests to the [changes REST api](http://docs.couchdb.org/en/1.6.1/api/database/changes.html#changes) method on a CouchDB server. The important thing here is that the changes api method is designed to be used with long polling where the client makes a long running request to the server to get notified of new database changes. In our config CouchDB sends a newline every 10 seconds as a form of heartbeat. What we're noticing is that no data is getting now received by the client (in our case browser) when going through hapi and h2o2. When we globally turn off compression for hapi everything works fine.

I believe the change in dcd65d6 is causing this issue for us because (I assume) the content length is reasonably not being set by CouchDB. Previously this would have prevented the gzip compression from being applied on the proxied responses and now it is not. The gzip compression ultimately seems to be the thing that is preventing the heartbeat data from being sent - at least in a timely fashion.

The specific change that is causing the issue is line 185 in lib/transmit.js:
```
var length = parseInt(response.headers['content-length'], 10); 
```

Is it possible to advise if this is an issue in hapi or expected behaviour?

Thanks,
Simon

**Comment by hueniverse** [comment]
@kanongil ?

**Comment by kanongil** [comment]
I am sure your diagnosis, as to the cause of your problem, is correct.

Given that Hapi is designed to deliver HTTP requests, it makes sense that the default configuration is geared towards such requests. Keeping a request alive is outside this use case, and it makes sense that it can require custom settings to work as expected.

In this case it is unfortunate that CouchDB chose to use the `text/plain` MIME type for the response. A more appropriate MIME type could have avoided this issue.

**Comment by kanongil** [comment]
Note that you can disable compression for a specific response by including a `content-encoding: identity` header.

**Comment by skeary-immt** [comment]
Thanks for the info. That's very helpful! As suggested, sending the ```content-encoding: identity``` header works around the problem.

I logged the headers coming back from CouchDB  in the ```onResponse()``` handler and they are:
```
{
	'transfer-encoding': 'chunked',
	server: 'CouchDB/1.6.1 (Erlang OTP/R16B02)',
	date: 'Wed, 16 Dec 2015 09:29:32 GMT',
	'content-type': 'application/json',
	'cache-control': 'must-revalidate'
}
```
@kanongil - is this what you were expecting for the ```content-type``` header? As a test I also tried overriding the ```Content-Type``` header to ```application/octet-stream``` in the ```onResponse()``` handler. This also seemed to fix the issue but it also looks like this is disabling the gzip compression.. Is there an appropriate mime type that keeps the gzip compression but addresses the issue?

 Thanks again.

**Comment by kanongil** [comment]
There is not way to combine gzip compression with the keep-alive functionality, afaik.

**Comment by skeary-immt** [comment]
Okay, thanks. I think the workaround will work for us and it looks like the change that introduced the problem for us was the correct thing to do. It also seems that to get gzip working with the streaming behaviour is more of an enhancement and I suspect not trivial to do so I'll close this issue.

Thanks for your help!
Simon
