### ISSUE TITLE
Cors config not working 

### ISSUE THREAD

**Issue by safiresh** [hapijs/hapi#2976]
Hi Team, 

Cors wont work for new version hapijs 11.1.2. kindly share the new setup & configuration. i tried lot of ways but no response. always get Cross-Origin Request Blocked. 
we set Authorization in headers

![screen shot 2015-12-16 at 5 28 04 pm](https://cloud.githubusercontent.com/assets/2355624/11840258/6a1c9e58-a41a-11e5-9834-e3e160c1dfdf.png)
  

Server configuration : 
{
            "host": "127.0.0.1",
            "port": 4000,
            routes: {
                cors: true,
                validate: {options: {stripUnknown: true}}
            }
        }

HapiJs Version : v11.1.2
NodeJs : v5.1.1

**Comment by csrl** [comment]
try `cors:{credentials:true}`

**Comment by safiresh** [comment]
Hi  @csrl , 
Thanks for reply. 
Now tried your configuration but still same error there. Cross-Origin Request Blocked :(

**Comment by hueniverse** [comment]
This is not enough information. Need to see the full config from the connections and routes involved as well as example of some curl outputs. Note that there is a bug when mixing both route level and connection level cors config.

**Comment by hueniverse** [comment]
Please try again with v11.1.4
