### ISSUE TITLE
`Server.inject` generate timeouts

### ISSUE THREAD

**Issue by jney** [hapijs/hapi#2977]
I've got some routes which take a lot of time, so i've got this kind of error :

```
Failed tests:

  5) Title of the test :

      Timed out (2000ms) - Some reason here

```

How to remove timeout using `Server.inject()` ?

**Comment by devinivy** [comment]
It appears you're actually hitting lab's default 2sec test timeout.  See the lab docs here: https://github.com/hapijs/lab .  You can run your tests with a different timeout using the `--timeout` flag.
