### ISSUE TITLE
Multiple required authentication strategies for one route

### ISSUE THREAD

**Issue by mattii** [hapijs/hapi#2981]
I have a json-web-token schema for default authentication of protected routes. But for some critical routes (like changing password, user deletion etc.), I would like to add a second layer of protection by verifying a user's password again.

So I wrote a simple authentication schema to verify a users's password and tried to have multiple required authentication steps for one route, defined like this:

``` javascript
config: {
    auth: {
        mode: 'required',
        strategies: ['jwt', 'verify-password'],
    },
    ...
}
```

But unfortunately it seems to skip the verify-password schema, after `jwt` has been passed successfully. After reading some similar named issues here, I see that this is a useful feature, and not a bug. But is there a way to accomplish that pseudo "two-factor" authentication with that `auth` property?

If not, what's the best way to do it?

**Comment by hueniverse** [comment]
You cannot execute multiple auth schemes. It will stop after the first successful one. That's how HTTP auth works. You can setup your second scheme as an onPostAuth extension or pre handler.
