### ISSUE TITLE
Invalid cookie value - cookie has spaces

### ISSUE THREAD

**Issue by danielb2** [hapijs/hapi#2996]
ref #2513 

I came across the issue above with a website I'm migrating that has improperly escaped cookies with spaces in them. When trying to access a hapi server with those cookies, hapi fails with the error

``` json
{"statusCode":400,"error":"Bad Request","message":"Invalid cookie value"}
```

Because it's using legacy code, the cookies are stored on the user client.

Thoughts on how to handle this?

**Comment by hueniverse** [comment]
Did you try turning strict cookie parsing off?

**Comment by danielb2** [comment]
Are you talking about disabling parsing for cookies altogether, or is there one specifically to parse it still, just not in a "strict" way ? The latter I can't find

**Comment by hueniverse** [comment]
https://github.com/hapijs/statehood/blob/master/lib/index.js#L20

**Comment by danielb2** [comment]
I tried this before asking, but looks like I had missed one cookie name. 😓

**Comment by danielb2** [comment]
Oh, and thanks

**Comment by danielb2** [comment]
This came up again in a different context.

I tried using `server.state('SESSIONID', { strictHeader: false });`  however, that fails.

The only thing that worked is setting the config to option to `state: { parse: false }`

I looked at https://github.com/hapijs/hapi/blob/master/lib/connection.js#L78   but it looks like the server.state has an impact here per cookie.

What am I missing this time?  Is it just not possible to configure per cookie?

**Comment by hueniverse** [comment]
How is the cookie invalid?

**Comment by danielb2** [comment]
```javascript
 const headers = {
     Cookie: 'SESSIONID=4/7/2016 18:31:45 PM'
 };
 server.inject({ method: 'GET', url: url, headers: headers }, (res) => {
```

this will cause the error. removing the spaces causes it to work

**Comment by hueniverse** [comment]
Can you open a new issue and PR a test case showing how setting a single cookie config fails?

**Comment by danielb2** [comment]
going to close this either way

**Comment by carraher** [comment]
rather than setting parse:false I have worked around this by setting
```
      "routes":
            "state" : {
              "parse": true,
              "failAction": "ignore"
            }
      }
```

**Comment by carraher** [comment]
rather than setting parse:false I have worked around this by setting
```
      "routes":
            "state" : {
              "parse": true,
              "failAction": "ignore"
            }
      }
```

**Comment by tombh** [comment]
I just want to explain why @carraher's solution above worked for me. I'm using the `hapi-cookie-auth` plugin, which doesn't support the `ignoreErrors: true` option. I was in the situation of upgrading a site that had set, what that plugin would consider, invalid cookies. So I didn't want to create a single `server.state()` line just to ignore the errors on that one bad cookie name. That's why @carraher's more generic approach worked for me. Thanks.
