### ISSUE TITLE
server.ext('onPreResponse', ...) doesn't work when installed inside a plugin register() 

### ISSUE THREAD

**Issue by eyalw** [hapijs/hapi#3003]
For some reason the following code does not work:

```
module.exports = {
  register(server, options, next) {
    server.ext('onPreResponse', (request, reply) => {
      // WE DON'T GET HERE
      reply('2');
    });
    // WE GET HERE
    next();
  }
});
```

cant find any documentation saying you can't use server.ext in a plugin...  help?

**Comment by gergoerdosi** [comment]
That code results in a syntax error.

```
});
 ^

SyntaxError: Unexpected token )
```

If you remove the extra parenthesis, then it throws an other error:

```
    throw new Error(msgs.join(' ') || 'Unknown error');
    ^

Error: Invalid plugin options {}

[1] "attributes" is required
```

Please add a valid code. `onPreResponse()` works as expected with this code:

```js
exports.register = function(server, options, next) {
  server.ext('onPreResponse', (request, reply) => {
    reply('2');
  });

  next();
};

exports.register.attributes = {
  name: 'test'
};
```

**Comment by eyalw** [comment]
common... I was writing a pseudo code obviously, my real code has no syntax error... not a noob here :)

**Comment by eyalw** [comment]
I'll try to check again if I'm mistaken...  but I'm pretty sure something failed for me.
