### ISSUE TITLE
Can not change/remove the "accept-ranges" response header

### ISSUE THREAD

**Issue by jasonswearingen** [hapijs/hapi#3015]
I thought this was a h2o2 proxy issue (see here: https://github.com/hapijs/h2o2/issues/21 ) but I just repro'd this on normal Hapi.

if I have the following route, the ```accept-ranges``` response header is set and I cannot modify it, even if the ```onPreResponse``` ext point.

**Comment by jasonswearingen** [comment]
a fuller repro, the ```accept-ranges:bytes``` response header is always set in the following example.  

```
		server.ext("onPreResponse", function (request, reply) {
			if (request.response != null && request.response.header != null) {
				request.response.header("accept-ranges", "none!!");
			}
			reply.continue();
		});

		server.route({
			method: "GET",
			path: "/api/test",
			handler: (request, reply) => {
				var tmpStr = "asdf";
				for (var i = 0; i < 10; i++) {
					tmpStr += tmpStr;
				}
				var response = reply(tmpStr);
				//response.type("application/pdf");
				response.header("content-encoding", "base64");
				response.header("content-type", "application/pdf");
				response.header("accept-ranges", "none");
			},
		});
```

I need to disable ```accept-ranges``` so that Chrome doesn't spam multiple requests for my api.  (it tries to load 1 page of a pdf at a time)

**Comment by jasonswearingen** [comment]
looks like a bug:  https://github.com/hapijs/hapi/blob/d34f0dec788e283df0c8b0d810798653a2863526/lib/transmit.js#L248

I think that line should check if ```accept-ranges``` is already set, and if not, set it.

**Comment by jasonswearingen** [comment]
FYI, my current workaround is to return status-code ```207``` for non-text GET requests.

**Comment by jasonswearingen** [comment]
My ```statusCode:207``` workaround doesn't work because while chrome load+render of the pdf works, it errors when trying to save the pdf (seems like a chrome bug)

So my new workaround is to force gzip encoding of pdfs, (and back to returning ```statusCode:200```)

I guess in my circumstance that's not bad anyway, I save about 10% in bandwidth this way.

**Comment by kanongil** [comment]
I'd say that it is a bug that it is impossible to _not_ send the `accept-ranges` header.

FYI, you might be able to disable the header by removing the `content-length` header in an `onPreResponse` hook.
