### ISSUE TITLE
Testing routes with plugins loading time

### ISSUE THREAD

**Issue by Nargonath** [hapijs/hapi#3017]
**This is just a question.**

I'm testing the routes of my Hapi API and I had a problem as `server.inject()` would always return 404 NOT FOUND. To correct my problem I added a `before()` to my test to listen on `server.ext('onPreStart')`.

Is event listening the only way to wait for the server to load all plugins/routes? I group my routes as Hapi plugins hence they are loading in the `server.register` function call.

I found this old issue #1492 but I guess `server.pack()` is deprecated as I cannot find it in the 12.0.1 documentation.

Here is the code of my unit test:
```` javascript

'use strict';

var server = require('../../../index.js');
var assert = require('assert');

describe('User module', function() {

  before('Make sure plugins are loaded before loading tests', function(done) {
    server.ext('onPreStart', function() {
      done();
    });
  });

  describe('/users/create [POST]', function() {
    var options = {
      method: 'POST',
      url: '/users/create',
      payload: null
    };

    afterEach(function() {
      options.payload = null;
    });

    it('should return a user with HTTP 200', function() {
      options.payload = {
        email: 'test@gmail.com',
        password: 'iamapassword'
      };

      return server.inject(options)
                    .then(function(res) {
                      assert(res.statusCode, 200, 'has status code == 200');
                    });
    });
  });
});

````

I believe it to be a trivial question but I wonder if it is the best way to do it.

**Comment by devinivy** [comment]
If your tests do not `start(cb)` or `initialize(cb)` the server then yes, you would have to listen for `onPreStart` to guarantee that all plugins have been registered.

**Comment by Nargonath** [comment]
Alright. Thanks for the answer however I start to wonder whether loading the whole server only to test the user module is a wise thing to do. Would creating a new server and only registering the user plugin be better? I would have to mock up my database though.

Sorry if my questions seems trivial but as I'm getting into unit testing I'm not really sure how to test things.

**Comment by arb** [comment]
Generally, plugins are tested in isolation as you've suggested. When you know that all your plugins are well tested, when you compose your server, you generally only need a few smoke tests on the completely configured server.

**Comment by Nargonath** [comment]
Ok nice, thanks. I finally see how I need to tests my code. I didn't see how things could be tested in isolation prior to that. I just get it now, you brigten my day.

**Comment by tenaciousRas** [comment]
I spent a long time tracking this down.  It feels like a workaround because the solution requires boilerplate code.  Is there anything in official/popular docs about waiting for plugins to load when using server.inject in tests?
