### ISSUE TITLE
Allow auth strategies to expose an api

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#3018]

**Comment by J0NNYZER0** [comment]
@hueniverse This sounds interesting, but can you explain it's use case? (Don't know if appropriate space to do so)

**Comment by hueniverse** [comment]
I am using it in scarecrow to expose the internal settings so I can manipulate it in testing. But in general it is similar to how plugins can expose and api but since strategies are really an instance of a plugin definition, it wasn't enough.
