### ISSUE TITLE
Publicize server state

### ISSUE THREAD

**Issue by devinivy** [hapijs/hapi#3024]
Currently the server state (stopped, initializing, initialized, started, invalid, etc.) is placed privately on `server._state`.  I'm requesting that we make this part of the public API.  I realize it might mean some things need to be renamed so as not to conflict with the cookie concept of `state`.  I suppose a plugin could do some of this work if the request wont be fulfilled.

One usage example– perhaps tests would only initialize a server that has not already been initialized.

**Comment by gergoerdosi** [comment]
I ran into this problem too with the exact same use case.

**Comment by devinivy** [comment]
@gergoerdosi a hack to determine if the server is initialized,
```js
const cache = server.cache({ segment: '_is_initialized' });
const isInitialized = () => cache.isReady();
```

This works because caches are made ready during initialization, and hapi always reserves one default in-memory cache.

**Comment by gergoerdosi** [comment]
@devinivy: Thanks. I actually solved this problem with https://github.com/hapijs/hapi/pull/3057, so I don't need the server state anymore. But it might still make sense to make the state public.

**Comment by hueniverse** [comment]
I don't see the need for this.

**Comment by arb** [comment]
@hueniverse can we revisit this? Inside good, I am removing the listeners I add to the `server` object and I have to tear them down by hand when the server stops to prevent these events from firing after the server has stopped. It would be nice to not have to do that and to just check `server.state` or similar and not have to keep track of them all the time.

**Comment by hueniverse** [comment]
Why can't you just listen to the server events?

**Comment by arb** [comment]
The server still emits events when it's stopped though...? Not sure what you're suggesting.

**Comment by devinivy** [comment]
I can't tell if the server is initialized without attempting to initialize the server– I consider this a limitation.  In @arb's case, he'd have to pay attention to multiple server extensions and ensure that those extensions are registered before any calls to start/initialize/stop the server are made.  He really just wants to check in his server event callbacks if the server is in the stopped state, and if so ignore the event.

In my case I would like to be handed a server and tell if it is already initialized/started without having to attempt initialization/starting.

**Comment by hueniverse** [comment]
The problem is that the current server state isn't really that useful because it doesn't tell you about the state of the individual connections. It's more about the state of the cache and some plugin registration. We don't have a clean model for this because we allow adding connections and plugins at any time. For me to expose a useful state, I would have to either do a lot more to keep things consistent (e.g. automatically bring all connections to the current state when new are added, validate new registrations after init), or forbid all this once you are initialized. Neither option is very attractive.

I don't understand the good use case. How is this not what `onPostStop` is for?!

**Comment by arb** [comment]
Is there a guarantee that the hapi server won't emit any further events after `onPostStop`? That's what I'm trying to achieve. Once `onPostStop` happens, I want to do something to ensure no further events are recorded even if they are emitted from hapi. Unless you can point it somewhere that ensure hapi doesn't emit events after it's stopped...

**Comment by hueniverse** [comment]
It will not emit any more **server** events (onPreStart, onPostStart, onPreStop, onPostStop) until you start the server again with another `server.start()` or `server.initialize()`

**Comment by arb** [comment]
What about "request", "request-error", "log", etc... Seems like there isn't anything gating them from still firing after `server.stop()`.

**Comment by hueniverse** [comment]
Those are unrelated. I don't see how it's relevant. Why would they not emit when the server is stopped?!
