### ISSUE TITLE
Validation error message isn't user-friendly or developer-friendly

### ISSUE THREAD

**Issue by bgoldman** [hapijs/hapi#3028]
The response for the below code, when accessing `/hello/a' is:

```javascript
{"statusCode":400,"error":"Bad Request","message":"child \"name\" fails because [\"name\" length must be at least 2 characters long]","validation":{"source":"params","keys":["name"]}}
```

The message is not user-friendly, as we can't display something like that to a user, with square braces and with weird formatting like that. The response in general is not developer-friendly either, because we can't programmatically create our own error message from this, since the reason the validation failed is not available outside of that "English" message.

So I have two questions:

1. How can we customize the error message so it's user-friendly?
2. How can we get enough developer-friendly info in the response to generate our own user-friendly error-message?

If neither of these are possible, can you provide a fix?

```javascript
{
	method: 'GET',
	path: '/hello',
	handler: (request, reply) => {
		reply({
			statusCode: 200,
			message:    'Hello, ' + request.params.name
		});
	},
	validate: {
		params: {
			name: Joi.string().min(2).regex(/^[A-Za-z]+$/)
		}
	}
}
```

**Comment by simon-p-r** [comment]
I would open an issue for [joi](https://github.com/hapijs/joi) as this is the validation library used by hapi.

**Comment by Marsup** [comment]
You should use failAction properties to manipulate joi's errors, which are indeed more complete than this simple string.

**Comment by hueniverse** [comment]
joi provides plenty of ways to customize errors. In addition, you can provide a post validation function and create your own error from the error properties (not the message).

**Comment by bgoldman** [comment]
The problem is that it doesn't appear these messages can be customized with the regular Joi API, since Hapi doesn't expose all of that through the `validate` config option, and/or doesn't document how to do so. How can I customize the errors through the `validate` config option?

**Comment by hueniverse** [comment]
I suggest you move this question to hapijs/discuss.

**Comment by red-0ne** [comment]
@bgoldman we use `failAction` to expose a more structured error format (which is then used client side to generate custom error messages). Everything you need should be located at `error.data.details`

```javascript
...
validate: {
  ...
  failAction: (request, reply, source, error) => {
    error.output.error_details = error.data.details;
    reply(error.output).code(error.output.statusCode);
  }
  ...
}
...
```
