### ISSUE TITLE
How to save reply objects and return them all at once?

### ISSUE THREAD

**Issue by Marcoevich** [hapijs/hapi#3029]
In my first hapi project I am creating teams and teamMembers, all in one action. The teamMember create function creates the team, and replies with a Boom error if something goes wrong.

Immediately after that I create a teamMember (a user), and would like to reply any error in that process as well.

However, i return the reply (a Boom object) in a console.log now, because the reply interface can't be called twice. So the user can never see the error, if any comes up.

Is it possible to somehow save all these replies, and return them all at once to the browser?

**Comment by johnbrett** [comment]
Hi @Marcoevich, the hapi issues repo is used for bugs or issues with hapi itself, your question is better suited to the discussion repo if you would like to open an issue there: https://github.com/hapijs/discuss

**Comment by johnbrett** [comment]
If you do want to collect all the errors, you could just store them in an array and return the array of error objects like below, but this isn't how I'd go about it. The logic here seems a bit strange, why would you want to go on and create a teamMember if the teamCreate failed? Maybe you should just stop and return error there?

````javascript
server.route({
    method: '*',
    path: '/errors',
    handler: function(request, reply) {

        const errors = []; // array to collect errors
        
        createTeam((err, team) => {
            
            if (err) {
                errors.push(err);
            }
            
            createMembers((err, members) => {
                
                if (err) {
                    errors.push(err)
                }
                
                // reply signature is reply(err, response) but when no err returns response
                // so this means if no error will return response, if err returns error, if not returns response
                return reply(errors, 'Sample response here'); 
            });
        });
    }
})
````

**Comment by Marcoevich** [comment]
Hi John,

I have solved my issue now. Instead of creating seperate functions, I have put each new save function in the callback of the previous one, like you did here with createMembers. Now I just return a reply on the first error :)

Thx for your help!
