### ISSUE TITLE
Some request.query param with apices

### ISSUE THREAD

**Issue by furyscript** [hapijs/hapi#3031]
Request.query output debugging:
```
  skip: '0',
  page: '1',
  pageSize: '100',
  'sort[0][field]': 'order',
  'sort[0][dir]': 'asc',
  'filter[logic]': 'and',
  'filter[filters][0][full_text][value]': 'testss'
```
After upgrading my HapiJS to latest version, I have a problem because some key params in `request.query` have apices and app crashes... How can I fix it?

**Comment by hueniverse** [comment]
Read the release notes.

**Comment by furyscript** [comment]
I read it, so how can I fix this problem?

**Comment by furyscript** [comment]
Found sorry :)
