### ISSUE TITLE
Exposing additional response headers CORS

### ISSUE THREAD

**Issue by phoenixbox** [hapijs/hapi#3033]
Hey there, I can't quite figure out how to expose additional headers on my server responses. They seem to be getting stripped.

I added `additionalExposedHeaders: ['authorization']` to my server's cors setup but I dont seem to be getting the `authorization` header back.

Have I configured CORS incorrectly?

```
// Hapi Server
// *** server setup ***
var connectionOptions = {
  host: serverHost,
  port: process.env.PORT || 8000,
  routes: {
    cors: {
      additionalExposedHeaders: ['authorization']
      credentials: true
    }
  }
}
server.connection(connectionOptions);

// Example Auth Route
{ 
    method: ['GET','POST'],
    path: "/auth",
    config: {
      auth: false
    },
    handler: function(request, reply) {
      var session = {foo: bar}
      var token = JWT.sign(session, config.JWT_SECRET);
      reply({text: 'Check Auth Header for your Token'}).header("authorization", token)
    }
}

// Client request
request.post('http://localhost:8000/auth')
             .set({
               'Accept': 'application/json',
               'Content-Type': 'application/json'
             })
             .send({email: email, password: password})
              .end((err, response) => {
                /*
                   Expecting an `authorization` header here
                   response.headers === {
                     content-type: "application/json; charset=utf-8",
                     cache-control: "no-cache"
                   }
               */
              })
```

**Comment by phoenixbox** [comment]
As usual it was a problem with my code :)

**Comment by ignivaravinderrikhi** [comment]
can anyone explain to me difference between additionalHeaders & exposedHeaders???

**Comment by mtharrison** [comment]
`additionalHeaders` - these are additional _request_ headers that you're stating that you allow to be sent in the CORS request.
`additionalExposedHeaders` - these are additional _response_ headers that you're stating should be exposed to JavaScript. These are communicated to the browser the response header `Access-Control-Expose-Headers`

**Comment by ignivaravinderrikhi** [comment]
So if you want to send and receive data using headers you need to use both of them . Right ??

**Comment by kanongil** [comment]
Questions like this does not belong here. You can try [hapijs/discuss](/hapijs/discuss) instead.
