### ISSUE TITLE
API documentation not shown in 13.0

### ISSUE THREAD

**Issue by Nargonath** [hapijs/hapi#3041]
On the website, if the current version selected is 13.0, the API documentation page is empty. I don't know if it's normal or not so I just thought I should post an issue here.

**Comment by hueniverse** [comment]
That's an issue for hapijs/hapi.com and it sometimes take a bit. I don't know what's the issue in this case.

**Comment by AdriVanHoudt** [comment]
It is there now and can indeed take some time, I believe it also only updates once the milestone closes (not sure how the release process goes but if you publish first and then close the milestone it will only update after the milestone is closes on github)

**Comment by Nargonath** [comment]
Alright thanks for the info. Sorry for posting in the wrong repo though.

**Comment by hueniverse** [comment]
No need to be sorry.
