### ISSUE TITLE
Moment - Regular Expression Denial of Service

### ISSUE THREAD

**Issue by jhawlwut** [hapijs/hapi#3042]
In reference to this discussion:
https://github.com/moment/moment/issues/2936

We've included NSP in our build process and with this vulnerability was curious if there was a short-term plan to address this? I've looked around this and the joi repository but couldn't find any open / closed issues addressing this.

**Comment by hueniverse** [comment]
I don't think joi uses the feature with the issue. hapi doesn't use moment at all even through joi. Once moment publishes a new version with the fix, we can publish a new shirnkwrap file so the warning goes away but this is not an actually issue.

**Comment by dresende** [comment]
https://github.com/moment/moment/pull/2939

**Comment by Marsup** [comment]
False warning on NSP's side, even if we used the feature.
Joi is using 2.x.x, which makes it your responsibility to provide a bug-free version (which has been available for quite a while) as I'm not enforcing any specific version.
