### ISSUE TITLE
Mocking request property created via plugin

### ISSUE THREAD

**Issue by alexbeletsky** [hapijs/hapi#3045]
It's a more question, than issue so I apologise in advance.

My problem is that I can't find a reliable way to be able to mock request property, created via a plugin.

There is a plugin, `service.js`:

```js
import Service from './some/service.js';

const service = {
  register(server, options, next) {
    server.ext('onRequest', (request, reply) => {
      request.service = new Service();
      reply.continue();
    });

    return next();
  }
};

service.register.attributes = {
  name: 'service'
};

export default service;
```

Some handlers are accesing it, 

```js
function handler(request, reply) {
   request.service.doSomething();

   // ...
}
```

In my test code, I would like to be able to *mock* that `request.service` during `server.inject` call, ideally without any mocking frameworks like `sinon`, but just being able to set mocked version of `Service` into `request.service`.

I thought I can override the behaviour by injecting [plugins](http://hapijs.com/api#serverinjectoptions-callback), but no luck so far.

**Comment by hueniverse** [comment]
This belongs in hapijs/discuss.

You can try adding an onRequest ext in your test and add the properties to the request object.
