### ISSUE TITLE
Invalid request payload JSON format regardless of content-type (11.0)

### ISSUE THREAD

**Issue by jcollum** [hapijs/hapi#3046]
I'm posting a big (10MB or so) XML file to a HAPI endpoint. It's working fine when I curl to it: 

`curl -H  "Content-Type:text/xml" -d "@./test/full-0914A.xml" http://localhost:7900/convert`

Returns a big JSON object. But when I try to post to it with https://github.com/request/request, I get this error: 

`"{"statusCode":400,"error":"Bad Request","message":"Invalid request payload JSON format"}"`

I am setting the `content-type` options. The content-types that I've tried: 

```
'text/*'
'application/x-www-form-urlencoded'
'application/xml'
```

Here's the code: 

```

var server = new Hapi.Server();

  server.connection({
    host: 'localhost',
    port: appConfig.port,
    routes: {
      cors: true
    }
  });

server.route({
    method: 'POST',
    path: '/convert',
    config: {
      description: "Converts an XML document",
      payload: {
        maxBytes: 1073741824
      }
    },
    handler: function(request, reply) {
      var e, payload, result;
      try { 
        if (!(+request.headers['content-length'] > 0)) {
          logger.error("content length is 0");
          reply('Failed: content-length header must be greater than zero.').code(500);
          return;
        }
        payload = request.payload.toString();
        result = converter.convert(payload); 
        return reply(result).code(200);
      } catch (_error) {
        e = _error;
        logger.error(e);
        return reply(e).code(500);
      }
    }
  });
```

I've been over the docs and I can't see what I'm doing wrong. Is this a bug? Is this fixed/different in a new version?

**Comment by Marsup** [comment]
Since the problem is in the client, we'll need the client code as well.

**Comment by jcollum** [comment]
I think I was structuring my post data incorrectly. I don't have the test code handy though. I'll just close the ticket.
