### ISSUE TITLE
CORS: Access-Control-Request-Method names are matched case-insentitive

### ISSUE THREAD

**Issue by kanongil** [hapijs/hapi#3047]
The spec specifies case-_sensitive_ matching should be used: https://www.w3.org/TR/cors/#resource-preflight-requests

Feel free to close this if you think it is too minor an issue. It was just something I stumbled upon.

**Comment by hueniverse** [comment]
I don't see any security issues with being more flexible here, and I do expect stuff to break if we enforced the spec.
