### ISSUE TITLE
server.method with cache options failing

### ISSUE THREAD

**Issue by rainabba** [hapijs/hapi#3048]
Using Hapi 13.0.0. Every combination of caching options I try has the same result. My method is never run. If I remove the caching options, everything works as expected.

**server.methods.myMethod is undefined**
`server.method('myMethod', myMethod, { cache: { expiresIn: 5000, generateTimeout: 500 } } );`

**My method runs as expected**
`server.method('myMethod', myMethod, { } );`

**My method never runs** (I've somehow create a situation where my unhandled exceptions aren't visible so an unhandled exception could be occurring here)
`server.method('myMethod', myMethod, { cache: { expiresIn: 500 } } );`

My lack of unhandled exception reporting doesn't help, but I'm at a loss here and EVERY tutorial/example I can find is quite clear and suggests the same few configurations (which I've been trying for the last hour).

**Comment by johnbrett** [comment]
Can you post the myMethod code?

**Comment by ooogway** [comment]
server method with cache requires a callback. non cached functions don't.

if `server.method('myMethod', myMethod, { } )` works and `server.method('myMethod', myMethod, { cache: { expiresIn: 5000, generateTimeout: 500 } } ;` doesn't, then perhaps myMethod method does not support a callback.

`server.method('myMethod', myMethod, { cache: { expiresIn: 500 } } )` fails because generateTimeout is required.

**Comment by rainabba** [comment]
Here was the essence of it (different now because I've implemented node-cache so that I have something, but it behaves very differently.

```
myMethod = function( o, next ) {
// Here I was calling request(), and depending on statusCode and body, I'd do one of the following
if ( error ) {
return next( error, null);
} else {
return next(null, data);
}
```

@johnbrett I'll revisit my code and those samples after a bit of sleep. Thank you.

**Comment by matthieusieben** [comment]
See #3150 for more details as to why you get different behaviors depending on the `cache` option when using `callback: false` in a server method.
