### ISSUE TITLE
Content-Length response header

### ISSUE THREAD

**Issue by diegossilveira** [hapijs/hapi#3049]
Why does Hapi, when response payload has a `size()` function, set a `Content-Lenght` header on response? Accordingly to HTTP spec, `Content-Encoding: chunked` and `Content-Lenght` headers are mutually exclusive, and node.js always chunk the response, right?

**Comment by diegossilveira** [comment]
Anyone? It's really weird, some http clients are complaining about chunked responses with content-length response headers.

**Comment by mtharrison** [comment]
The method is `bytes(length)` to set explicit Content-length header, and it's used to _avoid_ chunked transfer: from the docs:

> bytes(length) - sets the HTTP 'Content-Length' header (to avoid chunked transfer encoding) where:

When you set an explicit size, you shouldn't get a `Content-length` header set. Can you show some example code, or a test case where this happens?

**Comment by mtharrison** [comment]
Ping @diegossilveira

**Comment by mtharrison** [comment]
Going to close, if @diegossilveira or anyone thinks there's an issue here please reopen.

**Comment by diegossilveira** [comment]
@mtharrison, sorry for this late reply. I still suspect it's an issue, but I'm going to provide a code that produce this (mis)behavior. Will reopen with that code, ok?
