### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by Martindelataille** [hapijs/hapi#3050]
Hi,

I am using Hapi 13.0, Node v5.1.1 and i get when running hapi

`Unexpected token import`

I think that problem is related to 
`at done (/app/node_modules/hapi/node_modules/items/lib/index.js:31:25)`

I saw that you updated items to ES6 style

**Comment by Marsup** [comment]
There's no use of import in any hapi project as it's not currently support by node, it's probably coming from your code.

**Comment by Martindelataille** [comment]
True.

Thanks for you fast response
