### ISSUE TITLE
Debugging 500 errors in debug mode

### ISSUE THREAD

**Issue by samalbert** [hapijs/hapi#3052]
Hi! 

Forgive me if this has been answered before, I've been digging around and have been unable to find a solution.

During development our team bump into 500 errors pretty often - error from db, proxying requests, etc.  To see what's going on we jump to our log viewer and track down the request and see what the 'real' error was since all 5xx errors are hidden.

 [This ticket](https://github.com/hapijs/hapi/issues/696) discusses the idea to enable the errors to flow throw during 'dev mode'.  However, looking at the server debug flag api it appears this only changes the console reporting and not the actual response payload.

Is there currently any way to let the errors flow through back to the client? If not, I would love to add this feature and could submit a pull request if you see it beneficial as well.

Thanks

**Comment by hueniverse** [comment]
This would be easy to do in a plugin that you load only during dev. You just add an onPreResponse extension that looks for errors and if it's 500, restores the message from the error information into the payload.

**Comment by nlindley** [comment]
@samalbert I threw together an example plugin that might help get you started. If there’s enough interest, I could clean it up some and publish it. https://github.com/nlindley/hapi-error-response

That said, I’ll probably never use it myself, so feel free to fork it, fix it up, and publish it yourself. :smile:

**Comment by samalbert** [comment]
Thanks @hueniverse for the info, this is incredibly helpful (and easy).

@nlindley, your example looks solid.  Really appreciate you setting this up.
