### ISSUE TITLE
Clear/ignore all invalid cookies automatically

### ISSUE THREAD

**Issue by keyvanakbary** [hapijs/hapi#3053]
Hi there! I have a hapijs server on a subdomain that shares cookies with other sites under the same domain. Eventually it raises a _400 Invalid Request: Invalid Cookie_ to clients that have non-standard/invalid cookies from other sites under the domain (out of my control). `othersite.example.com` setups some non-standard/invalid cookies for any `*.example.com`. Users visiting my site at  `mysite.example.com` with those invalid cookies crash with a 400.

I've been looking for a way of clearing them automatically or just ignoring them all but it seems like I have to specify the cookie name `server.data('invalid-cookie', {strictHeader: false})`. I was wondering if there is a better way of doing this without specifying the cookie name (it requires knowing the cookie name beforehand). Or even a way of telling hapijs to ignore the cookies from other subdomains.

Thanks a lot.

**Comment by hueniverse** [comment]
Did you try setting the default state options when creating the server?

**Comment by keyvanakbary** [comment]
Worked like a charm, thanks man :)

```js
const server = new Hapi.Server({
    connections: {
        state: {
            strictHeader: false
        }
    }
});
```
