### ISSUE TITLE
Allow onPreResponse to override response and execute other extensions

### ISSUE THREAD

**Issue by zerko** [hapijs/hapi#3055]
Hi, 

Versions:  migrating from 8.x to 13.

We were used to be able to rely on other hooks to be executed when replacing boom responses with templated ones (assigning response field), but thats not the case anymore with new API that asks for new responses to be returned instead. 

```js
function handler1(request, reply) {
  if (response.isBoom) {
    return reply.view(...);
  }
  return reply.continue();
}
function handler2(request, reply) {
  return reply.continue();
}
```

I would expect that both handlers or at least handler2 would be called for new response. With latter being what we had with assigning response and calling continue in 8.x.

Is that intentional? Could we work around it somehow? Our other hooks down in the pipeline are adding various things to template context that we need in order to render our layout.

**Comment by hueniverse** [comment]
I need a full working example to show your issue.

**Comment by zerko** [comment]
https://gist.github.com/zerko/be995e01a33e15680749

**Comment by rubennorte** [comment]
I have exactly the same issue. This is preventing me from rendering a template for errors and then extend the view context with additional variables in another extension.

**Comment by hueniverse** [comment]
I understand your issue but not how this worked in 8.x. There has been no changes to this mechanism (at least not intentional) since 8.x. Does this example work as you expect it in 8.x?

**Comment by zerko** [comment]
In 8.x we would assign request.response and call reply.continue(). All other handlers would be called for original request which would now contain templated response. 

If we take code from gist and replace  `return reply.view` with `request.response = reply.view` that would work in 8.x as expected. 13.x docs are specifically stating that you cant do that anymore and need to return new response instead if you want to render template for error response.

**Comment by hueniverse** [comment]
You should not have been directly assigning to `request.response` in 8.x. The doc change was just to make that explicit. If it worked for you in 8.x you can still use that but note that it's not really a defined behavior. The main reason is in the `request._setResponse()` logic where it makes sure to do proper housekeeping on the previously set response. For example, if you had a stream in there and you just replace it with something else directly, you are leaking the stream memory.

I'll leave this open in case I come up with a simple way to do what you want nicely.

**Comment by zerko** [comment]
If it worked as it used to there would be no issue :) I think some combination of hapi and vision changes made that impossible. Thanks for your time in any case.
