### ISSUE TITLE
Server.inject does not initialize cache

### ISSUE THREAD

**Issue by tjsail33** [hapijs/hapi#3060]
We are using Hapi and Lab for functional tests, and are wondering if there is any way to have Hapi initialize the cache while using `server.inject`.

Currently we have our env set up to use a Redis caching layer, however calls to `cache.isReady()` were always returning `false`. We specified only using Redis when we were not running tests, however the built in default `catbox-memory` cache has been returning `false` for `cache.isReady()` as well. This is making it hard for us to test our caching layer during functional tests, and we are wondering if there is a way around the cache not initializing short of manually creating the cache using `ioredis` or another library like that.

Thanks in advance.

**Comment by camfraser** [comment]
:+1:

**Comment by Marsup** [comment]
Have you used server.initialize ?

**Comment by tjsail33** [comment]
Nope, thanks for pointing out that method and for the quick response!
