### ISSUE TITLE
Pre is not allowed

### ISSUE THREAD

**Issue by NerdPad** [hapijs/hapi#3063]
In the documentation pre is part of the new Server options, or the connection options.

Am I doing something wrong? How can I execute a precondition before every route for that server instance.

## Server configuration:

```javascript
// Server Instance
const server = new Hapi.Server(),
    // options for new connection
    options = {
        address: config.ip,
        port: config.port,
        labels: 'api',
        router: {
            stripTrailingSlash: true
        },
        routes: {
            cors: {
                additionalHeaders: ['Allow']
            },
            pre: [{method: pre1}] // pre1 is imported
        }
    };

// Create connection
server.connection(options);
```

## Error

```javascript
Error: Invalid server options {
  "connections": {
    "router": {
      "stripTrailingSlash": true
    },
    "routes": {
      "cors": {
        "additionalHeaders": [
          "Allow"
        ]
      },
      "pre" [1]: []
    }
  }
}

[1] "pre" is not allowed
```

**Comment by arb** [comment]
Doesn't `router` and `routes` both need to be inside a `connections` option?

**Comment by NerdPad** [comment]
@arb They need to be inside connections when the options are passed in the Server constructor, and they can be overridden in server.connection options.

However, passing them inside connections in new Server options also throws the same error.

**Comment by hueniverse** [comment]
You cannot set global pre handlers.
