### ISSUE TITLE
Question about default route config

### ISSUE THREAD

**Issue by no-more** [hapijs/hapi#3064]
Hi,

Sorry if it's not the right place to ask, I would like to better understand the default route config behavior, I'm talking about the one configured in connections (through glue).
What I would like to know is, if I set up default config for a plugin then on a route I set up just a few more options (or some overriding options) does hapi merge so config or take the whole new config and replace the old one ? 

Thanks.

**Comment by hueniverse** [comment]
That's a question for https://github.com/hapijs/discuss
