### ISSUE TITLE
Allow access to parent realm

### ISSUE THREAD

**Issue by devinivy** [hapijs/hapi#3066]
It would be nice if plugins could have access to the parent realm (the realm of the registering plugin).  Without this there is no natural way for a plugin to inherit options from parent plugins.  I'm primarily referring to usage of `server.realm.plugins`.  If this requires extensive discussion/explanation, I'd be happy to move over to hapijs/discuss for the time being.

**Comment by devinivy** [comment]
I now use a decoration to prettify setting realm-specific plugin options (for plugins other than the singular plugin associated with the current realm).  It's a little hard to speak precisely about this, so let me know if clarification is needed.

**Comment by hueniverse** [comment]
I need a more specific example with how this will be used.

**Comment by devinivy** [comment]
The terminology around this is lacking a little bit.  Let me call the realm-specific server object that is passed as the first arg to a plugin's registration function a "plugin-server".

Currently the root server becomes a dumping ground for inheritable (through plugin registration) plugin state, and when that happens plugin composability can suffer.  For example, right now vision's `server.render()` will use the plugin-server's view manager if it has one, and otherwise the root server's view manager.  The manager lives on `realm.plugins.vision.manager`.  With access to the parent realm vision would have the opportunity to walk up the realm tree and instead use the "most relevant" view manager.

Plugins then start to look more self-similar, and therefore more portable when it comes to plugins registering other plugins.  If a plugin doesn't have to fall back on the root server's configuration then it can start to make its own guarantees to the plugins that it registers, and you are afforded better self-contained registrations.

**Comment by hueniverse** [comment]
I need to see the interface you have in mind.

**Comment by devinivy** [comment]
Worth mentioning– it could be solved by exposing the whole parent server on `srv.parent` (I believe it currently lives at `srv._parent`).  The realm would be accessed at `srv.parent.realm`.  If that's too heavy-handed, I'd suggest placing the whole parent realm at `srv.realm.parent`.  I would just provide the actual realm object– no need to bother with cloning, etc.

To illustrate that option,
```js
// The root server or a plugin-server
server;

const plugin = (srv, options, next) => {
    
    // It's a plain reference
    Hoek.assert(srv.realm.parent === server.realm);

    srv.decorate('server', 'aggregate', function () {
    
        // Walk up the realm tree and aggregate config

        const aggregation = {};
        let realm = this.realm;

        while (realm) {
            Object.assign(aggregation, realm.plugins.whatever || {});
            realm = realm.parent;
        }

        // Hopefully do something less boring with it than this?
        return aggregation;
    });

    next();
};

plugin.attributes = { name: 'whatever' };

server.register(plugin, (err) => Hoek.assert(!err, err));
```

**Comment by diegobfernandez** [comment]
I don't understand the full extension of this change but seems it would be useful in my scenario.
My app is dived in modules each one a different plugin. Today I can't use [hapi-error](https://github.com/dwyl/hapi-error) for 404 errors since I don't register vision globally.

**Comment by hulbert** [comment]
We're running into an issue this is perhaps intended to address in that we have the following app structure:

- base server, with registered plugins
  - htmlPageRoutes
    - registers Vision & configures it
    - uses [Wurst](https://github.com/felixheck/wurst) to register routes
  - restfulApiRoutes
    - uses [Wurst](https://github.com/felixheck/wurst) to register routes

The realm of all the registered routes is the respective Wurst realm, so using `request.render()` and so on don't work from those routes since Vision is in the parent realm.

**Comment by hueniverse** [comment]
@diegobfernandez can you provide more info on your setup and why you can't use hapi-error?
@hulbert is there a reason why you can't register vision globally?

**Comment by diegobfernandez** [comment]
Sorry @hueniverse, I no longer have access to the source code and I can't remember by heart the setup.
I'll ask someone to reply here with the specifics if they still have this issue.

**Comment by hueniverse** [comment]
Added as `server.realm.parent` and replaces `server.root`.
