### ISSUE TITLE
 Unexpected end of file, errno: -5, code: 'Z_BUF_ERROR'

### ISSUE THREAD

**Issue by Martindelataille** [hapijs/hapi#3067]
Hi,

I use HAPI 13.x / Node v5.4
I am uploading file and data with 'multipart/form-data'.

My configuration is like this: 
`  { method: 'POST', path: '/file/{slug}/upload',
    config: {
      payload:{
        maxBytes:6048576, // NOTE 6MB
        output:'stream',
        parse: true,
      },
      handler: require('./facets/file/create'),
    },
  },`

After receive datas, i upload it to AWS S3 and save receive data to my database.

It's working but sometimes, i get :
`cause: { [Error: unexpected end of file] errno: -5, code: 'Z_BUF_ERROR', response: null }`

It can be due with a simple PDF of 1MB.

**Comment by Martindelataille** [comment]
Is there anyway to stop download or stream in progress ?

Because i know where it has be pushed to S3.

**Comment by mtharrison** [comment]
@Martindelataille can you provide any code that shows this? An example gist or repo would be helpful.

**Comment by Martindelataille** [comment]
@mtharrison Here is a gist: 
https://gist.github.com/Martindelataille/72ad363549aa0a30f5edc78e8714d9e0

Feel free to ask me more details

**Comment by mtharrison** [comment]
Which version of Node are you running? Are you still seeing that same error?

**Comment by hueniverse** [comment]
No response.
