### ISSUE TITLE
Joi transformation is applied after validation

### ISSUE THREAD

**Issue by bsiddiqui** [hapijs/hapi#3076]
given two schemas
```js
let foo = Joi.object({
   count: Joi.number().integer().min(0).default(0)
})

let bar = foo.concat(Joi.object({
   count: Joi.forbidden()
}))
```

If you add response validation on a route using the above `bar` variable and don't include the count key, you'll get the following response `{ count: 0 }`. 

This seems a bit problematic since no error will be thrown and incorrect data could be sent

**Comment by Marsup** [comment]
concat makes a merge, not a replacement, you need to use keys() for that.

**Comment by bsiddiqui** [comment]
@Marsup if you had the `foo` schema without the `.default(0)` it would not apply a transformation so why would adding `.default(0)` do that?

If you had this schema instead:
```
let foo = Joi.object({
   count: Joi.required()
})

let bar = foo.concat(Joi.object({
   count: Joi.forbidden()
}))
```

Using `.concat()` acts as expected and overwrites instead of merging since those two requirements are in conflict. I would imagine that adding `.forbidden()` would not then add a default value to a key that's not present since that is directly in conflict with the schema.

**Comment by Marsup** [comment]
As I said it's a merge, so your schema becomes :
```js
let bar = Joi.object({
   count: Joi.number().integer().min(0).default(0).forbidden()
})
```
Which is not a conflict at all. The rule says you never want any user-provided value but want a default to 0.

**Comment by bsiddiqui** [comment]
Ok that's fair
