### ISSUE TITLE
How to get Current Url and Path ? 

### ISSUE THREAD

**Issue by codetrash** [hapijs/hapi#3084]
Halo...

I need to retrieve current request Url and Path in server.js

Does anyone know the shortcut ?

**Comment by mtharrison** [comment]
The path is just `request.path`. This Q on StackOverflow might be helpful if you need the full URL: http://stackoverflow.com/questions/31840286/how-to-get-the-full-url-for-a-request-in-hapi

**Comment by codetrash** [comment]
I make a simple server.method inside server.js


```
server.method('Response', (statusCode, statusText) => {
//console.log(server.info.uri);
//....need to get the requestPath here
})
```

**Comment by hueniverse** [comment]
The method is just a function. It can't magically get access to the "current request".

**Comment by rigon** [comment]
I created a library that tries to solve this problem:
https://www.npmjs.com/package/hapi-url
