### ISSUE TITLE
Why when I require index.js with Hapi it starts up a server?

### ISSUE THREAD

**Issue by noppanit** [hapijs/hapi#3086]
Here's my Hapi file

```
'use strict';

var Hapi = require('hapi');
var Inert = require('inert');
var Vision = require('vision');

var log = require('./logger');
var config = require('./config');
var extensions = require('./extensions');

var server = new Hapi.Server({
  connections: {
    routes: {
      validate: {
        options: {
          stripUnknown: true
        }
      }
    }
  }
});

server.connection({ port: config.port });

/**
 * Dynamically Load Routes
 */
require('./routes')(server);

// adds metadata to responses, and customizes error responses
server.ext({
  type: 'onPreResponse',
  method: function preResponse(request, reply) {
    // log.info("intercepting response");
    extensions.handlePreResponse(request, reply);
    return reply.continue();
  }
});

server.on('request-error', extensions.handleOnRequestError);

server.register(
  [
    Inert,
    Vision,
    require('./plugins/swaggerPlugin'),
    require('./plugins/redisPlugin')
  ],
  function handlePluginRegistrationError(err) {
    if (err) {
      log.warn(JSON.stringify(err));
      throw err; // something bad happened loading the plugins
    }
    server.start(function serverStartedCallback() {
      log.warn('DAL services listening on port '+config.port+'...');
      log.warn('Server running at: ' + server.info.uri);
    });
  }
);

module.exports = server;
```

Every time I `require('./index.js')` to do integration test. The server starts up because I can see this in my console.

```
2016-03-10T22:32:17.465Z - warn: DAL services listening on port 8081...
2016-03-10T22:32:17.465Z - warn: Server running at: http://X57112315094123:8081
```

The problem is because the server is started so the test will just hang there and not finish unless I kill manually. 

Here's how I do testing.

'use strict';

var querystring = require('querystring');
var chai = require('chai');
var expect = chai.expect;
var moment = require('moment');

var server = require('../../../index');

describe('Analytics Integration Tests', function desc() {
  describe('/', function postsDesc() {
    var redisClient;
    beforeEach(function beforeEach(done) {
      redisClient = server.plugins['sparrow-api'].client;

      redisClient.flushall(function flushFunc() {
        done();
      });
    });

    afterEach(function afterEach(done) {
      redisClient.flushall(function flushFunc() {
        done();
      }); 
    });

    it('should get analytics posts with from date', function it(done) {
      var from = moment().utc().subtract(2, 'hour').toISOString();

      server.inject(url, function injectResponse(response) {
        expect(response.statusCode).to.equal(200);
        done();
      });
    });

  });
});
```

Is this normal behaviour? This makes testing a bit hard for me because I have to call `shutdown` I thought the purpose of `inject` is that I don't have to start the server?

**Comment by nlf** [comment]
it starts because you're calling `server.start()`, try wrapping your call to `server.start()` in a check for `module.parent` like so:

```js
if (!module.parent) {
  server.start(function () {

    console.log('server started');
  });
}
```

if `module.parent` is set that means that your server has been required by another file, so we simply skip starting it

**Comment by noppanit** [comment]
got it thanks so much will try that.

**Comment by noppanit** [comment]
it works! closing the issue.
