### ISSUE TITLE
yar not making a synchronous get and set if more then 1 instance launched by pm2 

### ISSUE THREAD

**Issue by kvtm-anirudh** [hapijs/hapi#3090]
as i am using yar to store cookies at server with catbox-redis lib to use redis for kibana by elastic.co
i am getting logged out and request are becoming asynchronous   when using more then 1 instance by pm2 
Steps to replicate issues 
1. Use kibana and register yar to use cookie jar over redis with catbox-redis 
2. Change session storage syntax of kibana with yar syntax of using req.yar.set and req.yar.get
3. Run 5 instances from pm2 .
4. Now try to use kibana by clicking on different requesting links and buttons .
5. Find the  difference in redis of asynchronus set and get in values as an example if the process follows set get set get set get ..... in 5 instances it becomes set set get get get set ........ which hurts the whole process .

Please provide the possible solution to yar and me  if using more then 1 instance .,.,, 

anyone's help or solution will be of great use to me.

Thankyou

**Comment by hueniverse** [comment]
Please ask this either in the yar repo or in the hapijs/discuss repo.
