### ISSUE TITLE
Using Async.series inside a handler

### ISSUE THREAD

**Issue by moogway** [hapijs/hapi#3091]
Hi,
I'm trying to use [async](https://github.com/caolan/async) library inside my handler functions (for the sake of modularity) and this is what the example code is like - 

```
const Async = require('async');

const handler_function = function (request, reply){
    const final_responder = function (error, result){
        if(error) reply(Boom.notFound("not found"));
        else reply(result);
    };
    
    const internal_function1 = function (async_series_callback){
        call_to_a_db_function1(parameters, function(dbError, dbResponse){
            if(dbError) return final_responder(dbError);
            else return async_series_callback(null, dbResponse);
        });
    };

    const internal_function2 = function (async_series_callback){
        call_to_a_db_function2(parameters, function(dbError, dbResponse){
            if(dbError) return final_responder(dbError);
            else return async_series_callback(null, dbResponse);
        });
    };
    
    Async.series([
        internal_function1,
        internal_function2,
    ],final_responder);
};
```
So if an error is caught in ```call_to_a_db_function1```, ```final_responder``` should be executed and not ```internal_function2```. But as it is happening, both ```internal_function1``` and ```internal_function2``` are being executed inspite of ```call_to_a_db_function1``` throwing an error.

What I'm unable to figure out is whether this is happening because of hapi internals or because of async. Any help will be most appreciated. Thanks.

**Comment by AdriVanHoudt** [comment]
you should post this on the Async repo btw but in your Async functions (internal1 and 2) you should only ever call the the `async_series_callback`. If you read the Async docs it will tell you that the moment you call `async_series_callback` with an error it will immediately call your `final_responder` if no error it will call it when all internal's are done and have called their `async_series_callback`

**Comment by moogway** [comment]
Thanks @AdriVanHoudt for the advice.

Found my mistake. And am going to close this issue before I go drown myself in the cesspool of shame.

**Comment by AdriVanHoudt** [comment]
no shame in asking questions, glad I could help!
