### ISSUE TITLE
Catch internal errors and display HTML without losing information

### ISSUE THREAD

**Issue by shugigo** [hapijs/hapi#3093]
Hey,

I wanted to understand how I can replace internal server errors with a generic page on the onPreResponse extension without losing the error event emit with the full stack of the error.

Thanks,
Shay

**Comment by hueniverse** [comment]
Just log the error in the ext handler.

**Comment by shugigo** [comment]
I found the error itself under request.response but I didn't find the functions stack. 
Is there any way to retrieve the stack?

Thanks,
Shay

**Comment by mtharrison** [comment]
`err.stack`?

**Comment by shugigo** [comment]
Oh right! Its seems like my IDE misled me to think this variable is undefined. Thanks!
