### ISSUE TITLE
Sideway logo served w/ SSL causing insecure content warning on npmjs.com

### ISSUE THREAD

**Issue by hulbert** [hapijs/hapi#3095]
Reproduce:

1. Visit https://www.npmjs.com/package/hapi
2. See in console:
    
    >  Mixed Content: The page at 'https://www.npmjs.com/package/hapi' was loaded over HTTPS, but requested an insecure image 'http://blog.sideway.com/wp-content/uploads/logo-300x114.png'. This content should also be served over HTTPS.

NPM should probably proxy README images like Github does, but alas they aren't. I'd submit a PR but `blog.sideway.com` doesn't seem to have SSL setup.

**Comment by sholladay** [comment]
If fixing the problem with `blog.sideway.com` is a pain, one _could_ use:

https://camo.githubusercontent.com/5f79227094b6dbe8e04e644139449df7f3a3d3dc/687474703a2f2f626c6f672e736964657761792e636f6d2f77702d636f6e74656e742f75706c6f6164732f6c6f676f2d333030783131342e706e67

**Comment by AdriVanHoudt** [comment]
@hueniverse could you add ssl to your blog?
