### ISSUE TITLE
Respect buffer.headers given to reply()

### ISSUE THREAD

**Issue by sholladay** [hapijs/hapi#3096]
Using [h2o2](https://github.com/hapijs/h2o2#flow-control)'s `onResponse` handler, it caught me by surprise when some header copying logic I wrote suddenly broke when I switched from `reply()`ing with a stream to a buffer from [wreck](https://github.com/hapijs/wreck). It actually took me a while to figure out it wasn't my fault, since I had no indication that Hapi may simply not care about the headers property when given a buffer rather than a stream.

Once I figured that out, I was able to successfully modify the headers using this pattern:

````javascript
const resp = reply(buffer);
resp.headers.foo = 'bar';
````

But it seems cleaner to me to prepare a response and hand it off to `reply()`, rather than modify what I get back from that. Is there a good reason not to do so? I can think of at least one situation where I would _have_ to use the latter strategy: if I wanted to reply with a raw string. And of course `resp.header()` is more powerful. However, in this case I merely need to copy the headers from the incoming response to the outgoing response.

**Comment by kanongil** [comment]
The header copying behavior is controlled by the `settings.passThrough` option and only applies to `stream` responses. It doesn't make sense to extend that behavior to other response types.

If you need to set the headers you should generally use the `resp.header(…)` method.

@hueniverse Maybe `passThrough` should default to `false` for less surprises?

**Comment by sholladay** [comment]
`passThrough` does default to false. In my proxy, I want the request to be transparent, so it makes sense to set `passThrough` to true. But then I need to deal with the consequences of the response being encoded based on the client's given `Accept-Encoding` header. Therefor, if I want to modify the response, I need to create a `zlib` stream or buffer to decode and re-encode it. That worked fine when it was a stream and I endowed it with a reference to the response headers. Switching to a buffer seems like it should have worked.

Another way to say this is that merely putting `wreck.read()` in front of the response causes a massive change in behavior - beyond the obvious - rather than a small one.

**Comment by hueniverse** [comment]
We support headers on a stream because that's the stupid was the **request** module does it and we wanted to be nice to people who just pass `reply()` a request module stream. From there it became a thing. Extending it to buffers feels wrong. We should just make the docs better to make it clear.

**Comment by sholladay** [comment]
Okay, fair enough. So to clarify, is this the idiomatic way to copy the headers verbatim, given that `wreck.read()` breaks the "flow" of `passThrough`?

````javascript
reply(response).headers = response.headers;
````

**Comment by hueniverse** [comment]
No. Call `reply().header()` for each header.

**Comment by hueniverse** [comment]
The docs clearly state this applies to Streams only.
