### ISSUE TITLE
plugin attribute "dependencies" is not processed if it's located under "pkg"

### ISSUE THREAD

**Issue by PavelPolyakov** [hapijs/hapi#3097]
Hi,

[Here](http://hapijs.com/tutorials/plugins) in the documentation we have the statement that developer can declare the plugin attributes either directly or inside the `package.json` file, while it's merged to the `pkg` attribute.

![image](https://cloud.githubusercontent.com/assets/839290/13998637/712c0baa-f138-11e5-8956-53779dc913f6.png)

However, it seems that if the dependencies are declared inside the `pkg` attribute, they are not taken into the attention while the server starts.

Here I've prepared the repository to reproduce the incorrect behavior:
https://github.com/PavelPolyakov/hapijs-dependencies-processing-bug

Please, have a look.

Regards,

**Comment by mtharrison** [comment]
[hapi only pulls the name and version from the `package.json`](https://github.com/hapijs/hapi/blob/master/lib/plugin.js#L228-L229). You need to declare the deps in the `attributes` separately. So your b plugin should look like:

```javascript
exports.register.attributes = {
    pkg: require('./package.json'),
    dependencies: [ "vision" ]
};
```

**Comment by PavelPolyakov** [comment]
@mtharrison 
indeed it makes effect, however it's unexpected :)

Thanks!

Consider closing, if this behaviour is expected by others.
