### ISSUE TITLE
Connectionless Auth Strategy

### ISSUE THREAD

**Issue by jaw187** [hapijs/hapi#3100]
Would it be possible to allow for connectionless plugins to define auth strategies to be used by other plugins later?

This would correct a bug where a plugin which is applied to more than one connection attempts to define auth strategies which use `server.decorate` in the implementation.  The use case is one where the strategy is to be shared with other plugins which reside on different connections.

https://github.com/hapijs/hapi-auth-cookie/issues/119 has some more details.

**Comment by nlf** [comment]
to define strategies? i'm not sure about that. i would use the plugin to define the auth scheme, and then create the strategies myself on the connections as needed. if you have a plugin that defines your routes, create the strategy there. there's nothing stopping you from making that code reusable.

**Comment by hueniverse** [comment]
Auth strategies are connection specific. Where would you put them?
