### ISSUE TITLE
HPE_UNEXPECTED_CONTENT_LENGTH error

### ISSUE THREAD

**Issue by cdaringe** [hapijs/hapi#3103]
Hi all:

When making a call against my server for a particular API route, I receive:

```
"{"bytesParsed":299,"code":"HPE_UNEXPECTED_CONTENT_LENGTH"}"
```

A little googling lead me [to this post](http://stackoverflow.com/questions/35525715/http-get-parse-error-code-hpe-unexpected-content-length) which says that headers are probably fubared.

My _request_ headers are:

```
// request
Accept:"application/json, text/plain, */*"
Authorization:"Hawk id="64ece184-c6f4-4d64-8912-bebee7d8909f", ts="1459211540", nonce="2fLS98",... (length: 131)"
contentType:"application/json"
User-Agent:"axios/0.9.1"
x-forwarded-host:"localhost:2000"
```

I'm not seeing an exception on the server, just in the client (same thread for testing), which is peculiar.

Any tips would be appreciated.  Thanks!

Node 4.4.1.
code: [this repo, npm i, npm test](https://github.com/MRN-Code/nodeapi)

**Comment by cdaringe** [comment]
i will note that downgrading to 4.2.4 did temporarily resolve the issue

**Comment by hueniverse** [comment]
That response doesn't look like it's coming from hapi. Do you have something running in front of it like nginx?

**Comment by cdaringe** [comment]
hey @hueniverse,

thanks for getting back.  i omitted key details that were relevant to the problem.  we _were_ using hapi v9.x.  upon upgrading to hapi 13.x just now (sole change** to the environment), the problem has vanished.  verified on multiple machines, osx and ubu based.

the error sources from node's internal http lib.  i assume hapi wraps that, and suspect that hapi was writing headers in the `reply` cycle that my version of node didn't like.

sound like a reasonable thing?  thanks again.
