### ISSUE TITLE
Continuations for request lifecycle

### ISSUE THREAD

**Issue by ugate** [hapijs/hapi#3104]
Is there a way to suspend the request lifecyle like we have with [reply](http://hapijs.com/api#flow-control)? I'd liked to be able to perform some pre-processing on the request before resuming. Maybe something like:
```js
server.ext('onPreAuth', (request, reply) => {
    const req = request.hold();
    setTimeout(() => {
        req.continue();
    }, 1000);
});
```

**Comment by hueniverse** [comment]
If you add an extension anywhere and not call `reply.continue()` or `reply()`, the lifecycle stops until you do.

**Comment by ugate** [comment]
@hueniverse It wasn't clear to me that the [reply-interface](http://hapijs.com/api#reply-interface) section also applied to the [request-lifecycle](http://hapijs.com/api#request-lifecycle)/[extension points](http://hapijs.com/api#serverextevents). Sorry for the issue and thanks for clarifying!
