### ISSUE TITLE
Call another controller method to complement the reply

### ISSUE THREAD

**Issue by lucasbastianik** [hapijs/hapi#3106]
Is it possible to call another controller method to complement the reply?

For example:
`{
  method: 'GET',
  path: "/cities/{id}",
  config: {
    handler: controllers.cities.searchCity,
    validate: {
      query: {
        id: Joi.number()
        .description('City ID')
      }
    }
  }
},
{
  method: 'GET',
  path: "/users/{id}",
  config: {
    handler: controllers.users.searchUser,
    validate: {
      query: {
        id: Joi.number()
        .description('User ID')
      }
    }
  }
}`

When I search the user, I got the cityId and I want to call the `controllers.cities.searchCity` to search more informations of city and complement the answer of user with these city informations.

I know I could do this directly in the database modeling or via ORM, but the requisites of the project doesn't allow this.

**Comment by hueniverse** [comment]
This is what prerequisites are for. Best to ask these kind of questions in hapijs/discuss.
