### ISSUE TITLE
Charset of Hapi.js or Node.js?

### ISSUE THREAD

**Issue by lucasbastianik** [hapijs/hapi#3110]
Hello,

I have a answer of MS SQL stored procedure but when I do `reply.` the accentuation of words are wrong.

Example:
The return of API actually are:
`
{
id: 1,
"name": "OPERA€ÇO"
}
`

But I want this return:
`
{
id: 1,
"name": "OPERAÇÃO"
}
`

Can anybody help me how can I set a encoding or charset to fix this?

Ty,
Lucas.

**Comment by Marsup** [comment]
As in anything javascript, I'd say it's UTF-8, can you check what you get out of the database before using reply ?

**Comment by lucasbastianik** [comment]
I did a console.log before using reply and I got this:
`
{ id: 1, "name": "OPERA€ÇO" } 
`

Maybe it's connector to MS SQL?! I am using [mssql](https://www.npmjs.com/package/mssql).

**Comment by Marsup** [comment]
Maybe the data in the database itself is wrong, or some setting. I'd suggest taking the issue to this library since it's not hapi's fault.

**Comment by DavidTPate** [comment]
@lucasbastianik I've run into this a few times, straight UTF-8 doesn't usually work but instead requires UTF-8 with unicode support and fields that can support the character set to store the data.

**Comment by devinivy** [comment]
Worth looking into db-connection-level, database-level, table-level, and column-level character set support.
