### ISSUE TITLE
Check existing routes in Hapi proxy handlers

### ISSUE THREAD

**Issue by lutfor3737** [hapijs/hapi#3116]
Scenario: I have an existing legacy application which has lots of routes. I am developing HAPI API which has all new routes. I will convert all existing routes into hapi over time. If incoming route does not match with existing HAPI routes, I will forward those into legacy system. 

How can i check my all current hapi routes for incoming route request before forwarding it to other legacy system? Any kind of example, advice will be appreciable.

**Comment by mcmo** [comment]
You could put your forwarding code inside of the 'catch all route' handler, which will run if none of your hapi routes are matched.

http://hapijs.com/api#catch-all-route

**Comment by hueniverse** [comment]
@lutfor3737 Please post questions in hapijs/discuss next time. The suggestion from @mcmo is the way to go.

**Comment by lutfor3737** [comment]
@mcmo  thanks
@hueniverse  I will post there.
