### ISSUE TITLE
adding issue template

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/hapi#3117]
I notice a lot of questions regarding hapi that are not bugs or just general question get posted on this hapi repo instead of the discuss one (which I found totally normal) but it is weird a user to get told to ask questions about hapi somewhere else then the hapi repo, this is not the case on other repos. On the other hand I do understand the hapi side of it as well.

Maybe we can find a solution whereby people are more activly directed to the discuss repo, I know it is in the readme but maybe also put in the CONTRIBUTING.md and maybe even add an issue template so everyone who makes an issue has definatly read where what should go. 

any thoughts?

**Comment by johnmanko** [comment]
I don't like seeing questions posted on rep issues, either.  Not that I don't learn from them, it's just not the place. I wish GH allowed for custom notices above the comment box informing devs where to really post their questions.  

Anyway, perhaps the README of the different repos can have a notice linking to all discussion venues, including StackOverflow tags and Gitter.  It's hard to find the Gitter room for many projects.

**Comment by mtharrison** [comment]
@AdriVanHoudt CONTRIBUTING updated in https://github.com/hapijs/hapi/pull/3186

**Comment by AdriVanHoudt** [comment]
nice 👍
