### ISSUE TITLE
Support [] as payload validation

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/hapi#3119]
regarding https://github.com/hapijs/hapi/blob/af9591356114f64485546cac0aa6b540a010c7da/lib/schema.js#L160
now `{}` works instead of `Joi.object()` so I would expect `[]` to work instead of `Joi.alternatives().try()`
Joi will auto convert it to alternatives so it will work

This would be a trivial PR but still asking first ;)

**Comment by hueniverse** [comment]
Should be fine.
