### ISSUE TITLE
Simpler route definition: hapi-rest-methods

### ISSUE THREAD

**Issue by daraosn** [hapijs/hapi#3120]
I moved away from Express to Hapi, but missed the simplicity for creating routes. I'm new to your framework, not sure the decision behind of choosing expressiveness over shortness, but I decided to create a plugin https://github.com/daraosn/hapi-rest-methods

Let's you do this:
```
server.get('/foo', function(request, reply) {
  reply('bar');
});
```

Same for `post()`, `put()`, `patch()`, `delete()` and `options()`.

Just wanted to share and receive feedback too

**Comment by devinivy** [comment]
Hi @daraosn– looks like a plugin that other folks will definitely find and use :).  You could add it to the plugins section of the hapijs.com site if you'd like by submitting a PR to [hapijs/hapijs.com](https://github.com/hapijs/hapijs.com).

For further discussion could you move this issue to the [hapijs/discuss](https://github.com/hapijs/discuss) repo?

**Comment by daraosn** [comment]
Sure, I will move it there, thanks! (and nice project 👍 )

**Comment by devinivy** [comment]
Moved to https://github.com/hapijs/discuss/issues/269
