### ISSUE TITLE
Logging improvement

### ISSUE THREAD

**Issue by Marsup** [hapijs/hapi#3122]
I don't think we have any way to know ahead of time whether a log statement will be used, while the creation of the log message itself can be costly (stringify or else).

Most log frameworks allow for a test function to know if some level/tag would cause logging, or a lazy function that the framework would evaluate if need be, like:
```js
if (request.wouldLog(['debug', 'foobar']) {
    request.log(['debug', 'foobar'], /* costly operation */);
}

// OR

request.log(['debug', 'foobar'], () => { /* costly operation */ });
```

Unless we already have a similar mechanism I didn't see, what do you think of supporting one of those ?

**Comment by AdriVanHoudt** [comment]
How would `wouldLog` work? If I register `.on('request', [function]` you can't know whether I will use a tag or not.

And just out of interest how would the lazy function defer the costly operation?

**Comment by mtharrison** [comment]
Any other examples apart from stringifying, because that's not necessarily required, you can pass an object to `request.log()`.

@AdriVanHoudt makes a valid point about plain `.on()` handlers.

Could this be something managed in the app instead via configuration?

**Comment by Marsup** [comment]
@hueniverse it's lacking an important test, the whole point was not to call that function if there's no listener.

**Comment by hueniverse** [comment]
Feel free to add that feature to podium and then we can expose it here. However, there is no clean way to do this perfectly. At best, you can check if there are any **potential** listeners ignoring restrictions on channel and tags. Basically just check with the current (and any linked) podium(s) to see if there are any listeners at all.
