### ISSUE TITLE
server.expose is really slow for deeply nested objects

### ISSUE THREAD

**Issue by 5c077yP** [hapijs/hapi#3126]
Hey,

this is more a question than an issue. Recently I realized when using `server.expose` from within a plugin to expose an object (redis client) it took about 4-5 seconds to register the plugin, whereas the key, value notation of server.expose is done in under 1ms. After checking the code and re-reading the docs I saw that `server.expose(obj)` is putting a deep copy into server.plugins, which explains the differences. 

I was just wondering if this is really intended and if so, maybe it would make sense to give a better visible hint in the docs, just to say that this deep copy can really take some time and should better not be used if not necessary. I'm using mocha for testing with a 2 seconds timeout and all my tests suddenly failed telling me that initializing the server timed-out.

**Comment by mtharrison** [comment]
I usually just expose a function when I don't want to deep copy an object with `server.expose()`.

**Comment by 5c077yP** [comment]
so that it looks like this ?

```javascript
// in the plugin
const client = ...
server.expose(() => client);
```

```javascript
// in a handler
const client = request.server.plugins[...]();
```

actually i really love the hapi documentaion, but i felt that it lacks some details on the custom plugins section. that's why i wasn't really sure which function to use when exposing something from a plugin the the server/request-handler.

**Comment by mtharrison** [comment]
@5c077yP if I were exposing a Redis client from inside a plugin, I'd probably just use the `server.expose(key, value)`. For example:

```js
'use strict';

// Plugin

const Redis = require('redis');

const plugin = function (server, options, next) {

    const client = Redis.createClient();
    server.expose('client', client);

    // Initialize counter to 0

    client.set('counter', 0, next);
};

plugin.attributes = { name: 'redis' };

// Server

const Hapi = require('hapi');

const server = new Hapi.Server();
server.connection({ port: 4000 });

server.register(plugin, (err) => {

    if (err) {
        throw err;
    }

    server.route({
        method: 'GET',
        path: '/',
        handler: function (request, reply) {

            const redis = request.server.plugins.redis.client;

            redis.incr('counter', (err, count) => {

                if (err) {
                    return reply(err);
                }

                return reply(`Route was visited ${count} times!`);
            });
        }
    });

    server.start((err) => {

        if (err) {
            throw err;
        }
        console.log('Started server');
    });
});
```

You could also expose an object with a function inside but that seems a little overkill:

```js
server.expose({ client: () => client });

...

const redis = request.server.plugins.redis.client();
```

The docs mention that the object will be deep cloned [here](http://hapijs.com/api#serverexposeobj).
