### ISSUE TITLE
inert module crashes on registering

### ISSUE THREAD

**Issue by sulemankm** [hapijs/hapi#3130]
Hi, I was just trying out the hapi tutorial and got this error.

/home/suleman/Projects/hapijs_tut/node_modules/inert/lib/index.js:14
    server.expose('_etags', server.settings.files.etagsCacheMaxSize ? new File.Etags(server.settings.files.etagsCacheMaxSize) : {});
                                                 ^

TypeError: Cannot read property 'etagsCacheMaxSize' of undefined
    at Object.exports.register (/home/suleman/Projects/hapijs_tut/node_modules/inert/lib/index.js:14:50)
    at Object.target [as register] (/home/suleman/Projects/hapijs_tut/node_modules/hapi/node_modules/joi/lib/object.js:79:30)
    at each (/home/suleman/Projects/hapijs_tut/node_modules/hapi/lib/plugin.js:317:14)
    at iterate (/home/suleman/Projects/hapijs_tut/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/home/suleman/Projects/hapijs_tut/node_modules/hapi/node_modules/items/lib/index.js:39:9)
    at module.exports.internals.Plugin.parent.auth.internals.Plugin.register.each [as register] (/home/suleman/Projects/hapijs_tut/node_modules/hapi/lib/plugin.js:320:11)
    at Object.<anonymous> (/home/suleman/Projects/hapijs_tut/server.js:24:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

**Comment by mtharrison** [comment]
What's the tutorial? Can you post a link or even better yet the code that you're using?

**Comment by sulemankm** [comment]
Yes.  Here is the link to the tutorial and my code is as below:

`'use strict';

const Hapi = require('hapi');

const server = new Hapi.Server();
server.connection({port:3000});

server.route({
	method: 'GET',
	path: '/',
	handler: function (req, reply) {
		reply('Hello, World!');
	}
});

server.route({
	method: 'GET',
	path: '/{name}',
	handler: function (req, reply) {
		reply('Hello, ' +  encodeURIComponent(req.params.name) + '!');
	}
});

server.register(require('inert'), (err) => {
	if (err) {
		throw err;
	}

	server.route({
		method: 'GET',
		path: '/hello',
		handler: function (req, reply) {
			reply.file('./public/hello.html');
		}
	});
});

server.start((err) => {

	if (err) {
		throw err;
	}
	
	console.log('Server running at:', server.info.uri);

});

`

**Comment by sulemankm** [comment]
And here is my package.json file; just in case if hapi and inert versions matter.

`{
  "name": "hapijs_tut",
  "version": "1.0.0",
  "description": "Haip.js Tutorial",
  "main": "index.js",
  "scripts": {
    "test": "test.js"
  },
  "author": "Suleman Khalid",
  "license": "ISC",
  "dependencies": {
    "hapi": "^13.3.0",
    "inert": "^2.1.6"
  }
}`

**Comment by gergoerdosi** [comment]
2.1.6 is probably not compatible with hapi 13.3.0. Try the latest version, 3.2.0.

**Comment by sulemankm** [comment]
Yeah, updating inert to version 3.2.0 fixed the problem.

However, is there a way to determine, which version of a plugin is compatible with which version of hapi?

Thanks.

**Comment by devinivy** [comment]
Plugins should (and typically do) have hapi listed as a peer dependency in their package.json, e.g https://github.com/hapijs/hapi-auth-cookie/blob/master/package.json#L22-L24.

**Comment by sulemankm** [comment]
So why did `npm install --save inert` install version 2.1.6 and not the latest version?

**Comment by gergoerdosi** [comment]
It install 3.2.0 for me:

```
$ npm install inert
/test
└─┬ inert@3.2.0 
  ├── ammo@1.0.1 
  ├── boom@2.10.1 
  ├── hoek@2.16.3 
  ├── items@1.1.1 
  ├─┬ joi@6.10.1 
  │ ├── isemail@1.2.0 
  │ ├── moment@2.13.0 
  │ └── topo@1.1.0 
  └── lru-cache@2.7.3 
```
