### ISSUE TITLE
Performance improvements?

### ISSUE THREAD

**Issue by taoeffect** [hapijs/hapi#3148]
I've been looking at the [TechEmpower web framework benchmarks](https://www.techempower.com/benchmarks/#section=data-r12&hw=peak&test=json&l=b95g) (note: that link has some filters on) and was rather shocked to see how much of an overhead Hapi would add to Node.js on all of the various tests they ran.

For JSON serialization **[Hapi is apparently 2.7%](https://www.techempower.com/benchmarks/#section=data-r12&hw=peak&test=json&l=b95g)** the speed of raw Node.js, while Express is 52.7% of raw node (half as fast).

For [single query](https://www.techempower.com/benchmarks/#section=data-r12&hw=peak&test=db&l=b95g) we have Hapi at 6.4% of node, and Express at 26.3% (both are awful, but Hapi is somehow much worse).

OTOH, the good news is that Hapi does better on [Multiple query](https://www.techempower.com/benchmarks/#section=data-r12&hw=peak&test=query&l=b95g) and [Data updates](https://www.techempower.com/benchmarks/#section=data-r12&hw=peak&test=update&l=b95g) benchmarks (91.3%/29% for Hapi vs 35.2%/10.6% for express).

Now, I noticed that [at least one of the TechEmpower benchmarks](https://github.com/TechEmpower/FrameworkBenchmarks/issues/2045) didn't make sense, but these folks have been doing this benchmarking thing for some time, and I'm guessing not everything is a mistake.

You can see their benchmark code for Hapi, Express and Node.js here: https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/JavaScript

**Comment by jamesdixon** [comment]
This might be a good read if you haven't already seen this: https://hueniverse.com/2014/08/20/performance-at-rest/

Also with regards to JSON serialization, wondering if #3014 had made it into the benchmark.

**Comment by taoeffect** [comment]
> This might be a good read if you haven't already seen this: https://hueniverse.com/2014/08/20/performance-at-rest/

Nope, hadn't seen it! Thanks, that's helpful enough by itself for me to close this issue. I do appreciate all that Hapi does out of the box. :)

> Also with regards to JSON serialization, wondering if #3014 had made it into the benchmark.

Doesn't seem like it, they were using [Hapi 8.6.0](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/hapi/package.json#L9). I don't know whether or not the changes since then would affect the benchmarks.

**Comment by jamesdixon** [comment]
Wow, I'd say the fact that they did a benchmark on February 25, 2016 using Hapi 8.6 says something about their methods 👍
