### ISSUE TITLE
Update response with a middleware

### ISSUE THREAD

**Issue by yamsellem** [hapijs/hapi#3149]
It's relatively easy to add a pre middleware:

```javascript
server.route({
  method: 'GET',
  path: '/item',
  config: {
    pre: [{method: function(req, res) {}, assign: 'item'}],
    handle: function(req, res) {}
  }
});
```

But the documentation lacks example on how to do the same with post middleware (like changing every objets before responding).

The idea here is a `toJSON()` method on domain objects that expose their public representation, so this post middleware have to call it on every object (or objects of array).

ps. I've seen the `json: { replacer: function(data) { return data.toJSON(); }}` but adding it in the above config don't work. I've also seen the `server.ext` but don't get it.

double ps: I've found this option, is this ok? Will this apply to every responses?

```javascript
server.ext('onPostHandler', function(req, res) {
  req.response.source = req.response.source.toJSON();
  res(req.response);
});
```

**Comment by hueniverse** [comment]
`server.ext()` on the `onPreResponse` or `onPostHandler` is probably what you want. You will get a better answer by posting the question here: https://github.com/hapijs/discuss instead.

**Comment by Marsup** [comment]
Also such ext can be put on the route ext property.
