### ISSUE TITLE
CORS Headers not being set

### ISSUE THREAD

**Issue by randallmeeker** [hapijs/hapi#3154]
There are a lot of CORS issues, I think I read all that apply and have come up empty handed. 

Setup
```
server.connection({
  host: '0.0.0.0',
  port: 1337,
  routes : {
    cors: true
  }
})
```

Using chrome these are the headers I'm getting back when making a pre-flight `OPTIONS` request.
```
HTTP/1.1 200 OK
content-type: application/json; charset=utf-8
cache-control: no-cache
vary: accept-encoding
content-encoding: gzip
Date: Tue, 17 May 2016 19:09:23 GMT
Connection: keep-alive
Transfer-Encoding: chunked
```

None of the cors headers getting set?

Node v5
Hapi v13.4

I have also tried setting `cors:true` on the route config, same response. I know that cors is getting initiated due to the status 200 on the pre-flight request. When I turn cors off I get the expected 404 status.

I have attempted a Console log here: https://github.com/hapijs/hapi/blob/master/lib/cors.js#L131 , based on other issues read. I get no console log triggered.

**Comment by mtharrison** [comment]
It's possible that there are some headers being sent with the request that are not whitelisted. You have to explicitly allow them, it's not enough to just set cors to `true`.

Try logging [here](https://github.com/hapijs/hapi/blob/master/lib/cors.js#L119):

```js
console.log(headers, settings._headers);
```

If there are any headers in the first list, that aren't also in the second list, that's the issue and you need to allow them by setting the `config.cors.additionalHeaders` setting.

**Comment by randallmeeker** [comment]
THANKS, was missing the `xsrf-token`, and I thought I checked that. I could not imagine with all the other CORS issues that mine was actually valid.
