### ISSUE TITLE
Setting up server to serve Angular2 application

### ISSUE THREAD

**Issue by matthewhardern** [hapijs/hapi#3175]
Hi, I would just like some help setting up angular2 to run from a public folder under hapijs. Atm i have read several other issues about this, but none seem to resolve my problem.

any help would be greatly appreciated.

**Comment by AdriVanHoudt** [comment]
What is it that you want to do exactly and what problem(s) are you facing?
Also general hapi question should go https://github.com/hapijs/discuss (the hapijs/hapi issues are for hapi bugs etc)

**Comment by matthewhardern** [comment]
well i am trying to use this:

server.ext('onPreResponse', function (request, reply) {

        var response = request.response;

        console.log(request.url);

        if (!response.isBoom ||
            response.output.statusCode !== 404) {

            return reply();
        }

        reply.file('./public/index.html');

    });

to route 404's back to index.html but just get system js can not be found in the angular app, well returns index.html instead of the system.js file.

**Comment by gergoerdosi** [comment]
Look at the boilerplates: http://hapijs.com/resources#Boilerplates. There are examples for React, Angular, etc.

**Comment by blex2011** [comment]
I looked, I see nothing for Angular2

**Comment by MaheshSasidharan** [comment]
I think this was added later on.

https://github.com/ptpaterson/hapi-angular-quickstart
