### ISSUE TITLE
No docset available for Dash

### ISSUE THREAD

**Issue by likeabbas** [hapijs/hapi#3176]
Hi,

While this isn't a huge problem, it would be awesome if there was an official docset for [Dash :)](https://kapeli.com/dash).

**Comment by danielb2** [comment]
There is, it's 3rd party user contributed

**Comment by danielb2** [comment]
11.1 version is available

![screen shot 2016-05-22 at 4 09 17 pm](https://cloud.githubusercontent.com/assets/26678/15457085/906f1f1a-2037-11e6-9370-473890aee5ba.png)

**Comment by hueniverse** [comment]
That's something you can bring up in hapijs/discuss.
