### ISSUE TITLE
Nginx + HapiJS CORS header on error 5xx

### ISSUE THREAD

**Issue by furyscript** [hapijs/hapi#3177]
I have HapiJS server with option `cors: {origin: ['*']}` so when server is running, my javascript frontend (with an `$http`) can access to HapiJS's API. But, If the server is down, the header `Access-Control-Allow-Origin` is not present.

So, how can I pass it from Nginx proxy if it get error like `5xx` ? I use `add_header 'Access-Control-Allow-Origin' '*';` but not work (the header in not present in `Response Header` field).

**Comment by kanongil** [comment]
This doesn't sound like a hapi issue, but more of a usage / nginx question. Try asking in the [hapijs/discuss](https://github.com/hapijs/discuss) instead.

**Comment by furyscript** [comment]
Somebody can help me? I also ask on SO and hapijs/discuss ...
