### ISSUE TITLE
add before hook for every route

### ISSUE THREAD

**Issue by xycloud** [hapijs/hapi#3180]
is there any easy way of adding a before hook for every route in a same place?

for example,
we have two routes:

```
/api/foo
/api/bar
```
and now we want add add some validation for each route before response.
if there are 100 routes, how can we add the before hook in same place?

**Comment by devinivy** [comment]
You can apply an extension to all routes on a group of connections, all routes in a plugin, or a single route.  It sounds like you might want to do one of the first two.

Check out `server.ext(type, method, options)` in the docs.  The `{ sandbox: true }` option will ensure that the extension is only applied to the routes in the current plugin.  Omitting that option will apply the extension to all connections selected by `server`.

In the future, questions like this are best asked in [hapijs/dicuss](https://github.com/hapijs/discuss).  Good luck!
