### ISSUE TITLE
how can i use the session

### ISSUE THREAD

**Issue by xycloud** [hapijs/hapi#3184]
is there any guideline for using the hapi session?

**Comment by devinivy** [comment]
Sessions are often a combination of cookies and authentication.  Cookies can be defined and set manually with [`server.state()`](https://github.com/hapijs/hapi/blob/master/API.md#serverstatename-options) and [`response.state()`](https://github.com/hapijs/hapi/blob/master/API.md#response-object).  Authentication is provided by auth schemes and strategies.  You can learn more about this in the docs and in tutorials on hapijs.com.

One cookie-based implementation of sessions can be found at [hapijs/hapi-auth-cookie](https://github.com/hapijs/hapi-auth-cookie).

In the future, questions like this should be asked in [hapijs/discuss](https://github.com/hapijs/discuss).  Feel free to open an issue over there to continue the conversation!

**Comment by xycloud** [comment]
thanks very much
