### ISSUE TITLE
isn't it strange, that server.initialize require connections to be configured?

### ISSUE THREAD

**Issue by PavelPolyakov** [hapijs/hapi#3188]
Hi,

Currently I'm writing the tests, and met the next issue.

My module `trainings` has dependency from the module `KB`, which is stated in the `attributes` of the module:
```javascript
exports.register.attributes = {
    pkg: require('./package.json'),
    dependencies: ['KB', 'i18n']
}
```

Im my test, I gather minimalistic server with all the modules which are needed, in order to test the `trainings` module:

```javascript
server = new Hapi.Server();
        // server.connection({
        //     host: 'localhost',
        //     port: 8000
        // });
        server.register([require(process.cwd() + '/app/i18n'),
            //require('KB'),
            require('trainings')], (err) => {
            // abort everything in case we have failed to register the plugin
            if (err) {
                throw new Error(`Failed to register the plugin (${err})`)
            }

            server.initialize((err) => {
                if (err) {
                    throw new Error(`Failed to register server (${err}`);
                }

                done();
            })
        });
```

I've learned, that there are two ways to force hapi to check for the dependencies: `server.start()` and `server.initialize()`. I have selected the 2nd one, because I don't want to start the server.

But, in such case, there is an error in the callback:
![image](https://cloud.githubusercontent.com/assets/839290/15805650/0f713592-2b31-11e6-889a-c3a789420ff6.png)

It could be "cured" in case I will uncomment the `connection` line in the code.

However, it's obvious that this code has no sense, because for real, we don't need any connection.

What do you think?

Regards,

**Comment by mtharrison** [comment]
A "server" is just a proxy for one or more connections, so it's not just `initialize()` that requires a connection, you also can't add routes without connections, because each route is associated with a connection not a server. Normally in tests [you'll see this done](https://github.com/hapijs/hapi/blob/master/test/auth.js#L38).

**Comment by PavelPolyakov** [comment]
@mtharrison 
Thanks, I've also discovered that I can just add an "empty" connection, which looks nicer then the full one.

Regards,
