### ISSUE TITLE
non rest route

### ISSUE THREAD

**Issue by xycloud** [hapijs/hapi#3191]
how can i get the param in non restful route:

```
server.route({
  path: '/xx',
  method: 'GET',
  handler: function(req, reply) {
    var name = req.params.name;  //access "/xx?name=foo"
    console.log(name);
  }
});
```
but the name is always NaN

**Comment by simon-p-r** [comment]
Try `request.query.name`

**Comment by xycloud** [comment]
thx

**Comment by simon-p-r** [comment]
Best to ask questions [here](https://github.com/hapijs/discuss/issues) in future!

**Comment by Marsup** [comment]
@xycloud you've be told several times to ask your questions on the other repo, so please do from now on.
