### ISSUE TITLE
Server.inject with credentials silently fails

### ISSUE THREAD

**Issue by GuilhouT** [hapijs/hapi#3192]
Hi,

We are trying to bypass the authentication strategy to test one of our endpoints. Unfortunately, the `server.inject` call fails whenever we include the `credentials` property in the `options` param.
We tried removing the auth strategy for this route specifically as well as for the entire app but the problem remains as long as we try to pass the credentials.

Here's a snippet:

```
const Test = require('tape');
const Server = require('../../server');

Test('User#list endpoint',function (t) {
  const options = {
    method: 'GET',
    url: '/users',
    credentials: {
      id: 'Iajv6xUl',
    },
  };

  Server.init(server => {
    server.inject(options, response => {
      console.log('this never runs');
      t.equal(response.statusCode, 200, 'should reply with 200 HTTP status code');  
      server.stop(t.end);
    });
  });
});
```

**Comment by mtharrison** [comment]
I can't see anything obviously wrong in this snippet. 

You'll need to supply more code, ideally a complete, runnable example showing the issue so we can replicate. Strip things down to the bare minimum that breaks if you don't want to share everything.

**Comment by GuilhouT** [comment]
@mtharrison After digging deeper we found it was actually an issue with [hapi-plugin-co](https://github.com/rse/hapi-plugin-co/pull/1).

We thought it was linked to hapi itself because it was happening only with the `credentials` property...

Thanks for your help!
