### ISSUE TITLE
Specify order or priority of helpers.

### ISSUE THREAD

**Issue by monkeytroy** [hapijs/hapi#3195]
Using hapi, vision and handlebars I want to created helpers to do jade style code blocks.   In a partial or page I want to define a block of code to be placed in the head of the layout..  not in the {{{content}}} section of the layout. 

Example template:  
 `
<html>
  <head>
      {{#myBlock}}{{/myBlock}}
  </head>
  <body>
    {{{content}}}
  </body>
</html>
`

and in pages and partials I have this

`
  <div>My body content</div>
  {{#extendTo "css"}}
    
    <style> div: { color: red; } </style>
  {{/extendTo}}
`

My helper for extendTo stores the style text and returns empty string.  The helper for myBlock takes the stored value and returns it, making it appear in the head. 

This works some of the time, but the problem is that the helper blocks are processed in an unknown order.   In my testing the '#myBlock' in the template are sometimes processed first and then the '#extendTo' blocks from pages / partials are processed after from within the partials.  This means that the style does not make it into the page.

I am not sure if a view is built first from it's partials, pages and layout... and THEN the helper blocks are all processed top down or something?   

Is there any way to specify a priority for helper blocks?   If a priority could be set I could make sure my extendTo blocks are processed first, guaranteeing that the content is in memory before any of the myBlock helper blocks are processed.  

It almost seems like helpers should be processed on partials first, then pages, then layouts.   Any way to enforce this? 

Thanks.

**Comment by Marsup** [comment]
That's not really a hapi problem, rather a handlebars problem.

**Comment by mtharrison** [comment]
@monkeytroy you might get help in vision repo. afaik template and subviews are _always_ rendered to a string before layout is touched.

Either way, this isn't a hapi core issue.

**Comment by monkeytroy** [comment]
Ok.  Thats part of what I was trying to figure out.  Since the helpers were defined in my vision / hapi view configuration it seemed like a possibility that the hapi layout process might be where I am seeing the issue.  

But if the templates are rendered first that points me elsewhere.  thanks.
