### ISSUE TITLE
Generate hapi restful server using swagger

### ISSUE THREAD

**Issue by kuncevic** [hapijs/hapi#3200]
I just discovered this tool https://github.com/swagger-api/swagger-codegen and just wondering is it possible to generate hapi thing using something like that?

**Comment by nlf** [comment]
for future reference, general questions like this should be opened in hapijs/discuss

to answer your question, sure it's possible. does it exist already? not to my knowledge. shouldn't be that hard though

**Comment by nlf** [comment]
i'm going to close this, but if you'd like to continue the conversation feel free to open a new issue at [hapijs/discuss](https://github.com/hapijs/discuss)
