### ISSUE TITLE
404 errors on home page

### ISSUE THREAD

**Issue by bridiver** [hapijs/hapi#3205]
We see occasional 404 error for https://brave.com
https://github.com/brave/brave-website has hapi configuration and all related code. We are running on Heroku and the problem is intermittent. We are seeing debug 404 messages in the logs, but no other useful info

**Comment by bridiver** [comment]
I know the description is not very useful and if there is a setting that will provide more info in the logs we can put it in

**Comment by kanongil** [comment]
Which routes / paths are returning 404?

**Comment by bridiver** [comment]
the home page `https://brave.com`

**Comment by bridiver** [comment]
should return a static page `./public/index.html`

**Comment by kanongil** [comment]
Most likely the 404 is generated in my inert plugin. This should only be output if the file is missing from the file system itself. Eg. my best guess is that the file is not there when requested, possibly during a deploy? Or a heroku issue file system level issue?

**Comment by bridiver** [comment]
I think a Heroku issue is unlikely because this has happened over multiple deploys and each one is an independently generated read-only `slug`. The generated output files are committed to the git repo so they should be there on deploy even if something went wrong in the deploy process. The intermittent nature of the problem would also suggest that it's not a missing file, but I'm open to testing it. Is there something we can do that will log the reason for the 404?

**Comment by bennyschmidt** [comment]
@kanongil Thanks for replying. The way 404 works is fine (JSON by default, HTML file if there is one), but we're wondering why it's happening -- if there's a way to log what's going on. In any case, we deployed a proper 404 page yesterday, but the issue remains of why the 404 is sometimes occurring.

**Comment by devinivy** [comment]
Is it possible to find out if it happens during deployments?

**Comment by kanongil** [comment]
The `.stack` stack trace property on the `Boom` error can show exactly where the 404 is triggered.

Also, you should probably change your 404 handler to the `onPreResponse` extension point. The `onPostHandler` extension is only triggered for registered routes.

**Comment by bennyschmidt** [comment]
@kanongil Thanks Gil. It traces back to a few files in the `Inert` module you mentioned before, but unclear why it's caused or why it's so rare that it happens etc. Is this a known issue with the npm itself?

<img width="889" alt="screen shot 2016-06-16 at 8 28 25 am" src="https://cloud.githubusercontent.com/assets/1307594/16122534/527374d6-339c-11e6-8911-5f11eb558217.png">

I moved the 404 from `onPostHandler` into `onPreResponse` just now. This shouldn't have any effect on why it is 404'ing in the first place though right? Thanks.

**Comment by kanongil** [comment]
Are you sure that it is the `/` path that fails? The trace shows that it has matched the `directory` handler, which should not happen. What is `request.path` when it fails?

Regarding the extension point, the change just means that it will return the nice 404 on eg. `POST` requests to unhandled routes.

**Comment by bridiver** [comment]
I wonder if this is a conflict with the directory handler and the individual file maps? If a directory handler is specified, what file does it look for when serving `/`?

**Comment by bridiver** [comment]
I'm redeploying now with the file map from / => ./public/index.html removed. I noticed that none of the errors include the actual url. That makes it really hard to setup an alert in our log monitoring system. Is there a way to capture that in error log?

**Comment by hueniverse** [comment]
@kanongil ?

**Comment by bridiver** [comment]
I haven't heard any more reports of 404s since the change

**Comment by hueniverse** [comment]
Great.

**Comment by bridiver** [comment]
it appears that the problem is still ongoing and it is stranger now than ever. We have a 404 page that you can see at https://brave.com/fdsafdsa, but we have received multiple reports of the default json 404 page

**Comment by bridiver** [comment]
config https://github.com/brave/brave-website/blob/staging/server.js

**Comment by mtharrison** [comment]
Are you sure it's the JSON response for 404. And not say 403 like this page
shows? https://brave.com/assets/

**Comment by bridiver** [comment]
https://slack-files.com/T04PX1BU8-F2JP1KB7E-dc3a6f70dc

**Comment by kanongil** [comment]
This should only happen if the `public/404.html` file is somehow not available when serving the 404. I'm still guessing that this is the actual culprit.
