### ISSUE TITLE
override default cache headers for error pages

### ISSUE THREAD

**Issue by bridiver** [hapijs/hapi#3206]
We would like to change the default `cache-control` header from `no-cache` to `private` to prevent our CDN from caching 404s, etc..

**Comment by devinivy** [comment]
You can set default route options (including client-caching options) on the server- and connection- level.  See `connections.routes` here: http://hapijs.com/api#new-serveroptions.  For further discussion or questions please feel free to open an issue at [hapijs/discuss](https://github.com/hapijs/discuss), which is better suited to general-purpose questions about hapi and its usage.

**Comment by bridiver** [comment]
this is only for error pages and @hueniverse told me to submit an issue for it

**Comment by bridiver** [comment]
actually it's not just for error pages, we'd like to override it for any page that would normally be no-cache

**Comment by hueniverse** [comment]
@devinivy they are asking for a different default value when caching is currently 'no-cache'. The 404 is just an example.

**Comment by devinivy** [comment]
Ah, I understand now– sorry about that!

**Comment by bridiver** [comment]
np, probably a bad explanation on my part

**Comment by kanongil** [comment]
Documentation for the new `cache.otherwise` option is missing.
