### ISSUE TITLE
Remove part of url before redirect after FB callback

### ISSUE THREAD

**Issue by keerthivasan-r** [hapijs/hapi#3209]
Hi, I have integrated with FB using hapi-auth-facebook plugin. Everything works as intended, but
when i try to redirect to another url, it gets appended with **#_=_**. This cause problems in the routes.

Is there a way i can remove it before redirecting? I also don't know how this gets added to the url, that i provide. Please refer this link for more details [http://stackoverflow.com/questions/7131909/facebook-callback-appends-to-return-url](url)

Can someone face the same problem?

**Comment by hueniverse** [comment]
Please ask general question in https://github.com/hapijs/discuss
