### ISSUE TITLE
Question on request performance with server methods

### ISSUE THREAD

**Issue by Crispy1975** [hapijs/hapi#3210]
We use Hapi and want to make use of server methods as efficiently as possible as we don't like including the same modules all over our handlers. Is there a tipping point where having too many custom server methods would slow down requests? As with anything putting too much in one place is bound to slow things a little, but I guess the question is (we haven't run tests yet) how much would requests be slowed by, 10s of ms perhaps, more?

Would be great to hear if others have a lot on the server methods and see how you guys are doing.

**Comment by hueniverse** [comment]
Please ask general question in https://github.com/hapijs/discuss. Once a method has been registered, you pad for the method wrapper (based on caching and other options you choose) and a simple hash lookup in the `server.methods` object.
