### ISSUE TITLE
Assert request in handler

### ISSUE THREAD

**Issue by guidsen** [hapijs/hapi#3211]
I have multiple endpoints starting with `/networks/{networkId}/*`. I don't want to have logic to find a network and execute some extra validation on it, in every handler. Is there any way to solve this on a higher level? Ex. plugins/server method etc?

In every handler I have the following boilerplate code:

```
import networkRepo from 'common/repositories/network';

// handler.js
export default (req, reply) => {
  return networkRepo.findById(req.params.networkId).then(network => {
    // Logic to validate whether the logged user belongs to the network
    // Logic where I need the network instance
  });
}
```

The best situation would be:

```
// handler.js
export default (req, reply) => {
  console.log(req.network); // This should be the network instance
}
```

**Comment by simon-p-r** [comment]
@guidsen I answered your question on stackoverflow.  In future you are best asking questions like this on the discuss repo [here](https://github.com/hapijs/discuss/issues), stackoverflow or gitter channel for help.

**Comment by guidsen** [comment]
@simon-p-r Thanks for your time. I think you've misinterpreted my question. I want to be able to pass a object to my request that I can access via my handlers. I didn't know about the discuss repo, thanks for pointing out!

**Comment by mtharrison** [comment]
https://github.com/hapijs/discuss/issues/292
