### ISSUE TITLE
init cache[discuss]

### ISSUE THREAD

**Issue by xycloud** [hapijs/hapi#3212]
from the tutor, if we want to use redis as hapi cache backend, we should register it when init Hapi.Server,

```
var server = new Hapi.Server({
  // Configure the server cache by defining a catbox client which uses the "catbox-redis" adapter.
  cache: {
    engine: require('catbox-redis'),
    host: '127.0.0.1',
    port: '6379',
    password: '',
  },
});
```

can I register in for an existed Hapi.Server instance, like below?
```
server = new Hapi.Server();

server.cache = xxx
```

**Comment by devinivy** [comment]
You can provision a new cache programmatically with [`server.cache.provision()`](https://github.com/hapijs/hapi/blob/master/API.md#servercacheprovisionoptions-callback).

**Comment by xycloud** [comment]
that not works in hapi with version 8.8.1

**Comment by devinivy** [comment]
Yeah, it's actually a relatively new feature– v13.1 and beyond.  In v8 you wont be able to provision a new cache, but you will be able to carve-out a new segment of an existing cache using `server.cache()`.

**Comment by xycloud** [comment]
so i have to init it within the server instance?

**Comment by devinivy** [comment]
As far as I know, yes– on hapi v8 you have to define the cache instances in the server options.

**Comment by xycloud** [comment]
ok, thanks!
