### ISSUE TITLE
Extend plugin attributes to support Joi schema for options.

### ISSUE THREAD

**Issue by sberryman** [hapijs/hapi#3213]
# Extend plugin attributes to support plugin option validation
http://hapijs.com/api#plugins

Right now attributes are typically defined by requiring `package.json` but you only pull in name and version. You also support `multiple`, `dependencies`, `connections` and `once`. I find myself adding this validation logic to almost every plugin I write. It would be nice to have this as a base HAPI feature and does not cause any breaking changes.

## Benefits
1. Supports self documentation of options.
2. It protects people from dangerously starting a server with missing configs
3. A lot of times when configs are missing for a plugin it takes a while to track them down (on larger projects)

## Proposed attribute

- `validate` - optional validation of plugin options.

    - `schema` - the validation schema. Can be a joi type object or a plain object where every key is assigned a joi type object.
    - `options` - options to pass to Joi. Defaults to no options.
    - `failAction` - defines what to do when validation fails. Options are:
        - `error` - fatal error, server will not start. This is the default value.
        - `log` - log the error but let the server start.

### Example

```javascript
const register = function (server, options, next) {

    server.route({
        method: 'GET',
        path: '/test/' + options.path,
        handler: function (request, reply) {

            return reply('ok');
        }
    });

    return next();
};

register.attributes = {
    name: 'test',
    version: '1.0.0',
    validate: {
        schema: {
            path: Joi.string().required()
        },
        options: {
            abortEarly: false
        },
        failAction: 'error'
    }
};
```

**Comment by sberryman** [comment]
Started working on tests and code here: https://github.com/teeleader/hapi/tree/issue-3213.

@hueniverse, hopefully this is something that is merge worthy and I'm not wasting my time here. If I am let me know and I'll halt work on this ASAP.

This is my first time digging into the HAPI code and hopefully I'm not screwing things up too badly. I'm not excited about adding a requirement of Joi to `lib/plugin.js` but it was required as I couldn't reuse `apply()` from `lib/schema.js`.

I still have to fix several of the tests and complete the code but this is a WIP.

**Comment by hueniverse** [comment]
I don't understand what you want to validate.

**Comment by sberryman** [comment]
Sorry, I would like to `Joi.validate()` the options passed to a plugin. In almost every plugin I write that expects options, I typically create a Joi schema to validate and create the default options. I find this is much more expressive and provides extremely clear and familiar error messages to developers. I would like to extend HAPI to allow defining an options schema via Joi or a validation function that will validate/assert the options passed to the plugin.

**Comment by hueniverse** [comment]
I don't see the point. How is this better than just validating the options as the first thing you do inside register()?

**Comment by sberryman** [comment]
Repetition, I do it in almost every plugin. I figured other people most likely do as well. This is simply a convince and follows all the other validation HAPI does on our behalf.

Clearly it doesn't seem like a big time saver to anyone else so I'll just close the issue.

**Comment by hueniverse** [comment]
This doesn't solve anything though. You are just moving code around. You still have the same repetition just in a different part of the code.

**Comment by sberryman** [comment]
Very true, it moves the validation logic to HAPI and out of the plugin. In reality it only saves a few lines of code in the plugin. It slightly reduces the code coverage tests the developer has to write for validating options as part of registration. Probably not worth the additions to core HAPI though?
