### ISSUE TITLE
Support failAction function on validation response failures

### ISSUE THREAD

**Issue by alexspence** [hapijs/hapi#3214]
I can configure a custom handler to handle validation failures for request validation.  It would be nice to be able to do the same for response validation.  Specifically, we need the ability to add a requestId header to help with issue reports.

Let me know if you want a PR.

**Comment by alexspence** [comment]
This seems pretty easy, I'll come up with a PR.

**Comment by hueniverse** [comment]
I need more info. Can you show a mock example?

**Comment by alexspence** [comment]
Our code looks something like this:
```


server.ext('onPreResponse', (request, reply) => {
  request.response.header('x-request-id', UUID.v4());
})

const route = {
  method: 'GET',
  path: '/products/{id}/most_helpful',
  config: {
    handler: reviewController.mostHelpfulByProduct,
    description: 'List of Most Helpful Reviews',
    validate: {
      params: Joi.object().keys({
        id: reviewDef.params.productId().required()
      }),
      query: Joi.object().keys({
        perpage: reviewDef.params.perpage().default(5),
        positiverating: reviewDef.params.positiveRating(),
        negativerating: reviewDef.params.negativeRating(),
        threshold: reviewDef.params.threshold(),
        expand: reviewDef.params.expand()
      })
      failAction = (request, reply, source, error) => {
        return responseDecorator.sendError(request.context, reply, error, 500);
      };
    },
    response: {
      failAction = (request, reply, source, error) => {
        return responseDecorator.sendError(request.context, reply, error, 500);
      };
    }
  }
}
```

Without the failAction's, when Joi Validation fails, onPreResponse is never called and the requestId is never added to the response header.  I am currently able to do this on the request side by implementing failAction, but on the response side the function is not implemented.

I took a stab at it locally and it worked well.

https://github.com/alexspence/hapi/commit/bdaad8f616c40df4d373ac099224b3a367605ac3

**Comment by alexspence** [comment]
@hueniverse Let me know if you need more information.

**Comment by alexspence** [comment]
Not to pester, but any way to get some attention on this issue?
