### ISSUE TITLE
Integrated Platform for Real Time Analysis Big Datas (AI = DeployR + Hapi.js + Big Data)

### ISSUE THREAD

**Issue by maxprog** [hapijs/hapi#3215]
Company name: **JRB System** (www.jrbsystem.com)
Product name or use case: **Integrated Platform for Real Time Analysis Big Datas (AI = DeployR + Hapi.js + Big Data)**
Is it in production or development: **PRODUCTION, DEVELOPMENT**
Contact information for further questions: info@jrbsystem.com
Contact information for security alerts: info@jrbsystem.com
Link to logo if we can showcase your company on the new site: **http://jrbsystem.com/jrbsystem.png**
User quote (with attribution) about your hapi user experience: 
Framework for Real-time (statistical) analytics Big Data 
Details:
Databases: NoSQL - MongoDB
Languages: R Language, JavaScript (V8 Engine)
Server: DeployR, (Hapi.js)
JavaScript Framework: Node.js(Hapi.js), Socket.IO, AngularJS
Node.js as a middlware running on http,https protocols with authorization process regardless to Operating System. Serving sending and storage huge parts of datas, real time analysis, 
Communication between Client<=>Node.js - Requests are submitted by the client application through the server application REST API. 
Communication between Node.js<=>DeployR - used DeployR javaScript libraries, CRUD operations of massive datas on MongoDB
Implemented Pagination of sending datas &  RBroker functionality

**Comment by hueniverse** [comment]
This should be posted in https://github.com/hapijs/hapijs.com
