### ISSUE TITLE
Infinite recursion when subclassing Server

### ISSUE THREAD

**Issue by sholladay** [hapijs/hapi#3217]
I would like to subclass `Server` and override `start()` so that it can take care of all my plugin and route registration ceremony in one fell swoop as a black box.

But I ran into a problem when trying to return the promise from hapi's `start()` method.

```js
'use strict';

const {Server} = require('hapi');

class MyService extends Server {

    constructor() {
        super();
        super.connection({ port : 3000 });
    }

    start() {
        return super.register(require('h2o2')).then(() => {

            // super.route([
            //     ... routes ...
            // ]);

            // Errors out!
            return super.start();
        });
    }
}

const myService = new MyService();
myService.start().then(() => {
    console.log('My service listening at', myService.info.uri);
});
```

## Error

```js
Error: Plugin h2o2 already registered in: http://Seth-Laptop.local:3000
    at Object.exports.assert (/Users/sholladay/Code/my-service/node_modules/hapi/node_modules/hoek/lib/index.js:737:11)
    at each (/Users/sholladay/Code/my-service/node_modules/hapi/lib/plugin.js:287:26)
    at iterate (/Users/sholladay/Code/my-service/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/Users/sholladay/Code/my-service/node_modules/hapi/node_modules/items/lib/index.js:39:9)
    at MyService.internals.Plugin.register (/Users/sholladay/Code/my-service/node_modules/hapi/lib/plugin.js:320:11)
    at Promise (/Users/sholladay/Code/my-service/node_modules/hapi/lib/promises.js:24:16)
    at Object.exports.wrap (/Users/sholladay/Code/my-service/node_modules/hapi/lib/promises.js:13:12)
    at MyService.internals.Plugin.register (/Users/sholladay/Code/my-service/node_modules/hapi/lib/plugin.js:164:25)
    at MyService.start (/Users/sholladay/Code/my-service/index.js:13:22)
    at Promise (/Users/sholladay/Code/my-service/node_modules/hapi/lib/promises.js:24:16)
```

Now the interesting thing is that if I replace `return super.start()` with this ...

```js
return new Promise((resolve, reject) => {
    super.start((err) => {

        if (err) {
            reject(err);
            return;
        }

        resolve();
    });
});
```

... then everything works perfectly.

I tried replicating the problematic pattern but without subclassing and that also worked fine.

**Comment by mtharrison** [comment]
I think the issue is that `super()` refers to a class and you're trying to call non-static methods on it. Might work if you do:

```js
'use strict';

const { Server } = require('hapi');

class MyService extends Server {

    constructor() {
        super();
        this.connection({ port : 3000 });
    }

    run() {

        return this.register(require('h2o2')).then(() => {
            
            return this.start();
        });
    }
}

const myService = new MyService();

myService.run().then(() => {

    console.log('My service listening at', myService.info.uri);
});
```

Personally though if I was wrapping a hapi server, I'd just have my object hold onto one via a property (e.g. `this.server = new Hapi.Server()`) than subclass it.

**Comment by sholladay** [comment]
That only works because you are using a `run()` wrapper instead of overriding `start()` in the subclass. It doesn't have anything to do with `super`. If you change all your `this` references back to `super`, it still works perfectly.

To be clear, `super` isn't really a reference to a class. In fact it is a keyword that helps you delegate behavior to the parent, without having a reference to it. Inside of subclass prototype methods, `super.foo()` calls the parent's prototype method named `foo()`. It does **_not_** call a static method named `foo()`.

For example, this code ...

```js
class Animal {
    constructor() {
        console.log('constructing an Animal');
    }
    foo() {
        console.log('Animal prototype foo');
    }
    static foo() {
        console.log('Animal static foo');
    }
}

class Dog extends Animal {
    constructor() {
        super();
        console.log('constructing a Dog');
    }
    foo() {
        super.foo();
        console.log('Dog prototype foo');
    }
}

const dog = new Dog();
dog.foo();
```

... prints:

```js
constructing an Animal
constructing a Dog
Animal prototype foo
Dog prototype foo
```

So we have two separate workarounds to my problem. Use a different method name instead of overriding `start()` or use a callback to hapi's `start()` and manually construct a promise myself (see my original post).

The underlying problem is that when I call hapi's `start()`, it seems to be calling `this.start()`. This would cause infinite recursion if it weren't for `register()` throwing an error when the same plugin is registered twice.

From a quick glance, this looks like the problem: https://github.com/hapijs/hapi/blob/ed195fad213a9da0f0762271c4907f4218e2abaf/lib/server.js#L160

**Comment by mtharrison** [comment]
You're right, my bad on `super()`. Still think you'd be better not subclassing.

**Comment by hueniverse** [comment]
@sholladay Feel free to bring this up in https://github.com/hapijs/discuss but this is not a use case I care about to support, regardless of the cause.

**Comment by sholladay** [comment]
Okay, fair enough. Would you accept a patch if it were trivial?

The solution is dead simple.

This line:

```js
        return Promises.wrap(this, this.start);
```

... becomes ...

```js
        return Promises.wrap(this, internals.Server.prototype.start);
```

I would argue that this is more technically correct, for the neat freak in us all. And if the extra characters bother you, this could be improved by using a named function.

Also, while I love consistency, I should note that `start()` is the only place I need this.

😇

**Comment by hueniverse** [comment]
It would have to be consistent and tested in every case. Seems silly.
