### ISSUE TITLE
is there a setting for emitting timestamps in logs? 

### ISSUE THREAD

**Issue by jcollum** [hapijs/hapi#3218]
I don't see one.

```
// request.js:242 (similar in plugin.js:493)
    if (this.server._settings.debug &&
        this.server._settings.debug.request &&
        Hoek.intersect(tagsMap, this.server._settings.debug.request, true)) {
        console.error('Debug:', event.tags.join(', '), (data ? '\n    ' + (data.stack || (typeof data === 'object' ? Hoek.stringify(data) : data)) : ''));
    }

```

The timestamp field seems like it's not used. How about adding in `console.error('Debug @ '+ new Date(event.timestamp), ': ', event.tags.join(', '),`? 

I ask because I was looking at my logs today (pm2) and found that I had about 5 error events in there but no idea when they happened, so it will be much more difficult to track down what happened. 

Want me to PR it?  I thought I should ask first since I've not PRd to this repo before.

**Comment by mtharrison** [comment]
Do timestamps really matter for debug mode? It's only really intended for development. For production logging you should probably be using Good and one of the reporters which _do_ log timestamps.

**Comment by jcollum** [comment]
> one of the reporters which do log timestamps

I'm using Bunyan & PM2, not something weird. The PM2 logs are split into error and normal streams. The error stream, because of how Hapi is logging, does not contain timestamps. 

The timestamp object is passed in to the function `internals.Request.prototype.log = function (tags, data, timestamp, _internal) {`so I don't see why actually using it would be an issue. It's probably not passed in for fun.

**Comment by hueniverse** [comment]
hapi logging is designed with other plugins in mind. The timestamp is not ignored, it is passed to the event emitter. Relying on this console log for production is wrong.

**Comment by jcollum** [comment]
But I'm not in production. Having that timestamp will help me sort out what happened when the app failed. 

Should I be telling Hapi to use the Bunyan logger that I'm instantiating in my API? That might be the real issue here...

**Comment by hueniverse** [comment]
I know this might sound silly given how easy it would be to just add stuff to that console log, but the point I am trying to make is that the core module should not even have that console log in there. It is there as a last resort when people just hack around with the framework and stuff doesn't work to help them see they are missing something. It is your responsibility to use the hapi `server.on()` API to listen to all the errors you care about and handle them. You can easily do that with the good-console plugin. Just add that to your application or just add your own `server.on('request-error')` handler.

**Comment by jcollum** [comment]
Have you considered adding that (`request-error`) to any of the getting started pages? This is the first I've heard of it and can't find it on any of the first 3 basic instruction pages I've seen.

**Comment by hueniverse** [comment]
I don't write guides and tutorials, I just write code. Feel free to suggest it on the hapijs.com repo or even make a PR.
