### ISSUE TITLE
Revise server.handler design

### ISSUE THREAD

**Issue by b123400** [hapijs/hapi#3220]
Hello,

I come across `server.handler('name', handler)` and think the design is not very good.

It is possible to run the following code without warning:

```Javascript
server.handler('A', handlerA);
server.handler('B', handlerB);

server.route({
    method: 'GET',
    path: '/',
    handler: {
      A: 'a data',
      B: 'b data'
    },
  });
```

- There is no specification about which handler will be used,
  - The code used to selected the handler is `const type = Object.keys(handler)[0];` which means random result. ([Here](https://github.com/hapijs/hapi/commit/beb3d50e1561962b68933b3a91cce93ce57810e8#diff-48151be9b298d43428374cd794d41106R202))
- Passing an object that should only have 1 key to `handler` seems strange to me, the name handler sounds like function, this is pretty subjective though.

I suggest this function should be removed and we should recommend people to create handler like this:

```Javascript
server.route({
    method: 'GET',
    path: '/',
    handler: makeHandler('some data')
  });

function makeHandler(data) {
  return function(request, reply) { ... };
}
```

**Comment by Marsup** [comment]
Nope, can't happen. https://github.com/hapijs/hapi/blob/master/lib/schema.js#L251-L255

**Comment by Marsup** [comment]
On the subjective part, I don't think it's strange, a handler is not necessarily a function. Also, your suggestion will make it way harder to create plugins that expose new handlers, or it will be way more verbose.

**Comment by mtharrison** [comment]
@b123400 without warning? That throws for me:

```
Error: Invalid routeConfig options (GET /) {
 ...
 "handler" [1, 2, 3]: {
    "A": "a data",
    "B": "b data"
  }
}

[1] "handler" must be a Function
[2] "handler" must be a string
[3] "handler" must have 1 children
```

**Comment by hueniverse** [comment]
I don't mind feedback on how to improve features. But to say you don't like this feature so we should remove it is not helpful.
