### ISSUE TITLE
overlap joi routes validation

### ISSUE THREAD

**Issue by sabala12** [hapijs/hapi#3222]
Hello,
I have two overlapping routes:

Route A: '/myRoute/{paramater}'
Route B: '/myRoute/'

route A parameter is required via Joi.
The problem is that the validation is checked on all request, and therefore I cannot reach Route B.
I am not sure if I misusing the library, or it is simply not possible to accomplish.

Thanks anyway.

**Comment by DavidTPate** [comment]
Could you post your code for how you have your routes setup?

**Comment by sabala12** [comment]
It look's like that:

`var schema = Joi.object().keys({
    param_a: Joi.String().required(),
    param_b: Joi.String().required()
});

server.route([{
    method: 'GET',
    path: '/MyRoutes/{param_a}/Prefix',
    config: {
        auth: authMethod,
        validate: {
            params: schema.requiredKeys(['param_a'])
        },
        handler: myHandlerA
    }
}, {
   method: 'GET',
   path: '/MyRoutes/{param_a}/Prefix/{param_b}',
   config: {
       auth: authMethod,
       validate: {
           params: schema.requiredKeys(['param_a', 'param_b'])
       },
       handler: myHandlerB
   }
}]);`

**Comment by hueniverse** [comment]
@sabala12 Want to try this fix? https://github.com/hapijs/call/pull/21/files

**Comment by Marsup** [comment]
Well with code it's more obvious. Your usage of Joi is wrong, both keys are required as you specified on L2-3, using `requiredKeys` has absolutely no effect on that, so you got the false impression that it was hitting the wrong route.
