### ISSUE TITLE
How to send and receive data between Hapi and Angular

### ISSUE THREAD

**Issue by lel1234** [hapijs/hapi#3223]
Hello guys,

1) How do you send variables from Hapi in this situation (A JS object for example) : 

`server.route({
        method: 'GET',
        path: '/',
        handler: function (request, reply) {
            reply.file('./public/index.html'});
        }
    });`

2) How to receive it in a .js script included in index.html

3) And how to send data from the .js script to the server ?

PS: I'm trying to make a single page application (SPA) using AngularJS

**Comment by bboysathish** [comment]
Please look into this tutorial (DirectoryHandler) http://hapijs.com/tutorials/serving-files. You need to serve the directory.

**Comment by sfabriece** [comment]
You can just make a rest api which you can connect to from the SPA.
