### ISSUE TITLE
not able to set cookie to the front-end  running in the different server.

### ISSUE THREAD

**Issue by hussainathar** [hapijs/hapi#3224]
Hi ,
I am running **hapi.Js** server in **localhost:8000**  and  **angular Js** server in **localhost:9000**
I am trying to **set cookies**  on reply() from hapi.Js.
on angular server i getting the cookie in the response but it is not setting cookies in the browser .

here is my **server.js**

    server.connection({
    host: 'localhost',
    port: 8000,
    routes: { cors: {
                    credentials: true,
                    
                    origin:['*']
                }
            }});

    server.route({ 

      method: 'POST',

    path: '/login',

    handler: function (request, reply) {

         console.log(request.payload)

        console.log(JSON.parse(request.payload));

        var query={};

        query['postData']={};

        query['query']=JSON.parse(request.payload);

        new userHandler().getUserProfile(query,function (err, data) {

            if (err) {

                return reply("Data not found");
            }

            else { 

                return reply(loginData).state('Name','My_name_is_khan123',{ encoding : 'none', isHttpOnly : true });
            }
        });
    }});

 **response headers**  that i am getting 

```
access-control-allow-credentials:true
access-control-allow-origin:http://localhost:9000
access-control-expose-headers:*
cache-control:no-cache
Connection:keep-alive
content-encoding:gzip
content-type:application/json; charset=utf-8
Date:Tue, 28 Jun 2016 08:30:40 GMT
set-cookie:Name=My_name_is_khan123; HttpOnly
Transfer-Encoding:chunked
vary:origin,accept-encoding
```

can someone help me on this why this response is not setting cookie in my browser  , I m not able to access these headers as well .

**Comment by arb** [comment]
The `isHttpOnly` flag makes it so the cookie isn't accessible in the browser. Set that to `false` (or remove it entirely since it defaults to `false` anyway) and you should see it show up in the browser.

**Comment by v1r** [comment]
Hello there!

This is problematic when the front end and backend are running and diffrent domain... For instance:

frontend:3000 --- request --> backend:3000

The cookie domain will be set to backend domain not the front end one.

**Comment by tonyonlian** [comment]
Default value: of the isSecure   is true。when URL is use  https schema  The cookie can be set successfully when http schema   The cookie cannot be set successfully. 
You use HTTP access instead of HTTPS access,so isSecure is set to false
