### ISSUE TITLE
Recommendations for extending request.auth to routes not configured with auth settings?

### ISSUE THREAD

**Issue by geuis** [hapijs/hapi#3232]
The answer for this used to be using `hapi-context-credentials`, https://github.com/mtharrison/hapi-context-credentials/blob/master/lib/index.js where we could hook into `onPreResponse` and detect if the user had already authenticated. This doesn't seem to work anymore, in the ways in this issue https://github.com/mtharrison/hapi-context-credentials/issues/3.

**Comment by mtharrison** [comment]
Can you elaborate? What would be in `request.auth` for a route without auth?

**Comment by geuis** [comment]
hey @mtharrison. Your plugin `hapi-context-credentials` used detect if a user has been authenticated and then add that to request.auth for all route contexts. That doesn't seem to work anymore with the latest version of hapi.

**Comment by mtharrison** [comment]
It simply copies the value of `request.auth.credentials` into the view context for a route where a user has authenticated. It still works as far as I can see. 

If you have an example where it doesn't work, please post on that issue.

**Comment by geuis** [comment]
Hey, I don't think closing this just yet is right. My original question remains unanswered, `Recommendations for extending request.auth to routes not configured with auth settings?`

The use case is very simple and extremely common across nearly every site ever made. A site has pages that are public and private, and public pages almost always change state if the visitor is signed in or not.

I spent a lot of time re-reading through the Hapi docs today and it is simply not clear about how to configure routes to allow this behavior.

Using the following configuration, I've tried false, optional, and try. 

```
server.register([Inert, HapiAuthCookie, HapiContextCredentials], err => {
  if (err) {
    throw err;
  }

  // tried false, try, and optional
  server.auth.strategy('session', 'cookie', 'try', {
    password: process.env.cookiePwd,
    cookie: 'sess',
    clearInvalid: true,
    isSecure: process.env.NODE_ENV === 'development' ? false : true,
    ttl: 86400000, // milliseconds a day
    redirectTo: '/signin',
    validateFunc: (request, session, callback) => {
      server.app.cache.get(session.sid, (err, cached) => {
        if (err) {
          return callback(err, false);
        }
        
        if (!cached) {
          return callback(null, false);
        }
        
        return callback(null, true, cached.account);
      });
    }
  });
});
```

**Comment by hueniverse** [comment]
Questions belong in hapijs/discuss. Unfortunately I don't have time to answer this right now.

**Comment by hueniverse** [comment]
A pretty out dated example:

https://github.com/hueniverse/postmile-web/blob/master/lib/misc.js#L15-L32
https://github.com/hueniverse/postmile-web/blob/master/lib/index.js#L58

I would make the auth required and override it to 'try' for that one route instead.
