### ISSUE TITLE
custom statusCode while `validate`

### ISSUE THREAD

**Issue by jney** [hapijs/hapi#3234]
Hi. I've got the following pattern to ensure the header has the authenticated header: 

```js
{
  config: {
    validate: {
      headers: Joi.object({
        authorization: Joi.string().regex(/bearer (\S+)/i).required()
      }).options({allowUnknown: true})
    }
  }
}
```

The standard `hapi` behavior is to return a `400` code, but in this case i'd like to return a `403`, is it possible to achieve such behavior? thanks.

**Comment by bboysathish** [comment]
Check for `failAction` in http://hapijs.com/api#route-options and change the status code in respose object using `code` http://hapijs.com/api#response-object

**Comment by bboysathish** [comment]
Going forward, redirect these kind of questions to [hapijs/discuss](https://github.com/hapijs/discuss) @jney

**Comment by Marsup** [comment]
Try with `Joi.string().regex(/bearer (\S+)/i).required().error(Boom.forbidden('....'))`, but I think your auth layer should take care of that, not joi.
