### ISSUE TITLE
Is it possible to access to response.headers["set-cookies"] set in transmit ?

### ISSUE THREAD

**Issue by Alex-Werner** [hapijs/hapi#3235]
Hello, 

Using Hapi, on my API /auth/login, i'm allowing my app client (Android/iOS) to give their registrationToken (for Google Cloud Messaging), but because a user (defined by a UUID that I create on my /auth/register call), can have many advice, I wanted to take another data which was the sessionID to identify many devices (ipad, smartphone) connected to the same account but with each ones a different sessionID. 

So in order to access to this, I tried to access to response.headers["set-cookies"] that is being initialized in transmit.js (l.523). 

But this initialisation seems to being done AFTER "onPreResponse", so I can't access to it. I know that I could just have to create a simple other unique identifier that would being created when I ask for a setCookieAuth and destroyed on my clearCookieAuth (using hapi-auth-cookie).
 
But I wanted to solve it first : Is it possible to access to the headers somewhere in my code before it's send to the browser/client ? 

Thank you for any insight on this matters.

**Comment by hueniverse** [comment]
Next time, post questions in hapijs/discuss.

Maybe:

```js
server.on('response', (request) => {
    console.log(request.raw.res.header['set-cookie']);
});
```

I didn't test this.
