### ISSUE TITLE
req.response.once is not a function

### ISSUE THREAD

**Issue by kevinbror** [hapijs/hapi#3236]
I have an `onPreResponse` route extension that does some cleanup on temp files after a download. I am running the app in docker containers via AWS ECS. In one ecs cluster the application runs fine. In another, with the docker image built from the same code, the extension causes an exception due to req.response.once not being a function. What could be causing this? Could it be a bad dependency installation? I am producing the images from the exact same code base. 

The handler config file and the exception are given below:

`'use strict';

const Joi = require('joi');
const Path = require('path');
const FS = require('fs');
const CONSTANTS = require('@florencehealthcare/florence-constants');
const severity = CONSTANTS.LOG_LEVEL;
const logTags = CONSTANTS.TAGS;

/**
 * Download package
 *
 * @name Controllers.downloader.download
 */
module.exports = {
    ext: {
        onPreResponse: {
            method: (req, reply) => {

                if (req.pre.packagePath) {
                    req.response.once('finish', () => {

                        FS.unlink(req.pre.packagePath, (err) => {

                            if (err) {
                                const tags = [logTags.downloader, severity.error];
                                const data = { cause: err };
                                req.server.log(tags, data, new Date(Date.now()));
                            }
                        });
                    });
                }
                reply(req.response);
            }
        }
    },
    validate: {
        options: { stripUnknown: true },
        params: {
            pack: Joi.string()
        }
    },
    pre: [
        {
            method: 'business.downloader.getPackagePath(params.pack, auth.credentials.id)',
            assign: 'packagePath'
        }
    ],
    handler: (request, reply) => {

        const filename = Path.basename(request.pre.packagePath).split('tmp-').pop();
        reply.file(request.pre.packagePath, { confine: false, filename: filename, mode: 'attachment' });
    },
    tags: ['api'],
    description: 'Download package',
    notes: 'Download package with hierarchy of folders and documents'
};`
`21:21:14 web-client-0 160718/212114.502, [error], message: Uncaught error: req.response.once is not a function stack: TypeError: Uncaught error: req.response.once is not a function
21:21:14 web-client-0     at module.exports.ext.onPreResponse.method.req.response.once (/usr/src/app/node_modules/@florencehealthcare/florence-downloader-hapi/lib/controllers/downloader/download.js:21:34)
21:21:14 web-client-0     at /usr/src/app/node_modules/hapi/lib/request.js:402:22
21:21:14 web-client-0     at iterate (/usr/src/app/node_modules/hapi/node_modules/items/lib/index.js:36:13)
21:21:14 web-client-0     at done (/usr/src/app/node_modules/hapi/node_modules/items/lib/index.js:28:25)
21:21:14 web-client-0     at Function.wrapped [as _next] (/usr/src/app/node_modules/hapi/node_modules/hoek/lib/index.js:867:20)
21:21:14 web-client-0     at Function.internals.Reply.interface.internals.continue (/usr/src/app/node_modules/hapi/lib/reply.js:107:10)
21:21:14 web-client-0     at exports.register.internals.destroyCookiesOn401 (/usr/src/app/node_modules/@florencehealthcare/florence-users-auth-jwt/lib/plugin.js:90:19)
21:21:14 web-client-0     at /usr/src/app/node_modules/hapi/lib/request.js:402:22
21:21:14 web-client-0     at iterate (/usr/src/app/node_modules/hapi/node_modules/items/lib/index.js:36:13)
21:21:14 web-client-0     at Object.exports.serial (/usr/src/app/node_modules/hapi/node_modules/items/lib/index.js:39:9)
21:21:14 web-client-0     at /usr/src/app/node_modules/hapi/lib/request.js:397:15
21:21:14 web-client-0     at internals.Protect.run.finish [as run] (/usr/src/app/node_modules/hapi/lib/protect.js:64:5)
21:21:14 web-client-0     at internals.Request.internals.Request._execute.internals.Request._lifecycle.internals.Request._invoke.callback._protect.run [as _invoke] (/usr/src/app/node_modules/hapi/lib/request.js:395:19)
21:21:14 web-client-0     at internals.Request.internals.Request._execute.internals.Request._lifecycle.internals.Request._invoke.internals.Request._reply.exit [as _reply] (/usr/src/app/node_modules/hapi/lib/request.js:454:10)
21:21:14 web-client-0     at /usr/src/app/node_modules/hapi/lib/request.js:388:21
21:21:14 web-client-0     at done (/usr/src/app/node_modules/hapi/node_modules/items/lib/index.js:31:25)
21:21:14 web-client-0 Debug: internal, implementation, error 
21:21:14 web-client-0     TypeError: Uncaught error: req.response.once is not a function
21:21:14 web-client-0     at module.exports.ext.onPreResponse.method.req.response.once (/usr/src/app/node_modules/@florencehealthcare/florence-downloader-hapi/lib/controllers/downloader/download.js:21:34)
21:21:14 web-client-0     at /usr/src/app/node_modules/hapi/lib/request.js:402:22
21:21:14 web-client-0     at iterate (/usr/src/app/node_modules/hapi/node_modules/items/lib/index.js:36:13)
21:21:14 web-client-0     at done (/usr/src/app/node_modules/hapi/node_modules/items/lib/index.js:28:25)
21:21:14 web-client-0     at Function.wrapped [as _next] (/usr/src/app/node_modules/hapi/node_modules/hoek/lib/index.js:867:20)
21:21:14 web-client-0     at Function.internals.Reply.interface.internals.continue (/usr/src/app/node_modules/hapi/lib/reply.js:107:10)
21:21:14 web-client-0     at exports.register.internals.destroyCookiesOn401 (/usr/src/app/node_modules/@florencehealthcare/florence-users-auth-jwt/lib/plugin.js:90:19)
21:21:14 web-client-0     at /usr/src/app/node_modules/hapi/lib/request.js:402:22
21:21:14 web-client-0     at iterate (/usr/src/app/node_modules/hapi/node_modules/items/lib/index.js:36:13)
21:21:14 web-client-0     at Object.exports.serial (/usr/src/app/node_modules/hapi/node_modules/items/lib/index.js:39:9)
21:21:14 web-client-0     at /usr/src/app/node_modules/hapi/lib/request.js:397:15
21:21:14 web-client-0     at internals.Protect.run.finish [as run] (/usr/src/app/node_modules/hapi/lib/protect.js:64:5)
21:21:14 web-client-0     at internals.Request.internals.Request._execute.internals.Request._lifecycle.internals.Request._invoke.callback._protect.run [as _invoke] (/usr/src/app/node_modules/hapi/lib/request.js:395:19)
21:21:14 web-client-0     at internals.Request.internals.Request._execute.internals.Request._lifecycle.internals.Request._invoke.internals.Request._reply.exit [as _reply] (/usr/src/app/node_modules/hapi/lib/request.js:454:10)
21:21:14 web-client-0     at /usr/src/app/node_modules/hapi/lib/request.js:388:21`

**Comment by Marsup** [comment]
`request.response` contains what you're replying, not necessarily a stream. If this is unexpected you might want to check if you're not replying an error before doing your thing.

**Comment by kevinbror** [comment]
Ahh, makes sense. Thanks.
