### ISSUE TITLE
Requests to a particular plugin timing out for apparently no reason

### ISSUE THREAD

**Issue by moogway** [hapijs/hapi#3240]
Hello,

My application is broken down into plugins (one plugin per service) that register routes pertaining to that service. For example,

- main.js
- plugins
    - posts
    - comments
        - index.js registers comments routes (comments/add, comments/remove etc)
        - handlers.js,  models.js, pre-handlers.js etc etc

I'm running into a weird problem. Once I start the server, all the plugins and all the routes work fine, but after some time, requests to one particular plugin (say to "comments" plugin) start timing out while all the other requests (to other plugins) are getting appropriate responses. Once I restart the Hapi server, everything starts working again, only for the "comments" plugin to breakdown again.

What makes it weird is that **it does not happen when I run a hapi server locally on my machine**, so it cannot be a configuration issue. Besides, none of the affected routes have their own specific timeout configuration.

I've eliminated these possibilities - 

1. _It's not a server-hosting service issue because_ all the other routes from other plugins are working fine. All the routes, non responding and responding, are simple GET/POST HTTP methods. No sockets, nothing.

2. _It can't be a configuration issue because_ it works fine when hosted on my machine

I am trying to figure out exactly where in the request lifecycle does the breakdown happen, but then the bug seems to be whimsical and is not easily replicable.

Any help here would be great.

Thanks

**Comment by Marsup** [comment]
Without code there's not much to work with but I'm going to take a stab in the dark. You're using promises somewhere in the request lifecycle, your handler or your hooks are crashing, and the promise is gobbling the error. For the record you shouldn't open discussion on this repo, [discuss](https://github.com/hapijs/discuss) is for that.

**Comment by moogway** [comment]
You're right. Let me close this. Besides this had nothing to do with hapi. It was a mongo thing :|

Thanks.
