### ISSUE TITLE
Hapi, HTTP/2 and Node.js Core

### ISSUE THREAD

**Issue by jasnell** [hapijs/hapi#3278]
Hello Hapi team,

I am currently heading up an effort to explore whether and how to implement HTTP/2 support directly in Node.js core. The question of If we should do this is still open. To help answer that question, as well as determine the best course forward should we decide to move ahead, I would love to get input from each of you with regards to what would be the best approach from the Hapi point of view.

(If this repo is not the correct place to discuss this, then please accept my apologies. I'll gladly move the conversation over to wherever you prefer it.)

Refs: https://github.com/nodejs/CTC/issues/6

**Comment by lostthetrail** [comment]
@hueniverse I assume this might be in your court.

**Comment by hueniverse** [comment]
I don't really have an opinion on this, not the time to participate in any WG discussion. hapi allows you to bring your own HTTP server and as long as the interface is the same, you can use HTTP/2. I have long advocated to removing HTTP from node and moving it into a separate module.

Posting this in hapijs/discuss might be more effective but the core contributors already saw it here and I guess don't have much to add.

**Comment by devinivy** [comment]
It would be smart for any HTTP/2 module to provide an interface that's consistent with that of `http`.  I expect hapi will be able to handle things like server push in the form of plugins.

**Comment by nlf** [comment]
agreed, i'm completely neutral on this. so long as the interface is the same it has basically no impact on hapi itself.

**Comment by Marsup** [comment]
I don't see any advantage to having it in core. In your reference you're essentially discussing the how, not the why, and I can't think of any good reason.

As for hapi, I don't think this has much of an impact, we'll manage.

**Comment by jasnell** [comment]
Ok, thank you all, I appreciate the feedback. We're still a long ways off from deciding if this is even something we would want to do so this feedback is useful. Thank you!
