### ISSUE TITLE
Not able to get array in payload

### ISSUE THREAD

**Issue by unagi2020** [hapijs/hapi#3279]
When I submit the following form ... Instead of getting an array in the payload, I get form names. I am pulling out hairs trying to figure out the problem. What stupidity could I be doing ?

<form method="POST" action="/from/action">
<input type="text" name="info[0][name]">
<input type="text" name="info[0][phone]">
</form>

In my payload request.payload I get
info[0][name]: 'John Doe'
info[0][phone]: '18005551212'

I was expecting to see .. 
info :[ {
    name: 'John Doe',
   phone: '18005551212'
}]

**Comment by hueniverse** [comment]
https://github.com/hapijs/hapi/issues/2985
