### ISSUE TITLE
request.query.hasOwnProperty causes "hasOwnProperty is not a function" error

### ISSUE THREAD

**Issue by jeremiahlee** [hapijs/hapi#3280]
I'm having a new issue with node v6.3.1 and hapi v14.1.0.

A handler function with `request.query.hasOwnProperty('whatever')` will result in a "request.query.hasOwnProperty is not a function" error.

Changing to `Object.prototype.hasOwnProperty.call(request.query, 'whatever')` works.

`typeof request` is 'object', so I'm not sure why this method is missing or why calling it from Object works.

**Comment by jasnell** [comment]
This is expected. https://github.com/nodejs/node/pull/6289 modified the `query` object returned by the `querystring` module such that it uses a `null` prototype, and therefore does not inherit the base properties and methods of ordinary `Object` instances. This was done intentionally to address some bugs that are detailed in the PR. Your workaround is the proper alternative.

**Comment by jeremiahlee** [comment]
Thanks @jasnell. Closing issue.

**Comment by crobinson42** [comment]
https://github.com/ljharb/qs#parsing-objects

**Comment by Ethan-Arrowood** [comment]
Could a change to the querystring type file help with this? TypeScript should definitely be throwing an error
