### ISSUE TITLE
Support for flowtype definitions

### ISSUE THREAD

**Issue by SimonDegraeve** [hapijs/hapi#3282]
Is there any plan to support [flow](https://flowtype.org/) definitions for Hapi?

If yes, should we contribute in this repository or in the [flow-typed](https://github.com/flowtype/flow-typed) project?

PS: I am not pushing for using the latest fancy tech, it's because I saw @hueniverse on the [Flow Q&A](https://sideway.com/room/6c) so I thought it could be relevant.

**Comment by hueniverse** [comment]
I think it's premature to include it with this module. I don't have an opinion about contributing work to the flow-typed project, but that topic belongs in hapijs/discuss.
