### ISSUE TITLE
What is the best way to extract/modify the scope on a route from onPreAuth?

### ISSUE THREAD

**Issue by hostiphur** [hapijs/hapi#3283]
I'm trying to add in some user level permissions so that the record to be modified by a route can only be modified by the user that originally created the record or by an admin. I was hoping to do this with the built in scopes so that I could put in something like:

`auth: { scope: ['manage', 'user.{record.createdBy}'] }`

However, I'm a little nervous about where I found the scope data on the route: 

`request.route.settings.auth.access[0].scope.selection`

I was hoping to write an onPreAuth function to replace the {record.createdBy} with the actual user id from that underlying database record, but the way I'm accessing the scope seems hacky and that the location of it within the request could easily change.

So, is there a recommended way to access/modify the scope on a route?

**Comment by devinivy** [comment]
Anything in `request.route` is part of the route public interface, which is considered read-only.  There's no way to change scopes on the fly that I know of.  I'd suggest looking into dynamic scopes (your scopes can use `params` and `query` from the `request`), and move the complication from the route's configured scopes to the scopes with which you endow your user.

**Comment by hostiphur** [comment]
Thanks for the feedback 👍  I've looked into dynamic scopes extensively but I'm not seeing a way to do what I need to do. My situation is that a user should be able to edit a record if they created it (regardless of their role) or if they're an admin (edit any records). So I basically need a way of pulling a record from the underlying db and use it to dynamically modify the scope. If that's not possible then I'm guessing the next possible step is to use pre-handlers to do permission checks and leave out scopes all together since scopes would prohibit the user from editing their own record if they aren't an admin.

**Comment by devinivy** [comment]
Another way to slice it is this,
Consider the route `POST /posts/{id}`.  Give the route scope `post-{params.id}`.  In your strategy implementation (rather than `onPreAuth`) give the user scope `post-10` if the owner of post no. 10 is the authenticated user.

**Comment by hostiphur** [comment]
OK, that makes sense. I was just thinking of it in an ass backwards kind of way. Thanks for the tip!

**Comment by devinivy** [comment]
No problem 🍻

**Comment by hugomd** [comment]
@hostiphur I'm not sure if you've found a nice solution to this but I've implemented it by creating an Access-Control-List (ACL) collection, and storing `itemId` and `userId` along with some permissions. In the authentication validation function, I check to see if the user has the required access and then add the relevant permissions (`read` or `write`) to their scope (`route.settings.auth.access[0].scope.selection`). Then I can just add `read` or `write` to the route scope.

I know this isn't the best way to go about it, but it's the best solution in my (project-specific) case.
