### ISSUE TITLE
Option to parse values in request.payload from strings to native types?

### ISSUE THREAD

**Issue by geuis** [hapijs/hapi#3287]
Sorry if I missed the relevant information here http://hapijs.com/api. (there are 103 references to "payload", couldn't find what I need)

I have data being POST'ed to an endpoint. The data is parsed and accessed in request.payload.

All values are parsed as strings. I'm hoping there is a config option to cause things like booleans to be converted into their native types.

e.g. 

> curl  -X 'POST' 'http://localhost:3000/api/v1/post' -d 'title=Test%20Title&isPublic=false&isBoolean=true'

request.payload is:

```
{
  title: "Test Title",
  isPublic: "false",
  isBoolean: "true"
}
```

My goal is:

```
{
  title: "Test Title",
  isPublic: false,
  isBoolean: true
}
```

**Comment by johnbrett** [comment]
You should read up on payload validation options for your route configuration: http://hapijs.com/api#route-options (scroll down to the `validate` section. 

Here you can specify a `joi` object https://github.com/hapijs/joi/blob/v9.0.4/API.md#validatevalue-schema-options-callback, which converts the types by default. 

Here's a tutorial on validation in hapi to help you get started: http://hapijs.com/tutorials/validation

**Comment by mtharrison** [comment]
x-www-form-urlencoded encoding just gives you key/value string pairs. If, possible you can try JSON instead, you should get the values you expect:

```
curl -X 'POST' 'http://localhost:4000' -H "Content-type: application/json" -d '{"title":"test title","isPublic":true,"isBoolean":true}'
```

Otherwise you'll need to manually convert these values or pass them through Joi schema validation.

**Comment by geuis** [comment]
Thanks @johnbrett and @mtharrison!
