### ISSUE TITLE
500 statusCode, next connection emits clientError HPE_CB_headers_complete

### ISSUE THREAD

**Issue by lostthetrail** [hapijs/hapi#3290]
When running Node 6 and the latest HAPI.js, a second connection will hang and emit HPE_CB_headers_complete if the previous connection results in a 500 statusCode.

Here is a reproduction repo. Instructions are in the readme.
https://github.com/lostthetrail/hapi-node6-hang

I have been attempting to dig into the code to see if I can determine/solve the problem, but I am coming up a bit short and would like some help determining the problem.

**Comment by lostthetrail** [comment]
Related to: https://github.com/hapijs/discuss/issues/315

**Comment by devinivy** [comment]
I mentioned in that discussion above that I couldn't reproduce the hang (though I did see the `HPE_CB_headers_complete`).  Could it be client-dependent?  It would be easier to diagnose if the hang itself were demonstrable in node (by scripting requests to the server).  Or A cURL could help too.

**Comment by lostthetrail** [comment]
It happens on all browsers, but not cURL for me.

**Comment by lostthetrail** [comment]
This appears to be only happening on my machine. Going to close it out.

**Comment by devinivy** [comment]
@lostthetrail I'm now experiencing the hang (so far I think it's related to this same problem) when using HTTPS but not HTTP.  Does that ring a bell?
