### ISSUE TITLE
The "Vary: accept-encoding" header is not always set

### ISSUE THREAD

**Issue by kanongil** [hapijs/hapi#3292]
When hapi only sometimes sets the `vary` header, based on input headers, it can cause caching issues.

I noticed that this is done for the `accept-encoding` header here: https://github.com/hapijs/hapi/blob/26aaff316ab6e769f6a88d9b1d2b9e4be6db8b7e/lib/transmit.js#L207-L209.

If a caching agent receives this response to a request without the `accept-encoding` header, it won't know to re-fetch the resource when another requests is made with the header, thus returning an incorrect response to the client.

The simple fix is to remove the `if`. Ideally it should only include the `vary` header for routes that serves different responses depending on the `accept-encoding` header. Maybe some kind of switch is needed?

**Comment by hueniverse** [comment]
If you have ideas how to do this better than just always set it, lmk.

**Comment by kanongil** [comment]
Of the top of my head, the response is only changed based of that header for compressible responses, where compression has not been disabled. Eg. `request.connection.settings.compression && mime.compressible`.
