### ISSUE TITLE
Modifying the boom payload property of reply(error) has no effect

### ISSUE THREAD

**Issue by teogeos** [hapijs/hapi#3293]
If I want to send a custom error message to a client I can do:
```
somePromise.catch(error => {
  let boomed = Boom.wrap(error);
  boomed.output.payload.message = 'woops';
  reply(boomed);
});
```
As expected, the client receives:
```
{
  "statusCode": 500,
  "error": "Internal Server Error",
  "message": "woops'"
}
```

But if I do:
```
somePromise.catch(error => {
  let boomed = reply(error);
  boomed.output.payload.message = 'woops';
});
```
Then I get:
```
{
  "statusCode": 500,
  "error": "Internal Server Error",
  "message": "An internal server error occurred'"
}
```
So setting a custom message directly on the boom instance returned by reply(error) has no effect, the message sent to the client remains the default one. This feels weird compared to the fact that if reply(stuff) is a response, and not a boom object, we can modify it to customize what is sent to the client.

Is there a reason for this?

**Comment by hueniverse** [comment]
When you return an error, `reply()` doesn't return a response object.

**Comment by teogeos** [comment]
Hello hueniverse,

I know, if I call `reply()` on an error, it doesn't return a response object, it returns a boom object.

Then, the client which originally made the request also receives back a payload that comes from a boom object:
```
{
  "statusCode": 500,
  "error": "Internal Server Error",
  "message": "An internal server error occurred'"
}
```

My problem is that if I modify the payload of the boom object returned by `reply()`, the client still receives the default payload from above instead of the one I modified. So it feels like the boom object returned by `reply` isn't the one the client receives. Is that true?

**Comment by devinivy** [comment]
It should be the same object, but in the error case I believe it's simply too late to modify it after you call `reply()`– hapi wastes no time to start responding with the error.  In the non-error case you have the rest of the tick.

**Comment by teogeos** [comment]
Hello devinivy,

Ok, that makes it clearer. In that case, couldn't it be good for consistency to have error responses behave like successful ones by sending them on the next tick?

**Comment by devinivy** [comment]
I can imagine that making sense, but I haven't considered the implications very far.  @hueniverse or others might know better.

**Comment by hueniverse** [comment]
The error can change internally. I don't recall all the paths.

**Comment by teogeos** [comment]
Ok, thank you for your explanations.

**Comment by hueniverse** [comment]
The reason you are getting a 500 is not because of the error but because you are setting a non existent property on the error. The error wrapping happens later so it's not that your payload change is ignored, it's that changing it is causing your code to throw a new error.

**Comment by teogeos** [comment]
That surprises me.

If I do this:
```
somePromise.catch(error => {
  let boomed = reply(error);
  console.log(boomed.isBoom);
});
```
It logs:
```
true
```
If I do this:
```
somePromise.catch(error => {
  let boomed = reply(error);
  console.log('msg: ' + boomed.output.payload.message);
  boomed.output.payload.message = 'woops';
  console.log('msg: ' + boomed.output.payload.message);
});
```
It logs:
```
msg: An internal server error occurred
msg: woops
```
But the client receives `An internal server error occurred` instead of `woops`.

This shows that:
->`reply(error)` instantly returns a boom-wrapped error
->the property `reply(error).output.payload.message` exists, can be set, but is then ignored.
