### ISSUE TITLE
Pass plugin's server rather than root server to route config function

### ISSUE THREAD

**Issue by devinivy** [hapijs/hapi#3297]
In #3277 (v14.1) the ability to specify a route's config as a function was introduced.  That function currently receives the root server as an argument.  I would suggest passing the relevant plugin's server instead, and additionally the relevant plugin's options as a second argument.  I find this to be more multi-purpose (since the root is trivially found accessible the plugin's server) and possibly more consistent with the original use-case that the feature was intended to cater to.

To illustrate,

``` js
server.route({
  path: '/',
  method: 'get',
  config: (srv, opts) => {

    Hoek.assert(srv === server);
    Hoek.assert(opts === server.realm.pluginOptions);

    const { serverLevelConfig } = srv.app;
    const { pluginLevelOptions } = opts;

    return { handler: (request, reply) => reply(serverLevelConfig + pluginLevelOptions) };
  }
});
```

**Comment by hueniverse** [comment]
Well, it works great for the user case I had for it... :-)

**Comment by devinivy** [comment]
I suppose every application is its own special snowflake. :o)

**Comment by hueniverse** [comment]
Use `plugin.realm.parent`.
