### ISSUE TITLE
Error when reply() is called with a third argument (non-auth)

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#3303]
Currently, the third argument is only used by the authentication strategy logic and is ignored elsewhere. This is to ensure the interfaces are used correctly and prevent bugs. Note that if you pass the result of a cached method directly to reply, you will need to drop the third `ttl` argument.

**Comment by hueniverse** [comment]
See https://github.com/hapijs/hapi/commit/20913131bdb73285bc2f3f58c722a083c640b951#diff-4714f65d47d46b2330b6dce750b931d5R2439 for how to change your code to handle the third argument.

**Comment by hueniverse** [comment]
I'm looking for feedback on this issue. It's better to throw but this might be a painful change for some if you chain methods into `reply()` directly and this would require a messy refactor (in which case the bug safety gain is minimal).

**Comment by AdriVanHoudt** [comment]
I am +1 on this, the example is a really good way to deal with it

**Comment by devinivy** [comment]
Fine with me.  I'll admit though, it is too bad that the reply interface is setup to be able to be used as a standard callback but that server methods call-back with a third argument– it _would_ be nice for them to be compatible.

Could server methods actually check if the callback is a reply interface, then call it with two arguments if so?  Seems a little quirky, but we do a similar thing with boom errors (`err.isBoom`) all the time.  It would be a minor-level change, so we could make a decision on that at a later date without any trouble.

**Comment by hueniverse** [comment]
Commit above was a typo.
