### ISSUE TITLE
Enable compression for 206 range responses

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#3305]
Was disabled due to incorrect handling of compressed data.

https://github.com/hapijs/hapi/pull/3291#issuecomment-241605375

**Comment by kanongil** [comment]
Why? I don't think anyone actually does this.

**Comment by hueniverse** [comment]
Proper.

**Comment by kanongil** [comment]
Fair enough, but it seems unsolvable, or at least a lot of work.

Also, something I missed previously, the exact etag matching to enable 206 response is supposed to be predicated on that the response actually emits that entity (and not an encoded representation).
