### ISSUE TITLE
hapijs/joi

### ISSUE THREAD

**Issue by marekkobida** [hapijs/hapi#3321]
Can anyone tell me how can I set up custom messages in my route with hapijs/joi?

```
config: {
  validate: {
    payload: {
      email: Joi.string().min(3).max(10)
    }
  }
}
```

The response must be different than the original message in English.
I tried absolutely all examples.

**Comment by igorkosta** [comment]
@marekkobida - from this thread: https://github.com/hapijs/joi/issues/546
```
email: Joi.string().email().required().language({
  string: {
    email: '!!Aaarrrrrggghhhhh!!! It needs to be valid matey!' // Note the !! escape prefix
  }
})
```

**Comment by marekkobida** [comment]
@igorkosta 

TypeError: Joi.string(...).email(...).required(...).language is not a function

**Comment by igorkosta** [comment]
@marekkobida I saw that you already forked `relish` - why don't you use that?

**Comment by marekkobida** [comment]
@igorkosta - This works but does not change the whole text.
Relish is a third party. This shall be possible to solve the natural way.

```
config: {
  validate: {
    payload: {
      email: Joi.string().email().required().options({
        language: {
          string: {
            email: 'ERROR'
          }
        }
      })
    }
  }
},
```

Server response:
`"message": "child \"email\" fails because [\"email\" ERROR]"`

**Comment by marekkobida** [comment]
@igorkosta - I can parse []... But why this text before?

**Comment by jamesdixon** [comment]
https://github.com/dialexa/relish

**Comment by igorkosta** [comment]
@jamesdixon Marek would prefer not to use third party solutions.

**Comment by marekkobida** [comment]
@jamesdixon - This does not solve the problem. In Relish I can not define more precisely the messages.

**Comment by marekkobida** [comment]
@igorkosta 

```
config: {
  validate: {
    options: {
      language: {
        string: {
          email: '!!ERROR'
        }
      }
    },
    payload: {
      email: Joi.string().email().required()
    }
  },
}
```

Server response now:
`"message": "child \"email\" fails because [ERROR]"`

Now I can parse []... But this useless text remains.

**Comment by marekkobida** [comment]
I solved the problem!

_payload_ is an object.

```
config: {
  validate: {
    options: {
      language: {
        object: {
          child: '!!{{reason}}'
        },
        string: {
          email: '!!Tento E-mail nie je správny.'
        }
      }
    },
    payload: {
      email: Joi.string().email().required()
    }
  }
}
```

**Comment by marekkobida** [comment]
@igorkosta - I solved the problem!

_payload_ is an object.

```
config: {
  validate: {
    options: {
      language: {
        object: {
          child: '!!{{reason}}'
        },
        string: {
          email: '!!Tento E-mail nie je správny.'
        }
      }
    },
    payload: {
      email: Joi.string().email().required()
    }
  }
}
```

**Comment by igorkosta** [comment]
@marekkobida that's great and thanks for posting the solution :)

**Comment by marekkobida** [comment]
@igorkosta - You're welcome!

**Comment by marekkobida** [comment]
[Hapi && Joi Validator — Custom Messages](https://medium.com/@marek.kobida/hapi-joi-validator-custom-messages-a5af06e4b419#.fjmgfe8e2)

**Comment by ekoome** [comment]
Great solution matey!

Is there a way remove the backslashes such as \"email\" in the error message ?
