### ISSUE TITLE
prefix all routes

### ISSUE THREAD

**Issue by jney** [hapijs/hapi#3327]
Hi. i would like to add a prefix to every of my url. 
I'm aware of http://hapijs.com/api#serverrealm i'm sure i can use it for that.

so i'm considering using this approach:

```js
routes.forEach(route => {
  if (PREFIX_URL) route.path = `${PREFIX_URL}${route.path}`
  Server.route(route)
})
```

maybe you could advice a better approach ?

**Comment by thebergamo** [comment]
You can use the `prefix` setting in the registration plugin level like the example follow, when you use the options `routes.prefix` in registring a plugin all your routes inside the plugin will have the prefix.

```javascript
server.register({ register: require('myplugin') }, {
    routes: {
        prefix: '/plugins'
    }
}, (err) => {

    if (err) {
        throw err;
    }
});
```` 

Reference: http://hapijs.com/tutorials/plugins#plugin-options

**Comment by hueniverse** [comment]
Please read the issues instruction and post support questions in hapijs/discuss.

**Comment by v1r** [comment]
no longer working for hapi v17?
