### ISSUE TITLE
Document request.connection

### ISSUE THREAD

**Issue by jmm** [hapijs/hapi#3328]
There's a `request.connection` property that doesn't appear to be documented. It's possible I could've missed some reference to it (especially considering that the documentation is difficult to follow in general due to things like all being on one page, long nested lists, and lack of much to hang text searches on), but it's not in the main [request object](http://hapijs.com/api#request-object) section.

If that's part of the public API, can it please be documented? FWIW it's referenced by a member of the Hapi org [here](https://github.com/hapijs/hapi/issues/2863#issuecomment-149489476).

If not, I'd be interested to know why and if there's an alternative, public API way to access the connection associated with a request.

Thanks!

**Comment by mtharrison** [comment]
I think it's probably just an accidental omission than anything on purpose - it's the right way to get a request's connection. Want to make a PR to add it?

Also if you have some suggestions or even time to help improve the documentation, it'd be very welcome. Please see relevant discussion: https://github.com/hapijs/hapijs.com/issues/200.

**Comment by jmm** [comment]
Thanks @mtharrison! I'm not sure when I'd have time to add it, so if someone else is up for it, :+1:

Thanks for that link. If I have any good ideas I'll chime in there.
