### ISSUE TITLE
reply interface called twice

### ISSUE THREAD

**Issue by Dinfyru** [hapijs/hapi#3340]
```
Debug: internal, implementation, error 
    Error: reply interface called twice
    at Object.exports.assert (/var/www/web-site/swinechat/node_modules/hoek/lib/index.js:736:11)
    at Function.internals.response (/var/www/web-site/swinechat/node_modules/hapi/lib/reply.js:150:10)
    at reply (/var/www/web-site/swinechat/node_modules/hapi/lib/reply.js:72:22)
    at callback (/var/www/web-site/swinechat/modules/routes.js:37:17)
    at playerModel.where.populate.populate.populate.findOne.exec (/var/www/web-site/swinechat/controller/game/base.js:55:17)
    at Query.<anonymous> (/var/www/web-site/swinechat/node_modules/mongoose/lib/query.js:2233:28)
    at /var/www/web-site/swinechat/node_modules/kareem/index.js:259:21
    at /var/www/web-site/swinechat/node_modules/kareem/index.js:127:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

controller Base.js called callback (cb()) for use reply
http://pastebin.com/B8FYEDMj
I have a loop that once per second refers to the server (function - getTimeEnergy in Base.js). And sometimes there is this error "reply interface called twice"

hapi version 15.0.3
nodejs - 6.3.0

**Comment by mtharrison** [comment]
You need to ensure you only ever call `reply(result)` once per request.

**Comment by Dinfyru** [comment]
@mtharrison i use once per request

**Comment by Marsup** [comment]
I don't think the code you pasted will help us understand what you're doing wrong, it doesn't contain any hapi related code.

**Comment by Dinfyru** [comment]
function cb() leads to router (example: Base.js:55)
```
$lib.s.route({
        method: 'POST',
        path:'/game',
        config: {
            plugins: {
                'hapi-io': 'user-action'
            }
        },
        handler: function (request, reply) {
            require($lib.controllerpath + 'game/base')(callback, request, true);
            
            function callback (err, result){
                return reply(result);
            }
        }
    });
```

**Comment by Marsup** [comment]
Best guess is ` this.getTimeEnergy` throws an exception which triggers an implicit reply. hapi protects you from failures in your code by doing that.

**Comment by Dinfyru** [comment]
The error occurs when you call at the same time 2 soket.emmit
![image](https://cloud.githubusercontent.com/assets/10163112/18342630/62bfd6dc-75b8-11e6-9398-2bd1ebcb2fd5.png)

**Comment by Dinfyru** [comment]
@Marsup how i can fix it?)

**Comment by mtharrison** [comment]
@Dinfyru I advise you to try to create a minimal example that shows the problem and we can debug from there. Otherwise it's too difficult to advise. Have a look at [How to create a Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) if you need help.

**Comment by Dinfyru** [comment]
I call socket.emit 2 times for route
```
$lib.s.route({
        method: 'POST',
        path:'/game',
        config: {
            plugins: {
                'hapi-io': 'user-action'
            }
        },
        handler: function (request, reply) {
            require($lib.controllerpath + 'game/base')(callback, request, true);
            
            function callback (err, result){
                return reply(result);
            }
        }
    });
```
And this return error 
```
Debug: internal, implementation, error 
    Error: reply interface called twice
```

**Comment by Dinfyru** [comment]
this
```
socket.emit('user-action', { userAction: 'start'}, function(res) {
	socketFunc(res);
});
```
and this
```
socket.emit('user-action', { userAction: 'getTimeEnergy' }, function(res) {
	$('.header .energy .text').text(res.val);
	if (res.type !== 'time') {
		$('.header .energy .progress').css('width', (res.val + '%'));
	}
});
```

**Comment by Dinfyru** [comment]
The error only occurs when they are called at the same time, and then they fall into one reguest (somehow)

**Comment by Dinfyru** [comment]
This will fix my problem?
https://github.com/mtharrison/susie
In example i see many reply
```
reply.event({ id: 1, data: 'my data' });
setTimeout(function () {
     reply.event({ id: 2, data: { a: 1 } }); // object datum
 }, 500);
```

**Comment by Dinfyru** [comment]
Or ho i can disable error (reply called twice)

**Comment by mtharrison** [comment]
> I advise you to try to create a minimal example that shows the problem and we can debug from there.

This advice still stands. You're not giving us enough to help. Simply adding another library won't fix the problem.

**Comment by Marsup** [comment]
You're mixing up websockets and normal handlers, I have no idea what you're doing there. This should really go into the discuss repo, this is not the place.

**Comment by Dinfyru** [comment]
@Marsup and what i can use for websockets?

**Comment by Marsup** [comment]
[nes](https://github.com/hapijs/nes/).

**Comment by Dinfyru** [comment]
How i can push data with this? 
```
var client = new Nes.Client('ws://138.201.35.240:8012/');
	client.connect(function (err) {
	    client.request('gamesock', function (err, payload) {
			console.log(payload)
	    });
	});
```

**Comment by Dinfyru** [comment]
before i use
```
data = { userAction: 'confirmAnswer', dataId: 0};
socket.emit('user-action', data, function(res) {
	socketFunc(res);
});
```
