### ISSUE TITLE
i cant set cookie by using reply().state(name,value)

### ISSUE THREAD

**Issue by ColorfulCow** [hapijs/hapi#3344]
this is my code
```
server.connection({
  host: '10.1.101.106',
  port: config.app.port,
})

server.route({
  method: 'GET',
  path:'/test/start/{name}',
  handler: function (req, res) {
    var cookie_options = {
      ttl: 365 * 24 * 60 * 60 * 1000, // expires a year from today
      encoding: 'none', // we already used JWT to encode
      isSecure: true, // warm & fuzzy feelings
      isHttpOnly: true, // prevent client alteration
      clearInvalid: false, // remove invalid cookies
      strictHeader: true // don't allow violations of RFC 6265
    };
    res('success')
      .state("token1", 'a', cookie_options)
      .state("token2", 'b', cookie_options)
  }
})
```

after execute this code ,i can't find cookies in chrome's devtools, but i can see 'success', is there something wrong ?

**Comment by AdriVanHoudt** [comment]
What does the cookie header from the reply look like?

**Comment by ColorfulCow** [comment]
@AdriVanHoudt  thank you for replying 
in response headers, i can find the right 'set-cookie' header,
but i can't understantd why there is nothing in devtool's cookie manager,

**Comment by ColorfulCow** [comment]
@AdriVanHoudt thanks for replying 
in response headers, i can find the right 'set-cookie' header,
but i can't understantd why there is nothing in devtool's cookie manager,

**Comment by Marsup** [comment]
`isSecure: true` indicates that this cookie should only work over https, are you using that protocol ?

**Comment by hueniverse** [comment]
`isHttpOnly` means the browser will not expose this cookie to javascript. I don't know what Chrome shows in the dev tools.

**Comment by ColorfulCow** [comment]
@Marsup thanks a lot, i removed 'isSecure', then works right

**Comment by ColorfulCow** [comment]
@hueniverse so sorry about my thoughtless

**Comment by janzenz** [comment]
In my case since my Hapi server was found on a different node, I had to specify `isSameSite: false`.
