### ISSUE TITLE
Major performance issue with hapi.js 15.x

### ISSUE THREAD

**Issue by lostthetrail** [hapijs/hapi#3347]
#### What are you trying to achieve or the steps to reproduce?

Under higher concurrency Hapi 15.x memory usage spikes and fails, where Hapi 14.x had no problem

``` js
'use strict';

const Hapi = require('hapi');
const hoek = require('hoek');

const server = new Hapi.Server({
    connections: {
        router: {
            stripTrailingSlash: true
        }
    }
});

server.connection({
    port: process.env.NODE_PORT || 8080,
    host: process.env.HOSTNAME || '0.0.0.0',
    routes: {
        response: {
            emptyStatusCode: 204
        }
    }
});

server.route([
    {
        method: 'GET',
        path: '/validate',
        handler: function handle(request, reply) {
            return reply({
                validate: true
            });
        }
    }
]);

server.start(function handleServerStart(serverStartErr) {
    hoek.assert(!serverStartErr, serverStartErr);
    console.log(`Server running at: ${server.info.uri}`);
});
```

```
artillery quick --duration 60 --rate 100 -n 100 http://localhost:8080/validate
```
#### What was the result you received?

With Hapi 15.x, you will see a "JavaScript heap out of memory" and it will fail.
With Hapi 14.x, you will have a successful test and have zero errors.
#### What did you expect?

No major failures and zero errors.
#### Context
- _node version_: 6.5.0 & 4.5.0
- _hapi version_: 15.0.3
- _os_: OSX & Centos
- _any other relevant information_: I am aware this is a very high RPS to push through a server. But it is an attack vector. I also was able to replicate this with JMeter, so the load tool isn't important in this case. Just high concurrency and RPS.

**Comment by hueniverse** [comment]
I cannot reproduce this issue with hapi@15.0.3. I ran the artillery test about 20 times against the same process. I ran it 3 times in parallel. I then ran 3 parallel artillery processes at 200 rps over 2 minutes - I got lots of errors on the artillery side (timeouts and disconnected sockets) but not a single memory error on the hapi server side. When that test was done, I was able to connect to the server and get the response.

Can someone else reproduce this?

**Comment by mtharrison** [comment]
I can't replicate any memory issues but I do see slightly higher CPU usage with hapi 15.x.x compared with 14.x.x. The additional time is mainly spent in Joi validation for every request coming from `internals.Podium.registerEvent`

![screen shot 2016-09-19 at 10 37 32](https://cloud.githubusercontent.com/assets/916064/18627851/31d825ce-7e55-11e6-86dd-0aec2847eece.png)

**Comment by genediazjr** [comment]
Hi, @mtharrison what did you use for the profiling?

**Comment by igorkosta** [comment]
@genediazjr https://artillery.io/, I guess

**Comment by mtharrison** [comment]
V8 inspector (`node --inspect`).

**Comment by genediazjr** [comment]
@mtharrison thanks!

**Comment by lostthetrail** [comment]
It appears there is some correlation between the failure I am seeing in Hapi and the version of Artillery used during the test.

I have pushed up an example with the specific version I used pinned:
https://github.com/lostthetrail/hapi-15-mem-issue

`npm start` in terminal 1
`npm test` in terminal 2

**Comment by Marsup** [comment]
The most important source of memory seems to be `_notificationsQueue` on the hapi `Connection` object. I don't see why it would retain so much unless we never reach a point where `setImmediate` runs those events, but I thought the whole point of this against `nextTick` was IO, I'm puzzled.

**Comment by Marsup** [comment]
@hueniverse doesn't seem to make a difference but is https://github.com/hapijs/podium/blob/master/lib/index.js#L168 really in the right place ? For both cases ?

**Comment by lostthetrail** [comment]
Let me know if there is anything else I can do.

**Comment by rfk** [comment]
FWIW, I can confirm that the steps in https://github.com/hapijs/hapi/issues/3347#issuecomment-248055798 reproduced the bug for me as well, with the server process from `npm start` eventually dying with `Allocation failed - process out of memory`.

Based on https://github.com/hapijs/hapi/issues/3347#issuecomment-248123795 I added some diagnostic logging inside podium, and the process got up to logging `_notificationsQueue.length == 642928` before it died.

**Comment by Marsup** [comment]
That's a difficult trade-off, if we switch from setImmediate to nextTick to allow node to actually process those, we're accepting less sockets, but at least the server doesn't fall. I still find it weird that node is never ever running setImmediate as long as IO is keeping it busy, this looks like a flaw in node.

**Comment by DavidTPate** [comment]
@Marsup It actually makes sense (based on the docs) that what you are seeing is happening, below is why:

[setImmediate](https://nodejs.org/api/timers.html#timers_setimmediate_callback_arg)
> Schedules the "immediate" execution of the callback after I/O events' callbacks and before timers created using setTimeout() and setInterval() are triggered. Returns an Immediate for use with clearImmediate().

> When multiple calls to setImmediate() are made, the callback functions are queued for execution in the order in which they are created. The entire callback queue is processed every event loop iteration. If an immediate timer is queued from inside an executing callback, that timer will not be triggered until the next event loop iteration.


[nextTick](https://nodejs.org/api/process.html#process_process_nexttick_callback_arg)
> The process.nextTick() method adds the callback to the "next tick queue". Once the current turn of the event loop turn runs to completion, all callbacks currently in the next tick queue will be called.

> This is not a simple alias to setTimeout(fn, 0), it's much more efficient. It runs before any additional I/O events (including timers) fire in subsequent ticks of the event loop.

So if we are talking about the processing then all of our callbacks made using `setImmediate` will be called after I/O completes and then called after the event loop completes. Whereas those added with `nextTick` which will process once the current event loop completes and prior to other I/O.

**Comment by Marsup** [comment]
I know that but I'm having a difficult time understanding how IO can never leave any tiny amount of time for it to kick in.

**Comment by vladikoff** [comment]
Allocation profile chart below: 

![image](https://cloud.githubusercontent.com/assets/128755/19050090/0bd66ff8-897b-11e6-8860-cc1fabfabbf5.png)

Download it via: 

[hapi15v3.heapprofile.zip](https://github.com/hapijs/hapi/files/506982/hapi15v3.heapprofile.zip)

based on https://github.com/lostthetrail/hapi-15-mem-issue

**Comment by DavidTPate** [comment]
Just going through the Node code around (both [JS](https://github.com/nodejs/node/blob/c8c2544cd9c339cdde881fc9a7f0851971b94d72/lib/timers.js) and [C++](https://github.com/nodejs/node/blob/b3d283acd4dd184712066b33994f3d8ec5f238dd/src/timer_wrap.cc)) around the underlying functionality of `setImmediate` it can definitely get into what looks to be some really interesting edge cases (still digging into the code, so could be wrong here). For example it will actually fallback to `nextTick` if it fails to execute the timer during the callback operation and reconstructs the queue.

There's also re-use of the handles for the Timers but that doesn't appear to be a case that this particular code would fall into from what I'm seeing. Definitely going to dig around some more.

**Comment by vladikoff** [comment]
@hueniverse @mtharrison how can we help move this issue forward?

**Comment by hueniverse** [comment]
This requires some attention from node core contributors who can help understand the actual cause. @cjihrig

**Comment by cjihrig** [comment]
So far, using hapi@15.0.3 and the hapi-15-mem-issue repo on OS X, I was able to recreate this on:
- v6.0.0
- v6.5.0
- v6.9.1 (latest Boron release)

I was unable to reproduce on:
- v4.5.0
- v4.6.1 (latest Argon release)
- v5.12.0 (the final v5 release)
- v7.0.0

I was also unable to reproduce on v6.9.1 using hapi@14.2.0.

**Comment by Marsup** [comment]
@cjihrig isn't it surprising to you that there isn't any time left for node to slip even a single setImmediate ? Is it at all possible to saturate node like that ?

**Comment by cjihrig** [comment]
@Marsup yes, it's possible to saturate Node. It's possible that since `setImmediate()` defers its work, the flood of incoming requests could prevent the `setImmediate()` callbacks from executing causing memory consumption to increase. I added a counter for the `setImmediate()`s, and you can see them gradually slowing over time.

**Comment by Marsup** [comment]
Then I guess the only solution is to go with nextTick in podium @hueniverse.

**Comment by cjihrig** [comment]
FWIW, using `setImmediate()` isn't necessarily wrong. The system is being stress tested, and eventually it breaks down. You'll also get an out of memory crash if you just write `while (true) { console.log(); }` :-)

hapi's load handling features would probably be another good way to mitigate the problem.

**Comment by hueniverse** [comment]
Wouldn't `nextTick()` just starve something else that this test isn't looking for? I am not sure this performance issue is a real problem. Is this causing actual production issues or is this a theoretical limit given this particular test?

**Comment by Marsup** [comment]
It would slow down on accepting new connections, thus maybe a few clients would timeout, but it's less likely you'd run out of memory in case of a ddos.

**Comment by pjcraven** [comment]
On our project we had to revert to 14.2.0 due to memory usage increasing to failure while using nes. This is on Heroku FWIW.

**Comment by vladikoff** [comment]
> Is this causing actual production issues or is this a theoretical limit given this particular test?

Yes, crashes production servers on routes that are high usage.

**Comment by cjihrig** [comment]
I don't think performance is an issue, but memory consumption might be. Is there a reason podium needs to defer when emitting events, when Node core's event emitter does not?

**Comment by devinivy** [comment]
@cjihrig I wonder if it's a way to recurse through podiums and source podiums without worrying about creating an arbitrarily large stack.

**Comment by mcollina** [comment]
Please check if https://github.com/hapijs/podium/pull/17 solves your issues.

**Comment by vladikoff** [comment]
@lostthetrail it seems like your repo is holding up with the fix from https://github.com/hapijs/hapi/issues/3347#issuecomment-263589308 , wanna double check?

**Comment by lostthetrail** [comment]
@vladikoff Yup. I am on it. At a conference so it may be a few hours.

**Comment by lostthetrail** [comment]
Confirmed. The patch to podium does fix the ever going process. Thanks!
