### ISSUE TITLE
More than three route parameters lead to "not found" error

### ISSUE THREAD

**Issue by barbalex** [hapijs/hapi#3348]
#### What are you trying to achieve or the steps to reproduce?

I am trying to implement an api with this path: `/node/{table}/{id}/{folder}/{levels}`

This is the route:

    {
        method: 'GET',
        path: '/node/{table}/{id}/{folder}/{levels}',
        handler: projekt,
      }

The idea is that the app passes this information:

- dataset: defined by table and id
- folder: in case this table has more than one relations on the n-side the relations are grouped in folders
- level: If the user clicked a node in the hierarchy tree, the next lower hierarchical level is needed (level = "next"). If the app starts up with a deep link, additionally all nodes that are hierarchically above the needed one are needed (level = "all").

The app builds a hierarchical tree with the provided data. The user uses it to understand the complex hierarchy and also to navigate to datasets.

#### What was the result you received?

    Debug: handler, error
    {"msec":1.646368995308876,"error":"Not Found","data":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found"},"headers":{}},"message":"Not Found"}}

#### What did you expect?

Data.

I DO get the expected data with the following paths:

- `/node/{table}/{id}/{folder}`
- `/node/{table}/{id}`
- `/node/{table}`
- `/node`

#### Context

* *node version*: 6.5.0
* *hapi version*: 15.0.3
* *os*: Windows 10

**Comment by Marsup** [comment]
Works for me. What's in your handler ? How are you querying the api ?

**Comment by barbalex** [comment]
This is the route: https://github.com/FNSKtZH/apflora_api/blob/master/src/routes/node.js
This is the handler: https://github.com/FNSKtZH/apflora_api/blob/master/queries/node/projekt.js
I was querying by calling `localhost:4001/node/projekt/1/none/next`

**Comment by Marsup** [comment]
Not sure what I'm supposed to be seeing there. You have defined a route with 3 parameters, you're providing, it's not matching anything, that's expected.

**Comment by barbalex** [comment]
The four parameters are now commented out because they provoke the error
When I test with four parameters I uncomment the path with four and comment the path with three

**Comment by barbalex** [comment]
OMG. I tried again and it works now.
SORRY for bugging you!
