### ISSUE TITLE
Correction to homepage doc.

### ISSUE THREAD

**Issue by karlbateman** [hapijs/hapi#3349]
Hey all,
Just a quick one.. the docs on the homepage should have the user create the `server.js` file first, then run `npm init` as this will be picked up for running `npm start`.

Currently as they are in the wrong order, you need to specify that `node server.js` is added to the start script of `package.json` e.g.

```
{
...
    scripts: {
        "start": "node server.js"
    },
...
}
```

Great work on **Hapi** btw, I absolutely ❤️  it.. keep up the 🔥 💻  😃

**Comment by hueniverse** [comment]
Please open website issues at hapijs/hapijs.com.

**Comment by mtharrison** [comment]
`node server.js` is the default behaviour of `npm start`. You don't need to explicitly add it. See https://docs.npmjs.com/cli/start.

**Comment by karlbateman** [comment]
Not to worry, thought it may have been an oversight. Apologies 👍
