### ISSUE TITLE
npm shrinkwrap produces error with hapi

### ISSUE THREAD

**Issue by mischah** [hapijs/hapi#3352]
Hej there,

I’m trying to shrinkwrap a hapi project and I’m able to reproduce that issue with `hapi` as single dependency.

#### Steps to reproduce**

```bash
mkdir hapi-shrinkwrap
cd hapi-shrinkwrap
npm init -f
npm i hapi --save
npm shrinkwrap
```

#### What was the result you received?

The following npm error:

```
npm ERR! invalid: have wreck@9.0.0 (expected: 8.x.x) /Users/mkuehnel/hapi-shrinkwrap/node_modules/hapi/node_modules/subtext/node_modules/wreck
npm ERR! extraneous: wreck@9.0.0 /Users/mkuehnel/hapi-shrinkwrap/node_modules/hapi/node_modules/subtext/node_modules/wreck
```

#### What did you expect?

That npm creates a `npm-shrinkwrap.json` file as described in the [npm docs](https://docs.npmjs.com/cli/shrinkwrap).

#### Context

* *node version*: `5.5.0` as well as `6.5.0`
* *hapi version*: `15.1.0`
* *os*: OS X `10.11.6`
* *npm version*: `3.10.3`

**Comment by mischah** [comment]
Uhm. Using the following succesfully creates a `npm-shrinkwrap.json`

```
npm prune && npm update && npm install 
```

**Comment by Marsup** [comment]
It's already fixed by https://github.com/hapijs/hapi/pull/3351, just need to merge it.

**Comment by mischah** [comment]
Thanks. Feel free to close the issue whenever you want 👌
