### ISSUE TITLE
Joi throws error in 15.1.0

### ISSUE THREAD

**Issue by armand1m** [hapijs/hapi#3353]
#### Are you sure this is an issue with hapi or are you just looking for some help?

Not sure if this is an issue with hapi or joi, but getting Hapi back to v15.0.3 helped me "solving" it.

#### What are you trying to achieve or the steps to reproduce?

I've started a simple API implementation a couple months ago using Hapi.js v15.0.3 and everything was going fine. I've been using `boom` and `joi` as well. But today, when I arrived the work, it was the time to test and build the docker image in the CI server, and suddenly my tests started throwing some strange errors that broke 15 tests. 

I could test it by making a PUT request with an empty payload into a route that has this implementation:

```js
'use strict'

const Joi = require('joi')
const Boom = require('boom')
const messages = require('../../messages')
const models = require('../../models')

function handler (request, reply) {
  let id = request.payload.cha_cd_chamado

  return models
    .Chamado
    .findById(id)
    .then(chamado => {
      if (!chamado)
        throw Boom.notFound(messages.chamado.error.notFound(id))

      return chamado.update(request.payload)
    })
    .then(chamado => reply(chamado).code(201))
    .catch(reply)
}

module.exports = {
  handler,
  method: 'PUT',
  path: '/',
  config: {
    validate: {
      payload: {
        cha_cd_chamado: Joi.number().integer().required(),
        cha_ds_assunto: Joi.string(),
        cha_ds_descricao: Joi.string(),
        cha_dt_conclusao_estimada: Joi.date(),
        cha_cd_column: Joi.number().integer(),
        cha_cd_cliente: Joi.number().integer(),
        cha_cd_servico: Joi.number().integer(),
        cha_cd_colaborador_responsavel: Joi.number().integer(),
        cha_cd_categoria: Joi.number().integer(),
        cha_cd_sub_categoria: Joi.number().integer(),
        cha_cd_criticidade: Joi.number().integer(),
        cha_cd_contrato: Joi.number().integer(),
        cha_fl_considera_data_prevista: Joi.boolean(),
        cha_dt_abertura: Joi.strip(),
        cha_dt_created_at: Joi.strip(),
        cha_dt_updated_at: Joi.strip(),
        cha_dt_deleted_at: Joi.strip(),
        alocacoes: Joi.strip()
      }
    }
  }
}

```

#### What was the result you received?

No response was received in the client, and the server has thrown this error:
```bash
service_1  | Debug: internal, implementation, error 
service_1  |     TypeError: child.schema._getLabel is not a function
service_1  |     at _base (/src/node_modules/hapi/node_modules/joi/lib/object.js:157:93)
service_1  |     at _validate (/src/node_modules/hapi/node_modules/joi/lib/any.js:540:37)
service_1  |     at _validateWithOptions (/src/node_modules/hapi/node_modules/joi/lib/any.js:600:29)
service_1  |     at root.validate (/src/node_modules/hapi/node_modules/joi/lib/index.js:105:23)
service_1  |     at Object.internals.input (/src/node_modules/hapi/lib/validation.js:137:20)
service_1  |     at exports.payload (/src/node_modules/hapi/lib/validation.js:42:22)
service_1  |     at each (/src/node_modules/hapi/lib/request.js:380:16)
service_1  |     at iterate (/src/node_modules/hapi/node_modules/items/lib/index.js:36:13)
service_1  |     at done (/src/node_modules/hapi/node_modules/items/lib/index.js:28:25)
service_1  |     at onParsed (/src/node_modules/hapi/lib/route.js:407:20)
service_1  |     at Subtext.parse (/src/node_modules/hapi/lib/route.js:428:20)
service_1  |     at next (/src/node_modules/hapi/node_modules/subtext/lib/index.js:48:16)
service_1  |     at internals.object (/src/node_modules/hapi/node_modules/subtext/lib/index.js:171:20)
service_1  |     at Object.internals.jsonParse (/src/node_modules/hapi/node_modules/subtext/lib/index.js:290:12)
service_1  |     at Object.internals.object (/src/node_modules/hapi/node_modules/subtext/lib/index.js:263:26)
service_1  |     at Wreck.read (/src/node_modules/hapi/node_modules/subtext/lib/index.js:163:19)
```

After some debugging, I've found that when using the v15.1.0 that was released yesterday at night, this error is thrown when trying to validate something using Joi.

Going back to 15.0.3 was the solution I've found for it.

#### What did you expect?
a `HTTP 1.1 400 Bad Request` response.

#### Context

* *node version*: 6.2.0
* *hapi version*: 15.1.0
* *os*: Alpine (docker image)

**Comment by Marsup** [comment]
Try to either synchronize your joi version with hapi's or pass actual joi schemas (joi.object({})) in your case.

**Comment by armand1m** [comment]
Well, actually I was using the hapi.js joi dependency as you can see in the stacktrace path:

"at _base (/src/node_modules/hapi/node_modules/joi/lib/object.js:157:93)"

I didn't have `npm install`ed joi since it is already on hapi as a dependency (don't know either if it is a bad practice or not) and it just works normally on 15.0.3. I'll try to wrap my payload validation object into a joi schema and if it works I'll give some feedback in here.

**Comment by Marsup** [comment]
It probably works because you're using npm 3 which is flattening the modules but you shouldn't do that. You probably had this error because you updated your modules instead of reinstalling it.

**Comment by armand1m** [comment]
I don't think that.. I just deleted the `node_modules` folder and `npm install`ed everything once again like 3 times and the error has persisted. This is my actual `package.json`:

```json
{
  "name": "sisdem-api",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",  
  "author": "",
  "license": "ISC",
  "dependencies": {
    "boom": "^4.0.0",
    "hapi": "ˆ15.0.3",
    "hapi-auth-jwt2": "^7.0.1",
    "jsonwebtoken": "^7.1.9",
    "ldapjs": "^1.0.0",
    "moment": "^2.14.1",
    "recursive-readdir-sync": "^1.0.6",
    "sequelize": "^3.23.6",
    "socket.io": "^1.4.8",
    "tedious": "^1.14.0"
  },
  "devDependencies": {
    "chai": "^3.5.0",
    "chai-things": "^0.2.0",
    "geni": "^0.1.2",
    "istanbul": "^0.4.4",
    "mocha": "^3.0.2",
    "sequelize-cli": "^2.4.0",
    "sinon": "^1.17.5",
    "sinon-chai": "^2.8.0"
  }
}
```

I'll try installing joi through npm install later. Thanks for the feedback.

**Comment by Marsup** [comment]
Can you `npm ls joi` ?

**Comment by armand1m** [comment]
So, this is the output with hapi on v15.0.3:

```bash
sisdem-api@1.0.0 /Users/armandomagalhaes/Projects/sisdem-api/service
├─┬ hapi@15.0.3
│ └── joi@9.0.4 
└─┬ jsonwebtoken@7.1.9
  └── joi@6.10.1 
```
 and this is the output with hapi on v15.1.0:

```bash
sisdem-api@1.0.0 /Users/armandomagalhaes/Projects/sisdem-api/service
├─┬ hapi@15.0.3
│ └── joi@9.0.4 
└─┬ jsonwebtoken@7.1.9
  └── joi@6.10.1 
```
Maybe it has something to do with the dependency that `jsonwebtoken` has on joi?

**Comment by armand1m** [comment]
This is the output with hapi on v15.0.3:

```bash
sisdem-api@1.0.0 /Users/armandomagalhaes/Projects/sisdem-api/service
├─┬ hapi@15.0.3
│ └── joi@9.0.4 
└─┬ jsonwebtoken@7.1.9
  └── joi@6.10.1 
```

This is the output with hapi on v15.1.0:

```bash
sisdem-api@1.0.0 /Users/armandomagalhaes/Projects/sisdem-api/service
├─┬ hapi@15.1.1
│ └── joi@9.0.4 
└─┬ jsonwebtoken@7.1.9
  └── joi@6.10.1 
```

**Comment by Marsup** [comment]
So I guess npm decided to put joi@6 at the root, which is what you're using. You must always declare your dependencies.

**Comment by DamodarSojka** [comment]
I am experiencing the same issue, with Joi explicitly declared as a dependency and without.
npm ls joi
`├─┬ good@7.0.2
│ └── joi@7.3.0 
├─┬ good-console@6.1.2
│ └── joi@8.1.1 
├─┬ hapi@15.1.1
│ └── joi@9.0.4 
├─┬ hapi-auth-bearer-token@4.3.1
│ └── joi@9.1.1 
├─┬ hapi-mongodb@6.2.0
│ └── joi@9.1.1 
└── joi@9.2.0 
`

Problem happens with payload validation.

**Comment by mayankkumar0072** [comment]
I faced the same issue while making a POST request to HAPI server with JOI.
Then after some debugging, I realised that my request content type was :  

 **'Content-type','application/x-www-form-urlencoded'**

Which I changed to: 

**'Content-type','application/json'** 

And it worked.

**Comment by moksamedia** [comment]
Same issue here. Would appreciate any suggestions.

Andrews-MBP:bodak-backend cantgetnosleep$ npm ls joi
hapi-api@1.0.0 /Users/cantgetnosleep/development/toptal/TulsaApp/bodak-backend
├─┬ blipp@2.3.0
│ └── joi@6.10.1 
├─┬ glue@4.2.0
│ └── joi@10.6.0 
├─┬ good@7.3.0
│ └── joi@10.6.0 
├─┬ good-console@6.4.0
│ └── joi@8.1.1 
├─┬ hapi@16.6.0
│ ├─┬ catbox@7.1.5
│ │ └── joi@10.6.0 
│ ├─┬ heavy@4.0.4
│ │ └── joi@10.6.0 
│ ├── joi@10.6.0 
│ ├─┬ podium@1.3.0
│ │ └── joi@10.6.0 
│ ├─┬ shot@3.4.2
│ │ └── joi@10.6.0 
│ └─┬ statehood@5.0.3
│   └── joi@10.6.0 
├─┬ hapi-auth-jwt2@7.3.0
│ └─┬ jsonwebtoken@7.4.3
│   └── joi@6.10.1 
├─┬ hapi-sequelize@3.0.4
│ └── joi@8.1.0 
├── joi@11.0.2 
└─┬ lab@14.3.0
  └─┬ bossy@3.0.4
    └── joi@10.6.0
