### ISSUE TITLE
the path from 'reuest.url.path' loses something

### ISSUE THREAD

**Issue by iTonyYo** [hapijs/hapi#3363]
I want to deal an url like 'https://lodash.com/docs/4.16.4#chunk', but there's no '#chunk' in the result from 'reuest.url.path'.

Here is part of my code:

```js
let handling    = (request, reply) => {
  const kw      = 'target=';
  let stId      = shortid.generate();

  log(
    ctx.blue.bgBlack.bold('HUSO.IO'),
    ctx.red.bgBlack.bold('?Request obj from hapi.js is ')
  );
  console.dir(request);

  log(
    ctx.blue.bgBlack.bold('HUSO.IO'),
    ctx.red.bgBlack.bold('?Path from hapi.js is ') + ctx.white.bgBlack.bold(request.url.path)
  );

  let urlPath   = urlencode.decode(request.url.path);
  log(
    ctx.blue.bgBlack.bold('HUSO.IO'),
    ctx.red.bgBlack.bold('?target is ') + ctx.white.bgBlack.bold(urlPath)
  );

  console.log(request.url);

  let strQuery  = urlPath.substring(
    urlPath.indexOf(kw),
    _.size(urlPath)
  );
  log(
    ctx.blue.bgBlack.bold('HUSO.IO'),
    ctx.red.bgBlack.bold('Query string is ') + ctx.white.bgBlack.bold(strQuery)
  );

  let target    = strQuery.substring(
    _.size(kw),
    _.size(strQuery)
  );
  log(
    ctx.blue.bgBlack.bold('HUSO.IO'),
    ctx.red.bgBlack.bold('Target is ') + ctx.white.bgBlack.bold(target)
  );

  // TODO: □ 增加策略：可切换域名。
  let shortenUrl  = domains[0] + stId;
  log(
    ctx.blue.bgBlack.bold('HUSO.IO'),
    ctx.red.bgBlack.bold('Shorten url is ') + ctx.white.bgBlack.bold(shortenUrl)
  );
};
```

I get these from iTerm:
![image](https://cloud.githubusercontent.com/assets/5499703/19433311/bd7e0622-9492-11e6-9f6b-23d443a1a4b6.png)

How can I solve this problem? Please!

#### Context

* *node version*: v6.8.1
* *hapi version*: v15.1.1
* *os*: macOS Sierra

**Comment by mtharrison** [comment]
The browser doesn't send the hash part in the request. See related: https://github.com/hapijs/hapi/issues/3109

**Comment by iTonyYo** [comment]
@mtharrison Thanks a lot!

**Comment by iTonyYo** [comment]
@mtharrison 

But... the 'https://lodash.com/docs/4.16.4#chunk' url wasn't sent by browser:
```js

let $iptUrl = $(this).find('input[name=iptUrls]');
let iptUrlVal = $iptUrl.val();

if (!isempty(iptUrlVal) && isUrl(iptUrlVal)) {
  let getShortUrl = $.ajax({
    url: 'http://huso.io:9011/v1/shorturl/create',
    data: {
      target: iptUrlVal
    },
    headers: {
      Authorization: 'Basic aVRvbnlZbzpjblNXWjIxMjk5MDIy'
    }
  });
}
```

**Comment by mtharrison** [comment]
So you're sending that URL as data in another request? If you're sending that URL as part of the payload, then you should be reading it from `request.payload` then and not `request.url`.

**Comment by iTonyYo** [comment]
It's a GET request. I cannot set payload settings on HEAD or GET request, right? For now, result of 'request.payload' is null... 😭

**Comment by mtharrison** [comment]
From `jQuery.ajax()` docs:

> Data to be sent to the server. It is converted to a query string, if not already a string. It's appended to the url for GET-requests

So it's probably in `request.query` then, if that's how you're sending it.

**Comment by iTonyYo** [comment]
From `req.query`:
![image](https://cloud.githubusercontent.com/assets/5499703/19437395/cfc1f89c-94a7-11e6-8f95-c0c9a07ba564.png)

From `request.raw.req`:
![image](https://cloud.githubusercontent.com/assets/5499703/19437415/edf181d4-94a7-11e6-8cbc-e4a4ba353717.png)

...... 😭 

Maybe I should take a look at ajax & jQuery.

**Comment by iTonyYo** [comment]
![image](https://cloud.githubusercontent.com/assets/5499703/19437677/02a46fe6-94a9-11e6-8361-8e4940b82b36.png)

What...... 😭 

[6 Things You Should Know About Fragment URLs](https://blog.httpwatch.com/2011/03/01/6-things-you-should-know-about-fragment-urls/)
