### ISSUE TITLE
scopes are undocumented

### ISSUE THREAD

**Issue by turtleDev** [hapijs/hapi#3364]
https://github.com/hapijs/hapi/issues/2541#issuecomment-103968226 describes the use of `scopes`, however the official [docs](http://hapijs.com/api) contain nothing about scopes.

I'm pretty sure it's a not a feature of `hapi-auth-cookie` either, because I peeked under the hood.

**Comment by vdeturckheim** [comment]
@turtleDev I think `scopes` are documented:
https://github.com/hapijs/hapi/blob/master/API.md#route-options

**Comment by turtleDev** [comment]
Ahh pardon my stupidity.
Still I believe a lot of explanations are missing from the docs.

**Comment by vdeturckheim** [comment]
@turtleDev no worries. PR are welcomed
