### ISSUE TITLE
'reply.redirect' doesn't work

### ISSUE THREAD

**Issue by iTonyYo** [hapijs/hapi#3365]
> Also putted it on [StackOverflow](http://stackoverflow.com/questions/40093022/hapi-js-reply-redirect-doesnt-work).

The `forward` is `https://ja.wikipedia.org/wiki/メインページ`, but 'reply.redirect' doesn't work. If I replace `base64url.decode(val)` with 'https://lodash.com/docs/4.16.4#isNull', it works. Here's the code:

``` js
let handling = (request, reply) => {
  let theShortId = request.params.shortid;

  if (!_.isEmpty(theShortId) && !_.isNull(theShortId)) {
    // TODO: □ 增加策略：给定名称（Key）对应的数据库是否存在；参阅，https://www.sitepoint.com/using-redis-node-js/。
    redis.HGET(cfg.redis.dbs.db.target, theShortId, (err, val) => {
      if (!err) {
        let forward = base64url.decode(val);

        console.log(forward);
        console.log(typeof forward);

        reply.redirect(forward);
      } else {
        reply(err);
      }
    });
  }
};
```

**The output:**

![image](https://cloud.githubusercontent.com/assets/5499703/19449073/ba5d3852-94d6-11e6-8936-a9bf5c07c90a.png)

The 'reply.redirect' just don't work.

**I tried to use express.js & node-fetch, it works.**

``` js
router.get('/:shortid', (req, res, next) => {
  if (!_.isEmpty(req.params.shortid)) {
    fetch(cfg.rest.getRedirection + req.params.shortid, {
      method: 'GET'
    }).then((res) => {
      return res.text();
    }).then((text) => {
      res.redirect(text);
    });
  } else {
  }
});
```

HELP~~~~~ 😭  I want to be happy(hapi)!
#### Context
- _node version_: v6.8.1
- _hapi version_: v15.1.1
- _os_: macOS Sierra

**Comment by AdriVanHoudt** [comment]
You are getting a 500, what is the error your server generates?

**Comment by iTonyYo** [comment]
@AdriVanHoudt There was only `500`, no more error message, even if I set `DEBUG` env to `*`.
```coffeescript
'use strict'

gulp         = require 'gulp'
run_sequence = require 'run-sequence'

gulp.task 'default', (cb) ->
  process.env.DEBUG = '*'
  run_sequence 'nodemon', cb
  return
```

**Comment by AdriVanHoudt** [comment]
Weird normally it should print the error, can you run the server without gulp, maybe it is swallowing the error

**Comment by Marsup** [comment]
I doubt the env is propagated to the server, nodemon is a separate process.

**Comment by iTonyYo** [comment]
Still no more error message, after running `node server.js`, just `500` code. 😭 
![image](https://cloud.githubusercontent.com/assets/5499703/19507280/85a0fa66-9604-11e6-88fd-7ec543fe16a4.png)

**Comment by Marsup** [comment]
Are you even using that env to set hapi in debug mode ?

**Comment by iTonyYo** [comment]
Yeap, just 500 code. 😭
![image](https://cloud.githubusercontent.com/assets/5499703/19511084/55b0b418-9618-11e6-8048-77f493a36d6c.png)

**Comment by Marsup** [comment]
What's your `good` config ?

**Comment by iTonyYo** [comment]
😆 It can print error message, now! Studied hapi-good api [doc](https://github.com/hapijs/good/blob/master/API.md).

![image](https://cloud.githubusercontent.com/assets/5499703/19515087/9687613e-9628-11e6-9e55-4668db7fe6c4.png)

The error message:
![image](https://cloud.githubusercontent.com/assets/5499703/19515050/79d779a2-9628-11e6-9c52-04b8c0c6277b.png)

I'll go to check `reply([err], [result])` [doc](http://hapijs.com/api#replyerr-result) for customizing headers.

Thank you so much! @Marsup 🍻 🍻 🍻 🍻 🍻

**Comment by Marsup** [comment]
So maybe that's a shortcoming of hapi.redirect, it might be helpful if it encoded your URL, but to fix your immediate problem you could do it yourself.

**Comment by hueniverse** [comment]
hapi expects all headers to be HTTP compliant which means, 7bit text only. If you want to use other inputs such as an international URI, you need to do the encoding yourself. https://www.npmjs.com/package/encodeurl is the module used internally by express and seems to be well written.

I don't think this should be done for every URI by the framework.
