### ISSUE TITLE
Request: Change server.state default value for "path" to "/"

### ISSUE THREAD

**Issue by storrdev** [hapijs/hapi#3367]
I would like to propose that the the default value for the "path" property in the server.state options object be changed to "/" to mirror the default property found in expressjs' res.cookie().

Coming from an express background I was frustrated to find out I lost many hours due to missing what "path"'s default value was in the documentation.

**Comment by hueniverse** [comment]
Just because that's the Express default doesn't mean anything. If you want to make the case for such a change, you need to show why it's actually better.
