### ISSUE TITLE
Deprecation Warning in Node v7.0.0 for call to os.tmpDir

### ISSUE THREAD

**Issue by jonhester** [hapijs/hapi#3369]
`DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.`

`os.tmpdir` was added in Node v0.9.9 and `os.tmpDir` deprecated in Node v7.0.0. More info:
- https://github.com/nodejs/node/pull/6739 
- https://nodejs.org/en/blog/release/v7.0.0/
- https://nodejs.org/api/os.html#os_os_tmpdir

Reproducible by running hapi tests under Node v7.0.0

**Comment by QCCS** [comment]
![img_0580](https://cloud.githubusercontent.com/assets/13073380/23116841/b4c18f4c-f787-11e6-9f99-04564410df0f.JPG)

**Comment by gittirat** [comment]
update hapi
