### ISSUE TITLE
support redirect in route pre-requisites

### ISSUE THREAD

**Issue by kellyrmilligan** [hapijs/hapi#3370]
#### What are you trying to achieve or the steps to reproduce?

I would like to be able to redirect in the reply interface in a route pre-requisite. 

Currently, you can do reply().takeover to interrupt the lifecycle, but you cannot redirect.

``` js
reply.redirect('/someurl').takeover()
```
#### What was the result you received?

request just hung. 
#### What did you expect?

to be redirected
#### Context
- _node version_: 6.9
- _hapi version_: 13
- _os_: os x
- _any other relevant information_:

**Comment by hueniverse** [comment]
Works just fine. If you can provide an example that fails, I'll reopen.

**Comment by kellyrmilligan** [comment]
Will try on latest hapi thanks

**Comment by kellyrmilligan** [comment]
finally tested this on latest hapi, thanks again.
