### ISSUE TITLE
WebSocket connection to 'wss://' failed: WebSocket opening handshake was canceled

### ISSUE THREAD

**Issue by Dinfyru** [hapijs/hapi#3373]
In Chrome browser I have a problem, in the other browsers all is well
WebSocket connection to 'wss://' failed: WebSocket opening handshake was canceled

What can i do?
node -v 7
hapi 15.0.3
i use Nes for ws

**Comment by AdriVanHoudt** [comment]
@Dinfyru I suggest opening an issue on the nes repo if you still have issues

**Comment by cbrandabur** [comment]
what a fucking asshole this heniverse is
