### ISSUE TITLE
Request logger and destructuring

### ISSUE THREAD

**Issue by swashcap** [hapijs/hapi#3374]
#### What are you trying to achieve or the steps to reproduce?

I’m restructuring in a handler to make the function body more terse:

```js
const boom = require('boom');

const internals = {
  // Returns a Promise
  doSomethingAsync() {
    // whatever...
  },
};

module.exports.post = {
  handler({ log: requestLog, payload }, reply) {
    return internals.doSomethingAsync(payload)
      .then(reply)
      .catch(error => {
        requestLog(['error', 'post'], error.message);
        return reply(boom.wrap(error));
      })
  },
};
```

#### What was the result you received?

When `internals.doSomethingAsync` throws an error I notice an unexpected error instead:

```shell
161108/151527.588, [log,error], data: {"message":"TypeError: Cannot read property 'id' of undefined","stack":"TypeError: Cannot read property 'id' of undefined
    at internals.Request.log (/Users/creed/Sites/quarterback/packages/steelpenny/node_modules/hapi/lib/request.js:228:22)
# and so on...
```

I assume this is because [_lib/requests.js_’s `internals.Request#log`](https://github.com/hapijs/hapi/blob/5f446ddc179cde0cc7d34059c86bcae868870186/lib/request.js#L221-L241) method isn't bound to the request instance after destructuring. Would it make sense to throw a more direct error if `this` is `undefined` in the log function? Or, should public request methods not be instance methods such that they can be destructured and used? Should the [logging tutorial](http://hapijs.com/tutorials/logging) contain some clarification on the matter?

#### What did you expect?

I expected the request logger to actually log, not throw a TypeError.

#### Context

* *node version*: 6.9.1
* *hapi version*: 13.3.0
* *os*: OS X 10.12.1

**Comment by devinivy** [comment]
I personally think of this as the expected result.  Whenever you call a method out of context, that method can be expected to lose its `this` context.

**Comment by swashcap** [comment]
Sounds good. What would you think about a PR that does something like:

```js
internals.Request.prototype.log = function (tags, data, timestamp, _internal) {
  if (typeof this === 'undefined') {
    throw new Error('request\'s logger lacks \'this\' context');
  }

  // ...
};
```

**Comment by hueniverse** [comment]
I don't think so. This is how JS works. You should expect all request object methods to care about the existence of `this`.
