### ISSUE TITLE
Set-cookie header is not sent

### ISSUE THREAD

**Issue by nohsenc** [hapijs/hapi#3377]
Set-cookie header is not sent when I try to set state in the response method of auth scheme.
I just try to only update timestamp of session when auth succeeded at one place, the auth scheme.

```js
/**** scheme.authenticate ****/
const session= request.state.session;
// => session {sid: ... , timestamp: ... }

const cache = getCache( session.sid );
// => cache {sid: ... , timestamp: ... }

if(session.timestamp === cache.timestamp) ok( something ) ...
else fail( something ) ......

// finally 
// request.auth.credentials => { session: session, user: user };

// after route life cycle

/**** scheme.response ****/
const session = request.auth.credentials.session;
session.timestamp = Date.now();
saveCache(session);

reply.state('session', session); // no error but not sent 
request.response.state('session', session); // no error but not sent 
request._setState('session', session); // no error but not sent 
```

#### Context

* *node version*: 6.9.1
* *hapi version*: 15.1.1
* *os*: ubuntu 
* *any other relevant information*:

**Comment by AdriVanHoudt** [comment]
what does your `server.state` (https://github.com/hapijs/hapi/blob/master/API.md#serverstatename-options) for `session` look like?

**Comment by nohsenc** [comment]
server.state('session', { path: '/', isSecure: false, ttl: 16000, .... } )

I think it's not about my case, it's about control of route life cycle. 
Same code in onPreResponse extension works.  
scheme.response method is called after that.
so this issue happen. thanks

**Comment by nohsenc** [comment]
scheme.response method is called after transmit.state called.
let me know how I can send set-cookie header by using state method.

**Comment by AdriVanHoudt** [comment]
According to https://github.com/hapijs/hapi/blob/master/API.md#serverauthschemename-scheme `scheme.response` is only called in case of an error
Is this the case? If so try `reply().state()` (with the brackets)
Otherwise you might want to set the state somewhere else

**Comment by nohsenc** [comment]
According to https://github.com/hapijs/hapi/blob/master/API.md#serverauthschemename-scheme
**scheme.response** - optional function called to decorate the response with authentication headers  '**BEFORE** the response headers or payload is written',
AND 
reply.continue() - is called '**if the operation succeeded**'.

BUT I think **scheme.response** method is called '**AFTER** the response headers or payload is written'.

**Comment by nohsenc** [comment]
reply().state() => error

TypeError: Cannot read property 'payload' of undefined
    at Object.internals.fail (/home/www/kr1/node_modules/hapi/lib/transmit.js:114:40)
    at internals.marshal (/home/www/kr1/node_modules/hapi/lib/transmit.js:33:30)
    at Hoek.once (/home/www/kr1/node_modules/hapi/lib/protect.js:52:16)
    at wrapped (/home/www/kr1/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
    at internals.Response._processPrepare (/home/www/kr1/node_modules/hapi/lib/response.js:525:16)
    at internals.Response._prepare (/home/www/kr1/node_modules/hapi/lib/response.js:453:21)
    at process.nextTick (/home/www/kr1/node_modules/hapi/lib/reply.js:169:22)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by AdriVanHoudt** [comment]
@nohsenc if you could provide a code snippet that I could run that gives the error you are having it would help a lot to debug/fix/help your issue thanks!

**Comment by nohsenc** [comment]
here's my code snippet thanks

```js
const Hapi = require('hapi');
const server = new Hapi.Server();
const session = {
    sid: 'nsdfh376sbdg9sew253bshdhfsjdf7',
    timestamp: Date.now()
};

server.connection({port: 3000});
server.state('session', {
    path: '/',
    ttl: 1000 * 60,
    isSecure: false,
    encoding: 'base64json'
});
server.ext('onRequest', (request, reply)=> {
    console.log(`\n===> server [ ${request.method.toUpperCase()} ${request.path} ]`);
    return reply.continue();
});
server.auth.scheme('test', (server, options)=> {
    return {
        authenticate: function(request, reply) {
            console.log('> scheme.authenticate called');
            return reply.continue({
                credentials: { session: request.state.session }
            });
        },
        response: function(request, reply) {
            console.log('> scheme.response called');
            if(request.auth.credentials.session) {
                session.timestamp = Date.now();
                // reply.state('session', session); // no error but not sent 
                // request.response.state('session', session); // no error but not sent 
                // request._setState('session', session); // no error but not sent 
                // reply().state('session', session); // no error but not sent 
                return reply().state('session', session); // ===> error occured
            }
            return reply.continue();
        }
    };
});
server.auth.strategy('test', 'test');
server.auth.default('test');
server.route({
    method: '*',
    path: '/',
    handler: function(request, reply) {
        if(!request.state.session) {
            return reply('now authenticated').state('session', session);
        }
        else {
            return reply('already authenticated');
        }
    }
});
server.ext('onPreResponse', (request, reply)=> {
    console.log('> ext.onPreResponse called');
    if(request.auth.credentials.session) {
        // session.timestamp = Date.now();
        // reply.state('session', session); // no error, works!!
        // request.response.state('session', session); // no error, works!!
        // request._setState('session', session); // no error, works!!
        // reply().state('session', session); // no error, works!!
        // return reply().state('session', session); // no error, works!!
    }
    return reply.continue();
});
server.start((err)=> {
    if(err) throw err;
    console.log(`server running at ${server.info.uri}`);
});


const Http = require('http');
var cookie;
function parse(headers) {
    if(headers && headers['set-cookie']) {
        cookie = headers['set-cookie'][0].split(';')[0];
    }
}
function request() {
    var options = {
        hostname: 'localhost',
        port: 3000,
        path: '/',
        method: 'GET',
        headers: {}
    };
    if(cookie) {
        options.headers['Cookie'] = cookie;
    }
    return new Promise((resolve, reject)=> {
        var req = Http.request(options, (res) => {
            console.log('===> client received response');
            console.log('> set-cookie : ' + res.headers['set-cookie']);
            parse(res.headers);
            res.setEncoding('utf8');
            res.on('data', (chunk)=> {
                console.log('> payload : ' + chunk);
            });
            res.on('end', ()=> {
                resolve(null);
            });
        });
        req.on('error', (err)=> {
            reject(err);
        });
        req.end();    
    });
}
Promise.resolve()
.then(()=> {
    return request();
})
.then(()=> {
    return request();
})
.then(()=> {
    return request();
})
.catch((err)=> {
    console.log(err);
})
.then(()=> {
    process.exit();
});


```

**Comment by AdriVanHoudt** [comment]
If you change `return reply().state('session', session); // ===> error occurred`  to `request.response.state('session', session); // ===> error occurred` does that do what you want?

Mind the absence of the return to make sure to do `reply.continue()`.

**Comment by nohsenc** [comment]
I do not mind the absence of the RETURN.
The issue is that why Set-cookie header is not sent in the RESPONSE method of the AUTH SCHEME.
I think it is the one of the process of route life cycle.

**Comment by AdriVanHoudt** [comment]
ignore the return comment does changing the reply.state to request.response.state fix your issue?

**Comment by nohsenc** [comment]
I'm trying to set state here

``` js
        response: function(request, reply) {
            console.log('> scheme.response called');
            if(request.auth.credentials.session) {
                session.timestamp = Date.now();
                // reply.state('session', session); // no error but not sent 
                // request.response.state('session', session); // no error but not sent 
                // request._setState('session', session); // no error but not sent 
                reply().state('session', session); // no error but not sent 
            }
            return reply.continue();
        }

```

not here

```js
server.ext('onPreResponse', (request, reply)=> {
    console.log('> ext.onPreResponse called');
    if(request.auth.credentials.session) {
        // session.timestamp = Date.now();
        // reply.state('session', session); // no error, works!!
        // request.response.state('session', session); // no error, works!!
        // request._setState('session', session); // no error, works!!
        // reply().state('session', session); // no error, works!!
        // return reply().state('session', session); // no error, works!!
    }
    return reply.continue();
});

```

**Comment by AdriVanHoudt** [comment]
```js
response: function(request, reply) {
            console.log('> scheme.response called');
            if(request.auth.credentials.session) {
                session.timestamp = Date.now();
                // CHANGE THIS => reply().state('session', session); TO LINE BELOW
                request.response.state('session', session); 
            }
            return reply.continue();
        }
```
Does this change work for you?

**Comment by nohsenc** [comment]
as I already wrote above in the test code
all trying do not send header but no error occur

request.response.state('session', session); ===> no error but not sent
reply().state('session', session);  ===> no error but not sent 
reply.state('session', session); ===> no error but not sent

**Comment by AdriVanHoudt** [comment]
oh ok totally missed that sorry.
yeah this is a far as my knowledge of this goes maybe someone else can help you.
Let me post this issue on gitter ;)

**Comment by nohsenc** [comment]
thanks for all your support

**Comment by sirgallifrey** [comment]
Auth.response is called inside of the transmit.state callback and not only that it is the last thing called with this comment: `// Must be last in case requires access to headers`. See [transmit.js](https://github.com/hapijs/hapi/blob/master/lib/transmit.js#L105)

So calling reply().state or request.response.state will be of no use.

I think that would be better to not set any session stuff at Auth.response, but if you need to:

The only way you can tamper with the session at this points is to do it manually like this:

```javascript
response: function(request, reply) {
            console.log('> scheme.response called');
            if(request.auth.credentials.session) {
                session.timestamp = Date.now();
                
                const state = {
                    name: 'session',
                    value: session
                };

                request.connection.states.format(state, (err, header) => {

                    if (err) {
                        return reply(Boom.wrap(err));
                    }

                    const existing = request.response.headers['set-cookie'];
                    if (existing) {
                        header = (Array.isArray(existing) ? existing : [existing]).concat(header);
                    }

                    request.response._header('set-cookie', header);
                    return reply.continue();
                });

            } else {
                return reply.continue();
            }
        }
```
this was taken from [here](https://github.com/hapijs/hapi/blob/master/lib/transmit.js#L493)

Note that in this code i'm not handling the case where session has already been set

**Comment by nohsenc** [comment]
debugging this issue I saw that comment:  // Must be last in case requires access to headers

in the beginning of my reading API document about authenticate and response method of auth, it seemed like a couple methods for strategy. but when I found set-cookie header was not sent, I was puzzled why I couldn't set state here? isn't it couple methods for doing check and reset state with the same strategy of auth? I think it's kind of awkward proccess that auth.response method is only for accessing header manually. 

any way, it works! thanks

**Comment by sirgallifrey** [comment]
> I think it's kind of awkward proccess that auth.response method is only for accessing header manually.

Well, Auth.response is intended to set authentication headers on the response, something like this:

```javascript
response: function(request, reply) {
            if(request.auth.credentials.token) {
                request.response.header('Authorization', 'Bearer ' + request.auth.credentials.token);
            }
            return reply.continue();
        }
```

What you're trying to do is not what Auth.response was created for... It's possible to append a new cookie, but it's very messy :/

> any way, it works! thanks

glad we could help! :smile:

**Comment by AdriVanHoudt** [comment]
@sirgallifrey thanks for helping out!
