### ISSUE TITLE
Missing logs after upgrade to v15

### ISSUE THREAD

**Issue by kanongil** [hapijs/hapi#3379]
Using a standard `good` logging setup, the v15 upgrade has caused some trailing responses to not be logged when calling `server.stop()`.

As far as I can tell, this is due to a podium bug, where it drops emitted events. See https://github.com/hapijs/podium/issues/15.

**Comment by hueniverse** [comment]
Can you provide an example where this happens with hapi? When do you remove the event listeners in relation to `server.stop()`? I assume by lost you mean they are emitted after the listener was removed?

**Comment by kanongil** [comment]
No, they will be completely missing. Like in my podium issue example – eg. if you wait around, nothing happens.

**Comment by kanongil** [comment]
Hmm, I tried to replicate this, and it seems that this is in fact a `good` specific problem, which removes its event listeners in an `onPostStop` hook (and thus doesn't receive any trailing events).

**Comment by hueniverse** [comment]
I'll close this assuming you will pick this up with good.

**Comment by kanongil** [comment]
I'm not sure that this is a good bug, especially considering it works on pre podium Hapi. My current thinking is that it just uses it in a specific way, that triggers a bug in Hapi/podium.

**Comment by hueniverse** [comment]
When are these events emitted? The was podium work, when the stop event is emitted, all other previously emitted event must have been flushed out. Are these events emitted after the stop event is emitted? And if that's the case and the onPostStop removed the listener, why should it receive them?

**Comment by kanongil** [comment]
No worries, the issues was fixed with the v16 release and https://github.com/hapijs/podium/pull/17.
