### ISSUE TITLE
Regression on 16, lib/handlers.js

### ISSUE THREAD

**Issue by simlevesque** [hapijs/hapi#3399]
Hi everyone.

I'm experiencing a regression on 16. One of the routes on my hapi application won't respond. This route has a prerequisite without assignment and the error is triggered while still inside the pre.

The line that's causing problem is the 65th of lib/handler.js. The error says that domain is undefined, thus it cannot read it's bind property.

To fix the error, the only thing I did was change ^16.0.0 in my package.json to ^15.2.0, delete the node_modules and reinstall. Now everything works as it always did.

Sadly I can't give you access to my code and I don'T have the time at the moment to create a server which exhibits the bug. I'll try to do one soon.

Thank you.

**Comment by hueniverse** [comment]
Are you using promises?

**Comment by simlevesque** [comment]
I am. Let me try to do the same thing without them and see if the same thing happens.

**Comment by sirgallifrey** [comment]
This code works on 15.2.0 and fails as @simlevesque  described in 16.0.0

```javascript
const Hapi = require('hapi');

const server = new Hapi.Server({ useDomains: false });

server.connection({port: 3000});

server.route({
    method: 'get',
    path: '/',
    handler: function (req, reply) {

        reply('working');
    },
    config: {
        pre: [{
            method: function(req, reply) {
                
                reply('pre');
            }
        }]
    }
})

server.start((err) => {

    if (err) {
        throw err;
    }

    console.log('server running');
});

```

Note `useDomains: false` in combination with pre handler

**Comment by sirgallifrey** [comment]
Line [57](https://github.com/hapijs/hapi/blob/master/lib/handler.js#L57) is just assuming there is a domain in place

**Comment by simlevesque** [comment]
NB: In my setup, useDomains is true.

**Comment by sirgallifrey** [comment]
@simlevesque I thought it would be. My guess is that there might be a lot o causes for `process.domain === undefined` I think we can focus on making handler.js know what to do when there is a domain and where there isn't

**Comment by sirgallifrey** [comment]
Noticed something that might be relevant, I'm trying to write a test for this, and I can't make a test that fails.... I don't have knowledge on how lab works, but I'm guessing it creates a domain and thus process.domain !== undefined
