### ISSUE TITLE
request.query with encoded params

### ISSUE THREAD

**Issue by mattberridge** [hapijs/hapi#3402]
A query about encoded query parameters...

I've a hapi server running among other things, and image proxy. I've a handler set like so:

```
server.route({
  method: 'GET',
  path: '/images/{params*}',
  config: {
    handler: imageProxy
  }
});
```

When a request hits this with encoded parameters, e.g
```
http://example.com/images?url=/a5d0a7004b82450096a5fc8f1fd3e0df&amp;w=800
```

Then the result of `request.query` does not decode the parameter keys, so when I `console.log` in my `imageProxy` handler like so:

```
export default (request, reply) => {
  console.log(request.query);
};
```

The following is returned:

```
{
  'url': '/a5d0a7004b82450096a5fc8f1fd3e0df',
  'amp;w': 800
}
```

Is this intended behaviour or is there something I have missed when configuring the route?

As a work-around for now I have the following helper in place in the handler.

```
import { mapKeys } from 'lodash/object';

const decodedQuery = mapKeys(query, (value, key) => {
  return key.substr(0, 4) === 'amp;' ? key.substring(4) : key;
});
```

Giving me as required:

```
{
  'url': '/a5d0a7004b82450096a5fc8f1fd3e0df',
  'w': 800
}
```

---

* *node version*:
v4.0.0

* *hapi version*:
13.5.0

**Comment by hueniverse** [comment]
That's how query parameters are parsed. HTML entity encoding are not valid in query.
