### ISSUE TITLE
strange bug, sometimes i got wrong query params

### ISSUE THREAD

**Issue by ColorfulCow** [hapijs/hapi#3405]
i request two api  like the following,:

A:  localhost:8072/api/a?location=5
B:  localhost:8072/api/a?location=8

 in the case of a high frequency, sometimes i got the reply.query.location is 5 in requesting B

**Comment by ColorfulCow** [comment]
now it's not only the wrong query params, by the verification，i got wrong reply object

**Comment by calmdev** [comment]
Share an example of the code that is causing you trouble. It's almost impossible to help otherwise.

**Comment by ColorfulCow** [comment]
code like this
`
// router
[
  {
    method: 'GET',
    path: '/api/app/ad',
    config: {
      handler: adAppService.getAppAd
    }
  },
  {
    method: 'GET',
    path: '/api/quan/ad',
    config: {
      handler: adAppService.getQuanAd
    }
  },
]
`
`
function mapping(result, locationId, pathname) {
  try {
    return result.map(_ => ({
      bannerId: _.id,
      title: _.title,
      picUrl: _.pic_url,
      action: adActionData[_.action_id].content,
      actionParam: _.action_content,
      topic: _.topic,
      LocationId: locationId,
      Pathname: pathname,
    }))
  } catch (e) {
    throw new Error('error in ad mapping')
  }
}
`
`async function getAd(req, res) {
    const locationId = req.query.location
    const pathname = req.path
    let adList = []
    const result = await appModel.getAdForAllStation(locationId, TARGET_ALL_STATION)
    adList = mapping(result, locationId, pathname)
    return res(createRes(true, 0, '', adList))
 }
`
` 
export default {
@catchErrorForService('app get ad list')
  async getAppAd(req, res) {
    return await getAd(req, res)
  },
@catchErrorForService('zhenliaoquan get ad list')
 async getQuanAd(req, res) {
    return await getAd(req, res)
  }
}
`

 i requesting /api/quan/ad?location=8 and /api/app/ad?location=5 at the same time in the case of a high frequency,
but i got response like this in requesting /api/quan/ad?location=8: 
{
  "succeed": true,
  "resultStatus": 0,
  "reason": "",
  "data": [
    {
      "bannerId": 202,
      "title": "test title",
      "picUrl": "test pic url",
      "action": "QUAN_URL",
      "actionParam": "https://www.baidu.com/",
      "topic": "test",
      "LocationId": 5,
      "Pathname": "/api/app/ad"
    },
  ]
}
obviously, the response LocationId and Pathname is wrong

**Comment by calmdev** [comment]
Edit the post and wrap the code in tripple backticks so it's easier to read, please:
https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by ColorfulCow** [comment]
@calmdev

**Comment by calmdev** [comment]
That's easier to read, but unfortunately I don't have any experience using async/await with hapi or at all really, I'm still using callbacks and promises. Looking at your code I don't seeing anything _obvious to me_ standing out that would be causing your issue. Hopefully someone else can point you in the right direction though 🤔

**Comment by ColorfulCow** [comment]
@calmdev i hope so, thanks a lot for replying *_*

**Comment by hueniverse** [comment]
I suggest you try to reproduce this without the async/wait and see if that makes a difference.

**Comment by ColorfulCow** [comment]
@hueniverse  i still using async/await, but after i modify code like this, the response seems correct
```javascript
async function getAd(req, res) {
    const locationId = req.query.location
    const pathname = req.path
    let adList = []
    const result = await appModel.getAdForAllStation(locationId, TARGET_ALL_STATION)
    adList = mapping(result, locationId, pathname)
    // add .hold()
    const response = res(createRes(true, 0, '', adList)).hold()
    return response.send()
 }
```

**Comment by kanongil** [comment]
The difference, contrary to what the docs say, is that the reply is sent immediately, instead of on `nextTick`.

The `send()` logic that is applied is very different depending on what is returned from you `createRes()` method. Can you elaborate on this?

**Comment by ColorfulCow** [comment]
```javascript
function createRes(isSuccess, errorCode, reason, data) {
  commonData.succeed = isSuccess
  commonData.resultStatus = errorCode
  commonData.reason = reason
  commonData.data = data
  return commonData
}
```
createRes() is just a sync function to create a object and return it

**Comment by kanongil** [comment]
Ah, so this is where you fail. You are modifying a shared object instead of creating a new one / returning a clone. This means that another request can have a chance to modify the object before it is serialized in hapi.

For future reference, these kind of questions should go in the [hapijs/discuss](https://github.com/hapijs/discuss) repo.

**Comment by ColorfulCow** [comment]
@kanongil  thanks a lot, 
but i still have a confusion，nextTick will push the response function to the top of the next event loop, why the other request have the chance to modify the object

**Comment by kanongil** [comment]
@ColorfulCow I'm not sure how this happens exactly.

In any case, you should not rely on the handler not being called before the response is serialized.

**Comment by ColorfulCow** [comment]
Ah, i wanna know why reply() using process.nextTick() instead of send response  immediately? @hueniverse @kanongil

**Comment by hueniverse** [comment]
Nothing is sent immediately. There are lots of steps before the response is serialized and transmitted. And we use next tick to allow changes to the response object after it is created by chaining modifiers to the reply interface.
