### ISSUE TITLE
Server.inject array as query params

### ISSUE THREAD

**Issue by doron2402** [hapijs/hapi#3407]
Seems like when using `server.inject({ method: 'get', url: '/users?SOMEKEY=[1,2,3]' }, callback...`
there's a bug when parsing the array 

Validation:
```javascript
Joi.array().items(Joi.number().integer()).optional()
```

Test:
```javascript
describe('sort result by array', () => {
    it('Should return a collection...', (done) => {
      const req = {
        method: 'GET',
        url: '/users?users=[1,2]' ,
        headers: {
          authorization: JWT.sign({ data: ... }, secret)
        }
      };
      server.inject(req, (res) => {
        console.log(res.result);
        done();
      });
    });
  });
```

Here's the error:
```
Can only assert empty on object, array or string
      at Object.exports.assert (node_modules/hoek/lib/index.js:736:11)
      at Object.internals.assert (node_modules/code/lib/index.js:472:14)
      at internals.length (node_modules/code/lib/index.js:253:15)
```

I've also try to change the url to `/stations?missions[0]=1` I got this error:
```javascript
{ statusCode: 400,
  error: 'Bad Request',
  message: '"missions&#x5b;0&#x5d;" is not allowed',
  validation: { source: 'query', keys: [ 'missions&#x5b;0&#x5d;' ] } }
```

Thanks

**Comment by sirgallifrey** [comment]
Can you test with something like this?

```javascript

const uriEncodedArray = encodeURIComponent('[1,2,3]');

server.inject({ method: 'get', url: '/users?SOMEKEY=' + uriEncodedArray }, callback...
```

**Comment by doron2402** [comment]
@sirgallifrey thanks for the quick response but that's also fail...
it's the same as `somekey=1&somekey=2...`
I think the issue is also with joi when it's try to validate the url it expect to get an array... :/

**Comment by sirgallifrey** [comment]
Your joy validation must be an object with a key that with receive the array, like this:

```javascript
server.route({
    method: 'GET',
    path: '/',
    config: {
        handler: function(request, reply) {

            reply(request.query.key);
        },
        validate: {
            query: Joi.object().keys({
                key: Joi.array().items(Joi.number().integer()).optional()
            })
        }
    }
});
```
you can rename `key``to whatever you like

you can see a working code on [this gist](https://gist.github.com/sirgallifrey/85e0bb4d800f7692d8e6e5962565ad2a)

**Comment by doron2402** [comment]
that's exactly what I did (checkout my initial comment I've added my joi validation), anyway we decide not to use an array on the url but not sure if that's a bug or not

**Comment by hueniverse** [comment]
That's just not an array. It is a string that looks like a JS array. Last time I checked, joi doesn't parse strings to look for `[]` structures. That would be a bit much. A query string array is `a=1&a=2&a=3`
