### ISSUE TITLE
server methods are not being passed their callback

### ISSUE THREAD

**Issue by turtleDev** [hapijs/hapi#3410]
#### What are you trying to achieve or the steps to reproduce?

Hi,

I can't seem to get server methods to work.
It appears that the server methods are not passed their callback argument. Is this a bug, or am I missing something?

```js

'use strict';

const Hapi = require('hapi');

const server = new Hapi.Server();

server.connection({
    port: 8080
})

server.method('what', function(cb) {
    console.log('well, I will be damned');
    return cb();
}, {});

server.start(() => {

    server.methods.what()
});

```

#### What was the result you received?
```
TypeError: cb is not a function
    <stack trace>
```

#### What did you expect?
well, I will be damned

#### Context

* *node version*: v6.9.1
* *hapi version*: 16.0.1
* *os*: Ubuntu 14.04

**Comment by hueniverse** [comment]
You are not passing a callback to `server.methods.what()`...

**Comment by turtleDev** [comment]
@hueniverse isn't the callback supposed to be passed by Hapi?

https://hapijs.com/tutorials/server-methods#function
> The method parameter is the actual function to call when the method is invoked. It can take any number of arguments but must accept a callback as its last parameter.The callback accepts three parameters: err, result, and ttl

**Comment by hueniverse** [comment]
It's a function that you provide, like any other function. The fact you are calling it as a method doesn't change anything. I don't know what you are expecting hapi to pass there but no. You call your own function with your own callback.

**Comment by turtleDev** [comment]
I see. However, the docs make it ambiguous. If server methods are just a namespace and carry no addtional semantics, then the docs stating that their last argument _must_ be a callback make it confusing. The fact that they even tell you it's arguments is weird as well.

**Comment by hueniverse** [comment]
It matters when you set caching on.

**Comment by turtleDev** [comment]
fair enough :)
