### ISSUE TITLE
Hapi is not honouring Route security config option

### ISSUE THREAD

**Issue by imtiazwazir** [hapijs/hapi#3413]
Hapi is sending 2 x-frame-options headers while I have set only one in route config.

client iframe error:

<img width="955" alt="2b8b2fe0-c7a2-11e6-9520-f2b179308c7d" src="https://cloud.githubusercontent.com/assets/1964969/21424948/ed3cc048-c867-11e6-987e-863836f41c8d.png">

client header response:

<img width="416" alt="2b8e74ac-c7a2-11e6-971c-b861d865f47f" src="https://cloud.githubusercontent.com/assets/1964969/21424963/04eeae86-c868-11e6-87e5-9f78f13282cb.png">

my route has following config:

`    
config: {
      description: 'Return generaed url for client',
      cors: true,
      security: {
        xframe: {
          rule: 'allow-from',
          source: 'http://datameister.co.jp'
        }
      },
...
`

my package.json dependency looks something like below
`
  "dependencies": {
    "file-extension": "^3.1.0",
    "glue": "^4.0.0",
    "handlebars": "^4.0.6",
    "hapi": "^16.0.1",
    "hapi-auth-basic": "^4.2.0",
    "hapi-sequelize": "^3.0.4",
    "hoek": "^4.1.0",
    "inert": "^4.0.3",
    "joi": "^10.0.5",
    "mysql": "^2.12.0",
    "mysql2": "^1.1.2",
    "nes": "^6.3.2",
    "sequelize": "^3.27.0",
    "vision": "^4.1.1"
  },
`

**Comment by Marsup** [comment]
When I see `Server: Apache`, I can only doubt that it's hapi's fault. Could you check without it ?

**Comment by AdriVanHoudt** [comment]
Dupe of https://github.com/hapijs/discuss/issues/419

**Comment by imtiazwazir** [comment]
Thanks for your help and closing this topic without my input

**Comment by calmdev** [comment]
He closed it because you've posted the same issue twice in two different places within the same org. It was even cross referenced for you before being closed. Why not continue the discussion there instead and provide feedback to those who are trying to help you. You've already been asked multiple times to try without apache. It seems people _are waiting for your input_.
