### ISSUE TITLE
Resolve server method lazily when using short-hand string notation for handler

### ISSUE THREAD

**Issue by devinivy** [hapijs/hapi#3421]
When using the special short-hand string notation for route handlers or pre-requisites, the server method specified is resolved at the time of registering the route.  I find it would be more flexible to instead resolve the server method as-needed (at the time of the request).  This enables monkey-patching server methods, which is sometimes useful during testing.

**Comment by hueniverse** [comment]
Sounds slow.

**Comment by devinivy** [comment]
It would be no slower than simply using a server method in a handler, which isn't usually considered a bad practice.  I can't imagine indexing into an object being the type of thing that's going to slow your server down.  At least that level of perf granularity is far removed from my world.  Again, any use of server methods in a handler or pre-requisite function is considered "lazy" in the sense that I'm using it here.

**Comment by hueniverse** [comment]
`Hoek.reach()` is pretty terrible for runtime performance. Where are you suggesting to construct the shim that calls the actual server method? In general, the string notation was a cool idea that can produce really clean route config (as well as moving route config to JSON files lacking function support), but in practice, I never use it because it is slower than just providing a function that calls the method. Same reason `bind()` is a bad idea when you can manually create the closure you want.

**Comment by devinivy** [comment]
I see what you're getting at.  I think there still are ways this could be both lazy and performant.  Here's one example.  Consider `'some.long.specificName(params.id)'`.  Split the name into `basePath = 'some.long'` and `methodName = 'specificName'`.  At route registration time resolve the base, `Hoek.reach(server.methods, basePath)`.  Then in the handler itself finally resolve the method as `base[methodName]`.

**Comment by hueniverse** [comment]
This feels like a waste of time and a lot of added complexity. I don't see the point.

**Comment by devinivy** [comment]
The point is for the short-hand handler feature to work with monkey-patched server methods, which I personally find valuable for testing purposes.  It will add some complexity to support that while being performant.  Naturally it's up to you if those balance out!  I would be happy to contribute the code.

**Comment by hueniverse** [comment]
I don't see the value.
