### ISSUE TITLE
Remove "Vary: Origin" for wildcard CORS origins

### ISSUE THREAD

**Issue by rubennorte** [hapijs/hapi#3423]
At the moment, enabling CORS in a route using `cors: true` or `cors: { origin: ['*'] }` sets the following response headers:

```
Vary: Origin
Access-Control-Allow-Origin: <origin-request-header-received>
...
```

This breaks caches unnecessarily as it could be done for all requests the same way:

```
Access-Control-Allow-Origin: *
```

I've found this issue because I have dynamic subdomains in my site and CloudFront has been caching different versions of each static file for each origin, when it's not necessary.

Would you accept a PR changing this behaviour only for routes configured that way? I'm pretty sure it requires just a small change in the code.

**Comment by rubennorte** [comment]
I tried modifying the header in a `onPreResponse` extension but the code that handles the CORS options is executed after all extension points, so it's not possible.

As a workaround I've implemented the CORS headers myself but that way I loose all the features this options provides (OPTIONS method, validation, etc.).

**Comment by kanongil** [comment]
I think a CDN-friendly mode would be a nice addition to Hapi, as it is something that I have had to work-around in the past.

I don't think it should be signalled as you suggest, rather it needs to be a distinct option, since it changes the way the CORS headers are validated and transmitted. Eg. it needs to _always_ add the CORS headers to responses to safely remove the `Vary: Origin` header. Even for non-CORS requests.

Note that Hapi used to work this way until it was completely reworked in one of the releases.

**Comment by rubennorte** [comment]
> I don't think it should be signalled as you suggest, rather it needs to be a distinct option, since it changes the way the CORS headers are validated and transmitted. Eg. it needs to always add the CORS headers to responses to safely remove the Vary: Origin header. Even for non-CORS requests.

I understand it would be necessary to always set the CORS headers in this particular case, but is that a problem? I rather have some additional headers and be able to cache my responses.

IMO setting a new configuration option is adding unnecessary complexity.

**Comment by kanongil** [comment]
> IMO setting a new configuration option is adding unnecessary complexity.

In general, Hapi prefers explicit options, rather than implicit as you suggest. It is also kind of required since there are valid use-cases for the config you mention, where you expect the existing behaviour. 

Finally, re-intepreting the meaning of the config is a breaking change.

**Comment by rubennorte** [comment]
I think it's actually more explicit setting `Access-Control-Allow-Origin: *` for an origin option `['*']` than the current behaviour. It's also the regular behaviour in other libraries, such as the  express "cors" middleware.

What alternative would you use? I'd be glad to consider and implement a better alternative.

About the breaking change, I understand that isn't something that usually prevents changes in Hapi, as major versions are released regularly.

**Comment by rubennorte** [comment]
I just realized that, if I implement my proposal, the Origin header will no longer be required in OPTIONS requests when the origin is configured using a wildcard. That way OPTIONS requests can also be cached more efficiently.

If you'll consider these changes I'm willing to create a PR ASAP.

**Comment by rubennorte** [comment]
Any consideration on this?

**Comment by rubennorte** [comment]
@hueniverse will you reconsider this, now that many breaking changes will be introduced in v17?

**Comment by hueniverse** [comment]
I don't want to change existing behavior but I'm open to adding a special case for this. Maybe use `'**'` as the origin value?

**Comment by rubennorte** [comment]
I'm not sure `'**' ` is intuitive enough. The express cors module [does it](https://github.com/expressjs/cors/blob/master/lib/index.js#L41) using `'*'` to set `Access-Control-Allow-Origin: *` and the boolean value `true` to reflect the received header. WDYT?

**Comment by hueniverse** [comment]
I don't want this to be breaking. Maybe add a new setting?

**Comment by rubennorte** [comment]
I understand. Perhaps an option like `expandWildcard: true|false` being `true` by default would be fine.

**Comment by hueniverse** [comment]
Try it

**Comment by rubennorte** [comment]
I finally used `wildcardIgnoresOrigin` as it does more than just expanding wildcards (ignores the origin header completely if set).
