### ISSUE TITLE
request.payload on onRequest is always null

### ISSUE THREAD

**Issue by Zuckonit** [hapijs/hapi#3424]
version: hapi 14.20

question:
>    request.payload on onRequest is always null

code:

```
    server.ext('onRequest', function(request, reply) {
        console.log(requeset.payload); //always null
    })
```

test:
>    curl -XPOST http://localhost:5601/hello -d "name=Paul2"

**Comment by sirgallifrey** [comment]
Payload has not yet been parsed at the time of onRequest. Have a look at this awesome cheatsheet 

![](https://pbs.twimg.com/media/CF1VSUKUsAEDQad.png)

**Comment by AdriVanHoudt** [comment]
Here is version 2 ;)
![](https://pbs.twimg.com/media/CL-bp3_W8AAimRi.png:large)
by the great @mtharrison

**Comment by kafkahw** [comment]
Any idea how to access request's body on onRequest since payload is always null?

**Comment by hueniverse** [comment]
@kafkahw you can't. You can only process the request stream on your own but that would create problems elsewhere. Just use the appropriate lifecycle spot instead.
