### ISSUE TITLE
reply.entity() will always return null for correct etags

### ISSUE THREAD

**Issue by dypsilon** [hapijs/hapi#3427]
The test fixture in [test/reply.js](https://github.com/hapijs/hapi/blob/master/test/reply.js#L890) is not correct because a valid etag looks like this: 

~~~
server.inject({ url: '/', headers: { 'if-none-match': '"abc"' } })
~~~

Please note the quotes around abc. Particularly this is how the browsers send them. If you change this line to a correct etag the count will always be 2 and the test will fail.

**Comment by kanongil** [comment]
Wow, good catch. We should fix this.
