### ISSUE TITLE
CORS does not add additional headers

### ISSUE THREAD

**Issue by masted** [hapijs/hapi#3428]
I'm trying to add additional headers to all my OPTIONS responses for CORS. But still have no effect.

```js
  server.connection({
    host: 'localhost',
    port: 8000,
    routes: {
      cors: {
        origin: ['*'],
        additionalHeaders: ['X-Requested-With', 'X-Request']
      }
    }
  });
```

#### Context
nodejs version: 7.2.0
hapi version: 16.1.0
hapi-cors version: 1.0.1
os: Ubuntu 16.04

**Comment by dubcdr** [comment]
seeing a similar issue 

**bump**

**Comment by Marsup** [comment]
Since you mentioned "responses", I guess you should check `additionalExposedHeaders`, the one you're using is for incoming headers.
