### ISSUE TITLE
Disable STDOUT logging for internals.Request and internals.handler

### ISSUE THREAD

**Issue by codemouse** [hapijs/hapi#3433]
Trying to configure a route to disable logging via a declaration of log:false within the route config, as such:

```js
  server.route({
    path: '/service-status',
    method: 'GET',
    config: {
      handler: handler.getStatus,
      log: false
    }
  });
```

Debugging through the chain to hapi internals, it looks like this log:false is honored as a value but unfortunately I still cannot disable the logging entirely to STDOUT for two entries, that seem to appear as something like the following:

"method":"get","url":"/service-status","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36"

and then,

"msec":10.816219002008438

I feel like either I'm clearly missing something or need to work on filtering the STDOUT from my logging process. Is there a way to disable this from getting out? The code appears to be honoring the lack of pushing to _logger but is still writing this out at some point (possibly connection.emit?).  Help in navigating this would be useful.

The goal would be to disable logging entirely for certain routes used as relatively simplistic health checks.

* *node version*: 7.5
* *hapi version*: 16.1.0
* *os*: ubuntu 16.04

Brian

**Comment by hueniverse** [comment]
Are you using good? any other logging plugin?

**Comment by codemouse** [comment]
Figured this out and now feel foolish. My logging was done via bunyan and I have the hapi-bunyan plugin still enabled.  Removed and wrote my own logic appropriately, everything is good.  Closing out.
