### ISSUE TITLE
question about the hapi authenticate

### ISSUE THREAD

**Issue by xycloud** [hapijs/hapi#3435]
I have a authenticate way with two step:
1: before user access a url, I will judge whether the cookie contains some value A, if not, redirect to a special authenticate token server, it will callback a route on my app and bring with the value A, and I will set the value A in cookie.
    if cookie contains Value A already, turn to step 2

2: basic authenticate

I am sorry, how can I implement this in hapi

**Comment by hueniverse** [comment]
When you created this issue, you clearly ignored the instructions:

Issues should only be posted in this repository after you have been able to reproduce
them and confirm that they are either a missing functionality or a bug. If you are in
need of help resolving your issue or are not sure, please do not open an issue here.
Instead, open an issue in the [discussion repository](https://github.com/hapijs/discuss).
