### ISSUE TITLE
how to expose an instance

### ISSUE THREAD

**Issue by xycloud** [hapijs/hapi#3436]
hapi: 14.x
question: expose an client instance by using server.expose failed

```
const urllib = require('urllib');

const client = urllib.create({...});

server.expose(client);

```
cannot use client's request function by server plugin

**Comment by sirgallifrey** [comment]
> Note that all properties of obj are deeply cloned into server.plugins[name], so you should avoid using this method for exposing large objects that may be expensive to clone or singleton objects such as database client objects. Instead favor the server.expose(key, value) form, which only copies a reference to value.

Probably giving a key to you client will solve, try this:
```
const urllib = require('urllib');

const client = urllib.create({...});

server.expose('httpclient', client);

server.plugins['httpclient'].request()
```

**Comment by sirgallifrey** [comment]
> Note that all properties of obj are deeply cloned into server.plugins[name], so you should avoid using this method for exposing large objects that may be expensive to clone or singleton objects such as database client objects. Instead favor the server.expose(key, value) form, which only copies a reference to value.

try setting this way:

```
const urllib = require('urllib');

const client = urllib.create({...});

server.expose('httpclient', client);

server.plugins[pluginName]['httpclient'].request()
```

**Comment by Marsup** [comment]
Decrypting the issue for @hueniverse, it's probably because he's trying to access methods on the prototype of the exposed object, which are obviously not copied. I don't think you intend to fix this but just making sure...

**Comment by sirgallifrey** [comment]
I agree with @Marsup , I also don't think this need fixing. If something we could enhance the docs.

Where it says:

> singleton objects such as database client objects. Instead favor the server.expose(key, value) form, which only copies a reference to value.

We could make:

singleton objects such as database client objects **or objects that rely on prototypal inheritance**. Instead favor the server.expose(key, value) form, which only copies a reference to value.

**Comment by hueniverse** [comment]
Agree. If someone thinks the docs can be improved, go for it.
