### ISSUE TITLE
Cannot change Accepted-Range header in a response

### ISSUE THREAD

**Issue by Drakehawk** [hapijs/hapi#3442]
Hi. I need to set a custom range in the Accepted-Range header in a response. 
As far as I have read. Hapi automatically set's the range as bytes:

https://github.com/hapijs/hapi/blob/09c2e3374cf0ad63144f90268fb0b0d0e8a2ceba/lib/transmit.js#L199

An issue about this was already made: https://github.com/hapijs/hapi/issues/3015, but the solution was to simply remove the header, which doesnt solve the problem entirely.

Here's a simple case that shows it's always set:

### Request

```
server.route({
            method: "GET",
            path: "/api/test",
            handler: (request, reply) => {
                var msg = "test-Range";
                var response = reply(msg);
                response.header("accept-ranges", "items");
                response.header('Content-Range', 'items 0-49/600');
            },
        });
``` 

### Response
```
HTTP/1.1 200 OK
accept-ranges: bytes
content-range: items 0-49/600
x-powered-by: Node/6.3.0 Trails/1.1.0
vary: origin
```

It probably seems needless or useless but I need to set custom ranges since I'm using Dojo components that require ranges to be items not bytes.

#### Context

* *node version*:
6.3.0
* *hapi version*:
13.4
* *os*: 
Linux

**Comment by kanongil** [comment]
Check the `response.ranges` setting to disable the built-in behavior for a route.

**Comment by Drakehawk** [comment]
Thanks. Setting response.ranges to false did the trick.
