### ISSUE TITLE
Disable validation of Content-Type

### ISSUE THREAD

**Issue by danihodovic** [hapijs/hapi#3445]
#### What are you trying to achieve or the steps to reproduce?

My API is only accepting file uploads with the header `application/octet-stream`. I use Joi to validate that the header value is valid. I only allow `application/octet-stream`.

```js
  {
    method: 'POST',
    path: '/',
    handler: post,
    config: {
      validate: {
        headers: Joi.object({
          'content-type': Joi.string().valid('application/octet-stream').required()
        }).options({allowUnknown: true});
      },
    }
  }
```
#### What was the result you received?

Whenever I try to send a request towards the endpoint with the `Content-Type: multipart/form-data` header I get the response:

```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "Invalid content-type header: multipart missing boundary"
}
```

#### What did you expect?
The above error comes from Hapi's internal validation, presumably from https://github.com/hapijs/content. The payload is not validated against my schema as it fails before that.
The error message is not informative as an API consumer would expect. I want to directly specify in the error message that the `Content-Type` can only be `application/octet-stream`.

This is what I expect:
```
const schema = Joi.object({
  'content-type': Joi.string().valid('application/octet-stream').required()
}).options({allowUnknown: true});

const error = Joi.validate({'content-type': 'multipart/form-data'}, schema);
console.log(error.error.details[0].message)
// "content-type" must be one of [application/octet-stream]

```

I'm currently working around this by validating the `Content-Type` header in `onPreAuth` so that it fails before it reaches the internal Hapi header validation. I don't find this an elegant solution. Is it possible to disable validation done by https://github.com/hapijs/content entirely?

#### Context

* *node version*: v6.9.4
* *hapi version*: 16.1.0
* *os*:  Ubuntu 16.04.2 LTS
* *any other relevant information*:

**Comment by kanongil** [comment]
Please direct usage questions to the [discuss](https://github.com/hapijs/discuss) repo.
