### ISSUE TITLE
one server is always leaked

### ISSUE THREAD

**Issue by cjihrig** [hapijs/hapi#3447]
#### Are you sure this is an issue with hapi or are you just looking for some help?

This is an issue with hapi. You may or may not care to fix it.

#### What are you trying to achieve or the steps to reproduce?

Create one or more `Server` objects.

#### What was the result you received?

[This function](https://github.com/hapijs/hapi/blob/713ec759714e493def9cbb114234309c71035d7b/lib/plugin.js#L68) captures various things, including the `server` object. The memory associated with the last call can never be released because `this.cache` is on the prototype.

#### What did you expect?

I don't expect much out of life.

#### Context

* *node version*: 7.3.0
* *hapi version*: master
* *os*: macOS
* *any other relevant information*:

If you care to fix this, it should be as simple as moving `cache` to the instance instead of the prototype. I can give it a shot and send a PR if you want. If it's not that important or by design, just close the issue.

**Comment by AdriVanHoudt** [comment]
This is a nice and sad report at the same time :O

**Comment by cjihrig** [comment]
I don't think dc52c138cc6973c93faa5e6775893e3fa147a310 fixes the leak. `internals` is around for the entire execution of the application, so it holds the reference like the prototype was previously.

**Comment by hueniverse** [comment]
@cjihrig what about this?

**Comment by cjihrig** [comment]
I tested by running a few of the tests in `test/server.js`, adding an `after()` hook at the end of the tests, and taking a heap snapshot. The snapshot for the [latest commit](7f15394156f3587e897bd5ef5713bc8a588de662) has lower memory consumption and no instances of `module.exports.internals.Server` 👍

**Comment by hueniverse** [comment]
Thanks.
