### ISSUE TITLE
cache tests should call server.stop(done)

### ISSUE THREAD

**Issue by cjihrig** [hapijs/hapi#3450]
#### Are you sure this is an issue with hapi or are you just looking for some help?

yes

#### What are you trying to achieve or the steps to reproduce?

I'm looking at memory usage in tests. Some of the tests create timer objects, but don't clear the timer when the test is done. An example is some of the cache tests. Items in the cache get a timer associated with them. If you call `done()` in the test, eventually they will expire. Until then, the timer reference is kept alive, along with any memory it points to. Using `server.stop(done)` cancels the cache timers.

#### What was the result you received?

See above

#### What did you expect?

See above

#### Context

* *node version*: 7.3.0
* *hapi version*: master
* *os*: macOS, but doesn't matter
* *any other relevant information*: This is a low priority fix. Possibly a good first contribution.

**Comment by grantlouisherman** [comment]
@cjihrig I can take this, please assign to me.

**Comment by cjihrig** [comment]
@grantlouisherman just go ahead and work on it and submit a PR.

**Comment by kanongil** [comment]
Are you sure this is still an issue? The latest `catbox` release clears timeouts when sending the response.

**Comment by cjihrig** [comment]
I'm not sure. I haven't looked into this since March.

**Comment by hueniverse** [comment]
It's a good idea to call `stop()` after every `start()`
