### ISSUE TITLE
Have access to request.app in Joi validation context

### ISSUE THREAD

**Issue by cur3n4** [hapijs/hapi#3451]
#### Are you sure this is an issue with hapi or are you just looking for some help?

Yes.

#### What are you trying to achieve or the steps to reproduce?

Sometimes during Joi validation on a route, it is useful to have access to request.app to check some values. Currently the Joi validation context contains request headers, params, query, payload, and auth.

#### What did you expect?

I would expect to be able to access request.app in Joi, same as the other request attributes

#### Context

* *node version*:7.2.1
* *hapi version*:13.2.1
* *os*:MacOS

Let me know if this change makes sense to you and I can try to do a PR.

**Comment by AdriVanHoudt** [comment]
I think only a few properties are available since they are being copied into the context object.
So my only concern would be perf I think but if you send a massive payload you have the same issue I think.

/cc @Marsup

**Comment by Marsup** [comment]
I know for a fact it's not exposed, I don't know if @hueniverse wants to, sorry can't help you on this one.

**Comment by cur3n4** [comment]
Thanks a lot
