### ISSUE TITLE
route config id - only number allowed, should be string

### ISSUE THREAD

**Issue by eobrien-fsp** [hapijs/hapi#3468]
Route id attribute is supposed to be a string, as per the documentation.

https://hapijs.com/api#serverlookupid

* *hapi version*:16.1.1

**Comment by AdriVanHoudt** [comment]
Can you share some code that show your issue?

**Comment by eobrien-fsp** [comment]
https://github.com/hapijs/hapi/blob/master/lib/connection.js#L340

This specifically prevents the use of string id's, when the documentation indicates that they should be allowed.

**Comment by eobrien-fsp** [comment]
`        let s = new hapi.Server();

        s.route({
            method: 'GET',
            path: '/',
            config: {
                handler: function (request, reply) {
                    return reply({});
                },
                id: 1
            }
        });

        let r = s.lookup(1);`

Typescript indicates an error on the s.lookup, because it expects a string parameter.

`        let s = new hapi.Server();

        s.route({
            method: 'GET',
            path: '/',
            config: {
                handler: function (request, reply) {
                    return reply({});
                },
                id: "root"
            }
        });

        let r = s.lookup("root");`

In this alternatively, s.route indicates an error, because it won't allow a string id.

**Comment by eobrien-fsp** [comment]
It appears it may be a problem with @types/hapi, not hapi itself.
