### ISSUE TITLE
Adding a onPreValidate extension point

### ISSUE THREAD

**Issue by guidsen** [hapijs/hapi#3471]
It would be great if we could transform certain incoming payload or query parameters, before going into the Joi validation.

Let's take a look on an example having some kind of API convention:

`URL -> /api/users?include=posts,comments&select=id,name`

I currently don't know how I would validate the `include` and `select` query parameters with Joi. It would be pretty useful to have an extension point that is called something like `onPreValidate`.

Example implementation:

```
const onPreValidate = (req, next) => {
  req.query.include = req.query.include.split(',');
  req.query.select = req.query.include.split(',');

  return next(req);
};
```

So I could easily validate this using:

```
{
  query: {
    include: Joi.array().items(Joi.string().valid('posts')),
    select: Joi.array().items(Joi.string().valid('id', 'name', 'place')),
  },
}
```

It can also be quite useful when passing JSON stringified payload data from the client. Quick example:
```
const onPreValidate = (req, next) => {
  req.payload.settings = JSON.parse(req.payload.settings);

  return next(req);
};
```

```
{
  payload: {
    settings: {
      foo: Joi.string().required(),
      baz: Joi.string(),
    },
  },
}
```

What is your thought on this @hueniverse? I could even create a PR to help you implement this.

**Comment by AdriVanHoudt** [comment]
You can provide your own querystring parser by doing something like
```js
const Url = require('url');
const Qs = require('qs');

const onRequest = function (request, reply) {

    const uri = request.raw.req.url;
    const parsed = Url.parse(uri, false);
    parsed.query = Qs.parse(parsed.query);
    request.setUrl(parsed);

    return reply.continue();
};

server.ext('onRequest', onRequest);
```
As you can see you do pretty much whatever you want in there do customize the query object to your needs.
Hope this helps 💪

**Comment by guidsen** [comment]
Ah yeah, I can also do that. It just felt to me that it would be great to have an hook before validation because it's actually a step inside the life cycle. Most of the other lifecycle methods have their own extension point.

**Comment by AdriVanHoudt** [comment]
You can also use `onPostAuth` maybe 
see ![](https://pbs.twimg.com/media/CL-bp3_W8AAimRi.png:large)

**Comment by hueniverse** [comment]
So... you designed a query string that you can't easily validate?!

I understand there is a certain amount of legacy code we all have to deal with (and that's what `onPreRequest` is for to normalize the request path), but if you want to use joi rules, you kinda need to stick with its capabilities. It costs the client nothing to send a properly designed query string, vs the cost on the server to reformat it on every request (or even just to check if it needs to be formatted).

**Comment by guidsen** [comment]
Yup you're right. I just normalize the query strings via the `onPreRequest` hook. That will do the same.

**Comment by AJamesPhillips** [comment]
@AdriVanHoudt thanks for linking to mtharrison's diagram.  Can we include this in the docs @mtharrison ?  This is really useful high level view of the lifecycle (and power) of hapi that I haven't seen before.

**Comment by AdriVanHoudt** [comment]
@AJamesPhillips I'm all for that, but needs @mtharrison 's approval and attribution 
We also probably want a version we can update if things change (however unlikely)
