### ISSUE TITLE
Optional parammeters should not be validated if they are empty

### ISSUE THREAD

**Issue by danielo515** [hapijs/hapi#3474]
#### What are you trying to achieve or the steps to reproduce?

I am trying to validate an optional query parameter in case it is present. However, the validation is being triggered even if the parameter does not exist. 

```js
    server.route({
        method: 'GET',
        path: '/api/localization/{lang?}',
        config: {
            validate: {
                params: {
                    lang: Joi.string().regex(/^[a-z]{2}-[A-Z]{2}$/)
                }
            },
            handler: ( request, reply ) => {
                 reply('hello');
        }
    });
```

#### What was the result you received?

When the parameter is not present, hapi tries to validate, and the validation fails.

#### What did you expect?

Validation should only be applied if the parameter exists, if it do not exist (because it is optional) then validation does not make sense.

#### Context

* *node version*: 7
* *hapi version*: 16
* *os*: MacOsx

**Comment by Marsup** [comment]
What's the url ? What's the error ? It shouldn't attempt to validate it.

**Comment by danielo515** [comment]
Good catch about the url.
I was testing it with the swagger plugin.
Actually it is a bug on the swagger plugin, if you don't provide the parameter, instead of not sending it they are in including the optional parameter as it is `http://localhost:/api/locale/{lang}`

I'll post the issue on the hapi-swagger repo, where it belongs.

**Comment by farzadso** [comment]
@danielo515 did you ever get to fix this issue on the hapi-swagger plugin?

**Comment by farzadso** [comment]
@danielo515 I actually searched for your issues, but couldn't find them. Can you give me the links please?

I might open a pull request if myself if I find the time.

**Comment by danielo515** [comment]
Hello @farzadso, for this particular problem I didn't open an issue, sorry for being unclear. There are other pending issues and I didn't wanted to add another one to the growing list.
Feel free to do it yourself
