### ISSUE TITLE
403 Forbidden when not validating POST body

### ISSUE THREAD

**Issue by trentgillham** [hapijs/hapi#3476]
I am trying to proxy a POST request through the "app server" to an upstream server.

The app server has authentication for finding an accounts company and pointing it to the proper endpoint in the upstream server: `/{companyId}/datasource`

For example, a user will hit the endpoints `/datasource` from the frontend and based on the auth I am using, it inserts the companyId into the url in the mapURI method.

``` javascript
server.route({
        method: 'POST',
        path: '/datasource',
        config: {
            auth: {
                strategy: 'session',
                scope: 'account'
            },
            validate: {
                payload: {
                    name: Joi.string()
                }
            },
            payload: {
                output: 'data',
                // parse: true
            }
        },
        handler: {
            proxy: {
                mapUri: (request, callback) => {

                    console.log('made  it!');
                    let companyId =  request.auth.credentials.roles.account.company.id.toString();
                    callback(null, 'http://localhost:9001/api/' + companyId + '/datasource');
                },
```

In the above situation, I get the following error: `Route payload must be set to 'parse' when payload validation enabled`.

If I enabled parse, then I get this error: `Cannot proxy if payload is parsed or if output is not stream or data`.

If I do not validate the payload, then I get a `403 Forbidden` and it never even reaches the `console.log('made  it!');`

In all cases, I cannot get the body to pass through to the upstream server.

~~I am trying not to pass the companyId around in the react code I have driving the frontend, which is why I am trying to proxy like this. Is there something I am missing that is causing the `403 Forbidden`?.. or is there a better way to do this?~~

**Comment by kanongil** [comment]
Please direct usage questions to the [discuss](https://github.com/hapijs/discuss) repo.

**Comment by trentgillham** [comment]
I would argue this isn't really a usage question. Every potential solution I have read online, has said to try the options I outlined in the issue. All of them end up with an error. The usage question was just an addition at the end. I will remove it.

**Comment by trentgillham** [comment]
Found the solution, had crumb set for all request. To fix this, I did this: 
``` javascript
config: {
            cors: {
                origin: ['http://localhost:9001']
            },
            plugins: {
                crumb: false
            }

},
```

After doing this, it let a non-validated payload through.
