### ISSUE TITLE
Thoughts on implementing a request.expose (counter-part to server.expose)

### ISSUE THREAD

**Issue by lostthetrail** [hapijs/hapi#3478]
Thoughts on implementing a request.expose (counter-part to server.expose)?

I have found the server.expose sugar to be a nice helper and was curious why it didn't exist for request?

**Comment by Marsup** [comment]
Isn't server.decorate already enough ?

**Comment by lostthetrail** [comment]
Much like directly interacting with the plugins object, it works, but it isn't in parity with an existing feature.

**Comment by hueniverse** [comment]
I don't have an objection. I'll take a PR.

**Comment by argonlaser** [comment]
Hi @hueniverse , I would like to work on this. 

I want some clarity before I start working on this. Please correct me if I misunderstood.
- The requirement is to have a ```request.expose()``` method that will be available only during **onRequest** extension method which will be undecorated later.
- I see that the ```server.expose()``` mutates the object in **plugins[name]** namespace but ```server.decorate('request', 'aaaa', bbbb) ``` mutates the request object at the **request** object itself which can be accessed through ```request.aaaa````. Do we need to decorate the **request** object in a different namespace(like **server**) or shall I go ahead with an API that achieves the current behaviour?

**Comment by hueniverse** [comment]
@argonlaser I would hold off making any PRs at this point until after v17 is done.

**Comment by argonlaser** [comment]
Thanks for the reply. I will come back to this issue once v17 is done.

**Comment by hueniverse** [comment]
I am going to close this for now. I need to get some specific use cases to decide if this is actually needed.
