### ISSUE TITLE
Getting "Invalid cookie value" in response

### ISSUE THREAD

**Issue by vivekimsit** [hapijs/hapi#3522]
Trying a simple use case with some default configuration.

#### What are you trying to achieve or the steps to reproduce?

```js
'use strict';
const Hapi = require('hapi');
const Joi = require('joi');
const server = new Hapi.Server();

server.connection({
  host: 'localhost',
  port: 8000
});

server.state('hello', {
  ttl: 60 * 60 * 1000,
  isHttpOnly: true,
  isSecure: false,
  encoding: 'iron',
  password: 'a5LewP10pXNbWUdYQakUfVlk1jUVuLuUU6E1WEE302k'
})

server.route({
  method: 'GET',
  path: '/',
  config: {
    handler: function(request, reply) {
      let hello = request.state.hello.name;
      reply(`Cookies! ${hello}`)
        .state('hello', {name: 'foo'});
    }
  }
});

server.start(() => console.log(`Started at: ${server.info.uri}`));
```

#### What was the result you received?

`{"statusCode":400,"error":"Bad Request","message":"Invalid cookie value"}`

#### What did you expect?

`Cookies! foo`

#### Context

* *node version*: v7.6.0
* *hapi version*: ^16.4.3
* *os*: macOs 10.12
* *any other relevant information*:

**Comment by mtharrison** [comment]
This isn't enough code to replicate your issue. Making a request to `/` in the above example is just going to error out because `request.state.hello` is not defined. Can you provide a full example to show the issue?

**Comment by mtharrison** [comment]
I changed a line in your example:

```js
let hello = request.state.hello.name;
```
to
```js
const hello = request.state.hello ? request.state.hello.name : 'guest';
```
Everything appears to work as expected. First request giving `Cookies! guest` and then subsequent (i.e. after cookie is set) giving `Cookies! foo`.

We'll need more info if there's really an issue here.

**Comment by vivekimsit** [comment]
@mtharrison I followed your comment but can't make my code to work. I also removed the whole read logic and just tried to set the state but getting same result.

```
server.route({
  method: 'GET',
  path: '/',
  config: {
    handler: function(request, reply) {
      //const hello = request.state.hello ? request.state.hello.name : 'guest';
      reply(`Cookies!`)
        .state('hello', {name: 'foo'});
    }
  }
});
```
I hope you are on the same version of hapi and node

**Comment by mtharrison** [comment]
You obviously already have a bad cookie somehow. How are you making the request? In a browser? Try clearing your cookies and trying again, it's possible there's a bad cookie value already stored somehow. E.g. you can easily simulate this error by making a request with a bad cookie:

```
$ curl -H "Cookie: hello=bad-cookie" localhost:8000

{"statusCode":400,"error":"Bad Request","message":"Invalid cookie value"}
```

Anyway, this sounds like a problem on your end, not an issue with hapi.

**Comment by vivekimsit** [comment]
@mtharrison you were right, but still error message was not helpful at all. Anyways closing this issue, thanks,

**Comment by fdobre** [comment]
Hello, I am also getting this error at the second request.
Cookie format is exactly the same format as the first one but request fails with: `Invalid cookie value`

`"cookie": "token=9d23caf0a6790523755bc573b4ca36dd394a3847ae4fb6e1ebe5cc80b9816e0;"`
@vivekimsit how did you fix the issue? 
I've been fighting with this for 2 days....

**Comment by steffenrostock** [comment]
Hello,

I can replicate this error on node.js (v10.5.0) hapi (v17.5.3)

steps:
- hapi get a request on route /{*filename} 
- responce is a valid image

- manually set a cookie on path /  (cookiename includes ":" => example "test:1")
![cookie_error](https://user-images.githubusercontent.com/43887724/46546248-c9d51700-c8c8-11e8-95f2-9ebe9b7eacc1.png)
- hapi get a request on /{*filename} 
- responce is a bad-request http error (400) with message: "{"statusCode":400,"error":"Bad Request","message":"Invalid cookie value"}"

- now rename the cookie to "test1"
- hapi get a request on /{*filename} 
- responce is a valid image

I dont know, if this is the previous reported error, but i think its not the rigth way to deal with cookies.
Maybe the parsing is corupted by the ":".

best regards

**Comment by george-norris-salesforce** [comment]
`return h.redirect('http://localhost:3000/handle-login').state('tester', { authToken, refreshToken })`
Boom. Same error. What is invalid this cookie? I just ported this from Express and it worked like a charm.

**Comment by nazar-pc** [comment]
This is definitely an issue and `non-issue` label is misleading at best. As soon as we have `"` in cookie value, it fails, which doesn't happen in other frameworks both in Node.js and other languages. We store JSON in some cookies and this is a terrible experience for Hapi to get such frustrating errors.

**Comment by hueniverse** [comment]
If you think there is a problem, open a proper issue with your full details. Adding comments to a random cookie related closed issue is not a productive way to get support. Just because you get the same error doesn’t mean much. You have provided no additional useful information to help figure out your specific problem.
