### ISSUE TITLE
Debug does nothing

### ISSUE THREAD

**Issue by Jared-Sprague** [hapijs/hapi#3524]
#### What are you trying to achieve or the steps to reproduce?
Enable all debug logging

```js
let options = {
    debug: {
        log: ['hapi', 'error', 'debug', 'info', 'warning', 'request', 'server', 'timeout', 'internal', 'implementation', 'tail', 'remove', 'last', 'add'],
        request: ['hapi', 'error', 'debug', 'info', 'warning', 'request', 'server', 'timeout', 'internal', 'implementation', 'tail', 'remove', 'last', 'add']
    }
};
server = new Hapi.Server(options);
```

#### What was the result you received?
No extra logs written

#### What did you expect?
Debug logs written to console

#### Context

* *node version*: 6.10.3
* *hapi version*: 16.4.3
* *os*: Linux - Fedora 25

**Comment by AJamesPhillips** [comment]
What kind of queries where you giving it?  You have no routes there so I'm not sure what output you were expecting.  If you add a route and add [good](https://github.com/hapijs/good) then the log messages should start to flow out to stdout / files / http endpoint.

**Comment by Jared-Sprague** [comment]
Hi!
Here is a link to my routes:
https://github.com/redhataccess/statuspage-controller/blob/master/server/StatuspageController.js#L506

But it doesn't do anything with just sample routes too from the getting started documentation.

The Server options documentation says nothing about using "good" to log debug event:
https://hapijs.com/api#new-serveroptions

**Comment by Marsup** [comment]
Working example with some more tags on the request to log stuff : https://runkit.com/590207717e2df30012fa390b/59450dd9db64da0011f2e3b3

It's not very clear what you're trying to log but I guess you missed this part of the docs https://hapijs.com/api#request-logs about which tags a request is emitting.

**Comment by Jared-Sprague** [comment]
Ah ok I understand now.  Thanks for the example!   Let me step back explain what I was looking for.

What I wanted was a way to toggle on all internal logging by enabling debug.  When I saw that in the documentation I thought that was what it was for.

So I guess this is more of a feature request:  A way to toggle on ALL internal logging, without having to copy and paste a bunch of tags from different parts of the documentation into a huge array. 

Lets make it simple to enable debug logging, like other server technologist have.  Maybe a Boolean that overrides tags and will always log no matter what the tags are.   Or a tag that is on every internal log so that you can turn on debug logging you just have to pass one tag like 'hapi'.

**Comment by Marsup** [comment]
You can follow along on the referenced PR.

**Comment by Jared-Sprague** [comment]
Awesome!  A wildcard would be perfect!  THANKS!
