### ISSUE TITLE
Missing Path Parameter results in 400 in POST vs 404 in GET request

### ISSUE THREAD

**Issue by PadminiKarthika** [hapijs/hapi#3527]
I have a POST and GET REST API for an entity.
 URL is the same for both the HTTP methods.
 Say for instance, URL --> {BASE_URL}/baseEntity/{baseEntityID}/childEntity/{childEntityID}/grandChildEntity
 In JOI Validation, I have marked both baseEntityID and childEntityID as 'required' fields.
 When childEntityID is not provided (empty) in the URL, POST API returns 400 while GET API returns 404.
 Why is the status code different for the same error scenario ?

**Comment by mtharrison** [comment]
Can you show the route config that you have? Also there's no need to create 2 issues, I've closed the other one.

**Comment by PadminiKarthika** [comment]
{
            method: 'POST',
            path: '/credential-management/customer/{customer_id}/users/{user_id}/invitation',
            config: {                
                tags: ['api','sdk','invitations'],
                description:'Create Invitation',
                notes: '**Applicable Roles:** End User Admin, Super Admin\n\nPermission Set Key: ```json\n{invitation: create}```\n\n**Dependent Backend Services:** Settings, SEOS, SMTP Server',

                validate: {
                    params: {
                        customer_id: Joi.number(),
                        user_id: Joi.number().required()
                    },
                    payload: sdk_createInvitationSchema,
                    headers: SCIMConstants.HEADER_DEF,
                    failAction: SDKErrorUtil.handleScimError
                },
                handler: invitationCtrlObj.sdk_validateUser,
                plugins: {                   
                    'hapi-swagger':response_schema.createInvitationResponses
                }
            }
        },
 {          
            method:'GET',
            path:'/credential-management/customer/{customer_id}/users/{user_id}/invitation',
            config:{               
                tags: ['api','invitations','sdk' ],
                description: 'LIST Invitations of a user',
                notes: '> **Applicable Roles** : HID Admin, MA Admin, MA Operator, MA Reviewer\n\n> **Permission Set Key**: ```{invitation:get}```\n\n> **Purpose**: LIST invitations for a user',
                validate:{
                    params: {
                        customer_id: Joi.number().required(),
                        user_id: Joi.number().required()
                    },
                    headers: SCIMConstants.HEADER_DEF_NO_BODY,
                    failAction: SDKErrorUtil.handleScimError
                },
                handler: invitationCtrlObj.listInvitations,
                plugins:{                 
                    'hapi-swagger' : response_schema.listInvitationResponses
                }
            }

        }

**Comment by AJamesPhillips** [comment]
@PadminiKarthika  can you format this better please?

**Comment by kanongil** [comment]
customer_id is not required in the POST route, which means that the handler is called for empty customer_id and probably returns a 404.

**Comment by PadminiKarthika** [comment]
@kanongil,

The difference in status code is encountered when the second path param  is missing in the URL.
when user_id is missing in the URL, POST responds with 400 vs GET with 404
Marking customer_id as required did not fix the issue.

**Comment by AJamesPhillips** [comment]
Despite not having a well formatted test script to run @PadminiKarthika I think the behaviour of: "POST API returns 400 while GET API returns 404." could make perfect sense.  What would you expect instead.  POST isn't going to return 404 as the endpoint exists you've just made a bad request by not providing a valid user_id, and GET isn't going to return 400 [though perhaps this is what you were expecting?], you've made a valid request but there is no user_id that doesn't exist.

**Comment by PadminiKarthika** [comment]
@AJamesPhillips
Thank you, James.
But I'm still confused.

Below is the URL :
http://host/credential-management/customer/{customer_id}/users/{user_id}/invitation

Only the HTTP methods are different.
For HTTP POST, HAPI finds a matching route and responds with 400 when {user_id} is empty,
whereas for GET it could not find a matching route.
The handler is not even invoked and the 404 response is not from the handler.
My concern is for POST request, route is matched and param validation happens, resulting in 400.
I expect the same for GET, but see a 404 as the route doesn't match.

**Comment by AJamesPhillips** [comment]
Please see above.  Also you haven't provided the URL you are actually using. Is it something like:

    /credential-management/customer/123/users//invitation  # <= perhaps would expect 400 but 404 is fine.

or:

    /credential-management/customer/123/users/invitation  # <= would expect 404

**Comment by AJamesPhillips** [comment]
Perhaps this should 400 though.  It is invalid to provide the `/user//invitation` route so perhaps a request to an invalid route should return 400 if there is a route that could be matched i.e.:  `/user/{user_id}/invitation` and has validation that would fail on a parameter having 0 characters i.e. `validate: { params: { user_id: Joi.string().optional() } }`.  Thoughts anyone?

@PadminiKarthika presumably you've now just corrected the error in your code or are handing the 404.

**Comment by PadminiKarthika** [comment]
@AJamesPhillips 

Thank you so much for your response.
You got it right.
My URL  ends with below path:
/credential-management/customer/123/users//invitation
 
I have a matching route for this URL
/credential-management/customer/{customer_id}/users/{user_id}/invitation

user_id is marked as required in Joi validation.
When method is HTTP POST, URL is matched (Joi Validation gives 400 due to missing mandatory path param). When the request is HTTP GET, URL is not matched.
I haven't handled this difference in response code gracefully yet.

**Comment by PadminiKarthika** [comment]
@Marsup ,
What's the solution to this issue ?

**Comment by Marsup** [comment]
I thought it was solved. Provide a repo with a ready-made hapi server and curl commands to test your issue, you guys are going nowhere with this discussion.
