### ISSUE TITLE
"disconnect" event on the "request" object is never emitted

### ISSUE THREAD

**Issue by jfromaniello** [hapijs/hapi#3528]
This is a simple test where I create a HAPI server with a route that replies with "hello world" after 2 seconds. The same code contains a client that does a request to the route and aborts it after 500ms.

```javacript
const request = require('request');
const Hapi = require('hapi');

const server = new Hapi.Server();

server.connection({
  host: 'localhost',
  port: 3001,
});

server.route({
  method: 'GET',
  path:'/slow',
  handler: function (request, reply) {
    request.once('disconnect', () => {
      console.log('disconnected');
    });
    setTimeout(() => reply('hello world'), 2000);
  }
});

server.start();

setTimeout(() => {
  console.log('starting request');
  const req = request.get('http://localhost:3001/slow');
  setTimeout(() => {
    console.log('aborting request');
    req.abort();
  }, 500);
}, 1000);
```

According to the documentation the [request object should emit a `disconnect` event](https://hapijs.com/api#request-object). After debugging for a while I notice that HAPI subscribes to the event too late when the route calls the `reply` function.

I have tried with version `hapi@16.4.3` and node v6.

Thank you very much in advance.

**Comment by AJamesPhillips** [comment]
I tried to recreate this and succeeded.  I also tried using the python `requests` with `requests.get("http://localhost:3001/slow", timeout=1)` and using `net` as per [the hapi tests](https://github.com/hapijs/hapi/blob/master/test/request.js#L309).

#### What was the result you received?

    server: started
    client: starting request
    client: starting request
    server: handling request
    server: handling request
    client: destroying client
    server: replying  # <=
    server: replying  # <=

#### What did you expect?

    server: started
    client: starting request
    client: starting request
    server: handling request
    server: handling request
    client: destroying client
    server: request disconnected  # <=
    server: request disconnected  # <=

#### Context

  // https://github.com/hapijs/hapi/issues/3528

  // const request_module = require('request');
  const Hapi = require('hapi');
  const Net = require('net');

  const server = new Hapi.Server();

  server.connection({
    host: 'localhost',
    port: 3001,
  });

  const onRequest = function (request, reply) {

      request.once('disconnect', () => {

          console.log('server: request disconnected');
      });

      request.once('finish', () => {

          console.log("server: request finished");
      });

      return reply.continue();
  };

  server.ext('onRequest', onRequest);

  server.route({
      method: 'GET',
      path: '/slow',
      handler: function (request, reply) {

          console.log("server: handling request");

          setTimeout(() => {

              console.log("server: replying");
              reply('hello world');
          }, 200);
      }
  });

  server.start((err) => {

      if (err) {
          console.error('server: error', err);
          process.exit(1);
      }

      console.log('server: started');

      const client = Net.connect(3001, 'localhost', () => {

          console.log('client: starting request');
          client.write('GET /slow HTTP/1.1\r\n\r\n');
          console.log('client: starting request');
          client.write('GET /slow HTTP/1.1\r\n\r\n');
      });

      client.on('data', (data) => {

          console.log('client: received data:', data);
      });

      setTimeout(() => {

          console.log('client: destroying client');
          client.destroy();
      }, 100);
  });

**Comment by devinivy** [comment]
This does appear to be a bug to me.  The request's close/abort listeners aren't added until transmission: https://github.com/hapijs/hapi/blob/c212bc8a5d241cc4edfabc5f7b1fd50ac19417ef/lib/transmit.js#L269-L290

The current hapi test doesn't cause the disconnect until transmission has begun: https://github.com/hapijs/hapi/blob/b8efbd9dd6668fd32d983760a953e69c0e6e0027/test/request.js#L334-L338

It seems that the close/abort listeners that trigger the disconnect event should be moved roughly here: https://github.com/hapijs/hapi/blob/b8efbd9dd6668fd32d983760a953e69c0e6e0027/lib/request.js#L171-L178

**Comment by jfromaniello** [comment]
Thanks a lot!
