### ISSUE TITLE
Cookie not getting set for angular 2 application when I use hapi-auth-cookie plugin

### ISSUE THREAD

**Issue by laxmanraut** [hapijs/hapi#3529]
If I make a same request from a browser then the authentcation strategy works. But in case of angular 2 when I make a request from my angular 2 application the authenticaion doesn't work.
Any help would be great

**Comment by AdriVanHoudt** [comment]
1 Open this on the hapi-auth-cookie repo
2 If it breaks when changing angular it is probably an issue with angular
3 Start by comparing what you send and get back from the server
