### ISSUE TITLE
Wrapping bluebird promises with catch causes reply to be called 2 times

### ISSUE THREAD

**Issue by AVVS** [hapijs/hapi#3530]
#### What are you trying to achieve or the steps to reproduce?

This would call reply() twice as `.asCallback` returns that same promise that was there before except for calling nodejs-style callback if it was passed without stopping promise propagation

```js
const Promise = require('bluebird');

// route definition
module.exports = {
  config: {
    handler(req, reply) {
      return Promise
        .reject(new Error('sample error'))
        .asCallback((err) => {
          if (err) {
            return reply(err);
          }

          reply(null, 'all good');
        });
    },
  },
};
```

#### What was the result you received?

Returned promise is then wrapped with .catch(reply) and reply is called twice.

#### What did you expect?

No wrapping of the promises like that. I've found that you wrap it in the docs and it's quite subtly noted. It should either be reply - and then no promise voodoo, or reply is not used at all by checking arity of the function and promises are handled natively by hapi

As a middle-ground there could be server-level setting that disables wrapping of promises

#### Context

* *node version*: 8.1.2
* *hapi version*:  16.4.3

**Comment by AJamesPhillips** [comment]
I apologise for not fully understanding your use case but could you just use:

        .asCallback((err) => {
          return err || 'all good';
        });

?

**Comment by AVVS** [comment]
The method I'm talking about is http://bluebirdjs.com/docs/api/ascallback.html - it basically wraps promise and passes err/result into a node-style callback, but at the same time returns same instance of promise

```js
Promise.prototype.asCallback = Promise.prototype.nodeify = function (nodeback, options) {
    if (typeof nodeback == "function") {
        var adapter = successAdapter;
        if (options !== undefined && Object(options).spread) {
            adapter = spreadAdapter;
        }
        this._then(
            adapter,
            errorAdapter,
            undefined,
            this,
            nodeback
        );
    }
    return this;
};
``

**Comment by jeff-kilbride** [comment]
`.asCallback` is designed to allow you to write API functions that easily accept callbacks or return promises, e.g. (from the bluebird site):

```javascript
// This function accepts an optional callback parameter.
// The `dataFromDataBase()` function returns a promise.
function getDataFor(input, callback) {
    return dataFromDataBase(input).asCallback(callback);
}

// Returns a promise when no callback supplied.
getDataFor('me')
    .then(function(dataForMe) {
        console.log(dataForMe);
    })
    .catch(function(err) {
        console.error(err);
    });

// Uses callback when supplied.
getDataFor('me', function(err, dataForMe) {
    if (err) {
        return console.error(err);
    }
    console.log(dataForMe);
});
```
Notice how `getDataFor` is passing the callback parameter it receives to the `.asCallback` method. In your example, you are creating a new, anonymous function and passing it to `.asCallback`:
```javascript
    .asCallback((err) => {
        if (err) {
            return reply(err);
        }

        reply(null, 'all good');
    });
```
That doesn't work. It's not supposed to work that way. 

Hapi handler functions are invoked by the server and don't receive a traditional, node-style callback, so there's no callback to pass to the `.asCallback` method. There's really no reason to use `.asCallback` in a handler. If you can explain what you are trying to accomplish, maybe we can help.
