### ISSUE TITLE
Remove joi validation when creating request podium events

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#3532]
https://medium.com/walmartlabs/optimizing-hapijs-for-benchmarks-737f371265e9

**Comment by AdriVanHoudt** [comment]
If you can give a slight pointer on what needs to be removed this would very nice for newcomer to PR, what do you think?

**Comment by wswoodruff** [comment]
I'd give it a shot!

**Comment by devinivy** [comment]
While that would be awesome, I expect this to require changes to both podium and hapi, which might make it more complex than a typical `new contributor` issue.  What changes those should be is also somewhat of a design decision.  Does someone see a simpler path?

**Comment by AdriVanHoudt** [comment]
@devinivy oh I thought it was just removing some joi validation calls?

**Comment by sirgallifrey** [comment]
We can still validate the event but not validate the same events over and over.

I was thinking in something like this:

```javascript
const finishEvent = new Podium.Event('finish'); //event was validated here

somePodiumInstance.registerEvent(finishEvent); //no need to validate since it is an Podium.Event instance.

somePodiumInstance.registerEvent('disconnect'); //validate this one as we already do
```
in request.js
```javascript
internals.events = {
    finish: new Podium.Event('finish'),
    peek: new Podium.Event({ name: 'peek', spread: true }),
    disconnect: new Podium.Event('disconnect')
}

/*...*/

internals.Request = function (connection, req, res, options) {

    Podium.call(this, internals.events.finish, internals.events.peek, internals.events.disconnect);

    // Take measurement as soon as possible
```

If everyone like this approach I can start by making a PR to podium to get this moving :P

**Comment by hueniverse** [comment]
Just leave it for me... hence why it is already assigned. I am still thinking how I want to implement this.
