### ISSUE TITLE
Hapi to not unescape query parameter

### ISSUE THREAD

**Issue by noppanit** [hapijs/hapi#3536]
My API is accepting a URI as a query parameter and it looks like Hapi unescaped the query parameter before Joi validation causing validation error because `%20` would be unescaped to a space. I wonder if there's a way to tell Hapi not to unescape query parameter?

This is the Joi validation code bit

``` javascript
validate: {
	query: {
		url: Joi.string().uri().required().description('url')
	}
}
```

And this is how we initialize Hapi

``` js
new Hapi.Server({
    connections: {
      routes: {
        cors: {
          origin: ['*'],
          credentials: true
        }
      }
    }
  })
```

Nothing really fancy here. Here's how I test it

handler.js

``` js
exports.create = function create(request, reply) {
   console.log(request.query);
}
```

I start the sever and hit this url

`http://localhost:8081/content?url=https://www.example.com/search/chicken%20soup`

#### What was the result you received?
And this is the result I get
``` js
{ 
   uri: 'https://www.example.com/search/chicken soup',
}
```

#### What did you expect?
I expect it to be this
``` js
{ 
   uri: 'https://www.example.com/search/chicken%20soup',
}
```

I tried with this code and it passed Joi validation

``` js
var Joi = require('joi');
const schema = {
    url: Joi.string().uri()
};

const {error, value} = Joi.validate({ url: 'https://www.example.com/search/chicken%20soup' }, schema);
console.log(error);
console.log(value);
```

#### Context

* *node version*: 6.6.0
* *hapi version*: 16.1.1
* *os*: Centos 7
* *joi version*: 10.6.0
* *any other relevant information*:

**Comment by AdriVanHoudt** [comment]
hapi uses Url.parse to turn the querystring into an object. Url.parse uses the querystring module from node which decodes out of the box.
If you really want the %20 just use encodeURIComponent or roll your own querystring parser in the onRequest hook like
```js
 // Parse querystring with qs
    const onRequest = (request, reply) => {

        const parsed = Url.parse(request.url.href, false);
        parsed.query = Qs.parse(request.url.query);
        request.setUrl(parsed);

        return reply.continue();
    };

    server.ext('onRequest', onRequest);
```

**Comment by noppanit** [comment]
Thanks for the response @AdriVanHoudt . One quick question. Is there a way to let Joi validate the escaped URI instead of do that for every request?

Because it seems like Joi is validating the unescaped URL.

**Comment by hueniverse** [comment]
Your query value is wrong and the validation is actually telling you that... If you want to pass a URI as a query parameter value, you need to take the actual value `https://www.example.com/search/chicken%20soup` and encode it properly to `https://www.example.com/search/chicken%2520soup`.
