### ISSUE TITLE
Uncaught async errors in pre-handlers

### ISSUE THREAD

**Issue by jeff3yan** [hapijs/hapi#3537]
I've noticed that uncaught errors from async handlers are now handled by the framework, courtesy of #3486.

Will a similar behavior also be applied onto `pre` handlers? Anything that executes in the `pre` phase seems to have the same input arguments and design conventions, so I was curious if this was an issue.

For example:
```
{
	method: 'GET',
	path: '/Items',
	config: {
		pre: [{
			assign: 'test',
			method: async function(request, reply) {
				throw new Error();
			}
		}]
	}
}
```

**Comment by rubennorte** [comment]
It applies to other extension points (`onRequest`, `onPreHandler`, etc.) where this could also be very handy.

**Comment by rubennorte** [comment]
@jeff3yan this will no longer be an issue in Hapi 17, as it'll remove all callback-style APIs and adopt Promises for all async methods.

**Comment by hueniverse** [comment]
I am not going to add any new support for async/await/Promises in hapi v16. You will need to wait for v17 for proper and consistent handling of them.
