### ISSUE TITLE
How to unregister onPreResponse and onRequest handlers?

### ISSUE THREAD

**Issue by Somebi** [hapijs/hapi#3540]
Is there a way to unregister these handlers or overwrite them with empty functions?
Nothing in docs about it if I haven't missed something. Source code doesn't seems to have such method too...

Thank you.

**Comment by AdriVanHoudt** [comment]
Why do you want to do this?

**Comment by devinivy** [comment]
You can't do this with hapi's API, but you could certainly extend hapi to do this using a plugin.

**Comment by Somebi** [comment]
I need it for tests.

**Comment by AJamesPhillips** [comment]
@Somebi, in my application I have a function that returns a server instance (with all the necessary plugins, handlers and routes setup) and in my tests I invoke it before each group / each individual test.  This should solve your problem.

Also it's beneficial as each test is isolated from the others and you don't have any state (from sessions, plugins, cache, etc) interfering with each other.

(For my education and curiosity I was hoping you might share why you need to test your server with and without these handlers?  Are you dynamically adding them during the course of the server's life time?  Or is it that you want to test the server fails without them and succeeds with them added?  Or is it something else?  Thanks.)

**Comment by devinivy** [comment]
@AJamesPhillips's solution is likely what you want then :)
