### ISSUE TITLE
response does not always contain statusCode in onPreResponse

### ISSUE THREAD

**Issue by danielb2** [hapijs/hapi#3547]
#### What are you trying to achieve or the steps to reproduce?

The request.response object has inconsistent behavior, sometimes containing a statusCode and sometimes not. It would be useful if it always contains statusCode.

curl http://localhost:7777/derp
curl http://localhost:7777/here

```js
const Hapi = require('hapi');
const Hoek = require('hoek');
const server = new Hapi.Server();
server.connection({ port: 7777 });

server.start((err) => {

    server.route({ method: 'GET', path: '/here', handler: (request, reply) => {

        reply('here');
    }});

    server.ext('onPreResponse', (request, reply) => {

        console.log(request.response.statusCode);
        reply.continue();
    });
    console.log('Server started at: ' + server.info.uri);
});
```

#### What was the result you received?

undefined for `/derp` and 200 for `/here`

#### What did you expect?

404 for `/derp`

#### Context

* *node version*: 6.9.1
* *hapi version*: 16.4.3
* *os*: osx
* *any other relevant information*: n/a

**Comment by hueniverse** [comment]
It's your responsibility to check if the response is an error. Errors have different structure than response object.s

**Comment by danielb2** [comment]
The documentation claims response can be either a response object or null. I'll update the documentation since a Boom object is a third choice.   A more consistent implementation seems to have been what the documentation said, and if an error was to be returned that should be part of the response object.
