### ISSUE TITLE
Configurable request tags for routes

### ISSUE THREAD

**Issue by ugate** [hapijs/hapi#3549]
#Currently, request **tags** are _hard-coded_ in `request.js`:

```js
this._onClose = () => {
  this._log(['request', 'closed', 'error']);
  this._isPayloadPending = false;
  this._isBailed = true;
};
...
this._onError = (err) => {
  this._log(['request', 'error'], err);
  this._isPayloadPending = false;
};
...
this._log(['received'], about, now);
...
this._log(['request', 'server', 'timeout', 'error']
... etc.
```

While `response` **tags** are configurable via:

```js
config: {
  ...
  tags: [ "myResponseTag" ]
  ...
}
```
Would be nice if both the `request` and `response` use the configured tags rather than just the `response`

**Comment by hueniverse** [comment]
Those tags are for documenting the endpoint, they are not used anywhere. I am not sure what you are talking about...
