### ISSUE TITLE
Route options should include post with parallel semantics to pre.

### ISSUE THREAD

**Issue by ericeslinger** [hapijs/hapi#3553]
apologies if this is a duplicate request - searching for "post-handler" is not terribly productive, given the dual meanings of the term.

#### What are you trying to achieve or the steps to reproduce?

I would like to override JSON.stringify (or inject a handler right before stringify is called) that varies on a per-route basis. I can finagle onPostHandler, but it would be pretty useful if there were an array of `post` elements in the route configuration similar to how the `pre` handlers work.

Specifically, I am trying to modularize my hapi code so I can define some fields with partial visibility on a given model, so getting `/api/foos/1` might have some extra fields if you're authenticated as a system administrator. I *could* put that logic in the handler (or just chain off the then stack), or I could make that logic the handler itself, and make the general-purpose "load a record from the database and then reply with it" method that's currently set as the handler as the final item in the pre array. Logically speaking, though, it feels right to have a post handler stack there for post-processing, and maybe expects a reply() to be called with a string (allowing me to override JSON.stringify as needed).

Right now, I've got a bunch of micro-handlers reused in a lot of routes in the pre-handler array, and do the route-specific thing (for CRUD actions) in the actual handler, after loading, authorizing, and so on.

**Comment by devinivy** [comment]
Are you aware that `onPostHandler` can be set on a per-route basis via route config?  Beyond that, I've used this (https://github.com/devinivy/loveboat-postreqs) in the past to achieve what you're looking for.  But I would suggest working with `ext.onPostHandler` before diving into heavier machinery.

This topic has been broached in the past: https://github.com/hapijs/hapi/issues/2351 https://github.com/hapijs/contrib/issues/13

**Comment by ericeslinger** [comment]
Ah, no - I didn't realize that you could do per-route onPostHandlers based on the documentation - it looked like there was one onPostHandler set per server / plugin. In that case, I think since the functionality is there, it isn't super-urgent, but would be nice to sugar that stuff in somehow (although loveboat looks like it will do the trick nicely as well). In general, one of the things I like a lot about hapi is how declaratively the route blocks are created.

**Comment by hueniverse** [comment]
`pre` is just a way to break the handler. The `handler` is just the last `pre`. If you look at it that way, you don't need `post`. You just arrange your `pre`s and `handler` in a way that does what you need.
