### ISSUE TITLE
plugins have version and name, to also have description

### ISSUE THREAD

**Issue by danielb2** [hapijs/hapi#3555]
Routes have description, tags, etc.

plugins have version and name. It would also be useful to have a plugin description field so that plugins can programmatically be listed with descriptions somewhere much like routes are with hapi-swagger etc.

**Comment by devinivy** [comment]
I'm pretty sure plugins have allowed arbitrary attributes for a while now, if you want to write a tool that utilizes some specific attribute.

**Comment by hueniverse** [comment]
Routes are a public property of an API. Plugins are not. I don't see any reason to add this.
