### ISSUE TITLE
Npm can ignore the Hapi shrinkwrap

### ISSUE THREAD

**Issue by kanongil** [hapijs/hapi#3556]
#### What are you trying to achieve or the steps to reproduce?

Install Hapi:
```sh
> npm install hapi@15 --no-package-lock
```

#### What was the result you received?

It installs, but uses semver declared dependencies from `package.json` instead of specific files from `npm-shrinkwrap.json`.

#### Context

* *hapi version*: any with shrinkwrap file
* *any other relevant information*: npm@5.3.0

The trigger is the `--no-package-lock` option, which apparently caused npm to ignore all shrinkwrap files.

More concerning, some have advocated that people add the `package-lock=false` & `save=false` settings to their npm setup. This will cause a standard `npm install hapi` to ignore the shrinkwrap file.

**Comment by hueniverse** [comment]
Nothing I can do about it.

**Comment by kanongil** [comment]
I see a couple of things that can be done from hapi to alert consumers that the installation is not trusted.

You can setup your shrinkwrap and package.json files in a way that would break the install when the shrinkwrap is ignored.

Alternatively, you can validate the install when starting the server, or in a postinstall hook.

Both of these should also work for yarn, and any other package managers that ignore the shrinkwrap.

**Comment by hueniverse** [comment]
That's more than I want to do. At some point, it is not my responsibility to deal with individual deployment details.
