### ISSUE TITLE
Is it possible to get any of the configured cache instances from a handler?

### ISSUE THREAD

**Issue by atrauzzi** [hapijs/hapi#3557]
I see that I can assign any of the cache instances I configure to a variable up-front from the server.  But is there any way during a handler to get a specific cache instance as well?

Thought there being that this saves me having to pass my reference to the cache driver initialized at bootstrap around.

**Comment by hueniverse** [comment]
You can created a shared instance and then just "recreate" it (and you get back the shared instance).
