### ISSUE TITLE
request.params seems to be missing  in OnRequest event in Hapi request lifecycle

### ISSUE THREAD

**Issue by vedhashrees** [hapijs/hapi#3558]
#### Are you sure this is an issue with hapi or are you just looking for some help?

Issues should only be posted in this repository after you have been able to reproduce
them and confirm that they are either a missing functionality or a bug. If you are in
need of help resolving your issue or are not sure, please do not open an issue here.
Instead, open an issue in the [discussion repository](https://github.com/hapijs/discuss).

#### What are you trying to achieve or the steps to reproduce?

Unable to find request.params values seems to be missing  in OnRequest event in Hapi request lifecycle

```js
// Wrap code in markdown source tags
server.ext('onRequest', function(request, reply) {
            console.time(request.params);
            return reply.continue();
    });

```

#### What was the result you received?
{}
#### What did you expect?
request params that was sent as part of the request.In the documentation , it says request object will be available in OnRequest event
#### Context

* *node version*:v6.11.1
* *hapi version*:15.1.1
* *os*:
* *any other relevant information*:

**Comment by vedhashrees** [comment]
@hueniverse  Can you help me in this

**Comment by AdriVanHoudt** [comment]
Check the lifecycle, since you hook in so early it hasn't done the request.params yet
![](https://pbs.twimg.com/media/CL-bp3_W8AAimRi.png:large)
