### ISSUE TITLE
my phone malware need update my sever 

### ISSUE THREAD

**Issue by gravy528** [hapijs/hapi#3559]
#### Are you sure this is an issue with hapi or are you just looking for some help?

Issues should only be posted in this repository after you have been able to reproduce
them and confirm that they are either a missing functionality or a bug. If you are in
need of help resolving your issue or are not sure, please do not open an issue here.
Instead, open an issue in the [discussion repository](https://github.com/hapijs/discuss).

#### What are you trying to achieve or the steps to reproduce?

Describe your issue here, include as much detail as neccessary to reproduce the issue
or implement a missing functionality.

```js
// Wrap code in markdown source tags
```

#### Context

* *node version*:
* *hapi version*:
* *os*:
* *any other relevant information*:

**Comment by AdriVanHoudt** [comment]
@gravy528 do you have an actual issue or question?

**Comment by gravy528** [comment]
I have a bug in my phone
