### ISSUE TITLE
Issue with catbox-redis as cache

### ISSUE THREAD

**Issue by anttiviljami** [hapijs/hapi#3562]
#### What are you trying to achieve or the steps to reproduce?

I'm trying to use catbox-redis as cache with Hapi's server methods using the instructions given [here](https://hapijs.com/tutorials/caching).

#### What did you expect?

I should be able to register the catbox-redis client in the Hapi.Server constructor like so

```
const server = new Hapi.Server({
  cache: {
    name: 'redisCache',
    engine: require('catbox-redis'),
    host: '127.0.0.1',
    partition: 'cache'
  }
});
```

and then reference 'redisCache' with my server methods to use redis.

```
server.method('sum', add, {
    cache: {
        cache: 'redisCache',
        expiresIn: 30 * 1000,
        generateTimeout: 100
    }
});
```

#### What was the result you received?

When using catbox-redis@3.0.2, the server fails to start, giving this error.

```
/app/user/node_modules/redis-parser/lib/parser.js:326
      throw new TypeError('The options argument contains the property "' + key + '" that is either unkown or of a wrong type')
      ^
TypeError: The options argument contains the property "name" that is either unkown or of a wrong type
    at new JavascriptRedisParser (/app/user/node_modules/redis-parser/lib/parser.js:326:13)
    at Redis.exports.initParser (/app/user/node_modules/ioredis/lib/redis/parser.js:20:22)
    at Socket.<anonymous> (/app/user/node_modules/ioredis/lib/redis/event_handler.js:39:10)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1067:10)
```

Downgrading to catbox-redis@3.0.1 fixes this issue.

#### Context

* Node version: 8.1.4
* Hapi version: 14.2.0
* OS: Linux
* Catbox-redis issue on Github: https://github.com/hapijs/catbox-redis/issues/68

**Comment by hueniverse** [comment]
Seems to be an issue with catbox-redis. The referenced issue has a proposed solution.
