### ISSUE TITLE
Proposal: Clean and chain able Reply API

### ISSUE THREAD

**Issue by VigneshPeriasami** [hapijs/hapi#3565]
Reply api design is too hard to get. Some parts of reply object are chain able while some are not.

**Objective** Make reply completely chain able and readable without having to remember which calls returns response object and which returns reply itself.

Example
```javascript
// Works
reply.redirect("/").state("data", "test").unstate("bar").header("foo", "test");

// fails as state, entity methods of reply may not return a response object
reply.state("data", "test").redirect("/");
```

First one works as `redirect` returns the `Response` object while the second one still operates on
`reply` object.

Going through `reply.js` & `response.js` I find `reply` is mocking (as a wrap) using same methods from `response` but in an inconsistent way.

**Make reply clean** Instead of just making all the methods of `reply` to behave the same way as 
`response` to support chaining. I would like to remove redundancy between reply and response.

Reply API Design Proposal
-------------------------

```javascript
reply() // to return response straight away, by registering process.nextTick ofcourse.

// redirect, entity other delegating methods of reply to be removed from reply
reply("hello").entity().headers("x", "X").state("data", "test").state("meta", "testTwo");
// if called with no args (data or err) by default defer execution and do not register a process.nextTick
reply().unstate("data").redirect("/");

// deferred reply

const deferredReply = reply.hold().state("data", "test").headers("X", "Y")

deferredReply();
```

**Comment by hueniverse** [comment]
This all changes in v17.
