### ISSUE TITLE
response validate options for 'modify' and 'sample' is too strict

### ISSUE THREAD

**Issue by rokoroku** [hapijs/hapi#3567]
#### What are you trying to achieve or the steps to reproduce?

Describe your issue here, include as much detail as neccessary to reproduce the issue
or implement a missing functionality.

```js
// set connection-level configurations
server.connection({
  ...,
  route: {
    ...,
    response: {
      modify: true
    }
  }
})

// set route-level configurations
server.route([{
  ...,
  configs: {
    response: {
      modify: false,
      sample: 0,
      schema: Joi.object({ ... })
    }
  }
}])
```

   
#### What was the result you received?
```
[1] "modify" conflict with forbidden peer "sample"
```

#### What did you expect?
When we set `modify` false, we can use `sample` option.
However, the validator forbids on the `key peers`, not the value.
Could it be relieved by replacing them with `Joi.alternative().when()`? 

#### Context

* *node version*: 8
* *hapi version*: 16.5.2

**Comment by hueniverse** [comment]
I'll take a PR.
