### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by Extarys** [hapijs/hapi#3569]
Hey there!

I just heard about hapi. I was wondering if I should do my project with it.

I read a "benchmark" where it says hapi is slower than express and koa. What those tests doesn't test is the fact that koa for example have no middleware included but hapi have quite a lot. So once you install a couple of middlewares and routes, it slows down.

I was wondering what was your current experience and if hapi was reliable under alot of load.

Also - any good "recent" beginner guide to suggest?

Thanks!! Cheers

**Comment by devinivy** [comment]
Hi @Extarys!  Welcome to hapi :) In short, hapi is slower than plain express for exactly the reason you mentioned.  In my experience hapi has performed well in production, especially when taking into account the features/protections it provides that I use.  Here is an old but relevant blog by hapi's creator talking about hapi's framework benchmarks (and benchmarking frameworks in general): https://hueniverse.com/performance-at-rest-75bb8fff143.

In the future please post discussions like this in https://github.com/hapijs/discuss, which serves as our mailing list.  It's the intended place for questions and discussions.  If you'd like to continue chatting about this, let's bring it over there.  Thanks!
