### ISSUE TITLE
Drop support for request tails

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#3571]

**Comment by devinivy** [comment]
Curious what the impetus is for this change.

**Comment by AdriVanHoudt** [comment]
Since I actually use this, not in favor ^^
What is the reasoning?
Will there be another solution to do something after `reply` like post handlers or?

**Comment by hueniverse** [comment]
The only reason to use this was if you want to log requests after the tails are done. Otherwise, you can just use normal node facilities to do stuff after you call `reply()`.

**Comment by AdriVanHoudt** [comment]
@hueniverse hmm true, I do think we log the tail time with good atm not the response time.
Also will I be able to do `request.log` without a tail?

**Comment by hueniverse** [comment]
As long as you keep a reference to the request, sure. But keep in mind this is not a great pattern. You are holding resources for no real reason past the time the request lifecycle is done.

**Comment by AdriVanHoudt** [comment]
the only reason I do atm is so it logs the log with the request context, I could probably/maybe work around that

**Comment by nlf** [comment]
I just pass the request id along to later methods for context and make sure it’s included in logs. Works for me.

**Comment by mikeatkins** [comment]
Sorry to bring this up after this issue has been closed, but I thought it worth mentioning, we have a number of endpoints that we serve that are fire-and-forget. It is very convenient to be able to see the log of request.log events within our response logs. we can associate the request id with the log events as described above, but it does add some effort every time we want to query the logs in splunk, etc. Obviously this isn't a showstopper, but this feature will definitely be missed by some of us.

**Comment by hueniverse** [comment]
You can easily accomplish this yourself.
