### ISSUE TITLE
Remove support for multiple connection in a single server

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#3572]
hapi is (probably) the only framework that supports adding multiple ports to a single server instance. This was done for two use cases:

- Support an internal process admin channel (serve normal API over port 8000 and allow internal admin access on port 8001)
- Run multiple services in a single process for testing purposes (run a single server that have both your "login" and "billing" APIs, each on a different port)

At this point, external tools would do as good a job at allowing you to manage multiple servers, each with a single port.

**Comment by gr2m** [comment]
I’m working heavily with hapi for several years now, I can’t recall a single situation where we had depended on the multiple connections. On the other side, I do recall it being a bit confusing when starting to work with hapi. If you were to remove this feature, I think the onboarding would be much easer. Big +1 from me 💯

**Comment by kpdecker** [comment]
Would still be possible to spin up another server instance in the same process, no?

**Comment by hueniverse** [comment]
@kpdecker yep. Just need to reuse the config.

**Comment by diegobfernandez** [comment]
O agree 100% with @gr2m, I think the cognitive overload of multiple connections is not worth It.

**Comment by janl** [comment]
I’ve used this before and found it handy for the reasons outlined, but the workaround in https://github.com/hapijs/hapi/issues/3572#issuecomment-329413611 would be more than acceptable.

I too agree that the initial setup simplification alone is worth removing that feature.

**Comment by bleupen** [comment]
We use this feature all the time to redirect http requests on port 80 to use ssl

**Comment by axpro** [comment]
I find it useful. I love that you can load plugins per connection. One use case is private routes for cache invalidation.

**Comment by mattii** [comment]
I like the possibility to load plugins for specific connections, too. Is there any other way to restrict the effect of a plugin to certain routes or path-prefixes (e.g. a plugin should only affect `/admin/*` routes)?

**Comment by hueniverse** [comment]
@mattii You just just losing the ability to select connections because there is always just one. The rest of the plugin options remain.

**Comment by fernandorossato** [comment]
Congratulations, now I'm going to need another plugin or use version 16. I have a WS API that shares data with the REST API and now how will I share data in real time between the two services?
