### ISSUE TITLE
Weird oversight in documentation with server.start() and server.inject()

### ISSUE THREAD

**Issue by kswope** [hapijs/hapi#3577]
Its about testing, server.start and server.inject.

I've looked through books, docs, github issues and blog posts and there seems to be no consensus, or even awareness, of how to handle the combination of server.start and server.inject

The following is everywhere:

in server.js
```
  server.start( () => {} )
```

In handler.test.js
```
const server = require('./server')

test('dummy'), () => {
  server.inject(something)
})
```
 
Almost everybody seems oblivious that this starts a server listening on a socket and then tests go through server.inject().  This cannot be good for performance, parallel tests or even sharing a port with a dev server.

I've seen what seems like a better practice, but ugly, shown below, but I've only seen it in one blog post and two github issues.
```
if ( ! module.parent ) {
  server.start( () => {} )
}
```
There's another option of using process.env.NODE_ENV === 'test' guarding server.start(), still ugly
```
if( process.env.NODE_ENV === 'test' ) {
  server.start()
}
```

Somebody tell me what is the right way and then lets document it somewhere.

**Comment by devinivy** [comment]
If you're going to test a server I highly suggest initializing it with `server.initialize()` but not starting it.  That will enforce plugin dependencies and ensure the server can connect to any caches, etc, but not listen on a port.  Here's some example code to initialize a server but not start it during testing: https://github.com/devinivy/boilerplate-api/blob/pal/server/index.js.

I think it's worth continuing this conversation, but if so we should move the conversation over to [hapijs/discuss](https://github.com/hapijs/discuss).

**Comment by kswope** [comment]
Is there some fancy way to move this over to discuss or should I just repost it?

**Comment by devinivy** [comment]
Sorry, there isn't any fancy way that I know of!  But I'll certainly meet you over there if you repost :)

**Comment by kswope** [comment]
reposted https://github.com/hapijs/discuss/issues/548
