### ISSUE TITLE
Remove server methods string handlers shortcut

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#3580]
Remove the ability to pass a string as a pre or handler that resolves into a registered server method.

**Comment by SimonSchick** [comment]
Why is this getting removed? Too unpopular?

**Comment by hueniverse** [comment]
Adds complexity to core. This is now easy to do with async methods and arrow functions.

**Comment by devinivy** [comment]
I agree there will be little use for it in hapi v17.  If anyone really wants to keep using this though, https://github.com/devinivy/toys/blob/master/API.md#toyshandlerserver-notation
