### ISSUE TITLE
Throwing boom error in handler results in Internal Server error output since 16.2.0

### ISSUE THREAD

**Issue by martinj** [hapijs/hapi#3587]
Before Hapi version `16.2.0` throwing a boom error in the handler would set the corresponding statusCode and message to the boom error that was thrown.

E.g the following example would result in a response with statusCode `404` and message `Not Found` in versions earlier than `16.2.0`

```js
'use strict';

const Hapi = require('hapi');
const Boom = require('boom');

const server = new Hapi.Server();
server.connection({ port: 3000, host: 'localhost' });

server.route({
	path: '/',
	method: 'GET',
	config: {
		handler(req, reply) {
			throw Boom.notFound();
		}
	}
});

server.start((err) => {

    if (err) {
        throw err;
    }
    console.log(`Server running at: ${server.info.uri}`);
});

```
This will now return statusCode `500` `Internal server error` instead.
I think it has something todo with the changes done in `Boom` with wrapping errors.

This has been tested on Hapi version `16.6.2`

**Comment by hueniverse** [comment]
This is not supported behavior in v16. The fact that it worked before was unintended. You cannot throw errors in handlers (this changes in v17). I might take a look at this after v17 is done, but my initial reaction is that throwing anything in a handler is a 500 situation.

**Comment by hueniverse** [comment]
I am not going to change this.
