### ISSUE TITLE
Move request and server events to `events` getter

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#3589]

**Comment by AdriVanHoudt** [comment]
Am I correct that this means that the request and response objects are no longer event emitters? And is this for perf reasons or? (just curious)

**Comment by hueniverse** [comment]
You are correct. They each have a new `events` property. It's primarily for performance reasons but also because it's much cleaner and safer approach. JS inheritance is generally garbage.

**Comment by AdriVanHoudt** [comment]
Awesome, thanks!
