### ISSUE TITLE
Move HTML escaping from joi to hapi

### ISSUE THREAD

**Issue by Marsup** [hapijs/hapi#3590]
Currently, joi is [escaping HTML entities](https://github.com/hapijs/joi/blob/27e340b6aa39e5ff8924f1a012eebf72a836117e/lib/errors.js#L119) for hapi. This is probably not joi's responsibility and many users have been complaining about this. Can we try and find a way to have the same level of protection but built in hapi instead of joi ?

**Comment by AdriVanHoudt** [comment]
Can you give an example of when it does it this? Is this only when it formats an error?

**Comment by Marsup** [comment]
Yes, on error. The risk is that hapi blindly repeats the user's forged input, which could lead to client security issues.

**Comment by AdriVanHoudt** [comment]
I don't see a real use case where this happens but that is probably just me :D

**Comment by hueniverse** [comment]
It's a hard security rule to never echo back any input without escaping it. Just drop this from joi in the next breaking change. I'll deal with it.
