### ISSUE TITLE
Change reply interface from function to object

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#3592]
Instead of `reply(value)` call `h.response(value)`.

**Comment by rubennorte** [comment]
Have you considered alternative name such as `reply.with(value)` or `reply.withBody(value)`? I think this method will be called very frequently and these names are easier to understand.

**Comment by hueniverse** [comment]
I like `wrap()` because it is exactly what it does, take a value and wraps it in internal response object.

**Comment by hueniverse** [comment]
Landed on `response()`
