### ISSUE TITLE
Support compression minimum length

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#3594]
Changes the server `compression` settings from a boolean to an object with:
- `minBytes` - the minimum number of bytes required to enable response compression. Defaults to `1024` bytes.

Compression can still be set to `false` to disable completely but cannot be set to `true` anymore.

**Comment by AdriVanHoudt** [comment]
This would be way less breaking when true would result into minBytes = 1 internally no?

**Comment by hueniverse** [comment]
`true` is the default so I would expect most people not to use that value. But I rather break it and force people to notice than just change the behavior unnoticed.

**Comment by AdriVanHoudt** [comment]
I understand now 👌
