### ISSUE TITLE
Provide a way to flush compression stream on demand

### ISSUE THREAD

**Issue by mtharrison** [hapijs/hapi#3599]
It's useful to be able to tell the payload compression stream to flush its content, for example when wanting the browser to render the HTML document` <head>` and download the associated resources while you're still generating or writing the document body. 

Express's compression middleware achieves this by offering a `res.flush()` method. I think something similar would be useful in hapi for better control of streaming compressed content.

### Streaming compressed payload with hapi
![hapi](https://user-images.githubusercontent.com/916064/31383377-076cacfe-ade5-11e7-9340-5f317d3c2326.gif)

### Streaming compressed payload with express+compression
![express](https://user-images.githubusercontent.com/916064/31383407-22a32b4c-ade5-11e7-81f4-4ff30f5d533c.gif)

**Comment by kanongil** [comment]
Interesting. I was not aware that this is possible using compressed streams.

**Comment by kanongil** [comment]
@mtharrison How would an api user access the `flush()` method in Hapi? The stream is not available until after the response has started transmission.

**Comment by hueniverse** [comment]
The only way I think we can support something like this is with a new response api that lets you define blocks:

```js
const handler = (request, h) => {
   return h.response().block('This\n').block('is\n').block('being\n').block('streamed!');
};
```

And then if compression is involved, we flush it after writing each block.

However, since we do not write to the response stream until the handler is done, the only way this works well is by crafting a response stream and returning that, and doing some of the handler work inside the stream data read events. In which case, this API is useless and we need to expose the flush action as something we hand over the readable stream at pipe time.

Hmm.

**Comment by cvbuelow** [comment]
I have been playing around with this and was able to get it to work by exposing the compressor on the response (last line in this snippet of `transmit.js`).
```js
let compressor = null;
if (encoding &&
    length !== 0 &&
    response._isPayloadSupported()) {

    delete response.headers['content-length'];
    response._header('content-encoding', encoding);

    compressor = (encoding === 'gzip' ? Zlib.createGzip() : Zlib.createDeflate());
}
response.compressor = compressor;  // added this line
```
I'm sure you can think of a less hacky way to do this but it then allows me to do
```js
const handler = (request, reply) => {
  const stream = new Stream.PassThrough();
  reply(null, stream).type('text/html').code(200);
  stream.write('<html><head><script src="https://unpkg.com/react@15.3.1/dist/react.min.js"></script>');

  setTimeout(() => {
    // `compressor` won't be available till next tick
    request.response.compressor.flush()
    setTimeout(() => {
      stream.write('</head><body>hello</body></html>');
      stream.end();
    }, 2000);
  });
}
```

**Comment by ryanwholey** [comment]
I was able to get this working in Hapi 17.8.5 with the added setCompressor functionality in [c49b9c8](https://github.com/hapijs/hapi/commit/c49b9c82a633f8c6ef7379cc0a2dd276598b35cb)

```
async handler(request, h) {

    class ResponseStream extends Stream.PassThrough {
        setCompressor(compressor) {
            this._compressor = compressor;
        }
    }

    const stream = new ResponseStream()
    stream.write('<!DOCTYPE html><html><head></head><body>hello')

    setTimeout(() => {
        stream._compressor && stream._compressor.flush()

        setTimeout(() => {
            stream.write(' world</body></html>')
            stream.end()
        }, 1000);
    })

   return h.response(stream)
}
```
How exciting! Thanks @hueniverse!

**Comment by ryanwholey** [comment]
Got this working in hapi 17.8.5 with the new setCompressor changes added in [c49b9c8](https://github.com/hapijs/hapi/commit/c49b9c82a633f8c6ef7379cc0a2dd276598b35cb)
```js
handler(request, h) {

    class ResponseStream extends Stream.PassThrough {
        setCompressor(compressor) {
            this._compressor = compressor;
        }
    }

    const stream = new ResponseStream()
    stream.write('<!DOCTYPE html><html><head></head><body>hello')

    setTimeout(() => {
        stream._compressor.flush()

        setTimeout(() => {
            stream.write(' world</body></html>')
            stream.end()
        }, 1000)
    })

   return h.response(stream)
   .type('text/html')
}
```
So awesome! Thanks @hueniverse!
