### ISSUE TITLE
Feature: automatic server shutdown

### ISSUE THREAD

**Issue by rubennorte** [hapijs/hapi#3603]
#### What are you trying to achieve or the steps to reproduce?

Gracefully stopping servers when SIGTERM or SIGINT signals are received is a very common need in applications. It'd be great if Hapi had a server option to do it automatically. That way users would only have to add `onPreStop` and `onPostStop` extensions to add additional behaviours.

Example:

```js
const server = new Hapi.Server();
server.connection({
  port: 3000,
  stop: {
    handleSignals: true, // Can also be an array of event names `['SIGINT', 'SIGTERM']`
    timeout: 10000
  }
});

server.ext('onPostStop', (server, next) => {
  // do something and then call next()
});
```

**Comment by AdriVanHoudt** [comment]
You can easily do this with a simple plugin like https://www.npmjs.com/package/hapi-shutdown

**Comment by rubennorte** [comment]
I know, but since most applications do it (or should) I think it's worth it adding it to the framework.

**Comment by kanongil** [comment]
That seems outside the bounds of the framework. Also, there is no "one way to do it", eg. my version here: https://www.npmjs.com/package/exiting

**Comment by AdriVanHoudt** [comment]
@kanongil was looking for that :D but couldn't find it. Maybe add the shutdown keyword to the package.json?

**Comment by hueniverse** [comment]
This is not something we can do at the core level. Every platform has their own rules and shutting down a server is rarely just calling stop.
