### ISSUE TITLE
request.auth.strategy is not documented

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/hapi#3604]
#### Are you sure this is an issue with hapi or are you just looking for some help?

Issues should only be posted in this repository after you have been able to reproduce
them and confirm that they are either a missing functionality or a bug. If you are in
need of help resolving your issue or are not sure, please do not open an issue here.
Instead, open an issue in the [discussion repository](https://github.com/hapijs/discuss).

#### What are you trying to achieve or the steps to reproduce?

Describe your issue here, include as much detail as neccessary to reproduce the issue
or implement a missing functionality.

```js
npx devinivy/paldo docs request.auth
```

#### What was the result you received?

no docs on `request.auth.strategy`

#### What did you expect?

docs on `request.auth.strategy`

#### Context

* *node version*: v8.7.0
* *hapi version*: 16 and master
* *os*: macOS
* *any other relevant information*:

@hueniverse If you want I can do a PR on v16 and you can take this up for master since you are already working on the docs?

**Comment by AdriVanHoudt** [comment]
Do you think it would be useful to add this to the v16 branch?

**Comment by hueniverse** [comment]
You can do a PR against the v16 branch. I think we'll need to fine a v16 lead to handle backporting stuff.

**Comment by AdriVanHoudt** [comment]
Will do.
Do you think that is viable given the changes? A patch for 17 will never land clean on 16 as far as I can predict :P
