### ISSUE TITLE
Feature: request.info.protocol

### ISSUE THREAD

**Issue by rubennorte** [hapijs/hapi#3608]
#### What are you trying to achieve or the steps to reproduce?

Add `request.info.protocol` property, that has the value of `server.info.protocol` by default.

#### Context

There is a plugin ([therealyou](https://github.com/briandela/therealyou)) that sets `request.info.remoteAddress` and `request.info.remotePort` using the information set in `x-forwarded-*` headers.

I'm working in a PR for that plugin to add support for `x-forwarded-host`, `x-forwarded-proto` and `forwarded`  headers (there's [an issue for that](https://github.com/briandela/therealyou/issues/6)) so it's easier to regenerate the full URL of requests behind trusted proxies, but I just realized that the `protocol` is only stored in `server.info` so it can't be modified for specific requests.

I can create the property in the plugin but it'd be great if Hapi already had that property and it was documented, so that plugin can be used transparently when a server is behind a proxy.

**Comment by hueniverse** [comment]
You want to replicate a server property and then allow use code to change it? You are not suppose to check anything in `request.info` and `server.info`.

**Comment by rubennorte** [comment]
The plugin is listed in the official Hapi website and it mutates `request.info` so I assumed you considered it wasn't a bad practice.

I can propose a modification of the plugin or create a new one that exposes this information in a new namespace if mutating the information provided by the framework is a bad practice.

I just hoped this could be done transparently for the user.

**Comment by hueniverse** [comment]
You can't assume I code review every plugin that is listed on the site (which I do not maintain or visit often...). I think mutating the `info` objects by plugins is wrong and in some cases can break internal behavior since the core code uses that info internally as well.

**Comment by rubennorte** [comment]
I assumed you were aware of that because it's in the description of the plugin in the official website:

> A plugin for setting the request.info.remoteAddress and request.info.remotePort based on the X-Forwarded-For and X-Forwarded-Port headers

Of course I wouldn't assume you review their code or documentation.

I'm closing this and looking for an alternative solution. Thanks!
