### ISSUE TITLE
Maintenance page

### ISSUE THREAD

**Issue by Zedonboy** [hapijs/hapi#3610]
Hello, am new to Hapi, how do i create a middleware for checking whether, website is it under maintenance, i tried using plugins, but i cant manipulate the reply and request objects.

I want the middleware to check whether the site is under maintenance, then it reply a maintenance page(view)

Can help me with any workround?

**Comment by hueniverse** [comment]
Open an issue in the [discussion repository](https://github.com/hapijs/discuss).
