### ISSUE TITLE
hapijs.com not reachable

### ISSUE THREAD

**Issue by BorntraegerMarc** [hapijs/hapi#3611]
Click on this [link](http://hapijs.com) -> the website is not responding

**Comment by AdriVanHoudt** [comment]
Open an issue over at https://github.com/hapijs/hapijs.com

**Comment by Marsup** [comment]
Or don't, we know about the situation, just waiting for someone with access to fix it :)

**Comment by AdriVanHoudt** [comment]
@Marsup to late :D https://github.com/hapijs/hapijs.com/issues/516
