### ISSUE TITLE
Plugin route modification

### ISSUE THREAD

**Issue by sorensen** [hapijs/hapi#3617]
We are using a few custom methods to map internal settings to sequelize models + fields, and it would be great to allow a plugin to alter a given route its configured for to inject the `config.validate.query` or `config.validate.payload` options.

Our primary goal here would be to give the plugin an internal mapping of models -> Joi validation objects, and allow it to set the `config.validate` object. Currently we are exporting a config option and using it in multiple places in the route config (plugin options + validate).  The biggest benefit here would be that we could provide the initial plugin registration app/config context, and have it used during route setup to populate the Joi validation.

I understand if this is a design choice, as I can see it getting a little confusing, no worries there, we have an easy workaround, its just not as elegant as a single plugin configuration would be.

**Comment by hueniverse** [comment]
I assume you load this config plugin first, then add routes?

**Comment by sorensen** [comment]
@hueniverse Yes exactly.

**Comment by hueniverse** [comment]
Route rules will address this. Hopefully included in v17.
