### ISSUE TITLE
Review the new v17 ✨ 

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/hapi#3623]
v17 is coming closer and main reason you can help right now is using the latest rc and checking/verifying the docs ✏️  (the rendering of the docs can be messy in some places but a fix for that is coming ^^)
You can install the latest version using `npm i hapi@17.0.0-rc9` 🚀 
v17 requires node 8 (or greater) and has a lot of breaking changes.
You can get a glance of them over at https://github.com/hapijs/hapi/milestone/221
Be aware that probably no current plugin will work anymore (the official hapi plugins almost all have a version now which is compatible though).
You can also start updating your own plugins to be compatible with v17 since no major breaking changes are expected anymore and let maintainers of plugins know v17 is on its way.

If you have any questions post them here or join us in the hapi hour slack. If you find bugs open a new issue. If you have updates/improvements for the docs just open a PR 🙅

👉 Eran spent a lot of time and effort on this release, if you or your company wants to sponsor take a look at https://github.com/hapijs/hapi/issues/3588 👌

**Comment by pi0** [comment]
@AdriVanHoudt We are working on a compatibility plugin for Hapi which adds support for 16.x compatible plugins by recursively wrapping registers and maybe show a warn about migration. Working on more things, will keep this thread updated :)

BTW really good improvements with rc8 👍

**Comment by AdriVanHoudt** [comment]
@pi0 sounds cool 🔥

**Comment by hueniverse** [comment]
Also, every section in API.md should have an example. Feel free to submit PRs adding those in.

**Comment by pi0** [comment]
As an update just released the initial version of [hapi-compat](https://github.com/bakjs/hapi-compat) which for now targets migration to 17.x. It is for sure missing many many things, but at least provides a way to see what's incompatible inside exciting projects and hopefully speeding up upgrade process...

**Comment by hueniverse** [comment]
This is moving to normal ongoing effort.
