### ISSUE TITLE
Intentions for security fixes for pre-v17  hapi

### ISSUE THREAD

**Issue by midknight41** [hapijs/hapi#3661]
The new **v17 looks fantastic** and I've certainly keen to migrate existing APIs to the new version as soon as is practically possible. Thanks for your hard work!

I'm interested if you have a position of how you would respond to a security issue on the v16 line *after* you launch v17? I'm concerned that if we haven't finished upgrading to the latest version of hapi and node.js that we'll be in a bit of a tight spot.

Thanks for your time.

**Comment by Marsup** [comment]
Maintenance will be carried as long as node is LTS.

**Comment by midknight41** [comment]
I'm really pleased to hear that. Thanks for your help!

**Comment by hueniverse** [comment]
Yeah, we will continue to support v16 for critical bugs and security issues for at least a year. Not specific dates yet, but this is largely based on resources. Companies who care about it should consider investing some resources in it - directly by letting employees contribute time, or indirectly by making a financial contribution. We will have more specific info about it when v17 is officially out.
