### ISSUE TITLE
prerequisite returning empty string yields null on the pre object of request

### ISSUE THREAD

**Issue by twhitbeck** [hapijs/hapi#3662]
#### Are you sure this is an issue with hapi or are you just looking for some help?

Definitely with hapi, although I don't know this is a bug or just undocumented behavior. It's unexpected, at the very least.

#### What are you trying to achieve or the steps to reproduce?

When a route prerequisite replies with an empty string, the resulting property assigned to `request.pre` is `null`, not the empty string as I was expecting.

This is because of https://github.com/hapijs/hapi/blob/ec5eacae9e7b2fc16d622d8d8be1bb8623aeef0e/lib/response.js#L82-L87

#### What was the result you received?

`null`

#### What did you expect?

empty string

#### Context

* *node version*: 8.8.0
* *hapi version*: 16.6.2
* *os*: Debian

**Comment by hueniverse** [comment]
This is because pre are processed like handlers and `null` / `''` both mean empty payload. If someone wants to update the v16 docs to clarify this, I'll merge but it is not going to change. It is different in v17.

**Comment by AdriVanHoudt** [comment]
@hueniverse is this a bug as in `it should return ''`? If so would you take a PR?

**Comment by Marsup** [comment]
He assigned himself, unlikely.

**Comment by AdriVanHoudt** [comment]
totally missed that, don't mind me, carry on ^^

**Comment by hueniverse** [comment]
I am not sure yet. This came up in nes as well where empty payload is sent as null. I need to come up with a consistent way to address it. I think I am not going to force '' into null anymore, but still treat both as empty payload.
