### ISSUE TITLE
Invalid route options - unhelpful...

### ISSUE THREAD

**Issue by ianbale** [hapijs/hapi#3664]
Any error in any module of a node project that causes an error to be thrown at startup is caught by Hapi. As a result, potentially useful debugging information is lost and replaced with "Invalid Route Options"

eg.
```
Error: Invalid route options 
at Object.exports.assert (/dm/node_modules/hapi/node_modules/hoek/lib/index.js:736:11)
at module.exports.internals.Server.internals.Plugin.route (/dm/node_modules/hapi/lib/plugin.js:564:10)  at server.register (/dm/server.js:113:20)
```

As an example, I'd accidentally typed let x = = xxxxxxxxxx
That second = causing the fault.

It is extremely hard to debug applications with Hapi because I do not see an error like:
```
/dm/server.js:171 
SyntaxError: Unexpected token =  
```

Is there any options that would cause Hapi to dislay the original errors in such cases rather than just "Invalid Route Option"?

**Comment by hueniverse** [comment]
Can you post a full example?

**Comment by ianbale** [comment]
Morning. Sorry I missed your response. I will sort out an example for you as soon as I can.

**Comment by AlexanderElias** [comment]
@ianbale I received an error like this when I was requiring a module and incorrectly spelled `module.exports`. I would check for errors in your routes our routes module.
