### ISSUE TITLE
Missing documentation on some methods in API.md

### ISSUE THREAD

**Issue by BorntraegerMarc** [hapijs/hapi#3669]
#### Are you sure this is an issue with hapi or are you just looking for some help?
Yes

#### Context
@rafaelsouzaf & myself are working on new typescript definitions for v17. So we need this info to properly define a `index.d.ts` file. We are currently defining it, so it may take some time. Also more missing documentation may be found. We'll post our questions in this issue.

#### What are you trying to achieve or the steps to reproduce?

In the `API.md` there is missing documentation for the argument `options` in this method: https://hapijs.com/api/17.0.1#-requestgenerateresponsesource-options

#### What was the result you received?
Proper documentation of what the `options` argument may contain. So we can write the typescript definition file.

* *node version*: -
* *hapi version*: v17
* *os*: -
* *any other relevant information*:

**Comment by AdriVanHoudt** [comment]
The options are passed to the response constructor https://github.com/hapijs/hapi/blob/master/lib/response.js#L33
So `marshal`, `prepare`, `close` and `variety`although not really an idea what they exactly do

**Comment by BorntraegerMarc** [comment]
Thanks for the answer @AdriVanHoudt that one is pretty easy. What is more difficult is to see of what the objects consist 😄 I can't really figure that one out. Also by looking at the code

**Comment by AdriVanHoudt** [comment]
Maybe the tests will help? https://github.com/hapijs/hapi/blob/master/test/response.js#L1183

**Comment by BorntraegerMarc** [comment]
Very good starting point 😄 Thanks a lot @AdriVanHoudt

**Comment by rafaelsouzaf** [comment]
Great! Thanks @AdriVanHoudt and @BorntraegerMarc

**Comment by Samueljoli** [comment]
@AdriVanHoudt Hey while working on the v17 upgrade for `h2o2` I ran into a method `server.states.passThrough` that I noticed was not included in the documentation as well.

**Comment by AdriVanHoudt** [comment]
@Samueljoli PR's welcome 🎉

**Comment by BorntraegerMarc** [comment]
@AdriVanHoudt PR's are not the problem 😄 The issue is I have literally no idea what the methods/params do or what they are for. So I couldn't document it even 😄

**Comment by AdriVanHoudt** [comment]
@BorntraegerMarc tell me what method specifically and I'll give you some pointers, I'm here to help :D

**Comment by BorntraegerMarc** [comment]
@AdriVanHoudt ah sorry, I see my previous comment was not posted. So basically we have some questionmarks regarding all the comments/TODO's in this PR: https://github.com/rafaelsouzaf/DefinitelyTyped/pull/1

as well the `server.states.passThrough` method from @Samueljoli :)

**Comment by Samueljoli** [comment]
@AdriVanHoudt haha, yeah I'm in the same boat as @BorntraegerMarc, but I'm shamefully being lazy now 😞 , let me take a look into it and I'll reach out if I need some.

**Comment by AdriVanHoudt** [comment]
The tests for passthrough are here, https://github.com/hapijs/hapi/blob/e9ca206424b65f21527dbc888037c4a9fc033db0/test/response.js#L466, so that should give you an idea.
It is also used in h2o2, see https://github.com/hapijs/h2o2/blob/master/lib/index.js.
And afaik it accepts just a boolean https://github.com/hapijs/hapi/blob/e9ca206424b65f21527dbc888037c4a9fc033db0/lib/response.js#L329
To see what it actually does I would look ever here https://github.com/hapijs/hapi/blob/e9ca206424b65f21527dbc888037c4a9fc033db0/lib/response.js#L465

**Comment by rafaelsouzaf** [comment]
With @BorntraegerMarc we keep working in [v17 TS definitions](https://github.com/rafaelsouzaf/DefinitelyTyped/pull/1).

Reading the API, in Lifecycles methods exists some properties with descriptions like "_A response symbol_". For example:

```
h.abandon
Access: read only.
A response symbol. When returned by a lifecycle method...
```

https://github.com/hapijs/hapi/blob/master/API.md?lipi=urn%3Ali%3Apage%3Ad_flagship3_messaging%3Bs8wblGvESZeBqwyUZTtTzA%3D%3D#-habandon

We are not sure about what type _(string, number, any, Object, etc)_ we should use in this cases. We are supposing should be an _Object_.

`readonly abandon: Object;`

Is that right?

**Comment by hueniverse** [comment]
Object would be safe bet. It doesn't matter as you cannot do anything other than return that value.

**Comment by BorntraegerMarc** [comment]
That's true @hueniverse however it would be nice to know as a hapi user, **what** is returned 😄 so in case we can get any more specific info on the type, that would be great :) else we leave it as object...

**Comment by hueniverse** [comment]
It's a symbol. There is nothing more to say about it.

**Comment by rafaelsouzaf** [comment]
@hueniverse we got it. Thanks!
