### ISSUE TITLE
How can I set headers before calling reply.continue in 'onPrehandler'

### ISSUE THREAD

**Issue by arankhem** [hapijs/hapi#3680]
Hey I am new to Hapi.js So can any one explain me on how I can achieve the following thing. I have read documentation and i have did research on this but could not find any solution. Can any onde please help me 
    
        server.route({
                method : 'GET',
                path : '/',
                config: {
                   description: 'api with hello-world end point', //
                   someVariable: 'someValue' // i need some custom variable at route level
                }
                handler : function (request, reply) {
                    reply('Hello Anil');
                }
            })
 Is it possible to access this config object of server.route inside 'onPreHandler'
        
            server.ext('onPreHandler', function (request, reply) {  
                    console.log(request.response) //this is null dont know why  
                    request.config.discription ---> how can i access config object
                   //some logic  
                   return reply.continue()  
                })
Here just before calling reply.continue i need to set some headers. How I can achieve this in hapi.js

**Comment by hueniverse** [comment]
This is the wrong place to ask for help. If you paid any attention to the issue template that you clearly erased, you would know that.
