### ISSUE TITLE
when decoded object is not valid, onPostAuth is not being considered

### ISSUE THREAD

**Issue by Dindaleon** [hapijs/hapi#3683]
I am using a custom `verifyFunc` where I want to return to onPostAuth hook an error when token is expired or scope is different. Right now, if the decoded object has a different scope, I cannot catch it with the onPostAuth so I cannot return a custom 401 error; instead, is sending a 500 error.

A quick fix I am using to force it through the onPostAuth hook, I have to replace the scope in the decoded object with the correct scope and attach an error object. So when I catch it with the onPostHook, I can return a 401 error. The same goes when the token has expired.

Is there a proper way of doing it?

If I am not being cleared enough, please let me know.

**Comment by hueniverse** [comment]
Please follow the instructions in the issues template.
