### ISSUE TITLE
Confusing V17 documentation

### ISSUE THREAD

**Issue by indreek** [hapijs/hapi#3685]
https://hapijs.com/api/17.0.1#server.ext() has a code:

```javascript
const Hapi = require('hapi');
const server = Hapi.server({ port: 80 });

server.ext({
    type: 'onRequest',
    method: function (request, h) {

        // Change all requests to '/test'

        request.setUrl('/test');
        return h.continue;
    }
});

server.route({ method: 'GET', path: '/test', handler: () => 'ok' });
await server.start();

// All requests will get routed to '/test'
```

```await server.start();// doesn't work like that.```

Maybe someone can fix that in manual?

Thanks,
Indrek

**Comment by johnbrett** [comment]
Thanks for raising the issue, we're working on it: https://github.com/hapijs/hapi/pull/3684/

**Comment by hueniverse** [comment]
The code examples are not really meant to be copied as-is. If you don't know that you cannot call `await` outside of an `async` function, you probably are not experienced enough with async/await to use it. The docs assume you know how to use the language to begin with. I don't think that's an unreasonable assumption.

**Comment by indreek** [comment]
"The code examples are not really meant to be copied as-is" I understand You, but I don't agree with You. If examples are wrong what else could be wrong in that manual?

**Comment by hueniverse** [comment]
Examples are not wrong. They are just incomplete. And it's not a manual, it's a reference.

**Comment by midnightcodr** [comment]
I am with @hueniverse on this. Once you get a basic understanding how async/await works, you wouldn't just copy the example code as-is and try to run it. For the minimum you will need to wrap the example in an `async` function, like this
```javascript
(async () => {
  // example codes here
})()
```

**Comment by vhcoder** [comment]
So, I have been trying to get my feet wet with Hapi. I am with @indreek on this, sort of. Been with express for a while. As usual went to the source: https://hapijs.com/tutorials/getting-started?lang=en_US. The idea of a "tutorial" is to teach. With working examples. And how is a newbie, getting started, supposed to know the differences between hapi <16 & 17+ ? The tutorial does not tell you that there are breaking changes which will prevent it from working on hapi 17. When you take the time to add the line "It is compatible with x, why not say, not compatible with the current hapi that get when you do npm install --save hapi (which btw, I copied from the paragraph above on the same tutorial).  I am for one, thinking of sticking with express though I like what hapi can get me.  In my case, and I may have something else wrong even if, after much googling, I took out server.connection I still could not get the tutorial on said page to run without the following change. 
async function start() {

    try {
        await server.start();
    }
    catch (err) {
        console.log(err);
        process.exit(1);
    }

    console.log('Server running at:', server.info.uri);
};

start();

as opposed to:

server.start((err) => {

    if (err) {
        throw err;
    }
    console.log(`Server running at: ${server.info.uri}`);
});

The documentation is extremely lagging. At least the getting started one should just work.

**Comment by mtharrison** [comment]
It will "just work" when it's updated to hapi 17. A person has to do that, in their free time. Lucky for you someone has done it and it will be merged very soon. If you want to preview it, you can here: https://github.com/hapijs/hapijs.com/blob/990ffe80333d31561bfcf609797e86c35dd20198/lib/tutorials/en_US/getting-started.md

**Comment by vhcoder** [comment]
Reviewed that, thanks for sharing. It looks good. In my case, as I had pointed out, I am a newbie to hapi but not to node, so I was able to move ahead. My point was more along the lines of -documentation is lagging and that has consequences for uptake- especially when there are breaking changes. I understand that this is an open source project so people need to be able to do this in their "free time" but the "getting started" tutorials especially need to be good source of current info.

**Comment by vhcoder** [comment]
Just thought that I would share what I had come up with -FWIW:

const Hapi=require('hapi');

// Create a server with a host and port
const server=Hapi.server({
    host:'localhost',
    port:8000
});

// Add the route
server.route({
    method:'GET',
    path:'/',
    handler:function(request,response) {
        
        return'hello world';
    }
});

// Start the server
server.start().then(() => {
    console.log(`Server started at ${server.info.uri}`);
}).catch((err)=>{
    console.log(err);
    process.exit(1);
});
