### ISSUE TITLE
Hapi v17.0.2 cors origin

### ISSUE THREAD

**Issue by indreek** [hapijs/hapi#3688]
```js
const server = Hapi.server({ port: 8080, routes: {cors: {origin: ['http://*.domain.com']} }});
```

#### What was the result you received?
(node:12710) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'match' of undefine

#### Context

* *node version*: 8.9.1
* *hapi version*: 17.0.2
* *os*: Ubuntu 16.02
* *any other relevant information*: https://hapijs.com/api#route.options.cors

Cannot add cors origin with wildcard. * works, *.domain.com doesn't work.

Indrek

**Comment by hueniverse** [comment]
I cannot reproduce this. First, there is no promise generated for creating a new server so that line cannot generate an unhandled rejection. Second, you need to capture and log the full error so I can get the stack trace. Third, you need to provide a full example of what request you are sending to get this...

**Comment by indreek** [comment]
Code is here, but i will send you full error later.
```javascript
const Hapi = require('hapi');
const server = Hapi.server({ port: 8080, routes: {cors: {origin: ['http://*.domain.com']} }});


server.route({ method: 'GET', path: '/test', handler: () => 'Hello test!', options: {tags: ['api']} });
server.route({
  path: '/foobar/{test?}',
  method: 'GET',
  options: {
    tags: ['api'],
    description: 'My route description',
    notes: 'My route notes',
    handler: (request, h) => {
      return 'Hello foobar!';
    }
  }
});

async function startup(){
  await server.start();
}

try{
  startup();
}
catch(err){
  console.log(err);
}
```

**Comment by hueniverse** [comment]
This code runs without an error. What request causes it to error?

**Comment by indreek** [comment]
Simple  "curl http://localhost:8080/", "curl http://localhost:8080/test" and node outputs warning to console.
