### ISSUE TITLE
Server.connection is not a function in 17.1.0

### ISSUE THREAD

**Issue by brihaspati** [hapijs/hapi#3692]
I am just starting to use Hapijs and here I have a pretty simple setup and I am trying to spawn a server

```
const Hapi = require('hapi');

const server = new Hapi.Server();
server.connection({ port: 3000, host: 'localhost' });

server.start((err) => {

    if (err) {
        throw err;
    }
    console.log(`Server running at: ${server.info.uri}`);
});
```
and I am getting error on  running this file
server.connection({
       ^

TypeError: server.connection is not a function

I tried with older version of Hapi(16.6.2) and it works fine. But for 17.1.0 it doesn't. and its giving this error

* *node version*: 9.0.0(also tried with 8.x stable)
* *hapi version*:17.1.0
* *os*:mac
* *any other relevant information*:

**Comment by Alexays** [comment]
```
const server = new Hapi.Server({ port: 3000, host: 'localhost' });
```
See #3658

**Comment by brihaspati** [comment]
@Alexays thanks Alex, just after I raised this bug, I came to know that the official documentation on the site is not an updated one(which I was following:(). But it would be good if the documentation is updated so that a newbie to Hapi like me won't end up facing issues

**Comment by IlyasAbdighni** [comment]
The official document still has been updated yet.

**Comment by Freddixx** [comment]
Guys, please update the docs. I just spent endless time because my hapi server kept crashing. This is extremely hard to debug when there are no up-to-date docs.

**Comment by hueniverse** [comment]
@Freddixx which documents are you talking about? The API doc and the release notes are up to date. If you are complaining about the tutorials, why are you using v17 in the first place?!

**Comment by andrewquartey** [comment]
I run into the same error. Is there a tutorial for v17?
