### ISSUE TITLE
Unexpected (or bug) swallowing of error

### ISSUE THREAD

**Issue by brillout** [hapijs/hapi#3693]
Hapi swallows `throw new Error('Please log me')` in following

```js
process.on('unhandledRejection', err => {throw err});
const Hapi = require('hapi');

const myPlugin = {
    name: 'my-plugin',
    register: (server, options) => {
        server.ext('onPreResponse', (request, h) => {
            console.log('I have been run');
            throw new Error('Please log me');
            return h.response("I don't exist").type('text/html');
        });
    },
};

(async () => {
    const server = Hapi.Server({
        port: 3000,
     // debug: {request: ['error']}
    });

    await server.register([
        {plugin: myPlugin},
    ]);

    await server.start();

    console.log(`Server running at: ${server.info.uri}`);
})();
```

Not sure if this is intended. But I can't see any reason why it would be a good idea to swallow errors on default settings. Couldn't find any rationale in the doc.

#### What was the result you received?

`Please log me` is not printed in the console.

#### What did you expect?

`Please log me` to be logged in the console.

#### Context

* *node version*: v9.1.0
* *hapi version*: 17.1.0
* *os*: Most likely irrelevant
* *any other relevant information*: Nop

Thanks for Hapi, I'm looking forward to extensively use it.

**Comment by hueniverse** [comment]
There is a difference between explicitly throwing an error and errors thrown due to developer mistakes. If you throw an error, that's the same as returning a `Boom.internal()` error. It is a 500 response that is logged normally. By default, hapi doesn't log to console every 500 error, only those that are the result of developer mistakes. A 500 error like the one above is considered part of the normal application flow. If you want them logged, you need to configure it.

**Comment by brillout** [comment]
Ok I tested and indeed the following does print in the console

```js
        server.ext('onPreResponse', (request, h) => {
            console.log('I have been run');
            // Developer typo: it's `h.response` and not `h.repsonse` 
            return h.repsonse("I don't exist").type('text/html');
        });
```

> There is a difference between explicitly throwing an error and errors thrown due to developer mistakes

I've never encountered such error handling behavior before. It's surprising and unexpected.

At this point I don't know what Hapi sees as a "developer mistake" or as a "explicit error".

Actually, I would even say this behavior to be erroneous;
I'm writing library code that looks like that

```js
function myLibraryApi(name) {
  if( name.constructor !== String ) {
    throw new Error('Argument "name" should be a string');
  }
}
```

Now upon `myLibraryApi(['Jon'])` the library will throw `Argument "name" should be a string`. This is clearly a developer mistake. Does Hapi handle this as "developer mistake" or as "explicit error"?

> If you throw an error, that's the same as returning a Boom.internal() error

Why? Why not keep the Boom logic entirely separated from user created errors?

I like Hapi a lot. I deeply appreciate your work.
I can move this ticket to the discussion repo if you want me to.

**Comment by hueniverse** [comment]
Your disagreement boils down to what is being printed to the console by default. All errors are captured and result in a 500 response. I am unlikely to change the console debug logging defaults anytime soon (if at all). If you want to continue discussing this, you are free to bring this up again in discuss but I am not sure what result you want. All you have to do is to configure debug filters to log all errors.
