### ISSUE TITLE
Should server.route options be named options or config?

### ISSUE THREAD

**Issue by aknuds1** [hapijs/hapi#3696]
From reading the v17 API documentation, it looks as if [`server.route`](https://hapijs.com/api#server.route()) options are now named `options`, rather than `config` which used to be the case. Although `config` is apparently still supported, I guess as a synonym of `options`. Can you please clarify if `options` is the new name for this setting? For example [hapi-auth-cookie](https://github.com/hapijs/hapi-auth-cookie) still refers to this setting as `config`.

There also seems to be an inconsistency with the naming of the [route authentication options](https://hapijs.com/api#-routeoptionsauth) key, it should be `auth`, but [parts of the documentation](https://hapijs.com/api#authentication-options) refer to it as `access`.

**Comment by hueniverse** [comment]
The new name is `options` but `config` will remain supported. `access` is a sub key of `auth`.

**Comment by aknuds1** [comment]
@hueniverse Thanks for clearing up options/config.

However, the documentation doesn't correspond to what you're saying about access being a sub key of auth. If you look at the documentation for [route authentication options](https://hapijs.com/api#authentication-options), you'll see that it's declared as being configured via `route.options.access` as opposed to `route.options.auth`, which is how it actually is.

I can't see any reference to `route.options.auth.access` either in the documentation.

**Comment by hueniverse** [comment]
Links are correct, headings are wrong. Fixed now.

**Comment by aknuds1** [comment]
Thanks @hueniverse!
