### ISSUE TITLE
reply not a function and missing .connection method

### ISSUE THREAD

**Issue by pawel-miczka** [hapijs/hapi#3697]
Hi,

I'm using hapi in version ^17.1.1 and I have problem because I get an error in route hander:

```
reply is not a function
```

since my handler function looks kinda short:

```
{
	method: 'GET',
	path: '/',
	handler: (req, reply) => {
		reply('test');
	}
}
```

I found out that ```return 'test';``` is working kinda ok but still what happend? Also there is no .connection method in server instance. Why? What happend also :D ? Are there any changes that happend past few months that I should know about?

I'm also using nodejs in version 9.2 (but I tested on 8.6 and same things happened).

**Comment by hueniverse** [comment]
You are running v16 code.

**Comment by hueniverse** [comment]
You are running v16 application code. See release notes. You moved to a new major version and instead of doing some basic research, just posted this issue. Don't be lazy.
