### ISSUE TITLE
Update turtorials please! 😿

### ISSUE THREAD

**Issue by PinkyRabbit** [hapijs/hapi#3710]
* 9.0.0*:
* Lastest*
* Ubuntu*

Hello! All the time I used Express. But I knowing that Hapi is same cool framework. I want to try it on my project. But... instead of fallowing guide I must read Release Notes and Issues. Thats really not fun. I even cant start basic server normally. I think you needs a special issue ticket, thats why I typed this.

**Comment by hueniverse** [comment]
You think we forgot?!

They will be update when people find the time. Opening issues is just wasting time.
