### ISSUE TITLE
Plugin Registration: calling the callback twice breaks async behaviour

### ISSUE THREAD

**Issue by elmolicious** [hapijs/hapi#3716]
## The Problem

I noticed that if the `next` callback during plugin registration gets called twice the register function of the hapi server will resolve without other plugins finishing their registration before that.

This can cause unexpected behaviour where you rely on a plugin being ready for doing its job but at the same time the plugin is still bootstrapping (maybe opening a connection to a database or whatever async task).

Also plugin registration errors can be "hidden" with no possibility to handle them.

## Expected behaviour

If a plugin calls the callback twice the register function should reject with an error (or even throw one) like if a route handlers reply interface gets called twice.

Or it could be ignored that it got called a second time but it should not just "finish" the plugin registration.

## Minimal Demo Project

The demo projects registers 3 plugins each calling setTimeout before calling the callback.

Plugin 1 calls next twice (after 1 secs)
Plugin 2 calls next once (after 2 secs)
Plugin 3 calls next once with an error (after 2 secs)

[Demo-Project](https://github.com/elmolicious/hapi-bug-example)

Output: 

```
Registering plugins ...
Plugin 1: Doing async task for 1000ms.
Plugin 1: Double Calling Next
Plugin 2: Doing async task for 2000ms
Plugin 3: Doing async task for 2000ms.
Plugin 2: Calling Next
Plugin 3: Calling next with error.
Registered plugins!
Starting server ...
Startet server!
```

If you remove the second next call in plugin 1:

```
Registering plugins ...
Plugin 1: Doing async task for 1000ms.
Plugin 1: Double Calling Next
Plugin 2: Doing async task for 2000ms
Plugin 2: Calling Next
Plugin 3: Doing async task for 2000ms.
Plugin 3: Calling next with error.
Plugin registration failed Error: Plugin 3 Error.
  at Timeout.setTimeout [as _onTimeout] (/src/plugin3.js:5:10)
  at ontimeout (timers.js:475:11)
  at tryOnTimeout (timers.js:310:5)
  at Timer.listOnTimeout (timers.js:270:5)
```

## Context
- node version: v8.9.0
- hapi version: v16.6.2
- os: macOS 10.13.1 (High Sierra)

**Comment by hueniverse** [comment]
This is not a common mistake that should be protected against. Most callback APIs will do something bad if you call a callback twice. We protect against calling `reply()` more than once but that's as far as common mistakes go.
