### ISSUE TITLE
Missing documentation: life-cycle hooks - the reply.continue() issue

### ISSUE THREAD

**Issue by dharmax** [hapijs/hapi#3721]
1. The reply object is replaced now (version 17+) with the "h". 
2. on the life-cycle hook there used to be the need to call reply.continue()
3. well, it is not so now. Following the flow with the debugger i found you have to **return** the **symbol** h.continue 
4. Kindly update the documentation accordingly.

**Comment by Marsup** [comment]
It **is** documented, please be more specific where you would expect to find it, or better yet, submit a PR.
