### ISSUE TITLE
Hapi v17.2.0 bugs Invalid load monitoring options - [1] "concurrent" is not allowed

### ISSUE THREAD

**Issue by hbinduni** [hapijs/hapi#3724]
Hi, i have hapi with this config

```js
const options = {
  router: {
    stripTrailingSlash: true
  },
  host: 'localhost',
  port: 3000
};

const server = new Hapi.Server(options);
```

it working fine with previous version, but if i update to hapi 17.2.0, it then give me an error below:

```js
ValidationError: Invalid load monitoring options {
  "sampleInterval": 100,
  "concurrent" [1]: 0
}

[1] "concurrent" is not allowed
```

can you help with this issue?

#### My OS

* *node version*: v9.3.0
* *hapi version*: v17.2.0
* *os*: mac os High Sierra v10.13.2

**Comment by devinivy** [comment]
I suggest performing a fresh install– my guess is that you have an outdated version of the `heavy` module.

**Comment by hbinduni** [comment]
i have remove all node_modules, and do fresh install. but the result same.
this is my dependency package that working:

```
"hapi": "17.1.0",
"inert": "5.0.1",
"marked": "0.3.9",
"moment": "^2.20.1",
"mustache": "2.3.0",
"parse": "1.11.0",
"vision": "5.3.0"
```

but once i update to hapi v17.2.0, it just error as describe above

**Comment by devinivy** [comment]
Is it possible that you have an old package-lock.json file that is specifying the version of heavy?

**Comment by hbinduni** [comment]
Thank you. After remove yarn.lock, i do fresh install and make it work. below the content of my yarn.lock after fresh install:

```
hapi@17.2.0:
  version "17.2.0"
  resolved "https://registry.yarnpkg.com/hapi/-/hapi-17.2.0.tgz#e5d74b65235b443225e05d7b7510cdb80d4887e7"
  dependencies:
    accept "3.x.x"
    ammo "3.x.x"
    boom "7.x.x"
    bounce "1.x.x"
    call "5.x.x"
    catbox "10.x.x"
    catbox-memory "3.x.x"
    heavy "6.x.x"
    hoek "5.x.x"
    joi "13.x.x"
    mimos "4.x.x"
    podium "3.x.x"
    shot "4.x.x"
    statehood "6.x.x"
    subtext "6.x.x"
    teamwork "3.x.x"
    topo "3.x.x"

heavy@6.x.x:
  version "6.1.0"
  resolved "https://registry.yarnpkg.com/heavy/-/heavy-6.1.0.tgz#1bbfa43dc61dd4b543ede3ff87db8306b7967274"
  dependencies:
    boom "7.x.x"
    hoek "5.x.x"
    joi "13.x.x"
```
