### ISSUE TITLE
Upload request is getting failed in 2 minutes

### ISSUE THREAD

**Issue by gauravmakkar** [hapijs/hapi#3729]
What should be the route configuration to set the timeout for upload request?

server.route({
        method: 'POST',
        path: '/accounts/upload',
        config: {
            auth: {
                strategy: 'session'
            },
            cors: {
                origin: ['http://localhost:8000']
            },
            plugins: {
                crumb: false
            },
            payload: {
                allow: 'multipart/form-data', // important,
                parse: true,
                maxBytes: 3000000000000,
                output:'data'
            }
        },

        handler: function (request, reply) {
        ...

**Comment by simon-p-r** [comment]
I would ask this question on the discuss forum [here](https://github.com/hapijs/discuss), I would also include all code including your handler.
