### ISSUE TITLE
Server.route does not work if I register an array of routes

### ISSUE THREAD

**Issue by danielo515** [hapijs/hapi#3735]
#### What are you trying to achieve or the steps to reproduce?

 I want to register several routes, as I used to do on hapi 16. In hapi 17 only single object route registration seems to work

 This code does not work
```js
const register = async (server, options) => {
        const routes = [
        {
            method: 'GET',
            path: '/create',
            handler: function (request, h) {

                return renderCreateBenchmark();
            }
        }, {
            method: 'POST',
            path: '/create',
            handler: function (request, h) {

                console.log(request.payload);
                return { status: 200, id: 99 }
            }
        }];
    server.route(routes);
};
```

This does

```js
const register = async (server, options) => {

    server.route({
        method: 'GET',
        path: '/create',
        handler: function (request, h) {

            return renderCreateBenchmark();
        }
    });
};
```

#### Context

* *node version*: 8
* "hapi": "^17.2.0",
* *os*: Windows
* *any other relevant information*:

**Comment by thebinarypenguin** [comment]
Looks like a JS syntax error. You forgot the opening curly `{` for the second route object

**Comment by danielo515** [comment]
No, it is a typo on the example. If that was my actual code it won't start, but instead I am getting a 404.
I'll fix the code example

**Comment by danielo515** [comment]
Dam, it works now. Passing the array stored on a variable worked.
Mm, I'll close until  i can reproduce again
