### ISSUE TITLE
outdated documentations ?

### ISSUE THREAD

**Issue by a-eid** [hapijs/hapi#3737]
* *node version*: 9.4
* *hapi version*: 17.2.0
* *os*: macos
* *any other relevant information*:

I'm just started using hapijs and the docs is not up to date I belive. 
issues I had: 

-  connection is not a function
```
const server = new Hapi.Server();
server.connection({ port: 3000, host: 'localhost' });
// needs to be 
const server = new Hapi.Server({ port: 3000, host: 'localhost' });
```

- `server.start(cb)` the callback is not getting called.
- `reply` is not a function. 
....

**Comment by nolan-m** [comment]
Had this same problem and found out the site has not been updated and they are looking for a new maintainer.   The [site code](https://github.com/hapijs/hapijs.com)   is in a different repo.

See the PR [here](https://github.com/hapijs/hapijs.com/pull/537/files) if you need help finishing the tutorial.


Also see: 
[API Docs](https://github.com/hapijs/hapi/blob/master/API.md)
[17.0.0 Release Notes](https://github.com/hapijs/hapi/issues/3658)
