### ISSUE TITLE
Route level Authentication issue with Scope

### ISSUE THREAD

**Issue by sansugu** [hapijs/hapi#3748]
I am using Hapi v17.0.2 and hapi-auth-bearer-token v6.0.1. I am able to use bearer token to authenticate the API's. The issue is with enabling scope based authentication at Routes.

My server.js code snippet

const server = new Hapi.Server({ port: 4001, host: 'localhost' });

  server.register(plugins).then(async () =>  {
    server.auth.strategy('simple', 'bearer-access-token', {
    validate: async (request, token, h) => {

      const decoded = jwt.verify(token, 'secret');

      const auth = await Auth.findOne({ _id: decoded._id }).populate('user');
      if (!auth) {
        return h.response({ message: 'Invalid Token' }).code(401);
      } else if (auth.authKeys.find(key => key === decoded.key)) {
        //  else if("H1y_gqfuf" === decoded.key) {
        console.log('Login: Success');

        return { isValid: true, credentials: auth.user };
      } else {
        return h.response({ message: 'Invalid Key' }).code(401);
      }
    },
  });

    server.auth.default('simple');

  server.views({
    engines: {
      jsx: HapiReactViews,
    },
    compileOptions: {}, // optional
    relativeTo: __dirname,
    path: 'views',
  });

    server.start();
});

server.route(routes);

routes.js code snippet

const routes = [
  {
    method: 'POST',
    path: '/Login/UserLogin',
    handler: UserLogin,
    config: {
      auth: false,
      tags: ['api'],
      validate: {
        payload: {
          email: Joi.string()
            .email()
            .required(),
          password: Joi.string().required(),
        },
      },
    },
  },
  {
    method: 'GET',
    path: '/Login/VerifyPhone',
    handler: VerifyPhone,
  },
  {
    method: 'GET',
    path: '/Login/VerifyEmail',
    handler: VerifyEmail,
    config: {
      auth: {
            access: {
              scope: 'admin',
              entity: 'any'
        }},
      tags: ['api'],
      validate: {
        query: {
          email: Joi.string()
            .email()
            .required(),
          key: Joi.string().required(),
        },
      },
    },
  },
];

export default routes;

When starting the server i get the below error

   throw new Assert.AssertionError({
    ^

AssertionError [ERR_ASSERTION]: Route missing authentication strategy and no default defined: /Login/VerifyEmail
    at module.exports.internals.Auth._setupRoute (/Happlo/Projects/Marketplace/node_modules/hapi/lib/auth.js:135:18)
    at new module.exports.internals.Route (/Happlo/Projects/Marketplace/node_modules/hapi/lib/route.js:172:71)
    at internals.Server._addRoute (/Happlo/Projects/Marketplace/node_modules/hapi/lib/server.js:455:23)
    at internals.Server.route (/Happlo/Projects/Marketplace/node_modules/hapi/lib/server.js:448:22)
    at Object.<anonymous> (/Happlo/Projects/Marketplace/src/index.js:61:8)

If i add strategy: 'simple' to the routes.js under auth object, then i get an error "AssertionError [ERR_ASSERTION]: Unknown authentication strategy simple in /Login/VerifyEmail"

The Auth process works without route level scoping.

**Comment by Marsup** [comment]
Please read the issue template carefully before posting, this is not the place.
