### ISSUE TITLE
Error in route prefix documentation

### ISSUE THREAD

**Issue by JbIPS** [hapijs/hapi#3759]
Hello,

I try to prefix my routes with the API version. I read [in the `server.register` doc](https://hapijs.com/api#server.register()) that I should give an `options` param with a `routes` key with the prefix as a property : 
```js
options: {
  routes : {
    prefix: String
  }
}
```
But when I look at [`server.register` code](https://github.com/hapijs/hapi/blob/master/lib/server.js#L389), I see it's looking for `item.routes.prefix` so my options should be like : 
```js
options: {
  opt: {}
  routes: {
    prefix: String
  }
}
```

#### How to reproduce

```js
module.exports = {
  name: 'api',
  register(server) {
    server.route({
      method: 'GET',
      path: '/hello',
      handler() {
        return 'World';
      },
    });
  },
};
```

```js
await server.register([
    {
      plugin: routes,
      options: {
        routes: {
          prefix: '/api/v1',
        },
      },
    },
```

#### What was the result you received?
Calling `GET /hello` gives a 200 but `GET /api/v1/hello` gives a 404

#### What did you expect?
The route should be prefixed by `/api/v1`

#### Context

* *node version*: 9.4.0
* *hapi version*: 17.2.2
* *os*: Windows
* *any other relevant information*:

**Comment by Marsup** [comment]
You've confused plugin options which are passed to the plugin and registration options which are the 2nd parameter of register. See https://runkit.com/embed/fae9wle3vuwi.

**Comment by JbIPS** [comment]
My bad, thank you for the disambiguation!
