### ISSUE TITLE
server.control()

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#3767]
Allow linking servers to start/stop together.

**Comment by kanongil** [comment]
This implementation is a bit naive, and can put the set of servers into an undefined state, if one eg. of the controlled servers throws an error during start. Or if the primary server throws an early error during stop, the controlled servers won't be stopped.

See my implementation here for a safer start implementation: https://github.com/kanongil/exiting/blob/master/lib/index.js#L238
