### ISSUE TITLE
Documentation missing onPostStart reference

### ISSUE THREAD

**Issue by TheJimFactor** [hapijs/hapi#3774]
Following the tutorial for v17 @ https://hapijs.com/tutorials in the `Plugins` section I noticed that the `logEvents` only included `response` though the following explanation shows a `onPostStart` event.

### In the tutorial
```js
const init = async () => {
  await server.register({
    plugin: require('hapi-pino'),
    options: {
      prettyPrint: true,
      logEvents: ['response']
    }
  })
  await server.start()
  console.log(`Server running at: ${server.info.uri}`)
}
```

### Expected
Having a `onPostStart` event included to get the example output listed in the tutorial.
```js
const init = async () => {
  await server.register({
    plugin: require('hapi-pino'),
    options: {
      prettyPrint: true,
      logEvents: ['response', 'onPostStart']
    }
  })
  await server.start()
  console.log(`Server running at: ${server.info.uri}`)
}
```
#### What was the result you received?
Just the default server started `Server running at: http://localhost:3000`

#### What did you expect?
Output more like the example
```
[2017-12-03T17:15:45.114Z] INFO (10412 on box): server started
    created: 1512321345014
    started: 1512321345092
    host: "localhost"
    port: 3000
    protocol: "http"
    id: "box:10412:jar12y2e"
    uri: "http://localhost:3000"
    address: "127.0.0.1"
```
#### Context

* *node version*: 8.11.1
* *hapi version*: 17.3.1
* *os*: ubuntu 16.04 lts

**Comment by hueniverse** [comment]
Thanks. Please open this issue here: https://github.com/hapijs/hapijs.com
