### ISSUE TITLE
Content type on empty string payloads

### ISSUE THREAD

**Issue by dominykas** [hapijs/hapi#3782]
Background: https://github.com/hapijs/nes/pull/234#discussion_r183474664 and https://github.com/hapijs/nes/issues/106 (tl;dr: Nes treats `null` and `''` payloads differently, even though in HTTP both are in effect the same; this can be disambiguated in HTTP by setting a content-type).

When a non-empty string payload is set as a response, hapi will automatically set `text/html`.

The same should apply to empty string payloads.

**Comment by hueniverse** [comment]
I marked this as breaking change just to draw attention and help anyone who might be affected. There should be no issue with this except the additional response header.
