### ISSUE TITLE
an api suggest

### ISSUE THREAD

**Issue by atmjs** [hapijs/hapi#3783]
```const after = function (server) {

    // Additional plugin registration logic
};

exports.plugin = {
    name: 'example',
    register: function (server, options) {

        server.dependency('yar', after);
    }
};
```
for most time the server object can get from the outside of the callback function,
so the api why not designed as the under

```
const after = function (plugin = server.plugins['yar']) {

    // Additional plugin registration logic
};

exports.plugin = {
    name: 'example',
    register: function (server, options) {

        server.dependency('yar', after);
    }
};
```

**Comment by atmjs** [comment]
and conside that: can the server.dependency be set  promisable

**Comment by hueniverse** [comment]
I have no idea what you want.

**Comment by devinivy** [comment]
@atmjs if you'd like to expand on your idea, feel free to post in [hapijs/discuss](https://github.com/hapijs/discuss).  It can be useful to refine ideas there with input from other community members before making a formal request here.
