### ISSUE TITLE
Lowercasing Hapi namespace throughout all example and documentation

### ISSUE THREAD

**Issue by krunkosaurus** [hapijs/hapi#3787]
#### Is this a security related issue?

No

#### What are you trying to achieve or the steps to reproduce?

In all Hapi examples in Hapijs.com and this Github the Hapi JavaScript object is initial-capped. This is potentially confusing as the Hapi object is neither a "JavaScript class" or instantiatable.  

As an example https://hapijs.com/tutorials/views even initial-caps the node Path package: 

```js
'use strict';

const Path = require('path');
const Hapi = require('hapi');
const Hoek = require('hoek');

```

You can see in Node.js documentation that non-"Javascript Classes" are lowercased: https://nodejs.org/api/path.html

```js
const path = require('path');
```

#### What was the result you received?

I'm not trying to be pedantic. This really is a consistency issue.  

#### What did you expect?

To lowercase the Hapi namespace to remain consistent with common JavaScript paradigms. 

#### Context

* *node version*: All
* *hapi version*: All
* *os*: All

**Comment by arb** [comment]
Per the hapi style guide:

https://github.com/hapijs/contrib/blob/master/Style.md#require

**Comment by devinivy** [comment]
Ohp, @arb beat me to it!  There are some words on the reasoning behind this rule [here](https://gist.github.com/hueniverse/a06f6315ea736ed1b46d#required-modules).  If you find any non-PascalCased `require()`s in examples, feel free to log an issue or simply make a PR for the fix.
