### ISSUE TITLE
Global cors and security options not respected in 404

### ISSUE THREAD

**Issue by erfanio** [hapijs/hapi#3792]
#### What are you trying to achieve or the steps to reproduce?
From API docs:
> If set to `'ignore'`, any incoming Origin header is ignored (present or not) and the 'Access-Control-Allow-Origin' header is set to `'*'`

I have this in my hapi server configs:
```js
...
    routes: {
      cors: { origin: 'ignore' },
...
```

This works fine most of the time
![image](https://user-images.githubusercontent.com/9994172/40184453-ab74d2a4-5a33-11e8-82dd-11d405938d8a.png)

But when a route doesn't exist, the 404 response doesn't include the cors headers.
![image](https://user-images.githubusercontent.com/9994172/40184553-e4a3678e-5a33-11e8-9700-3a1a558216f3.png)

#### What did you expect?
I expect to have `access-control-allow-origin: *` on the 404

#### Context
* *node version*: 10
* *hapi version*: 17.4
* *os*: Linux

**Comment by vladikoff** [comment]
I was about to file this bug, but saw yours.

This can be reproduced with this: 

```
git clone https://github.com/vladikoff/issue-hapi-17-404-headers.git
cd issue-hapi-17-404-headers
node index.js
```

Navigate to http://localhost:3000

### Existing route:

![image](https://user-images.githubusercontent.com/128755/41607041-1c4dd0a0-73b3-11e8-8b45-ba88c61b057f.png)


### 404 route: http://localhost:3000/404something

Response headers are missing security route options: 

![image](https://user-images.githubusercontent.com/128755/41607106-37b50fc0-73b3-11e8-9317-c0fbfa17e2c6.png)

This seems like a regression in Hapi 17. In hapi 16 this worked fine, we have testa covering this behaviour.

**Comment by vladikoff** [comment]
Sample code:

```js
'use strict';

const Hapi = require('hapi');

const server = Hapi.server({
  port: 3000,
  host: 'localhost',
  routes: {
    cors: true,
    payload: {
      maxBytes: 16384
    },
    security: {
      hsts: {
        maxAge: 15552000,
        includeSubdomains: true
      },
      xframe: true,
      xss: true,
      noOpen: false,
      noSniff: true
    },
  }
});

server.route({
  method: 'GET',
  path: '/',
  handler: (request, h) => {

    return 'Hello, world!';
  }
});

server.route({
  method: 'GET',
  path: '/hello',
  handler: (request, h) => {

    return 'Hello, ' + encodeURIComponent(request.params.name) + '!';
  }
});

const init = async () => {

  await server.start();
  console.log(`Server running at: ${server.info.uri}`);
};

process.on('unhandledRejection', (err) => {

  console.log(err);
  process.exit(1);
});

init();
```

**Comment by vladikoff** [comment]
Workaround mentioned here: https://github.com/hapijs/hapi/issues/3658#issuecomment-398804025

**Comment by bmgdev** [comment]
@vladikoff have you seen any official fix for adding a global cors: true?  I'm bewildered how its been this long without a fix.  This seems like a giant use case/issue for most people.

**Comment by bmgdev** [comment]
![2018-08-01_00-32-18](https://user-images.githubusercontent.com/1637668/43507576-60b16f46-9522-11e8-895f-fe762ebb1d76.png)

complete oversight, but i was able to add this to my manifest.  had no idea, so simple.

**Comment by kanongil** [comment]
Hmm, tricky. The docs, could both mean every _defined_ route, or _every_ route (including built-in). I would probably expect it to just apply to all responses (contrary to the current implementation).

Adding CORS headers to unrouted `404` responses will add a bit of extra processing, and some extra bytes to the responses. There is also a remote possibility that it can trigger a bug in a browser app, due to receiving the actual `404` response instead of a CORS fail.

For reference:
>`server.options.routes`
>
>Default value: none.
>
>A route options object used as the default configuration for every route.

**Comment by hueniverse** [comment]
> due to receiving the actual 404 response instead of a CORS fail

It will not change the 404 response, just add a few headers as configured for the other routes.
