### ISSUE TITLE
Hapi 17 doesn't fail properly when failing a payload Joi validation schema

### ISSUE THREAD

**Issue by GuyHadas** [hapijs/hapi#3797]
Given an example route:

```
method: 'PUT',
path: '/articles
config: {
    validate: {
        payload: Joi.object().keys({
            articleId: Joi.string().guid(),
            body: Joi.string()
        })
        .allow(null)
    }
}
```

If I were to pass in a payload that fails the above schema, ex:
```
{
    articleId: 'not a valid guid',
    body: 'example content...'
}
```
even though `failAction='error'`, this does not automatically error out and 400, instead it continues into the handler with the following payload:
```
{
    error: { ValidationError: child "details" fails because ["details" must be a valid GUID] ... }
    value: {
        articleId: 'not a valid guid',
        body: 'example content...'
    }
}
```

Note that if I used a POJO instead of Joi.object().keys(), then it would work as expected and it would 400 after failing the schema validation.

#### What did you expect?
I expected this to 400 for failing the validation schema, given that my `failAction` is set appropriately. Mainly, I find it odd that passing in a POJO vs. passing in `Joi.object().keys()` results in a different shape for the payload object, whether there was an error or not.

Side note, in case this is actually expected  behavior: I could not find any documentation anywhere in the migrating to Hapi 17 docs, or in the docs themselves about the potential for a payload object to be shaped as `{ error, value }` if a Joi validation schema was passed not as a POJO.

#### Context

* *node version*: 10
* *hapi version*: 17.0.2
* *os*: linux
* *any other relevant information*:

Forgive me if I'm reading this code incorrectly, but this seems incorrect https://github.com/hapijs/hapi/blob/master/lib/validation.js#L83-L94

It seems as if it's expecting `Joi.validate` to throw an error when it fails the schema and enter the `catch`, but it would just return an object with the `error` property set, which is what's then getting set as the `request[source]` in the request handler.

**Comment by GuyHadas** [comment]
Turns out the issue was because of an old version of `Joi`

**Comment by GuyHadas** [comment]
@vladikoff They removed the specifics on why validation failed for security reasons, check out https://github.com/hapijs/hapi/issues/3706

**Comment by vladikoff** [comment]
@GuyHadas Thank you! Gonna work on adding this back now 🏗
