### ISSUE TITLE
'request' event handler not being triggered for successful requests

### ISSUE THREAD

**Issue by jeffkenney** [hapijs/hapi#3802]
When a request is received by a Hapi server, event handlers listening for the `request` event are not being triggered when the request is successful, but are being triggered when an error is thrown in the route handler.

```js
const hapi = require('hapi');

const server = new hapi.server();

server.route({
  method: 'GET',
  path: '/success',
  handler: (request, h) => {
    console.log('in /success request handler');
    return h.continue;
  }
});

server.route({
  method: 'GET',
  path: '/error',
  handler: () => {
    console.log('in /error request handler');
    throw new Error();
  }
})

server.events.on('request', (request, event, tags) => {
  console.log(`request event received for path ${request.path}, tags:`, Object.keys(tags));
});

(async () => {
  await server.start();
  await server.inject({ method: 'GET', url: '/success' });
  await server.inject({ method: 'GET', url: '/error' });
  process.exit();
})();
```

#### What was the result you received?

The request event handler was not triggered when making a request to the `/success` route:

```
in /success request handler
in /error request handler
request event received for path /error, tags: [ 'handler', 'error' ]
request event received for path /error, tags: [ 'internal', 'error' ]
```

#### What did you expect?

The request event handler should have been triggered when making a request to the `/success` route.

#### Context

* *node version*: 8.11.2
* *hapi version*: 17.5.2
* *os*: macOS 10.13.5

**Comment by hueniverse** [comment]
It is not supposed to. There is nothing in the docs to suggest otherwise. If you want to know when all requests come in, use the onRequest ext.
