### ISSUE TITLE
Can't access request.payload in POST route

### ISSUE THREAD

**Issue by Banjerr** [hapijs/hapi#3805]
Howdy Hapi folks. I'm running into a pretty interesting issue. I'm `POST`ing to a route and using the `request.payload` to update some records in Mongo.. Here's the interesting part...

#### What was the result you received?

If I `console.log` out the `request.payload` then I can see all the data is there correctly; however if I try to access any property in the payload (`request.payload.customerID`, which I can clearly see logged out correctly in the `request.payload`) then all I get is undefined. I've tried assigning the `request.payload` to another var, logging out that var (which has all the data correctly in it), and then trying to access a property in the var which also gives me undefined. I have other routes where I'm doing almost the exact same thing, but it works as expected there.

#### What did you expect?

I expected to be able to access `request.payload` parameters

An example of the route in one of its iterations...

```
server.route({
    method: 'POST',
    path: '/update-score',
    handler: (request, h) => {
        var scores = db.collection('scores');
        console.log('request payload ', request.payload); // correct data as object
        var payload = request.payload;
        console.log('payload ', payload); // correct data as object
       
        var queryObj = {
            customerID: payload.customerID // undefined
        };

        var updateObj = {
            $set: {
                customerID: payload.customerID, // undefined
                customerName: payload.customerName,  // undefined
                highScore: payload.highScore  // undefined
            }            
        }

        console.log(request.payload); // correct data as object
        console.log(request.payload.customerName); // undefined
        console.log(request.payload.customerID); // undefined 
        var updateScore = new Promise((resp, rej) => {
            scores.findOneAndUpdate(queryObj, updateObj, { upsert: true, returnNewDocument: true}, (err, res) => {
                if (err) {
                    return rej(err);
                }
                else {
                    return resp(res);
                }
            })
        });

        return updateScore;
    }
});
```

I'm quite stumped here. To make it even more interesting, if I'm `POST`ing the data from Insomnia/Postman then I'm able to access the `request.payload` parameters and assign them as needed, and as expected. But when this `POST` comes from a web page I start seeing this weird behavior, even though I can see the correct data making its way to the server (just can't access any of its properties...)

**Comment by k-j-kleist** [comment]
Have you read, digested, and understood the instructions in the issue template? Especially this part:

> Issues should only be posted in this repository after you have been able to reproduce
them and confirm that they are a bug or incorrect/mising information in the API.md file. If you
are not sure, please first raise the question in the [discussion repository](https://github.com/hapijs/discuss).

That said, I believe you should check the post request's content type, as well as `config.payload.defaultContentType` for the route.

I suggest that you now close this issue here, and move on to the [discussion repository](https://github.com/hapijs/discuss).

**Comment by Banjerr** [comment]
Issue closed: reopened in [https://github.com/hapijs/discuss/issues/699](discussion repo here #699)
