### ISSUE TITLE
Error: Cannot throw non-error object on GET response using

### ISSUE THREAD

**Issue by jthommen** [hapijs/hapi#3810]
Hi everyone,

I searched extensively but couldn't find something similar. Hope this helps:

#### What was the result you received?
I get an internal error:
``` 
Debug: internal, implementation, error 
    Error: Cannot throw non-error object
    at module.exports.internals.Manager.execute (.../node_modules/hapi/lib/toolkit.js:42:33)
    at <anonymous>
```
#### What did you expect?
Endpoint should return data from levelDB

#### Context
I use Hapi with LevelDB. With levelDB, I have functions to set data and to get data:
```
/** Helper fucntions to interact with the address levelDB */

const level = require('level');
const addressDB = './adressdata';
const db = level(addressDB);

function addAddressToDB(address) {
  return new Promise( (resolve, reject ) => {
    db.put(address.toString(), 'valid')
      .then( () => resolve('Stored Address.'))
      .catch(err => reject(err));
  });
}

// Checks how many stars an address still can create
function getAddressInfo(address) {
  return new Promise( (reject, resolve) => {
    db.get(address.toString())
      .then(value => resolve(value))
      .catch(err => reject(err));
  });
}

module.exports = {
  addAddressToDB: addAddressToDB,
  getAddressInfo: getAddressInfo
};
```
Those handler work fine in a nodeJS environment. Also the setter routine works with a Hapi POST routine. But retrieving the data through a GET routine fails (even though I can retrieve in a nodeJS environment).
Hapi code:

```
'use strict';

// Basic server setup
const Hapi = require('hapi');
const addressDB = require('./addressdb-utilities');

const server = Hapi.server({
    port: 8000,
    host: 'localhost'
});
// Helper to Add Address
  server.route({
    method: 'POST',
    path: '/addAddress',
    config: {
      handler: async (request, response) => {
        try {
          let address = request.payload.address.toString();
          let response = await addressDB.addAddressToDB(address, 'valid')

          return response;
        } catch(err) { throw new Error(err) }
      }
    }
  });
  
  // Helper to retrieve address
  server.route({
    method: 'GET',
    path: '/address/{address}',
    handler: async (request, reply) => {
      let address = encodeURIComponent(request.params.address).toString();
      let status = await addressDB.getAddressInfo(address);
      console.log('Address: ', address);
      console.log('Address Type: ', typeof address);
      console.log(status);
      return 'address';
    }
  });
// Initialize server
const init = async () => {
    await server.start();
    console.log(`Server running at: ${server.info.uri}`);
    return;

};

// Error handling
process.on('unhandledRejection', (err) => {

    console.log(err);
    process.exit(1);
});

init();
```

* *node version*: 8.11.3
* *hapi version*: 17.5.2
* *Using level version*: 4.0.0
* *os*: OSX 10.13.6 (High Sierra)
* *any other relevant information*:
- Tried Postman & Curl to send the requests
- Also tried to retrieve data via POST request, same error
- If I wrap it in a try {} catch {} block, there doesn't occur an NodeJS error, but I get an error code 500 on request

**Comment by hueniverse** [comment]
This really doesn't belong here. It should be posted in the discuss repo. I would suggest you add a console log in .../node_modules/hapi/lib/toolkit.js:42 to output what non-Error object is being thrown and figure out what you are doing wrong from there. Basically, something is throwing and it's not an Error object which hapi does not allow.

**Comment by afuggini** [comment]
Having the same problem.
@hueniverse the non-Error object is simply `null` in my case.

**Comment by afuggini** [comment]
@jthommen Found my problem was related to the header format. I was sending `Bearer: xxxxxx` instead of `Bearer xxxxxx`.
