### ISSUE TITLE
Stale timestamp

### ISSUE THREAD

**Issue by srikantpandey** [hapijs/hapi#3817]
i am getting this message on postman  after providing hawk auth
{
    "error": {
        "message": "API key is not valid. Request authorization failed. Stale timestamp"
    }
}

**Comment by srikantpandey** [comment]
i am getting this message on postman after providing hawk auth
{
"error": {
"message": "API key is not valid. Request authorization failed. Stale timestamp"
}
}

**Comment by k-j-kleist** [comment]
I suggest you read and digest the instructions in the issue template before wasting the maintainers' and the 489 subscribers' time.
