### ISSUE TITLE
response().code() doesn't work for empty/null payloads

### ISSUE THREAD

**Issue by dwelle** [hapijs/hapi#3820]
#### Are you sure this is an issue with the hapi core module or are you just looking for some help?

core issue

#### Is this a security related issue?

no

#### What are you trying to achieve or the steps to reproduce?

Returning `response().code()` doesn't respond with given code if empty/null payload (see below).

```js
const Hapi = require("hapi");
(async function () {
    try {
        const server = Hapi.server({
            port: 3000
        });
        
        server.route([{
            path: "/404",
            method: "GET",
            options: {
                auth: false
            },
            async handler ( request, h ) {
                return h.response().code(404);
            }
        }]);

        await server.start();
    } catch ( err ) {
        console.error(err);
    }
})();
```

tested via:

```
$ curl -I 'http://localhost:3000/404'
```

#### What was the result you received?

- `h.response().code(404)` → `0HTTP/1.1 200 OK` :x:
- `h.response(null).code(404)` → `0HTTP/1.1 200 OK` :x:

- `h.response(false).code(404)` → `0HTTP/1.1 404 Not Found` :heavy_check_mark:
- `h.response(true).code(404)` → `0HTTP/1.1 404 Not Found` :heavy_check_mark:
- `h.response(0).code(404)` → `0HTTP/1.1 404 Not Found` :heavy_check_mark:
- `h.response(1).code(404)` → `0HTTP/1.1 404 Not Found` :heavy_check_mark:
- `h.response('').code(404)` → `0HTTP/1.1 404 Not Found` :heavy_check_mark:
- `h.response({}).code(404)` → `0HTTP/1.1 404 Not Found` :heavy_check_mark:

#### What did you expect?

404 response

#### Context

* *node version*: `10.0.0`
* *hapi version*: `17.5.4`
* *os*: Windows 7
* *any other relevant information*: maybe related to https://github.com/hapijs/hapi/issues/3152

**Comment by saurav-sahu** [comment]
@dwelle Unable to repro this issue. My node version is also `10.0.0` and hapi.js `17.5.4`
Can you try again and check if this issue is present?

**Comment by dwelle** [comment]
@saurav-sahu hmm, cannot repro either. Can't explain, nothing changed --- I recall I was quite meticulous and spent a lot of time before reporting. If I come across this again, I'll re-open this issue.
