### ISSUE TITLE
hapijs.com is down

### ISSUE THREAD

**Issue by Y-LyN-10** [hapijs/hapi#3824]
Unfortunately, https://hapijs.com/ is down right now (and it's been a while).

**Comment by k-j-kleist** [comment]
Please check for duplicates before reporting, this is the THIRD issue opened about this.

**Comment by Y-LyN-10** [comment]
> Please check for duplicates before reporting, this is the THIRD issue opened about this.

@k-j-kleist , I know that there were posted issues like that before and they are closed. Initially, I posted a comment on on of them, but then I thought that it's quite urgent and a comment on a closed issue will not be noticed.
