### ISSUE TITLE
Documentation missing for setting up SPA with inert 

### ISSUE THREAD

**Issue by ohcibi** [hapijs/hapi#3829]
The documentation about serving static files should cover how to setup an SPA that uses real paths for it's routes. The documentation should cover, how to:

1. Set up hapi to serve all static assets of the spa (living in e.g. a directory `/assets`)
2. Set up hapi to serve the spa's `index.html` for any request to a path that does not map to an existent asset

**Comment by hueniverse** [comment]
That's an issue for inert or hapijs.com.
