### ISSUE TITLE
Dependency duplication

### ISSUE THREAD

**Issue by SimonSchick** [hapijs/hapi#3858]
#### What are you trying to achieve or the steps to reproduce?

Trying to keep our dependencies in check, I have a tool that traces duplicate dependencies:

#### What was the result you received?

```
Duplicate dependency joi installed 2 times 14.0.3,13.7.0!
    14.0.3: catbox
    14.0.3: hapi > heavy
    14.0.3: hapi
    14.0.3: hapi > podium
    14.0.3: hapi > shot
    13.7.0: hapi > statehood <<<<<<
    14.0.3: inert
    14.0.3:

Duplicate dependency hoek installed 2 times 6.0.0,5.0.4!
     6.x.x: boom
     6.x.x: catbox
     6.x.x: hapi > accept
     6.x.x: hapi > ammo
     5.0.4: hapi > bounce
     6.x.x: hapi > call
     6.x.x: hapi > catbox-memory
     6.0.0: hapi
     6.x.x: hapi > heavy
     6.x.x: hapi > mimos
     6.x.x: hapi > podium
     6.x.x: hapi > shot
     5.0.4: hapi > statehood  <<<<<<
     5.0.4: hapi > statehood > iron  <<<<<<
     5.0.4: hapi > statehood > joi  <<<<<<
     6.x.x: hapi > subtext > pez > b64
     6.x.x: hapi > subtext > pez > nigel
     5.0.4: hapi > subtext > pez > nigel > vise  <<<<<<
     6.x.x: hapi > subtext > pez
     6.x.x: hapi > subtext
     6.x.x: hapi > subtext > wreck
     5.0.4: hapi > topo  <<<<<<
     6.x.x: inert
     6.x.x: joi
     5.0.4: yar  <<<<<<
```

#### What did you expect?

No duplicate dependencies.

#### Context

* *node version*: v10.12.0
* *hapi version*: all latest
* *os*: osx

You might want to create a utility that keeps all these things in check, I know managing dependencies is tedious.

**Comment by SimonSchick** [comment]
Ok, after wrestling npm for a good 30min, clearing my cache many times and screaming at my screen the only issue left is `yar` see https://github.com/hapijs/yar/blob/master/package.json#L18

**Comment by hueniverse** [comment]
It will take a few more days before I update the entire ecosystem to the new deps.

**Comment by SimonSchick** [comment]
That's fair, regardless you might want to look into a tool that auto updates the ecosystem, should make the entire update process less of a chore :)
