### ISSUE TITLE
response.headers.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by birdream** [hapijs/hapi#3877]
When I want to check the response.headers in test ```await response = server.inject({...balabala})```

response.headers:
```
{ 
  'content-type': 'application/json; charset=utf-8',
  'cache-control': 'no-cache',
  'content-length': 396,
  date: 'Tue, 13 Nov 2018 06:20:42 GMT',
  connection: 'keep-alive'
}
```

```
typeof response.headers // 'object'
```
But:
```
response.headers.hasOwnProperty('date') // throw an hasOwnProperty is not a function error
```

And actually I want to do some test like ```response.headers.should.have.property('data')```
but it would throw ```TypeError: Cannot read property 'have' of undefined``` error, so any idea that how can I handle it? thanks.

#### Context

* *node version*:  v8.9.4
* *hapi version*: hapi@17.7.0

**Comment by hueniverse** [comment]
This is coming from shot which calls node's Http.ServerResponse `getHeaders()` which I guess is creating a headers object with null prototype. Just compare to undefined instead.
