### ISSUE TITLE
Tests fail on node v11.2.0 (pass on v11.1.0)

### ISSUE THREAD

**Issue by dominykas** [hapijs/hapi#3880]
#### What are you trying to achieve or the steps to reproduce?

Re-ran latest master build on travis: https://travis-ci.org/hapijs/hapi/builds/451977488

#### What was the result you received?

Failed - travis has since been upgraded to nodejs `v11.2.0`; used to pass with nodejs `v11.1.0`, see e.g. https://travis-ci.org/hapijs/hapi/builds/451745849.

Same story locally on macOS.

#### What did you expect?

Passing build

#### Context

* *node version*: `v11.2.0`
* *hapi version*: latest `master`
* *os*: Docker on travis, macOS Sierra

**Comment by hueniverse** [comment]
Resolved with 11.6.0
