### ISSUE TITLE
request.url.search is empty string using node.js 8 LTS, but is null using 10 LTS

### ISSUE THREAD

**Issue by jeromecovington** [hapijs/hapi#3883]
#### Are you sure this is an issue with the hapi core module or are you just looking for some help?

This appears to be an issue with core in that differing behavior in the value for `request.url.search` is observed in node.js 8 LTS vs node.js 10 LTS.

#### Is this a security related issue?

I don't think so.

#### What are you trying to achieve or the steps to reproduce?

My app has a few cases where browser requests are parsed and proxied to an underlying request. Here's a simple file that distills out the mechanism being used without any of my app-specific complications.

```js
const Hapi = require('hapi');
const rp = require('request-promise');

const server = Hapi.server({
    port: 3000,
    host: 'localhost'
});

server.route({
    method: 'GET',
    path: '/asking-for-a-friend',
    handler: (request, h) => {
      const proxyUrl = `https://duckduckgo.com${request.url.search}`;
      console.log({ proxyUrl });
      return rp(proxyUrl);
    }
});

const init = async () => {
    await server.start();
    console.log(`Server running at: ${server.info.uri}`);
};

process.on('unhandledRejection', (err) => {
    console.log(err);
    process.exit(1);
});

init();
```

#### What was the result you received?

When running this file on node.js 8 LTS we can see the following behavior:
```shell
$ node index.js
Server running at: http://localhost:3000

# request made to http://localhost:3000/asking-for-a-friend?q=foo
{ proxyUrl: 'https://duckduckgo.com?q=foo' }

# request made to http://localhost:3000/asking-for-a-friend
{ proxyUrl: 'https://duckduckgo.com' }
```

Now, running this file on node.js 10 LTS:
```shell
$ node index.js
Server running at: http://localhost:3000

# request made to http://localhost:3000/asking-for-a-friend?q=foo
{ proxyUrl: 'https://duckduckgo.com?q=foo' }

# request made to http://localhost:3000/asking-for-a-friend
{ proxyUrl: 'https://duckduckgo.comnull' }
# 500 error received
```

#### What did you expect?

I was surprised that my app was giving me errors under similar conditions when running it on node.js 10 LTS. I guess I would expect the same behavior as under node.js 8 LTS. My only semi-informed guess is that now that the WHATWG `URL` class is global there may be some new issue, although my attempts to find such a problem in hapi core have come up empty-handed so far.

#### Context

* *node version*: 8 LTS vs. 10 LTS
* *hapi version*: 17.7.0
* *os*: macOS 10.12.6
* *any other relevant information*: Test server can be cloned from this repo - https://github.com/jeromecovington/hapi-request-url-search

**Comment by cjihrig** [comment]
This is a change in Node core. You can verify with `url.parse('http://localhost:3000/asking-for-a-friend', true);` on Node 8.13.0 versus 10.13.0.

I haven't bisected, but this change in Node 9.0.0 should be responsible: https://github.com/nodejs/node/commit/c88ba036b4
