### ISSUE TITLE
Server.inject with array query params breaks instanceof Array

### ISSUE THREAD

**Issue by AnianZ** [hapijs/hapi#3890]
I have a handler that acceps an array for one query parameter. So when I do a request like
```bash
$ # Request with httpie
$ http GET "$API/instruction?states=active&states=archived"
```
it get's parsed correctly.
```js
console.log('in query', Array.isArray(request.query.states), request.query.states instanceof Array);
```
at the beginning of the `handler` logs `in query true true` to the console.

To test this endpoint I use `server.inject` with the same query parameters, so for example:

```js
const response = await testEnv.server.inject({
        method: 'GET',
        url: '/api/instruction?states=active&states=archived',
});
```
but then I get logged  `in query true false` to the console.

I was using `instanceof Array` in later steps of the handler to determine if I got only one `?states=` or multiple in the URL. I will need to adapt that to `Array.isArray()` to be able to test it but  I expected `instanceof` should work as well. I don't see a reason why the `request.query.states` would be different when using `server.inject`.

#### Context

* *node version*: 10.13.0
* *hapi version*: 17.8.1 (experienced the bug with 17.5.4 first)
* *os*: Linux 4.19.4-arch1-1-ARCH x86_64
* *any other relevant information*: I'm using hapi with typescript but I checked the transpiled javascript as well and the `instanceof` stayed the same

This could be related to #3407 but that issue got closed without a solution

**Comment by hueniverse** [comment]
Cannot reproduce. See tests added to both v17 and master branch.
