### ISSUE TITLE
No detail in error message of Joi validation

### ISSUE THREAD

**Issue by nickeljew** [hapijs/hapi#3893]
When I was using Hapi v16.6.2, the error message of Joi validation carried the invalidate detail like the following:
_child "page" fails because ["page" must be a number]_

After I upgraded Hapi to v17.7.x, the error message only shows
_Invalid request payload input_

How can I get the error detail back?

**Comment by WesTyler** [comment]
Yes, this was a security improvement made in hapi@17.

You can leverage the [`failAction`](https://github.com/hapijs/hapi/blob/master/API.md#lifecycle-failAction) by making your route validation property look something like this:
```
{
    params: {
        id: Joi.string().guid().required()
    },
    query: {
        active: Joi.string().optional()
    },
    failAction: async(request, h, err) => {
        return err;
    }
}
```

**Comment by j0shua** [comment]
Hi @WesTyler,

Does that need to be configured on every route individually ?

**Comment by devinivy** [comment]
Not necessarily—you can set it on your [`server.options.routes`](https://github.com/hapijs/hapi/blob/v17/API.md#server.options.routes) configuration or apply defaults to routes on your own with a tool like [`Toys.withRouteDefaults()`](https://github.com/hapipal/toys/blob/master/API.md#toyswithroutedefaultsdefaults).

**Comment by Marsup** [comment]
On a side-note, hapi removed it for a reason, it was explained in the release notes, make sure you understand those reasons.
