### ISSUE TITLE
Server.route should give a warning or show an error when accidentally providing multiple route objects as parameter instead of an array

### ISSUE THREAD

**Issue by JNokikana** [hapijs/hapi#3896]
Example code:

```js
exports.plugin = {
    name: "app-routes",
    version: "1.0.0",
    register: async function (server, options) {
        server.route(
            {
                method: "POST",
                path: "/api/v1/news",
                config: {
                    handler: Handler.createNews
                }
            },
            {
                method: "GET",
                path: "/api/v1/news",
                config: {
                    handler: Handler.readNews
                }
            },
            {
                method: "DELETE",
                path: "/api/v1/news",
                config: {
                    handler: Handler.deleteNews
                }
            }
        )
    }
}
```
If you use the above code then only the first route works. This is because server.route expects an array of route objects and not multiple route objects. In my humble opinion the framework should throw an error or maybe a warning when you accidentally do it like this without an array. 😄  This annoyed me very much especially when I once had a typo in my code and could not at first figure out why only the first route worked. 🙈

**Comment by kanongil** [comment]
Given destructoring, the api should probably just be reworked to `server.route(...routes)`, and throw on arrays.

**Comment by hueniverse** [comment]
You can't expect the framework to validate the number of arguments passed for every api call.
