### ISSUE TITLE
Cookies HTTP vs HTTPS

### ISSUE THREAD

**Issue by dl748** [hapijs/hapi#3902]
I don't know if this is an issue or not, but it was a pain to debug and fix.  If you default to http, statehood is defaulting the cookie to be "Secure" so no browser will ever set the cookie, you have to set this.settings.state.isSecure = false.  I'm not sure if the system should default to secure, or, it should take into account http vs https when setting that default.

**Comment by hueniverse** [comment]
The problem is that most production node deployment use HTTP not HTTPS (using an external front HTTPS LB). This means that you cannot decide if cookies should be secure based on the protocol level at the hapi server level.

If the docs can be clearer on that, please submit a PR. Otherwise, there isn't much I can do about this.

**Comment by dl748** [comment]
Why can't you? Why would you default to unable to set cookies?  Secure should only be used if certs are specified in the configuration for that connection i.e. { tls: { cert:"", key:"" }}.  Setting secure for any other reason will make cookies completely useless.  If most node production deployment use HTTP then I would think you wouldn't want secure set, as there is no browser that would even accept those cookies, ever.

**Comment by dl748** [comment]
No I understand that, but then wouldn't the configurer TURN ON SECURE manually because they are going use it?  What i'm not understanding, i guess. Is why is the default to be in a broken state where cookies cannot be used. Non TLS/SSL should default to non secure, TLS/SSL should default to secure, with the ability to override that if needed.  I'm just saying the DEFAULT should take into account the state of the connection, instead of always saying true or false.

**Comment by hueniverse** [comment]
The default is always going to be the most secure.
