### ISSUE TITLE
Drop support for node v8

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#3910]
Pave the way for new language features such as `for await...of`.

**Comment by kanongil** [comment]
With current v10, `BigInt` support is also included, and `URL` is exposed as a global (no need to `require('url')`).

It also allows us to use [`util.types`](https://nodejs.org/api/util.html#util_util_types) for type detection in Hoek.

**Comment by mcollina** [comment]
@hueniverse https://github.com/nodejs/readable-stream/issues/333. I also wrote https://github.com/mcollina/stream-iterators-utils#utilstoreadablegenerator-opts ( I'd like to get it into core at some point).

Overall the question is that:

```js
const http = require('http')

async function handle (req, res) {
  let chunks = []
  for await (let chunk of req) {
    chunks.push(chunk)
  }
  res.end()
}

http.createServer(function (req, res) {
  handle(req, res).catch(() => res.end())
})
```

Is stable for the Hapi community to use. It also works on files and on any other stream from core or created via readable-stream.
