### ISSUE TITLE
Failing CI

### ISSUE THREAD

**Issue by DanielRuf** [hapijs/hapi#3918]
It seems CI is often not stable on AppVeyor.
https://ci.appveyor.com/project/hueniverse/hapi/builds/22036366

Would it be more stable on the Windows builds of Travis CI?

**Comment by hueniverse** [comment]
Maybe. Just low on my list.

**Comment by Marsup** [comment]
Maybe we could enable windows builds on Travis and stop with AppVeyor.

**Comment by hueniverse** [comment]
Giving it a try. Thanks.
