### ISSUE TITLE
Update hapijs/bourne to 1.1.2 from 1.1.1

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#3926]
Not a concern, just good housekeeping.

**Comment by aorinevo** [comment]
Hi @hueniverse,

Does this mean opening a PRs for each of statehood, subtext, and wreck?
```bash
$ npm ls bourne
hapi@18.1.0 /Users/aorinevo/Repositories/hapi
├─┬ statehood@6.0.9
│ └── bourne@1.1.1
├─┬ subtext@6.0.12
│ └── bourne@1.1.1  deduped
└─┬ wreck@14.1.4
  └── bourne@1.1.1  deduped
```

![Screen Shot 2019-04-01 at 12 19 23 PM](https://user-images.githubusercontent.com/3240137/55343134-7824d800-5478-11e9-8e33-203b15d99858.png)

**Comment by hueniverse** [comment]
No. But don't worry about these issues. They are for me.
