### ISSUE TITLE
hapijs.com front page uses h. What is h?

### ISSUE THREAD

**Issue by mikemaccana** [hapijs/hapi#3928]
Just checking out Hapi. https://hapijs.com/ includes:

    // Add the route
    server.route({
        method:'GET',
        path:'/hello',
        handler:function(request,h) {

            return'hello world';
        }
    });

As someone who hasn't used Hapi before: **what is h?**

If it's not used, it should be deleted. If it is used, it shouldn't be minified.

**Comment by k-j-kleist** [comment]
Why do you not follow the instructions in the issue template?

Please close this issue, and open one in the [discussion repository](https://github.com/hapijs/discuss).

**Comment by calmdev** [comment]
**[Response Toolkit](https://github.com/hapijs/hapi/blob/master/API.md#response-toolkit)**
> It is named in the spirit of the RethinkDB r method, with h for hapi.

**Comment by mikemaccana** [comment]
@k-j-kleist Why do you think I didn't read it? The issue isn't fixed - hapijs.com [still uses the minified variable](https://hapijs.com)

**Comment by zveljkovic** [comment]
Please do not 'fix' this. I love the convention that something well explained in the docs, has single letter name as it's quicker to program and has that deep feeling of interconnectedness with the API. This h variable is reminding me of all the nice things in hapi, its conventions, features and down to earth attitude. I love hapi and I love h :)

**Comment by nlf** [comment]
this issue is in the wrong place, and won't be fixed regardless as it follows hapi conventions

**Comment by mikemaccana** [comment]
@zveljkovic a demo on a front page of a website shouldn't require further explanation. The purpose of a demo is to explain, not to save you typing three characters. 

> This h variable is reminding me of all the nice things in hapi, its conventions, features and down to earth attitude.

Nor is the purpose of a demo for exiting users to feel better about hapi. 

But hey, I give up. Do what you want.
