### ISSUE TITLE
Revise list of hop-by-hop headers

### ISSUE THREAD

**Issue by l-hedgehog** [hapijs/hapi#3943]
The list of hop-by-hop headers in #3621 are taken from rfc2616, and there's [Errata 4522](https://www.rfc-editor.org/errata/eid4522) which says 

> Trailers (with a s) does not seem to a header field, just a keyword for TE.
> I think that Trailer (without a s) is expected here.

I think the list here should be updated accordingly.

You might also want to take these discussions [1] [2] about the missing of such a list in updated http/1.1 rfc723* into consideration.

[1]: https://mailarchive.ietf.org/arch/msg/httpbisa/gLmLxl2wjMWRGLRHvwHSLI67bVs
[2]: https://mailarchive.ietf.org/arch/msg/httpbisa/5UQpFIJbvmSd16VYEjGYjPtQQ6s

How I found this:

I'm using hapijs/h2o2 to proxy request to hapi-auth-hawk protected endpoint, but after upgrading from node 8 to 10, I'm getting an [ERR_HTTP_TRAILER_INVALID](https://github.com/nodejs/node/commit/80c9ef0b6be57d42632526818a3b0c3f20f225a1) error, seemingly from the removal of "transfer-encoding" but not "trailer".

**Comment by hueniverse** [comment]
@mnot Beyond fixing the typo, would you recommend making other changes to the code here:
https://github.com/hapijs/hapi/blob/master/lib/response.js#L15

**Comment by mnot** [comment]
You appear to be removing headers listed in `Connection`, so you should be good. There's a discussion at https://github.com/httpwg/http-core/issues/165 that might touch on this in the revised specs.
