### ISSUE TITLE
Destructured Tooltip methods

### ISSUE THREAD

**Issue by Firanolfind** [hapijs/hapi#3948]
#### Are you sure this is an issue with the hapi core module or are you just looking for some help?

Yes. I've just created PR #3949  .

#### Is this a security related issue?

No.

#### What are you trying to achieve or the steps to reproduce?

To use destructured `response` method from **h** in route handler.

```js
server.route({
  method: 'POST',
  path: '/',
  handler: (req, { response }) => {
    return response({
      message: 'Created',
    }).code(201);
  },
});
```

#### What was the result you received?

```
Debug: internal, implementation, error
    TypeError: Cannot read property 'request' of undefined
    at response (. . . ./node_modules/@hapi/hapi/lib/toolkit.js:177:43)
```

#### What did you expect?

Use `response` without **h**;

#### Context

* *node version*: v12.2.0
* *hapi version*: v18.3.1

**Comment by hueniverse** [comment]
The toolkit is a class with prototype methods. You can't deconstruct it. Allowing you to means creating new functions on every toolkit generation instead of reusing the prototype methods. Not going to happen.
