### ISSUE TITLE
Errors from res.setHeader inside internals.writeHead are not properly caught

### ISSUE THREAD

**Issue by iiroj** [hapijs/hapi#3951]
When Hapi sends data using the `exports.send` method in `lib/transmit.js`, the call will go through the chain `internals.transmit` -> `internals.writeHead`. In `writeHead` the node.js native `res.setHeader` is called. The `internals.transmit` contains no error handling, so errors in `res.setHeader` will be thrown from `internals.writeHead` and hit the `exports.send` method's catch statement, where `internals.fail` is eventually called. The `internals.fail` will finally call again the `internals.transmit` without further error handling. This means we are back in the original problem with calling `res.setHeader`.

In our case the error message in console was:

```bash
[error] message: The header content contains invalid characters, stack: TypeError: The header content contains invalid characters
    at validateHeader (_http_outgoing.js:497:11)
    at ServerResponse.setHeader (_http_outgoing.js:501:3)
    at Object.internals.writeHead ([REDACTED]/node_modules/hapi/lib/transmit.js:324:21)
    at Object.internals.transmit ([REDACTED]/node_modules/hapi/lib/transmit.js:106:15)
    at Object.exports.send ([REDACTED]/node_modules/hapi/lib/transmit.js:32:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

We managed to isolate the origin of this error to a Hapi redirect, where the redirect path was generated from a Hapi route's path parameter. In our case, a newline characted in the parameter emitted the error.

Here is a working test case `server.js`, that you can start with `node`:

```js
// server.js
const Hapi = require('hapi')

async function start() {
    try {
        const server = new Hapi.Server({ port: 8080 })

        server.route({
            method: 'GET',
            path: '/',
            handler: (request, h) => {
                return h.redirect(`/bad/path/\n`) // Redirect to path with a newline character
            }
        })

        await server.start()
    } catch (e) {
        console.error(e)
        process.exit(1)
    }
}

start()

```

the error is achieved on a server running at `localhost:8080` with:

```bash
node server.js
curl localhost:8080
```

#### What was the result you received?
Our server logs the error message and we cannot seem to handle it in our application code without first sanitizing the path parameters.

#### What did you expect?
Hapi's error handling should also cover the case where for whatever reason the `res.setHeader` (and theoretically also `res.removeHeader` and `res.writeHead`) fails, and allow the user of Hapi to more easily handle errors.

#### Context

* *node version*: `v8.9.4`
* *hapi version*: `17.8.5`
* *os*: `macOS 10.14.4 (18E226) (local development)`
* *any other relevant information*:

**Comment by kanongil** [comment]
This seems to be a variant of the issues mentioned in https://github.com/hapijs/hapi/issues/3830#issuecomment-430157680.

**Comment by iiroj** [comment]
I agree, @kanongil. Feel free to close, but hopefully the test case helps. :-)

**Comment by kanongil** [comment]
Yes, it is much appreciated. I just like to link issues 😃

**Comment by hueniverse** [comment]
I am not sure what you expected to happen instead. The error was caught and then another error returned instead. That error was sent without a problem because it no longer included the invalid header.

Where you expecting hapi to validate the header when `redirect()` is called and error there instead? I've been trying to avoid double validating all headers.

@kanongil I don't see how the two issues are connected since in this case only the first `fail()` call fails. The second one goes out because it is just a simple error response.

**Comment by kanongil** [comment]
You are right. I was too quick to diagnose the cause. This is expected behavior.

**Comment by iiroj** [comment]
I’m ok with this. We solved the problem by adding our own validation of headers in this particular case.

Our initial thought was that if Hapi errored because of an invalid header, it shouldn’t try to re-use that header in the error handler. I’m sure this behaviour would lead to other problems, so it’s probably not worth it to try and handle.
