### ISSUE TITLE
hapi 17.8.4 pre throw 500 error instead  of 400 

### ISSUE THREAD

**Issue by anuraggupta816** [hapijs/hapi#3958]
I am using pre-method in Hapi v17.8.4 with promise and pre-method throw 500 error instead of 400. But I am sending 400 error.

**Comment by hueniverse** [comment]
This is not enough information. You need to provide enough code to reproduce the problem.

**Comment by anuraggupta816** [comment]
I am using pre-method for authentication and whenever token expires I send 400 error. But pre-method   send  500 error inserted of 400 error

**Comment by hueniverse** [comment]
500 means your code is most likely doing something wrong.
