### ISSUE TITLE
Question - Why >=8.12.0 for v18?

### ISSUE THREAD

**Issue by Vadorequest** [hapijs/hapi#3961]
I wonder about the technical reasons behind the limited node v8 support.

You've stated in the readme that only versions >=8.12.0 are supported by Hapi v18.x, why is that?

I'm concerned because the package `serverless-offline` has upgraded to hapi v18 in their latest version, but AWS Lambda (one of the possible aws official node engine alongside v10.x) only supports v8.10.

Hence, I'm wondering what are the technical limitations node v8.10 has that makes it incompatible with hapi.

See https://github.com/dherault/serverless-offline/issues/741

**Comment by hueniverse** [comment]
We just use the latest version because that's the only one we test. If you use other versions, you should probably test it by running all the hapi tests.

**Comment by Vadorequest** [comment]
Thanks for the clarification.
