### ISSUE TITLE
Invalid Certificate on hapijs.com

### ISSUE THREAD

**Issue by guischdi** [hapijs/hapi#3963]
The TLS certificate on https://hapijs.com was not issue for that domain (for shortener.secureserver.net instead).

This leads to a ERR_CERT_COMMON_NAME_INVALID error in my browser.

**Comment by kanongil** [comment]
This is likely a temporary fallout of the domain being moved to https://hapi.dev/.

**Comment by guischdi** [comment]
The first entry on google searching for "hapi" still is https://hapijs.com though. Just saying. Maybe it's not the best marketing. And it's happening for quite some time now.

**Comment by AdriVanHoudt** [comment]
Is hapijs.com not redirecting for you? if so what browser/OS are you using? Do you also not get the redirect when doing `$ curl -v hapijs.com`?

**Comment by Marsup** [comment]
I'm going to close this issue as it was just a temporary hiccup and should be solved by now, dns propagation is not that long.

**Comment by guischdi** [comment]
@AdriVanHoudt http://hapijs.com was redirecting of course. But https://hapijs.com (which was the #1 search result in google) was not redirecting because TLS would have had to be terminated successfully first (which was not the possible due to the invalid certificate). A simple **s** in the url makes quite that difference... (so yes, `curl https://hapijs.com` has had certificate issues as well).

@Marsup Thanks for having a look. Yep seems like it was a temporary (though quite some hours) hiccup/misconfiguration of whatever service terminates the TLS for hapijs.com. It's working properly right now.
