### ISSUE TITLE
Custom "content-encoding" without vary header

### ISSUE THREAD

**Issue by kanongil** [hapijs/hapi#3964]
I have a case where I need to do my own compression of the content, setting where I set the `content-encoding` header to disable the built-in processing. As it is, this also sets the `vary` header with an `accept-encoding` value during the transmit step.

Since I always set the `content-encoding` header, I do not want the response to `vary` as such. However, there is no response level option to disable this.

Note, it might not even need to be an option, as unconditionally setting the header for any response with a `content-encoding` header, is a bit of an overreach. Then it can be solved as a (possibly breaking) bug fix, by moving the `response.vary('accept-encoding');` line after the `content-encoding` header check.

The relevant logic:
https://github.com/hapijs/hapi/blob/93378b243e064c961a42fae2e4e72ed874d4588b/lib/compression.js#L78-L99

**Comment by kanongil** [comment]
Another option, that might work better, is for hapi to expose forced content encoding through a response object method. That way I don't need to bother with the encoding myself.

Note that I can't use a route-level option since I need to this in response to a specific query parameter.

**Comment by hueniverse** [comment]
How do you find yourself in all these HTTP rabbit holes...? ;-)
