### ISSUE TITLE
Using joi@16 with hapi

### ISSUE THREAD

**Issue by mytototo** [hapijs/hapi#3970]
#### What are you trying to achieve or the steps to reproduce?

I just saw a new version of `@hapi/joi` is going to be released soon. Since I have a lot schemas, a custom extension and there is a lot of breaking changes I want to make the transition as soon as possible.

This is why I would like to use the preview of `@hapi/joi@16` with `@hapi/hapi@18`. Unfortunately, I came across a lot of errors even though my schemas are good with the new version. It appears I can't use the preview because Hapi rely on `@hapi/joi@15`. The breaking changes are not yet compatible with `@hapi/hapi@18`.

How is it possible to use `@hapi/joi@16` within a `@hapi/hapi@18` application ?

#### What was the result you received?

```bash
(node:5860) UnhandledPromiseRejectionWarning: Error: Invalid schema content: ($_root.alternatives)
```

#### What did you expect?

No errors.

#### Context

* *node version*: v12.8.1
* *hapi version*: v18.3.2
* *os*: macOS

**Comment by hueniverse** [comment]
This requires some work around for v18 and full support in v19.

**Comment by xthule** [comment]
Why is this closed? It isn't fixed yet, and v19 isn't out yet?

**Comment by hueniverse** [comment]
I have my own system of keeping track of things.
