### ISSUE TITLE
request event interactions with failAction

### ISSUE THREAD

**Issue by collintime** [hapijs/hapi#3973]
In an attempt to log every 400, I decided to listen for [request events](https://github.com/hapijs/hapi/blob/master/API.md#-request-event) and check for a `validation` tag. Surprisingly, my listener was not called. I believe this is due to the [default `failAction`](https://github.com/hapijs/hapi/blob/master/lib/toolkit.js#L93) which throws and does not lead to a request event. 

I was able to produce my desired result by adding a `route.validate.failAction` and manually calling `request.log('validation', err)`. Specifying `failAction: "log"` will also work, but bypass validation. 

Should the default `failAction` lead to a `request` event? Should the `server.events` documentation be more explicit? I'm happy to contribute to either solution. Perhaps I've missed something obvious. 

I've added a sample project which illustrates my issue. Run the server and navigate to `http://localhost:3000/whatever?limit=nope` to interact with these features.

```js
"use strict";

const Hapi = require("@hapi/hapi");
const Joi = require("@hapi/joi");

const init = async () => {
  const server = Hapi.server({
    port: 3000,
    host: "localhost",
    routes: {
      validate: {
        failAction: async (request, h, err) => {
          // according to hapi server.events documentation this should be unnecessary
          request.log("validation", err);
          throw err;
        }
      }
    }
  });

  server.events.on("request", (request, event, tags) => {
    // this function will not be called without the failAction above
    if (tags.validation) {
      console.log("log the 400...");
    }
  });

  server.route({
    method: "GET",
    path: "/whatever",
    handler: (request, h) => {
      return "Hello World!";
    },

    options: {
      validate: {
        query: Joi.object({
          limit: Joi.number()
            .integer()
            .min(1)
            .max(100)
            .default(10)
        }).options({ stripUnknown: true })
      }
    }
  });

  await server.start();
  console.log("Server running on %s", server.info.uri);
};

process.on("unhandledRejection", err => {
  console.log(err);
  process.exit(1);
});

init();

```

* *node version*: v10.16.0
* *hapi version*: ^18.3.2
* *os*: macOS Mojave 10.14.6 (18G87)

**Comment by kanongil** [comment]
Yeah, I just had to deal with this while implementing my logger plugin. See https://github.com/kanongil/nipo/blob/a82ec5d4fda8e883dee4ddab8e21f4103ee6fe14/lib/index.js#L14-L25, where I simulate an event when the response contains a non-500 error.

This will probably still not log 400s that are changed in a `onPreResponse` handler.

**Comment by hueniverse** [comment]
We can have a separate discussion on verbose logging, but in v17 I've made the change to log a lot less because it was being ignored 99% of the time and wasting resources. We can add a feature to failAction to log+something if that's desirable.

I updated the docs to properly reflect when the error is logged.
