### ISSUE TITLE
Sever is not being started in Tutorials/Views

### ISSUE THREAD

**Issue by cz0** [hapijs/hapi#3978]
The naming convention for tutorials scripts should be sync. Eg in Tutorials/Views (https://hapi.dev/tutorials/views) the following naming is used:

**const start = async () => {...};
start();**

But previously you used:
**const init = async () => {...};
init();**

Moreover, when you just copy-paste the script from Tutorials/Views and run it, it doesn't work, since the server is not started. Pls add the line with:
**await server.start();**
as a last line in the following function:
**const start = async () => {...};**

**Comment by hueniverse** [comment]
@jarrodyellets please apply to the tutorial to make sure they are consistent in that regard.

@cz0 Thanks - closing as this belongs in hapi.dev.
