### ISSUE TITLE
How to handle errors in a plugin?

### ISSUE THREAD

**Issue by devshorts** [hapijs/hapi#3985]
Sorry for opening an issue but I'm stumped. I'd like to create a plugin that handles any thrown errors from any route and maps them to Boom responses.  In a middleware approach this would be simple, but I can't figure out how this works with hapi.  Is there any documentation or guidance that can be provided on how I can effectively wrap a route?

**Comment by hueniverse** [comment]
Look at the request lifecycle section in the docs, pick the point in the lifecycle you want this to happen (e.g. usually `onPreResponse`) and capture it there. You don't actually handle your own "catching". hapi will catch all errors and convert them to Boom.internal() errors. You can then process those at the desired lifecycle location.

**Comment by devshorts** [comment]
Is there a way to map the boom error? Calling `h.response(.. a boom  type..)` doesn't work. For example, I want to map unhandled errors to a different boom response type.

**Comment by devshorts** [comment]
Nevermind, got it. For anyone in the future I have

```
  register(server: Server, options: void) {
    server.ext('onPreResponse', (r, h) => {
      if (isBoom(r.response) && r.response.output.statusCode === 500) {
        const response = this.handler.mapToBoom(r.response) // map to a better boom type based on the raw response which is the thrown error

        return h.response(response.output).code(response.output.statusCode)
      }

      return h.continue
    })
  }
```

**Comment by devshorts** [comment]
@hueniverse is there a way to get the raw response that isn't boomified? For example, if my error has a `message` field and its not set, then by the time i get `r.response` the `message` field is set with `Internal Service Error` which isn't correct.  Seems like boom adds properties to the existing object instead of wrapping it.  This means I either need to pick a different property name, or handle boom wrapping at each route level. Do you have suggestions?

**Comment by sholladay** [comment]
@devshorts you may want to bring this up in the Slack channel. More people can help that way (most are not watching the issue tracker on a regular basis).

**Comment by devshorts** [comment]
@sholladay will do. Is there a link? The link on the hapi page doesn’t work

**Comment by sholladay** [comment]
Try the link of the support page: https://hapi.dev/support/

**Comment by devshorts** [comment]
Right, the link fails to load. it says the invite is invalid

**Comment by sholladay** [comment]
Ah, yep confirmed. I posted in Slack about it, I'm sure it'll get fixed soon. In the meantime, if you'd like a faster invite, I can send you one manually - just send me your email address ([here's my contact info](http://seth-holladay.com/contact)).
