### ISSUE TITLE
ERROR in ./node_modules/@hapi/joi/lib/types/object/index.js when i use @hapi/hapi instead hapi

### ISSUE THREAD

**Issue by raylyanway** [hapijs/hapi#3989]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v10.16.3
* *module version with issue*: "@hapi/hapi": "^18.4.0"
* *last module version without issue*: "hapi": "^18.1.0"
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*: this is my ```package.json```
```
"devDependencies": {
        "@babel/plugin-transform-runtime": "^7.4.0",
        "babel-eslint": "^10.0.3",
        "babel-jest": "^24.9.0",
        "copy-webpack-plugin": "^4.1.1",
        "extract-text-webpack-plugin": "^3.0.1",
        "html-webpack-harddisk-plugin": "0.1.0",
        "html-webpack-plugin": "2.30.1",
        "webpack": "3.9.1",
        "webpack-dev-server": "2.9.5",
        "webpack-merge": "4.1.1",
        ....
    },
    "dependencies": {
        "@babel/preset-env": "^7.3.4",
        "@babel/preset-react": "^7.0.0",
        "@hapi/boom": "^8.0.1",
        "@hapi/hapi": "^18.4.0",
        "babel-polyfill": "6.26.0",
        "es6-promise": "^4.2.2",
        "hapi": "^18.1.0",
        ...
    },
```

#### What are you trying to achieve or the steps to reproduce?

When i use ```import hapi from '@hapi/hapi';``` instead ```import hapi from 'hapi';``` in my ```server.js``` file. This error reproduced with other libraries  ```@hapi/h2o2, @hapi/inert```. ```@hapi/boom``` works good.

#### What was the result you got?

```
ERROR in ./node_modules/@hapi/joi/lib/types/object/index.js
Module parse failed: Unexpected token (240:96)
You may need an appropriate loader to handle this file type.
|           const pattern = this._inner.patterns[i];
| 
|           if (pattern.regex ? pattern.regex.test(key) : !pattern.schema._validate(key, state, { ...options,
|             abortEarly: true
|           }).errors) {
 @ ./node_modules/@hapi/joi/lib/index.js 23:10-35
 @ ./node_modules/@hapi/hapi/lib/server.js
 @ ./node_modules/@hapi/hapi/lib/index.js
 @ ./src/server/server.js
 @ multi ./src/server/server.js
```

#### What result did you expect?

The correct assembly of my server.

**Comment by Marsup** [comment]
You're not supposed to mix hapi and @hapi/hapi, but I guess you're migrating, still you shouldn't have both in your package.

As for your problem, your setup of webpack doesn't seem to understand the object spread syntax, which has been stable since node 8, your configuration should also support that if you insist on building the server side.

**Comment by raylyanway** [comment]
Thank you. Updating webpack to the latest version helped. Of course, I wanted to leave only one package.
```
"devDependencies": {
        "case-sensitive-paths-webpack-plugin": "^2.2.0",
        "compression-webpack-plugin": "^3.0.0",
        "copy-webpack-plugin": "^5.0.4",
        "html-webpack-harddisk-plugin": "^1.0.1",
        "html-webpack-plugin": "^3.2.0",
        "mini-css-extract-plugin": "^0.8.0",
        "optimize-css-assets-webpack-plugin": "^5.0.3",
        "terser-webpack-plugin": "^2.1.3",
        "webpack": "^4.41.2",
        "webpack-cli": "^3.3.9",
        "webpack-dev-server": "^3.8.2",
        "webpack-manifest-plugin": "^2.2.0",
        "webpack-merge": "^4.2.2"
     .......
    },
    "dependencies": {
        "@babel/preset-env": "^7.3.4",
        "@babel/preset-react": "^7.0.0",
        "@hapi/boom": "^8.0.1",
        "@hapi/h2o2": "^8.3.2",
        "@hapi/hapi": "^18.4.0",
        "@hapi/inert": "^5.2.2"
        ......
    }
```
