### ISSUE TITLE
Response Caching ?

### ISSUE THREAD

**Issue by emrealparslan93** [hapijs/hapi#3991]
I've a route which takes time to respond and sometimes my server fails with 503 while preparing the response.

This route executes some queries in Amazon Athena and then goes for some population in MongoDB. These queries returns with same result for an hour (because the data updated hourly), so the route respond with the same result within an hour.

I want to optimize it by using a response caching logic but I couldn't find any in Hapi docs.
Can you show me a way to achieve this?

Example Library in Express: https://www.npmjs.com/package/apicache

**Comment by hueniverse** [comment]
The issue template is there for a reason. You are welcome to try again, this time following the instructions.
