### ISSUE TITLE
when statusCode is 204 can not get any response result.

### ISSUE THREAD

**Issue by birdream** [hapijs/hapi#3992]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): 
* *is this issue currently blocking your project?* (yes/no):
* *is this issue affecting a production system?* (yes/no):

#### Context

* *node version*:  v10.15.3
* *module version with issue*: hapi v18.1.0 
* *last module version without issue*: 
* *environment* (e.g. node, browser, native):  node
* *used with* (e.g. hapi application, another framework, standalone, ...):
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

```js

// an endpoint handler
const handler = (request, h) => {
    const res = ['a', 'b', 'c'];

    return h.response(res).code(204);
}

// response
// using server.inject() for test
console.log(response.statusCode) // 204
console.log(response.result) // null

//-----------------------------------

// an endpoint handler
const handler = (request, h) => {
    const res = ['a', 'b', 'c'];

    return h.response(res).code(200);
}

// response
// using server.inject() for test
console.log(response.statusCode) // 200
console.log(response.result) //  ['a', 'b', 'c']
```

#### What result did you expect?
204 status should get the response  ['a', 'b', 'c'].

**Comment by Marsup** [comment]
That's kind of the definition of a 204, why would you expect something else ?
