### ISSUE TITLE
Allow payload on GET requests

### ISSUE THREAD

**Issue by AlonMiz** [hapijs/hapi#3993]
#### Support plan
* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context
* *node version*: 10
* *module version*: 18.4
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi
* *any other relevant information*: 

#### What problem are you trying to solve?
Allowing GET routes to recieve body/payload. as of now, the payload is not being processed at all.
I agree it's not a common use case, but that case, we want to proxy requests which are not controlled by our end, and some of the requests are GET with a payload.
eg. Elasticsearch `_msearch` route allows GET requests with a payload.

```js
server.route({
    method: 'GET',
    path: '/',
    handler: (request, h) => {
        return request.payload; // payload will always be empty
    },
});
```

Looking at the library code, it seems that allowing such a case requires removal of several defenses mechanisms. a payload on a GET request is literally nulled, no matter if the payload exists or not.

#### Do you have a new or modified API suggestion to solve the problem?
Allowing GET routes to receive payload, requires only to remove the existing blocking of that capability

**Comment by devinivy** [comment]
One possibility is to utilize an `onRequest` extension and `request.setMethod()` to rewrite the request to use a method that supports payloads.

**Comment by hueniverse** [comment]
@AlonMiz the suggestion from @devinivy is the way to work around it. I am not going to support it. If you prefer to use express, that's your choice.
