### ISSUE TITLE
Error uploading large file - Out of Memory

### ISSUE THREAD

**Issue by tzachristas** [hapijs/hapi#3998]
Hello,

I am trying to upload a large file 76MB through POST using stream. After a few seconds i am getting error :

`FATAL ERROR: invalid table size Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: ..........................`

### HapiJS -v: 16.6.3

Any suggestions appreciated. The nodejs is raising high memory up to about 2GB and then i am getting the out of memory heap

**CLIENT**

  let newData = new FormData();
        newData.append('file', data.FILE_UPLOAD);
        newData.append('data', JSON.stringify(data));
        const request = {
            headers: {
                'Accept': 'multipart/form-data',
            },
            method,
            url: `${application}/api/${this.version}/${this.name}${method === 'POST' ? '' : `/${pkJoin}`}`,
            data: newData,
            noStringify: true,
            useAuth: true,
        };
**API**

  payload: {
              output: 'stream',
              parse: true,
              maxBytes: 157286400, // 150MB of data
              timeout: false,
            },
**Server looks like that:**

var busboy = new Busboy({ headers: request.headers });
        busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
          var saveTo = path.join(basePath, path.basename(fieldname));
          file.pipe(fs.createWriteStream(saveTo));
        });
        busboy.on('finish', function() {
          res.writeHead(200, { 'Connection': 'close' });
          res.end("That's all folks!");
        });
        return request.pipe(busboy);

**Comment by tzachristas** [comment]
I have also removed all server side code. It seems that memory raise up to 1.5GB and after that we get that exception

**Comment by cjihrig** [comment]
> It seems that memory raise up to 1.5GB and after that we get that exception

Google for `--max-old-space-size`. That might help you.

> Node -v: 8.9

You're running an insecure version of Node. Please update to at least v8.16.1, but preferably the latest 8.x. Moving between versions of Node 8 at this point should be trivial.

**Comment by tzachristas** [comment]
That's true...works using this setting but this is not the way stream works

**Comment by cjihrig** [comment]
Yea, I was only addressing your comment about running out of memory. In your original post, you also mention using `parse: true` and `output: 'stream'`. The hapi docs state:

```
Note that payload streams for multipart payloads are a synthetic interface created on top of the entire mutlipart content loaded into memory. To avoid loading large multipart payloads into memory, set parse to false and handle the multipart payload in the handler using a streaming parser
```

Without actually running any code, I'd imagine that's at least partially the problem.
