### ISSUE TITLE
Ability to remove 'X-Frame-Options' header from server response from particular routes

### ISSUE THREAD

**Issue by maxaus** [hapijs/hapi#3999]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no):  yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 8.11.1
* *module version*: 17.8.5
* *environment* (e.g. node, browser, native): Chrome 78 on Windows 10
* *used with* (e.g. hapi application, another framework, standalone, ...): Hapi application
* *any other relevant information*:

#### How can we help?

We wanted to make some routes of our Hapi application embeddable in "iframe" to be used by external systems of our clients. And to be able to do that we need to remove "X-Frame-Options" header from server responses for such routes, but keep it for other routes (now we have default security configuration on server level to send "sameorigin" in responses).
But can't figure out, how to remove this header from response.
What's done so far:
Added `onPreResponse` handler with `server.ext`, and tried to set different values for header inside it, e.g.

```js

 server.ext('onPreResponse', function (request, h) {
    const href = request.url.href;
    const {response} = request;

    if (href.indexOf('/embedded/') > -1) {
      response.header('X-Frame-Options', null);
    }

    return h.continue;
  });
```

If header is set to any string (even if not valid, "sameorigin" or "deny", values), then it's set by this code correctly. But if "null", "undefined", empty string is set, then it's ignored and default "sameorigin" is returned.
I tried to debug and print  `response.headers` inside handler, and seems, that at this moment it doesn't contain "X-Frame-Options" header, e.g. `response.headers` can be something like following:
```js
{
  'content-length': 560,
  'content-type': 'text/html',
  'last-modified': 'Thu, 14 Nov 2019 09:02:04 GMT',
  etag: '"64bdb3fa3fcb932b750a56ce17c934f581fde486"' 
}
```
Maybe this is the reason, why empty value set at this moment is ignored later. But then what is correct moment to set empty header (or remove header somehow else) ?
Thanks in advance for any help on this!

**Comment by hueniverse** [comment]
Do you have a paid core support plan? If so, under what company? If you don't, please change the support plan above to `community` which is the free support option.

**Comment by maxaus** [comment]
@hueniverse sorry, misunderstood this item meaning, changed it to `community` now.

**Comment by hueniverse** [comment]
Unfortunately, no community resources were available to help resolve this issue after two weeks, and it is being closed. We close unresolved community issues to keep the issue tracker organized and effective. Please check https://hapi.dev/support for other support options.

Some hints - the correct way is to set the right security options on the routes you want to override. Setting empty header values will just send empty headers in general so that's not a good approach. You can look at route rules as a way to make this more generic, but probably not needed in this case.
