### ISSUE TITLE
Joi Error when building with Create React App (failed to minify)

### ISSUE THREAD

**Issue by yuschick** [hapijs/hapi#4004]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): Yes
* *is this issue affecting a production system?* (yes/no): Yes

#### Context

* *node version*: v8.11.3
* *module version with issue*: @hapi/joi 16.1.8
* *last module version without issue*: N/A
* *environment* (e.g. node, browser, native): Browser
* *used with* (e.g. hapi application, another framework, standalone, ...): Create React App
* *any other relevant information*: N/A

#### What are you trying to achieve or the steps to reproduce?

After implementing Joi into my forms, I am now trying to run the Create React App `build` command. This is when the error occurs.

Example schema file:

```js
import * as Joi from '@hapi/joi';
```

I have also done:

```js
const Joi = require('@hapi/joi');
```

#### What was the result you got?
Failed to minify the code from this file:
`./node_modules/@hapi/joi/dist/joi-browser.min.js:1:1411`

#### What result did you expect?
I expected the build to complete.

**Comment by Marsup** [comment]
Having an actual error would be helpful, do you have more details than that?

**Comment by Marsup** [comment]
Doesn't belong in this repo.
