### ISSUE TITLE
If global prefix is set, allow overriding prefix in specific routes

### ISSUE THREAD

**Issue by nitrocode** [hapijs/hapi#4007]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 12.13.x
* *module version*: 18.4.x
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi
* *any other relevant information*:

#### What problem are you trying to solve?

Set prefix for all routes except a specific route e.g. /status

```js
var server = new Hapi.Server()
server.realm.modifiers.route.prefix = '/api/v1'
```

but cannot override this variable as seen here

https://github.com/hapijs/hapi/blob/master/lib/route.js#L40

#### Do you have a new or modified API suggestion to solve the problem?

Would be nice when setting up routes that we can do something like this

```
    server.route([
      {
        path: "/status",
        method: "GET",
        options: {
          auth: false,
          // override prefix
          prefix: '',
          // maybe disable prefix?
          //prefix: false,
        },
        handler: (requestData: any, h: any) => {
          return h.response().code(200);
        },
      },
    ])
```

Looks like the `options` key can either be an object or function

https://github.com/hapijs/hapi/blob/master/lib/route.js#L53

When I tried to override the key `options` with a function, I received typescript validation issues.

**Comment by hueniverse** [comment]
Why not just move that one special route to a separate plugin?

**Comment by nitrocode** [comment]
Couldn't you make the same argument for any of the configuration `options` key?

**Comment by hueniverse** [comment]
Time and resources are limited and when there is a simple solution available for something that is not requested by other people, it is the appropriate solution. I am more flexible with requests based on how many people are requesting it, the availability of alternative solutions, and if the request comes from a community plan or paid plan.
