### ISSUE TITLE
Can anyone explain what is this means?

### ISSUE THREAD

**Issue by xiongzhend** [hapijs/hapi#4009]
in a route controller, I found a line 

> const tsl = reply.tslWrap('common.verifyCode');

I wanna to know what 's that use for? many thanks!

**Comment by Marsup** [comment]
One of your plugins or yourself likely decorated the reply object using https://hapi.dev/api/?v=16.8.1#serverdecoratetype-property-method-options. Look for tslWrap somewhere in your code or node_modules.
