### ISSUE TITLE
Here is reproduce repository: https://github.com/kamontat/KingKnight

### ISSUE THREAD

**Issue by kamontat** [hapijs/hapi#4014]
Here is reproduce repository: https://github.com/kamontat/KingKnight

## Relate loc is 

https://github.com/kamontat/KingKnight/blob/17c5563e508cb4bf36d48213d6ea9780debbc23a/src/main.ts#L12-L17

## Step to reproduce

1. clone the project
2. install dependencies by `yarn install [--force]`
3. start project by `yarn start`

Error will look like this... 
![CleanShot 2019-12-29 at 14 39 44](https://user-images.githubusercontent.com/14089557/71553869-1914e380-2a49-11ea-9481-d35363316c90.png)

and If you go to ./.webpack/main/index.js you will found that joi version that pack into webpack is `16.1.8`

_Originally posted by @kamontat in https://github.com/hapijs/hapi/issues/3990#issuecomment-569482622_

**Comment by hueniverse** [comment]
First, next time you open an issue without following the instructions in the issue template your issue will be closed without a response.

Second, I don't know what your point is. Your project doesn't specify a version of joi and hapi internally uses v16 so that's what will be there by default.

**Comment by kamontat** [comment]
My issue refer from this #3990  https://github.com/hapijs/hapi/issues/3990#issuecomment-569482622

**Comment by kamontat** [comment]
And this was created to notify project owner about issue.
