### ISSUE TITLE
Do not override request.payload if set manually in onRequest

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#4015]
- `request.payload` initialized to `undefined`
- If `request.payload` is set to any other value than `undefined` in `onRequest`, any incoming payload will be ignored.

**Comment by Hydrock** [comment]
I want to intercept the payload and modify it a little. But I only see undefined. How can I intercept payload? @hueniverse

**Comment by hueniverse** [comment]
@Hydrock open a proper issue with more details. This is not the right place.
