### ISSUE TITLE
Feature request: custom toJSON() method for request.info

### ISSUE THREAD

**Issue by cjihrig** [hapijs/hapi#4019]
#### Support plan

* *which support plan is this issue covered by?* Community
* *is this issue currently blocking your project?* yes - blocking an update to hapi 19
* *is this issue affecting a production system?* not yet

#### Context

* *node version*: 12.14.1
* *module version*: 19.0.1
* *environment*: node
* *used with*: hapi application
* *any other relevant information*:

#### What problem are you trying to solve?

hapi 19 breaks `JSON.stringify(request.info)`. This [commit](https://github.com/hapijs/hapi/commit/acab4705010de7408a4c234cc78a633e24f51f30) seems like the culprit, as it adds circular structures to `request.info`.

#### Do you have a new or modified API suggestion to solve the problem?

Adding a custom `toJSON()` function to `internals.Info` should fix the problem I think. I'm happy to send a PR.

**Comment by hueniverse** [comment]
I’ll take a PR

**Comment by cjihrig** [comment]
Thank you for the quick turnaround on this.
