### ISSUE TITLE
Handler Issue: connection between hapi server and MS Sql database

### ISSUE THREAD

**Issue by Karol-Kahn** [hapijs/hapi#4028]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no 

#### Context

* *node version*:  v12.14.1
* *module version*: npm 6.13.4
* *environment* (e.g. node, browser, native):  node
* *used with* (e.g. hapi application, another framework, standalone, ...): @hapi/hapi 19.0.5, @hapi/vision 6.0.0, handlebars 4.7.2, mssql 6.0.1
* *any other relevant information*: 

#### How can we help?

Hi, 
I would like to connect my hapi server with a MS SQL server. I am not very familiar with hapi and the h toolkit. Additionally I am quite new to programming. 

I use hapi vision and handlebars to work with template engine. 

The code on promises basis from the documentation of the MSSQL module is not compatible with the hapi handler. Or maybe it is and I just do something wrong. 

I have already established a simple connection to the SQL server via express and was able to display the data in the browser. So the connection from database side should be fine. 

A trained eye might see the error directly. But I have already tried every possibility and I just can't get it right. I would be very happy if someone could help me with the correction.
In the following my approach: 

```js
server.route({
        method: 'GET',
        path: '/',
        handler: (request, h) => {

            const sql = require("mssql");

            sql.connect(config).then(pool => {


                return pool.request()
                    .query("select * from mytable")
                    .then(res => {
                        return h.view('test', { data: res.recordset });
                    })
                    .catch(err => {
                        console.log(err);
                    });
            })
        }
    });
```
The following error is displayed:

Server running at: http://localhost:3000
Debug: internal, implementation, error
    Error: handler method did not return a value, a promise, or throw an error
    at exports.Manager.execute (C:\Users\node_modules\@hapi\hapi\lib\toolkit.js:81:29)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Object.internals.handler (C:\Users\node_modules\@hapi\hapi\lib\handler.js:
46:20)
    at async exports.execute (C:\Users\node_modules\@hapi\hapi\lib\handler.js:31:20)
    at async Request._lifecycle (C:\Users\node_modules\@hapi\hapi\lib\request.js:365:32
)
    at async Request._execute (C:\Users\node_modules\@hapi\hapi\lib\request.js:274:9)

**Comment by Marsup** [comment]
To directly answer your question, you're missing a return on the connect line, as mentioned in the error, your function returns nothing.

Although 2 pieces of advice:
- Hapi has out of the box support and encourages you to fully embrace the async/await syntax, you should get familiar with it as it's much easier to see these kind of problems with some syntactic sugar. Learning promises can also help.
- On a server, it's common to have your connection pool created at the start and then used in the handlers so you don't have to pay the price of a database connection on each request. In hapi it's usually done inside a plugin that exposes the pool to all the handlers.
