### ISSUE TITLE
Incorrect typings

### ISSUE THREAD

**Issue by madtrick** [hapijs/hapi#4030]
#### Support plan

* *which support plan is this issue covered by?* Paid but I can't tell right now which of Core, Plus or Enterprise. Can forward company details by email or similar.
* *is this issue currently blocking your project?* no
* *is this issue affecting a production system?* no

#### Context

* *node version*:  v12
* *module version with issue*: 19.0.5
* *last module version without issue*: 18.0.2
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*: using `@types/hapi__hapi` v19.0.0 

#### What are you trying to achieve or the steps to reproduce?

We enhance the routes of one of our services with [per route app options](https://hapi.dev/api/?v=19.0.5#route-options). Something like:

```typescript
    options: {
      app: {
        action: APIAction.Foo,
        type: APIType.Bar
      },
```
We have extended the `RouteOptionsApp` interface to include the `action` and `type` props:

```typescript
  interface RouteOptionsApp {
    action: APIAction
    type: APIType
  }
```

So we can later access the `app` object:

```typescript
  ...
  if (req.route.settings.app!.type === APIType.Bar) {
  ...
```

#### What was the result you got?

After upgrading to hapi v19 (together with its types definitions) there's a compilation error when we try to access the `app` property of the route options. Accesses like `req.route.settings.app!.type` get the following error:

```text
Property 'app' does not exist on type 'RouteSettings'.
```

#### What result did you expect?

The typings follow the documentation and I can access the route options `app` property through `request.route.settings.app`.

**Comment by hueniverse** [comment]
@madtrick The types provided by DT are not maintained by me and are not officially supported. You need to open this issue in the DT repo.

Adding type definitions natively to all hapi modules is a time and resource consuming process. I've been trying to find ways to fund it and I did start a crowdfunding effort (https://www.gofundme.com/manage/hapi-ts) but it doesn't look like it will work out. Unfortunately this work needs bigger corporate sponsors to get done and right now only Salesforce has contributed $5000 towards the effort.

As for the support plan, your company has been a very generous sponsor over the years. However, the sponsorship is no longer active and a paid support plan requires some additional steps. I would love to chat with them about it but has been unable to reach them for over 6 months.

**Comment by madtrick** [comment]
@hueniverse thanks for you reply. I'll try to clarify the sponsorship because I don't know if it was something intentional or a mistake.

**Comment by hueniverse** [comment]
@madtrick much appreciated!

**Comment by madtrick** [comment]
For visibility, linking here the issue I opened in the typings repo https://github.com/DefinitelyTyped/DefinitelyTyped/issues/41936
