### ISSUE TITLE
Show list from MS SQL database via hapi/vision/handlebars in browser 

### ISSUE THREAD

**Issue by Karol-Kahn** [hapijs/hapi#4032]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v12.14.1
* *module version*: npm 6.13.4
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): @hapi/hapi 19.0.5, @hapi/vision 6.0.0, handlebars 4.7.2, mssql 6.0.1
* *any other relevant information*:

#### How can we help?

Hi,

I have problems using the hapi vision plugin with handlebars. As you can see in the code below, I am trying to program a query from a MSSQL database and display the results in a table via html. 

Unfortunately the data are not listed in my table. And I can't figure out why. Can anyone see the error?  

Thanks in advance

```js
const Hapi = require("@hapi/hapi");
const sql = require("mssql");

const config = {
    user: 'sa',
    password: 'mypasswort',
    server: 'localhost\\MYSERVER', 
    database: 'mydb',
    options: {
        "encrypt": true,
        "enableArithAbort": true
    },
};


const pool = new sql.ConnectionPool(config);
const poolconnect = pool.connect();

poolconnect.then((pool) => {
    return pool.request()
})

pool.on('error', err => {
    console.log(err)
})

const start = async () => {
    const server = Hapi.server({
        host: '0.0.0.0',
        port: 3000
    });
    await server.register(require('@hapi/vision'));

    server.views({
        engines: {
            html: require('handlebars')
        },
        relativeTo: __dirname,
        path: 'templates'
    });

    server.route({
        method: 'GET',
        path: '/',
        handler: (request, h) => {

            return pool.query("select * from mytable")

                    .then(res => {
                       
                        return h.view('test', {rows:res.row});
                      //return console.log(res.recordset)
                    })
                    .catch(err => {
                        return {};
                        console.log(err);
                    });
        }
    });
   

    await server.start();

    console.log('Server running at:', server.info.uri);
};

start();
```
Here are the extract of the teplates from the html file:

```js
   {{#each rows}}
                <tr>
                  <td>{{device}}</td>
                  <td>{{data}}</td>
                  <td>{{stationid}}</td>
                  <td>{{rssi}}</td>
                </tr>
              {{/each}}
```
If I console log the result i get the actual values from the database: 

```js
[
  {
    id: 1111,
    date: <Buffer 00 00 00 00 00 00 07 d5>,
    device: 'Device 1',
    stationId: null,
    rssi: -324,
    data: '887654334567'
  }
]
```
So I assume that the database is connected. The table is also displayed in the browser. Only the data from the database is not listed.

**Comment by Marsup** [comment]
`res.row` doesn't exist, that's `res.recordset`. Independently from that, I don't you're using the driver right. The pool is connected but not awaited, you request a connection from the pool but never use it, ... basically the whole pool stuff before the start function.
