### ISSUE TITLE
any.fork(paths, adjuster), How to pass the paths where i require a field to be mandatory (required) in the array of objects. Dot Notation only works on an object  for key hierarchy now with the array's

### ISSUE THREAD

**Issue by shivab3214** [hapijs/hapi#4033]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): 
* *is this issue currently blocking your project?* (yes/no):
* *is this issue affecting a production system?* (yes/no):

#### Context

* *node version*: 
* *module version*: 
* *environment* (e.g. node, browser, native): 
* *used with* (e.g. hapi application, another framework, standalone, ...):
* *any other relevant information*:

#### How can we help?

```js
const some = 'properly formatted code example';
```

**Comment by hueniverse** [comment]
The template is there for a reason.
