### ISSUE TITLE
request.info.remoteAddress / request.info.remotePort undefined after connection closed (request aborted)

### ISSUE THREAD

**Issue by dominykas** [hapijs/hapi#4034]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Enterprise (I think)
* *is this issue currently blocking your project?* (yes/no): not exactly, a workaround exists
* *is this issue affecting a production system?* (yes/no): not yet

#### Context

* *node version*: 12.4.1
* *module version with issue*: @commercial/hapi@19.0.5
* *last module version without issue*: Unsure, but 18.x was OK
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi service
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

`request.info.remoteAddress` is not available after the socket is closed. It used to be available, because `info` data used to be constructed in full up till https://github.com/hapijs/hapi/commit/acab4705010de7408a4c234cc78a633e24f51f30, whereas now `remoteAddress` / `remotePort` are cached upon first access. If the first access is _after_ the request aborted - the returned value is `undefined` ([node docs](https://nodejs.org/docs/latest-v12.x/api/net.html#net_socket_remoteaddress) say this bit is as designed).

It is trivial to work around this by e.g. calling `request.info.toJSON()` at the start of the request handler to make sure the IP is cached, but I wonder if this was intended and if so - should it be listed in [release notes](https://github.com/hapijs/hapi/issues/4017).

A quick search also found this: https://github.com/nodejs/node-v0.x-archive/issues/9287, and I _can_ see the IP address in the `peername` field, but it seems this has changed at some point between 0.x and 4.x...

#### What was the result you got?

`request.info.remoteAddress` is `undefined`.

#### What result did you expect?

`request.info.remoteAddress` should report the remote address (as recorded when the request came in?)

**Comment by hueniverse** [comment]
Also updated the v19 release notes.
