### ISSUE TITLE
Entire Joi object being logged when error thrown

### ISSUE THREAD

**Issue by adamreisnz** [hapijs/hapi#4036]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): No
* *is this issue affecting a production system?* (yes/no): No

#### Context

* *node version*: 12.14.0
* *module version with issue*: Latest (17.1)
* *last module version without issue*: 15
* *environment* (e.g. node, browser, native):  Node
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?
Just working on upgrading Joi extensions to support 16 and up

#### What was the result you got?
My console window has been filled with literally *hundreds* of lines of code due to one error thrown from `@hapi/joi/lib/index.js:243`. It seems that the error handler is somehow outputting the entire Joi library including circular references to the console when the error throws.

Not entirely sure if the fault lies with Node 12 and their new error handling, or with Joi because it appends so much data to the error (Joi itself, it seems), which then gets outputted.

Either way, the result isn't pretty:

![image](https://user-images.githubusercontent.com/490562/73338105-bda17400-42da-11ea-90fe-f98d07c2435d.png)

![image](https://user-images.githubusercontent.com/490562/73338121-c5611880-42da-11ea-8bf2-b47c5ddbde1f.png)

![image](https://user-images.githubusercontent.com/490562/73338138-cbef9000-42da-11ea-8fa0-eb521c1eb97a.png)

#### What result did you expect?
A simple error message with stack trace would suffice.

**Comment by hueniverse** [comment]
I can't reproduce this. Next time joi issues should go in joi...
