### ISSUE TITLE
Errors thrown by functions on request.app set by extension are resuting in request timeout rather than 500  

### ISSUE THREAD

**Issue by DamodarSojka** [hapijs/hapi#4037]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: v12.1.0
* *module version with issue*: 16.6.2
* *last module version without issue*: none
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): just hapi
* *any other relevant information*: none

#### What are you trying to achieve or the steps to reproduce?

I have an extension exposing a method during the onPreHandler phase: 
`req.app.exposedMethod = function() {};`

I am calling the exposedMethod within the route handlers, any errors thrown from within the exposedMethod are resulting in the request timeout in the browser rather than 500 as I would expect it to be.
Other logic within the extension point is working correctly.

#### What was the result you got?
Request timeout, no error logged

#### What result did you expect?
500 response and error to be logged

**Comment by hueniverse** [comment]
Cannot reproduce. See test.
