### ISSUE TITLE
server.validator(Joi) will not work as a plugin (but will otherwise)

### ISSUE THREAD

**Issue by Darmaiad** [hapijs/hapi#4038]
#### Support plan

* *which support plan is this issue covered by?* Community 
* *is this issue currently blocking your project?* no
* *is this issue affecting a production system?* no

#### Context

* *node version*: 12.14.1
* *module version with issue*: 19.1
* *last module version without issue*: N/A
* *environment*: node
* *used with*: Joi 17.1
* *any other relevant information*: Motivation: I want to find out if Glue is worthwhile to introduce at work.

#### What are you trying to achieve or the steps to reproduce?

I started making plugins out of everything. I had success with routes and authentication:
```js
export default {
    name: 'ApiRoutes',
    version: '1.0.0',
    register: (server) => server.route(routes),
};
export default {
    name: 'Authentication',
    version: '1.0.0',
    register: (server) => {
        server.auth.strategy('session', 'cookie', sessionConfiguration(server));
        server.auth.strategy('jwt', 'jwt', jwtConfiguration(server));
        server.auth.default({ strategies: ['session', 'jwt'] });
    },
};
```
Then I tried to create a simple plugin, just a wrapper around ```server.validator(Joi)```, like so:
```js
import Joi from '@hapi/joi';
export default {
    name: 'ValJoi',
    version: '1.0.0',
    register: (server) => server.validator(Joi),
};
```

#### What was the result you got?
Cannot set uncompiled validation rules without configuring a validator

#### What result did you expect?
To register Joi. 
Everything works when I call validator on the server object returned from ```Hapi.server()```, but not when the call is made from the plugin. 
I ensured that the plugin was first in the array for the register call, like so: 
```js
await server.register([ValJoi, ...Ecosystem, Authentication, ApiRoutes]);
``` 
(I even tried a separate server.register call).

**Comment by hueniverse** [comment]
The `validator()` method is sandboxed to each plugin. If you want to apply it to the entire server you need to apply it to the root. You can find it via `sever.realm.parent` (iterate until you reach the root - it will have no parent).

**Comment by k3n** [comment]
For anyone copy-pasting from the above comment, there's a typo -- should be `server.realm.parent`.
