### ISSUE TITLE
Change log "hapi.dev/resources/changelog" no updated

### ISSUE THREAD

**Issue by AndriiNyzhnyk** [hapijs/hapi#4039]
#### Context

* *node version*: 12.14.1
* *module version*:  19.0.5

#### What are you trying to achieve or the steps to reproduce ?

Run 
```js
npm i @hapi/hapi
```

The Hapi version will be 19.1.0 or 19.0.5(does not matter), go to "/hapi.dev/resources/changelog", the latest doc version was created for Hapi 19.0.4.

**Comment by hueniverse** [comment]
It just takes a few hours to update.
