### ISSUE TITLE
How to wrap a handler/pre-handler

### ISSUE THREAD

**Issue by jcchavezs** [hapijs/hapi#4049]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: 12
* *module version*: 17+
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*: this is for supporting a library

#### How can we help?

Currently we have an issue with hapi instrumentation when using promises. Usual instrumentation is based on middlewares and that allows us to wrap the next handlers with a scope. Hapi [has a different model](https://hapi.dev/tutorials/expresstohapi/?lang=en_US#plugins) based on listeners.

In *express* for example, one might do:

```js
  return function zipkinExpressMiddleware(req, res, next) {
     ...
     tracer.scoped(() => {
        ...
        next()
      })
  }
```

This means that everything in `next()` happens **scoped**. In hapi case, we subscribe to events `onRequest`, `onPreHandler`, `onPreResponse` but we can't actually wrap within a scope what happens in the handler (or pre handler). This code won't work for example:

```js
server.route({
    method: 'GET',
    path: '/',
    config: {
      pre: [
        {
          method: () => {
              return doCall()
          },
          assign: 'users',
        },
```

whereas this one will do the trick:

```js
server.route({
    method: 'GET',
    path: '/',
    config: {
      pre: [
        {
          method: (req) => {
            return tracer.scoped(function() {
              tracer.setId(req._trace_id) // restore the scope
              return doCall()
            })
          },
          assign: 'users',
        },
```

Is there any way we can wrap `handler` and `pre-handler`s without asking the user to specifically wrap the functions? If now, what is the recommended practice, should we extend Hapi server class and override the `server.route` method to do this wrapping?

For better context, this is the original issue in zipkin: https://github.com/openzipkin/zipkin-js/issues/483#issuecomment-583820036

**Comment by anuraaga** [comment]
@jcchavezs Looks like you're right, I read the comment in `hapiMiddleware.js` assuming it does something which it doesn't. I guess the comment isn't really valid, sent a PR to remove it to prevent confusion.

**Comment by jcchavezs** [comment]
Friendly ping @hueniverse

**Comment by hueniverse** [comment]
I don't know what it means to run inside the scope.

**Comment by hueniverse** [comment]
Closing this in favor of the original issue.
