### ISSUE TITLE
Expose (likely?) Content-Type on response object

### ISSUE THREAD

**Issue by btmorex** [hapijs/hapi#4051]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 12.15.0
* *module version*: 19.1.1
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...):
* *any other relevant information*:

#### What problem are you trying to solve?

I'd like to set some standard headers in an onPreResponse handler, but only for responses where Content-Type is set to text/html. It seems that Hapi already knows the likely Content-Type (assuming later code doesn't change it) via the private _contentType property. I'm using it, but it would be nice if it were part of the public API.

#### Do you have a new or modified API suggestion to solve the problem?

Either expose the Content-Type publicly on the Response object or add it to response.headers. I should mention that my expectation prior to reading the docs was that `response.headers['content-type']` would already be set.

**Comment by hueniverse** [comment]
The problem is that the internal content type is implied and can be changed. I need to look into it a bit to see how to expose the value but only if it is set explicitly by the user.
