### ISSUE TITLE
Joi version incompatibility

### ISSUE THREAD

**Issue by maximelkin** [hapijs/hapi#4054]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 10
* *module version*: 18
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*:

#### How can we help?

hapi v18 depends on Joi 15.x.x
All dependencies of hapi v18 depends on Joi 16.x.x
hapi-swagger v11.x also depends on 16.x.x

This setup causes swagger api or hapi server itself to break - because hapi/hapi requires me to use Joi 15.x.x and hapi-swagger Joi 16.x.x

Can you please support for hapi v18 joi 16.x.x?

**Comment by maximelkin** [comment]
Maybe backport 2cc43c0b32ccaaacdaa9cd0c120f166d65d743a4 ?

**Comment by Marsup** [comment]
See https://github.com/hapijs/joi/issues/2107#issuecomment-531543758.

**Comment by maximelkin** [comment]
Thanks!
