### ISSUE TITLE
What is the equivalent of forbiddenKeys in version 17.x.x?

### ISSUE THREAD

**Issue by averri** [hapijs/hapi#4055]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise):  Community
* *is this issue currently blocking your project?* (yes/no): Yes
* *is this issue affecting a production system?* (yes/no): No

#### Context

* *node version*: 12.
* *module version*:  "@hapi/joi": "17.1.0"
* *environment* (e.g. node, browser, native): Any
* *used with* (e.g. hapi application, another framework, standalone, ...): https://github.com/feathers-plus/validate-joi
* *any other relevant information*:

#### How can we help?

What is the equivalent of methods `requiredKeys`, `optionalKeys` and `forbiddenKeys` in Joi version 17?

Reference: https://hapi.dev/family/joi/api/?v=17.1.0#objectforbiddenkeyschildren

**Comment by dominykas** [comment]
I suspect you're looking to upgrade from pre-v16? If so - the release notes are here: https://github.com/hapijs/joi/issues/2037

**Comment by averri** [comment]
Hi @dominykas, yes, exactly that - I'm upgrading from v15 to v17, and I see the release notes:

> Remove requiredKeys(), optionalKeys(), and forbiddenKeys() (use fork() instead) (#1951)

How to rewrite this code using Joi v17?

```javascript
// Old code from Joi v15.
const newSchema =  schema.optionalKeys(fields)
```

**Comment by dominykas** [comment]
If I read the docs correctly - it's probably something like this:

```
const optionalSchema = schema.fork('username', (usernameSchema) => usernameSchema.forbidden());
```

Although you may also want to look into [`alter()`](https://hapi.dev/family/joi/api/?v=17.1.0#anyaltertargets)

**Comment by averri** [comment]
From the v17 docs:

> any.fork(paths, adjuster)
> Returns a new schema where each of the path keys listed have been modified where:
> 
> paths - an array of key strings, a single key string, or an array of arrays of pre-split key strings. Key string paths use dot . to indicate key hierarchy.
> adjuster - a function using the signature function(schema) which must return a modified schema. For example, (schema) => schema.required().
> The method does not modify the original schema.

So, it seems that this is the equivalent for v17:

```javascript
const schema = Joi.object().keys({ age: Joi.number(), username:  Joi.string() });
const optionalSchema = Joi.any.fork('username', schema => schema.forbidden());
```

**Comment by averri** [comment]
@dominykas, thank you so much!

**Comment by averri** [comment]
I have tested the new API and it's working fine, the upgrade is complete from v15 to v17.
