### ISSUE TITLE
Payload validation errors are still hitting handler

### ISSUE THREAD

**Issue by bsiddiqui** [hapijs/hapi#4056]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 12.12.0
* *module version*: 19.1.1
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*:

#### How can we help?

We are trying to upgrade form Hapi 16 => 19. Most of the transition has been pretty smooth (great changelogs) but something odd is that requests that fail payload validation are still making it to the handler.

I know the error response has is now more generic and we can use a `failAction` to customize the error response but the `failAction` handler isn't being triggered when validation fails (I've tried on the route and globally in the server config).

I know the payload is failing bc of the value of `request.payload` in the handler
```js
{ 
  error: Object // a Joi validation error
  value: Object // the request value
}
```

Also, I didn't see anything in the 17, 18, or 19 changelogs about the `request.payload` signature changing. It used to be a an object containing the payload but now it's `request.payload.value`. Did I miss something?

**Comment by hueniverse** [comment]
Something is wrong with your setup somewhere. Something seems to be catching errors and wraping them. The `request.payload` format has not changed. And payload validation works: https://github.com/hapijs/hapi/blob/master/test/validation.js#L685.
