### ISSUE TITLE
what's best practice? can you give me hapi  project generator?

### ISSUE THREAD

**Issue by anlexN** [hapijs/hapi#4057]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*:  latest
* *module version*:  latest
* *environment* (e.g. node, browser, native): node 
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*:

**Comment by aalimovs** [comment]
https://hapipal.com/

**Comment by hueniverse** [comment]
@anlexN you listed this as covered by a core support plan which I assume was a mistake as I don't see your name listed under a paying company contract. If I was wrong please let me know.

I suggest you visit the hapi.dev portal for links to many useful resources as well as link to the Slack channel where this kind of questions are better suited.
