### ISSUE TITLE
Joi.string().email() without options object returns Error: Built-in TLD list disabled

### ISSUE THREAD

**Issue by vanecgs** [hapijs/hapi#4059]
#### Context

* *node version*: v13.3.0
* *module version*: 17.1.0

#### What are you trying to achieve or the steps to reproduce ?

I have this validation scheme
```js
const loginSchema = Joi.object({
  email: Joi.string()
    .email()
    .required(),
  password: Joi.string().required(),
})
```
when validating I get **Error: Built-in TLD list disabled**. From the documentation https://hapi.dev/family/joi/api/?v=17.1.0#stringemailoptions I get that options are, well, optional. I tried passing `{ tlds: {allow: true} }` but I get the same error. After researching I found out that you removed tlds validation support in order to reduce your bundle, so maybe documentation needs update too.

**Comment by KhalidBhyan** [comment]
As per [the documentation](https://hapi.dev/family/joi/api/?v=17.1.0#stringemailoptions)

> tlds - options for TLD (top level domain) validation. By default, the TLD must be a valid name listed on the IANA registry. To disable validation, set tlds to false.

Means you must be specific and give a valid `tlds` option with a list of TLDs you want to validate, to disable this error message just do:
`email: Joi.string().email({ tlds: {allow: false} }) //.required() or any other method`

this will make Joi accepts any type of TLDs and continue your validation without any errors

**Comment by hueniverse** [comment]
You seem to be using the browser build of joi instead of the node version...

**Comment by sumer9999** [comment]
```
tlds: {
      allow: true,
    }
```
I tried the Node version of "joi": "^17.4.0", and still getting this issue.

Error: Built-in TLD list disabled

**Comment by devinivy** [comment]
@sumer9999 if you're using the browser build, then this is expected.  You can bring your own tlds from the same source joi uses in the non-browser version if you like.  This list lives here in @sideway/address: https://github.com/sideway/address/blob/master/lib/tlds.js

**Comment by dekatron** [comment]
@sumer9999 basically this:

```
import tlds from '/node_modules/@sideway/address/lib/tlds.js'

const loginSchema = Joi.object({
    email: Joi.string()
        .email({
            tlds: {
                allow: tlds
            }
        })
        .required(),
    password: Joi.string().required(),
})
```
Or you can maintain your own copy of the file / come up with your own list but if you do that you'll want to make sure any validation on the back-end uses the same list of TLDs so that you don't get something that passes on the front-end and fails on the back-end.

**Comment by NandoZee** [comment]
Note that @hapi/joi has been deprecated:
https://www.npmjs.com/package/@hapi/joi

For joi:
https://www.npmjs.com/package/joi

Through testing, I can confirm that `"@hapi/joi": "17.1.1"` will throw errors for TLDs as you've reported, whereas `"joi": "17.7.0",` does not. So your answer is to `npm uninstall @hapi/joi` and `npm i joi`.
