### ISSUE TITLE
when 16.8.2 version will available in npm registry?

### ISSUE THREAD

**Issue by Bodasia** [hapijs/hapi#4065]
#### Support plan

* *which support plan is this issue covered by?* Community
* *is this issue currently blocking your project?* yes
* *is this issue affecting a production system?* yes

#### Context

* *node version*: 8.17.0
* *module version*: 16.8.2
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*:

#### How can we help?

please publish version 16.8.2 to npm registry, thanks

**Comment by Marsup** [comment]
It is only available through a commercial license, which is all explained here: https://hapi.dev/support/.

**Comment by hueniverse** [comment]
Version 16 is only maintained under a commercial license. No new open source versions will be published. Please contact me if you have any questions about commercial support plans.
