### ISSUE TITLE
Additional meta property in route.options

### ISSUE THREAD

**Issue by alexsorinsky** [hapijs/hapi#4069]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: 13.8.0
* *module version*: 19.1.1
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi app
* *any other relevant information*:

#### What problem are you trying to solve?

I need to add any extra info about matched route directly from route configuration and keep it available from anywhere later (i.e. in onPreResponse)

```js
server.route({
	method: "get",
	path: "/",
	handler: ActionController.actionHandler,
	options: {
		// ... standard options

		meta: {
			pluginInfo: require("/some/path/package.json"),
			routeInfo: {
				someSpecialField1: "some value1",
				someSpecialField2: "some value2",
			}
			exrtaField1: ["extra", "values", 1],
			exrtaField2: ["extra", "values", 2],
		}
	}
})

// after in onPostHandler():

class ResponseExtender extends BaseExtenders {
	constructor(server, plugin) {
		this.server = server
		this.plugin = plugin
	}
	
	async onPostHandler(request, h) {
		
		// request.route.meta - previously provided any additional configuration object for the matched route (method: "get", path: "/")
		const routeInfo = request.route.meta

		// some post handler login goes here

		const metascreen = this.server.metascreen
		const result = "..."

		await metascreen.add(this.plugin.pluginName, result)
		
		return h.continue
	}
}

```

#### Do you have a new or modified API suggestion to solve the problem?

add new property **meta** to **route.options** object and expose it into **request.route.meta** after new request came and the corresponded route handler found

**Comment by hueniverse** [comment]
We already provide `app` for you to put in whatever you want.
