### ISSUE TITLE
typo in Community Support Plan description

### ISSUE THREAD

**Issue by jsoref** [hapijs/hapi#4071]
#### Context

* *node version*: N/A
* *module version*: N/A

#### What are you trying to achieve or the steps to reproduce ?

I'm trying to report a typo in https://github.com/orgs/hapijs/projects in the `Community Support Plan` description:
> Issues from community members without a commercial support plan. Will be resolved by available community resources. If _not_ free resources are available to help, the issue will be closed after 2 weeks.

This line should say:
If **no** free ...

**Comment by hueniverse** [comment]
Thanks.
