### ISSUE TITLE
CORS issue with google API 

### ISSUE THREAD

**Issue by xdrelos** [hapijs/hapi#4082]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no):yes
* *is this issue affecting a production system?* (yes/no):no

#### Context

* *node version*: 12.16.1
* *module version*: 12
* *environment* (e.g. node, browser, native): node , browser
* *used with* (e.g. hapi application, another framework, standalone, ...):hapi application
* *any other relevant information*:

#### How can we help?

Hello i am having  some issues to implement properly bell and google signin. I am pretty junior so please forgive me if i mistate things. I use https://developers.google.com/identity/sign-in/web/server-side-flow, and the example from bell for the backend. It seems i have a response from google API but then i have a CORS error that blocks me:

Access to XMLHttpRequest at 'https://accounts.google.com/o/oauth2/v2/auth?client_id=914091897182-m38hh6r2t4nhur4fgs1dn7v790l0bvrr.apps.googleusercontent.com&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fbell%2Fdoor&state=H7e-8hlMh3v857AsZVOk3f&scope=profile%20email' (redirected from 'http://localhost:3000/bell/door') from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

My route (the server.auth.strategy is the same as in the bell example for google with my secrets.)
```js
server.route({
        method: '*',
        path: '/bell/door',
        options: {
            cors: {
                origin: ['*'],
                additionalHeaders: ['cache-control', 'x-requested-with']
            },
            auth: {
                strategy: 'google',
                mode: 'try'
            }
        },
        handler: function (request, h) {
            //console.log(request);
            if (!request.auth.isAuthenticated) {
                return 'Authentication failed due to: ' + request.auth.error.message;
            }

            return '<pre>' + JSON.stringify(request.auth.credentials, null, 4) + '</pre>';
        }
    });
```
The frontend (using pug) part 1:
```js
script(src='//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js')
    script(src='https://apis.google.com/js/client:platform.js?onload=onLoadCallback' async defer)
    script.
        window.onLoadCallback = function start() {
            gapi.load('auth2', function() {
                auth2 = gapi.auth2.init({
                    client_id: '914091897182-m38hh6r2t4nhur4fgs1dn7v790l0bvrr.apps.googleusercontent.com',
                    // Scopes to request in addition to 'profile' and 'email'
                    //scope: 'additional_scope'
                });
            });
        }
```
The frontend (using pug) part 1:
```js
script.
        function signInCallback(authResult) {
            if (authResult['code']) {

                // Hide the sign-in button now that the user is authorized, for example:
                $('#signinButton').attr('style', 'display: none');
                alert(authResult['email']);
                // Send the code to the server
                $.ajax({
                    type: 'POST',
                    url: 'http://localhost:3000/bell/door',
                    // Always include an `X-Requested-With` header in every AJAX request,
                    // to protect against CSRF attacks.
                    headers: {
                        'X-Requested-With': 'XMLHttpRequest'
                    },
                    contentType: 'application/octet-stream; charset=utf-8',
                    success: function (result) {
                        // Handle or verify the server response.
                        alert('success');
                    },
                    processData: false,
                    data: authResult['code']
                });
            } else {
                // There was an error.
                alert('error');
            }
        }
```
I am not sure if i implement it badly or what but i cannot find the issue

**Comment by xdrelos** [comment]
up i am still blocked. hope someone can help me:)

**Comment by thihathit** [comment]
Tried `cors: true` ?

**Comment by xdrelos** [comment]
Thank you I already tried cors: true without success

**Comment by hueniverse** [comment]
Unfortunately, no community resources were available to help resolve this issue after two weeks, and it is being closed. We close unresolved community issues to keep the issue tracker organized and effective. Please check https://hapi.dev/support for other support options.
