### ISSUE TITLE
Hapi 18.4.1 Failaction throw 500 error 

### ISSUE THREAD

**Issue by anuraggupta816** [hapijs/hapi#4084]
<!--
In Route i Call failaction method & throw 500 error instead of 400. I am sending 400 error but gives 500 eror .

**Comment by anuraggupta816** [comment]
Router

 {
  method: 'POST',
  path: '/api/v1/customer/registration',
  handler: function (request, reply) {
    return Controller.CustomerController.registration(request.payload).then(response =>{ //console.log("response",response);
      return  UniversalFunctions.sendSucces(null, response)  ;   
    }).catch(error => { //console.log("error",error); 
        return UniversalFunctions.sendError(error) ;  
    });
  },
  config: {
    description: 'Login Via Email & Password For  customer',
    tags: ['api', 'Customer'],
    validate: {
      payload: {
        firstName: Joi.string().regex(/^[a-zA-Z ]+$/).required().trim(),
        lastName: Joi.string().regex(/^[a-zA-Z ]+$/).required().trim(),
        email: Joi.string().email().required(),
        mobileNumber : Joi.string().regex(/^[0-9]+$/).required().trim(),
        countryCode:Joi.string().required().trim(),
        password: Joi.string().required().min(5).trim(),
        deviceType: Joi.string().required().valid([DEVICE_TYPES.IOS,DEVICE_TYPES.ANDROID]),
        deviceToken: Joi.string().trim(),          
      },
      failAction: UniversalFunctions.failActionFunction
    },
    plugins: {
      'hapi-swagger': {
          payloadType : 'form',
          responseMessages: APP_CONSTANTS.swaggerDefaultResponseMessages
      }
    }
  }
}

**Comment by osukaa** [comment]
Do you have an example of the request you're making to the described route?
