### ISSUE TITLE
Serving Static Content install command correction?

### ISSUE THREAD

**Issue by 2point0** [hapijs/hapi#4085]
#### Context

* *node version*: v12.16.1
* *module version*: 6.13.4

#### What are you trying to achieve or the steps to reproduce ?

```js
const some = 'properly formatted code example';
```
The [Serving Static Content](https://hapi.dev/tutorials/servingfiles/?lang=en_US) page says to install inert with `npm install inert`. Shouldn't it be `npm install @hapi/inert`?

**Comment by 2point0** [comment]
If so the code snippets need to be updated to `@hapi/` as well.

**Comment by jonathansamines** [comment]
@2point0 Static content tutorial was updated at [#346](https://github.com/hapijs/hapi.dev/pull/346)

**Comment by 2point0** [comment]
See linked issue
