### ISSUE TITLE
Does hapi v17.x actually support Node.js 12?

### ISSUE THREAD

**Issue by watson** [hapijs/hapi#4093]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 12.16.2
* *module version*: 17.6.0
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*: none

#### How can we help?

According to #3898, in Node.js 11+ the `close` event on incoming requests will trigger a `disconnect` from hapi in versions of hapi lower than v18. But according to the hapi [Module Status page](https://hapi.dev/resources/status/), version 17 should support Node.js 12.

I discovered this because I'm upgrading a hapi 17.6.0 project from Node.js 10 to Node.js 12 and all of a sudden all these `disconnect` error events started happening.

What I already tried:
- I tried to manually port the commit a3a5ca97181a99cc06652a1f45579539cceb7d4a and 03e03dc955018b07fe248252b9ce680c30d2bc38 to a local fork of v17.6.0, but that still didn't make it work 100%
- I tried to upgrade to v17.9.2 to see if this issue had been fixed in a newer 17.x version, but no dice.

Questions:
1. Am I correct in assuming that ^17.6.0 isn't compatible with Node.js 12?
1. If so, how come the Module Status page says so?
1. Is there a workaround that doesn't involve upgrading to v18.x? (I will upgrade eventually, but it's a huge task, that I'd rather hold off on until after the Node.js upgrade)

**Comment by hueniverse** [comment]
This was a bug in hapi 17 under node 12. It doesn't mean the combination doesn't work, just that it will generate a lot more noise - it's a bug, not a breaking change. This bug in v17 is not going to be fixed because the version is no longer supported. If you need this fixed under v17, your options are to fork and figure out a patch yourself (which you have started) or get a commercial support plan that includes v17.
