### ISSUE TITLE
Control API Access (All or nothing would suffice)

### ISSUE THREAD

**Issue by bonbonio** [hapijs/hapi#4096]
#### Support plan

Community
* *is this issue currently blocking your project?* (no):
* *is this issue affecting a production system?* (no):

#### Context

* *node version*: 12.16.1
* *module version*: Latest
* *environment* (e.g. node, browser, native): Node/ReactJS
* *used with* (e.g. hapi application, another framework, standalone, ...): NextJS
* *any other relevant information*: Deployed on AWS Elastic Beanstalk

#### How can we help?
Is it possible to restrict calls to the API to come from a specific domain or IP? I was considering adding an access token to prevent others using, but I already use the Authorization Bearer for a JWT for the user level access. I don't need granular control.

I just want it to my API could only be consumed by www.example.com or example.com... ideally...

Anyone else found an elegant solution for this? The site front end is ReactJS with NextJS.

**Comment by hueniverse** [comment]
There is no native hapi api to do this. There might be plugins available but I'm not familiar with any. It would pretty simple to write an onRequest extension method that does that.
