### ISSUE TITLE
small Email validation bug

### ISSUE THREAD

**Issue by noodle-lover** [hapijs/hapi#4097]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Joi community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 12.16.2 
* *module version with issue*:@hapi/joi@17.1.1 
* *last module version without issue*: None
* *environment* (e.g. node, browser, native): node on ubuntu desktop 
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*: Similar issues on other frameworks/languages https://stackoverflow.com/questions/12355858/how-many-symbol-can-be-in-an-email-address  

https://github.com/wtforms/wtforms/pull/427

#### What are you trying to achieve or the steps to reproduce?

```js
const Joi = require('@hapi/joi')

const schema = Joi.object({
    email: Joi.string().email()
})

const {error, value} = schema.validate({ email: "'user@something' @example.com"})

if(error)
    console.log(error.details[0].message)
else
    console.log(value)
```

#### What was the result you got?
"email" must be a valid email
#### What result did you expect?
{ email: 'user@something@example.com' }

**Comment by hueniverse** [comment]
First, this is the wrong place to open this issue. It belongs in the joi or address repos. Second, the email provided is invalid because you have to use double quotes to enquote the local part of the email. Third, enquoted emails are not supported and will always fail.
