### ISSUE TITLE
can omit the dependency after a plugin is registed in a plugin?

### ISSUE THREAD

**Issue by atmjs** [hapijs/hapi#4100]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): core
* *is this issue currently blocking your project?* (yes/no):no
* *is this issue affecting a production system?* (yes/no):no

#### Context

* *node version*: 12.6.2
* *module version*: 19.1.1
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...):hapi application
* *any other relevant information*:no

#### How can we help?
In the following code, can I omit the 'foo-plugin' in server.dependency()

```js
exports.plugin = {
  name: 'some-plugin',
  version: '1.0.0',
  async register(server, options) {
    await server.register(require('foo-plugin'));
    server.dependency(['foo-plugin', 'bar-plugin'], async () => {
      // some code
    });
  },
};
```

**Comment by devinivy** [comment]
Yes, you can omit it.  The best way to ensure a dependency is registered is to register it yourself, just as it is done in this example.  The second best way to ensure a dependency is registered is to use `server.dependency()` and schedule `// some code` to be run during initialization (`await server.initialize()`) or start (`await server.start()`).  Note that the dependency above is pretty much identical to:
```js
server.ext('onPreStart', async () => {
  // some code
}, {
  after: ['foo-plugin', 'bar-plugin']
});
``` 

Except it also ensures during initialization that those plugins have been registered.  For more information, there is a detailed writeup on plugin dependencies here: https://hapipal.com/best-practices/handling-plugin-dependencies

**Comment by atmjs** [comment]
@devinivy Thanks!
