### ISSUE TITLE
any.describe() does not work in a browser

### ISSUE THREAD

**Issue by whitelizard** [hapijs/hapi#4102]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise):
Community
* *is this issue currently blocking your project?* (yes/no):
yes
* *is this issue affecting a production system?* (yes/no):
no

#### Context

* *node version*: 
13.0.1
* *module version with issue*: 
17.1.1
* *last module version without issue*: 
Donno
* *environment* (e.g. node, browser, native): 
Browser
* *used with* (e.g. hapi application, another framework, standalone, ...):
Standalone
* *any other relevant information*:
Issue appears in both newest Firefox & Brave

#### What are you trying to achieve or the steps to reproduce?

Trying to use `.describe()` on a Joi schema. In a browser.

```bash
npm i @hapi/joi
```

```javascript
// in script built into a webpage, see sandbox example link
import Joi from '@hapi/joi';

Joi.string().describe();
```

[https://codesandbox.io/s/priceless-brook-qj5xt?file=/src/index.js](https://codesandbox.io/s/priceless-brook-qj5xt?file=/src/index.js)

#### What was the result you got?

In own project:
```
joi-browser.min.js:1 Uncaught Error: Manifest functionality disabled
    at new e.exports (joi-browser.min.js:1)
    at e.exports (joi-browser.min.js:1)
    at Base.describe (joi-browser.min.js:1)
    at Module../src/index.js (index.js:6)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Object.1 (index.js:62)
    at __webpack_require__ (bootstrap:784)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1
```

In sandbox example:
```
Error
Manifest functionality disabled
▶ 3 stack frames were collapsed.
evaluate
/src/index.js:3:33
  1 | import Joi from "@hapi/joi";
  2 | 
> 3 | const schemaDescr = Joi.string().describe();
    |                                 ^
  4 | 
  5 | // document.getElementById("app").innerHTML = JSON.stringify(schemaDescr, null, 2);
  6 | 
View compiled
▶ 16 stack frames were collapsed.
```

The same code runs fine in Node.js.

#### What result did you expect?

A JS object structure according to the API description.

**Comment by dreamsinspace** [comment]
@whitelizard You should open this in @hapi/joi. `describe()` is stripped off from the browser build, probably to reduce the bundle size...

**Comment by whitelizard** [comment]
> @whitelizard You should open this in @hapi/joi. `describe()` is stripped off from the browser build, probably to reduce the bundle size...

Oh damn. I thought I was in the right place. Thanks.
