### ISSUE TITLE
package ca.uhn.fhir.context does not exist

### ISSUE THREAD

**Issue by jayviola** [hapijs/hapi#4103]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community): 
* *is this issue currently blocking your project?* (yes):
* *is this issue affecting a production system?* (yes):

#### Context

* *node version*: 
* *module version*: 3.7
* *environment* (e.g. browser): 
* *used with* (e.g. hapi application):
* *any other relevant information*:

#### How can we help?

I am having troubles building my project with the FHIR context package. The picture below shows the error i am getting. I am sure I properly installed my software as well as downloading the appropriate library. I need help !

```js
const some = 'properly formatted code example';
```
![image](https://user-images.githubusercontent.com/66642086/84069450-8b92d380-a998-11ea-9126-b95beee9de3d.png)

**Comment by hueniverse** [comment]
You are in the wrong repo. This has nothing to do with your project.

**Comment by wswoodruff** [comment]
I think there's another hapi out there built for dotnet @jayviola perhaps this repo or something under their umbrella? https://github.com/FirelyTeam/fhir-net-api

**Comment by jayviola** [comment]
> I think there's another hapi out there built for dotnet @jayviola perhaps this repo or something under their umbrella? https://github.com/FirelyTeam/fhir-net-api

Thank you!
