### ISSUE TITLE
Track cache policies

### ISSUE THREAD

**Issue by jonathansamines** [hapijs/hapi#4104]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise):  Community
* *is this issue currently blocking your project?* (yes/no): No
* *is this issue affecting a production system?* (yes/no): No

#### Context

* *node version*: Node 12
* *module version*: Hapi 19
* *environment* (e.g. node, browser, native): Node
* *used with* (e.g. hapi application, another framework, standalone, ...): Hapi application
* *any other relevant information*: No

#### What problem are you trying to solve?
We are trying to build a general introspection mechanism for all hapi applications cache, similar to [spring boot's actuator](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints) endpoints, allowing consumers to:

+ [List all available cache names](https://github.com/spring-projects/spring-boot/blob/v2.3.1.RELEASE/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/cache/CachesEndpointWebExtension.java#L43)
+ [Get details about a particular cache stats](https://github.com/spring-projects/spring-boot/blob/v2.3.1.RELEASE/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/cache/CachesEndpointWebExtension.java#L43)
+ [Drop cached data](https://github.com/spring-projects/spring-boot/blob/v2.3.1.RELEASE/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/cache/CachesEndpointWebExtension.java#L55)

With the existing public API's we have not been able to list all available cache policies created by the framework, either directly through [server methods](https://hapi.dev/api/?v=19.1.1#server.method()) or indirectly by using the [server.cache](https://hapi.dev/api/?v=19.1.1#server.cache()) functionality on plugins

So far, by making use of existing public API's we have been able to:

##### Server methods
We could iterate over [server.methods](https://hapi.dev/api/?v=19.1.1#server.methods) and use the currently exposed `.cache` property to get the policy `stats` and `drop` methods.

###### Get existing cache policies tracked by server methods

```javascript

function getMethodName(ns, methodName) {
  const nsf = ns.length ? `${ns}.` : ns;

  return `${nsf}${methodName}`;
}

function getMethodsStats(ns, stats, methods) {
  for (const [methodName, methodFn] of Object.entries(methods)) {
    // server method without namespace
    if (typeof methodFn === 'function') {
      // not all server methods have a cache available
      if (methodFn.cache) {
        stats[getMethodName(ns, methodName)] = methodFn.cache.stats;
      }
    } else {
      // namespaced server methods
      getMethodsStats(getMethodName(ns, methodName), stats, methodFn);
    }
  }

  return stats;
}
```

###### Get a particular server method caching policy
```javascript
const method = Hoek.reach(server.methods, 'segment-name');

if (method && method.cache) {
  return method.cache.drop('key');
}
```

##### Plugins
Unfortunately, a large source of application cache policies often comes from external plugins (e.g [yar](https://hapi.dev/module/yar/)) and while some of them expose their cache policies, is not practical to expect each plugin author to expose their policies and manually keep track of them.

#### Do you have a new or modified API suggestion to solve the problem?
The framework could automatically keep track of all cache policies created by using `server.cache` and expose them through a single `server.caches` property.

```javascript
const cache = server.cache({ segment: 'countries', expiresIn: 60 * 60 * 1000 });
const policy = server.caches.countries;

assert(cache === policy);
```

With that API in place, we could create some API endpoints to introspect the cache policies:

##### List all cache policy's stats
```javascript
server.route({
  method: 'GET',
  path: '/actuator/cache',
  handler() {
    const stats = {};

    for (const [segmentName, cachePolicy] of Object.entries(server.caches)) {
      stats[segmentName] = cachePolicy.stats;
    }

    return stats;
  }
});
```

##### Drop a cache key

```javascript
server.route({
  method: 'GET',
  path: '/actuator/cache/{segment}/{key}',
  handler(request) {
    if (server.caches[request.params.segment]) {
        return server.caches[request.params.segment].drop(request.params.key);
    }

    throw Boom.notFound('cache policy segment or key not found');
});
```

**Comment by hueniverse** [comment]
This sounds like a good idea. Unfortunately due to the current uncertainty of future work it will not be added for the time being. I'll leave it open just in case.

**Comment by jonathansamines** [comment]
This was introduced in #4219. As part of the `@hapi/hapi@20.1.0` release
