### ISSUE TITLE
Dynamically remove route

### ISSUE THREAD

**Issue by WebMatrixware** [hapijs/hapi#4106]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v12.16.1
* *module version*: 19.1.1
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*:

#### What problem are you trying to solve?

I have a utility site that I configure routes and information on dynamically via a .yml file. I want to allow users to edit the file in the browser and get changes without having to stop and restart the service (since you do not know who else is using it at the moment). I am currently dynamically adding routes successfully based on the re-loaded .yml config file, but when a route is either removed or modified my current option is to stop and restart the server loading the modified config from scratch. 

While my particular use case is rather an edge case, I can see a number of scenarios where dynamically managed routes would be useful. We have half of that equation now with dynamic route additions, but without the ability to delete them we cannot remove or modify routes effectively (modify is most easily implemented by allowing removal and replacement).

#### Do you have a new or modified API suggestion to solve the problem?

I would suggest two new methods.
1) `Server.lookup(id).remove()`
2) `Server.match(method, path, [host]).remove()`

Both of these should return true if the route is found and deleted and false if it is not found and deleted. The deletion process should stop the route from taking any new requests, wait for any active requests to complete, and then remove the route from the server object.

**Comment by devinivy** [comment]
There are a couple alternative options to achieve that:
 - You can add an extension that short-circuits requests to "removed" routes.  This is the approach taken by [lobotomy](https://github.com/outmoded/lobotomy).
 - You can use a proxy server that watches for changes, starts a fresh hapi server based upon the new config, and gracefully stops the stale/old hapi server.

**Comment by WebMatrixware** [comment]
> There are a couple alternative options to achieve that:
> 
> * You can add an extension that short-circuits requests to "removed" routes.  This is the approach taken by [lobotomy](https://github.com/outmoded/lobotomy).
> * You can use a proxy server that watches for changes, starts a fresh hapi server based upon the new config, and gracefully stops the stale/old hapi server.

Those were basically the options I was working through in my head before I opened the request.

The first one is insufficient since it either only allows you to block requests to "removed" endpoints, but not update their functionality, or if you go far enough to be able to update functionality as well you are basically recreating the route handling engine which seems overly complex for the use-case and would require a significant exposure to errors and bugs that have already been found and fixed in the existing implementation over the course of time.

The second option is one of half a dozen ways to handle the changes and restart the server, which is what I am doing already. This is exceedingly slow, inelegant, and will always does not fix any of the core problems of the difficulty of shutting down routes without hosing users of the service, it just makes them not hapis issue rather than seeking to resolve them in the routing engine.

I appriciate the feedback, but what I was really asking was if there was any interest in seeing the API be updated along the lines of what I suggested. I am not sure my skills are up to it, but I would be willing to take a stab / help someone who knows more than I do work on adding this if it's an option.

**Comment by hueniverse** [comment]
I am not interested in adding functionality to remove routes. The work is mostly in the router which is complicated enough.
