### ISSUE TITLE
Add information about failing route when starting server

### ISSUE THREAD

**Issue by Ginden** [hapijs/hapi#4107]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise):  Community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 10.15.3
* *module version*: 18.4.1 
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone?
* *any other relevant information*:

#### What problem are you trying to solve?

I have bug in definition of route. I don't know where it is and what it is. Currently, Hapi gives you error without any details. Eg. I got error `Invalid schema content: (externalCustomerId.$_root.alternatives)`.

I was able to pinpoint issue with monkey-hacking `_setupValidation` in `route.js` file.

#### Do you have a new or modified API suggestion to solve the problem?

I would like for Hapi to append information about route that failed validation as `route` property on error object.

**Comment by cjihrig** [comment]
hapi already does this to some extent. For example:

```
Error: Invalid route options (GET ) {
  "method": "GET",
  "pat": "/",
  "handler": (request, h) => {\n      return 'Hello World!';\n    },
  "path" [1]: -- missing --
}

[1] "path" is required
```

Please provide your route config.

**Comment by kanongil** [comment]
This is already done, so we need details about the specific issue to resolve it. Closing it for now.
