### ISSUE TITLE
The future of the hapi project

### ISSUE THREAD

**Issue by devinivy** [hapijs/hapi#4113]
👋 Hey all— I'm here to represent this crew that Eran has been referring to (see also #4111).  We're here to carry hapi into 2021 and beyond, and we want to share our vision with you.  Let me first say that we are feeling very positive about the future of the framework and are energized to work on it, in some cases with material backing by our employers.

Our group consists principally of core team members (former lead maintainers of hapi's direct dependencies), and members of the original team that built hapi at Walmart.  It is heartening to see so much support pouring out right now— many folks have made it clear that they are interested in spending time contributing to the framework.  We want to enable that: this is completely in line with our plans and we look forward to making hapi more of a community effort, but more on that later.

Within this small group you will find a former hapi Community Lead and Chief Architect at npm; a member of the Node.js TSC and libuv maintainer; several engineers working on major projects at Joyent; the finger that famously pressed "the button" on Walmart's Black Friday hapi deployment; several who provide B2B services utilizing the framework; and the creator of hapi pal, an entire sub-ecosystem of hapi.  We lived hapi's history, we are aware of the pain points and blind spots, we understand all that there is to love about the framework, and we know you.  Perhaps more importantly, if you've been active in the community then you probably know us!  Here we are:

 - Devin Ivy (@devinivy)
 - Jonas Pauthier (@nargonath)
 - Lloyd Benson (@lloydbenson)
 - Nathan LaFreniere (@nlf)
 - Wyatt Lyon Preul (@geek)
 - Colin Ihrig (@cjihrig)

This group of seven constitutes hapi's initial Technical Steering Committee (TSC).  Yes that's right, we're going to have a TSC!  That means that _for the first time hapi is going to be taking a more distributed, community-driven approach to governance_, in a similar vein to the Node.js organization.  It is the TSC's job to provide technical direction, onboard collaborators, and facilitate consensus-seeking within the community.  For practical reasons there is a smaller leadership team with exclusive rights to publishing new module versions: Colin, Nathan, and myself.

It's not all about making changes, though.  To begin our focus will be to establish stability in maintenance and governance, making only minor adjustments along the way to achieve that goal.  We'll be working closely with Eran leading up to the moment he steps away from hapi maintenance, and at that point we will release a new major version, more so to signal to the community this change in leadership than to make any significant API adjustments.  Here are some things that we intend to keep, not necessarily an exhaustive list:

 - Stability: _no, we're not here for a rewrite._
 - No external dependencies: _this organization remains a safe haven from the broader node ecosystem._
 - 100% code coverage: _we aim to hit all code branches with integration-style tests._
 - Security disclosure policy: _we will continue to encourage and practice responsible disclosure._
 - Close following of semver: _if there is a breaking change, we'll make sure you know about it._
 - Quality of release notes and migration guides: _when there are changes, we won't leave you hanging._

We want to keep what's making hapi what it is today but we also have visions for the future for what hapi could become. We're looking forward to all the cool stuff we'll be adding to the project and we're excited for you to help us with that.

And for now that is the "short" of it.  Hopefully this gives you a much better sense of who is working to carry hapi forward and what to expect.  We understand that there are likely lots of questions coming our way.  It is still relatively early in this process and there are still many details to work out, but we will try to speak to those to the best of our ability at this time!  Please bear in mind this is still open source, and while we will have some employer support in the near future, this is still a community effort with lots of personal time invested as well.

That is all for now!  Expect to hear more in the coming weeks and months— we hope you'll be there with us.

Note: you can find more information about legacy commercial support [here](https://github.com/hapijs/hapi/issues/4114).

**Comment by wswoodruff** [comment]
I love that there's such a well-formed community effort with great people AND what seems like a blessing from Eran! This couldn't have turned out better I don't think! Love y'all! ❤️ ❤️ ❤️

**Comment by patlehmann1** [comment]
Thanks again for this update. As someone who works for a company that uses the hapi ecosystem extensively, this has been very reassuring. I hope to be able to contribute in any way that I can in the future!

**Comment by DiegoRBaquero** [comment]
Really happy about this. Wondering how GitHub sponsorships will change in 2021? Hopefully by that moment an organization can sponsor another org. Congrats to this initial TSC and thank you! Stay safe and love from Colombia ❤️

**Comment by keerthivasan-r** [comment]
This news is really a big relief for me since I'm a big fan of @hapijs ecosystem. Thanks for the efforts. Looking forward to contribute in any manner ❤👍

**Comment by Icehunter** [comment]
Great to hear! @devinivy let me know if there's anything I can do to help as well; I can give about 5-10 hours a week depending on the week.

**Comment by danielkokott** [comment]
Great news!! Hapi is my preferred web framework and ecosystem. Thank you everyone.

**Comment by afgallo** [comment]
**THIS** warms up my ❤️ !

Thank you, thank you, thank you @devinivy, @Nargonath, @lloydbenson, @nlf, @petreboy14, @geek and @cjihrig!!

**Comment by tk120404** [comment]
Opensource community rocks. :1st_place_medal: it never lets you down :100:

**Comment by export-mike** [comment]
💯 Whoop! 👍 thats a relief!

**Comment by hiddenboox** [comment]
Good news!

**Comment by Samueljoli** [comment]
We are definitely in great hands. 🏅 💯 🏅

**Comment by foxdonut** [comment]
Congratulations @devinivy and team, wish you all the best for continued success!

**Comment by mw-felker** [comment]
Incredible news @devinivy and everyone! So hapi to see this project continuing and excited that this amazing community can continue to flourish.

**Comment by ozum** [comment]
This is really great. I'm very happy to see such a great piece of software (or art) is in the hands of great people. Thank you for all previous work and future efforts.

**Comment by ottoo** [comment]
Great! Big fan of Hapi.

**Comment by bodawei** [comment]
Fantastic!

**Comment by urbantumbleweed** [comment]
This is one of the first frameworks I got work with as I got started with Javascript.  I am glad to see this project getting community love all these years later

**Comment by tindecken** [comment]
That's a good news. Thanks.

**Comment by TinaHeiligers** [comment]
Great news! Hats off to the brave souls!

**Comment by anlexN** [comment]
i am very sure that wonderful things are not belong to someone, some company. they are belong to all the world.

**Comment by manju4ever** [comment]
This is so lovely. Love ya all for your dedication and time.

**Comment by cjihrig** [comment]
v20 is out. The future is here.
