### ISSUE TITLE
Commercial License

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#4114]
### Running open source versions of hapi prior to v20 are a technical and legal liability due to known bugs and security issues

* **If you are on version v20 or newer, you are all set, no need to read further.**
* If you are able to **upgrade to version v20 or newer**, that is your **best option** and it's completely free and open source.
* If you are unable or unwilling to upgrade to version v20, you should seriously consider a commercial license as **every published open source version of hapi prior to v20 has known bugs and security issues** only patched in the commercial distributions.

The new project leadership is fantastic and includes the best people for the job. They have my full trust and support and so should you. While I'm happy to sell you a commercial license, the best thing to do is upgrade to the latest free open source version which is v20 or newer.

## Background

The hapi project changed leadership from being maintained by Eran Hammer (me) to a new technical steering committee composed of veteran hapi contributors. This change was acknowledged with the release of hapi v20.0.0 (which is identical to v19.2.0).

All hapi users are encouraged to upgrade to v20 as soon as possible. It contains the best features, bug fixes, and security patches. It is the only supported open source licensed version.

## License Goals

A paid commercial license for versions v16, v17, v18, and v19 is being offered exclusively by Eran Hammer, the framework creator and previous lead maintainer.

The commercial license is offered to:
- allow companies to evaluation their options moving forward without a hard deadline.
- allow companies to stay on their current version of hapi (v16 - v19) due to lack to upgrade resources, product roadmap, or usage in a finished product or a product that is nearing its natural end-of-life.
- help cover on-going open source development cost of **joi** which was moved out of the hapi ecosystem.

The commercial license is **not** offered to:
- sponsor or support the hapi community - all funds will go exclusively to Eran Hammer, and will not help support future work on the hapi open source project. If you want to support hapi, this is not the right way to do it!
- provide access to any other services related to hapi - the commercial license is just that, a license granting access to use the hapi commercial distributions. It does not include any other professional services, priority support, custom development, etc.

What to expect from the commercial distributions:
- well maintained code that is free of **known** security issues and severe defects.
- tested and verified on the current LTS versions of node.

Companies paying for a commercial license can request non-critical bug fixes be ported to a covered version. While such requests are not guaranteed, they will be accomodated based on the compatibility of the fix with the legacy code base.

## Cost

The commercial license is offered on a monthly or annually basis.

For terms starting before January 1st, 2021:
Monthly: $500/month
Annually: $5000/year

For terms starting on or after January 1st, 2021 and before January 1st, 2022:
Monthly: $750/month
Annually: $8000/year

For terms starting on or after January 1st, 2022: Plan pricing published at that time

Discounts may be available on an individual basis.

## Legal

The commercial license can be best described as a "paid BSD". Any version published under the commercial distribution channel before or during a paid term is covered under the BSD-3-Clause license. This means that once you pay, the code you get is open source under the BSD-3-Clause terms. Newer versions published after you stop paying are no longer available to you, but any version published before or during the paid periods are yours to keep as open source.

The full legal terms can be found in the [license agreement](https://github.com/hapijs/hapi/files/4921400/Sideway.2.0.pdf).

Please let your legal team know that the license terms are not open to negotiation. They have already been reviewed and accepted by major corporations.

## Logistics

To purchase a commercial license please contact sales@sideway.com. Sideway Inc. can produce the necessary invoices and accept payments via:
- PayPal
- Direct deposit / wire
- GitHub sponsorship

**Comment by anlexN** [comment]
money is cumbrance
