### ISSUE TITLE
Error with Vision plugin

### ISSUE THREAD

**Issue by CarmenVigo** [hapijs/hapi#4124]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): Yes.
* *is this issue affecting a production system?* (yes/no): Yes.

#### Context

* *node version*: v.12.14.0
* *module version*: 19.2.0
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi app
* *any other relevant information*: -

#### How can we help?

I am currently developing an application with Vision but when I compile it I get the following _Error Error: Invalid register options  "value" must be of type object_
I have declared it the way you state in the documentation and haven't found a solution.
```
const Hapi = require('@hapi/hapi');
const Vision = require('@hapi/vision');

server.register(Vision, (err) => {
    server.views({
        engines: {
            html: require('handlebars')
        }
    });
});
```
Before registering the plugin like that I had:
```
const Hapi = require('@hapi/hapi');
const Vision = require('@hapi/vision');

    server.register(Vision);
    server.views({
        engines: {
            html: require('handlebars')
        }
    });

```
But that got me a different error :
_Error Error: Invalid plugin options  {_
  _"plugin": {_
    _"register" [1]: -- missing --_
  _}_
_}_

_[1] "plugin.register" is required_

I would be grateful if you could help me solve any of the two errors.

**Comment by cjihrig** [comment]
I think the problem is that you're missing `await`. Check out the example registrations in the `vision` tests: https://github.com/hapijs/vision/blob/master/test/index.js#L53-L58

**Comment by CarmenVigo** [comment]
Thank you for your quick reply.
I have just followed your instructions so now my code is this one:
```
const server = Hapi.server();
await server.register(Vision);
server.views({
     engines: { html: require('handlebars') },
     path: './views',
     layoutPath: './views/layout',
});
```

but the error

_Error Error: Invalid plugin options {_
_"plugin": {_
_"register" [1]: -- missing --_
_}_
_}_

_[1] "plugin.register" is required_

persists.

**Comment by cjihrig** [comment]
I threw this together quickly, but it seems to work:

```js
'use strict';
const Hapi = require('@hapi/hapi');
const Vision = require('@hapi/vision');

async function main() {
  const server = Hapi.server();
  await server.register(Vision);
  server.views({
    engines: { html: require('handlebars') }
  });
  await server.start();
  console.log('server started');
}

main();
```

**Comment by devinivy** [comment]
I suggest following your stacktrace!  I have a hunch that error might be from a different plugin that you are trying to register.

**Comment by CarmenVigo** [comment]
Thank you very much, now it's working :)
