### ISSUE TITLE
{"statusCode":400,"error":"Bad Request","message":"Payload content length greater than maximum allowed: 1048576"}

### ISSUE THREAD

**Issue by AdvenDeep** [hapijs/hapi#4126]
#### Support plan

* *is this issue currently blocking your project?* (yes/no):yes
* *is this issue affecting a production system?* (yes/no):no

#### Context

* *node version*: v10.16.0
* *module version*: "@hapi/boom": "^7.4.2","@hapi/wreck": "^15.1.0","hapi": "16.4.3",
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...):
* *any other relevant information*:

#### How can we help?
I am trying to formulate a request using form-data package for file upload, and sending the request to another server with payload using @hapi/Wreck module. When the file size is greater than 1 mb i am getting the below error - {"statusCode":400,"error":"Bad Request","message":"Payload content length greater than maximum allowed: 1048576"}
Is there way we can increase this payload length.

```js
const some = 'properly formatted code example';
```

**Comment by cjihrig** [comment]
Is https://github.com/hapijs/hapi/blob/master/API.md#-routeoptionspayloadmaxbytes what you're looking for?

**Comment by AdvenDeep** [comment]
I am looking for how can i increase this request payload from 1 mb to say 10 mb.

**Comment by wswoodruff** [comment]
@AdvenDeep — @cjihrig did point you to the correct spot to configure this.

You can configure all of your routes to have an increased max payload, or you can configure a specific route to have this setting.

Here's an example for configuring for all routes:
```
Hapi.server({ ... routes: { payload: { maxBytes: 10485760 } } });
```

**Comment by tallapragadasaikiran** [comment]
Route options:

`options: {
              auth: { strategy: 'session' },
              payload: {
                  allow: 'multipart/form-data',
                  maxBytes: 100485760, //update accordingly 
                  parse: true,
                  timeout: false
              },
              timeout: {
                  socket: false
              }
}`

**Comment by cjihrig** [comment]
I'm going to close this as answered.
