### ISSUE TITLE
Friendlier UX with simple tab title reversal

### ISSUE THREAD

**Issue by romMidnight** [hapijs/hapi#4128]
#### Support plan

* *is this issue currently blocking your project?* (yes/no):no
* *is this issue affecting a production system?* (yes/no):no

#### Context

* *node version*: any
* *module version*: any
* *environment* (e.g. node, browser, native): browser
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*: browser tab title format 'hapi.dev - specificPageTitle' makes many tabs opened at once hard to navigate

#### What problem are you trying to solve?

Many webpage's  titles are named like "specific page - broader page(i.e. my search text - google), hapi.dev does this inverse, look at the title, it starts with 'hapi.dev -', that makes many opened hapi.dev tabs hard to navigate as last title part(specific one) is not visible fully, in attached pictures there are four hapi tabs and its impossible to visually see which specific hapi tabs are open in the browser
![image](https://user-images.githubusercontent.com/26493289/88850578-a6493200-d1fc-11ea-99b4-b8f610300b74.png)

```js
const apology = 'sorry for typos, life's 👍👍👍';
```

#### Do you have a new or modified API suggestion to solve the problem?

Just reverse the titles, so its 'testing - hapi.dev" "code v8.0.1 - hapi.dev" not "hapi.dev - testing" "hapi.dev - code v8.0.1"

**Comment by wswoodruff** [comment]
@romMidnight Can we plz relocate this issue to https://github.com/hapijs/hapi.dev?

**Comment by romMidnight** [comment]
Of course, thanks.

**Comment by hueniverse** [comment]
GitHub lets admins move issues around the org which is nicer...
