### ISSUE TITLE
Duplicate cookie key will be converted into array

### ISSUE THREAD

**Issue by Ronnie-Chen** [hapijs/hapi#4129]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 12.16.0
* *module version*: v19.x.x
* *environment* (e.g. node, browser, native): dev
* *used with* (e.g. hapi application, another framework, standalone, ...): Glue
* *any other relevant information*:

#### How can we help?

When I send a request and the cookie(request.query and request.payload of type `x-www-form-urlencoded` are the same as it) contains duplicated key, like below:
```
GET localhost:port
Cookie: a=1; a=2
```
Server will convert them into an array
```js
console.log(request.state);
// { a: [1, 2] }
```

How can I always get the latest value like `{ a: '2' }`, is there an option or function to set this feature off?

**Comment by cjihrig** [comment]
I don't think there is currently an option to do this.

**Comment by devinivy** [comment]
The "latest value" isn't necessarily well-defined: the browser simply sends multiple cookies with the same name, usually when there's an overlap in the cookies' paths or domains.  [The spec](https://tools.ietf.org/html/rfc6265#section-4.2.2) even says that servers shouldn't rely on this order:

>   Although cookies are serialized linearly in the Cookie header,
   servers SHOULD NOT rely upon the serialization order.  In particular,
   if the Cookie header contains two cookies with the same name (e.g.,
   that were set with different Path or Domain attributes), servers
   SHOULD NOT rely upon the order in which these cookies appear in the
   header.


If there's anything significant about the order of your cookie values it is probably specific to your application and/or your application's client, but it's not especially recommended.
