### ISSUE TITLE
filter must be an object error after upgrading

### ISSUE THREAD

**Issue by nickchampion** [hapijs/hapi#4131]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): Yes
* *is this issue affecting a production system?* (yes/no): No

#### Context

* *node version*:  12.18.0
* *module version with issue*:  Joi
* *last module version without issue*: 15.1.0
* *environment* (e.g. node, browser, native): node.js
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi
* *any other relevant information*: upgraded to Joi version 17.1.1

#### What are you trying to achieve or the steps to reproduce?

Before upgrade I could validate an encoded object from the query string using the following code

```js
const queryParams = {
  limit: Joi.number()
    .min(1)
    .max(100)
    .default(10),
  offset: Joi.number().default(0),
  orderBy: Joi.string(),
  filter: Joi.object(),
  fields: Joi.array()
};
```

Note filter parameter.

Example URL would be 

/api/admin/cms?limit=20&offset=0&filter=%7B%22type%22%3A%22page%22%7D

After upgrading I get the following error

'filter' must be an object

#### What was the result you got?

Validation error: 'filter' must be an object

#### What result did you expect?

Validation to pass successfully

**Comment by cjihrig** [comment]
If this is a joi issue, can you open this at https://github.com/sideway/joi.
