### ISSUE TITLE
Unable to get npm install to work

### ISSUE THREAD

**Issue by advapiIT** [hapijs/hapi#4135]
Hello,
Till yesterday I've used hapi 19.2 without any problems, now I tried to build a docker image that uses @hapi/hapi and I get

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@hapi%2fhapi - Not found
npm ERR! 404
npm ERR! 404  '@hapi/hapi@^19.2.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:

What am I doing wrong?
Thanks

**Comment by anleodev** [comment]
And I get this problem today

**Comment by raunaqkapoor** [comment]
Same issue here. This is breaking the CI/CD pipeline

**Comment by arielkuzminski** [comment]
Same here. 404 error!!!

**Comment by lsmialowski** [comment]
As far as I can see package has been deleted from npm repository

**Comment by arielkuzminski** [comment]
It's more a global NPM problem than this particular package:
https://status.npmjs.org/incidents/cksjqc1w11v5?u=clfvn2m9yb5p

**Comment by cjihrig** [comment]
Thanks. I'll close this as an issue with npm and not hapi.
