### ISSUE TITLE
Schema validator is missing

### ISSUE THREAD

**Issue by davesierra** [hapijs/hapi#4144]
#### Context

* *node version*: N/A
* *module version*: N/A

#### What are you trying to achieve or the steps to reproduce ?

Hello, I would like to locate that sandbox schema validator, it used to be located at: https://hapi.dev/module/joi/tester/ I've tried looking for it in the current update but can't seem to find it.

**Comment by davesierra** [comment]
I believe this should be in Joi

**Comment by cjihrig** [comment]
Joi is no longer under the hapi organization. I'm not sure where that link will live moving forward.
