### ISSUE TITLE
Directory listing patterns found issue

### ISSUE THREAD

**Issue by sharmabrijesh39** [hapijs/hapi#4152]
Hi Team,
I am using Hapi server version 16 with angular 8 and node.js >10. I am getting directory listing patterns found vulnerability issue. 
Could you please help to understand how to resolve this issue?

Note. If I am using listing:false then my css classes are not loading.

**Comment by cjihrig** [comment]
hapi 16 is not supported unless you have a commercial license for it. If you update to hapi 20 and can provide some reproducible code we can revisit this.
