### ISSUE TITLE
This site can’t provide a secure connection

### ISSUE THREAD

**Issue by justlucdewit** [hapijs/hapi#4158]
#### Support plan
Hi, i was trying out hapi, and tried making a simple API with it, i used the getting started project on the Hapi site and it worked! there is only one problem and that is that it doesnt work on HTTPS yet, only HTTP

#### Context

im using Node 14.8.0
im using Hapi 18.1.0
the problem is caused by all browsers, but only with HTTPS, not with HTTP
i used nothing but the hapi getting started template from the site

#### How can we help?
is there any configuration i didnt do to get HTTPS working? does it have to do with SSL? how do i get this working?

```js
import Hapi from "hapi";

const init = async () => {
    const server = Hapi.server({
        port: 3000,
        host: 'localhost'
    });

    await server.start();
    console.log('Server running on %s', server.info.uri);
};

process.on('unhandledRejection', (err) => {
    console.log(err);
    process.exit(1);
});

init();
```

**Comment by cjihrig** [comment]
Check out https://github.com/hapijs/hapi/blob/master/API.md#-serveroptionstls.

**Comment by justlucdewit** [comment]
so i need to write a SSL certification?
what is the minimum i need for that?
ive never done this
