### ISSUE TITLE
v17 documentation

### ISSUE THREAD

**Issue by patrykniedbalski** [hapijs/hapi#4159]
Hi Guys, 
where i can find documentation for v17 and 16 versions? It just disappeared from your website...

**Comment by patrykniedbalski** [comment]
do you have any LTS program or just supporting private projects?

**Comment by lloydbenson** [comment]
https://github.com/hapijs/hapi/blob/v17-commercial/API.md

**Comment by lloydbenson** [comment]
These were removed from the site because commercial is not supported by the team since @hueniverse stepped down from the project. If you do want support for that, I believe you can reach out to directly to @hueniverse and he has support options like LTS for a fee.

**Comment by lloydbenson** [comment]
Also see https://github.com/hapijs/hapi/issues/4114.

**Comment by devinivy** [comment]
Also, it is possible these will be returning to the site: https://github.com/hapijs/hapi.dev/issues/398
