### ISSUE TITLE
How to fix Invalid plugin options (…) [1] register is required error?

### ISSUE THREAD

**Issue by alex3wielki** [hapijs/hapi#4160]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v14.9.0 
* *module version*: 20.0.0
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*: here are my dependencies
  "@hapi/eslint-config-hapi": "^13.0.2",
  "@hapi/eslint-plugin-hapi": "^4.3.5",
  "@hapi/hapi": "^20.0.0",
  "@hapi/lab": "^23.0.0",
  "apollo-server-hapi": "^2.17.0",
  "graphql": "^15.3.0",
  "mongoose": "^5.10.4"

#### How can we help?

I'm trying to run Hapi with graphql plugins as seen below.

index.js

    const Hapi = require('hapi');
    const mongoose = require('mongoose');
    const {
      graphqlHapi, graphiqlHapi,
    } = require('apollo-server-hapi');
    const schema = require('./graphql/schema');
    
    const HOST = 'localhost';
    const PORT = 3000;
    
    const StartServer = async () => {
    
      const server = new Hapi.server({
        port: PORT,
        host: HOST,
      });
    
      server.route({
        method: 'GET',
        path: '/',
        handler: (request, h) => {
    
          return 'Hello World!';
        },
      });
    
      await server.register([
        {
          plugin: graphqlHapi,
          options: {
            path: '/graphql',
            graphqlOptions: { schema },
            route: { cors: true },
          },
        },
        {
          plugin: graphiqlHapi,
          options: {
            path: '/graphiql',
            graphiqlOptions: { 'endpointURL': '/graphql' },
            route: { cors: true },
          },
        },
      ]).catch((e) => console.log(e));
    
      try {
        await server.start();
      }
      catch (err) {
        console.log(`Error while starting server: ${ err.message }`);
      }
    
      console.log(`Server running at: ${ server.info.uri }`);
    };
    
    StartServer();

schema.js

    const graphql = require('graphql');
    
    const UserType = require('./UserType');
    
    const {
      GraphQLObjectType, GraphQLString, GraphQLSchema,
    } = graphql;
    
    const RootQuery = new GraphQLObjectType({
      name: 'RootQueryType',
      fields: {
        user: {
          type: UserType,
          args: { id: { type: GraphQLString } },
          resolve(parent, args) {
    
            return { test: true };
          },
        },
      },
    });
    
    module.exports = new GraphQLSchema({ query: RootQuery });

UserType.js

    const graphql = require('graphql');
    
    const {
      GraphQLObjectType, GraphQLString, GraphQLNumber,
    } = graphql;
    
    const UserType = new GraphQLObjectType({
      name: 'User',
      fields: () => ({
        id: { type: GraphQLString },
        name: { type: GraphQLString },
        joinDate: { type: GraphQLNumber },
        lastLoginDate: { type: GraphQLNumber },
      }),
    });
    
    module.exports = UserType;

And right now I'm getting an error of:

    Error: Invalid plugin options  {
      "plugin": {
        "options": {
          "path": "/graphql",
          "graphqlOptions": {
            "schema": {
              "_queryType": "RootQueryType",
              "_directives": [
                "@include",
                "@skip",
                "@deprecated",
                "@specifiedBy"
              ],
              "_typeMap": {
                "RootQueryType": "RootQueryType",
                "User": "User",
                "String": "String",
                "Boolean": "Boolean",
                "__Schema": "__Schema",
                "__Type": "__Type",
                "__TypeKind": "__TypeKind",
                "__Field": "__Field",
                "__InputValue": "__InputValue",
                "__EnumValue": "__EnumValue",
                "__Directive": "__Directive",
                "__DirectiveLocation": "__DirectiveLocation"
              },
              "_subTypeMap": {},
              "_implementationsMap": {}
            }
          },
          "route": {
            "cors": true
          }
        },
        "register" [1]: -- missing --
      }
    }
    
    [1] "register" is required
        at Object.exports.apply (C:\Users\aironsid\Documents\tatooify\node_modules\hapi\lib\config.js:19:15)
        at internals.Server.register (C:\Users\aironsid\Documents\tatooify\node_modules\hapi\lib\server.js:412:31)
        at StartServer (C:\Users\aironsid\Documents\tatooify\server\index.js:27:16)
        at Object.<anonymous> (C:\Users\aironsid\Documents\tatooify\server\index.js:56:1)
        at Module._compile (internal/modules/cjs/loader.js:1075:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
        at Module.load (internal/modules/cjs/loader.js:940:32)
        at Function.Module._load (internal/modules/cjs/loader.js:781:14)
        at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
        at internal/main/run_main_module.js:17:47

To make things funnier, the server starts, and I can get the `Hello world` response. Any idea what I messed up? I tried to follow [this](https://levelup.gitconnected.com/how-to-set-up-a-powerful-api-with-nodejs-graphql-mongodb-hapi-and-swagger-part-ii-80266790a3ac) tutorial

My package.json dependencies

    "dependencies": {
      "@hapi/eslint-config-hapi": "^13.0.2",
      "@hapi/eslint-plugin-hapi": "^4.3.5",
      "@hapi/hapi": "^20.0.0",
      "@hapi/lab": "^23.0.0",
      "apollo-server-hapi": "^2.17.0",
      "graphql": "^15.3.0",
      "mongoose": "^5.10.4"
    },

**Comment by devinivy** [comment]
I believe your issue is that the `graphqlHapi` plugin exists, but `graphiqlHapi` does not.

**Comment by alex3wielki** [comment]
> 
> 
> I believe your issue is that the `graphqlHapi` plugin exists, but `graphiqlHapi` does not. Perhaps you're working with some outdated apollo examples that ended-up being misleading.

It also doesn't find `graphqlHapi`. Doesn't work if either of these is commented out

**Comment by devinivy** [comment]
I installed apollo-server-hapi and looked at all of its exports.  I don't see `graphqlHapi` or `graphiqlHapi` on there, so I think you'll have to dig more into how that package is intended to be used.  Perhaps your usage is based on an older or newer version of apollo-graphql-hapi.  Here's the full list of exports I found:
```
{
  GraphQLUpload: [Getter],
  GraphQLExtension: [Getter],
  gql: [Getter],
  ApolloError: [Getter],
  toApolloError: [Getter],
  SyntaxError: [Getter],
  ValidationError: [Getter],
  AuthenticationError: [Getter],
  ForbiddenError: [Getter],
  UserInputError: [Getter],
  defaultPlaygroundOptions: [Getter],
  makeExecutableSchema: [Getter],
  addCatchUndefinedToSchema: [Getter],
  addErrorLoggingToSchema: [Getter],
  addResolveFunctionsToSchema: [Getter],
  addSchemaLevelResolveFunction: [Getter],
  assertResolveFunctionsPresent: [Getter],
  attachDirectiveResolvers: [Getter],
  attachConnectorsToContext: [Getter],
  buildSchemaFromTypeDefinitions: [Getter],
  chainResolvers: [Getter],
  checkForResolveTypeResolver: [Getter],
  concatenateTypeDefs: [Getter],
  decorateWithLogger: [Getter],
  extendResolversFromInterfaces: [Getter],
  extractExtensionDefinitions: [Getter],
  forEachField: [Getter],
  SchemaError: [Getter],
  mockServer: [Getter],
  addMockFunctionsToSchema: [Getter],
  MockList: [Getter],
  makeRemoteExecutableSchema: [Getter],
  defaultCreateRemoteResolver: [Getter],
  introspectSchema: [Getter],
  mergeSchemas: [Getter],
  delegateToSchema: [Getter],
  defaultMergedResolver: [Getter],
  transformSchema: [Getter],
  AddArgumentsAsVariables: [Getter],
  CheckResultAndHandleErrors: [Getter],
  ReplaceFieldWithFragment: [Getter],
  AddTypenameToAbstract: [Getter],
  FilterToSchema: [Getter],
  RenameTypes: [Getter],
  FilterTypes: [Getter],
  TransformRootFields: [Getter],
  RenameRootFields: [Getter],
  FilterRootFields: [Getter],
  ExpandAbstractTypes: [Getter],
  ExtractField: [Getter],
  WrapQuery: [Getter],
  SchemaDirectiveVisitor: [Getter],
  PubSubEngine: [Getter],
  PubSub: [Getter],
  withFilter: [Getter],
  ApolloServer: [Getter]
}
```

**Comment by alex3wielki** [comment]
You're right. The example on both apollo website and the tutorial seem outdated. Here's a version that seems to make sense https://www.npmjs.com/package/apollo-server-hapi
