### ISSUE TITLE
getting method did not return a value, a promise, or throw an error when sending a compressed response

### ISSUE THREAD

**Issue by meeravalishaik** [hapijs/hapi#4163]
Hi Team i m trying to compress my response using zlib.gzip method and send it but it is returning method did not return a value, a promise, or throw an error
Hapi version -18.1.0
code-
``
response=[{name:'john'},{name:'cruyff'},......]
gzip(JSON.stringify(response), { level: 9 }, (err, result) => {
    console.log('result->', result);
    if (result) {
      response = result;
      console.log('final', paginationData);
    }else{
    console.log('err->', err);
}
  });
return response;

**Comment by cjihrig** [comment]
You're trying to mix callback APIs (gzip) with promise-based APIs (hapi). You could do something like promisifying gzip using `util.promisify()`.

**Comment by meeravalishaik** [comment]
data=[{name:'john'},{name:'cruyff'},......]
const compress = util.promisify(gzip);

response = await compress(JSON.stringify(data));
return response still getting same issue

**Comment by cjihrig** [comment]
From what I can tell, this works:

```js
'use strict';
const Util = require('util');
const Zlib = require('zlib');
const Hapi = require('@hapi/hapi');
const compress = Util.promisify(Zlib.gzip);

async function main() {
  const server = Hapi.server({
    port: 4000,
    host: '0.0.0.0'
  });

  server.route({
    method: 'get',
    path: '/',
    handler: (request) => {
      const data = { foo: 'bar' };

      return compress(JSON.stringify(data));
    }
  });

  await server.start();
}

main();
```

**Comment by meeravalishaik** [comment]
thank you  i was getting compress data should i send any headers in response so ui understands it or i have to decompress in ui?
