### ISSUE TITLE
Can't access payload during auth strategy

### ISSUE THREAD

**Issue by linareyne** [hapijs/hapi#4164]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no (not yet)

#### Context

* *node version*: 14.10.1
* *module version*: 19.1.1
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi app
* *any other relevant information*: nah

#### How can we help?

I'm creating an auth strategy for requests that require an HMAC hash signature as a header. The signature is created using the request body and a secret, and I need to recreate the signature within the auth function to check it against the provided header. However, `request.payload` is `undefined` within the auth function, even though it is correctly passed into the route function after authentication. 

Digging into the `request` object, I see the following paremeter `_isPayloadPending: true`. Is this related to the issue? Is there any way to retrieve the payload object within the auth function?

**Comment by devinivy** [comment]
Yeah, it's true that the payload isn't available to you during authentication, and you can see this reflected in the [request lifecycle](https://github.com/hapijs/hapi/blob/master/API.md#request-lifecycle).  It's somewhat related to performance: let's ensure the user is allowed to make the request before doing all the work of processing a payload.  But sometimes folks do need to tie the payload into their authentication.  hapi speaks to that through the auth scheme's `async payload()` configuration.  This allows auth schemes that rely on the payload to do some of their work after the payload is processed and available.  Another way to handle this is to make some checks in an `onPostAuth` [request extension](https://github.com/hapijs/hapi/blob/master/API.md#server.ext()).

**Comment by devinivy** [comment]
There's also a good example out there of how to achieve something similar to what you're doing with HMAC and hapi auth: check out hawk's auth scheme https://github.com/outmoded/hawk/blob/master/lib/plugin.js#L34.

**Comment by linareyne** [comment]
Brilliant, lifecycle methods to the rescue.

For anyone who stumbles upon this issue, here's some pseudocode that illustrates the simple changes I made to get it working.

```
const authenticateFn = (request, h) => {
  const payload = request.payload;

  // Use payload for auth stuff here

  return h.continue;          // Since this is used by the payload lifecycle method, it can't return h.authenticated
};

const myAuth = () => {
  return {
    authenticate: (request, h) => h.authenticated({            // Or pass another function for other auth stuff
      credentials: {
        auth: true,
      },
    }),
    payload: (request, h) => {
      return authenticateFn(request, h);           // This was originally passed as the authenticate method
    }),
    options: {
      payload: true,             // Required to force payload verification
    },
  };
};
```
