### ISSUE TITLE
unable to set  'Content-Encoding', 'gzip' for a compressed response object even after setting header via reply.response

### ISSUE THREAD

**Issue by meeravalishaik** [hapijs/hapi#4166]
Hi Team

I am unable to set  'Content-Encoding', 'gzip' header to my response  which data i have compressed with gzip and i was getting compressed data in response. attaching screenshots of response headers and response
https://filebin.net/xoxectbca7loilar/resHeaders.PNG?t=tj4y5c62
https://filebin.net/xoxectbca7loilar/responsy.PNG?t=43m3wv8x

Hapi version-18.1.0

Code-
```
const data=[{name:'john',name:'kevin',....]
const compressedData= await gzip(JSON.stringify(data)); 
reply.response(compressedData).header('Content-Encoding', 'gzip');
```

**Comment by cjihrig** [comment]
Please provide [runnable examples](https://github.com/hapijs/hapi/issues/4163#issuecomment-698975262) - ideally as minimal as possible. Your chances of receiving help will be significantly higher.

**Comment by kanongil** [comment]
You should use `response.compressed()`: https://hapi.dev/api/?v=18.4.2#-responsecompressedencoding.
