### ISSUE TITLE
response._close is not a function

### ISSUE THREAD

**Issue by jaulz** [hapijs/hapi#4168]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 14.7.0
* *module version with issue*: 20.0.1
* *last module version without issue*: n/a 
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*: n/a

#### What are you trying to achieve or the steps to reproduce?

Unfortunately, this happens only once in a while I could not really reproduce it. I will try to trace it down but I assume it's similar to my previous PR https://github.com/hapijs/hapi/pull/4161

#### What was the result you got?
Server stops immediately because of `response._close is not a function`.

#### What result did you expect?
Server should not stop.

**Comment by cjihrig** [comment]
@jaulz is this still occurring? Have you been able to come up with a reproduction?

**Comment by jaulz** [comment]
@cjihrig fortunately it is not occurring anymore... maybe it was related to some weird combination of dependencies. I will close the issue for the time being and open it again if I see it happen again.
