### ISSUE TITLE
return content  which fead from html  file   resspone  content-type: application/octet-stream

### ISSUE THREAD

**Issue by tablecell** [hapijs/hapi#4169]
#### Support plan

* *is this issue currently blocking your project?* (yes/no):yes
* *is this issue affecting a production system?* (yes/no):no

#### Context

* *node version*:  v13.7.0

* *module version with issue*: 20.0.1
* *last module version without issue*: 
* *environment* (e.g. node, browser, native): npm 6.13.6   curl 7.70.0
* *used with* (e.g. hapi application, another framework, standalone, ...):standalone
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

```js

'use strict';

const Hapi = require('@hapi/hapi');
const fs =require('fs');
const init = async () => {

    const server = Hapi.server({
        port: 3000,
        host: '127.0.0.1'
    });

server.route({
    method: 'GET',
    path: '/readfile',  // curl http://localhost:3000/hello/your
    handler: function (request, h) {
   
   var content = fs.readFileSync('file.html');   
    return  content;              //   content-type is  application/octet-stream  
  // return " some string" ;   // content-type  is    text/html    it is right 

    }
});

  await server.start();
    console.log('Server running on %s', server.info.uri);
};

process.on('unhandledRejection', (err) => {

    console.log(err);
     process.exit(1);
});
```
curl    -v  http://localhost:3000/readfile
#### What was the result you got?

< HTTP/1.1 200 OK
< content-type: application/octet-stream
...

#### What result did you expect?

expect content-type     as   
```JS
    handler: function (request, h) {
      return   " some string ";;
    }
curl    -v  http://localhost:3000/readfile
< HTTP/1.1 200 OK
< content-type: text/html; charset=utf-8

**Comment by cjihrig** [comment]
```js
var content = fs.readFileSync('file.html'); 
```

Try passing `'utf8'` as the second parameter to `fs.readFileSync()`.
