### ISSUE TITLE
how to read hapi source code? for example: what order?

### ISSUE THREAD

**Issue by anlexN** [hapijs/hapi#4170]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: all
* *module version*: all 
* *environment* (e.g. node, browser, native): all
* *used with* (e.g. hapi application, another framework, standalone, ...): all
* *any other relevant information*: i am reviewing hapi source code.

#### How can we help?
teach me how to read.

**Comment by devinivy** [comment]
This is a broad question that is hard to answer in one comment.  hapi is a collection of libraries, so it doesn't necessarily read linearly from "start" to "end".  There are several entrypoints, for example: [`Hapi.server()`](https://github.com/hapijs/hapi/blob/b8eb5f908d9cbab9769f9b79227bc9ce03c02a37/lib/server.js#L21-L25) is often the user's entry point, but http requests have a [their own](https://github.com/hapijs/hapi/blob/master/lib/core.js#L501) [entrypoint](https://github.com/hapijs/hapi/blob/b8eb5f908d9cbab9769f9b79227bc9ce03c02a37/lib/request.js#L265).  If you're interested to learn how to the framework works I recommend starting there and just seeing where you [end up](https://github.com/hapijs/hapi/blob/b8eb5f908d9cbab9769f9b79227bc9ce03c02a37/lib/transmit.js#L17).  It is also worth noting that there are [many modules](https://github.com/hapijs/hapi/blob/b8eb5f908d9cbab9769f9b79227bc9ce03c02a37/package.json#L21-L38) working in concert to support all of hapi's features (there's a router, a multipart parser, a cookie manager, a fancy event emitter for logging, and more).

**Comment by anlexN** [comment]
from the view of nodejs engine used by hapi, can we rewrite hapi with full es2015+ mordern syntax?
