### ISSUE TITLE
Multiple Payload validation

### ISSUE THREAD

**Issue by tguelcan** [hapijs/hapi#4171]
I have found a way to validate several conditions in a async row. 
**It works but i am not sure if this is recommended.** 
The condition is that the first schema (_validationSchema_) in the array must not be changed because it is already converted when using [joigoose](https://github.com/yoitsro/joigoose).

```javascript 
{
        method: ['POST'],
        path: '/users',
        options: {
            validate: {
                payload: validateMultiple([
                    validationSchema,
                    {
                        email: Joi.string().external(lookup)
                    }
                ]),
                failAction: (request, h, err) => {
                    throw err;
                }
            },
            handler: create
        }
    }
```

```javascript
const validateMultiple = (validationObjects) => {
    return async (payload) => {
        try {
             for (const item of validationObjects) {
                item.type !== 'object' ?
                    await Joi.object(item).validateAsync(payload) :
                    await item.validateAsync(payload);
            }
        }
        catch (err) {
            throw err;
        }
    };
};
```
In this example i take the validation schema of mongoose (_validationSchema_). with the additional conditions (.external(lookup)) i check, if the email address already exists.
Would another possibility be appropriate or is there an alternative?

**Comment by Marsup** [comment]
Schema compilation have a cost you probably don't want to pay each time a request is done, also the result of a validation can be different from its input so you likely want to change the payload as you go. I'm not sure what you're trying to solve, but you can likely improve the implementation details. Why aren't you merging the schemas if that's what you want ?

**Comment by tguelcan** [comment]
It is exactly my goal. Basically I want to use the schema, which is defined in mongoose as validation to avoid redundancies. This works fine so far. 
Bcs, i do not want to validate everywhere and at different places again and again in the code. 
But - there are deviations and exceptions in the validation queries during routing and here I want to create possibilities to extend, change and overwrite the validation. Is there a recommendation for this?

**Comment by Marsup** [comment]
I'm not sure what you're after but have you looked at https://joi.dev/api/?v=17.2.1#anyconcatschema ?

**Comment by devinivy** [comment]
It seems like you are using hapi in a supported way to suit your particular needs: that is a good application of a custom validation function.  A similar option I've seen out there is to use pre-handlers (which are easy to modularize and share) to enforce "policies" prior to hitting the handler.
