### ISSUE TITLE
can we make a example repo?

### ISSUE THREAD

**Issue by anlexN** [hapijs/hapi#4178]
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: latest
* *module version*: latest
* *environment* (e.g. node, browser, native): all
* *used with* (e.g. hapi application, another framework, standalone, ...): all
* *any other relevant information*: i am learning hapijs source code.

#### How can we help?
please give me many example that can inspire me, and tell me hapi structure and theory and philosophy

**Comment by devinivy** [comment]
Let's leave this open for another week or so, and see if folks share any examples or thoughts.  One interesting thing about hapi is that it's not very prescriptive about how you use it!  It is a fairly neutral framework, and is great for building more opinionated tools on top of it.  It's not uncommon to find teams building their own abstractions on top of hapi that reinforce their own structure and preferences about how to build application backends.

**Comment by anlexN** [comment]
so i need many examples that can demonstrate your opinion.

**Comment by brianle1301** [comment]
@anlexN what sort of example are you looking for? Simple server? Integration with other services?

**Comment by anlexN** [comment]
such like koa and fastify and express official example. hapi have no official example.

**Comment by brianle1301** [comment]
@anlexN There are in tutorials, no?

**Comment by anlexN** [comment]
those are just snippets. by the way, hapi have no cli to generate project.

**Comment by Nargonath** [comment]
hapipal is an example of opinionated tool built around hapi: https://hapipal.com/. It also comes with a CLI to generate your project but brings also so much more.

**Comment by anlexN** [comment]
hapipal is so awesome, but it is not official, and is it MIT License? i can not see its license.

**Comment by Nargonath** [comment]
Most of hapipal's components are under the MIT license. Take for example the CLI repository: https://github.com/hapipal/hpal. Hapipal was created by a member of the previous core team and he's also part of the TSC. Other TSC members also help with it (myself for example). It is not truly _official_ and probably never will because hapi itself is unopiniated. Many of us use it daily in their projects though so I'd say it's as close to _official_ as it gets.
