### ISSUE TITLE
what theory/philosophy does internals.toolkit use?

### ISSUE THREAD

**Issue by anlexN** [hapijs/hapi#4179]
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: latest
* *module version*: all
* *environment* (e.g. node, browser, native): all 
* *used with* (e.g. hapi application, another framework, standalone, ...): all
* *any other relevant information*: please tech this technology

[internals.toolkit](https://github.com/hapijs/hapi/blob/b9b8e6f08d3487f5e5581dc73902f45f8bd1c6d3/lib/toolkit.js#L175) line 175-247:

why use function, class, prototype at the same time?

**Comment by brianle1301** [comment]
@anlexN A function is used here to prevent `server.decorate('toolkit')` from overriding the default class.

**Comment by devinivy** [comment]
Yeah, exactly.  I will just echo Brian: each server will have its own toolkit class in order to support `server.decorate()` without leaking decorations across servers.  Then `prototype` is used to ensure all toolkits would have certain properties when instanced 👍

**Comment by anlexN** [comment]
understand hapijs source code, it is not a easy thing.

**Comment by brianle1301** [comment]
I find Hapi's code much easier to understand compared to other frameworks.

**Comment by anlexN** [comment]
koa is easier than hapi.
