### ISSUE TITLE
auth #schemes not really private

### ISSUE THREAD

**Issue by matthieusieben** [hapijs/hapi#4181]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 15
* *module version with issue*: 20.0.1
* *last module version without issue*: 20.0.1
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): none
* *any other relevant information*: n.a.

#### What are you trying to achieve or the steps to reproduce?

The `#scheme` property in `Auth` should not be temperable with.

#### What was the result you got?

The `#scheme` property in `Auth` can actually be accessed "from the outside"

```js
server.auth.scheme('foo', function (server, options) {
  // In this context `this` is equal to `auth.#schemes`

  this['other-scheme'] = function customOverrideOfOtherScheme() {}
})
```

Due to this line:

https://github.com/hapijs/hapi/blob/06d2723203ebe36cfe89528530dbf3f8d2648bcf/lib/auth.js#L49

#### What result did you expect?

schemes functions should be called with another context that `auth.#schemes`. Or is it by design ?

**Comment by matthieusieben** [comment]
Not an actual problem I have. Just stumbled upon this while reading te code. It seemed odd to use a private class property that could be actually be accessed from the outside.

**Comment by kanongil** [comment]
The private properties are not used for security reasons, and exposing content assigned to one is not an issue per-se. Hapi assumes that all plugin code is trusted, and as such it is not a big issue that this state is exposed. The private property still guards against direct assignment.

**Comment by matthieusieben** [comment]
Right I was mainly wondering. Thanks for your answer
