### ISSUE TITLE
Inject returns payload as string

### ISSUE THREAD

**Issue by alexnaldo** [hapijs/hapi#4183]
#### Support plan

* *is this issue currently blocking your project?* (yes/no):no
* *is this issue affecting a production system?* (yes/no):no

#### Context

* *node version*: 15.0.1
* *module version with issue*: ^20.0.1
* *last module version without issue*: 
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

We are trying to test the result of api, but Inject returns payload as string.

```js

    // create a simple GET  - return object

    server.route({
    method: 'GET',
    path: '/',
    handler: function () {

        return { name : 'Hello World!' };
    }
    });

   // Test it
  describe('GET /', () => {
    
    it('responds with "Hello World!" as object', async () => {
        const res = await server.inject({
            method: 'get',
            url: '/'
        });
        expect(res.payload.name).to.equal("Hello World!");
    });
});
   
```

#### What was the result you got?

res.payload as string  "{ name : "Hello World!" }", so the property "name" doesn't exists.

workaround: (parse the payload before access)

let data = JSON.parse(res.payload);
expect(data.name).to.equal("Hello World!"); // now works!

#### What result did you expect?

res.payload as object { name : "Hello World!" }

**Comment by devinivy** [comment]
I believe you want to use `res.result` rather than `res.payload`.  The `res.payload` property is always a string, whereas `res.result` is the result returned from your handler.  Should be as simple as that! 👍
