### ISSUE TITLE
Add a 'closing' event

### ISSUE THREAD

**Issue by kanongil** [hapijs/hapi#4194]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes (but have a workaround)
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: any
* *module version*: 20.0.2
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*:

#### What problem are you trying to solve?

Detect when the server has called `close()` on the listener in order to abort some slow processing pending responses.

The correct time to do this is right after `server.listener.close()` has been called since clients that retry the request will be denied at the socket level. Doing it earlier in an `onPreStop` extension risks clients reconnecting.

Currently I manage this by making a custom listener where I intercept the call to `close()`.

#### Do you have a new or modified API suggestion to solve the problem?

Yes. Add a new `'closing'` event on `server.events`, which triggers right after [`server.listener.close()` is called](https://github.com/hapijs/hapi/blob/75e901498f2914ebf9c2ec274b8abef072c274cf/lib/core.js#L462).

Note that the `'close'` event on the listener cannot be used, as it is first called once all listeners have been fully closed.

**Comment by cjihrig** [comment]
Sounds like a reasonable feature request.

**Comment by Nargonath** [comment]
I agree. Are you already working on it @kanongil? Otherwise I'd be happy to.

**Comment by kanongil** [comment]
I use my workaround at the moment, and haven't had the opportunity to make any implementation here. You are very welcome to implement this.

**Comment by Nargonath** [comment]
Closed by #4203
