### ISSUE TITLE
When can a header value be an array of strings?

### ISSUE THREAD

**Issue by nulltoken** [hapijs/hapi#4197]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 14 
* *module version*: 20.0.1
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*: TypeScript

#### How can we help?

According to the [doc](https://hapi.dev/api/?v=20.0.3#-responseheaders), `response.headers` is:
> An object containing the response headers where each key is a header field name and the value is the string header value or **array of string**

The TypeScript definition implements this (cf. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/hapi__hapi/index.d.ts#L687-L693)

However:
 - I haven't been to find in the codebase a code path where a returned header could actually be an array of strings
 - I haven't found either a test where the header value is an array of strings

I'd be very grateful if you could double check my findings and would I be wrong (highly probable  ;-) ) help me understand (and maybe add a test putting that under the light) under which circumstance a response header value can be returned as an array of strings.

**Comment by Marsup** [comment]
Some headers can contain multiple values, see [node's documentation](https://nodejs.org/docs/latest/api/http.html#http_request_getheader_name) for at least one example. I think you'll have to refer to the http spec to know which ones.

**Comment by nulltoken** [comment]
@Marsup Thanks for the rapid feedback.
