### ISSUE TITLE
Backend and Frontend running on different port but same domain but getting CORS error

### ISSUE THREAD

**Issue by ThPch** [hapijs/hapi#4198]
* *is this issue currently blocking your project?* (yes/no): Yes
* *is this issue affecting a production system?* (yes/no): No

#### Context

* *node version*: 15.3.0
* *module version*: 20.0.3
* *environment* (e.g. node, browser, native): nodejs, hapijs, reactjs, axios
* *used with* (e.g. hapi application, another framework, standalone, ...): running a backend hapijs server & a frontend react web application
* *any other relevant information*: No

#### How can we help?

Hi,

I couldn't find any solution relevant to my issue despite trying a different methods found on the web this evening. 
I'll make it really simple, I have a backend HapiJS server running on localhost on port 5000 & a frontend React web application running on port 3000.

On this web application I'm trying to fetch data from my server on the route '/'

So basically, this is how I've configured my server

```js
const server = Hapi.server({
  port: process.env.APP_PORT,
  host: 'localhost',
  routes: { cors:
    {
      origin: "ignore", //I've tried "*" also
      additionalHeaders: ["Authorization"],
      additionalExposedHeaders: ["Authorization"]
    }
}
});

//I've tried to configure the route without cors and with cors policy without success 
server.route({
        method: 'GET',
        path: '/',
        options: {
          cors: true,
          handler: async (req, h) => {
              return h.response({
                  text: 'Lorem ipsum'
              });
          }
      }
    });
```

And this is how I make the axios request from the web app : 
(please, be aware that I can make this code works configuring cors policy on an express server, but unfortunately, I couldn't make it happen with an HapiJS server)

```js
let data;
    const url = 'http://localhost:5000/'

    axios.defaults.headers.common['Access-Control-Allow-Origin'] = '*';
  
    axios.get(url, { 
      headers : {
        "Access-Control-Allow-Origin": "*"
      },
      crossdomain: true
      })
      .then((res) => {
        
        console.log("coucou")
        console.log(res)
        
      })
      .catch((err) => {
        console.log(err);
      })
```

I'm still getting this error in my browser console : **Access to XMLHttpRequest at 'http://localhost:5000/' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource**

Thank you

**Comment by Nargonath** [comment]
Thanks for raising the issue you're facing @ThPch. Could you please provide a github repository with the bare minimum code for the frontend and backend to reproduce your issue?

**Comment by ThPch** [comment]
Hi @Nargonath, thank you for your message. After struggled this night to find a fix, @[resu511](https://github.com/resu511) found that putting addionalHeaders with these following values on route setting in Hapi.server() would fix the problem.

```
    cors: {
      origin: ['*'],
      additionalHeaders: ['Accept', 'Access-Control-Allow-Origin', 'Referer', 'User-Agent'] // should contain list of request headers
    }
```

I'm quite surprised by the way that the value` cors: true or origini:"*" & "ignore"` don't work.

**Comment by kanongil** [comment]
This seems like a configuration issue. Try removing the "Access-Control-Allow-Origin" header from the axis request, and configure "origin" to "*" to fix it.

**Comment by ThPch** [comment]
> This seems like a configuration issue. Try removing the "Access-Control-Allow-Origin" header from the axis request, and configure "origin" to "*" to fix it.

I'll try your solution right now & get back to you in few minutes

**Comment by teknosains** [comment]
im not able to resolve this issue

accessing 

Hapi (http://localhost:3100)

from a React frontend (http://localhost:3000)

**Comment by ThPch** [comment]
> 

I'm sorry I don't have the track on this, try to hardcode all the value, the port number, localhost..., try to put the first arg of route like I've mentionned before your post, good luck
