### ISSUE TITLE
how do i handle errors with streams in hapi?

### ISSUE THREAD

**Issue by fiws** [hapijs/hapi#4199]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v15.3.0
* *module version*: 20.0.3
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*:

#### How can we help?

Using `h.response(stream)` with any stream does not seem to handle errors and instead just closes the connection without sending anything.
I am wondering if hapi can/should do some error handling or how i can handle stream errors myself.

```js
const hapi = require('@hapi/hapi');
const fs = require('fs')

const server = hapi.server();

server.route({
  method: 'GET',
  path: '/',
  handler(_, h) {
    const stream = fs.createReadStream('./doesNotExist');
    return h.response(stream);
  },
});

server.start()
  .then(() => console.log('Server running on %s', server.info.uri));
```

## Test

```
❯ curl localhost:43951   
curl: (52) Empty reply from server
```

**Comment by kanongil** [comment]
Once hapi has sent the headers there is no way to signal an error to clients other than closing the connection, as you see.

If you need to send a file, you really should use the `inert` module, which will among other things screen the file for such an error before sending it. It provides a simple `h.file()` api to send stored files.

**Comment by fiws** [comment]
hello @kanongil thanks for your reply. I am only using `fs` as a simple example here. I actually want to stream something from an object storage so using inert here is not an option.

Are you sure that the headers have been sent at this point? There is not even a status code in the response:

```
❯ curl -v localhost:41543
*   Trying ::1:41543...
* connect to ::1 port 41543 failed: Connection refused
*   Trying 127.0.0.1:41543...
* Connected to localhost (127.0.0.1) port 41543 (#0)
> GET / HTTP/1.1
> Host: localhost:41543
> User-Agent: curl/7.73.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

**Comment by kanongil** [comment]
There is internal buffering that means that in practice the stream can end before the server has transmitted the headers. If you delay the `'error'` emit on the stream, you will find that they are received.

Regardless, you will need to do your own pre-validation before returning the stream to support your use case. Hapi assumes that the only error that can happen once you set it as the response, is a fatal one.

**Comment by cjihrig** [comment]
I'm going to close this as answered, but feel free to continue any discussion.

**Comment by fiws** [comment]
thanks for the explanation. we will implement the validation before starting the stream.

Do you think there still is a workaround/hack to get hapi to always respond with a status code somehow tho?

The reason I am asking is because we are using [Google Cloud Run](https://cloud.google.com/run) and it seems that closing connections without sending anything is factored into some health metric. Our running containers seem to get replaced after repeatedly closing connections, which basically can be used as a DoS.

**Comment by kanongil** [comment]
No. Once the response has started transmission there is no other way to signal an error than to forcefully close the connection.

**Comment by fiws** [comment]
In case anyone has the same problem:
I am now waiting for the stream to become readable before passing it to hapi. This makes catching "not found" errors and other setup related errors very easy. This is better than manually pre-checking imo, as it has less problems with race conditions. This effectively solved our problem:

```js
const hapi = require('@hapi/hapi');
const fs = require('fs')

const server = hapi.server({ port: 1234 });

const streamReadable = stream => {
  stream.pause();
  return new Promise((resolve, reject) => {
    stream.once('error', reject);
    stream.once('readable', () => resolve(stream));
  });
};

server.route({
  method: 'GET',
  path: '/',
  async handler({ raw }, h) {
    const stream = fs.createReadStream('./notFound.txt');

    const readyStream = await streamReadable(stream);
    return h.response(readyStream);
  },
});

server.start()
  .then(() => console.log('Server running on %s', server.info.uri));
```

(not sure if this works for every stream source tho)

**Comment by kanongil** [comment]
This solution will be somewhat specific to the stream you are handling, but it makes sense that it can work.

The method used should be quite safe, and could possibly be applied to all streams by hapi to give it a chance to error before starting the actual transmission. I don't know if this is something we would want to do?

Btw. the `pause()` should not be needed, as attaching a `'readable'` handler is already supposed to do this.
