### ISSUE TITLE
Diluent not included in absorption coefficient when HITRAN_Unit = False

### ISSUE THREAD

**Issue by asindiff** [hapijs/hapi#4206]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: master
* *module version*: absorptionCoefficient_Voigt
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*: no

#### How can we help?

 I was just started in this area by trying a text book example, i.e. 10% H2O in air at 1 atm and 1000 K over 10cm path. The following function call returns an coeff1 that was 10x smaller than expected.
```
p = 1.0  # atm
T = 1000.0  # K
mfrac = 0.1  # mole fraction
nu1, coef1 = absorptionCoefficient_Voigt(((1, 1),), 'H2O',
                                         OmegaStep=0.002, HITRAN_units=False, Diluent={'self': mfrac, 'air': (1 - mfrac)},
                                         Environment={'p': p, 'T': T})
```
It seems this is due to mole fraction was not included in the calculation when HIRAN_units = False. The following call gave the correct result
```
p = 1.0  # atm
T = 1000.0  # K
mfrac = 0.1  # mole fraction
nu1, coef1 = absorptionCoefficient_Voigt(((1, 1),), 'H2O',
                                         OmegaStep=0.002, HITRAN_units=True, Diluent={'self': mfrac, 'air': (1 - mfrac)},
                                         Environment={'p': p, 'T': T})
coef = coef1 * volumeConcentration(p, T) * mfrac  # convert from HITRAN_units 1/(molecule*cm^-2) to cm^-1
```
```js
const some = 'properly formatted code example';
```

**Comment by cjihrig** [comment]
This is not a hapi issue.
