### ISSUE TITLE
How can I make a GET request with hapi?

### ISSUE THREAD

**Issue by omartoutounji** [hapijs/hapi#4207]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v12.16.2
* *module version*: hapi 17
* *environment* (e.g. node, browser, native): browser
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*:

#### How can we help?

How can I make a GET request with hapi?

**Comment by cjihrig** [comment]
I'm not entirely sure what you're asking here. If you want to make a request from inside of a hapi server, you can use any Node http client. The official hapi client is [wreck](https://www.npmjs.com/package/@hapi/wreck).
