### ISSUE TITLE
An update on how to support hapi's community-lead development and maintenance

### ISSUE THREAD

**Issue by devinivy** [hapijs/hapi#4213]
### If you are interested in sponsoring development of hapi, there's exactly one place to go, and that is our new [hapijs OpenCollective](https://opencollective.com/hapijs) page!

**We have joined the Open Source Collective,** a non-profit organization that enables us to transparently receive and allocate funds, which we invite you to follow on our OpenCollective.  On behalf of the community, the TSC ✨ greatly appreciates ✨  any and all contributions to support development of the hapi web framework.  We pledge that we will always use these funds to most favorably benefit the community as a whole.

**If you supported the framework in the past** then you have likely sponsored Eran Hammer's work on the project through [GitHub Sponsors](https://github.com/sponsors/hueniverse).  Note that **sponsoring Eran no longer translates to development of the hapi web framework,** however it does benefit development of the joi validation framework.  Contributing to joi is another worthy cause, and despite joi having left the hapijs organization hapi will continue to support joi route validations.

**The funds we receive through our OpenCollective are spent transparently,** and we invite you to track them on the "Budget" section of our OpenCollective page. Funds will primarily be used to reimburse members of the TSC for their time spent maintaining the framework, similarly to how contributions worked prior to the formation of the TSC. That means that contributing monetarily to hapi translates to time spent providing support, improving documentation, triaging bugs, responding promptly to security-related events, feature development, and shepherding work done by community members through to being published.

**hapi offers the kind of comprehensiveness and stability which only comes through years of careful work.** These attributes of the framework require a high level of attentiveness any time that changes are made, and providing that attentiveness takes time.  Knowing that there is material support for this work is heartening, as it means the framework has a bright future under non-commercial, community maintenance.

It's worth mentioning that **we have additional intermittent expenses** for the services we use, such as domain registration and hosting for hapi.dev. We dream of a future where we can spend our funds in some more exciting ways, such as sponsoring community members to give talks on hapi, writing documentation and tutorials, and giving out free merch to the community. We'll certainly let you know if and when we are able to organize such a thing.

**We would also like to provide better incentives to our backers!** We will be putting together a simple sponsorship program to acknowledge those who make large and/or recurring donations to the hapi organization. We will also continue to maintain [SPONSORS.md](https://github.com/hapijs/hapi/blob/master/SPONSORS.md) to publicly thank our backers right within hapi's codebase.

**Finally, supporting the framework with money is just one of many ways to contribute to hapi!**  We are very grateful for any time spent supporting the framework!  Answering questions in the issue trackers and in [hapi hour](https://join.slack.com/t/hapihour/shared_invite/zt-g5ortpsk-ErlnRA2rUcPIWES21oXBOg), tracking-down bugs and creating reproductions, contributing fixes, improving documentation, proposing well-spec'ed features, are all incredible ways to support the framework, and honestly we six TSC members can't do it alone, nor do we want to.  We'd love your help.  In the coming months we will be more proactively extending invitations to repeat contributors to become official collaborators.

### 🥂 Here's to a hapi and bright 2021!!

**Comment by AndriiNyzhnyk** [comment]
HI, why did you guys close this issue? In my opinion, it can help Hapi anyway. What is the plan here?

**Comment by Nargonath** [comment]
@AndriiNyzhnyk I believe the actual status of this issue is irrelevant that's why it was closed. The information are still relevant to whoever wants to support hapi. It's also easily accessible since the issue is pinned to the issues section. We just didn't want to leave it open because it would otherwise remain open ad vitam aeternam. Hope it makes sense.
