### ISSUE TITLE
About split router

### ISSUE THREAD

**Issue by mofengfs** [hapijs/hapi#4217]
I am a new player. I want to construct the route described in the picture. 
I tried some methods, but it seems not feasible. 
Hope to get help.
I think the splitting of route is very important, and I hope the official can give an optimal plan and doc. 
This helps new players like me join this interesting family.

![image](https://user-images.githubusercontent.com/16655229/104182658-bde34280-544b-11eb-800c-11cb45487261.png)

**Comment by geek** [comment]
@mofengfs in our docs we do have a tutorial related to routing here: https://hapi.dev/tutorials/routing/?lang=en_US

While it doesn't have an example with your specific structure it should help demonstrate how to add routes. But yes, you can export from admin/api above and register those split out routes in the Routes or server.js in the diagram.

**Comment by mofengfs** [comment]
@geek 
Thanks, I am studying your documentation, I think I will find the answer.
