### ISSUE TITLE
When an invalid 'date' is passed in as query string parameter Joi.date().iso().raw() fails

### ISSUE THREAD

**Issue by vineelgarimella** [hapijs/hapi#4228]
#### Support plan

* *is this issue currently blocking your project?* (yes/no):yes
* *is this issue affecting a production system?* (yes/no):no

#### Context

* *node version*: v10.22.1
* *module version*:  "@hapi/joi": "^15.1.1",
* *environment* (e.g. node, browser, native): macOS/Windows
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*:

#### How can we help?

```js
my api call : http://localhost:3000/myValidation?date='2020-12-31T05:00:00.000Z'

Joi.validate(req.query, mySchema, { stripUnknown: true });

const mySchema = Joi.object().keys({
date: Joi.date().iso().raw() / Joi.date().iso().raw(true)
})

```
case 1: 
When i try to pass the date as ?date=1234 (which is an invalid date format) or ?date=2020-12-31T05:00:00.000Z  - **without quotes**
**expected behaviour**: It should throw a validation error like  "&quot;date&quot; must be a valid ISO 8601 date" n error scenario and internal server error from joi in valid date scenario
**Actual behaviour**: It tries to accept as a valid string for 1234 parameter and  proceeds further which shouldn't happen.
When query for the object returned in req.query inside the function before it actually goes through joi validation get it like  { date: '1234' } 

case 2: 
When i try to pass the date as ?date='1234'(which is an invalid date format) -**with quotes**
**expected behaviour**: It should throw a validation error like  "&quot;date&quot; must be a valid ISO 8601 date"
**Actual behaviour**: works as expected and throws a a validation error.
When query for the object returned in req.query inside the function before it actually goes through joi validation get it like  { date: '\'1234\''  } 

I tried to change my schema configuration as per your package but nothing seems to be working . I also tried to parse the date to a string and mutate the req.query.date to the format like the way Joi likes it but it fails . 

Note: i  do not want joi to convert my date , i want to pass in raw date sent from the user and validate the same and throw error if it is incorrect . 

Please let me know if there is something which i am missing .

**Comment by devinivy** [comment]
I believe the issue is that `1234` is actually a valid ISO date representing the beginning of the year 1234.  When you add the quotes you get the behavior you want because `'1234'` is not a valid year (as far as I know ISO strings can never contain quotes).  For more info, see https://en.wikipedia.org/wiki/ISO_8601#Years.  I don't think that there's a bug with joi here, but if you believe there are any faulty validations, you might want to open an issue with [joi](https://github.com/sideway/joi).
