### ISSUE TITLE
Commit package-lock.json

### ISSUE THREAD

**Issue by spridev** [hapijs/hapi#4232]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 14.15.0
* *module version*: 20.1.0
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): -
* *any other relevant information*: -

#### What problem are you trying to solve?

According to the npm guidelines, the `package-lock.json` file should be [committed into source repositories](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#description). I couldn't find any discussion mentioning this topic (and this design choice for hapi's ecosystem).

#### Do you have a new or modified API suggestion to solve the problem?

I would suggest:

- Removing the `package-lock.json` file from `.gitignore`
- Using `npm ci` instead of `npm install` in the ci pipeline, which is the [recommended way](https://docs.npmjs.com/cli/v7/commands/npm-ci#description) to install dependencies in automated environments

Those changes could be done along with updating the dependencies version format #4231 in every module.

**Comment by Marsup** [comment]
I strongly disagree there, it makes sense for apps, not for libraries. The disadvantage of having to maintain the lockfiles across all modules is a burden far greater than the advantages it provides. It's been stated by many actors (eg. https://www.twilio.com/blog/lockfiles-nodejs https://snyk.io/blog/what-is-package-lock-json/)

**Comment by spridev** [comment]
Fair point. The npm guidelines should probably mention the "apps vs libraries" use cases somewhere.
