### ISSUE TITLE
what options are there for commercially supported plan , and what is the SLA if any

### ISSUE THREAD

**Issue by haniyasin** [hapijs/hapi#4253]
for non VCed or bootstrapped startups , other than  the community driven support which is great but not enough IMO , is there a support plan with pricing levels and SLA? 

#### Support plan

* *is this issue currently blocking your project?* (yes/no):
* *is this issue affecting a production system?* (yes/no):

#### Context

* *node version*: 
* *module version*: 
* *environment* (e.g. node, browser, native): 
* *used with* (e.g. hapi application, another framework, standalone, ...):
* *any other relevant information*:

#### How can we help?

```js
const some = 'properly formatted code example';
```

**Comment by Nargonath** [comment]
The latest version of `hapi` is only available as a community driven version. There are commercial versions supported by @hueniverse but for legacy `hapi` versions.

**Comment by devinivy** [comment]
The [hapi hour](https://join.slack.com/t/hapihour/shared_invite/zt-g5ortpsk-ErlnRA2rUcPIWES21oXBOg) Slack is remarkably responsive when folks provide well-defined questions and problem statements— while there's certainly no SLA, you may be surprised just how far the community support can go!
