### ISSUE TITLE
How do I delete/unregister hapi server.method for caching

### ISSUE THREAD

**Issue by humorean** [hapijs/hapi#4254]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: 10.16.3
* *module version*:  17.8.5
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*: NA

#### How can we help?

I registered a server.method for caching (memcache) purpose. But it seems to stick with cache for a long time and I can't find any documentation to delete this method or cached object and I always see this method in the application tab in developer tools.
```js
`const getInfo = () => {
            return {name: "Joe"};
          };

server.method("getUser", getInfo, {
            cache: {
              cache: "_default",
              expiresIn: 100000,
              generateTimeout: false
            }
          });`

```
Then when I check if this exist, it always return true and the object from getInfo.

`const source = server.methods.getUser && server.methods.getUser();` // always return true

How do I clear this data?  Like manually in code.

**Comment by arafel** [comment]
Hi

Looking at [the API ](https://hapi.dev/api/?v=20.1.3#-servermethodname-method-options) it looks like you want the `drop()` function from the `server.methods["getUser"].cache` object that was created.

> When configured with caching enabled, server.methods[name].cache is assigned an object with the following properties and methods:
> - await drop(...args) - a function that can be used to clear the cache for a given key.

**Comment by devinivy** [comment]
Agree!  If you want to invalidate the entire cache then you can also specify a `cache` for your server method with a different `cache.segment`.  The segment name defaults to `#{name-of-method}`.
