### ISSUE TITLE
Feature Session Start and End Event

### ISSUE THREAD

**Issue by govTechSatish** [hapijs/hapi#4255]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v16
* *module version*: 20.0.3
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): Hapi application
* *any other relevant information*: I want to catch the Session End event and redirect the user to a custom page.

#### How can we help?

```js
const some = 'properly formatted code example';
```

**Comment by devinivy** [comment]
hapi itself doesn't have a concept of sessions, so I am not sure if there's anything actionable here for us.  If you can be more specific I'd be happy to carry on the conversation, though.  You might be interested in checking-out [yar](https://github.com/hapijs/yar) and [request extensions](https://hapi.dev/api/#server.ext())! 👍
