### ISSUE TITLE
NOT A BUG.

### ISSUE THREAD

**Issue by nkurothe1** [hapijs/hapi#4266]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): No
* *is this issue affecting a production system?* (yes/no): No

#### Context

* *node version*:  N/A
* *module version*:  N/A
* *environment* (e.g. node, browser, native): N/A
* *used with* (e.g. hapi application, another framework, standalone, ...): N/A
* *any other relevant information*: This is not a bug in hapi, I wanted to get an understanding of the branching strategy that you guys use.

We have internal node modules and the branching and versioning strategy that we used to follow was fine till a point, now it's not aligning with our needs. So, I am working towards creating a new strategy, which is more or less what I have seen in the public node modules like yours. I have two questions. How and when do the release branches you have, get merged to master? After that, how do you pull the master into various other release branches that are not released yet?

**Comment by Nargonath** [comment]
We don't have an automated release process for now nor do we have a `release` branch. Every feature branch is created from `master` and merged into it. Once we reached a state we want to publish we run the `npm` commands manually from our local environment. If we need to maintain a legacy version we usually create a branch that branches out of `master` at a specific point and we work on that branch. `master` will never be merged into this branch or the other way around either. If you want an example of such branches look at the `v*-commercial` branches.

Hope this helps.
