### ISSUE TITLE
Headers are lower-cased

### ISSUE THREAD

**Issue by lucasff** [hapijs/hapi#4267]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

I'm using `hapi` through `serverless-offline`.
I found out this PR https://github.com/hapijs/hapi/pull/2866 basically adds code to lowercase the headers sent by the consumer. I have a requirement that the client looks for the header "X-Total-Count" and because of the lowercasing, this fails.

#### What result did you expect?

Headers to be passed through without modification.
Am I wrong here?

**Comment by devinivy** [comment]
The headers are lowercased intentionally, and this is in line with [how node's builtin http module works too](https://nodejs.org/api/http.html#http_message_headers).  The idea is that headers are case-insensitive per the spec, so most of the time it's beneficial to be able to assume the casing .  By convention node and hapi use lowercasing.  Node [does offer a way](https://nodejs.org/api/http.html#http_message_rawheaders) to access the raw headers, and they are received as an array.  In hapi you can access those as `request.raw.req.rawHeaders`.

**Comment by lucasff** [comment]
@devinivy that totally makes sense, thanks for your support. I'll try to see what serverless-offline can do for the implementation so that the rawHeaders are used somehow (maybe).
wish you a great weekend 🚀
