### ISSUE TITLE
request.socket missing from injected requests

### ISSUE THREAD

**Issue by mikeatkins** [hapijs/hapi#4268]
#### Support plan

* *is this issue currently blocking your project?*: yes
* *is this issue affecting a production system?*: yes

#### Context

* *node version*: 14.x
* *module version with issue*: all
* *last module version without issue*: all
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application w/ datadog tracing
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

In node 10.x and 12.x request.socket and request.connection were aliased. Starting with node 13.x, request.connection is no longer available. simulated requests as created by server.inject attach a connection property but not a socket property. I understand that there is no actual socket, but some libraries such as dd-trace expect there to be a request.socket property (and throw exceptions if it is missing).

#### What was the result you got?

server crashed, due to library checking for `request.socket.encrypted` 

#### What result did you expect?

request.socket to be same as request.connection

**Comment by kanongil** [comment]
I'm not sure I would classify this as a hapi bug since *there is no actual socket*. I would suggest that this is fixed in whatever external code that expects a socket.

If this is not feasible, you can try to file a an enhancement request / PR against [`hapijs/shot`](https://github.com/hapijs/shot) to create a fake `socket` property. We would need to understand more details on how the external code uses it though. Also, this is dangerous, as it could break existing code that relies on it being`undefined`.

**Comment by mikeatkins** [comment]
@kanongil - thanks for your quick response. Regarding the fact that there is no actual socket, there is for that matter no actual _connection_ either. However, these properties on an actual http request in node are actually one and the same.. afaik, they refer to the same object. If the goal of an injected request is to simulate an actual request as closely as possible, then I would think it would be desirable to include both properties (for versions of node that include both). 

note: I may have been mistaken above when I said that `.connection` was removed in node 13.x. It was deprecated, but might still be available.

In any case the specific use case I had in mind was for dd-trace which is an instrumentation library need for application monitoring with datadog . There are similar libraries for new relic and other application monitoring software packages. dd-trace was updated recently to keep in line with changes in node, i.e. to respect the deprecation of `.connection`. The specific change to that library can be seen here:  https://github.com/DataDog/dd-trace-js/pull/1372. Arguably it does not make sense to be instrumenting "fake" requests (I'll raise this with the dd-trace folks), but regardless, IMHO it would also be good for shot to include `.socket` for consistency with real requests. I'll look into creating a PR against shot, and I'm happy to move the conversation there.

**Comment by mikeatkins** [comment]
dd-trace was fixed for this, so I'll go ahead and close this.
