### ISSUE TITLE
My computer can't send post requests to a hapi version 18.1.0 server.

### ISSUE THREAD

**Issue by zhiwenh** [hapijs/hapi#4272]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): Yes
* *is this issue affecting a production system?* (yes/no): Yes

#### Context

* *node version*: 16.5.0
* *module version*: 18.1.0
* *environment* (e.g. node, browser, native): node 
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*:

#### How can we help?

Hello. I'm having issues sending post requests to my hapi server. When I send post requests with curl to my hapi server it shows that a process is running but nothing gets returned. It just stalls indefinitely. Here is the code I'm trying to run:

```
const hapi = require('hapi');

const server = hapi.server({
      port: 3000,
      host: 'localhost'
});

// route
server.route({
    method: 'GET',
    path: '/aboutus',
    handler: (req, h) => {
      console.log('here1');
      return '<h1>About Us</h1>'
    }
})

server.route({
    method: 'POST',
    path: '/post',
    handler: (req, h) => {
      console.log('here2');
      return 'post';
    }
})

const bootUpServer = async () => {
      await server.start();
      console.log(`Server is running at ${server.info.uri}`);
      process.on('unhandledRejection', (err) => {
             console.log(err);
             process.exit(1);
     })
}

bootUpServer();
```

And here is the request I'm trying to send:
```
curl -X POST http://localhost:3000/post 
```

I tried using the latest version of hapi, version 20.1.5, and post requests worked fine. However the application my company is building runs on hapi version 18.1.0. My coworker was able to send post requests with the code above but I wasn't.

**Comment by Marsup** [comment]
Can you show the curl logs, please? (in verbose mode would be better)

**Comment by kanongil** [comment]
Node 16 is only supported on the latest Hapi v20 release. I suggest you update, or use node 14.
