### ISSUE TITLE
Server settings not initialized as documented

### ISSUE THREAD

**Issue by jonathansamines** [hapijs/hapi#4285]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): No
* *is this issue affecting a production system?* (yes/no): No

#### Context

* *node version*: 12.22.6
* *module version*: 20.2.0
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*:

#### How can we help?

From hapi's documentation for [server app](https://hapi.dev/api/?v=20.1.4#-serveroptionsapp), seems like `server.settings.app` must have a default value equal to `{}`, but that doesn't seem to be the case as demonstrated by the test below:

```js
'use strict';

const Hapi = require('@hapi/hapi');
const assert = require('assert');

const server = Hapi.server();
const serverWithInitialSettings = Hapi.server({ app: {} });

assert.deepStrictEqual(serverWithInitialSettings.settings.app, {}); // suceeds
assert.deepStrictEqual(server.settings.app, {}); // fails
```

Should we update the implementation to match the documentation or the other way around? Or maybe I am reading the documentation wrong?

**Comment by devinivy** [comment]
I think you read it just right 👍 In my opinion we should sync-up the behavior with the documentation.  This will bring it in line with `route.settings.app`, where the default is set here: https://github.com/hapijs/hapi/blob/90cc2de3e256708540970c502ceb03940c2bf3e1/lib/route.js#L94
