### ISSUE TITLE
Reload a route?

### ISSUE THREAD

**Issue by chaeron** [hapijs/hapi#4290]
Is there any way to reload/replace a route after the server is started?

I have a situation where a route, specifically JOI validations, are based on data in a database, and when the data changes, I would like to be able to reload the route so that it would reconfigure the JOI validations based on the changed data.

Thanks!

**Comment by devinivy** [comment]
There isn't a way to reload a route.  However, you may write your own custom validation functions, and those could be dynamic:
```js
server.route({
    method: 'get',
    path: '/',
    options: {
        validate: {
            query: async (value, options) => {
                // Custom/dynamic validation logic can go here
                const minForMyParam = await getMinForMyParam();
                if (value.myParam < minForMyParam) {
                    throw Boom.badRequest(`myParam must be at least ${minForMyParam}`);
                }
                return value;
            }
        }
    }
});
```
