### ISSUE TITLE
Remove return value from generateResponse() prepare method

### ISSUE THREAD

**Issue by kanongil** [hapijs/hapi#4299]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): probably not

#### Context

* *node version*: any
* *module version*: 20.2.1
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...):
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

The [request.generateResponse()](https://hapi.dev/api?v=20.2.0#-requestgenerateresponsesource-options) takes a `prepare(response)` option that must return a response (existing or new).

https://github.com/hapijs/hapi/blob/404d2534e73350eb25188bd06fa638f74f8f54e4/lib/toolkit.js#L104-L106
https://github.com/hapijs/hapi/blob/404d2534e73350eb25188bd06fa638f74f8f54e4/lib/response.js#L510

Returning anything other than the existing response is however *fundamentally broken* since:

1. Returned value is not validated for correctness.
2. It causes the `close()` option to never be called.
3. It is not feasible to actually create, since there is no Toolkit to create it from. Only `request.generateResponse()` is available, and if used can break since the `prepare()` option is never called for it.

Given the above, I expect the feature has never been used and I suggest it is simply removed. Especially since there is no test code that covers this, or any pertinent use cases. Any return value should just be ignored. The feature is likely a vestige from when returned errors would be handled.

FYI the `generateResponse()` `prepare` option is currently only used in [inert](https://github.com/hapijs/inert/blob/f932e40afed47dc2eba9572d19b180b9dee0f782/lib/file.js#L95-L136) and [vision](https://github.com/hapijs/vision/blob/8bf34dba68743ed08790e17334e4f4b7c288dda6/lib/manager.js#L568-L573).

**Comment by kanongil** [comment]
While this is definitely a breaking change (the docs will have to change), I feel that it would be fair to remove such a broken feature on the current release.

**Comment by devinivy** [comment]
I fully agree that this is broken, but I do have some concerns about removing it in v20.  If someone is using the functionality, updating this and changing their responses could have worse effects for them than the bugs mentioned above.  And if nobody is using it, then this issue doesn't affect anyone.  I would be all for updating the docs now to discourage the behavior, then updating the code in v21.  I also would be open to handling the case of no return value in v20 by assuming the response hasn't been changed.

**Comment by kanongil** [comment]
I guess you are right. My main concern is that someone might add new code that tries to depend on this. But that is probably quite unlikely.

**Comment by devinivy** [comment]
Resolved with v21 https://github.com/hapijs/hapi/issues/4386
