### ISSUE TITLE
State override not working

### ISSUE THREAD

**Issue by meusx** [hapijs/hapi#4303]
#### Support plan

* *is this issue currently blocking your project?* yes:
* *is this issue affecting a production system?* no:

#### Context

Node : v14.17.6 
"@hapi/hapi": "20.1.5" 
* *environment* :  browser
* *used with* :  hapi application
* *any other relevant information*: Using handlesbar

#### How can we help?

I am trying to save cookies but for some reason it is settings in the first access but the when I try to override it does not work

Server: 
```js
server.state("dd", {
        ttl: null,
        isSecure: false,
        encoding: "base64json",
        clearInvalid: false,
        strictHeader: true,
        isSameSite: false
});
```

Some where in the project I am setting the cookie like this
```js
var toSet = {
    valid: false
}
h.state("dd", toSet);
```
And I am able to access the cookie in other routes

But if I do a POST request the cookie does not change it 

That's the handler for the post request:
```js
{
    method: "POST",
    path: "/aaaaa",
    options: {
        state: {
            parse: true, 
             failAction: 'ignore' 
         },
         validate: {
              payload: Joi.object({
                  data: Joi.string().required()
                }),
          },
          handler: (request, h) => {
              return new Promise((resolve, reject) => {
                   data = {
                       valid: true
                   }

                    resolve(h.response(data).state("dd", data))
              })
           }
     }
}
```

Can someone help me please ?

**Comment by devinivy** [comment]
I see three different cookie names that you're using here: `d`, `dd`, and `data`.  Are you setting and reading the same cookie?  There are also many reasons that you may set a cookie but browsers may not send the cookie back to the server, such as incompatible path, domain, protocol.  If you could look at the request and response headers that the browser sees, that could be helpful to debug this 👍

**Comment by devinivy** [comment]
Welcome!  I tried to create a reproduction case here, and I wasn't able to see any issues: https://runkit.com/60c18db503676e001ce17d66/6164e477d66a9d000821774a.  Maybe you can alter this to show how to reproduce the issue.

One thing that stood out is that `dd` is specified twice in the `cookie` header, so `request.state.dd` will be an array of two objects rather than being an object, which might be unexpected.

**Comment by kiambote** [comment]
@devinivy the paths were the problem, http://localhost:7020/rgt is the webpage itself but the route for the post request was http://localhost:7020/auth/native that's why the cookies were duplicated, I fixed the path on the routes and its working perfect now. One more time thank you!
