### ISSUE TITLE
TypeError: code is not a function - Discord.js

### ISSUE THREAD

**Issue by TheDevNoah** [hapijs/hapi#4310]
const code = require("@hapi/code");

 const suggestontoken = code(10);
            let embed = new Discord.MessageEmbed()
         .setAuthor(message.author.username , message.author.displayAvatarURL())
         .setDescription(suggest)
         .setFooter(`Suggestion Token: ${suggestontoken}`, message.guild.iconURL())      
        .setTimestamp()
        check.send(embed).then(m => {
          m.react('✅')
          m.react('❌')
          message.author.send(`Suggestion Creaed in ${message.guild.name}\nYou will be DM'd when a admin replies.`)
          db.set(`suggest_${suggestontoken}`, m.id)
           db.set(`suggest_${suggestontoken}_msg`, suggest)
          db.set(`suggest_${suggestontoken}_user`, message.author.id)
          message.channel.send(`Suggestion Sent!`)
          
          
```When doing that I constantly get 'TypeError; code is not a function;```

**Comment by cjihrig** [comment]
Code is not a function. It is a module that you can import with its own methods. Please check out the tests in https://github.com/hapijs/hapi/tree/master/test for examples of how to use the library.
