### ISSUE TITLE
Invalid cookie when using google one tap, potential parsing problems?

### ISSUE THREAD

**Issue by bdanzer** [hapijs/hapi#4313]
On my client side I am using credentials: true with my fetching and it's sending my cookies automatically. If I remove ` g_state={"i_l":0}` it will work but if I keep it I will get this response:

```javascript
{"statusCode":400,"error":"Bad Request","message":"Invalid cookie value"}
```

Here is the headers in the req

```javascript
accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Content-Length: 1523
content-type: application/json
Cookie: cookieName=cookieContent; g_state={"i_l":0}
Host: localhost:3000
Origin: http://localhost:8080
Referer: http://localhost:8080/
sec-ch-ua: "Google Chrome";v="95", "Chromium";v="95", ";Not A Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
```

Is this potentially due to something not parsing correctly in this package?

**Comment by devinivy** [comment]
I believe the issue here is the double-quotes in the cookie value `g_state={"i_l":0}`, which is technically invalid.  I would recommend url-encoding the cookie value to pass those quotes.  You can also tell hapi to ignore this cookie when it is invalid, or to allow invalid values, with the `ignoreError` and `strictHeader` options of [`server.state()`](https://hapi.dev/api?v=20.2.0#server.state()).

**Comment by bdanzer** [comment]
I don't pass these cookies manually, they are being included automatically. It's really hard to set up a testable scenario too since I am using google one-tap api. 

I am using apollo and from google searching the error message seemed to be coming from this package that apollo uses. So I'm not actually using this package directly in my project, it's being used by the apollo team so I'm not sure if it's something they could change. I did also open a bug on their repo about this so not sure if it's a bug yet or which package would need a change but this seems like unintended behavior.

In my case it's using apollo client httplink to build the link

```javascript
const link = new HttpLink({
  uri: process.env.REACT_APP_GRAPH_QL_URI,
  credentials: 'include'
});
```

But the google one tap api is automatically setting that cookie and then when I go to make the request I have `credentials: 'include'` and it will send the cookie headers automatically and it's sending that `g_state={"i_l":0},` value automatically.

So I'm not sure what to do exactly, for now I am overwriting that `g_state` cookie but I have a suspicion that in the scenario where a withCredentials/credentials is being used with google one tap this package is going to fail it.

**Comment by devinivy** [comment]
It sounds like you're in a situation where ignoring the invalid cookie using `ignoreError` or allowing it using `strictHeader` is going to be your best bet.  These options exists as an escape hatch for exactly these kinds of situations 👍 
```js
server.state('g_state', { ignoreErrors: true });
```

**Comment by bdanzer** [comment]
I ended up figuring out that it was the serverless-offline package there is a flag `--disableCookieValidation` that I guess sets some options for hapi. Appreciate the quick response on this, def helped me go down a different direction of troubleshooting.
