### ISSUE TITLE
how to add objects of user to artifacts?

### ISSUE THREAD

**Issue by Tarique06** [hapijs/hapi#4318]
#### Support plan

* *is this issue currently blocking your project?* (yes/no):
* *is this issue affecting a production system?* (yes/no):

#### Context

* *node version*: 
* *module version*: 
* *environment* (e.g. node, browser, native): 
* *used with* (e.g. hapi application, another framework, standalone, ...):
* *any other relevant information*:

#### How can we help?

```js
const some = 'properly formatted code example';
```

**Comment by Tarique06** [comment]
I have created a user table which has user_id, username, email and password. while performing log in, i am using email and password. now when i console log the request body i am getting only email in my artifacts. i want to also have username. Kindly help, guide me how to

**Comment by johnmanko** [comment]
A better place to ask this would be on SO: https://stackoverflow.com/questions/tagged/hapijs
