### ISSUE TITLE
Seems overly strict about trailing slash

### ISSUE THREAD

**Issue by ghostdevv** [hapijs/hapi#4320]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): kinda
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: 16.9.1
* *module version*: 20.2.1
* *environment* (e.g. node, browser, native): any
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi
* *any other relevant information*: 

#### How can we help?

I was wondering what the difference is (for example) between `/users/` and `/users` - if I define a route with the path of `/users` I get a 404 when going to `/users` which seems weird as surely they should be the same

**Comment by devinivy** [comment]
Glad to report hapi has a setting for this :) You can configure the router with `stripTrailingSlash` as `true` if you'd prefer that behavior: https://hapi.dev/api#server.options.router.
```js
const server = Hapi.server({
    router: { stripTrailingSlash: true }
});
```

**Comment by ghostdevv** [comment]
Amazing! thank you @devinivy
