### ISSUE TITLE
Hapi doesn't give proper response to post request even though the response appears on console.log

### ISSUE THREAD

**Issue by sayo96** [hapijs/hapi#4322]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): Yes
* *is this issue affecting a production system?* (yes/no): No

#### Context

* *node version*: 16.13.1
* *module version*: 16.0.3
* *environment* (e.g. node, browser, native): Mac os 12.1 
* *used with* (e.g. hapi application, another framework, standalone, ...): Hapi application
* *any other relevant information*:  I'm running into this bug on my 14 inch macbook pro with apple silicon chip

#### How can we help?

I have logic in place that gets access token for a user if they enter valid credentials.  But due to some weird reason when i send the email password to the hapi js backend server, a token is being generated but it never reaches the client side . 
When I test the same using postman the request keeps on loading 

Here is the route  
```js
server.route({
    method: 'POST',
    path: '/tokens',
    handler: tokens.create,
    config: {
      auth: false,
      description: 'Create authentication token for user',
      tags: ['auth', 'user', 'token', 'client:token.create'],
      validate: {
        payload: {
          email: Joi.string().email().required(),
          password: Joi.string().required(),
          expirationDate: Joi.number().optional(),
        }
      }
    }
  });
```

Here is my controller :
``` js
create(request, reply) {

    var email = request.payload.email;
    var password = request.payload.password;
    var expirationDate = request.payload.expirationDate || moment().add(3, 'months').valueOf();

    var promise = UserModel.findByCredentials(email, password)
      .then((user) => {
        if (!user) throw new errors.UnauthorizedError('No user found');

        return {
          access_token: jwt.encode(
            {
              id: user._id, 
              date_exp:  expirationDate//Token expires in 3 months 
            },
            envCfg.apiSecretKey
          )
        };
      });

    utils.standardResponse(promise, reply);

  },
```
Here is my standard response method

```
standardResponse(promise, reply, request) {

    Promise.resolve(promise)
      .then(function (doc) {

        if (!doc) return reply(boom.notFound());

        //For delete, don't expect an object
        if (request && request.method === 'delete' && !doc) return reply(null).code(200);
         
        console.log('token', doc);
        reply(doc);

      })
      .catch(errors.ConflictError, function (err) {
        return reply(boom.wrap(err, 409));
      })
      .catch(errors.InvalidRequestError, function (err) {
        return reply(boom.wrap(err, 400));
      })
      .catch(errors.NotFoundError, function (err) {
        return reply(boom.wrap(err, 404));
      })
      .catch(errors.ForbiddenError, function (err) {
        return reply(boom.wrap(err, 403));
      })
      .catch(errors.UnauthorizedError, function (err) {
        return reply(boom.wrap(err, 401));
      })
      .catch(function (err) {
        console.warn("Unknown error type caught in standard response handler", err.message);
        console.warn(err.stack);
        reply(boom.wrap(err, 500));
      });
  },
  ```

Here is what i have found . I'm getting the token on the console message above `reply(doc)` but due to some weird reason it never reaches front end

Postman screenshot

<img width="1199" alt="Screenshot 2021-12-08 at 6 56 39 PM" src="https://user-images.githubusercontent.com/26695583/145216134-a5a1b6d0-0851-4724-b978-51bc54d1a547.png">

Browser network tab ( firefox /chrome)
<img width="1351" alt="Screenshot 2021-12-08 at 6 57 25 PM" src="https://user-images.githubusercontent.com/26695583/145216302-bc2ac0d1-2395-4127-9057-900988df3ead.png">

I have an hunch i'm missing something simple but i'm not able to figure it out as i'm not familiar with hapi yet

**Comment by kanongil** [comment]
You need to update to the latest hapi, for compatibility with node v16+.

**Comment by sayo96** [comment]
I forgot to mention but i ran node 10.24.1 using nvm when i ran into this

**Comment by sayo96** [comment]
> You need to update to the latest hapi, for compatibility with node v16+.

Please reopen the issue and please educate me on what i'm doing wrong

**Comment by kanongil** [comment]
We only support v20+ hapi. There is a commercial version of v16 with paid support, but I think that has expired by now.

**Comment by sayo96** [comment]
> We only support v20+ hapi. There is a commercial version of v16 with paid support, but I think that has expired by now.

Oh that's bad. Thanks for letting me know 🙏

**Comment by johnmanko** [comment]
> > We only support v20+ hapi. There is a commercial version of v16 with paid support, but I think that has expired by now.
> 
> Oh that's bad. Thanks for letting me know pray

The upgrade to Hapi 17+ isn't complicated.  I think that's the breaking-change version.  Here are the release notes with breaking changes identified.

https://github.com/hapijs/hapi/issues/3658
