### ISSUE TITLE
async lifecycle method

### ISSUE THREAD

**Issue by xiongemi** [hapijs/hapi#4323]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no 

#### Context

* *node version*: v14.17.0
* *module version*: 
"@hapi/boom": "7.4.11",
    "@hapi/hapi": "18.4.1",
    "@hapi/inert": "5.2.2",
    "@hapi/joi": "17.1.1",
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...):
* *any other relevant information*:

#### How can we help?

i need to write an interceptor that retries the requests if run into a specific error code. however, i am thinking to use lifecycle event, but does it accept async function to lifecycle?

**Comment by devinivy** [comment]
Yes, [lifecycle methods](https://hapi.dev/api/?v=20.2.1#lifecycle-methods) may be asynchronous 👍
