### ISSUE TITLE
Typescript error on `server.events.on()` when using custom events

### ISSUE THREAD

**Issue by rajeevnaikte** [hapijs/hapi#4325]
#### Support plan
* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 16.1.0
* *module version with issue*: 20.2.1
* *last module version without issue*: NA
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): Hapi application

#### What are you trying to achieve or the steps to reproduce?
Trying to use custom events option as below.
```
const server = hapi.server();

server.event('onTlsRequest');
server.events.on('onTlsRequest', () => doSomething());
```

#### What was the result you got?
Getting typescript error for the function - `server.events.on()`
```
Argument of type '"onTlsRequest"' is not assignable to parameter of type '"stop" | ServerEventCriteria<"stop">'.
```

#### What result did you expect?
No typescript error.

**Comment by kanongil** [comment]
Hapi does not expose typescript types. I expect you are using ones by the DefinitelyTyped project, which is where this needs to be handled: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/hapi/index.d.ts
