### ISSUE TITLE
How to set custom route options for extensions?

### ISSUE THREAD

**Issue by nclsndr** [hapijs/hapi#4330]
#### Support plan

* *is this issue currently blocking your project?* yes
* *is this issue affecting a production system?* no

#### Context

* *node version*: 16.13
* *module version*: 20.2.1
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*: custom authentication Schemes & Strategies

#### How can we help?

Hi there, I've been crawling the docs and quite some issues without finding this answer. I hope I'm not opening a duplicate...

The issue: I'd like to have a static param I can set while declaring the route, for an extension (onPostHandler) to react against the value I set.

I have a route like:
```ts
{
  method: 'POST',
  path: '/my-route',
  options: {
    handler: controller.myRoute,
    validate: validate.myRoute,
    auth: 'jwt',
}
```

but I'd like to add a custom option like: 
```ts
{
  method: 'POST',
  path: '/my-route',
  options: {
    handler: controller.myRoute,
    validate: validate.myRoute,
    auth: 'jwt',
    extra: {
      someKeyDefinedForExt: true
    }
}
```

and then have some kind of exposure on ext handlers like:
```ts
server.ext('onPostHandler', (request, h) => {
  if(request.extra.someKeyDefinedForExt) {
    // ...
  }
  // OR
  if(h.extra.someKeyDefinedForExt) {
    // ...
  }
});
```

Are there some ways to achieve such configuration?

**Comment by devinivy** [comment]
Yeah, there is a way to do that.  You can place custom configuration in `options.app`, or if it's plugin-specific `options.plugins[pluginName]` 👍 Feel free to join us in the hapi hour Slack for questions like this too: https://join.slack.com/t/hapihour/shared_invite/zt-g5ortpsk-ErlnRA2rUcPIWES21oXBOg

**Comment by nclsndr** [comment]
Amazing thx @devinivy! I'm now able to set a key in options. Nevertheless, I got an empty result when accessing:
```ts
server.ext('onPostHandler', (request, h) => {
  request.app // is actually {}
});
```

**Comment by devinivy** [comment]
You will want to check `request.route.settings.app`.

**Comment by nclsndr** [comment]
Oh! that's interesting! Thank you again for the quick answer @devinivy!
It's working perfectly. For pure curiosity, what's the intent of `request.app` then?

**Comment by devinivy** [comment]
That would be for application state that can be different on each request to your server.  For example, request extensions can share some state there that wont affect other concurrent requests.  The route's `app` is read-only configuration for the route itself.
