### ISSUE TITLE
How to Return Stream

### ISSUE THREAD

**Issue by davidkavanaugh** [hapijs/hapi#4332]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): No
* *is this issue affecting a production system?* (yes/no): No

#### Context

* *node version*:  10.12.21
* *module version*: 19.2.0
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*:

#### How can we help?

What's the best way to return a stream with hapi? Please show me some documentation, if available. 

```js
return h.response(Buffer);
```

**Comment by kanongil** [comment]
```js
return stream;
```

https://hapi.dev/api?v=20.2.0#lifecycle-methods
