### ISSUE TITLE
Unable to resolve Localhost to Localhost CORS Issue

### ISSUE THREAD

**Issue by teknosains** [hapijs/hapi#4334]
#### Support plan

* *is this issue currently blocking your project?* (**yes**/no):
* *is this issue affecting a production system?* (yes/**no**):

#### Context

* *Node Version*: v14.16.0 
* *Hapi Version*: 20.2.1 
* *environment* (e.g. node, browser, native): browser
* *used with* (e.g. hapi application, another framework, standalone, ...): ReactJS Frontend
* *any other relevant information*:

#### How can we help?

Im developing both API (Hapi) and the frontend (React n Axios). I simply want to be able to call the API from the React/Axios

API (Hapi) => http://localhost:3100
React/Axios => http://localhost:3000

Heres my Hapi server

```js
const server = Hapi.server({
        port: 3100,
        host: 'localhost',
        routes: {
            validate: {
                failAction: (request, h, err) => {
                    console.log(err)
                    throw err;
                }
            },
            cors: {
                origin: ['*'],
            }
        }
    });
```

and the axios (i run the frontend from a browser (http://localhost:3000))

```js
let response = await axios.post('http://localhost:3100/v1/auth/login', {
	email: payload.email,
	password: payload.password
});
```

The error:

```
Access to XMLHttpRequest at 'http://localhost:3100/api/v1/auth/login' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

I've tried also what i found on this issue: [Backend and Frontend running on different port but same domain but getting CORS error](https://github.com/hapijs/hapi/issues/4198) 

yet still no luck

Thank u

**Comment by devinivy** [comment]
One common cause of this issue (when CORS is otherwise correctly configured) is when the request is to a route that doesn't exist on the hapi server.  Can you confirm that there's a route at `post /api/v1/auth/login`?  I also notice that the client-side code has a different route `/v1/auth/login`, so perhaps there could be some confusion there.  One simple way to check this is to `curl` the route from your terminal rather than through the browser.

**Comment by teknosains** [comment]
> One common cause of this issue (when CORS is otherwise correctly configured) is when the request is to a route that doesn't exist on the hapi server. Can you confirm that there's a route at `post /api/v1/auth/login`? I also notice that the client-side code has a different route `/v1/auth/login` compared to the error message, so perhaps there could be some confusion there. One simple way to check this is to `curl` the route from your terminal rather than through the browser.

ooh man, you're very right....I hit a wrong endpoint (that doesnt exist on the hapi). 

thanks for pointing out
