### ISSUE TITLE
How to catch and transform error

### ISSUE THREAD

**Issue by ifynk** [hapijs/hapi#4336]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 12.19.0
* *module version*: 20.2.1
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*:

#### How can we help?

Hello. How i can to catch any error from the handler and reformat it to another status for example. I have tried to use failAction callback for this, but it is not triggered.
```js
  server.route({
    method: 'POST',
    path: '/auth/login',
    handler: () => {
      throw new Error('Some error');

      return 123;
    },
    options: {
      response: {
        failAction: (req, h, err) => { console.log('failAction', err); throw err; },
      },
    },
  });
```
Expected behaviour
```js
  server.route({
    method: 'POST',
    path: '/auth/login',
    handler: () => {
      throw new Error('Some error');

      return 123;
    },
    options: {
      response: {
        failAction: (req, h, err) => { throw Boom.badRequest(err.msg); },
      },
    },
  });
```
Throws 400 error with message 'Some error'

**Comment by jonathansamines** [comment]
Hello, @ifynk  I think you can do that using an `onPreResponse` extension:

```js
const preResponse = function (request, h) {

    const response = request.response;
    if (response.isBoom) {
        response.output.statusCode = 400;
    }

    return h.continue;
};

server.ext('onPreResponse', preResponse);
```

There is additional information at the end of the [error transformation](https://hapi.dev/api?v=20.2.1#error-transformation) docs that you mind find useful.

**Comment by ifynk** [comment]
Thanks @jonathansamines, i tried your solution, but **onPreResponse** don't triggered when error throws from the handler.

**Comment by devinivy** [comment]
The onPreResponse request extension should trigger even when there is an error in the handler.  Here is an example: https://runkit.com/devinivy/620d0768bd49de0008322d5a

More more information, here are the docs on the request lifecycle: https://hapi.dev/api?v=20.2.1#request-lifecycle
