### ISSUE TITLE
Is it possible to disable the gzip compression for specific route?

### ISSUE THREAD

**Issue by kumark86** [hapijs/hapi#4337]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: 12.22.5
* *module version*: hapi - 17.3.0
* *environment* (e.g. node, browser, native):  node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi and react
* *any other relevant information*:

#### How can we help?

We have tried the disable compression in server level. It's working fine. But we want to disable the gzip compression to specific route. Because we are serving some static files, which really need gzip compression. But for other routes like JSON response, this gzip compression cause security issue.

Please advise how to disable the compression(gzip) for specific route?

**Comment by kumark86** [comment]
@kanongil thanks. Yes I will try it. Is there any security issues there while using the `content-encoding: identity`?

**Comment by devinivy** [comment]
I don't know of any security issues with not using an encoding in this way, but I can only speak from the perspective of the framework, and if you have a concern I'd recommend finding an expert to consult for your particular use-case 👍

**Comment by kumark86** [comment]
Please take this request as enhancement for disable the GZIP compression for specific route.
