### ISSUE TITLE
Hello World app with default route has potential leak

### ISSUE THREAD

**Issue by liras** [hapijs/hapi#4338]
#### Support plan

* *is this issue currently blocking your project?* (yes/no):yes
* *is this issue affecting a production system?* (yes/no):no

#### Context

* *node version*: v12.22.10
* *module version*: 20.2.1
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*: Mac OS 10.15.7

#### How can we help?

I've been working on what appears to be a memory leak issue with a hapi application and decided to see what the default behavior looked like.  I went back to the "Hello World" sample to do some investigating.  I've been tracing through a heap snapshot from the Hapi hello world js as is - hitting the default route 1000 times and then taking the heap snapshot and looking in Dev Tools at it.  It seems that there are objects that do not seem to be reclaimed by the garbage collector including "Response", "Request", "Socket" and a ton of Promises for each one of those requests.  You can see the counts in the screenshot of Dev Tools.  I feel like I'm chasing ghosts a bit.  Is this normal behavior??

Taken from hapi.dev:
```js

'use strict';

const Hapi = require('@hapi/hapi');

const init = async () => {

    const server = Hapi.server({
        port: 3000,
        host: 'localhost'
    });

    server.route({
        method: 'GET',
        path: '/',
        handler: (request, h) => {
            return 'Hello World!';
        }
    });

    await server.start();
    console.log('Server running on %s', server.info.uri);    
};

process.on('unhandledRejection', (err) => {

    console.log(err);
    process.exit(1);
});

init();

```
![image](https://user-images.githubusercontent.com/8240699/154344485-67b542e3-3235-493e-9757-1dde48128d85.png)

**Comment by devinivy** [comment]
Hey, I just took a look at this and I wasn't able to reproduce the issue.  Here were my steps:
```
nvm install 12.22.10
nvm use 12.22.10
mkdir repro-leak && cd repro-leak
npm init
npm i @hapi/hapi@20.2.1
vi index.js # paste in contents of example above and save
node --inspect index.js
# Connect to debugger
# In separate terminal:
autocannon -a 1000 http://localhost:3000
# Take heap snapshot
```

In my heap snapshot I am seeing e.g. 4 Sockets, 0 Requests, 0 Responses, 3 Promises.  I ran the test a few more times in the same process, took additional heap snapshots, and am seeing the same thing.  Would you mind sharing similar details about how you're testing this out?

**Comment by liras** [comment]
devinivy - thanks for checking this out so quickly - I think I might have figured out what was going on - I was generating the heapdump from VS Code and I think the debugger had its hooks into the memory objects.  Once I used the heapdump package natively without a debugger attached, these references went away.  Probably wasted an entire week...

**Comment by devinivy** [comment]
Oh awesome!  Glad that's all it was 👍
