### ISSUE TITLE
Is nodejs required to be installed for hapi, or only Node is enough.

### ISSUE THREAD

**Issue by PatilAnuraag** [hapijs/hapi#4340]
#### Support plan

* *is this issue currently blocking your project?* (yes/no):
* *is this issue affecting a production system?* (yes/no):

#### Context

* *node version*: 
* *module version*: 
* *environment* (e.g. node, browser, native): 
* *used with* (e.g. hapi application, another framework, standalone, ...):
* *any other relevant information*:

#### How can we help?

```js
const some = 'properly formatted code example';
```

**Comment by devinivy** [comment]
We support node v12, v14, and v16.  Here's some more info on node releases: https://nodejs.org/en/about/releases/.
