### ISSUE TITLE
Reverse proxy connection to hapi server gets disconnected after 5 second idle time

### ISSUE THREAD

**Issue by ceisele-r** [hapijs/hapi#4344]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: 16.14.1
* *module version*: 20.2.1
* *environment* (e.g. node, browser, native): node, on Windows Server 2016
* *used with* (e.g. hapi application, another framework, standalone, ...): as Webserver for Apis and a react application
* *any other relevant information*:

#### How can we help?

We are using our hapi Webserver behind a Reverse Proxy that rewrites requests so they receive the hapi server:
```
Client Browser <-----> Reverse Proxy <-----> hapi Webserver
```

The issue is that the performance is not ideal as some requests are pretty slow causing high time-to-first-byte values for requests.

All test requests are made with static files so no further application logic is slowing down the request:
```typescript
  server.route({
    method: "GET",
    path: "/files/{name*}",
    options: {
      auth: false,
      cache: {
        expiresIn: CACHE_DURATION,
        privacy: "public",
      },
    },
    handler: {
      directory: {
        path: "../public",
        etagMethod: "simple",
        listing: false,
      },
    },
  });
```

I traced the issue down to the following (all requests made through the reverse proxy):
* When making an initial request, the proxy establishes a connection to the hapi server port (I can see that by checking the TCP connections) and serves the request - this takes ~1 second
* Subsequent requests to the same file reuse the same connection between the reverse proxy and hapi and take about ~12ms to be fulfilled
* As soon as there is no request for 5 seconds, the TCP connection between the reverse proxy and the hapi server gets closed by the hapi server (at least that's what I saw from the TCP packets - hapi sends `FIN` to the reverse proxy which then by itself acks that and `FIN`s the connection).
* A subsequent request needs to establish a new connection between the reverse proxy and hapi and therefore takes ~1s again

**=> So overall, after 5 seconds idle time, the connection between the reverse proxy and the hapi server gets closed which is causing the bad performance for the next request.**

Additionally, in order to further ensure this issue is relating to hapi and not the reverse proxy, when using a different target server, the reverse proxy keeps the connection open.

**So it feels like hapi serves the requests fast over the existing connection as long there is no idle time longer than 5 seconds. And once there is, it closes the connection to the client (=reverse proxy).**

Is there any way to prevent this?
As the reverse proxy and the hapi server are running on the same machine, the connection should be kept alive as long as possible to avoid the expensive connection initiation time.

Or is there a way to optimize the connection initiation time?

Is there any way or setting that can be

**Comment by devinivy** [comment]
That sounds like node's default HTTP [keep-alive timeout](https://nodejs.org/api/http.html#serverkeepalivetimeout).  If you'd like to control this, you can pass hapi a listener with any nodejs HTTP settings you like, e.g.:
```js
const Http = require('http');
const Hapi = require('@hapi/hapi');

const listener = Http.createListener();
listener.keepAliveTimeout = 0; // No timeout

const server = Hapi.server({ listener });
```

I believe this should work equally well too, since hapi exposes the listener:
```js
const Hapi = require('@hapi/hapi');

const server = Hapi.server();
server.listener.keepAliveTimeout = 0; // No timeout
```

**Comment by ceisele-r** [comment]
@devinivy thank you very much for the fast response and your help. It definitely looks like this resolves the issue. Thanks!
