### ISSUE TITLE
While using joi version 10.2.2 in hapi js this type of request.payload was getting accepted "target_locale": "[\"fr\"]" for array of strings. But after joi upgradation to 17.5.0 the same request.payload fails and getting error "target_locale" must be an array"

### ISSUE THREAD

**Issue by amititme68** [hapijs/hapi#4362]
#### Support plan

* *is this issue currently blocking your project?* (yes/no):yes
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: 16.13.1
* *module version*: 1.2.2
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*: We have hundreds of api's and we are not in a state to use joi.alternate for each request payload. Please suggest a way such that before joi validation I can change this "target_locale": "[\"fr\"]" to target_locale: ["fr"] such that joi validation passes for all routes in one go. We don't want to manually edit each request payload to accept escaped characters backslash(\). 
@hapi/hapi : 20.2.1
joi: 17.5.0
hapi-swagger:  14.2.4

#### How can we help?

```js
const some = 'properly formatted code example';
```

**Comment by devinivy** [comment]
Joi removed string-to-object coercion in joi v16.  I suggest taking a look at the release notes here https://github.com/sideway/joi/issues/2037, where they document how to support it again in the section titled "Array and object string coercion."
