### ISSUE TITLE
Support passport.js

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#437]

**Comment by pablocarreraest** [comment]
what happen to this plugin? @hueniverse can you recommend a good plugin for OAuth 2.0

**Comment by gergoerdosi** [comment]
@pablocarreraest: The repository is here: https://github.com/hapijs/travelogue. The README says:

> This module is no longer being maintained. There will be no future releases. Please migrate to either hapi-auth-cookie or bell.

**Comment by pablocarreraest** [comment]
thanks for the info @gergoerdosi what should plugin you will recommend me for made a oauth

**Comment by cjihrig** [comment]
@pablocarreraest check out https://github.com/hapijs/bell.

**Comment by pablocarreraest** [comment]
@cjihrig bell is for consume and I want to create a OAuth for a API project or I'm just not know what bell is for...

**Comment by cjihrig** [comment]
You might want to check out @geek's https://github.com/geek/OAuth.

**Comment by StarpTech** [comment]
@pablocarreraest do you know grant?  https://github.com/simov/grant

**Comment by pablocarreraest** [comment]
@cjihrig or @StarpTech I found https://github.com/dwyl/hapi-auth-jwt2 with some good examples.

thanks guys!
