### ISSUE TITLE
Alternative to hapi-router?

### ISSUE THREAD

**Issue by bonbonio** [hapijs/hapi#4374]
Hello,

Hapi Router only supports Hapi 19.x, and I currently use it to auto load my routes, is there an alternative out there as the hapi-router project seems dead; but the functionality was very handy indeed!

I used it like this

````
  try {
    await server.register({
      plugin: require('hapi-router'),
      options: {
        routes: './src/components/**/*Route.js',
      },
    });
  } catch (err) {
    console.log(err);
  }
````

Many thanks!

**Comment by devinivy** [comment]
You may be interested in haute-couture, which works a bit differently but achieves the same results and handles more than just routes: https://hapipal.com/docs/haute-couture#example

**Comment by bonbonio** [comment]
Unfortunately, I am not using imports, models or typescript so that example is quite hard for me to follow...

My routes are in src/routes/ as folders with a controller file and a route file that gets loaded as per regex.

This is an example of src/routes/Audit/AuditRoute.js, there are maybe 20 folders organised like this

````
'use strict';

const Joi = require('joi');
const AuditCtrl = require('./auditCtrl');

module.exports = (() => {
  return [
    {
      method: 'GET',
      path: '/audit',
      handler: AuditCtrl.getAudit,
      },
    },
    {
      method: 'POST',
      path: '/audit',
      handler: AuditCtrl.createAudit,
      },
    },
  ];
})();
````

and this is my index.js file which powers the server;

````
const Hapi = require('@hapi/hapi');

const init = async () => {
  const server = await new Hapi.Server({
    host: '0.0.0.0',
    port: 4000,
    routes: {
      cors: {
        origin: envConfig.origin,
        credentials: true,
        exposedHeaders: ['x-total-count']
      }
    }
  });

  await server.register([
    require('hapi-auth-jwt2'),
    require('@hapi/inert'),
    require('@hapi/vision'),
    {
      plugin: require('hapi-swagger'),
      options: {}
    }
  ]);

  try {
    await server.register({
      plugin: require('hapi-router'),
      options: {
        routes: './src/routes/**/*Route.js'
      }
    });
  } catch (err) {
    console.log(err);
  }

  try {
    await server.start();
    console.log('Server running at:', server.info.uri);
  }
};

init();
````

How might I load the routes? Forgive me for the asking but I spent most of the night on this, its a codebase I am trying to modernise, but this older functionality seems quite neat.

**Comment by devinivy** [comment]
Based on the info you've shared above, I believe it should look something like this:
```diff
-    await server.register({
-      plugin: require('hapi-router'),
-      options: {
-        routes: './src/routes/**/*Route.js'
-      }
-    });
+    await HauteCouture.compose(server, {}, { dirname: './src' });
```

If you have directories with names that haute-couture pays attention to (e.g. `src/models` or `src/plugins`) that would would rather it ignore, then you can disable that:
```js
    await HauteCouture.compose(server, {}, {
        dirname: './src',
        amendments: {
            models: false,
            plugins: false
        }
    });
```

If you are interested in using this and have more questions join us in the hapi slack #hapipal room (linked at the bottom of https://hapi.dev) or file an issue on haute-couture.  Another solution I've seen used is https://github.com/felixheck/wurst, though I don't know if it officially supports hapi v20.
