### ISSUE TITLE
Inconsistent dependencies between `@hapi/hapi` and ecosystem

### ISSUE THREAD

**Issue by SimonSchick** [hapijs/hapi#4377]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 16.x
* *module version with issue*: 20.2.2
* *last module version without issue*: n/a
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): app
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

We are always striving to avoid dependency duplication, especially since this can cause wildly unexpected behavior (instanceof checks failing etc.

We noticed that the hapi eco-system has started to drift apart in terms of dependency cohesivenes eg.

Some hapi plugins rely on versions of `@hapi/boom`, `@hapi/hoek` etc. that `@hapi/hapi` does not use/support yet, this is causing our build tools to issue warnings.

While hapi is build to tolerate this it would be great if these dependencies were streamlined.

<details>
<summary>Script that generates a dependency report</summary>

```ts
/* eslint-disable unicorn/no-process-exit */
/* eslint-disable no-console */
import { execSync } from 'node:child_process';

function uniqueBy<T, K extends keyof T>(arr: T[], key: K): T[] {
  const uniques = new Map<T[K], T>();
  for (const e of arr) {
    if (uniques.has(e[key])) {
      continue;
    }

    uniques.set(e[key], e);
  }

  return Array.from(uniques.values());
}

interface Dependent {
  version: string;
  dependencies?: Record<string, Dependency>;
}

interface Report extends Dependent {
  name: string;
  problems: unknown[];
}

interface Dependency extends Dependent {
  resolved: string;
}

interface TracedDependency extends Dependency {
  trace?: string[];
}

function flattenDeps(
  dep: Dependent,
  trace: string[] = [],
  out: Record<string, TracedDependency[] | undefined> = {},
) {
  if (dep.dependencies) {
    for (const [name, subDep] of Object.entries(dep.dependencies)) {
      const arr = out[name] ?? [];
      arr.push({
        ...subDep,
        trace,
      });

      out[name] = arr;
      flattenDeps(subDep, trace.concat(name), out);
    }
  }

  return out;
}

let json: string;
try {
  json = execSync('npm ls --json --prod --all', {
    stdio: ['pipe', 'pipe', 'ignore'],
  }).toString();
} catch (error) {
  json = (error as Error & { stdout: Buffer }).stdout.toString();
}

let problemsFound = false;
for (const [name, deps] of Object.entries(flattenDeps(JSON.parse(json) as Report))) {
  if (!deps) {
    continue;
  }

  const unique = uniqueBy(deps, 'version');
  const count = unique.length;
  if (count > 1) {
    problemsFound = true;
    console.error(
      `Duplicate dependency ${name} installed ${count} times ${unique
        .map((u) => u.version)
        .join(',')}!`,
    );

    for (const d of deps) {
      console.error(
        `${d.version.replace(`${name}@`, '').padStart(10)}: ${
          d.trace ? d.trace.join(' > ') : '<root>'
        }`,
      );
    }
  }
}

process.exit(problemsFound ? 1 : 0);
```

</details>

#### What result did you expect?

No duplicate dependencies when using official `@hapi/*` packages.

**Comment by devinivy** [comment]
We can't give this as a general guarantee, but we do tend to periodically sync everything up.  In particular, with the upcoming v21 release of hapi you should find minimal to no duplicate dependencies across the ecosystem.  Part of the reason you've probably noticed this recently is because many dependencies have been upgraded to support node v18 and drop node v12, and @hapi/hapi will be the final module to do so.  In the meantime, you may consider using the previous versions of those modules, which will be more in line with the dependencies used in the current version of @hapi/hapi.

If you notice that @hapi/hapi is using a _more_ up-to-date version of a given dependency than some other modules in the ecosystem, we also welcome PRs to bring those modules up to date 👍

**Comment by devinivy** [comment]
With hapi v21 released, this should be resolved.
