### ISSUE TITLE
Compress with Gzip/Brotli based on content size?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [hapijs/hapi#4380]
I'm trying to do something novel: choose which compression scheme (Gzip or Brotli) to send a response back, based on the dynamic content-size of the response once it's ready.

I'm familiar with existing approaches to configure compression in Hapi; I learned Hapi does Gzip by default; or you can also use plugins like https://github.com/kanongil/brok to configure Brotli compression instead.

But neither of these solutions allows choosing dynamically between Gzip/Brotli based on the size of the content to be compressed, which could vary on every request.

So what I'd like to do is turn Hapi compression OFF on my route in question, and do it myself by setting response header and using zlib.createBrotliCompress (or the Gzip alternative) as the final step in piping output to the response.

The biggest obstacle seems to be turning compression OFF for one specific route. Is this possible?

**Comment by kanongil** [comment]
I usually disable compression by setting a `content-encoding: identity` header on the response.

**Comment by GeoffreyPlitt** [comment]
But then I won't be able to send back compressed content

**Comment by GeoffreyPlitt** [comment]
Thanks!
