### ISSUE TITLE
Clarification on request being aborted

### ISSUE THREAD

**Issue by ConnorJBeck** [hapijs/hapi#4383]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: 14.19.1
* *module version*: 20.0.0
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): @hapi/boom, @hapi/inert, @hapi/vision
* *any other relevant information*:

#### How can we help?

Just looking for clarification on a particular error we are seeing occasionally. [In the documentation for the `request` event,](https://hapi.dev/api/?v=21.0.0-beta.1#-request-event) it lists one of the possible types of request events with the tags `request`, `error`, `abort` with only the description `the request was aborted`. We are seeing this error on our server, but it is unclear what is causing the abort - is the client aborting the request, or is the server aborting it? Is this a network issue, or an internal one? Sorry if this is common knowledge among server frameworks, I'm not too familiar with the concept of aborting requests in general so it's been very tough to debug, especially since it only occurs rarely.

**Comment by kanongil** [comment]
Yeah, unfortunately for `HTTP/1.x`, the only way a client can signal that it has lost interest in a not yet fully delivered server request, is to *simply close the connection to the server*. There is no protocol level signalling, unlike `HTTP/2` where the client can send an [`RST_STREAM`](https://httpwg.org/specs/rfc7540.html#RST_STREAM) frame.

**Comment by ConnorJBeck** [comment]
I see, thank you for the advice. I'll continue investigating then, but at least for now it seems extremely unlikely this is an issue with Hapi.

**Comment by Nargonath** [comment]
If you have suggestions on how you think the documentation could better express the meaning of the `abort` event, please feel free to open a PR @ConnorJBeck and we can discuss the improvements there.
