### ISSUE TITLE
Memory leaks detected in WSL but not in any other OS?

### ISSUE THREAD

**Issue by nikiwycherley** [hapijs/hapi#4384]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): No
* *is this issue affecting a production system?* (yes/no): No

#### Context

* *node version*: 18.10.0
* *module version*: 20.2.1
* *environment* (e.g. node, browser, native): WSL2 running an Ubuntu v20 instance
* *used with* (e.g. hapi application, another framework, standalone, ...): Node hapi application
* *any other relevant information*:

#### How can we help?

I have recently been forced to move from using Ubuntu to a WSL2 running Ubuntu. I have noticed since the move that when i run my unit tests i get a lot of memory leaks detected, these do not appear in Ubuntu or running the same code on a Mac? Is the an issue with running this in WSL? I know i can update how i run my tests to add all leakimg elements to ignore list but that didnt seam like the right route to take. Current way of running unit-tests is `npm run unit-test` unit-test in package.json is below

```js
"unit-test": "MY_APP_LOCAL_CACHE=true && lab --verbose -c -r console -o stdout -r lcov -o coverage/lcov.info",
```

**Comment by kanongil** [comment]
This sounds strange. Under WSL, it will run the same node binary as under Ubuntu. And for WSL2, even under a linux kernel.

How is this detected?

**Comment by nikiwycherley** [comment]
![image](https://user-images.githubusercontent.com/29922309/197504637-03ac5680-4ce0-496a-9680-7fdfc28875bc.png)
Sorry forgot to add screen shot of messge

**Comment by kanongil** [comment]
Ah, the `lab -L` option. So this is really a `lab` issue.

I expect you are inadvertently using an older version, which has not been patched to whitelist those node-native globals. Or using a newer version of node, than supported for your lab version.

**Comment by nikiwycherley** [comment]
Thank you, ill add the tag and check the Lab versions against my node version

**Comment by nikiwycherley** [comment]
Just to confirm, updating hapi/lab to latest version and downgrading my node version from 18 to 16 has removed these messages. Thank you for the replies.
