### ISSUE TITLE
Server crashes due to `socketAddress` being undefined

### ISSUE THREAD

**Issue by trevrdspcdev** [hapijs/hapi#4405]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 18.12.0
* *module version with issue*: 21.0.0
* *last module version without issue*: 20.2.2
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): React 17.0.2
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

While running locally, our server occasionally crashes due to a TypeError generated from with in the Hapi library (specifically within `node_modules/@hapi/hapi/lib/request.js` as shown in the screenshot below). We're uncertain what would cause `socketAddress` to be undefined and hoping someone can provide some insight into this issue. We did not see this issue previously when using Hapi v20.2.2. It seems to have started after upgrading to v21.0.0.

![SCR-20221205-e2y](https://user-images.githubusercontent.com/19937217/205663500-2a95095c-4c36-4f55-bfdd-734bbc8ba7b5.png) 

#### What was the result you got?
Server crashes with `TypeError: Cannot read properties of undefined (reading 'startsWith')`

#### What result did you expect?
Expected the server to run without issue.

**Comment by cjihrig** [comment]
Duplicate of https://github.com/hapijs/hapi/issues/4395? Can you try upgrading to 21.1.0.

**Comment by trevrdspcdev** [comment]
> 

@cjihrig Thanks for pointing out the similar issue. Will try upgrading to 21.1.0 as you suggested.

**Comment by trevrdspcdev** [comment]
@cjihrig Upgrading to v21.1.0 appears to have fixed the undefined socketAddress TypeError so I'm closing this issue. Thank you!
