### ISSUE TITLE
server is throwing 504 gateway timeout after 1 minute 

### ISSUE THREAD

**Issue by Mohd-Farhaan** [hapijs/hapi#4410]
React.js application is hitting the Node.js api to generate the report, API is processing the client's request but in between execution api is throwing 504 error after 60 seconds of execution. seems like timeout issue

**Comment by Marsup** [comment]
It doesn't look like a hapi issue but you're not giving much details.

**Comment by devinivy** [comment]
hapi itself doesn't ever serve a gateway timeout response.  If you're using the h2o2 module for proxying, it's possible that could be serving it when the upstream service is taking too long to respond.  But most likely there's some infrastructure in between you and your hapi server that is timing-out during the course of the request and serving the 504.

**Comment by Mohd-Farhaan** [comment]
there is some time consuming database operation in an api so api needs more than a min to response back but after 60 seconds the server is throwing 504 error, how can we increase the timeout time from code.
seems like infrastructure is restricting?

**Comment by Mohd-Farhaan** [comment]
The issue was resolved, Timeout duration increased from application load balancer in AWS
