### ISSUE TITLE
[definition files] TypeScript 5.0 errors for @hapi/* imports after 21.2.0 update

### ISSUE THREAD

**Issue by peterblazejewicz** [hapijs/hapi#4418]
On DefinitelyTyped ecosystem the error has been seen for package using @hapi/hapi types (via proper versioning `^21.1.0`, that matched recent `21.2.0` update):
> Error: node_modules/@hapi/hapi/lib/types/server/server.d.ts(5,10): error TS2617: 'Mimos' can only be imported by using 'import Mimos = require("@hapi/mimos")' or by turning on the 'esModuleInterop' flag and using a default import.

`@hapi/mimos` was not updated for months. The last change related looks to be 21.2.0 release with changes to symbol exports to `@hapi/hapi` module:
https://github.com/hapijs/hapi/pull/4399/files#diff-cfc7807f6b174e1c3705c5c2747f56e49a889a52999dc96e4080a3af0131a534

Can you folks review this? I can help, if required. thanks!

**Comment by Marsup** [comment]
Are you sure you don't have DT types for mimos hanging around somewhere? Those have been integrated and changed long ago.

**Comment by peterblazejewicz** [comment]
> Are you sure you don't have DT types for mimos hanging around somewhere? Those have been integrated and changed long ago.

to put into the context, `@hapi/mimos` are hosted on DT (definitely typed) repo. The problem is in @hapi/hapi library imports when used in CJS context. To be address by #4419

**Comment by Marsup** [comment]
As also mentioned in this very PR, mimos types are now shipped with it, if you have DT types, remove them.

**Comment by peterblazejewicz** [comment]
no-op after: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64098 thansk!
