### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by dmokel** [hapijs/hapi#4424]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*:  v16.13.0
* *module version*:  8.1.0
* *environment* (e.g. node, browser, native):  node
* *used with* (e.g. hapi application, another framework, standalone, ...):  graphql-helix
* *any other relevant information*: no

#### How can we help?

```js
import { schema } from "@/api/schema";
import qs from "qs";
import { getGraphQLParameters, processRequest, Request, sendResult } from "graphql-helix";

  const server = Hapi.server({
    port: 8777,
    query: {
      parser: (query) => qs.parse(query),
    },
    routes: {
      cors: {
        origin: ["*"]
      }
    }
  });

  server.route({
    method:"POST",
    path: "/graphql",
    handler: async (req, h) => {
      const request: Request = {
        headers: req.headers,
        method: req.method,
        query: req.query,
        body: req.payload,
      };

      const { operationName, query, variables } = getGraphQLParameters(request);

      const result = await processRequest({
        request,
        schema,
        operationName,
        query,
        variables,
      });

      await sendResult(result, req.raw.res);
    }
  })

  await server.start();
  console.log(`Serve on ${server.info.uri}`);
```
I meet the err: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client,
and I think this error comes from 【await sendResult(result, req.raw.res)】, Is there any solution to solve it?

**Comment by devinivy** [comment]
If you want to take control away from the framework for delivering the response, you can return [`h.abandon`](https://hapi.dev/api/?v=21.1.0#-habandon) from the route handler 👍

**Comment by dmokel** [comment]
> If you want to take control away from the framework for delivering the response, you can return [`h.abandon`](https://hapi.dev/api/?v=21.1.0#-habandon) from the route handler 👍

cool~, you are right!!!

replace
```js
await sendResult(result, req.raw.res);
```
with
```js
sendResult(result, req.raw.res);
return h.abandon;
```
can solve the problem.
