### ISSUE TITLE
Unexpected v22.0.0 tag

### ISSUE THREAD

**Issue by kisaiev** [hapijs/hapi#4430]
#### Support plan

* *is this issue currently blocking your project?* **no**
* *is this issue affecting a production system?* **no**

#### Context

* *node version*: Not relevant 
* *module version*: Not relevant
* *environment* (e.g. node, browser, native): Not relevant
* *used with* (e.g. hapi application, another framework, standalone, ...): Not relevant
* *any other relevant information*: N/A

#### How can we help?

I noticed a [v22.0.0](https://github.com/hapijs/hapi/releases/tag/v22.0.0) tag in the repo with no proper release, e.g. nothing in a CHANGELOG.md. This is probably some kind of a failure in semantic release, ref. [v21.3.0..v22.0.0](https://github.com/hapijs/hapi/compare/v21.3.0...v22.0.0).

**Comment by devinivy** [comment]
That's right, you can ignore that tag.  No package ever went to npm or anything like that, it was just a tag pushed up to github by mistake.  Thanks!
