### ISSUE TITLE
Need help in migrating Hapi application to v20.0.1

### ISSUE THREAD

**Issue by kurr2410** [hapijs/hapi#4480]
### Runtime

Node.js

### Runtime version

v16.20.2

### Module version

^20.0.1

### Used with

Hapi application

### How can we help?

I need to migrate a hapi.js application from v16.4.3 to ^20.0.1. 
Since there are major changes made in v17.0.0 including reply() interface upgradation. Is there any optimal way to replace ```return reply()``` to ``` return reply.reponse()``` in all the handlers?

```js
//working code with  version v16.4.3(Hapi)
const addFoo = {
  description: 'add foo data',
  notes: 'add foo data',
  tags: ['api', 'FooCondition'],
  validate: {
    payload: {
      id: joi.number().required(),
    },
  },
  handler: (req, res) => {
    return maindb.subcategorymaster.findAll({
where: {'id': req.payload.id}
}).then((result) => {
      res(result);
    }).catch((DBException) => {
      res(DBException.message);
    });
  }
};

// Wanted to migrate to below code without making manual change at each and every handler.

//working code with version v20.0.1(Hapi)
const addFoo = {
  description: 'add foo data',
  notes: 'add foo data',
  tags: ['api', 'FooCondition'],
  validate: {
    payload: {
      id: joi.number().required(),
    },
  },
  handler: (req, res) => {
    return maindb.subcategorymaster.findAll({
where: {'id': req.payload.id}
}).then((result) => {
      return res.response(result);
    }).catch((DBException) => {
      return res.response(DBException.message);
    });
  }
};
```

**Comment by Nargonath** [comment]
For major releases we have detailed migration explanations in GitHub issues labelled with "Breaking changes" and "Release notes" labels. Here are the one you'll need to go through considering your starting point and the destination version:

* https://github.com/hapijs/hapi/issues/3658
* https://github.com/hapijs/hapi/issues/3871
* https://github.com/hapijs/hapi/issues/4017
* https://github.com/hapijs/hapi/issues/4138

I don't think there is an automated or quick way for you to move from v16 API to v17+ API as the move to async/await kind of impacted the way you write your handlers.

I'll close this issue but we can keep the discussion going if needed.
