### ISSUE TITLE
Handling Expect: 100-continue 

### ISSUE THREAD

**Issue by sugarnaoming** [hapijs/hapi#4487]
### Runtime

node.js

### Runtime version

18

### Module version

hapi 21

### How can we help?

I am looking to control whether or not to accept the request body when the Expect: 100-continue header is included in the request headers. I have searched through the documentation but was unable to find any mention of handling 100 continue. Is it possible to control behavior related to 100 continue in hapi.js, and if so, how can it be achieved?

**Comment by kanongil** [comment]
Yes, hapi does handle the `Expect: 100-continue` header.

Hapi will automatically send `HTTP/1.1 100 Continue` after the `onPreAuth` hook has been called and the non-payload auth has succeeded. An error from either stage should prevent it from being sent.

Does that work for you?

**Comment by sugarnaoming** [comment]
Thank you for your response.

I understand that the `onPreAuth` hook is triggered, but the control I am looking to implement is a bit more specific. I would like to reject the request body only when both of the following conditions are met:

- The `Expect: 100-continue` header is present in the request headers.
- The `Content-Length` header value is below a certain threshold.

Is there a way to check for the presence of the `Expect: 100-continue` header within an event or hook, but only under the above conditions?

**Comment by kanongil** [comment]
Yes, I suggest you add your logic to an `onPreAuth` hook. If you want to do it [at the route level](https://hapi.dev/api/?v=21.3.3#-routeoptionsext), you can do something like this (not tested):

```js
server.route({
    …,
    options: {
        ext: {
            onPreAuth: {
                method(request, h) {

                     if (request.headers.expect === '100-continue' &&
                         request.headers['content-length']
                         parseInt(request.headers['content-length']) < threshold) {

                         throw new Boom.badRequest();
                    }
                }
            }
        }
    }
```

Hapi doesn't have a public signal that there is continue pending, so I checked the header manually. Though it is probably safer to just use the internal `request._expectContinue` property.

**Comment by sugarnaoming** [comment]
Thank you very much.
I think I will be able to implement it successfully thanks to your advice.
