### ISSUE TITLE
hapi jwt package not able to recognize comma separated cookie as JWT

### ISSUE THREAD

**Issue by jassondhi** [hapijs/hapi#4498]
### Runtime

Chrome browser

### Runtime version

21.3.3

### Module version

21.3.3

### Used with

hapi jwt

### Any other relevant information

Hello,

I have a JWT being sent in a request which is being validated with a JWKS. The JWT is among a handful of cookies which are separated like this: 

oidc_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c, expiresIn=1712692506, trace_id=a932cfe4-71b8-4853-88ab-da9d7a92c7f7|2024-04-09T19:40:06.025Z

I do not have control over how the server attaches and sends the oidc_token. A cURL to my site works with semicolon-delineated cookies and fails with comma-delineated cookies. I can see that due to the other tokens, the oidc_token is not being parsed correctly, but as I am only providing a cookieName parameter to the options, I don't see a workaround. 

Is there some way for me to parse the cookie beforehand so as to only send the oidc_token or specify that the tokens are comma separated? Or would this require using another plugin in tandem with JWKS?

### How can we help?

```js
    const jwtOptions =     {
        keys: {
            uri: JWT_JWKS_ENDPOINT_URL,
            algorithms: ['RS256']
        },
        cookieName: 'oidc_token',
        validate: false,
        verify: {
            aud: false,
            iss: false,
            nbf: false,
            sub: false,
            exp: true,
            maxAgeSec: 14400, // 4 hours
            timeSkewSec: 60
        },
    }
    http.auth.strategy('my_jwt_strategy', 'jwt', jwtOptions)

    http.auth.default('my_jwt_strategy');
```

**Comment by kanongil** [comment]
Yeah, using `, ` to separate cookies is [clearly a cookie spec](https://www.rfc-editor.org/rfc/rfc6265#section-4.2.1) violation.

You can always "massage" then incoming "cookie" header in an `onRequest` extension point. Eg. `request.headers.cookie = request.headers.cookie?.replaceAll(', ', '; ')` should work fine, since `,` is not allowed to appear anywhere in a cookie header.

**Comment by jassondhi** [comment]
The onRequest suggestion worked for me - I was able to replace the commas with semicolons before processing the request and the token is being correctly pulled from the cookieName now. Agreed that it is a cookie spec violation - the contact I spoke to said that the browser (Chrome) was sending the cookies as comma-separated, and it was not in the server's control, but I don't think that's likely. Thank you for the help!
