### ISSUE TITLE
Nextjs is not supported as a server

### ISSUE THREAD

**Issue by shihuojian** [hapijs/hapi#4499]
### Runtime

node

### Runtime version

21.3.2

### Module version

21.3.2

### How can we help?

```js


const Hapi = require('@hapi/hapi');
const next = require('next')
const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })
const handle = app.getRequestHandler()
app.prepare().then(() => {
       
    const server = Hapi.server({
        port: 3000,
        host: 'localhost'
    });

    server.route({
        method: ["POST","GET"],
        path: '/api/test',
        handler: async (request, h) => {
            const {req,res} = h.request.raw;
            await handle(req,res);
            return h.close;
        }
    });


    server.start();
    console.log('> Ready on http://localhost:3000');

}).catch((ex) => {
    console.error(ex.stack)
    process.exit(1)
})
```

As above, GET can be successful, but the post request has been unresponsive. How to solve the problem? I tried experss and the post request was successful.

**Comment by devinivy** [comment]
You'll want to ensure hapi doesn't consume the request payload in that case.  Give something like this a whirl:
```js
    server.route({
        method: ["POST","GET"],
        path: '/api/test',
        options: {
            payload: {
                parse: false,
                output: 'stream'
            }
        },
        handler: async (request, h) => {
            const {req,res} = h.request.raw;
            try {
                await handle(req,res);
            } catch (err) {
                // handle err however you like, perhaps by logging
                return h.close
            }
            return h.abandon;
        }
    });
```

**Comment by shihuojian** [comment]
> 在这种情况下，您需要确保 hapi 不会消耗请求负载。尝试一下这样的事情：
> 
> ```js
>     server.route({
>         method: ["POST","GET"],
>         path: '/api/test',
>         options: {
>             payload: {
>                 parse: false,
>                 output: 'stream'
>             }
>         },
>         handler: async (request, h) => {
>             const {req,res} = h.request.raw;
>             try {
>                 await handle(req,res);
>             } catch (err) {
>                 // handle err however you like, perhaps by logging
>                 return h.close
>             }
>             return h.abandon;
>         }
>     });
> ```

Thank you very much, this is very helpful to me
