### ISSUE TITLE
Types for route.options.payload.multipart don't allow `true`

### ISSUE THREAD

**Issue by otajor** [hapijs/hapi#4504]
### Runtime

node.js

### Runtime version

18.18

### Module version

21.3.3

### Used with

Hapi application

### Any other relevant information

The [docs for `route.options.payload.multipart` ](https://hapi.dev/api/?v=21.3.3#-routeoptionspayloadmultipart) say that `true` should be a valid option:
<img width="583" alt="image" src="https://github.com/hapijs/hapi/assets/13705650/7e8268d5-4bee-4388-b4d6-c3163021865e">

But the types file (`lib/types/route.d.ts`) does not allow this and flags it as an error:

<img width="678" alt="image" src="https://github.com/hapijs/hapi/assets/13705650/6834587e-e778-4d15-992e-782689e5f54a">

The JS code (`lib/config.js` seems to agree with the docs, so I think the types file is wrong. 

<img width="715" alt="image" src="https://github.com/hapijs/hapi/assets/13705650/3b18cbe0-a863-436b-ac39-c64560e6df0d">

Can someone confirm what the correct type and usage here should be?

### What are you trying to achieve or the steps to reproduce?

Make a route with `route.options.payload.multipart` set to true. E.g.
```
payload: {
        maxBytes: 209715200,
        output: 'stream',
        parse: true,
        allow: 'multipart/form-data',
        multipart: true,
      },
```

### What was the result you got?

Typescript error: `Type 'true' is not assignable to type 'false | { output: PayloadOutput | "annotated"; } | undefined'`

### What result did you expect?

`true` should be an accepted value.

**Comment by damusix** [comment]
@otajor fixed in #4507
