### ISSUE TITLE
Problema con retiros de fondos

### ISSUE THREAD

**Issue by Mapexvenge** [hapijs/hapi#4509]
### Runtime

Hapi

### Runtime version

30:00 minutos 

### Module version

Problema

### Last module version without issue

No puedo 

### Used with

Hapi 

### Any other relevant information

No puedo retirar los fondos de hapi y lo e intentando mucho soy de Colombia 

### What are you trying to achieve or the steps to reproduce?

Hola,me llamo Julián y e intentando mucho retirar mis fondos de la cuenta pero no me deja lo e echo por el modelo de nequi que hay acá en Colombia pero no me deja después de un un día dice erro de datos y luego cuando los envío siempre dice error de internet y compruebe su conexión 😕 pero mi internet está bien. Entonces no sé qué hacer ahora por eso me comunico aquí haber que se hace como puedo retirarlos de verdad espero que me ayuden ya hice todos los pasos y no se puede en tonces? Hiba a retirar 29 dólares y no deja.

Espero su colaboración con este problema gracias 

### What was the result you got?

No puedo retirar.

### What result did you expect?

Retirar mis fondos

**Comment by damusix** [comment]
Hola @Mapexvenge , de que se esta refiriendo usted? Hapi no tiene nada que ver con retiro de fondos o tenencias de dinero. Voy a cerrar esta dicusion porque creo que fuy hecha erroneamente. Si nos comentas algun detalle mas especifico relacionado con este proyecto Open Source, o la organizacion de Open Source que es Hapi, lo podriamos ayudar. Gracias!
