### ISSUE TITLE
Getting response as Null in POST API calls Node 18.19.1 hapi - 19.0.2

### ISSUE THREAD

**Issue by husain-amjhera** [hapijs/hapi#4534]
### Runtime

Node

### Runtime version

18.19.1

### Module version

19.0.2

### How can we help?

in node modules @hapi/hapi/lib/ request.js file 

in _finalize() method receiving response as null

![image](https://github.com/user-attachments/assets/28ab8946-eee8-48a6-9645-e197d20bbe30)

**Comment by damusix** [comment]
@husain-amjhera Need some code to replicate. This doesn't happen during tests, which do run on windows.

Can you make sure there's not a request cancellation on your end that's causing the response to close suddenly? See if your client isn't aborting.

Also, can you make sure there are no plugins or lifecycle methods are modifying internals?

**Comment by Marsup** [comment]
Sorry but we do not support version 19 anymore, you'll need to upgrade.

Also, the report seems incoherent with the release you mentioned. There's nothing on L492, and the closest statusCode check on L482 cannot fail.

**Comment by husain-amjhera** [comment]
I upgraded to latest (21.3.12) its not giving any problem now. Thanks
