### ISSUE TITLE
Request Throttling/Debouncing

### ISSUE THREAD

**Issue by thegoleffect** [hapijs/hapi#584]
http://drupalmotion.com/article/debounce-and-throttle-visual-explanation

Debouncing:  All identical/similar requests made to a single endpoint/URL during a period of n seconds => count as one.

Throttling: At most, m requests can occur in n seconds.

**Neither n nor m need be integers.**

---

This is useful if you have a URL that shouldn't be called more than once in quick succession (like a payment URL). Or when you have a URL that must spend a long time processing (not in a background job) and don't want to overload the machine with too many requests.

**Comment by kellyrmilligan** [comment]
Was there ever a plug-in for this published that is recommended?

**Comment by corbinu** [comment]
I would recommend using a proxy for this (nginx, HAProxy, Caddy, node-http-proxy
 etc)
