### ISSUE TITLE
QUESTION: Calling internal routes.

### ISSUE THREAD

**Issue by scottcorgan** [hapijs/hapi#586]
We love the batch routes reature of Hapi, but we are curious if there is (or will be) a way to call internal routes. Seems like an awesome way to create abstraction without having to make http requests to your own server.

Thanks!

**Comment by camerow** [comment]
All these examples 404, could someone post a new link please? =)

**Comment by gergoerdosi** [comment]
Here is the new location of the link mentioned above:
http://hapijs.com/api#serverinjectoptions-callback

You may find this useful too:
https://www.youtube.com/watch?v=ppK47d2Uta4

**Comment by camerow** [comment]
Thank you @gergoerdosi =)

**Comment by khullah** [comment]
changed again, to https://hapijs.com/api#-await-serverinjectoptions

**Comment by c990802** [comment]
Link as of August 2019:  https://hapi.dev/api/?v=18.3.1#server.inject()

**Comment by bernardoadc** [comment]
that's a lot of changes

**Comment by blex41** [comment]
As of January 2020: https://hapi.dev/api/?v=19.0.4#-await-serverinjectoptions

**Comment by ruthearle** [comment]
As of Feb 2020, v19.10: https://hapi.dev/api/?v=19.1.0#-await-serverinjectoptions

**Comment by hueniverse** [comment]
We're working on fixing the links issue...

**Comment by warao-gil** [comment]
haha that's fun.
