### ISSUE TITLE
proxy with mapUri, example

### ISSUE THREAD

**Issue by gregtzar** [hapijs/hapi#599]
Would it be possible to provide an example of using the proxy handler with mapUri? I am trying to implement a /proxy route which performs a simple forward proxy to the url querystring which gets passed to the route. I thought that mapUri would do this, but am left guessing at how it works, and what the method signature is (I just didn't have time to dig into the source today but will try that tomorrow). I must be using it wrong because the literal value for the url querystring is getting returned to the client.

Example server:

```
var port = 9090,
    Hapi = require('hapi'),
    server = new Hapi.Server('localhost', port);

server.route({
    method: "GET",
    path: "/proxy",
    handler: {
        proxy: {
            mapUri: function(req, cb) {
                cb(req.query.url);
            }
        }
    }
});

server.start();
```

Example request:

```
GET http://localhost:9090/proxy?url=http://www.google.com
```

Example response:

```
http://www.google.com
```

Expected response:

```
[google homepage]
```

**Comment by maimike** [comment]
This example no longer works. Got error cb is not a function even i use cb(null, req.query.url);
