### ISSUE TITLE
Setting charset to UTF-8

### ISSUE THREAD

**Issue by stiang** [hapijs/hapi#621]
Is there an easy way to set the charset to UTF-8, preferably globally? I can’t imagine that this is the proper way to do it:

``` js
var res = request.reply.payload(data); // json data
res._headers['Content-Type'] = 'application/json; charset=utf-8';
res.send();
```

This works, but seems awfully convoluted for such a basic operation.

Incidentally, I had charset issues with restify too - the charSet property of the response object had been removed from the code (but not from the docs), and it didn’t seem to be particularly missed by anyone else. 

Doesn’t it make sense to use UTF-8 by default for json responses these days? Isn’t that the de-facto standard for APIs?

**Comment by hoanghiep** [comment]
Hello @hueniverse 
How i response state (base64json) with utf-8
In server my text is fullname: 'Ầ Ế'. But in client this text is "fullname":"� �"?
