### ISSUE TITLE
Parsing the request form-encoded payload using qs

### ISSUE THREAD

**Issue by aktang** [hapijs/hapi#637]
Previously, when using connect and posting these type of params in the form body:

bindings[msg]:Hi
bindings[name]:Walmart
bindings[symbols][key]:blah

This will actually create a bindings object:

bindings = {
   "msg": "Hi",
   "name": "Walmart",
   "symbols": {
      "key": "blah"
   }
}

but in Hapi, it returns those three parameters literally:

"bindings[msg]" = "Hi"
etc...

It looks like connect uses qs, which will parse this into objects.  Is this something that can be internalized into hapi, or are we expected to parse the rawBody ourselves if needed this way?

**Comment by ralexrdz** [comment]
I don't see the solution to this? is there a library we could use? 

I would like to get also some kind of object that could be sent to MongoDB without a problem
