### ISSUE TITLE
CORS headers need to override proxy CORS headers

### ISSUE THREAD

**Issue by kpdecker** [hapijs/hapi#681]
Access-Control-Allow-Origin: http://m-origin.pgroceries-qa3.asda.com
Access-Control-Max-Age: 86400
Access-Control-Allow-Methods: GET, HEAD, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Headers: Authorization, Content-Type, If-None-Match
Access-Control-Allow-Credentials: true
x-mashery-responder: mashery-web1-atl.mashery.com
access-control-allow-headers: X-Requested-With, Content-Type
access-control-allow-methods: OPTIONS, GET, POST, PUT
access-control-allow-credentials: true

**Comment by nelsonic** [comment]
@kpdecker did you mean to expose your QA server on github...? :confused:
