### ISSUE TITLE
Hawk's timestamp using Hapi

### ISSUE THREAD

**Issue by MathieuLoutre** [hapijs/hapi#705]
I have a Hapi server using the Hawk auth scheme and everything works brilliantly on the server side.
I'm now doing the client side part of the job and as outlined in the Hawk documentation I can't really get an NTP server running. I was hoping to rely on this part of the documentation:
"the server provides the client with its current time in response to a bad timestamp"
to get an up to date timestamp and do the time difference locally.

On a test request with a very stale timestamp (0), Hapi is only sending me back a 401 saying "stale timestamp" which is very true, but no sign of a fresh timestamp.

{"code":401,"error":"Unauthorized","message":"Stale timestamp"}

I don't know if the problem is coming from Hawk or Hapi, but I assumed Hapi just didn't include the new timestamp. Or is it up to me to send the fresh timestamp along?

**Comment by srikantpandey** [comment]
i am getting this message on postman after providing hawk auth
{
"error": {
"message": "API key is not valid. Request authorization failed. Stale timestamp"
}
}
