### ISSUE TITLE
Question: Getting IP of request

### ISSUE THREAD

**Issue by cbebry** [hapijs/hapi#777]
I've been using hapi and so far it's been an awesome server framework!
One feature I've been trying to find is being able to get the IP of the request made. The purpose in which we'd use this sort of feature is to be able to track some statistical data about usage of the API on a per-IP basis.

I looked through the available documentation pretty thoroughly -- if the feature exists, it's not documented yet (and I understand there may very well be a good reason why you guys haven't documented it yet if it exists).

Simply enough, my question is:
Is there a way to be able to grab the IP address from the request? If so, how?

Thanks!

**Comment by gauravvgat** [comment]
I tried using request.info.address, but I get a null. I also tried using request.info.remoteAddress. Now the weird issue is that all the ip's logged started with 172.31.x.x. How is it possible?

**Comment by geek** [comment]
@gauravvgat in hapi 8 use the `info.remoteAddress` and `info.remotePort`.  Both values come from the socket address and port: https://github.com/joyent/node/blob/master/lib/net.js#L555-L579

http://nodejs.org/api/net.html#net_socket_remoteaddress

**Comment by mr-e-** [comment]
Could this be used somehow to authenticate an API call? I have a particular API call which should be allowed from only one other machine, how secure is it to check this IP address before returning a result? Can it be spoofed somehow?

**Comment by PierBover** [comment]
@mr-e- the IP can be spoofed but you could authenticate using a key in a header and using `https`.
