### ISSUE TITLE
Https redirection

### ISSUE THREAD

**Issue by jozzhart** [hapijs/hapi#778]
Hello,

I'm using nodejitsu to host my app and I need to redirect all http requests to https at the server level.

https://www.nodejitsu.com/documentation/a-quickstart/faq/#how-do-i-force-my-clients-to-use-https-with-my-application

I'm not quire sure how to do this using hapi.  I believe I should use the "onReqest' extension, but that only provides setUrl and setMethod methods.  I need to force a redirect at this stage.

Can you please advise the best way to achieve this.

Thanks,
Jozz

**Comment by kristiankeane** [comment]
@carlo-m Did you ever find a solution to redirecting HTTP to HTTPS using a single port? I'm experiencing the exact same issue you described.

@bendrucker @chmanie  I'm using code almost exactly like the examples on this page and the plugin - It works fine for a HTTPS request but the browser just hangs for a HTTP request - any ideas what I'm doing wrong? If you set up TLS on the connection maybe it ignores HTTP requests?

```
server.connection({
    port: 3000,
    host: localhost,
    tls: {
        key: fs.readFileSync(__dirname + '/tls/server.key', 'utf8'),
        cert: fs.readFileSync(__dirname + '/tls/server.crt', 'utf8')
    }
});

server.ext('onRequest', function (request, reply) {
    if (request.headers['x-forwarded-proto'] === 'http') {
        console.log('redirect to https');
        return reply().redirect('https://' + request.headers.host + request.url.path).code(301);
    }
    console.log('NO redirect');
    return reply.continue();
});

https://localhost:3000 // works fine
http://localhost:3000 // browser hangs, waiting for localhost
```

**Comment by chmanie** [comment]
@kristiankeane which version of hapi are you using?

**Comment by AdriVanHoudt** [comment]
@chmanie I think @kristiankeane solved it with help from the gitter

**Comment by athlite** [comment]
### Usecase Hapi + Glue + Docker. 

I made a rather elaborate example, to connect the dots, useful for noobs ;-)

You can make an entry in manifest.js, ie.:
```
if (process.env.NODE_ENV === 'production') {
    tls.key  = Fs.readFileSync('/letsencrypt/etc/live/example.com/privkey.pem','utf8');
    tls.cert = Fs.readFileSync('/letsencrypt/etc/live/example.com/cert.pem','utf8');
}
...
connections: [{
    host: {
        $filter: 'env',
        production: '0.0.0.0',
        $default: 'localhost'
     },
     port: 3000,
     tls: {
         $filter: 'env',
         production: {
             key: tls.key,
             cert: tls.cert
         },
         $default: undefined
    },
    labels: ['api']
}, {
    port: 3001,
    labels: ['https-redirect']
}]
```
Register the plugin(https-redirect):
```
plugin: {
    register: './plugins/https-redirect',
    options: {
        select: ['https-redirect'],
        method: '*',
        path: '/{path*}',
        uri: {
            $filter: 'env',
             production: 'https://production.example.com',
             $default: 'http://localhost:3000'
        }
    }
}
```
Write the plugin(https-redirect):
```
exports.register = function (servers, options, next) {

    const server = servers.select(options.select);
    /* Assumption: you already made sure your regular routes 
    * are not written to 3001-server
    */
    server.route({
        method: options.method,
        path: options.path,
        handler: (request,reply) => {
            
            reply.redirect(options.uri + request.path);
        }
    });
    next();
};

exports.register.attributes = {
    name: 'https-redirect',
    version: '0.0.1'
};
```
Docker run:
```
// 'letsencrypt' is a volume with pre-made certificates that is mounted in container
docker run -it -d -p 443:3000 -p 80:3001 -v letsencrypt:/letsencrypt app-image
```

**Comment by captainjackrana** [comment]
I've created a simple hapi plugin for easy https redirections. You can find it here:
https://github.com/captainjackrana/hapi-gate
