### ISSUE TITLE
Catch all route to hook node with Angular

### ISSUE THREAD

**Issue by lefos987** [hapijs/hapi#800]
Hi.
I am trying to connect an Angular app to a hapi node server. 
My routes in hapi are of two kind: 
1. /api/xxxxx - for the api routes that I use to respond to the client
2. anything else should just reply with the index.html page, in order for angular to take care of the front end routing.

I have created the following route which I was hoping that will render index html for all the routes (including the localhost ( / ) ).

``` javascript
var indexRoute = {
    method: 'GET',
    path: '/{path*}',
    config: handler: {
        directory: { path: './app', listing: false, index: true }
    }
};
```

 It seems to work fine when I have the html5 mode of Angular disabled (so I am using normal hashbang URLs). When I turn this on, any route apart from the localhost returns with a 404, instead of rendering the index.html page. It seems that any URL (eg. localhost:8080/testUrl ) is not being handled by the indexRoute specified above.

Any ideas on how to solve this issue? Am I doing something wrong in the route?

Thank you very much and keep up the great work.

**Comment by monolithed** [comment]
```
Fatal error: Hapi ["/www/server.js"] -  Error: New route /{path*} conflicts with existing /{path*}
```

What does it mean?

**Comment by hueniverse** [comment]
That you have two catch alls

**Comment by djensen47** [comment]
After reading the [inert documentation](https://github.com/hapijs/inert#customized-file-response), I solved this single-page app "issue" as follows:

```javascript
// Static Assets
server.route({
  method: 'GET',
  path: '/{param*}',
  handler: {
    directory: {
      path: ['app/static'],
      listing: false,
      index: ['index.html']
    }
  }
});

// return index.html for everything else
server.ext('onPostHandler', (request, reply) => {
  console.log('WORD');
  const response = request.response;
  if (response.isBoom && response.output.statusCode === 404) {
    return reply.file('app/static/index.html');
  }
  return reply.continue();
});
``` 

I hope this helps somebody along the way.
