### ISSUE TITLE
Stage based configuration

### ISSUE THREAD

**Issue by dypsilon** [hapijs/hapi#806]
I would like to be able to feed the composer with different configuration options according to the current environment. This "issue" is a suggestion how it might look.

**NODE_ENV**
Allow to control which environment is used with the NODE_ENV variable.

**Formats**
Support different formats. Maybe use nconf for heavy lifting.

**Configuration Files**
The default configuration should be in a file with .defaults.{format} ending, for example: manifest.defaults.json

Env specific configuration should be in a file with .{env}.{format}, example: manifest.development.json or manifest.production.json or manifest.test.json

**Hierarchical Configuration**
Support nconf style hierarchical configuration: https://github.com/flatiron/nconf#hierarchical-configuration with the following levels:
1. argv
2. env
3. manifest.{env}.{format}
4. manifest.defaults.{format}

**Nesting**
Nesting configuration objects should be supported. Example:

_manifest.defaults.json_

```
servers: [
        {
            port: 8000,
            options: {
                labels: ['web']
            }
        },
        {
            host: 'localhost',
            port: 8001,
            options: {
                labels: ['admin']
            }
        }
]
```

_manifest.production.json_

```
servers: [
        {
            port: 80
        }
]
```

_result in the production environment_

```
servers: [
        {
            port: 80,
            options: {
                labels: ['web']
            }
        },
        {
            host: 'localhost',
            port: 8001,
            options: {
                labels: ['admin']
            }
        }
]
```

**Comment by khullah** [comment]
@dypsilon do you have the gist link? Was there a discussion about this?

**Comment by devinivy** [comment]
We achieve this through a [glue](https://github.com/hapijs/glue) manifest in the form of a [confidence](https://github.com/hapijs/confidence) document with that uses [dotenv](https://github.com/motdotla/dotenv) to fill-out the environment.

See https://github.com/hapipal/boilerplate/blob/pal/server/manifest.js

**Comment by dypsilon** [comment]
The world changed quite a bit in those five years :) I moved on to 12 factor apps using docker.
