### ISSUE TITLE
Support standard error format

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#855]
Consider adding support for http://tools.ietf.org/html/draft-nottingham-http-problem-03 to make @mnot happy.

**Comment by mnot** [comment]
@hueniverse FYI: http://mailarchive.ietf.org/arch/msg/ietf-announce/6FYYkiT1-_70jqrj83nwmSFYooY

**Comment by hueniverse** [comment]
Only three years for a standard of this complexity?! :-P

Would consider making this an opt-in feature at some point.

**Comment by hueniverse** [comment]
Going to close it. If someone requests this feature we can revisit.
